### ISSUE TITLE
Crashes on visting home page and zeroboard

### ISSUE THREAD

**Issue by thesoftwarejedi** [HelloZeroNet/ZeroNet#1]
Ran for a while - I browsed some site someone made with images. Suddenly crashed after attempting to post a message. Continues to crash when started. Rolled back entire git repo and started from scratch - continued to crash on load of inital home.

screen: http://gyazo.com/f6e26573a4e8ffd72c738f9ac95a9633

I wish I knew more about the python environment or I'd dig in and trace the stack and debug. Beginning to think whatever I posted as a message is what crashed it.

Visiting these causes crash:
http://127.0.0.1:43110/1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp
http://127.0.0.1:43110/1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr
http://127.0.0.1:43110/16tAyA58u8AiZMMu6tcsCYaM8KXWXMhiaJ

This works:
http://127.0.0.1:43110/1Jr5bnqSnnp94CfC7xrqPh4yYYDRkpzozD/

I'll leave it up overnight to continue seeding.

**Comment by shakna-israel** [comment]
What's the output of:

```
pip freeze
```

My experience with kernelbase failures is conflicting packages, after being called.

**Comment by thesoftwarejedi** [comment]
This has not happened since day-0.  Closing ticket.
