### ISSUE TITLE
content.json download failed

### ISSUE THREAD

**Issue by dydx** [HelloZeroNet/ZeroNet#10]
I'm having a slight problem with trying to add a site, I feel like its due to user error on my part, but nevertheless I'd like to get it working

I've done this in a directory `/home/dydx/Development/zeronet-sites/dydx`  which contains `index.html` and `style.css`

````
➜  dydx  python /home/dydx/Development/github/ZeroNet/zeronet.py siteCreate
- Generating new privatekey...
- -----------------------------------------------------------
- Site private key: [removed for sake of posting to github issues] (save it, required to modify the site)
- Site address: 1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb
- -----------------------------------------------------------
- Creating directory structure...
- Creating content.json...
Site:1GXtHR..wWhb Site not exits yet, loading default content.json values...
Site:1GXtHR..wWhb Opening site data directory: data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb...
Site:1GXtHR..wWhb - data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb/index.html (SHA1: 4065b2b27a289cba476a7ffbce11681cbcc9f6f9)
Site:1GXtHR..wWhb Adding timestamp and sha1sums to new content.json...
Site:1GXtHR..wWhb Verifying private key...
Site:1GXtHR..wWhb Signing modified content.json...
Site:1GXtHR..wWhb Saving to data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb/content.json...
Site:1GXtHR..wWhb Site signed!
- Site created!
````

Everything looks good. I try to visit `http://127.0.0.1/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb` and get a message saying there were no peers found, which I suppose is correct given that no one has visited/seeded the page besides me

I post on the message board about trying to see if it works, and a user replied with this:

````
> Gives me hash failed, try to use siteSign command again
````

I suppose thats sort of odd, but I try the siteSign command and get notified that it succeeded:

````
➜  dydx  python /home/dydx/Development/github/ZeroNet/zeronet.py siteSign 1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb                    
- Signing site: 1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb...
Private key (input hidden):
Site:1GXtHR..wWhb Opening site data directory: data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb...
Site:1GXtHR..wWhb - [SKIPPED] data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb/content.json
Site:1GXtHR..wWhb - data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb/index.html (SHA1: 4065b2b27a289cba476a7ffbce11681cbcc9f6f9)
Site:1GXtHR..wWhb Adding timestamp and sha1sums to new content.json...
Site:1GXtHR..wWhb Verifying private key...
Site:1GXtHR..wWhb Signing modified content.json...
Site:1GXtHR..wWhb Saving to data/1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb/content.json...
Site:1GXtHR..wWhb Site signed!
````

I go to check the URL once more and see that I have 3 peers! But, it never seems to load. I get a message saying that `content.json download failed`

Do I just need to wait for more seeds to propagate, or is there an error in my setup somewhere?

**Comment by HelloZeroNet** [comment]
Try this please:
- Stop zeronet
- Edit data/sites.json and set "own": true at your site
- Use siteSign 
- Then start zeronet.py again. 
in next release the "own" flag will be true on newly created sites

**Comment by dydx** [comment]
Heya,

I got it to work reasonably (I can view the site I put up now), though it says on the ZeroHello page that the update failed.

Also, I see this in the terminal output:

````
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
WorkerManager:1GXtHR..wWhb [peer ip addr]:15441: Hash failed: content.json
````

I'd assume this might because their version of my site is older than my version? If they visited my page again, would they begin seeding the 'working' version of it?

**Comment by HelloZeroNet** [comment]
I can access your site, looks nice :)
I think the Hash failed problem is because someone has older version of content.json than yours. 
You should run `zeronet.py sitePublish 1GXtHRoh7495zJYLthQ8xPt2dRzm8DwWhb` so he will get the updated file

**Comment by dydx** [comment]
Ohhhhh. Sweet. I'll close this since I think I've basically figured out it what was wrong.
