### ISSUE TITLE
How to hide the tray icon on Windows ?

### ISSUE THREAD

**Issue by WaichangChan** [HelloZeroNet/ZeroNet#1000]
Hello every one. I want to start zeronet sliently. Is there any way to hide the tray icon ?

**Comment by mkg20001** [comment]
just rename plugins/Trayicon to plugins/disabled-Trayicon

**Comment by WaichangChan** [comment]
@mkg20001 Thank you so much.   
Buy the way, is there any document for plugin developing ?   
I have read the official document but not thing found. @HelloZeroNet
