### ISSUE TITLE
ARM zeronet

### ISSUE THREAD

**Issue by OHLIA** [HelloZeroNet/ZeroNet#1001]
I wish there have ARM version zeronet can be use on my Router.

**Comment by skwerlman** [comment]
zeronet is written in python, so as long as you can find python for ARM, you can run zeronet on ARM. Just take care to make sure zeronet isn't available from outside your network

**Comment by OHLIA** [comment]
python Zeronet.sh

prompt:  
File "ZeroNet.sh", line 2
    cd "$(dirname "$0")"
                  ^
SyntaxError: invalid syntax

**Comment by grez911** [comment]
@OHLIA @HelloZeroNet Closing?
