### ISSUE TITLE
where is data file in MacOS?

### ISSUE THREAD

**Issue by ellicefix** [HelloZeroNet/ZeroNet#1002]
I can find it

**Comment by ellicefix** [comment]
./Library/Application Support/ZeroNet/data
What a fuck!

**Comment by HelloZeroNet** [comment]
If you place ZeroNet.app in application directory then ./Library/Application Support/ZeroNet/data
If you running it from other directory, then it saves the data in the same directory

**Comment by skwerlman** [comment]
imo, it'd be nice if there were a way for the user to discover this path through the ui

**Comment by ellicefix** [comment]
IN sierra，this is the only path
