### ISSUE TITLE
Strikethrough 'File transactions are not compressed' in README?

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1004]
With the ability to compress files with zip and 7zip now, should [this line](https://github.com/HelloZeroNet/ZeroNet/blame/master/README.md#L152) be removed or is compression not entirely implemented yet?

**Comment by MuxZeroNet** [comment]
Some files are saved in compressed form on the disk, but are not gzipped over the cable.

**Comment by anoadragon453** [comment]
Ah ok, good to know thanks.
