### ISSUE TITLE
Do you consider supporting Mathjax?

### ISSUE THREAD

**Issue by ellicefix** [HelloZeroNet/ZeroNet#1005]
If I want to enter the math formula with Latex syntax, I don't seem to be able to do it at the moment. Because you don't support Mathjax, can you consider supporting Mathjax? It's very important for taking mathematical notes

**Comment by skwerlman** [comment]
MathJax is a regular javascript library, so if you're writing your own zite you can just include it with the zite: http://docs.mathjax.org/en/latest/start.html#installing-your-own-copy-of-mathjax

Don't include it using a CDN, though, even though it's recommended by the docs.

**Comment by ellicefix** [comment]
Thank you. I'm trying. I didn't expect Mathjax's full library file to be so big. Anyway, I'm looking forward to your formal support for Mathjax, which is more friendly to most students or teachers at school.

**Comment by grez911** [comment]
Not related to the zeronet core.
@ellicefix @HelloZeroNet Please, close.
