### ISSUE TITLE
[Bug] Creating a new data folder from scratch

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#1007]
**Operating system**: Windows 7 SP1 x64 (but I believe it also happens in other OS)

**Steps to reproduce**:

1. Use terminal and open `zeronet.py` with the `debug` flag;
2. Create or import a profile and use ZeroID+other social sites of ZeroNet;
3. Close ZeroNet;
4. Re-open ZeroNet, yet using the `debug` flag;
5. You will see that all the data was "reseted".

The data is "reseted" because ZeroNet then creates a `data` folder inside the `core` folder and sets it as default.
A current solution for it is moving all data from the older folder to the new, then restart ZeroNet.

**Comment by Plasmmer** [comment]
The reverse also occurs:

1. Open ZeroNet normally;
2. See that your data from debug mode is working in the sites (folder: core/data);
3. Close ZeroNet;
4. Re-open ZeroNet;
5. You will see that all the data was "reseted" (now under the normal data folder).

**Comment by Plasmmer** [comment]
@shortcutme

**Comment by Plasmmer** [comment]
@shortcutme
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I think I was able to fix this issue by https://github.com/HelloZeroNet/ZeroNet/commit/c8f37674c6f3c324614e77f66227b65a36545f54
Please verify if this fix worked for you.

**Comment by Plasmmer** [comment]
The bug is now fixed. Thanks!

**Comment by Plasmmer** [comment]
@shortcutme

> Thanks for reporting

Thanks? Where my name in the page of the update 0.5.7 in the ZeroNet's blog and other media where possibly this update was announced by you?
