### ISSUE TITLE
Cannot sign files with parentheses or square brackets

### ISSUE THREAD

**Issue by glaubermmferreira** [HelloZeroNet/ZeroNet#1008]
Apparently it isn't possible to sign files whose names contain parentheses or square brackets with the _siteSign_ command, even through they are printable ASCII characters.

**Comment by HelloZeroNet** [comment]
Right now only files matching `"^[a-zA-Z0-9_@=\.\+\-/]+$` supported. It could be possible to add more characters.

**Comment by anoadragon453** [comment]
@HelloZeroNet square brackets and parenthesis are fairly common in file/folder names. I'd suggest added them to the list.

I also remember having to deal with renaming files with parenthesis when I was mirroring a site on ZeroNet, would be nice if that wasn't required :)

**Comment by HelloZeroNet** [comment]
Filenames `^[a-z\[\]\(\) A-Z0-9_@=\.\+-/]*$` allowed now: https://github.com/HelloZeroNet/ZeroNet/commit/96a097e33df3d24aa261bd41cf4f3a8ec5cf95ae
