### ISSUE TITLE
Can't run zeronet.py

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#1009]
I already did:
`pip install gevent msgpack-python`

Then I receive in the command prompt:

> - Starting ZeroNet...
> ERROR:root:Unhandled exception: No module named gevent
> Traceback (most recent call last):
>   File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.
> 
>     import main
>   File "C:\Programs\Programs\ZeroNet-win-dist\core\src\main
> ule>
>     import gevent
> ImportError: No module named gevent
> Traceback (most recent call last):
>   File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.
> ule>
>     main()
>   File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.
> 
>     traceback.print_exc(file=open(config.log_dir + "/error.
> AttributeError: 'Config' object has no attribute 'log_dir'

**Comment by HelloZeroNet** [comment]
maybe you have multiple python installed on your computer and the pip command points to an another.
try `python -m pip install gevent msgpack-python`
you can verify the installation by entering `python` then `import gevent`

**Comment by Plasmmer** [comment]
I has only Python 2.7.3, but the commands not worked in the command prompt, then I installed Python 3.6.1, and the installation had worked. But in ZeroNet it isn't working because ZN needs the Python 2.7.3, then gevent is only installed in 3.6.1 but not in 2.7.3. Any manner to do commands for 2.7.3 only?

**Comment by Plasmmer** [comment]
@HelloZeroNet
Its because Python 2.7 doesn't supports the PATH and PYTHONPATH. I suggest ZeroNet to update to the latest Python version.

**Comment by skwerlman** [comment]
you can try `pip2` instead of `pip` to force it to use python2

**Comment by Plasmmer** [comment]
> 'pip2' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by Plasmmer** [comment]
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
to run command-line actions under windows you can also use `lib\zeronet.cmd`.
If you don't have python added to your path, then `C:\Python27\python.exe -m pip install gevent msgpack` should work.
Python2 and Python3 is not compatible with each other, so porting it would require more work. Moving to py3 planned later. (probably next year)

**Comment by Plasmmer** [comment]
```
C:\Windows\System32>C:\Python27\python.exe
C:\Python27\python.exe: No module named pip
```

```
C:\Windows\System32>C:\Python27\python.exe -m pip install gevent msgpack
Downloading/unpacking gevent
  Running setup.py (path:c:\users\world.wd\appdata\local\temp\pip_build_World.w
\gevent\setup.py) egg_info for package gevent
    C:\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution op
ion: 'cffi_modules'
      warnings.warn(msg)
    warning: no files found matching 'changelog.rst'
    warning: no files found matching 'known_failures.py'
    warning: no files found matching '.pep8'
    no previously-included directories found matching '*\__pycache__'
    warning: no previously-included files matching '*.so' found anywhere in dis
ribution
    warning: no previously-included files matching '*.o' found anywhere in dist
ibution
    warning: no previously-included files matching '*.lo' found anywhere in dis
ribution
    warning: no previously-included files matching '*.la' found anywhere in dis
ribution
    warning: no previously-included files matching 'config.log' found anywhere
n distribution
    warning: no previously-included files matching 'config.status' found anywhe
e in distribution
    no previously-included directories found matching 'doc\_build'
    warning: no previously-included files matching '*.pyc' found anywhere in di
tribution
    warning: no previously-included files matching '.coverage' found under dire
tory 'src\greentest'
    no previously-included directories found matching 'src\greentest\htmlcov'
    warning: no previously-included files matching 'stamp-h?' found under direc
ory 'deps\c-ares'
    warning: no previously-included files matching 'ares_build.h.orig' found un
er directory 'deps\c-ares'
    no previously-included directories found matching 'deps\libev\.deps'
    warning: no previously-included files matching 'Makefile' found under direc
ory 'deps\libev'
    warning: no previously-included files matching 'libtool' found under direct
ry 'deps\libev'
    warning: no previously-included files matching 'stamp-h?' found under direc
ory 'deps\libev'
    warning: no previously-included files matching 'config.h' found under direc
ory 'deps\libev'
    warning: no previously-included files matching '_corecffi.c' found under di
ectory 'src\gevent'
    warning: no previously-included files found matching 'Makefile'
    warning: no previously-included files found matching 'configure-output'
Downloading/unpacking msgpack
  Could not find any downloads that satisfy the requirement msgpack
Cleaning up...
No distributions at all found for msgpack
Storing debug log for failure in c:\users\world.wd\appdata\local\temp\tmppmsv6s
```

```
C:\Windows\System32>C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.py --debu
g
- Starting ZeroNet...
ERROR:root:Unhandled exception: No module named gevent
Traceback (most recent call last):
  File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.py", line 18, in main

    import main
  File "C:\Programs\Programs\ZeroNet-win-dist\core\src\main.py", line 9, in <mod
ule>
    import gevent
ImportError: No module named gevent
Traceback (most recent call last):
  File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.py", line 91, in <mod
ule>
    main()
  File "C:\Programs\Programs\ZeroNet-win-dist\core\zeronet.py", line 64, in main

    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
AttributeError: 'Config' object has no attribute 'log_dir'
```

**Comment by HelloZeroNet** [comment]
try install msgpack-python & run it using C:\Python27\python.exe zeronet.py

**Comment by Plasmmer** [comment]
Whats the recommended Python version to use?

**Comment by HelloZeroNet** [comment]
the latest 2.7.x

**Comment by Plasmmer** [comment]
@HelloZeroNet

I'm in 2.7.9 and gevent with greenlet is successfully installed.
But in this last step (msgpack) I'm getting this:

```
C:\Windows\System32>C:\Python27\python.exe -m pip install msgpack
Collecting msgpack
  Could not find a version that satisfies the requirement msgpack (from versions
: )
No matching distribution found for msgpack
```

I only need to pass this to start developing my projects in ZeroNet with the `--debug` mode and to say you if the bug https://github.com/HelloZeroNet/ZeroNet/issues/1007 is solved.

**Comment by Plasmmer** [comment]
msgpack is `old`. Please update the docs, because the new version is called `msgpack-python`.

**Comment by HelloZeroNet** [comment]
can you please help me find the error in the docs? (i see msgpack-python everyone)
