### ISSUE TITLE
Sandbox prevents creating web worker

### ISSUE THREAD

**Issue by nametoolong** [HelloZeroNet/ZeroNet#1010]
`new Worker("worker.js")` merely fails: `Uncaught DOMException: Failed to construct 'Worker': Script at 'http://127.0.0.1:43110/[site address]/worker.js' cannot be accessed from origin 'null'.`
No idea about whether disallowing web workers should be a bug or a feature.

**Comment by HelloZeroNet** [comment]
Probably more like a feature of iframe sandboxing, but it works this way:
```js
function createWebworker() {
	// via http://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers
	var blob = new Blob([
	    "onmessage = function(e) { postMessage('msg from worker'); }"]);

	var blobURL = window.URL.createObjectURL(blob);
	console.log(blobURL)

	var worker = new Worker(blobURL);
	worker.onmessage = function(e) {
		document.getElementById('webworker_result').textContent = event.data;
	};
	worker.postMessage("hello");
}
```

**Comment by AnthyG** [comment]
I know, this is closed, but don't service workers need https anyways?!

PS.: This can be achieved through visiting zeronet via _localhost_ instead of _127.0.0.1_ (at least as far as I remember).

**Comment by HelloZeroNet** [comment]
web worker is not same as service worker.
Web worker: Script runs in separate thread, but it's closed when you leave the site.
Service worker: Keep running when you close the site

**Comment by AnthyG** [comment]
@HelloZeroNet Ah wow, I did so much research on workers, but till now, I didn't quite understand the differences 😅
