### ISSUE TITLE
The page is refreshed before I see the alert (animated complete).

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroNet#1013]
When I clone a site:

<img width="738" alt="2017-07-11 21_18_16-screentogif - editor" src="https://user-images.githubusercontent.com/15178410/28071919-f9a1a7da-6683-11e7-8843-5054e37ff309.png">

<img width="740" alt="2017-07-11 21_18_40-screentogif - editor" src="https://user-images.githubusercontent.com/15178410/28071946-0df8f364-6684-11e7-83a5-a89602d2f9f0.png">

<img width="741" alt="2017-07-11 21_18_57-screentogif - editor" src="https://user-images.githubusercontent.com/15178410/28071957-1346d336-6684-11e7-95d9-4948852dcf98.png">

The page is refreshed before I see the alert (animated complete).
So, what is the alert say?

**Comment by HelloZeroNet** [comment]
Nothing important, it just says "Site cloned" and redirects to the new site.
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiWebsocket.py#L818
