### ISSUE TITLE
[Feature] Allow cross-origin requests for files from already downloaded zites 

### ISSUE THREAD

**Issue by ImagicTheCat** [HelloZeroNet/ZeroNet#1014]
Hi, 
if I understood correctly the CORS security is here to prevent zites from downloading other zites without user consent, but what about already downloaded zites ? To load an image currently you need to use fileGet and convert that into a data uri, which is not very efficient, where you could just allow some resources to be loaded. No idea if it's possible and if it's easy to setup.

**Comment by HelloZeroNet** [comment]
The fileGet command only works within the same site. The cross-site loading is not allowed for privacy reasons, because it would allow the site to list the other sites that is added to the user's client.
