### ISSUE TITLE
ZeroNet is possibly under attack

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#1016]
I seriously believe that ZeroNet is suffering a DDOS attack.
I saw 1732 seeds in ZeroName.
In less than 4 minutes ZeroName is with 1608 seeds.
@HelloZeroNet, what do you think about preventing custom clients that can download a site but doesn't seed?
Also these great volume of "users" are seeding in majority ZeroName against ZeroHello. It is normal?
And when I tried to publish a comment about it in ZeroMe, it was stuck on publishing to 4 peers.

**Comment by HelloZeroNet** [comment]
There is a bit more peer than usual, but I don't see any suspicious thing.
The peer number is just an estimation. If you running your client for longer time you will see more due peer exchange. Also, more  frequently updated sites = more connections = more peer exchange = more peers.

It's an opensource protocol/app, so you can't do much about making custom modifications, but I don't see any problem with that. If someone does not have spare bandwidth to seed sites, then he/she can use a proxy or simply put it on paused state.

Publishing to 4 peers should be fine.

**Comment by Plasmmer** [comment]
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:69_1EZTWytasXcKdiUFnN4KHqAfvg1nwkTkKv
@Nofish: this NEEDS to be fixed with URGENCY. Thanks @kai0: now I know what is hapenning here.
Here I'm persecuted by the owners here, and they spy in my house anything I do in the Internet. When I created a site, in less than 1 minute it gained 5 peers without any promoting!
I properly signed it and tried to publish to a lot of proxies like I ever did in the last year, but now the proxies didn't received my updates. I know these 5 fixed peers are the mans that are persecuting me, and they made my site inavailable to the following peers. In the last year no, but now it was discovered by they. It needs to be fixed, because is clearly a security vulnerability.
Here are the prints, as a timeline:
http://prntscr.com/fx4482
http://prntscr.com/fx44d0
Without promoting, my site has 2 peers connected. One minute later, I saw it unavailable in the proxies.
http://prntscr.com/fx46pt
Stucked in the publishing (it can be normal, I know).
http://prntscr.com/fx470a
Stuck loading on proxies. I tried to publish more to reach proxies, everytime in this timeline.
http://prntscr.com/fx482w
Loaded only a few things.
http://prntscr.com/fx49kt
Loaded more things, but JS don't loaded.
http://prntscr.com/fx4afv
Not found on bit.surf.
https://prnt.sc/fx44kx
Peeper works on my local.
https://prnt.sc/fx44tg
Peeper isn't working on my mobile phone and on proxies like Peeper ever worked.
http://prntscr.com/fx4mfu
Ok, you can say the problem is on MY Peeper, on zn.maly, on MY CryptoID, on bit.surf, on colored poneys breeded with unicorns, whatever. But locally I can't see my video.
http://prntscr.com/fx4mqy
But in this proxy on the first load it appears!

Nofish, remember when I talked to you about the increasing peer number and the stranger things? And also this number isn't ciompatible with the people really using the sites. You talked itr is normal, but I surely believe that a botnet is attacking ZeroNet.

**Comment by Plasmmer** [comment]
@shortcutme

**Comment by Plasmmer** [comment]
The solution I was thinking is to when a peer see that the connected peer isn't sending the correct data to him (based in the site's address signature), then this peer is reported. Accourding to a number of reports, the peer is blocked and added in a site called BlockList, shipped with ZeroNet.

**Comment by HelloZeroNet** [comment]
Im not at home right now, i will check it next month if its still an issue

**Comment by Plasmmer** [comment]
> Im not at home right now, i will check it next month if its still an issue

Obviously it will still be a issue, unless you fix it or approve pull request of someone fixing it.

**Comment by Plasmmer** [comment]
@HelloZeroNet
@shortcutme

**Comment by HelloZeroNet** [comment]
I still have not found any suspicious activity and the updates reached my remote clients correctly.
But I made some changes that pushes the incoming updates to more peers. (6 instead of 4)
We can make it even higher, but unfortunately there is no way to make sure that every update is reaches every node.

**Comment by Plasmmer** [comment]
@HelloZeroNet

> I still have not found any suspicious activity and the updates reached my remote clients correctly.
Sure, they don't want this info reach you.

> (6 instead of 4)
> We can make it even higher
Will be nice a field in the 0 menu to set the minimum peers to publish.

> but unfortunately there is no way to make sure that every update is reaches every node.
Solution: when a peer see that the connected peer isn't sending the correct data to him (based in the site's address signature), then this peer is reported. Accourding to a number of reports, the peer is blocked and added in a site called BlockList, shipped with ZeroNet.

**Comment by Plasmmer** [comment]
@HelloZeroNet
Please read:
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:69_1EZTWytasXcKdiUFnN4KHqAfvg1nwkTkKv

**Comment by HelloZeroNet** [comment]
The per-site connection target can be overwritten using `--connected_limit` (by default it's 8)
In my experiences it should be enough in most situation.
I will monitor the "each time connecting the same nodes." problem.

**Comment by Plasmmer** [comment]
@HelloZeroNet

> I will monitor the "each time connecting the same nodes." problem.
Excelent. I did tests and peers was not sending the files, and the proxy/my client keeps with the same peers and still receiving 404, even my sites having 20/600 peers and I properly publishing all files.

**Comment by Plasmmer** [comment]
@HelloZeroNet
A solution here is to switch to other peers when receiving 404.
Blocking malicious peers is the best addition.

**Comment by Plasmmer** [comment]
> Well i'm not sure if its a good idea, because it would encourages people to run many clients on the same machine an by that flood the network.

Then, people can flood the network, this explains the "bit more peer than usual".
http://web.archive.org/web/20170808162515/https://github.com/HelloZeroNet/ZeroNet/issues/898

**Comment by Plasmmer** [comment]
@HelloZeroNet @shortcutme 

> I will monitor the "each time connecting the same nodes." problem.

A idea for this is here: https://github.com/ZeroNetJS/zeronet-js/issues/46.

@zwgshr @imachug @MuxZeroNet @PeterSurda

Please fix it.

**Comment by Plasmmer** [comment]
@HelloZeroNet, @shortcutme

**Comment by Plasmmer** [comment]
@HelloZeroNet
"Thanks but there is not real security issues" ?

**Comment by MuxZeroNet** [comment]
ZeroNet fetches a list of peers from the tracker every 2 hours. Your instance may be a side effect of this.

o A computer has a limited amount of RAM.

o A computer program can handle a limited number of simultaneous connections.

o A majority of users browse ZeroNet for only a few hours a day and shut their nodes off, so it is a good idea to ask the trackers for a new list of peers every few hours.

o Some trackers are known to intentionally insert fake IPs in order to confuse DMCA bots. Those 5 "phantom" peers might be fake IPs inserted by the trackers.

o ZeroNet has a "rating" algorithm.

**Comment by Plasmmer** [comment]
@MuxZeroNet
Some peers can give 404 errors. So would be good change to another peer when receiving 404 and to downvote it.
ZeroNetJS already have this reliability/security improvement.
