### ISSUE TITLE
Potentially unsafe part of the pattern: ]{

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1019]
New ZeroNet update.
Getting "Potentially unsafe part of the pattern" error for optional pattern: ^[0-9a-f]{10}.[0-9]{13}$
Used in users content.json files
An old content.json file now invalid:
<pre>
{
 "address": "1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ",
 "cert_auth_type": "web",
 "cert_sign": "HOFnzSDzr7fIevQePi+1G7/YOB+eUbv+xtdstzZsk+zsbC1lx1L61VesCr9/Dnn6j6ZqD6uucRq8oc2j1Q48cP8=",
 "cert_user_id": "17bkaTxefKABo@moneynetwork.bit",
 "files": {
  "wallet.json": {
   "sha512": "b2d87f021de5654624c2942eb44b298b1fb807abc7a949e07ee77e548d5db4a4",
   "size": 188
  }
 },
 "files_optional": {
  "2df0ef529c.1499446132848": {
   "sha512": "7a558a24de7e015a09072966ced13cec2b108d3db915f28c561eded19fd94457",
   "size": 2448
  },
  "2df0ef529c.1499446146829": {
   "sha512": "c9ef0ff90dc5b7cf01e91c8b6423c0280ee445cf4642f84ad6e3cd372f59ad5f",
   "size": 2236
  },
  "2df0ef529c.1499446167867": {
   "sha512": "8c21541ef464b494c02447e585362443770c7300b91397008324c0d64fed87f5",
   "size": 876
  }
 },
 "inner_path": "data/users/17bkaTxefKABomUaD9SffeHkywruhMHuU/content.json",
 "modified": 1499446169,
 "optional": "^[0-9a-f]{10}.[0-9]{13}$",
 "signs": {
  "17bkaTxefKABomUaD9SffeHkywruhMHuU": "HEAUiGNe0KVIhDtsfywmjzMDnMHqNB75hjCc7XgswyjBdmqwMVUYDYnS8CSldeBt3i2VHK84IuU9S2Ra9k9ZqvE="
 }
}
</pre>

**Comment by jaros1** [comment]
pattern ^[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$ is valid but why is {10} and {13} no longer allowed in optional files patterns?

**Comment by jaros1** [comment]
Temporary workaround util fixed. edit /src/util/SafeRe.py and remove the new unsafe pattern check:
<pre>
import re


class UnsafePatternError(Exception):
    pass


def isSafePattern(pattern):
    if len(pattern) > 255:
        raise UnsafePatternError("Pattern too long: %s characters" % len(pattern))

    # unsafe_pattern_match = re.search("[^\.][\*\{\+]", pattern)  # Always should be "." before "*{+" characters to avoid ReDoS
    # if unsafe_pattern_match:
    #     raise UnsafePatternError("Potentially unsafe part of the pattern: %s" % unsafe_pattern_match.group(0))
    return True


def match(pattern, *args, **kwargs):
    if isSafePattern(pattern):
        return re.match(pattern, *args, **kwargs)
</pre>

**Comment by HelloZeroNet** [comment]
Unfortunately we had to restrict pattern because of possible [ReDoS](https://en.wikipedia.org/wiki/ReDoS) attacks:  I have not found any reliable way to detect problematic patterns, so right now "." is mandatory before "*{+" characters
To fix it I recommend to put optional files to separate folder or use different pattern eg.: `.*\.[0-9].*$`

**Comment by jaros1** [comment]
OK. Not nice. It will be a very big work moving optional files to separate folders and optional files pattern will be very weak using .* and .+ pattern. ".+" and ".*" matches any characters!
Why the 255 characters length? Can solve my problem by repeating [] groups n times manually but then I will run into the 255 characters limit for some of my sites.

**Comment by HelloZeroNet** [comment]
Length limit is also to avoid some attacks. If you really want to be strict and `^.*\.[0-9].*$` does not works for you then `^.*\.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]$` just 71 chars.

Probably we need some more restriction as `re.match("^(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)(.*a)$", "aaaaaaaaaaaaaaaaaaaaaaaa!")` also takes long time to execute.

**Comment by jaros1** [comment]
Sounds like optional files pattern will end up almost useless and "^.*$" could be used instead (or a seperate folder).
How is it with "files_allowed" and "optional" patterns if a file in a user directory matches both files_allowed and optional? (I have no problems with files_allowed patterns). 
Will the file be a normal or an optional file?

**Comment by HelloZeroNet** [comment]
files_allowed is only parsed on verification, so it will be optional that case

**Comment by jaros1** [comment]
I have used regular expressions to exact match my optional files and that is no longer allowed due to the new restrictions. For example "optional": "([0-9]{13}-[0-9]{13}-[0-9]+-chat.json|[0-9]{13}-image.json|[0-9]{13}-[0-9]+-image.json|[0-9a-f]{10}.[0-9]{13})" in MonetNetwork. 

[0-9].* is an options as no of my allowed files have digits in filenames. I will change my optional files patterns to the new rules. I do not like it, but OK if that is the way it is :-)
