### ISSUE TITLE
By default, don't show the 0 button

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#1024]
Isn't pratical to use a drag function in a computer. Also, this button is very bad when we need to insert elements in the header of a site. Please consider inserting a "Z" key shortcut instead.

**Comment by anoadragon453** [comment]
Having a shortcut versus an on-screen icon makes it more difficult for in-experienced users to understand how to view the sidebar (or get back to ZeroHello).

Plus mobile users would be stuck since they can't enter keyboard shortcuts without an on-screen keyboard.

**Comment by Plasmmer** [comment]
We can have a option in the drawer 0 menu to can use a keyboard shortcut in PC.
Also, in mobile isn't needed the button, the user can just swipe from the right side.

**Comment by Plasmmer** [comment]
Moved to: https://github.com/ZeroNetJS/zeronet-js/issues/42.

**Comment by Ornataweaver** [comment]
Having a settings for ZeroNet can help these types of stuff.

**Comment by DaniellMesquita** [comment]
@Ornataweaver I agree.

**Comment by Ornataweaver** [comment]
There is the Config now. It can be put there.
