### ISSUE TITLE
[Feature] Cross-origin permissions

### ISSUE THREAD

**Issue by ImagicTheCat** [HelloZeroNet/ZeroNet#1026]
Following this issue https://github.com/HelloZeroNet/ZeroNet/issues/1014 .

ZeroNet is about the users and their control, so it could be interesting like for the merger feature to be able to ask the user to allow cross-origin requests (and fileGet access) for a specific external zite (a permission).

I think this could be a good compromise instead of disabling completely the cross-origin requests, even if this will not allow too many CORS to be done.

**Comment by HelloZeroNet** [comment]
Two possible solution:
 - Add a command set similar to merger site command, but only for read access and instead of get access to site types you requesting access to specific address.
- Add an option to site's content.json that allow cross-site file access.

**Comment by April93** [comment]
>Add a command set similar to merger site command, but only for read access and instead of get access to site types you requesting access to specific address.

This works. Just have a command to add a permission to read files from a particular site. So the flow would be something like: request permission to read site 1whatever -> remotefileget 1whatever inner_dir and read whatever file you need. Then repeat for other sites if you need to access them. The user would be notified of the cross-site access, and they could allow or deny particular requests.

>Add an option to site's content.json that allow cross-site file access.

I don't like this one. Having the site itself determine whether the files can be accessed does nothing to prevent malicious usage. For example, if many sites enable it (for whatever reason), then a malicious site could just fetch from all of them with no need for permissions. Defeating the entire point.

Unless you meant the other way: the requesting site puts it in it's content.json. That'd work, but malicious sites could then just include it and continue on their way, and users would still be vulnerable.

Just a permission to access X site, and then a command to be able to fetch *raw* (not formatted) files. I can see the need to fetch things like images, music, json/txt files, .db files, etc. Forcing a format limits functionality.

**Comment by ImagicTheCat** [comment]
I agree that allowing all cross-site access with a single option is not the way, but instead you could have a list of accepted origins able to request the content. This is far less flexible than a permission asked directly to the user, where no sites would require any static configuration and could just ask for things as soon as they need it. The permission request is also interesting because it will confirm that the user agree to download the requested site, making things easier to understand.

**Comment by April93** [comment]
>I agree that allowing all cross-site access with a single option is not the way, but instead you could have a list of accepted origins able to request the content. 

Eh, I feel that's worse. It solves the problem of malicious sites, but then once again restricts things and removes user control. And given how few people would actually whitelist sites, it'd basically be what we have now. I like the permissions idea. It's literally already implemented. Just quickly write a command that takes such a permission. IMO, when in doubt, give control to the users.

**Comment by ImagicTheCat** [comment]
Yeah, it's not really a solution. But why not doing something hybrid, like, you have the permission system to request access to a site (download, full cross-origin requests, remote fileGet) and a set of white-list rules (paths) in the configuration of the target site. So if the site owner doesn't allow any path, no cross-origin is possible. if the user doesn't allow it in the first place too, no cross-origin possible. So users can browse without too much headache, if they don't fully trust a site they can still allow the cross-origin requests if they trust the requested site. I don't know if this could even allow iframe to embed contents, following a "/embed" subdirectory rule.

**Comment by April93** [comment]
So basically:

* Nothing whitelisted + no perms given = no access

* Nothing whitelisted + perms given = access

* Something whitelisted + no perms given = access

Like that? I'm not sure I can imagine a case where whitelisting is needed or preferable, if the requesting site can just ask for permission. But I think it'd be welcome nonetheless. The more options the better.

**Comment by ImagicTheCat** [comment]
Not it's a "and" not a "or", the site owner should allow some path and the user should allow access/download the site. But of course the most important feature is on the user side.

**Comment by April93** [comment]
Needing things whitelisted returns to the problem of uncooperative or dead websites. Unless the user has the option to override that?

**Comment by HelloZeroNet** [comment]
I have added a cors plugin: https://github.com/HelloZeroNet/ZeroNet/commit/cbac57dc8824a9dff4a79dcfab008bebe5cddf6f

To request permission to other site you have to execute Page.cmd("corsPermission", "anysiteaddress)
After that you can access the site's resources using `cors-siteaddress/anyfile.json` (via http request or fileGet api command)

I hope it covers your usecases.

**Comment by ImagicTheCat** [comment]
Thanks, will test this as soon as I can.

**Comment by April93** [comment]
```
page.cmd("corsPermission", "138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP")
var db = null
var xhr = new XMLHttpRequest();
  xhr.open('GET', '/kaffiene.bit/cors-138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/data/ZeroWiki.db', true);
  xhr.responseType = 'arraybuffer';
  xhr.onload = function(e) {
    var uInt8Array = new Uint8Array(this.response);
    db = new SQL.Database(uInt8Array);
  };
  xhr.send();
```

This snippet still results in: 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:43110/kaffiene.bit/cors-138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/data/ZeroWiki.db. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
```

Even when permission has been granted. Testing with fileget, I was able to grab a text-based file (README.md for instance). However, I'm unsure how I'd go about fetching the .db or any non-text file for my own parsing purposes. Upon further testing, I *cannot* fetch the readme file through XMLHttpRequest, due to CORS, even though I'm fetching from within the virtual directory after given permission.

Does fileget have an option to just fetch the raw file?
