### ISSUE TITLE
UnboundLocalError: local variable 'row' referenced before assignment

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#1029]
getting this error while trying to rebuild DB

this site (never mind the frontend) http://127.0.0.1:43110/1GnTA9B5JDSsAEk63LyDCQkbmoiFDSVxad/

this is the error on console:
Site:1GnTA9..Vxad Error importing data/users/1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp/data.json: UnboundLocalError: local variable 'row' referenced before assignment in SiteStorage.py line 130 > MutePlugin.py line 126 > SiteStorage.py line 75 > Db.py line 268 > DbCursor.py line 147

this is the data.json mentioned in the error:
{
	"users": [
		{
			"user_id": "1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp",
			"user_name": "davidnelband@zeroid.bit",
			"user_date_added": 1500382501284
		}
	]
}

why does this happen? how to fix this?

**Comment by HelloZeroNet** [comment]
It happens, because you have `"version": 4,` in dbschema.json, but only 1-2-3 supported.
Also you should change `"optional": "(data/users)",` to `"ignore": "(data/users)",`
