### ISSUE TITLE
Provide a option for: auto turn on "Help distribute all new files"

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroNet#1033]
A feature request, as the title say.

**Comment by HelloZeroNet** [comment]
Added in Rev2170 https://github.com/HelloZeroNet/ZeroNet/commit/4cd393e4d8f96f8fed0f4c629c55605d26b126e3
You can enable it using `--download_optional auto` (only applies to newly added sites)

**Comment by zcyzcy88** [comment]
And more...
- [ ] one-click to turn on this for **all old sites** ([this is my workaround](https://github.com/zcyzcy88/SelfColle/issues/57))
- [ ] add buttons for these function into GUI
