### ISSUE TITLE
Get list of all user sites

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#1034]
I know its possible with merger sites, but is it possible to get a list of all the sites that the user is currently seeding?

**Comment by mkg20001** [comment]
Only "admin" sites (usually the homepage of the client) can do this

**Comment by HelloZeroNet** [comment]
If your site has merger permissions, then you can get the list of merged sites using mergerSiteList command, but you can't get the list of all seeded sites as it could be privacy issue.
