### ISSUE TITLE
config parsing error - ui_restrict

### ISSUE THREAD

**Issue by rinchen** [HelloZeroNet/ZeroNet#1037]
Howdy,
If you add the following to zeronet.conf
ui_restrict = 192.168.1.1 192.168.1.2
the directive will not work.  --debug shows this is translated to ui_restrict=['192.168.1.1 192.168.1.2'].  Note that it is an entire string vs two elements of an array.  Interestingly, in TestConfig.py the command-line arguments work just fine.
Joey

**Comment by HelloZeroNet** [comment]
Try this:
```
ui_restrict =
    192.168.1.2
    192.168.1.2
```

**Comment by rinchen** [comment]
That worked. Thanks.  The published docs only cover the command line options, not zeronet.conf unfortunately. This would be a good addition.

**Comment by slrslr** [comment]
It would be good if one can restrict like this:
ui_restrict = 1.2.3.4,9.8.7.6
or to restrict subnet like this:
ui_restrict = 1.2.3.0/24;9.8.7.6
