### ISSUE TITLE
找不到节点

### ISSUE THREAD

**Issue by qq573011406** [HelloZeroNet/ZeroNet#1038]
连接中...
找不到节点
CONTENT.JSON 下载失败
CONTENT.JSON 下载失败
CONTENT.JSON 下载失败

**Comment by chenjia404** [comment]
你是什么网络？

**Comment by l5h5t7** [comment]
你要访问的站点地址是？操作系统是？网络环境是？没有这些信息无从判断找不到节点的原因。

**Comment by crazyhuwho** [comment]
刚刚下载下来，出现内容为：连接中，找不到节点，CONTENT.JSON 下载失败。
一直连接不上，我的操作系统是window10。
以下是访问http://127.0.0.1:43110/geekway.bit的报错信息。还请帮助，感激不尽！
Server error

Err: IOError: [Errno 2] No such file or directory: u'A:/app/ZeroNet-win-dist/data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/data/names.json' in UiServer.py line 93 > UiRequest.py line 110 > MutePlugin.py line 137 > SiteManagerPlugin.py line 71 > SiteManagerPlugin.py line 46 > SiteStorage.py line 253 > SiteStorage.py line 167

Please report it if you think this an error.

Details:

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch", 
    "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.8,en;q=0.6", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36", 
    "PATH_INFO": "/geekway.bit", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "49987", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "TheOne", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.2 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
        "config_file": "A:/app/ZeroNet-win-dist/zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "A:/app/ZeroNet-win-dist/data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": false, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "zh", 
        "log_dir": "A:/app/ZeroNet-win-dist/log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": "default_browser", 
        "optional_limit": "10%", 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_host": null, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.2.1", 
    "version_python": "2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.5.6 r2153", 
    "wsgi.url_scheme": "http"
}

**Comment by l5h5t7** [comment]
看起来是 ZeroName 也没下载完成。打开 ZeroNet 后能成功打开 ZeroHello 吗？
你是什么网络环境？是公司的白名单网络环境或者二级运营商吗？
另外看起来你使用了 360 极速浏览器，那么你有没有安装 360 的其他相关软件？你可以卸载它们并使用最新版的 Chrome 或者 Firefox 来重试吗？

**Comment by ymai6** [comment]
我使用 windows10 64位专业版，客户端第一次能够运行，后面再点击程序就直接闪退了。安装了vs2008运行环境也一样，不知道问题在哪儿？

**Comment by IsaaCXY** [comment]
这个问题之后有解决吗？我现在也是下载下来也是 content.js 下载失败,hello 页面也无法访问

**Comment by dddog999** [comment]
@l5h5t7 如果主页连一个tracker都连不上怎么办？

**Comment by l5h5t7** [comment]
要么就是换 Tracker，要么让 Tracker 走代理或者 VPN 。

**Comment by UesugiErii** [comment]
在初始页面的左上角有一个config,很小,那里面设置代理后就可以连接了

**Comment by tangdou1** [comment]
It has been solved and can be closed.
