### ISSUE TITLE
Cannot login with unique private key

### ISSUE THREAD

**Issue by tantalate** [HelloZeroNet/ZeroNet#1039]
I have created zeroid and enabled Multiuser plugin, but when I login with the saved unique private key, I am still cannot use zeroid (the same as login with new private key.

There is a `master_seed`  field in users.json but not the same as the saved unique private key, and doesn't work also.

**Comment by l5h5t7** [comment]
You should access your ID provider site after login at ZeroHello.

**Comment by tantalate** [comment]
@l5h5t7  Do you mean I should open zeroid.bit site?  I tried, but with no effect. When I click the "Login as" button, there is a `zeroid.bit Register>>` on the popup.

**Comment by HelloZeroNet** [comment]
By default the users.json file is not updated when you using the multiuser plugin, so you have to login every time you start the client. You can change this behavior it by starting it using --multiuser_local argument. (Enable unsafe Ui functions and write users to disk)

**Comment by grez911** [comment]
@tantalate @HelloZeroNet Can the issue be closed?
