### ISSUE TITLE
Version 0.5.7 site loading problem

### ISSUE THREAD

**Issue by 1443** [HelloZeroNet/ZeroNet#1041]
The Highcharts/Highstock JavaScript on http://127.0.0.1:43110/eris.bit isn't loading with version 0.5.7 on Windows. It's working fine with earlier versions, including 0.5.6.

On further testing it seems there is a problem with downloading the content.json? It still works with this proxy: https://zeronet.maxweiss.io/eris.bit/

**Comment by AnthyG** [comment]
This rather seems to be a CORS-related issue, as I'm getting this error: `XMLHttpRequest cannot load http://127.0.0.1:43110/eris.bit/data/usa.json. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

**Comment by HelloZeroNet** [comment]
Unfortunately Ajax requests no longer works, you have to use the fileGet API call to do the same
