### ISSUE TITLE
'Potentially unsafe part of the pattern' error not descriptive enough

### ISSUE THREAD

**Issue by antilibrary** [HelloZeroNet/ZeroNet#1043]
When I try to add a books database (merger db) to the site antilibrary.bit on a fresh 0.5.7 zeronet install I get the error `ERROR Db:Antilibrary Potentially unsafe part of the pattern: ]+` on the console and no json files from the merger site are loaded into the database.
This is happening if you try to add any book database to the site (go to My Books, Settings).

The problem is, the error is not descriptive of where the issue is. I've searched the content.json and dbschema.json for the pattern `]+` but found nothing.

The error should at least point to the file that contains the unsafe pattern.

I'm still unable to fix the issue because I don't know where the problem is.

**Comment by antilibrary** [comment]
@HelloZeroNet sorry to trouble you with this one but, can you give me any ideas? [Some new users are having a hard time because of this](https://www.reddit.com/r/antilibrary/comments/6pe56q/no_books_found/) and I have no idea what file can be holding the wrong pattern :(
Thanks

**Comment by HelloZeroNet** [comment]
Please check your dbschema.json and content.json files regex patterns: https://zeronet.readthedocs.io/en/latest/site_development/content_json/#regular-expressions-limitations

**Comment by HelloZeroNet** [comment]
I have added the pattern itself to the log line: https://github.com/HelloZeroNet/ZeroNet/commit/f45ecb6cf4bf72bd77351cf90bde176b0203e8c7
This should make it easier to find the problem.

**Comment by antilibrary** [comment]
That's great. Thanks!

**Comment by grez911** [comment]
@HelloZeroNet @antilibrary Close maybe?
