### ISSUE TITLE
run "ZeroNet siteCreate" on macOS sierra occur error

### ISSUE THREAD

**Issue by javenisme** [HelloZeroNet/ZeroNet#1046]
➜  MacOS ./ZeroNet siteCreate
- Starting ZeroNet...
- OpenSSL loaded, version: 0009081DF
- Version: 0.5.4 r2054, Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)], Gevent: 1.2.1
- Generating new privatekey...
- ----------------------------------------------------------------------
- Site private key: 5J2vjCYnidUjbigbWjFZucuf64gWfjxt5Q8ShSoAH6XMuPwXpQF
-                   !!! ^ Save it now, required to modify the site ^ !!!
- Site address:     13JfSkzJG8Tms8GsbYoVX6FhRvKdHHpRFo
- ----------------------------------------------------------------------
? Have you secured your private key? (yes, no) > yes
- Creating directory structure...
- Creating content.json...
Site:13JfSk..pRFo Content.json not exist: /Users/jobs/Library/Application Support/ZeroNet/data/13JfSkzJG8Tms8GsbYoVX3FhRvKdHHpRFo/content.json
Site:13JfSk..pRFo File content.json not exist yet, loading default values...
Site:13JfSk..pRFo Opening site data directory: /Users/jobs/Library/Application Support/ZeroNet/data/13JfSkzJG8Tms8GsbYoVX3FhRvKdHHpRFo/...
Site:13JfSk..pRFo - index.html (SHA512: 47ad6e3c1cd06668156ea8409c595002bc523537eef00c5d3b2a6336557a9b5b)
Site:13JfSk..pRFo Adding timestamp and sha512sums to new content.json...
Site:13JfSk..pRFo Verifying private key...
Site:13JfSk..pRFo Correct 13JfSkzJG8Tms8GsbYoVX3FhRvKdHHpRFo in valid signers: ['13JfSkzJG8Tms8GsbYoVX3FhRvKdHHpRFo']
Site:13JfSk..pRFo Signing content.json...
Site:13JfSk..pRFo Saving to content.json...
Site:13JfSk..pRFo File content.json signed!
- Site created!
- Unhandled exception
None
Traceback (most recent call last):
  File "gevent/hub.pyo", line 857, in switch
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 137, in signalHandler
    raise ExitCommand()
__main__.ExitCommand
- Unhandled exception
None
Traceback (most recent call last):
  File "/Applications/ZeroNet.app/Contents/Resources/__boot__.py", line 81, in <module>
    _run()
  File "/Applications/ZeroNet.app/Contents/Resources/__boot__.py", line 66, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 179, in <module>
    gui()
  File "/Applications/ZeroNet.app/Contents/Resources/boot.py", line 106, in gui
    time.sleep(0.1)
  File "gevent/hub.pyo", line 169, in sleep
  File "gevent/hub.pyo", line 651, in wait
  File "gevent/hub.pyo", line 899, in get
  File "gevent/hub.pyo", line 630, in switch
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1057ce230 select pending=0 ref=0>)
2017-07-25 11:17:28.081 ZeroNet[87824:11603434] ZeroNet Error
2017-07-25 11:17:28.081 ZeroNet[87824:11603434] ZeroNet Error

**Comment by Plasmmer** [comment]
Reference: #1047.
I think it is related.

**Comment by HelloZeroNet** [comment]
I try to reproduce it, but:
```
$ ./ZeroNet.app
-bash: ./ZeroNet.app: is a directory
```
(Under 10.12.2)
So: How to run .app as command line applications?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in latest version. (you have to download ZeroNet.app again from zeronet.io homepage)
You may need to define the data directory manually as by default it creates it right next to ZeroNet.app. Example.: `MacOS zeronet$ ./ZeroNet --data_dir "/Users/zeronet/Library/Application Support/ZeroNet/data" siteCreate`
