### ISSUE TITLE
Images not displaying correctly in Zerome when scrolling

### ISSUE THREAD

**Issue by Clarin98** [HelloZeroNet/ZeroNet#1048]
When I am scrolling in Zerome this happens with images:
![screenshot from 2017-07-24 23-01-58](https://user-images.githubusercontent.com/14655066/28555341-e6f77614-70c4-11e7-931a-8d817ed53356.png)

**Comment by Plasmmer** [comment]
Here it doesn't occurs, its the first time I hear about it.
But here is not the correct place to post this issue, but in the [ZeroMe repo](https://github.com/HelloZeroNet/ZeroMe).
Please, say in the new issue your OS, the browser version and steps to reproduce the potential bug.

**Comment by grez911** [comment]
Not related to the core of zeronet.
@Clarin98 @HelloZeroNet Please, close.
