### ISSUE TITLE
how can i backup my zeronet file?

### ISSUE THREAD

**Issue by jcx70100** [HelloZeroNet/ZeroNet#1049]
When I reinstall ZeroNet or change to other system environment, are there any solutions to restore my ZeroNet files without signing up for a new account?

I searched a lot from the net, most say the easiest way is to backup my "user.json" file. Sadly, I'm using macos system now, having no idea to find this file. Would you please tell me how to find this file in macos.

Thanks so much.

**Comment by HelloZeroNet** [comment]
I have added a new "Show data directory" menuitem to ZeroHello that should open the directory in the finder. Please verify if its working (you need to update your client by Version 0.5.7... menu item)

**Comment by jcx70100** [comment]
thanks

**Comment by slrslr** [comment]
If anyone has doubts, here is the discussion on this topic: http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1514154652_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS, Thanks
