### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by yanqiangmiffy** [HelloZeroNet/ZeroNet#1050]
Server error

Err: IOError: [Errno 2] No such file or directory: u'C:/Users/Perfect/AppData/Local/Temp/360zip$Temp/360$0/ZeroNet-win-dist/data/sites.json' in UiServer.py line 93 > UiRequest.py line 110 > MutePlugin.py line 153 > UiRequest.py line 273 > SiteManagerPlugin.py line 64 > SiteManager.py line 132 > Site.py line 56 > Site.py line 80

Please report it if you think this an error.

**Comment by yanqiangmiffy** [comment]
how to solve

**Comment by yanqiangmiffy** [comment]
hello ，please delete my issue。because my github page always show a   notification about the repo

**Comment by HelloZeroNet** [comment]
I can't delete it, but you can "Unwatch" the repo here: https://github.com/HelloZeroNet/ZeroNet
