### ISSUE TITLE
ZeroNet 0.5.7

### ISSUE THREAD

**Issue by 631068264** [HelloZeroNet/ZeroNet#1052]
抱歉，你不能删除你自己拥有的站点。
请手动删除站点目录。

我的站点目录在哪？

**Comment by l5h5t7** [comment]
打开自己的站点后，拉出侧边栏，点“删除”即可。

**Comment by 631068264** [comment]
我点了删除就一直在转 然后就没有然后了 完全删不掉  为什么删除按钮这么隐蔽？在外面弄一个假的忽悠人

**Comment by l5h5t7** [comment]
你可以在侧边栏关闭“这是我的站点”试试。
ZeroHello 的那个删除按钮也不是假的啊！只是不能删除自己的站点罢了。

**Comment by chenjia404** [comment]
你zeronet目录，里面有个data目录，删除这个站点地址同名的文件夹。
或者进入这个站点，拖动右侧按钮打开侧边栏，关闭 这是我的站点

**Comment by Plasmmer** [comment]
Can someone talk in english what is hapenning?

**Comment by imachug** [comment]
@Plasmmer, @631068264 asks "Why can't delete own site from ZeroHello?"

**Comment by Plasmmer** [comment]
@imachug, thanks.
@HelloZeroNet @shortcutme deleting owned site via ZeroHello is a good idea.

**Comment by HelloZeroNet** [comment]
The self-owned site delete disabled on ZeroHello to avoid unintentional deletes. To delete your own site please use this way: click on site, open sidebar, click delete site

**Comment by imachug** [comment]
@HelloZeroNet Can we close this as it's intentional?
