### ISSUE TITLE
Accessing localStorage from zite

### ISSUE THREAD

**Issue by cusmith1** [HelloZeroNet/ZeroNet#1054]
I'm getting a "SecurityError (DOM Exception 18): The operation is insecure." while trying to check/store a login information cookie. I realize that this is because localStorage isn't accessible from a sandboxed iframe. Is there a way to get around this?

**Comment by HelloZeroNet** [comment]
Yes, for example:
`Page.cmd("wrapperSetLocalStorage", {"any": value"})`
`Page.cmd("wrapperGetLocalStorage", [], function(res) { console.log(res) })`

More info:
https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/
https://github.com/HelloZeroNet/ZeroHello/blob/master/template-new/index.html
