### ISSUE TITLE
I have some VPS and how can i take advantage of it to help zeronet?

### ISSUE THREAD

**Issue by p24ce** [HelloZeroNet/ZeroNet#1055]
My linux VPS has 10~50G free , I want to make use of it.
Any method ?

**Comment by Junming-Chen** [comment]
When you are reaching the limit of each folder, it will ask your permission to make the folder larger. I guess this is the only way for now to keep peoples' files or chats. But it will also keep much garbage like Ads or meaningless topics.

**Comment by tangdou1** [comment]
see https://github.com/HelloZeroNet/ZeroNet/wiki/%E5%9C%A8VPS%E5%AE%89%E8%A3%85ZeroNet%EF%BC%88Debian%E7%89%88%EF%BC%89
