### ISSUE TITLE
Please update requirements.txt

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#1056]
I have this list:
```
msgpack-python
gevent
rsa
maxminddb
pyelliptic
sqlite3
```

**Comment by HelloZeroNet** [comment]
Actually msgpack and gevent are the only requirements that you need to install.

**Comment by yurivict** [comment]
I see now that other packages are bundled.

Could you please move all bundled packages (that are copied into zeronet) under the directory called 'contrib'? This way it is easier to see that they don't originate in zeronet.

**Comment by yurivict** [comment]
> Actually msgpack and gevent are the only requirements that you need to install.

@HelloZeroNet  What about py-stem? It is required for tor and isn't bundled.

**Comment by HelloZeroNet** [comment]
Py-stem only required by StemPort plugin which is optional and Tor works without it.

**Comment by yurivict** [comment]
There should be the list of optional dependencies too. On the FreeBSD, port declares that it is Tor-ready, so i needs such dependencies.

**Comment by HelloZeroNet** [comment]
It is tor-ready. The StemPort is just an alternative communication plugin if the built-in, raw socket based tor communication way does not works for you.

**Comment by grez911** [comment]
> Could you please move all bundled packages (that are copied into zeronet) under the directory called 'contrib'? This way it is easier to see that they don't originate in zeronet.

@yurivict @HelloZeroNet All third party libraries are in src/lib, isn't it?

**Comment by HelloZeroNet** [comment]
Not all, only the pure-python ones. The ones that requires platform specific compilation is not included. (gevent, msgpack)

**Comment by yurivict** [comment]
> if the built-in, raw socket based tor communication way does not works for you.

How can it just not work? I don't understand.

**Comment by HelloZeroNet** [comment]
Not sure about the differences, but there was reports that it's does not works under Whonix.

**Comment by yurivict** [comment]
> Not sure about the differences, but there was reports that it's does not works under Whonix.

This should be documented. requirements.txt should say:
py-stem is required for alternative way to access Tor through the optional plugin StemPort that only works when native access method fails.

> there was reports that it's does not works under Whonix.

* It should be understood why it doesn't work, in my opinion.
* There should be top-level configuration file that sets a variable USE_STEM_PORT_PLUGIN based on the architecture or something like that.

I am sure, socket-based communication always works on Linux/BSD.

**Comment by yurivict** [comment]
> It is tor-ready. The StemPort is just an alternative communication plugin if the built-in, raw socket based tor communication way does not works for you.

You should delete socket-based code in favor of the Tor-supplied py-stem module. py-stem always works, externally supported. If it breaks, you can always have Tor people fix it. It's easier this way, no need to maintain separate code that does the same without any benefit.

And add py-stem to the list of dependencies.

**Comment by HelloZeroNet** [comment]
I try to avoid external dependencies if possible. When I added full Tor support py-stem did not supported the required features (create ephemeral hidden service) and they only added it half year later.
Later this year the Tor project going to make major changes in hidden services. When it happens I'm going to see if we can change to py-stem or not.
Py-stem also depends on pycrypto binary package, so requires compilation on every platform which can be painful and result in portability issues.

**Comment by imachug** [comment]
@HelloZeroNet This is py3-related and is fixed on py3 branch. Can this issue be closed?
