### ISSUE TITLE
Please add instructions how to run tests

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#1057]

**Comment by grez911** [comment]
All instructions are given here: https://github.com/HelloZeroNet/ZeroNet/blob/master/.travis.yml
It's pretty straightforward, I don't really see the necessity to copy/paste it into documentation. Just do what this file says: install `docker`, `pip`, clone repo, `cd` into it and do:
```
pip install -U pip wheel
pip install -r requirements.txt
pip install -U pytest mock pytest-cov selenium
pip install codecov
pip install coveralls
docker build -t zeronet .
docker run -d -v $PWD:/root/data -p 15441:15441 -p 127.0.0.1:43110:43110 zeronet
python -m pytest plugins/CryptMessage/Test
python -m pytest src/Test --cov=src --cov-config src/Test/coverage.ini
```
@yurivict @HelloZeroNet Please, close.

**Comment by yurivict** [comment]
Thanks!
