### ISSUE TITLE
Allow different data and log directory

### ISSUE THREAD

**Issue by n3r0-ch** [HelloZeroNet/ZeroNet#106]
Allow a different data and log directory passing by a startup argument instead of the default pathes.

**Comment by HelloZeroNet** [comment]
Yeah its planned, until then symlink directories should work

**Comment by HelloZeroNet** [comment]
Added to rev196
https://github.com/HelloZeroNet/ZeroNet/blob/66eca389bfc87049c1e20a26a5c0c2b8b876975e/src/Config.py#L106-L108
