### ISSUE TITLE
Customize language

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroNet#1067]
> ![image](https://user-images.githubusercontent.com/15178410/28922510-035379a0-788d-11e7-9bb6-0178f5044617.png)

Obviously these languages are not enough.
Give a `<input>` to set any language (for example: `JP`)

**Comment by HelloZeroNet** [comment]
If someone submits a translation for the ZeroHello/ZeroNet, then I automatically adding it to the list.

**Comment by skwerlman** [comment]
Have we considered setting up a transifex? its pretty good for tracking translation completion
