### ISSUE TITLE
Configfile additional to the startup options

### ISSUE THREAD

**Issue by n3r0-ch** [HelloZeroNet/ZeroNet#107]
Add a configfile feature. This will allow users to easily set and use their own startup option defaults. 

It should be possible to override the configfile settings with the startup options.

**Comment by HelloZeroNet** [comment]
Its already possible, but undocumented yet, example zeronet.conf:
```
[global]
ui_ip = *
ui_restrict = 1.1.1.1
proxy = 127.0.0.1:9050
```

**Comment by n3r0-ch** [comment]
Nice.

I think it would be useful to add a startup options to the config file path. I find static path similar to log and data (#106) a bit problematic.

**Comment by HelloZeroNet** [comment]
Added to rev196
https://github.com/HelloZeroNet/ZeroNet/blob/66eca389bfc87049c1e20a26a5c0c2b8b876975e/src/Config.py#L106-L108
