### ISSUE TITLE
Bypass the ban of "siteSetAutodownloadoptional"

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroNet#1075]
I have set the ban in MultiUserPlugin:
![image](https://user-images.githubusercontent.com/15178410/29284982-679ac474-815f-11e7-8aa8-0d76868ba794.png)

This is banned:
<img width="435" alt="2017-08-15 02_10_31-whitehub - zeronet" src="https://user-images.githubusercontent.com/15178410/29284887-1b93a758-815f-11e7-9fa5-cd4c2dbf9c28.png">

But you can bypass it:
<img width="637" alt="2017-08-15 02_10_18-zerohello - zeronet" src="https://user-images.githubusercontent.com/15178410/29285011-82e644ba-815f-11e7-8e70-81be98633043.png">

Please fix it.

**Comment by zcyzcy88** [comment]
And users also can do this:
<img width="580" alt="2017-08-15 02_23_06-windows shell experience host" src="https://user-images.githubusercontent.com/15178410/29285439-188edf8a-8161-11e7-9ce7-ce4d5d9307d1.png">

A solution: don't allow user to visit `/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/#Files` when multi user mode.

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed the permissions in Rev2187: https://github.com/HelloZeroNet/ZeroNet/commit/b1989ef02e1c438794ad5bbfde06f9e4474b7394
