### ISSUE TITLE
Is there have read file cache?

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroNet#1078]
As a BitTorrent-like application, disk usage are heavier than normal application.
I don't find the file cache behavior in code or UI.

**Comment by HelloZeroNet** [comment]
No, it's up to the OS, but we have to read/write lot's of small files and there is lot's of random reads and writes because of the sqlite database.
The Torrent client' load is the exact opposite: Read large files sequentially.
