### ISSUE TITLE
Use sql query "insert into" instead of "fileWrite", "fileGet"

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#1088]
As the title says, I'd like you to add that, since it's kind of annoying to edit the files from the code.

**Comment by HelloZeroNet** [comment]
We need .json files, because we can't sync .db files due multi-user sites. It would be possible to parse insert/update sql queries and magically also update the json file, but I try to avoid "magic" as much as possible.

**Comment by MagicInventor** [comment]
@HelloZeroNet Could make a kind of hook that detects when an "insert into" query is done and saved in the .json automatically...

**Comment by HelloZeroNet** [comment]
Actually you can do it in javascript, so it does not requires any modification in the client itself and by that brake the backward compatibility.

**Comment by purplesyringa** [comment]
@HelloZeroNet Closing?
