### ISSUE TITLE
wrapperOpenWindow - Cannot set property 'opener' of null

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1089]
I am using wrapperOpenWindow call in test2 to open a new window/tab. 

a) Test2 OK
b) Test1+test2 ERROR:
Uncaught TypeError: Cannot set property 'opener' of null
    at Wrapper.actionOpenWindow (all.js?rev=2163&lang=en:1036)
    at Wrapper.onMessageInner (all.js?rev=2163&lang=en:983)
    at all.js?rev=2163&lang=en:813

Wrapper.prototype.actionOpenWindow = function(params) {
      var w;
      if (typeof params === "string") {
        w = window.open();
        w.opener = null;
        return w.location = params;
      } else {
        w = window.open(null, params[1], params[2]);
        w.opener = null;
        return w.location = params[0];
      }
    };

Last window.open call returns null in b). 

Screendumps below. params is identical in the two testcases. Minor difference for the windows object. Using callbacks in test1. Maybe wrapperOpenWindow call is not allowed from a callback function?

Debug a) Test2 OK
![ok-screenshot from 2017-08-21 12-28-42](https://user-images.githubusercontent.com/4932088/29516667-835bdf74-8671-11e7-863a-4ab96e2f8795.png)

Debug b) Test1+test2 ERROR:
![error-screenshot from 2017-08-21 12-27-16](https://user-images.githubusercontent.com/4932088/29516674-8c75e780-8671-11e7-84a7-0bcb2725f2b6.png)

Debug a) and Debug b) in one screendump. Only difference is a minor difference in the window object:
![ok-and-error-screenshot from 2017-08-21 12-33-31](https://user-images.githubusercontent.com/4932088/29516754-f691a8fc-8671-11e7-9f9f-02633b78d6bf.png)

Comparing window object:
![window object compare](https://user-images.githubusercontent.com/4932088/29516578-2aa74990-8671-11e7-9025-5f6c9071567b.png)
[error windows object.txt](https://github.com/HelloZeroNet/ZeroNet/files/1238595/error.windows.object.txt)
[ok windows object.txt](https://github.com/HelloZeroNet/ZeroNet/files/1238596/ok.windows.object.txt)

**Comment by jaros1** [comment]
Updated ZeroNet from rev2163 to rev2187. Identical test result.

**Comment by HelloZeroNet** [comment]
I'm afraid it's a browser limitation that we can't affect

> It is blocked by the browser. window.open is only not being blocked, when it is invoked by user action, for example in a click event, emitted by a native browser event. Also javaScript emitted events are being blocked, just like delayed setTimeout callbacks.

via https://stackoverflow.com/questions/18401331/window-open-returns-null-and-fails-in-inline-script-but-works-from-console

**Comment by jaros1** [comment]
Thanks for the answer. Closing this issue
