### ISSUE TITLE
Mysterious wrapping with iter

### ISSUE THREAD

**Issue by grez911** [HelloZeroNet/ZeroNet#1092]
I am curious about [this comment](https://github.com/HelloZeroNet/ZeroNet/blob/1db2327b3dc633be6ba05b00080c01d4cdc639b2/src/Ui/UiRequest.py#L286). I replaced [this line](https://github.com/HelloZeroNet/ZeroNet/blob/1db2327b3dc633be6ba05b00080c01d4cdc639b2/src/Ui/UiRequest.py#L116) with:
```
from datetime import datetime
startTime = datetime.now()
body = self.actionWrapper(path)
endTime = datetime.now()
print endTime - startTime
```
and can not see any significant difference between
```
return iter([self.renderWrapper(site, path, inner_path, title, extra_headers)])
```
and
```
return self.renderWrapper(site, path, inner_path, title, extra_headers)
```
Am I doing something wrong?

**Comment by HelloZeroNet** [comment]
I just tested it if it's changed:
With return: `[16:19:09] Ui.UiServer 127.0.0.1 - - [2017-08-24 16:19:09] "GET http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/ HTTP/1.1" 200 16439 0.135000`
With iter: `[16:20:08] Ui.UiServer 127.0.0.1 - - [2017-08-24 16:20:08] "GET http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/ HTTP/1.1" 200 3001 0.000000`
(win + chrome)

Maybe something with buffering, also not sure about the 3K vs 16K response size difference (the correct one is the 3001)

**Comment by grez911** [comment]
I think the answer has been given [here](http://agiliq.com/blog/2013/07/basics-wsgi/), I'll cite it:
>The last line of application should not be return response_body. Instead, it should be return [response_body]. Reason being:
>- WSGI server expects the return from application to be an iterable and sends each element of this iterable to the client in an unbufferred fashion.
>- If we keep return response_body, response_body is a string and hence an iterable and so our code still works. But every character of the response_body will be sent one by one.
>- If we keep return [response_body], the iterable is a list here, containing only one element which is the string response_body. So, in this case entire response_body will be sent at once.
>- That's why we should replace return response_body with return [response_body].

**Comment by grez911** [comment]
@HelloZeroNet Please, merge.

**Comment by HelloZeroNet** [comment]
Nice finding
