### ISSUE TITLE
Linux Manjaro can't detect opened 15441 port

### ISSUE THREAD

**Issue by alexandre1985** [HelloZeroNet/ZeroNet#1093]
I have UPnP enabled on my router and on my pc firewall I have opened port 15441 both tcp and udp.
But when I start zeronet with `sudo systemctl start zeronet` and I then do a `sudo systemctl status zeronet` I get this message:

> ago 25 00:04:26 pc-grande env[6104]: [00:04:26] FileServer Checking port 15441 using portchecker.co...
ago 25 00:04:28 pc-grande env[6104]: [00:04:28] FileServer [BAD :(] Port closed: Port 15441 is closed.
ago 25 00:04:28 pc-grande env[6104]: [00:04:28] FileServer Trying to open port using UpnpPunch...

When I open ZeroHello I get "PORT: closed".
I believe this is a bug on the zeronet daemon

**Comment by alexandre1985** [comment]
After sometime the zeronet daemon spits out this message from `sudo systemctl status zeronet`
> ago 25 00:04:44 pc-grande env[6104]: [00:04:44] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 74 > UpnpPunch.py line 325 > UpnpPunch.py line 316

I believe this is relevant

**Comment by alexandre1985** [comment]
my firewall has port 15441 open, so in there isn't the issue

**Comment by HelloZeroNet** [comment]
What does https://portchecker.co says for port 15441 for you?

**Comment by alexandre1985** [comment]
It says that port is closed. Or my router isn't doing UPnP correctly or it may be blocked by ISP. Am I right?

**Comment by alexandre1985** [comment]
It is my router. I forwarded the port to my pc and this way everything is being detected as open.
Or my router isn't doing UPnP correctly (which I doubt since I haven't got any issues with other programs) or the UpnpPunch isn't punching the port on my case.
Can you help me resolve this issue? Where can I download Upnppunch to test if it works on my computer?

**Comment by alexandre1985** [comment]
I have got the same issue on other programs, but I didn't noticed because no one had a port: OPEN\CLOSE flag. +1 for you.
So the problem seems to be with my router that has UPnP enable but doesn't seem open ports on demand
