### ISSUE TITLE
Can peers connect offline on Wifi?

### ISSUE THREAD

**Issue by rjsteinert** [HelloZeroNet/ZeroNet#1094]
Hi folks - What beautiful project! I love the authorization for multi-key signatures. Can peers discover each other and transfer zites offline though? And if not, what are the missing pieces?

**Comment by skwerlman** [comment]
To clarify, you mean multiple peers on LAN without a connection to the wider net, right?

If that's what you're asking, the tech you seek is called LPD, and according to some discussion in #449 0net appears to support it (although I'm not 100% sure).

**Comment by amuuza** [comment]
I guess this request should be merged with [this one](https://github.com/HelloZeroNet/ZeroNet/issues/931).

**Comment by rjsteinert** [comment]
@amuuza Sounds right to me.
