### ISSUE TITLE
Concurrency on a single ZeroNet instance - need for multiple zeronet servers on single machine

### ISSUE THREAD

**Issue by jamesacampbell** [HelloZeroNet/ZeroNet#1101]
I am running ZeroNet as a transparent proxy to load zeronet from a VPS and having a lot of fun so far being able to serve content on a public ip address. I am wondering:

1. How many concurrent users can the single instance handle? 

Assuming 1 is a low number then:

2. How can I run multiple zeronet instances? 

I am assuming a `--port` flag at runtime `python start.py --port 1000` and another tmux window `python start.py --port 1001` and should work? Or in the config file itself, like how Tor does it with torrc1 torrc2 torrc3 etcetera? 

This capability, if doesnt exist already, should exist to ensure scalability on a single machine.

Thanks

**Comment by skwerlman** [comment]
1. probably limited by either the VPS's pipe, or its memory (assuming it has <1GB mem)

2. using the port option _should_ work, but you'd probably also want to have different data dirs for each process to avoid issues with r/w locking

**Comment by jamesacampbell** [comment]
@skwerlman yes, looks like CPU (2 core VPS) maxed when accessing all sites at once (264 available) but mem still holding under 1GB around 30% usage, gotta love python worker threads. 

Here is command I used so far: 

`sudo python start.py  --tor_hs_limit 100 --workers 100 --size_limit 1000 --file_size_limit 500 --connected_limit 100`

and I have a custom zeronet.conf with my public ip address

**Comment by jamesacampbell** [comment]
@skwerlman I will close the issue and make sure to try using different data directories per port instance. thanks!
