### ISSUE TITLE
Cannot add more than 2 signers

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#1103]
First, I had this in root `content.json`:
```json
...
"signers": ["1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD", "1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw"]
....
```
Signing works.

---

Now I change it to:
```json
...
"signers": ["1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD", "1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw", "18jNLCocEexrDZeyEiVe2yRGoAXd4KxDD7", "1CvyxRucf7BbDvGtFe5LayTS2qX88VN7Er"]
....
```

2 more signers. I am trying to sign `content.json` and get this:
`'ascii' codec can't decode byte 0xb0 in position 25: ordinal not in range(128)`

---

First I thought `18jNLCocEexrDZeyEiVe2yRGoAXd4KxDD7` or `1CvyxRucf7BbDvGtFe5LayTS2qX88VN7Er` are incorrect, but then I removed first two signers (`1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD`, `1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw`) and signing worked again! **Is there a limitation for signers count, maybe in pybitcointools?**

**Comment by skwerlman** [comment]
that error is talking about a different part of the file from what you posted; specifically, it mentions the 25th character. Can you post the first few lines of the file so we can check them?

**Comment by imachug** [comment]
'Course I can:

    {
        "address": "1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA",
    ....

Does it help? No, of course. I tried to add and remove signers, and only `0`, `1` and `2` worked. Another interesting thing (hardly ever connected, but just in case):

    ...
        "includes": {
            "data/content.json": {
                "signers": ["1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD", "1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw"],
                "signers_required": 1
        },
        "data/users/content.json": {
            "signers": ["1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD", "1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw"],
            "signers_required": 1
        }
    }
    ...

So, there are two more `signers` fields, in `includes`. When I add 1 more signer to *them*, signing works. When I add 1 more signer to root `signers`, signing fails.

**Comment by imachug** [comment]
Some more news:

    [14:34:29] Site:1Demof..VBFA Signing: content.json
    [14:34:29] Site:1Demof..VBFA Opening site data directory: data/1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA/...
    [14:34:29] Site:1Demof..VBFA - [SKIPPED] content.json
    [14:34:29] Site:1Demof..VBFA - dbschema.json
    [14:34:29] Site:1Demof..VBFA - index.html
    [14:34:29] Site:1Demof..VBFA - css/cover.css
    ...200 more lines...
    [14:34:30] Site:1Demof..VBFA - js/ZeroPage.js
    [14:34:30] Site:1Demof..VBFA Changed files: [u'content.json']
    [14:34:30] Site:1Demof..VBFA Adding timestamp and sha512sums to new content.json...
    [14:34:30] Site:1Demof..VBFA Verifying private key...
    [14:34:30] Site:1Demof..VBFA Correct 1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA in valid signers: [u'1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD', u'1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw', u'1CvyxRucf7BbDvGtFe5LayTS2qX88VN7Er', u'1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA']
    [14:34:30] Site:1Demof..VBFA Site sign failed: content.json: UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 25: ordinal not in range(128) in UiWebsocket.py line 381 > ContentManager.py line 626 > CryptBitcoin.py line 49 > main.py line 520 > main.py line 404

---

Problem in pybitcointools? Yes. Let's first look at `ContentManager.py`::

    625     new_content["signers_sign"] = CryptBitcoin.sign(
    626         "%s:%s" % (new_content["signs_required"], ",".join(valid_signers)), privatekey
    627     )

Here, we sign `1:signer1,signer2,signer3,siteaddress`. For 2 signers, that's `1:1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD,1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw,1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA` - 106 bytes. Remeber this number. For 3 signers, that's `1:1MMvgRPh9NGX2z5AGQMdoftTngCxS6DciD,1FUXrC4M9YuJ2hu7t82cgQ1nKFumcxwDhw,1CvyxRucf7BbDvGtFe5LayTS2qX88VN7Er,1Demofj5ntgDJxagDfAqQeH3FZua4zVBFA` - 141 bytes. Remember this number, too.

---

CryptBitcoin uses `ecdsa_sign` of pybitcointools for signing. `ecdsa_sign` uses `electrum_sig_hash` for hash calculating:

    # WTF, Electrum?
    def electrum_sig_hash(message):
        padded = b"\x18Bitcoin Signed Message:\n" + num_to_var_int(len(message)) + from_string_to_bytes(message)
        return bin_dbl_sha256(padded)

That's the last place in stacktrace. But let's look at `num_to_var_int`:

    def num_to_var_int(x):
        x = int(x)
        if x < 253: return from_int_to_byte(x)
        elif x < 65536: return from_int_to_byte(253)+encode(x, 256, 2)[::-1]
        elif x < 4294967296: return from_int_to_byte(254) + encode(x, 256, 4)[::-1]
        else: return from_int_to_byte(255) + encode(x, 256, 8)[::-1]

`from_int_to_byte(x)` is used here, and the error says about *128*. *106 < 128*, and signing *196* bytes works. *141 > 128*, and it doesn't work. Maybe the problem is here?

**Comment by imachug** [comment]
`from_int_to_byte(141)` returns `0x8d`. And the error message says about `0x8d`, BTW.

Wait a bit. I found this:
    def test_error_from_string(self):
        # See http://bugs.python.org/issue6289
        input = u"# coding: ascii\n\N{SNOWMAN}".encode('utf-8')
        with self.assertRaises(SyntaxError) as c:
            compile(input, "<string>", "exec")
        expected = "'ascii' codec can't decode byte 0xe2 in position 16: " \
                   "ordinal not in range(128)"
        self.assertTrue(c.exception.args[0].startswith(expected))
...in Python 2.7 libraries. Look at http://bugs.python.org/issue6289. Ascii codec refuses to decode bytes >= 128.

**Comment by imachug** [comment]
/cc @shortcutme 

    ContentManager.py
    625     new_content["signers_sign"] = CryptBitcoin.sign(
    626         "%s:%s" % (new_content["signs_required"], ",".join(valid_signers)), privatekey
    627     )

These lines throw exception in runtime, but they work if I run them with a simple `import` - `print` script.

**Comment by HelloZeroNet** [comment]
can you please attach your content.json here? (or send to me: tamas@zeronet.io)

**Comment by imachug** [comment]
I just made a new site and there is still an issue. Here is sample `content.json`:

    {
     "address": "197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyX",
     "address_index": 38134640,
     "background-color": "#FFF",
     "clone_root": "template-new",
     "cloned_from": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D",
     "description": "",
     "files": {
      "index.html": {
       "sha512": "b47188737048fb958728dd1eb429f4f786e061db1e1f6529b4db58b60150f261",
       "size": 1112
      },
      "js/ZeroFrame.js": {
       "sha512": "8bc18006f7bb457cca2338239ea345bc1db54a664b4bc9b8a34f4e4133d1776b",
       "size": 3816
      }
     },
     "ignore": "",
     "inner_path": "content.json",
     "modified": 1504200781,
     "postmessage_nonce_security": true,
     "signers": ["197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyX", "197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyY", "197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyZ", "197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyAFDS"],
     "signers_sign": "G1E/p9KgKUSvMqVYlXc+ZcmjWhLUxAUAuwMJOJBvvEipGHYWo3qI/qXccgUQpREoqW21+l+fnkjyucXm9uNNHfA=",
     "signs": {
      "197GZbac8xsfb7tzyM1Nehsp7U7SW1xXyX": "HLphMqK6iYu9a3LRUQgqDiOnM8Q7z/5yv+SCwJxoefzCaOL/0pyGsMpq8tmupdLrKGBVPO4ta3qDMRm5eWUsaMM="
     },
     "signs_required": 1,
     "title": "my new site",
     "translate": ["js/all.js"],
     "zeronet_version": "0.5.7"
    }

As I said before, nothing interesting except 4 signers.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in: https://github.com/HelloZeroNet/ZeroNet/commit/b584c586ecee3df0f1bb6890406771fc4213d04e
