### ISSUE TITLE
[Feature Request] Tracker Proxy

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#1108]
Recently, Resilio Sync is unavailable in China, because its tracker are blocked, and DHT support is removed in latest version.
As a censor-unfriendly software, ZeroNet's default tracker may be blocked, through people in China can add custom tracker, but new tracker can be information island and popular tracker will be blocked again. Seems ZeroNet's DHT support needs more time, but we can use some circumventing proxy such as [Psiphon 3](https://psiphon.ca) or [FireFly](https://github.com/yinghuocho/firefly-proxy) to connect to tracker(need send client's IP or other peers can't connect it), and connect to other peers directly.

**Comment by pahakalle** [comment]
Would routing tracker traffic trough tor work?

**Comment by skwerlman** [comment]
imo, we shouldn't rely on tor, since in areas where trackers are blocked, tor is likely to be blocked as well (and might even be illegal)

adding a generic proxy option which only applies to tracker requests seems reasonable (and would allow for tor usage as well)

**Comment by PeterCxy** [comment]
+1 for this solution. As long as there exist someone who has access to normal Internet, trackers can live on with this idea.

**Comment by rolders** [comment]
+1 for this - would be great to be able to use Resilio in China again without VPNs.

**Comment by slrslr** [comment]
[There](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1534344680_14UupgrdnT7Y8vMES7aqUFgD1fC5RYNrh8#comment_10_1Bcm7BpVuYsQaE8wGB8CrLWzef32rrMy1r) was an idea that other **peer/s can serve as a proxy to a trackers**

**Comment by tangdou1** [comment]
It can be clolsed. tracker proxy has been released.
