### ISSUE TITLE
[URGENT] ZeroNet security

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#1119]
*Conversation moved to ZeroMail. @shortcutme, I've sent you a mail. Please check as soon a possible. I'll publish mail here when this is fixed.*

**Comment by imachug** [comment]
> Internal error: Exception: No merger (MY_MERGED_SITE) permission to load: merged-SomeID/MY_MERGED_SITE/content.json (SomeID not in []) in UiWebsocket.py line 211 > MergerSitePlugin.py line 151 > MergerSitePlugin.py line 127 > MergerSitePlugin.py line 43

But Merger:SomeID appears in sites.json for MY_MERGER_SITE. And MY_MERGED_SITE has merged_type: "SomeID" in its content.json.

Interesting fact:

```javascript
zeroFrame.cmd("fileGet", ["merged-SomeID/MY_MERGED_SITE/content.json"]); // works
```

...but

```javascript
zeroFrame.cmd("fileGet", ["merged-SomeID/MY_MERGED_SITE/conten.json"]); // note a typo; hangs
zeroFrame.cmd("fileGet", ["merged-SomeID/MY_MERGED_SITE/content.json"]); // shows error
```

**UPD**
When running fileGet for merged-... paths, MergerSite plugin changes self.site address to merged, then executes query, then returns address back. I could reproduce this:

```javascript
zeroFrame.cmd("fileGet", ["merged-SomeID/MY_MERGED_SITE/conten.json"]); // note a typo; hangs
zeroFrame.cmd("fileGet", ["content.json"]); // returns MY_MERGED_SITE content.json
```

That means while first fileGet command is searching for conten.json, second fileGet has MY_MERGED_SITE address in self.site property and tries to read content.json from MY_MERGED_SITE.

A good solution is to create a new Site object for each fileGet, fileWrite, etc. commands.

**UPD URGENT**

Cors plugin is not really read-only. Using timing attack I can write data to CORS site if I already have Cors permission!

```javascript
zeroFrame.cmd("fileGet", ["cors-1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz/a/content.json", true, "text", 20000]); // Change address to ZeroID for ~300 hours
zeroFrame.cmd("fileWrite", ["content.json", ...]); // Write file
```

**Comment by HelloZeroNet** [comment]
For the record: It was fixed by https://github.com/HelloZeroNet/ZeroNet/commit/d3d748923287d2b4bf53fb93959c04a5531f9795

Thanks again for reporting!
