### ISSUE TITLE
SSL encrypted connections

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#112]
- [x] Workaround to fix gevent SSL bug on python 2.7.9

- [x] Benchmark SSL vs RAW connection speed
  It's around 6 times slower than raw connection when running client and server on the same machine.
  ```
10 worker:
# Raw: 		10000 req 1000009 kbytes transfered in 5.39999985695
# RSA 2048: 10000 req 1000009 kbytes transfered in 27.7890000343 using ('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256)
# ECC:		10000 req 1000009 kbytes transfered in 26.1959998608 using ('ECDHE-ECDSA-AES256-SHA', 'TLSv1/SSLv3', 256)
# ECC:		10000 req 1000009 kbytes transfered in 28.2410001755 using ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256)

100 worker:
# Raw:		10000 req 1000009 kbytes transfered in 7.02700018883 Mem: 14.328125
# RSA 2048:	10000 req 1000009 kbytes transfered in 44.8860001564 using ('ECDHE-RSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256) Mem: 20.078125
# ECC:		10000 req 1000009 kbytes transfered in 37.9430000782 using ('ECDHE-ECDSA-AES256-GCM-SHA384', 'TLSv1/SSLv3', 256) Mem: 20.0234375
  ```

- [x] Generate SSL cert&key PEM unique files on every startup
  I have tried to find a pure-python solution for this, but not found any, so using openssl command for it (openssl.exe bundled for windows).

 The key pem file creation is possible using [python-ecdsa](https://github.com/warner/python-ecdsa), but I could not found solution for the cert file:
 ```python
from ecdsa import SigningKey, VerifyingKey, NIST384p
sk = SigningKey.generate(curve=NIST384p)
print sk.to_pem()
vk = sk.get_verifying_key()
vk_pem = vk.to_pem()
print vk_pem
```

- [x] More lightweight solution to encryption to avoid compatibility problems (eg. we dont need HMAC because every client is trustless)

- [x] Transparently update the connection to ssl using wrapssl
 To make raw & encrypted connections work on same port:
 - Client connects to peer
 - Client checks if the other client supports ssl connection
 - If both fine then sends ssl handshake and update the connection transparently

 Later it can be changed to implicit SSL (automatically encrypt every connection) if this works on every machine.

**Comment by HelloZeroNet** [comment]
Unfortunately for some unknown reasons its does works well on some computer (slow, high memory usage), maybe its OS, OpenSSL or Python version bounded. 
I try to find alternative more lightweight solution to encryption...

**Comment by HelloZeroNet** [comment]
found a hack that helps openssl memory problems: https://journal.paul.querna.org/articles/2011/04/05/openssl-memory-use/

**Comment by HelloZeroNet** [comment]
Its up and working, I leave it some days of testing, after that I will publish it.
It takes more time to build up a connection, but after that there is no mayor overhead.
```
Reponse time from far server
with SSL:    1.036, 0.133, 0.133, 0.133
without SSL: 0.407, 0.133, 0.133, 0.133

Reponse time from close server
with SSL:    0.444, 0.019, 0.020, 0.019
without SSL: 0.067, 0.020, 0.019, 0.021

**Comment by HelloZeroNet** [comment]
Added in a78907cc9dc198dd28dce2204a8992cf9e00221f

**Comment by TheNain38** [comment]
I receive "ssl_error_rx_record_too_long" when trying to connect to https://127.0.0.1:43110

**Comment by HelloZeroNet** [comment]
The ssl support is for peer connections not for user interface (yet)

**Comment by TheNain38** [comment]
Ah, ok
