### ISSUE TITLE
Add siteUpdate to zeronet.py

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#1121]
Currently there is `siteSign`, `sitePublish`, etc. available via `python zeronet.py`. What about also adding `siteUpdate`? It would be interesting if ZeroNet is not running but you want to get the latest version of the site via script or something like that.

**Comment by HelloZeroNet** [comment]
Actually siteDownload does update the site if it's already exists.

**Comment by imachug** [comment]
@HelloZeroNet Yes, looks like that. Thanks!

**Comment by imachug** [comment]
BTW, Could you please check #1120?
