### ISSUE TITLE
Site:1MaiL5..Ju27 Verify sign error: VerifyError: We have newer (Our: 1488134162, Sent: 1464186584.58) in ContentManager.py line 807

### ISSUE THREAD

**Issue by hd999ljh** [HelloZeroNet/ZeroNet#1125]
i set up a zeronet on my vps, using ui_password to login and this appers.help please!

**Comment by skwerlman** [comment]
This error means a peer sent you an outdated copy of the zite. Assuming 0net continues to work after this message, its nothing to worry about.
On the other hand, if this is causing 0net to crash, a full log, os info, and version info would be really helpful in figuring out what went wrong.

**Comment by hd999ljh** [comment]
thanks man!
