### ISSUE TITLE
Blank page because GET *.js *.css return 403

### ISSUE THREAD

**Issue by m0len** [HelloZeroNet/ZeroNet#1129]

**Comment by hd999ljh** [comment]
when i use --ui_password and this happens, otherwise it doesn't.

**Comment by hd999ljh** [comment]
when i use nginx this happens, and the browser returns error code 403.

**Comment by hd999ljh** [comment]
here's my nginx conf
server {
    listen  443 ssl;
    server_name  zer0n.rocks;
    ssl_certificate /etc/letsencrypt/live/zer0n.rocks-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zer0n.rocks-0001/privkey.pem;
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
    add_header Strict-Transport-Security max-age=15768000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        autoindex on;
        proxy_pass http://127.0.0.1:43110;
        proxy_set_header Host "127.0.0.1:43110";
        proxy_http_version 1.1;
        proxy_read_timeout 1h;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
server {
    listen 80;
    server_name zer0n.rocks;
    return 301 https://$host$request_uri;
}

**Comment by HelloZeroNet** [comment]
Please try remove `proxy_set_header Host "127.0.0.1:43110";` and start zeronet using `--ui_host zer0n.rocks`

**Comment by anmol26s** [comment]
Hi
I have similar issue on yunohost after the update for yunohost. Working on Jessie. /css/all.css is loading, but the  zites are not rendering correctly and most of them are not showing pics. 
Nginx main conf: https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/nginx/server.tpl.conf
Nginx Zeronet config : https://github.com/YunoHost-Apps/zeronet_ynh/blob/master/conf/nginx.conf.template
Systemd: https://github.com/YunoHost-Apps/zeronet_ynh/blob/master/conf/systemd.service.template
