### ISSUE TITLE
Raspberry Pi 0 W problem again and again

### ISSUE THREAD

**Issue by Akito13** [HelloZeroNet/ZeroNet#1130]
```
pi@hostname:~/Public/ZeroNet-master $ python zeronet.py --verbose peerPing Kekgy
- Starting ZeroNet...
- OpenSSL loaded, version: 01000114F
- Version: 0.5.7 r2192, Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2], Gevent: 1.0.1
- Opening a simple connection server
TorManager Connecting to Tor Controller 127.0.0.1:9051
TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 165 > socket.py line 342
TorManager Starting self-bundled Tor, due to Tor proxy port 127.0.0.1:9050 check error: No connection
- Pinging 5 times peer: Kekgy:15441...
- Unhandled exception: 'NoneType' object has no attribute 'crypt'
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "/home/pi/Public/ZeroNet-master/src/main.py", line 496, in start
    actions.call(config.action, action_kwargs)
  File "/home/pi/Public/ZeroNet-master/src/main.py", line 155, in call
    func(**kwargs)
  File "/home/pi/Public/ZeroNet-master/src/main.py", line 433, in peerPing
    print "Response time: %.3fs (crypt: %s)" % (peer.ping(), peer.connection.crypt)
AttributeError: 'NoneType' object has no attribute 'crypt'

- Pinging 5 times peer: boot.zeronet.io:15441...
Response time: 1.441s (crypt: tls-rsa)
Response time: 0.168s (crypt: tls-rsa)
Response time: 0.165s (crypt: tls-rsa)
Response time: 0.165s (crypt: tls-rsa)
Response time: 0.169s (crypt: tls-rsa)
Reconnect test...
Response time: 1.093s (crypt: tls-rsa)
Response time: 0.163s (crypt: tls-rsa)
Response time: 0.163s (crypt: tls-rsa)
Response time: 0.168s (crypt: tls-rsa)
Response time: 0.620s (crypt: tls-rsa)
```

**Comment by HelloZeroNet** [comment]
is the `python zeronet.py --verbose peerPing boot.zeronet.io` says the same?

**Comment by Akito13** [comment]
@HelloZeroNet This one works! But my zite address is correct. I know it 100%, because it worked the first time. But after that, never again.

**Comment by HelloZeroNet** [comment]
peerPing only works on IP/Onion addresses

**Comment by Akito13** [comment]
Okay, well still doesn't solve the problem, that ZeroNet doesn't work on Raspi 0W and especially with Tor enabled it works even less.

`[15:23:58] Site:Kekgy Announce to 0 trackers in 0.324s, failed`

**Comment by Akito13** [comment]
`[15:24:35] Site:1Name2..hM9F Announce to 0 trackers in 0.013s, failed                                                         "icPi" 15:24 03-Oct-17[15:24:50] FileServer Internet offline`

**Comment by Akito13** [comment]
I need help! Why do I always hear chirping crickets when something is supposed to run on Raspi... Because if someone has a really stupid problem they get answers immediately. I need support!

**Comment by mmatoscom** [comment]
@Akito13 brother, the community needs help as well, and these inputs from you are valuable indeed.
However you can't really demand support for this. I own a rasp cluster of 5 boards myself, and I am fixing the kubernetes there in order to get all my personal tests up and running. 
Will probably have news this week, and will try to run a Zeronet node on each board. My main problem I am behind many firewalls and don't know if will it work anyhow as a way to publish distributed data, however will surely know if Zeronet will work there or not, and let you know. Don't take this personal, however the project guys are maybe dealing with some issue more people needs right away- other than PI support. I will try this week. cheers!

**Comment by Akito13** [comment]
@mmatoscom Considering the current evolution of (mainstream-)IT anything related to making something run on a microboard, especially the Raspberry Pi, should have #1 priority. IoT has just started and the demand rises every single day. Making it seem like this is not as important is therefore not depicting the current reality.

**Comment by radfish** [comment]
It is unlikely to do with Raspberry Pi. I get the same error if I try to ping non-existant host. Do you have Kengy IP in your /etc/hosts? What does `telnet Kengy 15441` say? As far as I understand, peerPing command takes a normal IP address or a normal DNS name that resolves to an IP address or a hostname assigned an address in /etc/hosts.

I run zeronet on an ARM board on Arch Linux ARM, all works.

**Comment by Akito13** [comment]
@radfish Okay, I didn't expect readers to take this so serious. Actually I don't care if peerPing works, at all. I just wanted to point out, that my zite isn't reachable anymore which is one part of a big problem when trying to run 0Net on Raspi. Now I know that peerPing only works for the normal net and not for 0net. Therefore I couldn't care less about peerPing right now. The big picture is that 0n is still not working on Raspi after such a long time of trying to get support and going different ways of running the program.

**Comment by Akito13** [comment]
It's pretty simple: I need support to make ZeroNet run on Raspi 0W. That's all.
