### ISSUE TITLE
Error "Missing parentheses"

### ISSUE THREAD

**Issue by lupa18** [HelloZeroNet/ZeroNet#1131]
When I download and run ZN using REAMDE instructions for Debian, I get this error: 
```
$ python zeronet.py 
  File "zeronet.py", line 10
    print "Starting ZeroNet", err
                           ^
SyntaxError: Missing parentheses in call to 'print'

```

**Comment by HelloZeroNet** [comment]
Thanks for reporting, running it using `python2 zeronet.py` should work. (I just updated the readme)

**Comment by slrslr** [comment]
Hello, on WIndows, i am getting this error, but for update.py:

> D:\ZeroNet\core>python update.py
>   File "update.py", line 23
>     print "Downloading from:", url,
>                             ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Downloa
> ding from:", url, end=" ")?
> 
> D:\ZeroNet\core>python2 update.py
> 'python2' is not recognized as an internal or external command,
> operable program or batch file.

When i tried to add parentheses, it also found other error so i do not know how to update zeronet on Windows beside via web interface.

**Comment by HelloZeroNet** [comment]
You need to install python2.7.x or just download it again, unpack and replace src and plugin directory from https://github.com/HelloZeroNet/ZeroNet/archive/master.zip
