### ISSUE TITLE
Site start problem with all.js

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1133]
Did a failed ZeroNet upgrade yesterday. Broken instance. Could not restart after upgrade. Some issue with a inconsistent bigfile parameter.  Sorry. Had to restart my comp. and lost the error message.
Could not fix the problem and did a new clean ZeroNet install. Marked my sites with "This is my site". 

OK start when local version = signed and published version and using js/all.js.zip/all.js.
Start is hanging when local version != signed and published version and using js/all.js

Found this lines in ui server log:
<pre>
[10:13:00] - Merged data/1JeHa67QEvrrFpsSow82fLypw8LoRcmCXk/js/all.js (0.10s)
[10:13:00] - UiWSGIHandler error: TypeError: argument of type 'bool' is not iterable in UiServer.py line 40 > pywsgi.py line 494 > UiServer.py line 91 > UiRequest.py line 130 > MutePlugin.py line 138 > UiRequest.py line 272 > UiRequestPlugin.py line 22 > TranslateSitePlugin.py line 25 > FilePackPlugin.py line 66 > UiRequest.py line 473 > BigfilePlugin.py line 111 > BigfilePlugin.py line 381
[10:13:00] Ui.UiServer 127.0.0.1 - - [2017-10-06 10:13:00] "GET /moneynetwork.bit/js/all.js HTTP/1.1" 000 - 0.193103
</pre>

all.js file is created on file system but is not downloaded to browser / not found under sources in browser console.

Did a siteSign without publish and no problems right now. all.js is being generated and used in browser without problems for some time. Now hanging again. Switching to an other computer with an old ZeroNet instance later today and I am hoping that will work without any problems.

**Comment by jaros1** [comment]
Did a siteSign without publish and no problems right now. all.js is being generated and used in browser without problems ...

**Comment by HelloZeroNet** [comment]
Thanks, fixed in https://github.com/HelloZeroNet/ZeroNet/commit/3030e00b218af0ab5a32df912608b2949e7f2470

**Comment by jaros1** [comment]
Have upgrated to rev3098. Still having a problem with hanging zite as descripted above. 
Now without any error messages in UI server log. siteSign without publish option works fine as a workaround

**Comment by jaros1** [comment]
Found the problem. I now sign and publish with all.js.zip and without all.js. No reason to publish with all.js when all.js.zip is the file being used in index.html. OK sign and publish.
Developing: switching to all.js, update some js and press f5 (site is hanging, no error messages and all.js is missing in content.json).
SiteSign: now both all.js and all.js.zip is in content.json. pass f5 and site is working ok in development mode
