### ISSUE TITLE
Request: some kind of routing in a sites content.json

### ISSUE THREAD

**Issue by Wieke** [HelloZeroNet/ZeroNet#1141]
Hi

I'm currently fiddling about with ZeroNet trying to build a single page application and have gotten to the point where I've got to start thinking about the routing. When using a more traditional client/server setup you'd configure the server to serve the same page regardless of the url given and let the clientside javascript handle showing the correct content. As far as I know this isn't possible with ZeroNet, it will always try to serve the file the url is pointing to.

Just to see if I could get the clientside routing thing to work if I could get ZeroNet to serve the right file, I hacked in the option ([gist](https://gist.github.com/Wieke/4491b9d66d47d1e1050d1317f8b299c8#file-uirequest-py-L490-L499)) for a zite to fall back on a configured path if the requested file couldn't be found. It worked, so it seems to me that giving a zite creator some rudimentary control over which file is served for which url could be useful.

Thanks,

Wieke

**Comment by krixano** [comment]
You can use javascript client-side routing. I created a library that helps with this called [ZeroFrame Router](https://github.com/krixano/ZeroFrame-Router). Here's a basic [demo zite](http://127.0.0.1:43110/1K2myjtjoEVpRC2JMieRL73ES4V4iLP2Ev/?/). All of my other projects also use the ZeroFrame Router along with the new Vuejs plugin I made so you can more easily use the plugin with vuejs. The best project you can look at to see how I use all this is probably [ZeroMedium](https://github.com/krixano/ZeroMedium).

Under the hood, all it does is run zeroframe's `wrapperPushState` and `wrapperPopState` commands and when you click a link to route to a page, it will run your controller function. This I believe is similar to how other zites are doing routing. If using the Vuejs plugin, it will switch a component you put into your root template to the component you defined for the route.

**Comment by HelloZeroNet** [comment]
Right now the sites routing using the "?" character, eg.:
http://127.0.0.1:43110/me.zeronetwork.bit/?Post/12h51ug6CcntU2aiBjhP8Ns2e5VypbWWtv/12gAes6NzDS9E2q6Q1UXrpUdbPS6nvuBPu/1507834329

Probably I would avoid complex routing rules in the client, but adding a default page for non-existent urls would be a good idea and you could also use it to parse the page url and route using javascript.

**Comment by Wieke** [comment]
@krixano Sweet. I'm using Vue as well and just noticed that vue-router tries to refresh the site when I hit forward. I'm going to give your router a try.

@HelloZeroNet Having some kind of fallback page would probably be sufficient. It's not like you could actually do something with complex routing in zeronet, right?

**Comment by krixano** [comment]
@Wieke  As a forewarning, my router is not really the best right now (there are things that need to be fixed, including with the vuejs plugin). However, it is usable.

**Comment by trenta3** [comment]
Please see issue #1548 and the associated PR #1549

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed in favor of #1548?
