### ISSUE TITLE
Unable to post updates as author/owner - Content signing failed Private key invalid! Valid signers ... missing documentation perhaps? 

### ISSUE THREAD

**Issue by tomachinz** [HelloZeroNet/ZeroNet#1142]
Hello, I've been cycling creating new sites and failing to port or merge my old site into the new one and feel maybe I am pasting over my old signatures or other keys. I understand the important keys I need to have are:

- the site key or address pubkey
- the owner authorised in content.json as signers
- but what on earth is "signs" ?? what should i put here?
- how do i know what value the HBuZ30 hash should be in signs?

The error I see in the browser notification popup: 
> Private key invalid! Valid signers: [u'1PvRsF1n......................'], Private key address: 1663jaG..................

 "address": "1PvRsF1nDwYAUD...................",
 "signers": ["1663jaGEnJSqtZb48oY..................."],
 "signers_sign": "HNpbCdFvyw.............................",
 "signs": {
  "1PvRsF1nDwYA................": "HBuZ30xjcw9TJ0bNL6C4LpdSiUlqp1RkebE52o..............."
 },
 "signs_required": 1,

**Comment by JazzMaster** [comment]
leave it or regen a new site to get the file again. throw away the new site. edit the site settings but leave the hashes and this stuff alone. I have to ignore the file when making updates. otherwise you get "update failed for 1 file"

**Comment by HelloZeroNet** [comment]
The ZeroNet client will automatically fill that for you. Just open the site in ZeroNet client, then sign it using the sidebar.

**Comment by tomachinz** [comment]
Thanks so much!! So when I ported over my code.... DO NOT wipe over this part yeah? This part is system generated and unique to the new site got it. Thanks.

**Comment by tomachinz** [comment]
Actually I'm still going round in circles on this.

So copy an old site to new I don't adjust:
"address" - new site address
"signers_sign" - leave as old its my sign anyhow? not sure if that ever changes. 
"signs" - leave as is

but I do adjust:
"signers" - new ID although it's same because it's me.


and that's all?

**Comment by krixano** [comment]
I don't think you have to anything. ZeroNet does everything for you when you "sign" and "publish" the zite.

**Comment by ndimario** [comment]
I'm having the same issue and cannot find a solution. I've used the supplied key from the tutorial and it keeps telling me "Content signing failed. Private key invalid! Valid signers". I've gone into ZeroNet and the users.json to find more keys and it changes nothing. Anyone ever figure this out?

**Comment by imachug** [comment]
@ndimario Can you post the part after `Valid signers: ` please?

**Comment by ndimario** [comment]
Content signing failed
Private key invalid! Valid signers: [u'1KugrB6oSZNHN96PM7CRNze7iL8Qs58QkL']

That key is the address of the site but with u' before it

**Comment by imachug** [comment]
@ndimario Okay, it should also say `Private key address: ... (maybe None)` or something like that. Does it?

**Comment by ndimario** [comment]
Content signing failed
Private key invalid! Valid signers: [u'1KugrB6oSZNHN96PM7CRNze7iL8Qs58QkL'], Private key address: 1J6csQA9K9NZaYUiCG5C2XQRF85yB5PGaJ

**Comment by imachug** [comment]
@ndimario Is `1KugrB6oSZNHN96PM7CRNze7iL8Qs58QkL` or `1J6csQA9K9NZaYUiCG5C2XQRF85yB5PGaJ` the address of your site? If one of them is, make sure you add `includes` to root `content.json`, create the correct `data/users/content.json` (like in the example), and sign them all in the sidebar.

**Comment by ndimario** [comment]
It seems that I'm a little dislexic and overlooked something simple. My data/users/content.json was actually named contents.json. So when I signed it (using the sidebar) it created a content.json. 

So this problem was solved by 
- recreating the data/users/content.json (using the code from the tutorial)
- deleting data/users/contents.json
- signing data/users/content.json

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this issue be closed?
