### ISSUE TITLE
Signing error when adding "optional" to content.json

### ISSUE THREAD

**Issue by doublec** [HelloZeroNet/ZeroNet#1144]
I get a "Site error: argument of type 'NoneType' is not iterable" when doing a siteSign of a site where I've added a `optional` key to `content.json` when that key did not exist before. A stacktrace when I remove the try/catch:

    - Unhandled exception: argument of type 'NoneType' is not iterable
    Traceback (most recent call last):
      File "zeronet.py", line 19, in main
        main.start()
      File "src/main.py", line 496, in start
        actions.call(config.action, action_kwargs)
      File "src/main.py", line 155, in call
        func(**kwargs)
      File "src/main.py", line 230, in siteSign
        succ = site.content_manager.sign(inner_path=inner_path, privatekey=privatekey, update_changed_files=True, remove_missing_optional=remove_missing_optional)
      File "src/Content/ContentManager.py", line 577, in sign
        helper.getDirname(inner_path), content.get("ignore"), content.get("optional")
      File "src/Content/ContentManager.py", line 524, in hashFiles 
        self.hashFile(dir_inner_path, file_relative_path, optional=True)
      File "plugins/Bigfile/BigfilePlugin.py", line 245, in hashFile
        if content and file_relative_path in content.get("files_optional"):
    TypeError: argument of type 'NoneType' is not iterable

It seems to look for a "files_optional" key and if it doesn't exist the error happens due to trying it iterate over `None`. If I add a line:

    "files_optional": { },

to `content.json` then the sign works and there is no error.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it's fixed in Rev3104: https://github.com/HelloZeroNet/ZeroNet/commit/a66b71fb9c328977cff594abf015297c19866c68
