### ISSUE TITLE
"Shutdown" button is not displayed properly.

### ISSUE THREAD

**Issue by clemat** [HelloZeroNet/ZeroNet#1148]
Hello,

On zeronet 0.6.0 (rev 3105) the "Shutdown" button in the Main menu isn't displayed properly.
On Chromium (61.0.3163.100p0) you don't see it at all, the menu hard-stop where it displays the version number. (no way to scroll or arrow down).
![zero_chrome](https://user-images.githubusercontent.com/32833540/31602742-84c940a6-b24d-11e7-9708-d21df84ee99e.png)

On Firefox (56) it isn't displayed properly, can't read it, but you can see the top (white) of the button which makes it still clickable.
![zero_firefox](https://user-images.githubusercontent.com/32833540/31602859-c7d007ae-b24d-11e7-9bc8-199b35d7c21f.png)

I've tried to maximize windows/reduce fonts etc...without success.

Is there another 'clean' way to shutdown? (something better than ctrl-c the zeronet.py).

Thanks.
Regards,
-- clemat

**Comment by HelloZeroNet** [comment]
It should be fixed now
