### ISSUE TITLE
how to use zeronet with tor on win10

### ISSUE THREAD

**Issue by wzhb** [HelloZeroNet/ZeroNet#1150]
I do not know ho to edit torrc. 
how to edit?
# Tor config for ZeroNet

DataDirectory data
DirReqStatistics 0
GeoIPFile geoip\geoip
GeoIPv6File geoip\geoip6

# Log notice file data\notice.log

ControlPort 49051
SOCKSPort 49050

CookieAuthentication 1

**Comment by HelloZeroNet** [comment]
You don't have to edit it, you can enable usage of Tor on every connection by clicking on Tor: Avaliable > Enable tor for every connection

**Comment by wzhb** [comment]
I clicking it.  And it does not work. I am from China.

**Comment by l5h5t7** [comment]
Tor is blocked in China, so you need an anti-censorship proxy or pluggable transport to connect to Tor.
If you have an anti-censorship proxy such as [Shadowsocks](https://github.com/shadowsocks/shadowsocks-windows), you can add `Socks5Proxy 127.0.0.1:1080` to a newline. If your anti-censorship proxy provide a http proxy(must support HTTP CONNECT), add `Socks5Proxy 127.0.0.1:1080` to a newline.
If you don't have any anti-censorship proxy, you can try these: [Psiphon 3](https://s3.amazonaws.com/psiphon/web/mjr4-p23r-puwl/zh/download.html), [Firefly](https://github.com/yinghuocho/firefly-proxy), [Lantern](https://github.com/getlantern/lantern).
If you tried the tools above and can't connect, try [meek](https://trac.torproject.org/projects/tor/wiki/doc/meek), [read this](https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-tor-work-if-my-isp-or-goverment-blocks-it) to know how to modify ZeroNet's config to use Tor browser's proxy and control port.

**Comment by wzhb** [comment]
I will try， thanks
