### ISSUE TITLE
when I use “tor always” some problem was happen

### ISSUE THREAD

**Issue by wzhb** [HelloZeroNet/ZeroNet#1151]
I can not link any site and update
![qq 20171016223209](https://user-images.githubusercontent.com/14255631/31617520-02c1e520-b2c2-11e7-8015-7ff90aed7fb1.png)

**Comment by HelloZeroNet** [comment]
What platform are you using? What does it says for Tor status on ZeroHello page?

**Comment by wzhb** [comment]
win10
