### ISSUE TITLE
what happen？

### ISSUE THREAD

**Issue by wzhb** [HelloZeroNet/ZeroNet#1152]
I reloaded zeronet， and restored user.json. But I found that I lost control of the original blog

**Comment by wzhb** [comment]
http://127.0.0.1:43110/1G5bve8RqNK7Gm8fheEvPfqqhokUAYYmh4/

**Comment by wzhb** [comment]
I cannot publish new article
![qq 20171017023219](https://user-images.githubusercontent.com/14255631/31628495-6f79d3aa-b2e3-11e7-9be1-b81cf4d11d74.png)
 click the button， there is no reaction. and I can't edit any post article. why?

**Comment by HelloZeroNet** [comment]
do you have your site's address in your users.json? does it have "pirvatekey" entry in that section?

**Comment by wzhb** [comment]
em....which is the privatekey?
![qq 20171017095719](https://user-images.githubusercontent.com/14255631/31643180-a3191c1e-b321-11e7-80a7-2fb3fa587935.png)
and how can I control my site?
thx

**Comment by krixano** [comment]
auth_privatekey is the private key for your authentication (your user). privatekey is your zite's private key.

**Comment by HelloZeroNet** [comment]
@krixano is right. 
Looks like you have the privatekey in place, so you should be able to edit it. When you open the sidebar (by dragging the topright button to left) do you have "this is my site" enabled? and what happens if you press the sign button on the bottom of that panel?

**Comment by wzhb** [comment]
![qq 20171017095719](https://user-images.githubusercontent.com/14255631/31657094-1b649138-b360-11e7-8d95-f45e1b6eb1c9.png)
and If I edit some article，I can not post
![qq 20171017172719](https://user-images.githubusercontent.com/14255631/31657266-84d8dc0a-b360-11e7-9f6d-effbb3612985.png)

**Comment by wzhb** [comment]
who can help me

**Comment by HelloZeroNet** [comment]
@wzhb When you open the sidebar (by dragging the topright button to left) do you have "this is my site" enabled? and what happens if you press the sign button on the bottom of that panel?

**Comment by wzhb** [comment]
My English is not well, maybe I cannot understand you well. this is my sidebar
![qq 20171018223432](https://user-images.githubusercontent.com/14255631/31724632-df24d87c-b454-11e7-912f-657d3e9fd6f0.png)
![qq 20171018223502](https://user-images.githubusercontent.com/14255631/31724637-e1863796-b454-11e7-9886-080e8dd97622.png)
![qq 20171018223616](https://user-images.githubusercontent.com/14255631/31724641-e45cf040-b454-11e7-8796-20d29e97d1ef.png)

**Comment by wzhb** [comment]
now I cannot open my blog normally
![qq 20171018224017](https://user-images.githubusercontent.com/14255631/31724833-56c7f562-b455-11e7-8795-08ac459f6f20.png)

**Comment by imachug** [comment]
@wzhb Is this still an issue to you? @HelloZeroNet Can this be closed for inactivity? We won't be able to help here anymore I think
