### ISSUE TITLE
How-to implement non-internet networks (Bluetooth, Wifi, Radio Comm, Meshnets, etc.)

### ISSUE THREAD

**Issue by hwegge2** [HelloZeroNet/ZeroNet#1153]
As mentioned in the ZeroNet presentation, it was noted that it could be implemented for non-internet networks (Bluetooth, WiFi, Radio Comm, Meshnets, etc.) 

[https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000&slide=id.g11ba381582_0_0](url)

Assuming you would be on a private intranet for this, what modifications to the code base would need to be implemented in order to support such a change. 

This is also assuming a private distributed ledger would have to be made in order to point and update to a private block-chain.

**Comment by HelloZeroNet** [comment]
I think it should work this way right now:
 - create a bootstrapper client on the local network by renaming plugins/disabled-Bootstrapper to plugins/Bootstrapper
 - Add `trackers = zero://ip.of.bootstrapper.client:15441` to zeronet.conf
 - start zeronet with `zeronet.py --ip_external yourlocalip`

Required improvements:
 - Implement local peer discovery eg.: https://pypi.python.org/pypi/zeroconf
 - Don't send local peers via PEX
 - Add ipv6 support

**Comment by unsystemizer** [comment]
> This is also assuming a private distributed ledger would have to be made in order to point and update to a private block-chain.

What is that for?

**Comment by hwegge2** [comment]
@unsystemizer  This would be for running a private instance of ZeroNet in an Intranet Type environment. (i.e. setting up a private Namecoin Ledger)
[](https://themerkle.com/altcoins-dying-make-one-hour/)

**Comment by unsystemizer** [comment]
Well, that seems out of scope, for ZN to create forks of each plugin such as Namecoin.

Separately, it just doesn’t make sense to fork Namecoin for a private network. Who’s going to mine it and why would they do that? This is a rhetorical question (it’s out of scope it seems to me, so the answer likely doesn’t matter).

**Comment by hwegge2** [comment]
Not quite, it was actually discussed as a use case in documentation.  As note above the plug-in already is implemented for a bootstrapped build. A majority of altcoins are forks of other crypto-currencies, so the logic behind this would be to perhaps implement a blockchain agnostic feature to perhaps support any coin with name value stores (ie. Emercoin) in order to further decentralized DNS and identity management.
