### ISSUE TITLE
Scrolling sidebar is interrupted by Globe scroll in sidebar, would you disable zooming of the Globe?

### ISSUE THREAD

**Issue by DeviatedMind** [HelloZeroNet/ZeroNet#1156]
When I drag the ZeroNet icon in every website to reach the sidebar of that site, when I try to scroll down or up, the Globe zooms in and out and prevents scrolling properly. Would you disable zooming of the Globe by mouse? It has a low resolution so zooming into it is a useless feature anyway.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, it's changed in Rev3126: https://github.com/HelloZeroNet/ZeroNet/commit/09413f5fc794616ce61d357611141462d59ca04f
