### ISSUE TITLE
Wappalyzer chrome extension prevents ZN sites from loading until I click on it's button.

### ISSUE THREAD

**Issue by Ornataweaver** [HelloZeroNet/ZeroNet#1157]
My browser is Iridium: https://alternativeto.net/software/iridium/
After clicking the extension button in the menubar the site starts loading.
I need Wappalyzer for studying the web and learning front-end coding.

**Comment by gitbugged** [comment]
Sounds like a bug in Wappalyzer, not ZeroNet.

https://github.com/AliasIO/Wappalyzer

**Comment by DeviatedMind** [comment]
I know it seems so, but Wappalyzer does not prevent any other site from loading. Or maybe because I'm familiar with ZeroNet environment I don't know other websites when they are affected.

**Comment by Ornataweaver** [comment]
The problem doesn't exist anymore.
