### ISSUE TITLE
how to back-up blog and my ID？

### ISSUE THREAD

**Issue by wzhb** [HelloZeroNet/ZeroNet#1163]
I want to back-up my ID and the blog I usually visit. And I have my own blog, I also want to back-up it

**Comment by HelloZeroNet** [comment]
To backup your identity you have to save data/users.json the sites are also in this directory

**Comment by HelloZeroNet** [comment]
To backup your identity you have to save data/users.json the sites are also in this di

**Comment by grez911** [comment]
...rectory
