### ISSUE TITLE
running zeronet on a vps ,how to close ssh connection from this vps without killing "python zeronet.py" thread?

### ISSUE THREAD

**Issue by emacsenli** [HelloZeroNet/ZeroNet#1168]
running zeronet on a vps ,how to close ssh connection from this vps without killing "python zeronet.py" thread?

can zeronet.py run as a daemon or backgroud?

**Comment by skwerlman** [comment]
use the `screen` command: https://www.mattcutts.com/blog/a-quick-tutorial-on-screen/

**Comment by emacsenli** [comment]
now I run zeronet this  way ,problem solved 


nohup python zeronet.py --ui_ip "my vps ip" &
