### ISSUE TITLE
Change source code style to PEP8

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#117]
https://www.python.org/dev/peps/pep-0008/

Probably required modifications:
 - [Use spaces instead of tabs.](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)
 - [Imports to separate lines](https://www.python.org/dev/peps/pep-0008/#blank-lines)
 - [Change module names to lower_cased](https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions)
 - Other things?

Possible problems:
 - The [update script](https://github.com/HelloZeroNet/ZeroNet/blob/master/update.py) does not handle  the renames/file removes. Some os does not allow to have the same file with upper cased and lower cased form in the same directory, so the update will fail. So we need to modify the update script and wait some time until everyone update it.
 - I'm a TAB person, going to need some time to get used to spaces :)

**Comment by Idealcoder** [comment]
Most editors let you set it so that when you press TAB key it inserts 4
spaces. Thats how I live with it.

BTW, there is a special config file you can put in project root to tell
editors whether to use tabs or spaces:

http://editorconfig.org/

**Comment by HelloZeroNet** [comment]
Yeah, the editor makes its easier, but for me it was easier to jump between indents with one cursor button press and delete an indent with one backspace.

The editor should detect if the current file using space or tabs, but for some unknown reasons this feature does not works in my sublime text. (`"detect_indentation": true`)

So i written a quick plugin for it, maybe its also useful for someone else: [detect_indent.py](https://gist.github.com/HelloZeroNet/e6343d9ee8e9968ac54e)

**Comment by HelloZeroNet** [comment]
Done in: https://github.com/HelloZeroNet/ZeroNet/commit/b5ecb62bc6e81ebb5e23855bb2195a9c9f802f7e?w=0

Tools used:
- [Python PEP8 Autoformat](https://packagecontrol.io/packages/Python%20PEP8%20Autoformat)
Settings:
```
{
    // autoformat code on save ?
    "autoformat_on_save": false,

    // enable possibly unsafe changes (E226, E24, W6)
    // aggressive level, 0 to disable:
    "aggressive": 0,

    // list codes for fixes; used by --ignore and --select
    "list-fixes": false,

    // do not fix these errors / warnings (e.g. [ "E501" , "E4" , "W"])
    "ignore": [],

    // select errors / warnings (e.g. ["E4", "W"])
    "select": [],

    // Maximum line length
    "max-line-length": 300  // I wanted to format long-lines myself
}
```
- [Python Flake8 Lint](https://packagecontrol.io/packages/Python%20Flake8%20Lint)
Settings:
```
{
	"lint_on_save": false,
	"pep8_max_line_length": 130,
	"report_on_success": true,
	"ignore": ["N802"]  // We use camel cased function names
}
```
