### ISSUE TITLE
Allow modals for iframe

### ISSUE THREAD

**Issue by 0polar** [HelloZeroNet/ZeroNet#1170]
> http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/12h51ug6CcntU2aiBjhP8Ns2e5VypbWWtv/12gAes6NzDS9E2q6Q1UXrpUdbPS6nvuBPu/1509344044

```
Ignored call to 'confirm()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
```

I want built-in modals, I don't want simulated modals.

**Comment by HelloZeroNet** [comment]
why not, added: https://github.com/HelloZeroNet/ZeroNet/commit/c3250378ee110721fc919e1ecfeb4c1040839f3f
