### ISSUE TITLE
ZeroHello zearch not working after adding categories

### ISSUE THREAD

**Issue by Akito13** [HelloZeroNet/ZeroNet#1171]
After adding the "All, Comment, Topic, Post, Mention" categories the search doesn't work anymore, because whenever you put something in the search bar it always keeps loading without showing the actual results. Was tested several times over several days since that update.

**Comment by HelloZeroNet** [comment]
in theory i fixed it some days ago. Maybe I forgot to sign + publish it, so I just did it again. Please try again and if it's still not working for you, check the JS console (F12) for error.

**Comment by Akito13** [comment]
It works now!
