### ISSUE TITLE
There is a way to check the number of peers of a site?

### ISSUE THREAD

**Issue by Axeltherabbit** [HelloZeroNet/ZeroNet#1175]
I've found nothing in the docs, a simple python script maybe usefull.

**Comment by HelloZeroNet** [comment]
The data/sites.json has "peer" filed for every site you seeding.

**Comment by Axeltherabbit** [comment]
Ok thanks but in this way i must download the site, i can't only check the peers number.
Or i wrong something?

**Comment by HelloZeroNet** [comment]
Currently it's not possible without downloading the site.
