### ISSUE TITLE
How is security maintained with a shared private key?

### ISSUE THREAD

**Issue by harrisonturton** [HelloZeroNet/ZeroNet#1176]
Hello,

I'm reading through the source for [ZeroBoard](https://github.com/HelloZeroNet/ZeroBoard), and [ZeroTalk](https://github.com/HelloZeroNet/ZeroTalk) . I noticed in ZeroBoard that the private key is visible in the [source code](https://github.com/HelloZeroNet/ZeroBoard/blob/master/publisher/add.php). If each user [starts sharing the site as they visit it](https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000&slide=id.g30df42c44_2_107), then every user would have a copy of the sourecode, correct?

How does ZeroNet allow sites to self-publish without other users accessing the private key, and potentially signing malicious content?

Cheers.

**Comment by skwerlman** [comment]
add.php is not included in content.json, so it's not shared.

**Comment by krixano** [comment]
zite's don't have the private key in their source code, therefore it isn't shared with anyone. The private key is stored in the users.json file in the zeronetroot/data directory. By signing your zite, the client is able to access this file to get the private key to sign with.

Also, in the sourcecode you linked, at the very top you can see that the private key is equal to "xxxxxxx". A private key can't be that, which means it was redacted. The file is also a php file, ZeroNet Zites don't use php files. My guess is that this php file is on another server that the ZeroBoard zite accesses. On that server, it would have the private key not redacted of course. However, not all zites access the internet in this way. The only ones that do (as far as I know) are ZeroId, ZeroBoard, and Kopy Kate.

**Comment by harrisonturton** [comment]
Ah, so the .php file would have to be hosted on a server? Is this how multi-user sites are managed - the site (shared to other users) sends a request to the server, which posts something to it's database, and then re-publishes the site? This can't be right, because that's centralised.

Are there any resources that I can read about distributed multi-user zites? I tried to go through the documentation and examples but I feel that it's barely touched on, unless there's something I missed.

Thanks for your help @krixano!

**Comment by krixano** [comment]
No. Remember when I said only ZeroId and ZeroBoard connect to the internet. The php file is on a server that only ZeroBoard is connected to. It's use I dont know about for ZeroBoard (but it's *not* for databases/multi-user stuff). But connecting to the clearnet for ZeroId is used for authentication and to ensure usernames are unique. **No other zite connects to the internet in this way** (except for KopyKate which connects to WebTorrent, and a few other zites like that). The databases in *all* zites are decentralized. There's tutorials on the ZeroNet Dev Center that may help you here: http://127.0.0.1:43110/14pM9huTYzJdyQyHRj6v2kfhMe8DrxwpGt/?/tutorials/the_basics (Note that this is a ZeroNet zite - you need ZeroNet downloaded, or use a proxy like www.bigcat.tk).

**Comment by krixano** [comment]
Furthermore, here's a little bit of how multi-user and database stuff works. The information in a zite's database is stored in a json file. When your client gets an updated json file, it reloads the information from and and put's it in an sqlite database that isn't shared (only the json files are shared). These json files are signed by their respective owner. If the zite has database information stored in a json file, it's signed by the zite owner's private key. If a user posts something on a zite, they get their own json file that they sign with their user private key.

**Comment by krixano** [comment]
To add more perspective on ZeroBoard: ZeroBoard is a pretty old zite, which is why it still has to connect to a server on the clearnet (it was never updated). Here's a quote directly from Nofish regarding ZeroBoard:
> ZeroBoard was the first site on ZeroNet when multi-user sites was not possible, so the messages are signed and distributed by contacting the site owner which was done by a simple http request.
> 
> Possible solutions
> 
>     Drop this site
>     Re-create the site with self-signed id certificates
>     Move the adder script to different domain and ip
>     Add a whisper protocol to ZeroNet that allows messages to be distributed between peers just like updates. (Cons: spam solution?)
>     Add a direct message option to ZeroNet API that allows direct messages to be sent to an ip address using ZeroNet protocol. Pro vs current http solution: it does not requires https since ZeroNet protocol supports self-signed cert with pinning.
