### ISSUE TITLE
Possible Typo in code

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1177]
`pice_size`: Should this be 'piece_size' instead?

https://github.com/HelloZeroNet/ZeroNet/blob/00b6842f355c4ac82fa99f1910533e7e49eb471d/plugins/Bigfile/BigfilePlugin.py#L147

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroNet/commit/bc1d79a07d976d521aa9900233749f481aff6fb3
