### ISSUE TITLE
BigfileUploadInit not compatible with merger site feature ?

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#1178]
I am trying to upload a file in a merger site but it doesn't seems to be able to do it.

`file_info = self.site.content_manager.getFileInfo(inner_path)` this line is indicated as the faulty one. `getFileInfo` return false.

**Comment by rllola** [comment]
I have added this api in `MergerSitePlugin.py`
```
   def actionBigfileUploadInit(self, to, inner_path, *args, **kwargs):
        return self.mergerFuncWrapper("actionBigfileUploadInit", to, inner_path, *args, **kwargs)
```

It is able to upload the file.

**Comment by HelloZeroNet** [comment]
It wasn't initially, but it was fixed in Rev3125: https://github.com/HelloZeroNet/ZeroNet/commit/99e5af67b75f6543bcba7a2e49322a7699d1a7cb
There was other bigfile related problems with merger sites, but it should work fine now.

**Comment by rllola** [comment]
I have updated my version. I confirm it is working well.
Thank you.
