### ISSUE TITLE
I can't share newly created sites

### ISSUE THREAD

**Issue by viktorstrate** [HelloZeroNet/ZeroNet#1181]
When i create a new blank site, from "zerohello" -> "create new, empty site"
I then sign the site, when I try to access the newly created site from another computer, it says "no peers found"

I can not publish any new sites I create. Is there somthing i am missing?

**Comment by HelloZeroNet** [comment]
You are not missing anything it should work. 
Is your or the other client has opened port? 
Do you have Tor enabled?
Have you tried to sign/publish the site (eg. using the sidebar) again?

**Comment by MuxZeroNet** [comment]
Have you tried advertising your site? :smile:

**Comment by viktorstrate** [comment]
@HelloZeroNet, I have the port open and pointing on one of the computers, but both of the computers are on the same network.

**Comment by HelloZeroNet** [comment]
Probably that's why they can't find each other. The local network peer discovery not implemented yet and it puts the client's external ip:port to blacklist to avoid connecting to itself.
You can try start one of the clients using `--fileserver_port 15442` to avoid this.

**Comment by viktorstrate** [comment]
Ah okay, thank you for the help :)
