### ISSUE TITLE
Can I run ZeroNet on remote server (or VPS)?

### ISSUE THREAD

**Issue by lewisxy** [HelloZeroNet/ZeroNet#1187]
I wonder if it is possible to run the ZeroNet Daemon on a Remote Server (with static IP, and online all day), and map the port to the local computer. For example, I run the ZeroNet on a server with IP 12.34.56.78 and expose the port 43110. Does ZeroNet provide or recommend any functionality that allows me to access ZeroNet from that server(act as a proxy) (12.34.56.78:43110) from the local environment?

**Comment by mkg20001** [comment]
You can use iptables to redirect all packets from `localhost:43110` to `12.34.56.78:43110` or use ssh port-forwarding if you don't want to expose the server to the public.

SSH: `ssh -f -L 43110:localhost:43110 user@12.34.56.78` (needs to be run every reboot)

IPtables port forwarding (requires server to be publicly accessible): don't know. just google it.

**Comment by MuxZeroNet** [comment]
[tmux](https://www.youtube.com/watch?v=5iXzqN8-34E) is recommended in this case, to avoid killing the daemon process when you log out of the SSH session.

**Comment by skwerlman** [comment]
it's also possible to use `screen` to achieve the same thing. alternatively, if you don't care about being able to resume the session, you can use `bash -c 'python zeronet.py &'` which will spawn the process in the background, detached from your session.

**Comment by grez911** [comment]
@lewisxy Probably you can find this useful: https://zeronet.readthedocs.io/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine

**Comment by lewisxy** [comment]
Thanks everyone for the advice.
I use the Nginx reverse proxy approach with HTTPS and basic authentication ([this](https://github.com/HelloZeroNet/ZeroNet/issues/1189)) that should provide enough security.
I don't want to use iptables approach because the connection is not encrypted. And prolong ssh connection is also not as versatile as https in this case, but I appreciate you all for advice.
