### ISSUE TITLE
Disable Multiuser Master Seed Popup Notification

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1190]
Just set up a ZeroNet proxy as a gateway to a single ZeroNet site accessible through a web address on the clearnet. Everything's working now, and I've cleared all sites besides the one I want to proxy, and have disabled users from adding new ones with the `--multiuser_no_new_sites` option.

Now, all that's left is that the little "Hello, Welcome to ZeroProxy!" popup slides in from the right each time a new user visits the page.

Is it possible to disable this notification? Users do not need to interact with the site so an account is not necessary.

Thank you!

**Comment by grez911** [comment]
It's definitely possible to do by commenting some code in this [file](https://github.com/HelloZeroNet/ZeroNet/blob/ebdb1ed322ee1b3639d914e619a06b47201c71d4/plugins/disabled-Multiuser/MultiuserPlugin.py#L65).
Alternatively you can add a new option (e.g. `--multiuser_no_greeter`) in this plugin to disable greeting message and make a pull request.

**Comment by HelloZeroNet** [comment]
I'm planning to change it to display only when the user registers itself an ID (eg. using ZeroID)

**Comment by anoadragon453** [comment]
@HelloZeroNet That'd be best I think, yeah.

Any way I could enable automatic anonymous registration with the ability to then like/comment? My site is currently just a cloned ZeroBlog. Having registered and anonymous comments/liking would be ideal.

**Comment by mkg20001** [comment]
@anoadragon453 Simply create your own certificate authority (https://zeronet.readthedocs.io/en/latest/site_development/cert_authority/) and then publish the private key for it or create a server that returns certificates for random usernames. And then of course add your own ca to the content.json

**Comment by anoadragon453** [comment]
@mkg20001 Cool, will look into that. Thanks.

**Comment by HelloZeroNet** [comment]
From Rev3151 it will only show the seed on certificate add: https://github.com/HelloZeroNet/ZeroNet/commit/9df86ecaa976c2dbf86b5965b9df61109a41781e

**Comment by anoadragon453** [comment]
Thank you!
