### ISSUE TITLE
How can I import a list of sites?

### ISSUE THREAD

**Issue by Liu233w** [HelloZeroNet/ZeroNet#1191]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0
  * Operating system: windows 10
  * Web browser: Firefox 57
  * Tor status: not
  * Opened port: yes

### Step 2: Describe the problem:

I need to remove my zeronet data files include the site files but keep the site list so that I can re-download them. Is there any way to export all the site I has connected to a list and import them in a new zeronet client?

**Comment by grez911** [comment]
Site list stored in `data/sites.json`, you can just copy this file to a new zeronet client.

**Comment by Liu233w** [comment]
It doesn't work. If I removed all the directory (like `data/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D`) but keep `data/sites.json` , the sites won't show up in `ZeroHello` , only the `ZeroHello` and `ZeroName` are there.

![default](https://user-images.githubusercontent.com/16333687/33107678-54b5bd70-cf73-11e7-9002-b864376476de.png)

**Comment by Liu233w** [comment]
I just tried to remove `data/content.db` along with the site directorys, it doesn't work too.

**Comment by HelloZeroNet** [comment]
Currently it won't work without moving the site data directories, but it would be a great addition.

**Comment by HelloZeroNet** [comment]
Added in Rev3153: https://github.com/HelloZeroNet/ZeroNet/commit/6b92d011d24c708674891f174a8d7f9c5153d7ef
All missing site from sites.json will be downloaded at startup.
