### ISSUE TITLE
Question - Port 43110 needed?

### ISSUE THREAD

**Issue by DarkBlaez** [HelloZeroNet/ZeroNet#1195]
Just a quick question. Is port 43110 just used for accessing the web sites? As in, can I just disable or block this port, keeping 15441 open for supporting zeronet as a node. Or truly does a site have to be accessed from the individual node for it to be pulled and peer distributed?

Thanks DB

**Comment by HelloZeroNet** [comment]
It's only required to access the websites, so you can block 43110  (by default it only allows connection from your computer)
