### ISSUE TITLE
ZeroNet Video html5 fullscreen

### ISSUE THREAD

**Issue by DATSEC** [HelloZeroNet/ZeroNet#1197]
Hi, I'm interested in the ability to move iframe from zeronet to support fullscreen video.

Is it possible to add these configurations?
```
allowfullscreen="true"
webkitallowfullscreen="true"
mozallowfullscreen="true"
```
I would like to see fullscreen was normal and not by reference as it is now.

**Comment by HelloZeroNet** [comment]
Actualy there is already a "wrapperRequestFullscreen" API call to do that. It was undocumented, but just fixed that issue: https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#wrapperrequestfullscreen

**Comment by DATSEC** [comment]
@HelloZeroNet This function is similar to F11
There is a more modern version that I could embed in <video> </ video>?

**Comment by HelloZeroNet** [comment]
I have tried allowfullscreen, but it's not possible to add it after the iframe was rendered. (after the request of fullscreen approved)

**Comment by DATSEC** [comment]
@HelloZeroNet Than it threatens if allowfullscreen function will be permanently on?

**Comment by HelloZeroNet** [comment]
Well, why not... added in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/0009b1b7d1d3fc62a0b126b8ed1d66730e75242b

**Comment by DATSEC** [comment]
@HelloZeroNet Thankee!
