### ISSUE TITLE
Cannot insert multiple allowed hosts in zeronet.conf

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1199]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0
  * Operating system: Linux
  * Web browser: N/A
  * Tor status: N/A
  * Opened port: N/A

### Step 2: Describe the problem:

The `ui_host` config parameter (and possibly other parameters) is not able to handle multiple options when specified within the config file, whereas you can do so on the command line.

Config file:
```
# Doesn't work at all
ui_host sub1.zeronet.io, sub2.zeronet.io

# Doesn't work at all
ui_host sub1.zeronet.io sub2.zeronet.io

# Doesn't work, only records one of the domains
ui_host sub1.zeronet.io
ui_host sub2.zeronet.io
```

Specifying on the command line:

```
# Does work!
python ./zeronet.py --ui_host sub1.zeronet.io sub2.zeronet.io
```

So it is a bug with the config file loading code. `argparse`, which parses from the command line, works fine.

I ran into this while trying to have a single ZeroNet daemon act as a ZeroProxy coming from two different subdomains of the same website. Running the daemon with the options on the command line works but it would be ideal if it was in the config file so it wouldn't have to be retyped/remembered all the time :)

**Comment by HelloZeroNet** [comment]
please try this way:
```
ui_host =
 sub1.zeronet.io
 sub2.zeronet.io
```

**Comment by anoadragon453** [comment]
Yep, working!

As an aside, searching zeronet.readthedocs.io for "config" shows no results, but I'm sure config is mentioned at least once in the docs...? Why is their search so terrible?
