### ISSUE TITLE
ZeroBoard: Submitting messages containing Chinese characters to get "Message submit failed! Parsing parameters... Please try again later".

### ISSUE THREAD

**Issue by ivanhjc** [HelloZeroNet/ZeroNet#1203]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0
  * Operating system: Windows 7
  * Web browser: Chrome Version 62.0.3202.94
  * Tor status: waiting
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:
I can't submit messages containing Chinese characters. Whenever I do so I get the prompt "Message submit failed! Parsing parameters... Please try again later". This only occurs on ZeroBoard though.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
There is lots of other Chinese messages on the board, so I think the problem should be somewhere else

**Comment by funny110** [comment]
More Chinese messages on ZeroBoard are SHIT politics.

**Comment by HaoyeTang** [comment]
indeed most chinese messages are uneducated anti-communist shit talks

**Comment by skwerlman** [comment]
@funny110 @HaoyeTang this is an issue tracker, not a place to talk about others' politics.

**Comment by imachug** [comment]
AFAIK `Message submit failed! Parsing parameters... Please try again later` means `you post too much`
