### ISSUE TITLE
Ability to submit sites for review to a ZeroProxy

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1209]
[Discussion on ZeroTalk](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1513428479_1EQuGEmS5J8SQ1xA6MM9KfubBb71uxiLvs/Feature+request+Proxy+Submit+new+site+for+review)

Currently we can allow users to add any site to a ZeroProxy, or allow none at all. It would be nice if there were some middle-ground where we could allow users to suggest a site, and the ZeroProxy owner could prune through the list and allow ones they deem suitable.

A button such as 'Suggest Proxy Add Site' or something similar to new pages which haven't been downloaded yet by a `no_new_sites` proxy would be very welcome.

Thanks!

**Comment by HelloZeroNet** [comment]
I would recomment to create a ZeroTalk clone for the proxy and the user would use it for submission to the admin.

**Comment by anoadragon453** [comment]
That's a decent idea, yeah. Any way to link that from the "new sites not allowed" page?

**Comment by imachug** [comment]
@anoadragon453 Change line `47` of file `plugins/Multiuser/MultiuserPlugin.py`.

`Adding new sites disabled on this proxy` is text that gets printed. Replace it with whatever you want (no HTML).

**Comment by anoadragon453** [comment]
Cool, that should do it then, thanks guys!
