### ISSUE TITLE
If I published with wrong advanced time than true time, I can't correct and publish more.

### ISSUE THREAD

**Issue by 0polar** [HelloZeroNet/ZeroNet#1216]
ZeroNet version: 0.6.0

Unfortunately, because I set wrong time, I signed my files with `"modified": 1513904603` and published, but true time is 1513865595.
Therefore, before true world reach the wrong time, I can't publish anything. If publish successfully, it will rollback after some time.

**Comment by HelloZeroNet** [comment]
It's your responsibility to keep your time in-sync, ZeroNet can't really do anything about it, but to avoid irreversible problem you won't be able to publish a file in the far future (t + 1day)
