### ISSUE TITLE
ZeroNet target="blank"

### ISSUE THREAD

**Issue by ZeroTube** [HelloZeroNet/ZeroNet#1217]
Does not work
`target="blank"`
Opens corrupted sites

**Comment by AnthyG** [comment]
Yes, you have to use the `wrapperOpenWindow`-command, for example like follows:
```
function openNewTab(url) {
    page.cmd("wrapperOpenWindow", [url, "_blank", ""]);
    return false;
}
```
`page` being your ZeroFrame-extend.

**Comment by HelloZeroNet** [comment]
Unfortunately this is a restriction of the browsers: Web pages opened with target=_blank from sandboxed iframe keeps the sandboxing, so won't be access cookies and many other things. It works fine if the users opens the link to new tab (eg. with middle mouse click)
Possible solution:
 - Open to current tab with target=_top
 - As @AnthyG said: use the wrapperOpenWindow API call

To automatically fix all target=_blank links:
```js
window.onclick = function (e) {
    if (e.target.getAttribute("target") == "_blank") {
        e.preventDefault()
        page.cmd("wrapperOpenWindow", [e.target.href, "_blank", ""])
    }
}
```

**Comment by ZeroTube** [comment]
@HelloZeroNet Perhaps it's worth adding this code as a standard for target = "blank"

**Comment by parkour86** [comment]
+1 to the idea of adding it as a standard.
