### ISSUE TITLE
server error on windows

### ISSUE THREAD

**Issue by benjin12345678** [HelloZeroNet/ZeroNet#1219]
### Step 1: Please describe your environment

  * ZeroNet version: newest one
  * Operating system: windows 10
  * Web browser: chrome
  * Tor status: not available/always/disabled
  * Opened port: yes
  * Special configuration: ____

every time i try to go to a page it doesnt work tried re installing 3 times still didnt work

![1111111](https://user-images.githubusercontent.com/34801557/34323326-114afae6-e83c-11e7-9e6f-b9adbf047b79.png)

**Comment by MuxZeroNet** [comment]
1. Check your zip file. Does `ZeroNet-master/src/Ui/template/wrapper.html` exist?
2. Check your installation. Does `ZeroNet-master/src/Ui/template/wrapper.html` exist?
3. Check your anti-virus. Have you tried rebooting into "Safe Mode" and unpacking your zip file again?

**Comment by imachug** [comment]
@HelloZeroNet Can this be closed for inactivity?
