### ISSUE TITLE
Apply for funding to Open Technology Fund

### ISSUE THREAD

**Issue by ValdikSS** [HelloZeroNet/ZeroNet#1220]
I think Zeronet conforms with the Open Technology Fund's "Internet Freedom Fund" and has a good chance to receive funding. 
https://www.opentech.fund/requests/internet-freedom-fund
The deadline is 1st of January.

What do you think about that, @HelloZeroNet?

**Comment by MuxZeroNet** [comment]
The deadline is in 24 hours. @shortcutme If not started, you should start writing the application right now.

**Comment by HelloZeroNet** [comment]
Thanks for the reminder, just filled out the form. Let's hope for the best :)

**Comment by ValdikSS** [comment]
What was the result? Did you get a reply?

**Comment by ValdikSS** [comment]
@HelloZeroNet, here's another distributed networks support initiative, from Samsung:
https://samsungnext.com/whats-next/introducing-the-samsung-next-stack-zero-grant/

**Comment by HelloZeroNet** [comment]
Thanks for the info I have no plans to apply, but if someone wants to do with a ZeroNet connected project, then I happy to help: tamas@zeronet.io
