### ISSUE TITLE
What is the meaning of pinning the file in ZeroNet Hello?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1221]
Windows 10, latest ZeroNet, http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/
"Files" tab i see some files are "PINNED" and i see no explanation what that means and what happen if i UNPIN it. Thank You

**Comment by imachug** [comment]
`pinned` files (you can only pin big and optional files) aren't deleted by automatical garbage collector. When you download a file, you automatically pin it. If you unpin it, it will be removed soon, but that's all.

**Comment by HelloZeroNet** [comment]
small correction: only big files (>20MB) get automatically pinned (https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/OptionalManager/OptionalManagerPlugin.py#L134), smaller files will be automatically deleted if you reach the storage limit (10% of your free space by default, but you can change it on files tab)
