### ISSUE TITLE
IOError: [Errno 2] No such file or directory: u'da

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#1222]
I spotted this strange line in the log:
```
[12:41:46] FileServer GetFile read error: IOError: [Errno 2] No such file or directory: u'da
```

### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0
  * Operating system: FreBSD 11.1
  * Tor status: always
  * Opened port: no

**Comment by skwerlman** [comment]
what line followed this? it looks like a partial unicode string to me (hence the `u` prefix before the quote)

**Comment by yurivict** [comment]
Ah yes, this is most likely caused by halfway truncated log lines.
