### ISSUE TITLE
[feature] ZeroTalk, ZeroBlog - add search functionality?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1224]
Hello,

can You please add search field into ZeroTalk, ZeroBlog. I think it can greatly increase usefulness of the whole product

Similar requests:
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1514127848_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS
http://127.0.0.1:43110/0list.bit/?Topic:1_1CpQAAfxYtFqAGfoGd6gdaN6jerQGoknzV

One can currently search in connected sites via [ZeroHello](http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/) (there is a serch field), but more handy for noobs might be direct search on a site one is at.

**Comment by imachug** [comment]
Please post this to [ZeroTalk](https://github.com/HelloZeroNet/ZeroTalk) and [ZeroBlog](https://github.com/HelloZeroNet/ZeroBlog) repositories. This repository is for ZeroNet core.

**Comment by slrslr** [comment]
Here i created it
ZeroBlog: https://github.com/HelloZeroNet/ZeroBlog/issues/55
ZeroTalk: https://github.com/HelloZeroNet/ZeroTalk/issues/10
