### ISSUE TITLE
ZeroHello slow Newsfeed / connected sites search (2+ minutes to load)

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1226]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0 rev3177
  * Operating system: Win.10 64b
  * Web browser: Firefox 57.0.2 (64-bit)
  * Tor status: always
  * Opened port: not opened anything
  * Special configuration: 5400 RPM HDD

### Step 2: Describe the problem:

Hello, always i open or refresh ZeroHello page (in Firefox or Tor browser), it takes 2-3 minutes for the white/search section of the ZeroHello page to load. The dark section on the left (list of the sites) loads quickly. Then it shows example: "from 10 sites in 180.42s"

http://127.0.0.1:43110/Stats shows:
Db:
- 50.586s: data/content.db
- 226.250s: data/1FREEMLT3GSta6TynuAC9EWM5mXCnrxkiu/data/zeroblog.db
- 226.248s: data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db
- 226.241s: data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/data/zeroblog.db
- 226.239s: data/1MALTALKxyXgvWSqZkcdjsh4LUqqL2bKFe/data/users/zerotalk.db
- 265.914s: data/1PjYBsgsWAfsPE4sQnSNg1t31CNwW4DZWw/data/zeroblog.db
- 265.904s: data/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t/merged-GitCenter/GitCenter.db
- 265.900s: data/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/merged-CDN/zeroverse.db
- 265.853s: data/186THqMWuptrZxq1rxzpguAivK3Bs6z84o/data/users/zerotalk.db
- 265.848s: data/1Kp5xdjQyrPth5mEJsn6NDBKZxcaeYz86N/data/zeroblog.db
- 1484.691s: data/1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH/merged-ZeroMe/ZeroMe.db
- 54073.490s: data/1PLAYgDQboKojowD3kwdb3CtWmWaokXvfp/data/play.db

Task manager and System explorer apps do not shows HDD being overloaded during ZeroHello load..

I am sorry if this issue is known.

**Comment by HelloZeroNet** [comment]
What does the per-site breakdown says? You can see it by click on "from xx sites in x.xx s" text in the search input area

**Comment by slrslr** [comment]
@HelloZeroNet 

> click on "from xx sites in x.xx s"

I tried it in FIrefox and TorBrowser but it does not show anything, i tried to refresh page and restart zeronet, but do not show, it show only when i not clicked it, tried to search something and then clicked it and then it show, but i assume You want to see results when it loads slow (2-3 minutes), but there it do not show anything when i click it. waited a few minutes.
Here i pasted the log of the zeronet, it shows some errors: https://pastebin.com/YfKh3293 (replace "9" by "0")

When i click it "from xx sites in x.xx s" and then try to search something, it do not reacts, no animation wheel of searching, no results.

When i refresh page, wait 3 minutes until newsfeed load, then click text "from xx sites in x.xx s"

nothing happens, so i click "Files" tab on the top, only one site appear:

ZeroTalk15.59 MB + 0.00 KBOptional ♡ 0.1 ⋰  8.53 MB ⋱  89.53 MB

So i click "Sites" tab and nothing happen, it do not switch to sites, its like frozen.

**Comment by HelloZeroNet** [comment]
Is there any error in the js console? (F12)

**Comment by slrslr** [comment]
In Firefox, i did F12, "Console tab" found error:

> Error: div.FeedList.search had a div child added, but there is now more than one. You must add unique key properties to make them distinguishable. all.js:443:35
	checkDistinguishable http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:443:35
	updateChildren http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:487:21
	updateDom http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:588:23
	updateChildren http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:471:31
	updateDom http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:588:23
	update http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:606:17
	doRender http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:837:17

Line 443 is:

>                            throw new Error(parentVNode.vnodeSelector + ' had a ' + childNode.vnodeSelector + ' child ' + 'added, but there is now more than one. You must add unique key properties to make them distinguishable.');

When i reloaded ZeroHello page, the only error seen in Firefox Developer console was:

> The connection to ws://127.0.0.1:43110/Websocket?wrapper_key=350c7***longstringhere*** was interrupted while the page was loading. all.js:69:16

Line 69 is:

>       this.ws = new WebSocket(this.url);

When i clicked "from xx sites in x.xx s" then this error appeared in Developer console:

> TypeError: site is undefined
[Learn More]
all.js:2671:11
FeedList.prototype.renderSearchStat
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2671:11
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
map self-hosted:297:17 FeedList.prototype.render
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2748:92
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
doRender
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:836:36

Then i clicked "Files" tab on ZeroHello and then "Sites" tab and another error appeared in Dev. console:

> TypeError: site is undefined
[Learn More]
all.js:2671:11
FeedList.prototype.renderSearchStat
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2671:11
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
map self-hosted:297:17 FeedList.prototype.render
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2748:92
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
replace
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:872:29
ZeroHello.prototype.setProjectorMode
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4738:9
Head.prototype.handleModeClick
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:3477:9
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:3278:56
exports.createProjector/projectionOptions.eventHandlerInterceptor/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:820:24

**Comment by HelloZeroNet** [comment]
According to 'Error: div.FeedList.search had a div child added, but there is now more than one. You must add unique key properties to make them distinguishable. all.js:443:35' it looks like one of the sites you following does not providers unique id for the feed item.
I have added a fix for it (https://github.com/HelloZeroNet/ZeroHello/commit/5dac15190e3bc3b0664baf17d8ebef2a9ea0afe0) please check if it's fixed it.

**Comment by slrslr** [comment]
@HelloZeroNet 
I have not found file "FeedList.coffee" (which you apparently modified) in my zeronet directories using Windows search. So i can't modify the file on my computer.
I tried to click three dots on ZeroHello click version and click Update button, waited a minute, then clicked windows zeronet tray icon and selected to quit the app. After start, it took 200 seconds to load newsfeed on zeronet page. When i clicked the "from xx sites in x.xx s" on the ZeroHello, the Developer console of the Firefox shown error

> TypeError: site is undefined
[Learn More]
all.js:2682:11
FeedList.prototype.renderSearchStat
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2682:11
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
map self-hosted:297:17 FeedList.prototype.render
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2759:92
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
doRender
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:836:36

Then i click "Files" tab, and then when i click "Sites" tab i see error:

> TypeError: site is undefined
[Learn More]
all.js:2682:11
FeedList.prototype.renderSearchStat
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2682:11
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
map self-hosted:297:17 FeedList.prototype.render
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2759:92
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2253:56
replace
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:872:29
ZeroHello.prototype.addRenderer
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4798:7
ZeroHello.prototype.setProjectorMode
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4821:9
ZeroHello.prototype.route
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4876:14
ZeroHello.prototype.setUrl
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4909:7
ZeroHello.prototype.handleLinkClick
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4924:9
bind/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:4765:56
exports.createProjector/projectionOptions.eventHandlerInterceptor/<
http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:820:24

but site is not stuck like before, but it redirects properly to default ZeroHello where is site list, but i still have to wait couple of minutes until newsfeed loads. This time it took: "from 13 sites in 328.39s" Thank you

btw., mentioned error:

> The connection to ws://127.0.0.1:43110/Websocket?wrapper_key=350c7***longstringhere*** was interrupted while the page was loading. all.js:69:16

continue to show up.

**Comment by HelloZeroNet** [comment]
I published the modification to ZeroHello, so it should automatically update your all.js file.

Please try this one:
 - Add `site.log.debug("Newsfeed query taken: %.3fs" % (time.time() - s))` line after https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/Newsfeed/NewsfeedPlugin.py#L89
 - Restart ZeroNet
 - Check log/debug.log file for "Newsfeed query taken" lines and see which site blocks the update.

**Comment by slrslr** [comment]
@HelloZeroNet

I did that and Quit & Start Zeronet, waited for newsfeed to load (90s) and then copied debug.log file in Zeronet log directory contents. [Here it is](https://www.protectedtext.com/934856586256) (pw: 489) i do not know what to look for exactly, file is huge.
Pls let me know what else i can do to find cause. Thank you

**Comment by HelloZeroNet** [comment]
According to the log it looks like it was caused by a site with no database, but with a feed signup. From Rev3178 will skip these sites (https://github.com/HelloZeroNet/ZeroNet/commit/92e353be40533140b783ede48010566848da9805) please update and try again

**Comment by slrslr** [comment]
@HelloZeroNet 
I think that you fixed this issue. The newsfeed loads under 1 second now and when i click thru the ZeroHello interface (files, sites, "from xx sites in x.xx s"), no error appears in Firefox developer console and all seem to work. Thank you

**Comment by slrslr** [comment]
@HelloZeroNet 

Hello, after one month i am back with the issue of slow loading newsfeed search. This time my Zeronet version is 0.6.1 rev3234 (OS is same, Win. 10 64bit)

In TorBrowser i tried to search one word on ZeroHello in newsfeed, there is a turning wheel (loading) and no results. So i tried to open ZeroHello in Firefox, but it is not opening (Waiting for 127.0.0.1...), then after a wile TorBrowser loaded some results in newsfeed, it took 190 seconds around and ZeroHello in FIrefox also loaded.
Isn't it wrong that ZeroHello was prevented to be loaded in Firefox during search query in TorBrowser?
When i click the "14 results from 218 sites in 191.09s" it does nothing, not show any details. So i click developer console in TorBrowser and click again, then it shows:
...
[FeedList] Updating feed (Done in 500ms)  all.js:25:7
hideProgress all.js:593:7
TypeError: site is undefined[Learn More]  all.js:2460:11
hideProgress all.js:593:7
...

i see that also other elements on the ZeroHello do not react on click - until i refresh page.

In the log file i seen example thse lines:
[2018-02-01 11:09:30,947] DEBUG    FileServer Conn#65080 127.0.0.1    [v2] > Socket error: AttributeError: 'bool' object has no attribute 'connection' in Connection.py line 198 > Connection.py line 354 > FileServer.py line 45 > FileRequest.py line 92 > FileRequest.py line 416
[2018-02-01 11:09:35,707] DEBUG    FileServer Conn#65081 37.146.79.200 [?] > Closing connection: Send error: [Errno 10057] Poadavek odesln nebo prjmu dat nebyl povolen, protoe soket nen pripojen a (pri posln po datagramovm soketu volnm sendto) nebyla dodna dn adresa, waiting_requests: 1, sites: 2, buff: 0...
[2018-02-01 11:09:45,706] INFO     Site:1Magne..XgQv [FAILED] 37.146.79.200:15441: {'exception': 'Timeout'}

Here is the log during the search to its end: https://defuse.ca/b/b1DsyZas8y0HRv26JPUpog (password: zeronet)

Yesterday, the search was also delayed more than 2 minutes and details was shown and ZeroMe was causing majority of the delay.

**Comment by HelloZeroNet** [comment]
@slrslr I made some modifications/fixes, please see if it's working now.

**Comment by slrslr** [comment]
@HelloZeroNet i selected to update zeronet from zerohello. after reconnect i did several searches, all good, but around 5th one ended up being stuck not giving any results and this is in developer console:

> 
> hideProgress all.js:593:7
> TypeError: body[0] is undefined[Learn More]  all.js:2339:1
> 	FeedList.prototype.formatBody http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2339:1
> 	FeedList.prototype.renderFeed http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2403:12
> 	bind/< http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2031:56
> 	map self-hosted:275:17
> 	FeedList.prototype.render http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2549:12
> 	bind/< http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:2031:56
> 	exports.createProjector/doRender http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/js/all.js:920:36
> hideProgress all.js:593:7

so as previously i tried to open zerohello via other browser (Firefox) and it opened without issue (in my previous reply in this issue, it was NOT loading during the time of unfinished search in TorBrowser Zerohello newsfeed). The search not completed even after like 6 minutes. My search query was a single word. I do not know what to search in log to discover if the cause is Tor timeout or Zeronet. Interesting observation:
- In torbrowser the search is still not finished.
- i open firefox and search for same word, it shows results quite quickly
- i open new tab in torbrowser and search for same word, the search does not finish
> so i have out of three searches, only one in firefox finished, both tor browser searches are loading and no result

**Comment by HelloZeroNet** [comment]
I have added a new fix for the problem based on your log.

I tried to reproduce the long search problem in Tor browser, but I wasn't able to do it yet. I will keep experimenting with it. Does the Zeronet.exe (or python.exe) process has high cpu usage when the search slows down?

**Comment by slrslr** [comment]
@HelloZeroNet 

> I have added a new fix
I do not know if it mean i should update zeronet or apply the fix somehow manually on Windows. So i updated. Then I did 20+ searches, all quick and good, CPU usage is raised, but just for a moment. I will update in case issue reappear.

**Comment by imachug** [comment]
@slrslr Based on nofish's edits, you should have uploaded ZeroHello only.

**Comment by slrslr** [comment]
@HelloZeroNet 

Hello, before 5 days i was saying following on this page:

> Yesterday, the search was also delayed more than 2 minutes and details was shown and ZeroMe was causing majority of the delay which is strange while site has enough peers.

Today it happened to me again. Search took ~70 seconds and when i clicked for details, it shown:

ZeroMe | Posts | 29.321s
ZeroMe | Comments | 33.02s
other sites under 1s

if you need more details, please let me know what to lookup in logs. thank you

**Comment by imachug** [comment]
@slrslr Please send the results of http://127.0.0.1:43110/Benchmark

**Comment by slrslr** [comment]
@imachug [here](https://pastebin.com/rfG7dxqa) they are, thank you

**Comment by imachug** [comment]
I thought that DB queries may be slow, but it doesn't look like that. How many hubs are you seeding?

**Comment by slrslr** [comment]
@imachug i am sorry, i am just a user, i do not know where can i see how many. But i used [this zite](http://127.0.0.1:43110/0hub.bit/) and selected to add 30 sites.

**Comment by slrslr** [comment]
@HelloZeroNet this issue is closed, but in last days i seen it to appear again.
The search not finished at all, i quit and start zeronet then i see "0 results from 231 sites in 115.72s"
Many sites under second, but:
ZeroMe | Posts | 25.96s
ZeroMe | Comments | 20.335s
New GFW Talk | Topics | 0.059s
New GFW Talk | Comments | 31.55s

On stats page, New GFW Talk is like this:
address | connected | peers | content.json | out | in
19BPUZYAdCMxExKHoVSG3cG95wfUfFTEC9 | [423] | 1/91/181 | 4193 (loaded: 12) | 11669kB | 47781kB
rev3234, Connections (76, total made: 854), Windows 10, Firefox, Tor available, port open

On Zerome, i think i used [this zite](http://127.0.0.1:43110/0hub.bit/) and selected to add 31 merger zites into zerome.

I do not know what to look in logs.

**Comment by slrslr** [comment]
@HelloZeroNet yes, when i search for "From A User's Perspective" (no quot. marks) on ZeroHello, the CPU gets overloaded for some seconds and then i still get no results.

**Comment by slrslr** [comment]
@HelloZeroNet 
searched for: lan
1764 results from 256 sites in 91.23s
Dark ZeroMe | Posts | 2.122s
Dark ZeroMe | Comments | 5.527s
ZeroTalk | Topics | 1.355s
ZeroTalk | Comments | 30.784s <--
Peeper | Posts | 1.671s
Peeper | Comments | 6.525s
New GFW Talk | Topics | 0.265s
New GFW Talk | Comments | 6.648s

is this normal to wait 1,5 minute for the search results? By the way during that time, other zites loading but does not opening. Thank You

**Comment by HelloZeroNet** [comment]
Yeah ZeroNet is single-threaded now, I planning to change it when moving to Python3.

what size is your data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db file?
does entering the second search also takes that long?

For me: ZeroTalk | Comments | 0.098s, but I have only 26 search-compatible sites.

**Comment by slrslr** [comment]
> what size is your data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/zerotalk.db file?

It is 21MB, @HelloZeroNet it is not a problem related to some zite database, it happen for various sites, example now for ZeroMe

ZeroMe | Posts | 19.503s
ZeroMe | Comments | 14.291s

and ZeroTalk was OK (under 1s), i tried to repeat the search for same phrase (after clearing search field) and it was quick. It is not too rare case this slow search issue. The CPU is not exhausted during slow search.

**Comment by slrslr** [comment]
@HelloZeroNet Hello, the issue is still there, it is slow very frequently. it also happen often that newsfeed itself (without searching, just opening zerohello) loading slow, example 43 seconds. But after couple of seconds once loaded, the speed counter is reset to show feed loaded in less than 1 second. @HelloZeroNet i recommend You to visit 250 or more different zeronet sites so you connect 250+ sites and add 30 merger sites to zerome at http://127.0.0.1:43110/0hub.bit/ and use zeronet that way, i think you may spot issues i am experiencing.

The newsfeed speed counter (11 results from 257 sites in 8.60s) is also made to reset the time the search took to complete. It takes more than one minute usually, but then i see 8.6 seconds.
