### ISSUE TITLE
image upload don't work for specif user.

### ISSUE THREAD

**Issue by btripoloni** [HelloZeroNet/ZeroNet#1227]
Hi guys i am creating a simple image board cloned from zupport.
zupport: http://127.0.0.1:43110/zupport.bit/

One of my users is having a problem, the images that he upload don't work.
At the begining of site he can post normaly, but now every image that he upload don't work.

The only image that work is the thumbnail.
zupport uses the nullchan script to create that image board and he create that thumbnail image that works.

he is using a mac
the ZeroNet version 0.6.0
he already re install Zeronet but does not work.

What could be the problem?
net neutrality?
Is he using a mac?

Thanks.

Edit -----
I found the problem, looks like that the images has some type of bad encoding or something like that, after the image was compressed again the upload works.

**Comment by imachug** [comment]
Anything in console?

**Comment by imachug** [comment]
Can this be closed?

**Comment by imachug** [comment]
@HelloZeroNet can this be closed?
