### ISSUE TITLE
[suggestion] Sign & Publish in one button?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1229]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0 rev3178
  * Operating system: Windows 10
  * Web browser: Tor borwser
  * Tor status: always

### Step 2: Describe the problem:

When i do "Publish" (without "Sign"), it tells me: "Content published to 5/5 peers." which mislead me into believing changes was published to all people.
If i have to do "Sign" before "Publish" then i think it should tell me: "You have not signed changes, content was not published to peers." Why it should tell me publishing was done if there was no signed changes so nothing new was published to peers?
It may be helpfull if the button is more noob friendly like [ Sign & Publish changes ] or the notification popup messages more talkative so even noob knows what to do.
Thank You

**Comment by krixano** [comment]
I sometimes sign without publishing. One of the reasons for this is if I update my database schema, I can sign it to test it out. After testing, then I publish.

**Comment by imachug** [comment]
@krixano:

> I sometimes sign without publishing. One of the reasons for this is if I update my database schema, I can sign it to test it out. After testing, then I publish.

Technically your changes can be downloaded by other peers without publishing. In your case, you can press `Reload database`.

> Otherwise, your idea of it telling you whether there is unsigned changes would be good.

I am not sure, but that would be difficult to check. Example: you recieve update from another computer, then press `Publish`. We think nothing changed, but for ZeroNet it did.

> But I don't think it's necessary because whenever I want to publish something, I always hit the Sign button first regardless of if there were any changes.

There are cases when you want to only `sign`, only `publish` or both `sign & publish`. Adding all will take much space.

**Comment by slrslr** [comment]
So if i click only "Publish" without "Sign", Zeronet have no reasonable/quick way to discover if i made any changes on my site, so it can not tell me in return "You have not changed your site, nothing new was published to peers" and instead it is confusing me by saying "Content published to 5/5 peers."?

**Comment by imachug** [comment]
E.g. you are offline, you sign, then you get online. Now you should publish - why sign then?

**Comment by krixano** [comment]
> > But I don't think it's necessary because whenever I want to publish something, I always hit the Sign button first regardless of if there were any changes.
> There are cases when you want to only sign, only publish or both sign & publish. Adding all will take much space.

I thought it was clear that I was talking about the notification to sign if you click publish without sign and *not* the part about combining the buttons, especially since I give a reason at the beginning for *not* doing this.

**Comment by krixano** [comment]
> I am not sure, but that would be difficult to check. Example: you recieve update from another computer, then press Publish. We think nothing changed, but for ZeroNet it did.
Actually it's probably not that hard. Just check whether the hashes of the files match what's in the content.json file, if not then there were changes.

If ZeroNet received an update, then the content.json with the new hashes would also be updated, which would work correctly with what I said above.

**Comment by imachug** [comment]
@krixano: When I told `There are cases when you want to only sign, only publish or both sign & publish. Adding all will take much space.` I didn't say it was an answer to your idea. It was just another option.

**Comment by imachug** [comment]
> If ZeroNet received an update, then the content.json with the new hashes would also be updated, which would work correctly with what I said above.

Then write some pseudocode which will check if it is necessary to sign. Maybe there is such possibility which I didn't find yet.

**Comment by slrslr** [comment]
Other thing may be a drop-down menu called example "Sign / Publish", when you click it, you can choose all three options, while third one is "Sign & Publish".
Or the Publish button triggering some check and returns error if there are changes but are not Signed. It would tell noob that his changed was not sent to peers instead of making him believe otherwise by telling "Content published to 5/5 peers."

**Comment by imachug** [comment]
> btw, it gets really annoying when people don't read something correctly.

Sorry, but it gets really annoying when you say that something is annoying.

**Comment by krixano** [comment]
get hashes of current 
Check if all hashes match the hashes in content.json
   If they do there were no changes.

Not that hard.

**Comment by imachug** [comment]
@krixano:

And without hashing current? Some repositories (e.g.) are big - hash them all?

**Comment by krixano** [comment]
Obviously leaving out the ignored ones. It's literally the same as what Sign does.

**Comment by imachug** [comment]
@slrslr: `Content published to 5/5 peers` means that `content.json` was really published to those peers. They *did* recieve them. But they noticed that they have the same `content.json` and reject them.

**Comment by imachug** [comment]
> Obviously leaving out the ignored ones. It's literally the same as what Sign does.

Wait, are you asking me to ignore all the `.git` of Git Center repositories? Welp, that is a solution :D

**Comment by krixano** [comment]
No, I was talking about the ignored files in the ignore regex.

**Comment by krixano** [comment]
You said you didn't know how it would be done. I gave *one way* to do it. You said nothing about performance. Yes, perhaps the performance isn't the best, but I was suggesting one way to do it.

**Comment by krixano** [comment]
> @krixano: When I told There are cases when you want to only sign, only publish or both sign & publish. Adding all will take much space. I didn't say it was an answer to your idea. It was just another option.

You put it right after a quote by me, so...

**Comment by imachug** [comment]
@krixano: Then maybe we should add a `noob` option to `zeronet.conf` (wait, if someone find `zeronet.conf` they aren't noobs) which will be not-so-good-performance-but-easier-to-use.

**Comment by imachug** [comment]
> You put it right after a quote by me, so...

My and your ideas were practically about the same, and I thought it is logical to separate flies and cutlets.

**Comment by krixano** [comment]
Would looking at modified dates of the files work?

**Comment by krixano** [comment]
> Sorry, but it gets really annoying when you say that something is annoying.
I've only ever said this once for anything online, so your statement is incorrect as I've never said something is annoying before.

**Comment by imachug** [comment]
@krixano: Yep, you never said `... is annoying`. Instead, you said `that is rude`.

**Comment by imachug** [comment]
> Would looking at modified dates of the files work?

Maybe that would be faster. Yeah, a good idea.

**Comment by krixano** [comment]
> @krixano: Yep, you never said ... is annoying. Instead, you said that is rude.
Actually I haven't. I've only ever said certain things *sounded* rude to me. And I've only every said this twice (maybe 3 time, but no more than that I don't think)

**Comment by imachug** [comment]
@krixano Okay, let's close this quarrel now :)

**Comment by krixano** [comment]
I will stop this quarrel, but I just have to point something out. You did the exact thing that I said I found annoying. I don't know if you intended to or not, but you should be able to understand my frustration:

> > Obviously leaving out the ignored ones. It's literally the same as what Sign does.
> 
> Wait, are you asking me to ignore all the .git of Git Center repositories? Welp, that is a solution :D

I said to leave out (don't sign) ignored ones (files) and you say I said that you should ignore `.git` files. I'm not really sure where you got that from.

**Comment by imachug** [comment]
When I told about repositories, I meant 0git repositories. Now I understand your frustration, yes, probably you thought ignoring `.git` in case you develop in ZeroNet site folder. Instead I meant the case when repository is the main thing.

**Comment by krixano** [comment]
Uh... no, I'm talking about the part where I never said to ignore `.git` files, but you said I said that.

**Comment by imachug** [comment]
> > And without hashing current? Some repositories (e.g.) are big - hash them all?
>Obviously leaving out the ignored ones. It's literally the same as what Sign does. and it's only done when you click publish.

**Comment by krixano** [comment]
Saying `the ignored ones` doesn't mean `.git` files.

**Comment by imachug** [comment]
Again:

> > I said:
> > And without hashing current? Some repositories (e.g.) are big - hash them all?
>
> The next comment was:
> Obviously leaving out the ignored ones. It's literally the same as what Sign does. and it's only done when you click publish.

So I thought those ignored ones were repositories.

**Comment by krixano** [comment]
How? The repositories aren't ignored.

**Comment by imachug** [comment]
> > I said:
> > And without hashing current? Some repositories (e.g.) are big - hash them all?
>
> I spoke about a big amount of big files - hashing them all would be slow. I thought you replied on how to make that faster:
> Obviously leaving out the ignored ones. It's literally the same as what Sign does. and it's only done when you click publish.

**Comment by imachug** [comment]
So if that would be as slow as signing, we don't need `publish only`. Also, you may notice that `sitePublish` API command signs automatically, and the button on sidebar sends a special argument to publish w/o signing.

**Comment by krixano** [comment]
Also, I see what you are saying about me misinterpreting what you meant by "repositories". Yes, I actually did originally think that you were talking about a zite repo.

**Comment by imachug** [comment]
@krixano So now we seem to understand each other :)

**Comment by krixano** [comment]
So if that would be as slow as signing, we don't need publish only. Also, you may notice that sitePublish API command signs automatically, and the button on sidebar sends a special argument to publish w/o signing.

Yes, I know that.

**Comment by krixano** [comment]
However, I never *actually* said that these repos were in the "ignored ones" that I'm talking about.

**Comment by imachug** [comment]
> So if that would be as slow as signing, we don't need publish only. Also, you may notice that sitePublish API command signs automatically, and the button on sidebar sends a special argument to publish w/o signing.

@HelloZeroNet We create problems to solve them.

**Comment by imachug** [comment]
> However, I never actually said that these repos were in the "ignored ones" that I'm talking about.

Once again, I thought that iterating and hashing all the files is slow, and I thought your idea about ignoring files from `ignored` sections would speed that up, and as the largest files are repo's files, I thought you spoke about ignoring those files.

**Comment by krixano** [comment]
Yes, you've already said this. I'm just saying I never actually said what you thought. I understand your thought. My response was mostly because you said `hash all of them` which to me meant all the files in a zite.

**Comment by imachug** [comment]
Oh, now I understand you, too. Sorry for my misunderstanding.

**Comment by krixano** [comment]
I'm essentially saying it's nobody's fault for the misunderstanding because we both did it.

**Comment by imachug** [comment]
So maybe this is OK?

```
+---------------------+------+---------+
| content.json        | Sign | Publish |
+---------------------+------+---------+
|            Sign & Publish            |
+--------------------------------------+
```

**Comment by krixano** [comment]
About the whole `rude` thing. I realize that people come from different cultures, which is why I try to explicitly say that something sounds rude, and I try to do it in the nicest way possible. My reasoning for this is because that person may not know what sounds rude in another culture, etc.

**Comment by krixano** [comment]
What about something like this:
> Other thing may be a drop-down menu called example "Sign / Publish", when you click it, you can choose all three options, while third one is "Sign & Publish".

It could be a button for sign and publish. Then on the right side, there could be a dropdown with the other two options "only sign" and "only publish".

**Comment by imachug** [comment]
Like this?

```
+---------------------+------------------+
| content.json        | Sign & Publish v |
+---------------------+------------------+
                      | Sign only        |
                      +------------------+
                      | Publish only     |
                      +------------------+
```

**Comment by krixano** [comment]
Yeah. Here's a better image that I found:

![image](https://user-images.githubusercontent.com/4098042/34454167-1886ba7c-ed2b-11e7-9ec7-c3b0abfd667e.png)

**Comment by imachug** [comment]
Was it from some post with CSS/JS?

**Comment by krixano** [comment]
No, it was from google images.

**Comment by imachug** [comment]
I'll try to implement this then.

**Comment by krixano** [comment]
The image uses these type of buttons from the Foundation framework.

**Comment by krixano** [comment]
@imachug I am going to delete everything that I've said that's not related to this topic.

**Comment by imachug** [comment]
Agree. */me deletes topics*

**Comment by imachug** [comment]
> This is the code it suggests:

Yeah, something like this.

**Comment by krixano** [comment]
I don't think that code is correct though, I think they messed up with the article. Because the text next to it says there should be something with a `split` class or something.

> The final layer of flexibility you have to play with is the option to add a split in your buttons. This can be used to indicate the availability of a dropdown, a download, whatever you want really. Add it onto your button using the ‘split’ class and a span element that should include the same ‘data-dropdown’ attribute we used earlier in our dropdown example.

**Comment by imachug** [comment]
Not classes, but at least HTML is correct.

**Comment by imachug** [comment]
> I am going to delete everything that I've said that's not related to this topic if that's fine.

I deleted some comments. Did I understand you correctly this time? :D

**Comment by krixano** [comment]
I don't know if you are trying to be funny or saying that as an insult.

**Comment by imachug** [comment]
I simply counted how many times we understood each other wrong so I am not sure if this is the case right now.

**Comment by krixano** [comment]
So you're being serious, which means, to me, it's kinda an insult.

**Comment by imachug** [comment]
Why do you think it's an insult? Also, let's move to thunderwawe.

**Comment by imachug** [comment]
WIP https://github.com/imachug/ZeroNet/tree/issue-1229
