### ISSUE TITLE
window Server error

### ISSUE THREAD

**Issue by kofzhanganguo** [HelloZeroNet/ZeroNet#1234]
Server error

Err: UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 219110: invalid continuation byte in UiServer.py line 95 > UiRequest.py line 130 > MutePlugin.py line 138 > UiRequest.py line 299 > UiRequest.py line 394 > UiRequest.py line 249 > utf_8.py line 16

Please report it if you think this an error.

**Comment by HelloZeroNet** [comment]
Thanks for reporting:
 - Does it worked for you earlier?
 - What operating system are you using?
 - Can you please upload the `(core)/src/Ui/template/wrapper.html` here

**Comment by kofzhanganguo** [comment]
Server error

Err: UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 219110: invalid continuation byte in UiServer.py line 95 > UiRequest.py line 130 > MutePlugin.py line 138 > UiRequest.py line 299 > UiRequest.py line 394 > UiRequest.py line 249 > utf_8.py line 16

Please report it if you think this an error.

Details:

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch, br", 
    "HTTP_ACCEPT_LANGUAGE": "zh-CN,zh;q=0.8", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 LBBROWSER", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "61080", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "2013-20160921PM", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.2 Python/2.7", 
    "arguments": {
        "action": "main", 
        "autodownload_bigfile_size_limit": 1, 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
        "config_file": "C:/Users/Administrator/Desktop/ZeroNet-win-dist/zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "C:/Users/Administrator/Desktop/ZeroNet-win-dist/data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "download_optional": "manual", 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": false, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "zh", 
        "log_dir": "C:/Users/Administrator/Desktop/ZeroNet-win-dist/log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": false, 
        "open_browser": "default_browser", 
        "optional_limit": "10%", 
        "pin_bigfile": 20, 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://zero.booth.moe#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_host": null, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "Bigfile", 
        "Cors", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.2.1", 
    "version_python": "2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.6.0 r3177", 
    "wsgi.url_scheme": "http"
}

System window7 X64

zeronet is the latest version

**Comment by kofzhanganguo** [comment]
[wrapper.zip](https://github.com/HelloZeroNet/ZeroNet/files/1597675/wrapper.zip)

**Comment by kofzhanganguo** [comment]
How to solve this problem

**Comment by HelloZeroNet** [comment]
Looks like your computer has some virus on it and it modified the html file (added part after </html>)
The wrapper.html should look like this: https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/master/src/Ui/template/wrapper.html (2.51KB)

You can try to overwrite the file with this one, but probably you need to get rid of that virus (or anything that modified the file) first.

**Comment by kofzhanganguo** [comment]
The problem is solved, the virus caused HTML file error

**Comment by MuxZeroNet** [comment]
Finally we can close these duplicates. #523, #814, #920, #1132, #1219

The cause is a computer virus. @kofzhanganguo where did you download ZeroNet from?
