### ISSUE TITLE
Error: Permission denied to access property "document"

### ISSUE THREAD

**Issue by Rtnd** [HelloZeroNet/ZeroNet#1236]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0 (rev3178)
  * Operating system: Windows 10
  * Web browser: Firefox / Chrome / Tor Browser
  * Tor status: not available/always
  * Opened port: no
  * Special configuration: -

### Step 2: Describe the problem:

I wanted to try and port a Javascript (VueJS) app to ZeroNet, but I got the following error:
**Error: Permission denied to access property "document"**
**There was attempt to access an object for which you have no permission. This is likely an <iframe> element loaded from a different domain for which you violated the same-origin policy.**

Is it possible to host in ZeroNet Javascript apps? 

#### Steps to reproduce:

  1. For example, a well know example in VueJS is: https://github.com/vuejs/vue-hackernews-2.0/
  2. The production files for that project are generated by running: npm run build.
  3. Create a new ZeroNet site.
  4. Copy the generated dist folder to the new site, and add the script in index.html.
  5. Sign content.json
  6. Try to open the website.

#### Observed Results:

I get the following message in Firefox console:
SecurityError: Permission denied to access property "document" on cross-origin object

In Tor Browser:
Error: Permission denied to access property "document"

Additional information: There was attempt to access an object for which you have no permission. This is likely an <iframe> element loaded from a different domain for which you violated the same-origin policy.

#### Expected Results:

Run the application without errors.

English is not my mother tongue; please excuse any errors on my part.

**Comment by imachug** [comment]
ZeroNet opens all your HTML files in `<iframe>`, so some things don't work because of SecurityError's. For example, `top.isRemotePresenter` throws an error. I'll try look what makes that error in Vue, but that may result in changing built code.

**Comment by imachug** [comment]
Sorry, which script do you add to `index.html`?

**Comment by imachug** [comment]
Can you show your `index.html`?

**Comment by krixano** [comment]
Afaik, Vue by itself shouldn't have any problems as I use vue for all of my zites without having to change the library in any way.

**Comment by imachug** [comment]
@krixano Not Vue, but maybe some plugin is generating incorrect code.

**Comment by krixano** [comment]
@imachug Yeah, it could definitely be a plugin.

**Comment by Rtnd** [comment]
The Firebase plugin was the problem. After disabling it I can see the website inside ZeroNet.

Thank you.
