### ISSUE TITLE
I make a WebGl game based on Unity3d. Then I put these files under my websites folder (clear all original files). When I open my web through ZeroNet, it just show nothing.    

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1237]
### Step 1: Please describe your environment

  * ZeroNet version:  0.60(3178)
  * Operating system: Windows64
  * Web browser: firefox
  * Tor status: not available
  * Opened port: no
  * Special configuration: no

#### Steps to reproduce:

 just replace the web files using webgl-based game files.

#### Observed Results:
It just shows nothing but a "0" symbol in left, when i open it through websites.
when i open the log of javascript, i see this "cause：CORS head miss 'Access-Control-Allow-Origin'"

#### Expected Results:
the web should be a web-game. When i open it by clicking the index.html, it can work.(the prefix of url is file://, not https://). However, when i open it through ZeroNet, it can not work. (the prefix of url is http://,)

**Comment by tangdou1** [comment]
http://127.0.0.1:43110/18nm9stKbCxPrzd7qi1hfp1hLHUQ68CFvu/
thanks for your reply

**Comment by imachug** [comment]
@tangdou1 Did you sign that? Also, if I could not download that site you could just send a ZIP here.

**Comment by tangdou1** [comment]
@imachug  Thanks for your attention. Here is the file 

[webgl-game.zip](https://github.com/HelloZeroNet/ZeroNet/files/1628902/webgl-game.zip)

**Comment by imachug** [comment]
Okay I can reproduce the problem.

**Comment by imachug** [comment]
Fixed: [1FevQJGEw5XadC1Hmkc6fL3WJcqyUmkXay.zip](https://github.com/HelloZeroNet/ZeroNet/files/1629117/1FevQJGEw5XadC1Hmkc6fL3WJcqyUmkXay.zip)

When you are transfering ClearNet site to ZeroNet, you can't just copy files. For example:
1. In ZeroNet you must use localStorage via ZeroFrame API only.
2. You can't simply use XHR or `fetch`.
3. You must add `<base>` and a script to `<head>`.
4. And many more. You can find some of them in [my tutorial](https://github.com/krixano/ZeroNet-Dev-Center/issues/28).

So I've added a monkey-patch to make XHR work and included ZeroFrame to your site.

**Comment by tangdou1** [comment]
@imachug Thank you very much. It indeed works now.

**Comment by imachug** [comment]
@tangdou1 @HelloZeroNet I assume this can be closed now?

**Comment by HelloZeroNet** [comment]
change `var gameInstance` to `window.gameInstance` should change it to global

**Comment by imachug** [comment]
@tangdou1 What @HelloZeroNet should work, but if you use Unity's own `SetFullscreen` method, it probably won't work in ZeroNet, you need to use ZeroFrame API. If you encounter this error, you should send me a new ZIP, so I could implement fullscreen.

**Comment by tangdou1** [comment]
@imachug @HelloZeroNet  Thanks, it can work now by `changing var gameInstance = to window.gameInstance =`

**Comment by DaniellMesquita** [comment]
Now zites can run without iFrame limitations.
Reference: #1262

**Comment by Stivencannor** [comment]
> Fixed: [1FevQJGEw5XadC1Hmkc6fL3WJcqyUmkXay.zip](https://github.com/HelloZeroNet/ZeroNet/files/1629117/1FevQJGEw5XadC1Hmkc6fL3WJcqyUmkXay.zip)
> 
> When you are transfering ClearNet site to ZeroNet, you can't just copy files. For example:
> 
> 1. In ZeroNet you must use localStorage via ZeroFrame API only.
> 2. You can't simply use XHR or `fetch`.
> 3. You must add `<base>` and a script to `<head>`.
> 4. And many more. You can find some of them in [my tutorial](https://github.com/krixano/ZeroNet-Dev-Center/issues/28).
> 
> So I've added a monkey-patch to make XHR work and included ZeroFrame to your site.

hello I made this Zite and I have some errors, I need your help to fix them. this is an example of a unity WebGl game.
1BkyaBHKaAkc9pNSFGQrTaubj6eH5ADHod
