### ISSUE TITLE
I can not publish a web page

### ISSUE THREAD

**Issue by tomas06** [HelloZeroNet/ZeroNet#1242]
Hello,

I have created a web page on my computer (in zeronet).
And on the other computer he joined the web site via a zeronet. (But for an hour I still get the same error)
https://image.ibb.co/dXsgsR/CRRR.png

**Comment by imachug** [comment]
Did you sign that page? How did you sign/publish it?

**Comment by tomas06** [comment]
When I do that, I get these 3 reports.

Content published to 0/5 peers.
Content publish failed.
No peers found, but your content is ready to access.

Does that have to wait 5 peers on my page to send her?

**Comment by tomas06** [comment]
Publish through the button or via the command is the same?

through "commands" it does not work.
https://pastebin.com/raw/1dwUrmiX (Successfuly published to 0 peers)

but on the other computer, I still see:

Connecting...
No peers found
content.json download failed
Peers found: 1
content.json download failed
Peers found: 1
content.json download failed

**Comment by imachug** [comment]
Did you `sign` it? Does it say `content.json signed successfully` or what?

**Comment by tomas06** [comment]
as a second computer I used a virtualbox...

I did a video to illustrate my problem.
https://streamable.com/q4x41

Thank you.

**Comment by imachug** [comment]
Next time when you publish a video, delete private key. But, anyways, you can't do anything right now because I've already copied it. Let this be a warning next time.

Do you have a port opened on any of those machines?

**Comment by imachug** [comment]
There are sometimes problems with that content publish failed. Usually just reloading page on one computer and publishing at the same time on another fixes this.

**Comment by tomas06** [comment]
This is a test page... there is no problem when somebody gets the keys...
But thank you for the alert....

"Your port 15441 is closed, but your Tor gateway is running well."
That is the problem?

PS:
as i sent there is also some error: https://pastebin.com/raw/1dwUrmiX
"Tor, due to Tor proxy port 127.0.0.1:9050 check error"

**Comment by imachug** [comment]
> "Your port 15441 is closed, but your Tor gateway is running well."
> That is the problem?

Wait, are you running Tor? There can be problems when publishing via Tor sometimes. With initial publishing, I mean. Sending publishes to peers having your site already usually works. So try to publish with tor disabled first.

**Comment by tomas06** [comment]
I do not use Tor connection.

**Comment by imachug** [comment]
And it isn't checked on ZeroHello, right?

**Comment by tomas06** [comment]
On the main page xxx I see: Port: Closed Tor: Available


I see this information on the page I want to share:
Missing files:
content.json

the file "content.json" exists in the folder "1111iB2JPb8usyJnzRVtwZQGag866F7n"

**Comment by imachug** [comment]
Weird. That `content.json` can be there, but only for clients, but you are site owner. Try to sign again and upload to a proxy then.

**Comment by tomas06** [comment]
Hmmm Hmmm.
Suddenly, it all works :-D

PS:
So the "content.json" file itself does not use its own site (only use-clients)?

**Comment by imachug** [comment]
> So the "content.json" file itself does not use its own site (only use-clients)?

Pressing `Sign` button creates that `content.json` . `content.json` holds all info about files. Pressing `publish` sends `content.json` to peers.

When peers receive a new `content.json` of a site they have, they look through `content.json`. It holds hashes of all files, so they can compare if some files were changed. If they were, they ask other peers for updated file.

So `content.json` is read-only for clients and read-write for owner.

**Comment by tomas06** [comment]
I don't understand how, but now everything works immediately..
Thank you help and your patience.

**Comment by imachug** [comment]
> I don't understand how, but now everything works immediately..

Well, I told you that *sometimes* publishing doesn't work, so maybe that's the case.

I assume we can close this now?

**Comment by elliekeli** [comment]
Yes close and Thx.

**Comment by imachug** [comment]
Could you close it then?

**Comment by wzzjhc** [comment]
老铁们，如果你们也跟这个老外一样的情况，出现搜索到一个种子，却json下载失败，那是因为还缺少最后一步，【./ZeroNet.sh sitePublish <adress>】。不谢。可以email我wzzjhc@qq.com。
如果你在国内发布不了，可能电信把全网络15441封锁了。我是在美国VPS上使用的。系统是ubuntu。
——————————————————————————————————————————————
step-1 ./ZeroNet.sh siteCreate  AND COPY 2 lines AND YES
step-2 ./ZeroNet.sh siteSign <adress> AND Private key (input hidden)
step-3 ./ZeroNet.sh sitePublish <adress>
tomas06 you lose step-3

**Comment by imachug** [comment]
@HelloZeroNet Can we close this issue please?
