### ISSUE TITLE
zeronet add content system.

### ISSUE THREAD

**Issue by elliekeli** [HelloZeroNet/ZeroNet#1244]
Hi all, 
Is there a (content management system) for zeronet?

I'm more an administrator, than a programmer (html, css, js).
I'm looking for some simple solutions how to add links to (alphabetical sorting and searching)

Thx.

**Comment by imachug** [comment]
Unfortunately, there isn't a CMS ready for ZeroNet yet. But you could take a look at ZeroBlog.

**Comment by elliekeli** [comment]
I was wondering if someone knows the normal (simple CMS) that can be used on zeronet,

**Comment by elliekeli** [comment]
Ecample:
http://127.0.0.1:43110/1AnimePihDhcbVdK1nvnbSEtH4oKU8RAYG/?Recent&page=2
http://127.0.0.1:43110/0play.bit

These pages use simple and same CMS. 
How do your owner a website, do its simple editing/maintenance?

**Comment by imachug** [comment]
Everyone creates their own CMS. But there isn't anything simple like WordPress.

**Comment by imachug** [comment]
@HelloZeroNet This issue looks like a duplicate, and it isn't directly related to ZeroNet core. Could you close it please?
