### ISSUE TITLE
Err: AttributeError: 'NoneType' object has no attribute 'content_manager' in ...

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1245]
### Step 1: Please describe your environment

    "version_gevent": "1.2.1", 
    "version_python": "2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.6.0 r3179", 
    Windows 10 64bit

### Step 2: Describe the problem:
Suddenly when i access zerohello, it says

> Server error
> Err: AttributeError: 'NoneType' object has no attribute 'content_manager' in UiServer.py line 95 > UiRequest.py line 130 > MutePlugin.py line 150 > UiRequest.py line 357

Other Zeronet sites seems to be loading OK. Quit and start Zeronet not helped to fix it.

**Comment by imachug** [comment]
Try with MutePlugin disabled. Rename `plugins/Mute` directory to `plugins/disabled-Mute`.

**Comment by slrslr** [comment]
@imachug when i quit zeronet, rename MutePlugin folder inside "core" folder of zeronet as you suggested, start zeronet, zerohello started loading. :-O

**Comment by imachug** [comment]
Looks like you are trying to visit some muted site, you get redirected to ZeroHello but that doesn't work somewhy. Is it possible that you muted ZeroHello? :D

**Comment by slrslr** [comment]
@imachug :D indeed, i found it in C:\ZeroNet\data\mutes.json
The reason why it ended up here is because i visited site http://127.0.0.1:43110/hellozeronet.bit/ thinking it may be some fake site so i banned it, but that .bit domain was hidding real zerohello: 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D

So i stopped zeronet, removed following from mutes.json:

>     "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D": {
>       "date_added": *********.***, 
>       "reason": "***"
>     }, 

renamed Mute plugin folder back and started zeronet. It works. I am sorry and thank you for help.
