### ISSUE TITLE
Feature request: localStorage backup and restore (all sites)

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1247]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.0 rev3171
  * Operating system: Ubunty 16.04
  * Web browser: Google Chrome 63.0
  * Tor status: error
  * Opened port: no
  * Special configuration: no

### Step 2: Describe the problem:

Can use JS to backup and restore localStorage data for current site using wrapperXetLocalStorage API calls. Can use OS backup but methods are different for each browser, not very user friendly and may change in new browser versions.

Could be nice to backup and restore localStorage data for all ZeroNet sites. 
wrapperXetLocalStorage cmd with ADMIN permission or button in 0 sidebar?

**Comment by krzysztof113** [comment]
Could you provide rationale for that? Is it useful for one/few sites only?

**Comment by jaros1** [comment]
Few sites I think. Closing this issue. Will use JS for backup & restore
