### ISSUE TITLE
"Connection with UiServer Websocket was lost. Reconnecting..." when i load multiple pages at same time

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1249]
Hello,

i have: zeronet 0.6.0, rev3179, Windows 10 64bit, Tor browser, not opened port, OpenVPN gui

a pop-up message "Connection with UiServer Websocket was lost. Reconnecting..."

appears in case i have several sites open, example 10 zites. Several of them are offline - never downloaded content.json (such sites can be found at: http://127.0.0.1:43110/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n) and i click one web browser tab hit F5 (to realod zite), after 1 second click other tab then F5, and like this lets say 5 times to reload lets say 6 zites), then i click tab with some opened zite like ZeroTalk and click some hyperlink and it show above mentioned error.

Are there any steps i can do to debug the cause of this?

**Comment by HelloZeroNet** [comment]
What error message you see in the javascript console? (F12)

**Comment by slrslr** [comment]
@HelloZeroNet 

I do not know if it is this, but in Tor browser / F12 key / "Console" tab, i seen these two lines only upon seeing mentioned error message on that web browser tab:

> [ZeroWebsocket] Closed close { target: WebSocket, isTrusted: true, wasClean: false, code: 1006, reason: "", currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false }  all.js:142:14
> [ZeroBlog] Websocket close  all.js:851:7

**Comment by ttlygw2018** [comment]
難道是遭到當局的惡意控制？？？

**Comment by slrslr** [comment]
I received the error mentioned in my previous message again (code 1006, all.js:142:14) just now. And no sites seem to be loading. It reconnect, but do not load site. I found a few unhandled exceptions like this one in log file: https://pastebin.com/fnT7ak7b

**Comment by ttlygw2018** [comment]
Thank you！！！


2018/1/28 上午1:57，"slrslr" <notifications@github.com>寫道：

**Comment by slrslr** [comment]
Some time passed and I can no longer reproduce this issue, sites loading perfectly. Though i was not thorough as i am just user, not developer.
