### ISSUE TITLE
Update to Rev3222, ZeroNet not working on Android.

### ISSUE THREAD

**Issue by funny110** [HelloZeroNet/ZeroNet#1250]
I use ZeroUpdate.bit update to the latest version,

**Comment by HelloZeroNet** [comment]
Has it worked before? What version are you on currently?

**Comment by funny110** [comment]
Android client 0.5.6.1，now open ZeroUpdate.bit, it is rev 3220, I back to zerohello click update, it can't open zeronet, I clear back ram is not work.

**Comment by stbinan** [comment]
Works for me with rev 3221 by using [Linux Deploy](https://github.com/meefik/linuxdeploy/) app, from the commits rev 3220 has some issue, but @shortcutme pushed it to ZeroUpdate and forgot to push rev 3221.

**Comment by funny110** [comment]
@HelloZeroNet @stbinan Android7.0 ,Zeronet APK 0.6.0.1,  reinstall zeronet, it  works, but when use ZeroUpdate.bit update to rev 3221,  zeronet can't be open,  the zeronet apk is downloaded on apkpure.com. Sorry, I don't know why, you can download and install to test.

**Comment by stbinan** [comment]
@funny110 @mkg20001 Then it's an issue for [ZeroNet-kivy](https://github.com/HelloZeroNet/ZeroNet-kivy)

**Comment by funny110** [comment]
update to rev3223, it works well.

**Comment by mkg20001** [comment]
Updated ZeroNet-kivy: https://github.com/HelloZeroNet/ZeroNet-kivy/releases/tag/v0.6.1.1
