### ISSUE TITLE
No console window on Windows

### ISSUE THREAD

**Issue by antilibrary** [HelloZeroNet/ZeroNet#1257]
### Step 1: Please describe your environment

  * ZeroNet version: rev3223
  * Operating system: Windows 10 Pro
  * Web browser: Chrome 63.0.3239.132 
  * Tor status: not available
  * Opened port: no
  * Special configuration: none

### Step 2: Describe the problem:

The Console window will not open when I run ZeroNet.exe nor there is a `Show Console` option in the icon tray menu

#### Steps to reproduce:

  1. Install the zeronet windows bundle and run
  2. Try to open the console window (to debug an error or something)

#### Observed Results:

  Icon tray screenshot: https://ibb.co/nip5Ww

#### Expected Results:

- A Show Console item in the menu

**Comment by antilibrary** [comment]
Awesome. I've created [this PR](https://github.com/HelloZeroNet/Documentation/pull/79) to avoid this questions again.
Thanks

**Comment by HelloZeroNet** [comment]
Thanks!
