### ISSUE TITLE
Proof of work based ID providers

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1258]
## Why?
The current, whitelist based listed ID provider solution leads to unnecessary centralization.

## How?
Proof-of-work based ID providers could let anyone create his/her own one and use it on any site that supports these kinds of ID providers.

## What?
The site could add required prefixes for ID providers instead of specific listing the supported ID providers.

Example for current, white-list based configuration:
```json
...
"user_contents": {
 "cert_signers": {
  "zeroid.bit": ["1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz"]
 }
}
...
```
This allows only one certificate provider on the site for the user contents.

Example for new, Proof-of-work based id specification
```
...
"user_contents": {
 "cert_pattern": "^1ZeroiD"
}
...
```
It would allow any certificate provider that's Bitcoin address starts with "1ZeroiD".
Currently, it takes around 6 hours on a ~200USD GPU or 30 USD on https://bitcoinvanitygen.com/
to generate an address with this prefix, which should be eligible to fight against spam.

Using the permission rules the site owners able to ban/set specific limits or rules based on ID provider address.

The users who don't have the possibility to generate his/her own ID provider could use
already existent ID providers that accept third-party registrations.

### Backward compatibility

An older client won't accept user files signed by these id providers.

### ID provider naming

We can't add readable name for the id providers, so they will appear as bitcoin address eg.: user@1ZeroiDJnkHkugPNd8UzSwceH8HfsnYtC

**Possible solution:** Display only the first few letter of the unique part, eg.: user@JnkH...

### Unlimited number of users

We can't limit the number of users issued by the ID provider the per-user size limit going to lose some effectiveness.

**Possible solution:** A per-ID provider limit.

**Comment by imachug** [comment]
Hm... The idea itself look interesting, but ~2-3 days... Not sure if that is acceptable for users who join the network.

**Comment by HelloZeroNet** [comment]
It's not acceptable for new users, but they would able to use already existing id providers. So if you do that 2-3 days of calculation you are also able to issue new certificates for users you trust.

**Comment by imachug** [comment]
Okay, looks reasonable.

**Comment by jaros1** [comment]
Will cert pattern "cert_pattern": "^1" be allowed in this implementation? (while list all cert providers).

**Comment by HelloZeroNet** [comment]
Sure, but if you don't want to have any control over the content submitted to your site, then I recommend self-signed certificate.

**Comment by grez911** [comment]
I like this solution because it doesn't require a blockchain.

**Comment by martinvahi** [comment]
Heaven forbid, AVOID THE PROOF-OF-WORK algorithm!!!!!!
Isn't the Bitcoin already contributing enough to the global warming?
Details are described at 
http://fouryears.eu/2017/07/09/the-blockchain-consensus-problem/
([archival copy](https://archive.is/gN70g))

**Comment by 6543** [comment]
1. Do you have a saver Proof-Of... wich is as secure as ...work?
2. BTC's Protokoll didnt need souch a heavy load - it only says the more miner they are they more they have to calc!
3. teoretikal If we replace all banks and stok markets wit BTC,ETC and 1-2 other blokchainsolutions we could save mouch more!
4. This is a dev discusion ethical discusions are needet but i think this is the wrong place :(

**Comment by martinvahi** [comment]
> Do you have a saver Proof-Of... wich is as secure as ...work?

I believe that if I, or You, @6543, modified the idea that I have described at 
https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=Experiment:+mmmv_symsig_t1
_([archival copy](https://archive.is/OcA2h))_
then that might work.

**Comment by HelloZeroNet** [comment]
Added as experimental feature to Rev3703: https://github.com/HelloZeroNet/ZeroNet/commit/6bc1ac1156551e35b072575340fe24a50854f6ba

Eg.: "cert_signers_pattern": "1Zero" to accept all signer startin with 1Zero (regexp supported)

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 

All ID providers must use 1Zero?

**Comment by HelloZeroNet** [comment]
its defined by the site

**Comment by DaniellMesquita** [comment]
> recommended (few days on average GPU) and probably will be enabled on ZeroTalk/ZeroMe hubs

You is against mobile phones

**Comment by filips123** [comment]
@HelloZeroNet I think that a few days are too much for the normal user. And something like https://github.com/HelloZeroNet/ZeroNet/issues/1258#issuecomment-380050512 should be implemented.

When it will be possible to import PowID providers from GUI?

Also, you said "Get my auth_address by entering to site's JS console". The auth_address will be diffreant for each site. Does this mean that I would need to do this and generate certificate for every site I want to use manually? Will this be automated?

**Comment by HelloZeroNet** [comment]
I think based on PoW it's not possible to create a solution that provides fairly good solution against spam attacks and makes it easy to users to create their own certificate, so:
this feature is not for the users, but for someone who want to be able to run a site that issue certificates for the users.
