### ISSUE TITLE
Just generated vanity address, how do I use it on a zite?

### ISSUE THREAD

**Issue by DataCourier** [HelloZeroNet/ZeroNet#1259]
Hi, I just used vanity to create a public and private key pair.

1) Generated the key pair
2) Created directory with vanity address
3) Cloned ZeroTalk fork in
4) Changed the `address` field in `content.json`
5) ... ?

Now there are bunch of things in `content.json` and I am wondering what to do next. 
Can you help me out please?

**Comment by HelloZeroNet** [comment]
Actually you don't have to change anything in content.json, here is the steps:
 - Generate address using vanitygen
 - Create data/1yourvanityadress directory and copy the site file's there
 - Open http://127.0.0.1:43110/1vanityaddress in your browser
 - Open sidebar and sign all the content.json at the bottom of it.
