### ISSUE TITLE
Can the ZeroNet creat a mechanism to encourage more and more pepole to spread the website content (share their disk) like bitcoin that encourage people to share their cpu?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1260]
idea

**Comment by HelloZeroNet** [comment]
The main problem proof-of-storage and proof-of-bw is really hard (impossible?) opposed to proof-of-cpuwork.

**Comment by MuxZeroNet** [comment]
> proof-of-storage and proof-of-bw is really hard (impossible?)

FYI, Proof of Space is possible. PoS uses hard-to-pebble graphs to ensure the prover must dedicate a certain amount of storage. It is hard to implement though. See the SpaceMint [paper](https://eprint.iacr.org/2015/528.pdf) and [source code](https://github.com/kwonalbert/spacemint).

**Comment by HelloZeroNet** [comment]
> FYI, Proof of Space is possible. PoS uses hard-to-pebble graphs to ensure the prover must dedicate a certain amount of storage.

Thanks for pointing out, but it sounds like it's not for any meaningful data and even it would be so the proof-of-bw solution is still required to make it comparable to pow.

**Comment by tangdou1** [comment]
Yes, it is hard to implement. But I think thak making a honor wall for those people who contribute to the ZeroNet is easy to implement. For example, when one's upload  exceed 1GB, he or she would recieve a virtual medel. Just like the Steam, in which people would recive a virtual medal for his or her palying time. It just be a suggestion.

**Comment by HelloZeroNet** [comment]
And who would decide if someone uploaded 1GB or not?

**Comment by imachug** [comment]
@HelloZeroNet Run fileRules locally?

**Comment by mkg20001** [comment]
@HelloZeroNet You should maybe take a look at https://filecoin.io and https://filecoin.io/proof-of-replication.pdf

**Comment by HelloZeroNet** [comment]
@mkg20001 It's very abstract, missing lots of details, but we will see once it's launched.

**Comment by tangdou1** [comment]
Thanks for your comments. Hope to see this can be implemented.
