### ISSUE TITLE
In development: Local peer discovery

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1264]
## Why?

It will allow to discover peers on local network without internet connection. Currently it's only possible by setting up a tracker by enabling the Bootstrapper plugin and pointing every client to that ip.

### How?

[Zeroconf](https://en.wikipedia.org/wiki/Zero-configuration_networking) allow clients to discover each other without server intervention.

### What?
Started working on local peer discovery using https://github.com/jstasiak/python-zeroconf as it seemed like the most active one and also works with gevent.

### Binary dependency
It depends on netifaces module that is not pure-python which I try to avoid due multi-platform issues. Solved it by creating a "fake" netifaces module that returns using the current Upnp.py module's `_get_local_ips` function.
Other dependencies: six, enum (both light, pure-python modules, so should not be a problem)

### How to broadcast the list of sites you have?
 - Creating service to each site
 - Adding it to service's description
 - Don't distribute it to zeroconf network, but allow the other client to receive a list of site address sha hashes you have. (this plugin will be turned off by default in tor: always mode)
 - Don't do anything, let other clients try and fail for unknown sites

### Avoid leaking local peer ips to peer exchange
 - Mark sites that received via zeroconf
 - Skip local ip ranges on pex

## Current status

 - I was able to create a registration request and other computer on the same network was able to discover it
 - Ran into some gevent error (<1.1 version), I was able to fix it, but one more ugly patches
 - Added private ip detection and filter to pex
 - Found a way to make it work on gevent without ugly patch
 - Moved to simple UDP broadcasting with custom protocol due [zeroconf problems](#issuecomment-361974868)

### Plan
 - [x] Create Plugin directory for it
 - [x] Basic broadcast listener server
 - [x] Testing basic broadcast server functions
 - [x] Extended broadcast server with peer discovery functions
 - [x] Implement discoverRequest, discoverResponse, siteListRequest, siteListResponse commands
 - [x] Test discoverRequest, discoverResponse, siteListRequest, siteListResponse commands
 - [x] Implement and test siteListRequest caching based on sites_change
 - [x] Test local peer exchange on UDP socket
 - [x] Connect peer discovery with announce events
 - [x] Prefer recently discovered tracker/LAN clients
 - [x] Set up multiple clients on LAN without internet connection for real-life testing
 - [ ] Release

**Comment by imachug** [comment]
> Don't do anything, let other clients try and fail for unknown sites

A bad idea (at least without any changes) - currently ZeroNet downvotes peers that request unknown sites.

**Comment by HelloZeroNet** [comment]
I'm using simple broadcast udp messages as zeroconf lib has the following problems:
 - No ipv6 support
 - Can't announce different ip for multiple network interfaces
 - Relatively high cpu usage (~15 cpu seconds/hour on chip computer in my quiet LAN)

I'm not sure if zeroconf/mdns/bonjour has other benefits

**Comment by HelloZeroNet** [comment]
Hm something weird happening:

I'm experimenting with multicast udp, it works fine if two machine connected (desktop, chip), but when a third computer (laptop) signs up the multicast messages stops reaching all machine in the group.

Currently:
- Multicasting from desktop: reaches desktop, laptop
- Multicasting from laptop: reaches laptop, desktop
- Multicasting from chip: reaches desktop laptop, chip

**Comment by HelloZeroNet** [comment]
Unfortunately I found an error that has to be fixed before release:
Creating an UDP socket server and binding it to '' has problems is multiple network address present on the computer. 
The solution is creating separate server for each interface...working on it.

**Comment by HelloZeroNet** [comment]
The local peer discover plugin added in Version 0.6.2: https://github.com/HelloZeroNet/ZeroNet/commit/6376f7dd566ad7f10bfd3e583023b70d0d1de887

**Comment by funny110** [comment]
@HelloZeroNet  Please update ZeroUpdate, THX :)

**Comment by slrslr** [comment]
Hello, [there is a question](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1519463831_13E6xCFLmbGYCNAPrKd3m5o6gTgnzMW4rd/How+to+apply+local+peer+discovery+feature+to+my+zeronet) asking for a explanation on how to achieve/verify that the local peer discovery works?
