### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor: u'*/ZeroNet/data/15vXv74dDjPLUtCnA6m7vwcucRNtJfcEgp/img/con.png'

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1268]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.1 rev3229
  * Operating system: Win. 10 64bit
  * Web browser: TorBrowser
  * Tor status: available
  * Opened port: not opened anything

### Step 2: Describe the problem:

In TorBrowser i am opening several zites at once and it is loading not timeout for 45 minutes already, zites not loaded and are ins tate "Loading..." and in log file i see: https://pastebin.com/NdKV1pxd

It seems to be some error related to one particular zite:
IOError: [Errno 9] Bad file descriptor: u'*/ZeroNet/data/**15vXv74dDjPLUtCnA6m7vwcucRNtJfcEgp/img/con.png**'

and it looks like it prevents other zites loading. I found that this error for same element (con.jpg) appeared also yesterday in the log. Is there any simple way for Zeronet developer to fix this so the zites are loaded instead in infinite loading?

Quitting and starting zeronet not helped to make zeronet zites loading in TorBrowser, Firefox works OK.

**Comment by slrslr** [comment]
I can no longer reproduce this issue, though i was not thorough as i am just user, not developer.

**Comment by skwerlman** [comment]
This error was caused by a windows limitation; `CON` is a reserved filename from the DOS days, and NTFS is dumb and doesn't count file extensions as part of the name, so `con.png` is forbidden.

See https://stackoverflow.com/a/122431/2817634, and specifically the comments on that answer
