### ISSUE TITLE
How about creating a Node.js verison for ZeroNet?

### ISSUE THREAD

**Issue by moshest** [HelloZeroNet/ZeroNet#127]

**Comment by HelloZeroNet** [comment]
While the JavaScript has some advantage (eg. more people know it), I think Python is more advanced language, so we don't have plans to switch to node.js. Although the alternative implementations are welcomed.

**Comment by joshgit** [comment]
But surely we also need an OCaml or Haskell version.

**Comment by almet** [comment]
Should we close this issue?

**Comment by TestItOnlyOnce** [comment]
Just for information, if someone ever visit this issue, there is an implementation already: https://github.com/ZeroNetJS/zeronet-js
