### ISSUE TITLE
Err：IOError：[Errno 2]没有这样的文件或目录：u'Server / U / > SiteManagerPlugin.py第46行> SiteStorage.py第301行> SiteStorage.py第195行

### ISSUE THREAD

**Issue by ttlygw2018** [HelloZeroNet/ZeroNet#1274]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by ttlygw2018** [comment]
Err：IOError：[Errno 2]没有这样的文件或目录：u'Server / U / > SiteManagerPlugin.py第46行> SiteStorage.py第301行> SiteStorage.py第195行。      我根本不曉得哪裡的問題。軟件是谷歌商店下載的，一開啟就是這樣

**Comment by 0polar** [comment]
信息过少，不可重现。

我觉得这是一个社会常识，花一分钟写的问题，不能期待一个毫无交情的陌生人花一个小时耐心地问你版本和操作步骤，模拟出你的环境来帮你分析解决。

**Comment by ttlygw2018** [comment]
我估計是我的筆記本電腦被當局攻擊了，我打算去刷下系統！如果這樣還不能解決問題，我就換一台功能強大點的機器！總之
我覺得堅持下去，零網肯定會日益強大起來，推廣到更多的用戶！！我只是個菜鳥！還有很多不足之處，麻煩啦！！

2018/2/5 下午5:45，"0polar" <notifications@github.com>寫道：

**Comment by trotsky1997** [comment]
You should use English to push an issue.
And you are ought to feedback this issue in HelloZeroNet/ZeroNet-Kivy.
谢谢（抠鼻，我是共产党我会攻击你这种人的电脑？
