### ISSUE TITLE
Linux 32-bit - ImportError: No module named fallback

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1277]
### Step 1: Please describe your environment

  * ZeroNet version: master / latest 32-bit
  * Operating system: linux 32-bit / ubuntu 12.04 / armv7l
  * Web browser: n/a
  * Tor status: n/a
  * Opened port: n/a
  * Special configuration: ____

### Step 2: Describe the problem:

Tried to install ZeroNet on an old cubox pro. ubuntu 12.04. 
Tried
- a) https://github.com/HelloZeroNet/ZeroNet Manual install for Debian Linux (+ copied ZeroNet from a other comp).
- b) download and unzip Manual install for Debian Linux

UI-server stops in both versions with ImportError: No module named fallback

Se log
[terminal.log](https://github.com/HelloZeroNet/ZeroNet/files/1704078/terminal.log)

**Comment by HelloZeroNet** [comment]
caused by a very old version on python / gevent (released 7 years ago)
you have to update these libs to run zeronet
