### ISSUE TITLE
Mozilla Dev Network 3GB unable to sync

### ISSUE THREAD

**Issue by sunk818** [HelloZeroNet/ZeroNet#128]
http://127.0.0.1:43110/1MoZDevNsM5NAitt2y17jCvPWRazbjYqLe

ZeroNet seems to choke every time it tries to connect to this URL.

Am I not being patient enough?

[19:58:46] Site:1MoZDe..YqLe Content.json not exist: data/1MoZDevNsM5NAitt2y17jCvPWRazbjYqLe/content.json

**Comment by HelloZeroNet** [comment]
its very extreme, contains 100k+ files, i dont think its going to work anytime soon

**Comment by sunk818** [comment]
I see. It seems to crash the client or makes it unusable. What about a way to disallow sites of a certain size, or a better way to handle it getting stuck? Long term, I wouldn't mind hosting/peering a 3GB site  if ZeroNet could could provide a way to handle it.

**Comment by zQueal** [comment]
I really think that's the wrong way to handle something like this. If it were me, and keep in mind this is just my opinion, depending on the content hosted; there's really no need for the site to be that big. If anything, I would host the main site via ZeroNet A, and have another service which hosts ZeroNet B which contains the files that you're attempting to serve. That ZeroNet B could be located on a dedicated server, maybe, so you only require one dedicated seeder--then clients could request the content they desired via ZeroNet. But attempting to throw all the files at the client at once even when they may never use them is pretty weird IMHO.

Just my $0.02.

**Comment by sunk818** [comment]
The thought is of making multiple ZeroNet addresses and breaking up the site into logical groups is definitely a better work around. Things like static blog publishing, or even torrent indexers could be published this way. You have the main address everyone comes to and say every month, the older content gets owned by a different address. My only concern there is how one goes about searching for content across different "domains".

**Comment by HelloZeroNet** [comment]
A feature is planned that allows to make sites that has access to other site's files, so it can generate a merged database from them.

This will allows to make huge sites without creating monoliths, keep the user's content decentralized in her/his hands and also solves scalability problems.

For example a twitter-like page could be done like this:
 - We going to have 2 pages: ZeroTwitterAccount and ZeroTwitterMerger
 - If someone who wants "create" a new account he/she clones the ZeroTwitterAccount page which will holds all his posts and replies as a standalone site.
 - If you want to follow anyone you just start serving his/her site
 - When you visit ZeroTwitterMerger site requests read access to all ZeroTwitterAccount type sites you hosting and create a merged sql database from them. This will allow you to browse and search all your hosted (followed) ZeroTwitterAccount in one place.

**Comment by sunk818** [comment]
Hi, just revisiting this idea again.. I'm curious about your thoughts on open source publications such as scientific journals. Would we follow a particular subscription and those subscriptions merged into our Merger account?

**Comment by border0464111** [comment]
the merger site feature is now into production. Closing ?

**Comment by grez911** [comment]
@HelloZeroNet Please, close the issue.
