### ISSUE TITLE
major issues w zeronet

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#1280]
tor is up after config.
running UBUNTU- i want to say 17...
Im getting a barrage of issues. just updated to latest(as I always do).

trackers:
rar.bg (rarbag) =down
explodie=down
opentrackr=timeout

ports ranging from 0 to random numbers (other than set by zero) showing up as a node and then failing to sync data. THESE ARE BAD PEERS. This is not the default config.

multiple NONE errors when sync..(I think these are .onion nodes.)

This can lead to your zites failing to have hosts, or failure to re add them after namecoin(NMC) issues. It isnt just you not being online long enough to sync.

Im also getting certificate issues across the board.
Looks like someone wants https but it isnt working(and cant work)- some of you need to use zero ID in its place.

While Im happy to host, Id appreciate others sharing content too.
I will be spinning fedora non-free eventually.

I cant read your kanji or russian so pardon me if I dont mirror those zites.

**Comment by JazzMaster** [comment]
for the record:
100mbps dwn cable modem-spectrum/charter/twc conglomerate

**Comment by JazzMaster** [comment]
trackers: we should use the list like coins do. 

hop on irc and go fetch every six hours or so or if nodes drop off. If we have at least a few nodes...we can ping the list from the active ones. 

we shouldnt be using p2p trackers for this. suprisingly..I dont see why this couldnt also be applied to p2p nodes to torrenting.. someone forgot about the blockchain tech you were supposed to be using...thats why you are given BTC addreses(I think bch or LTC would be better at this time and era, however) for your zites. I can see why torrents work this way but we should be completely DHT by the 0net nodes hosting the content, no?

DHT is new. trackers are old school. Trackers can go down while DHT cannot.

**Comment by HelloZeroNet** [comment]
Opentrackr is not down, but probably has some rate limiting implemented.
I will monitor rarbg and explodie and if they remain down I will find a new one in their place. The client using 8 trackers, so if some of them goes does it should not have any visible effect.

**Comment by HelloZeroNet** [comment]
Added more reliable trackers and removed warning from cli output: https://github.com/HelloZeroNet/ZeroNet/commit/f5137376280698192a84cbef4e28bd449d8171af
