### ISSUE TITLE
How to ZeroNet on LAN

### ISSUE THREAD

**Issue by Serkan-devel** [HelloZeroNet/ZeroNet#1283]
Is it possible to access ZeroNet on the same network, other than localhost?

**Comment by HelloZeroNet** [comment]
you have to start it using `--ui_ip *`

**Comment by Serkan-devel** [comment]
`python2 zeronet.py --ui_ip *` doesn't seem to work (I'm running it on a raspberry pi)

**Comment by HelloZeroNet** [comment]
try `python2 zeronet.py --ui_ip "*"` (`*` acts as magic character in some shells)

**Comment by Serkan-devel** [comment]
It works now, thanks!

**Comment by kskarthik** [comment]
So, this means zeronet is comparable with mesh networks !?

**Comment by DaniellMesquita** [comment]
@kskarthik
Not, because it is to be used only by the owner of ZeroNet installation, it implies in security risks.
You can't share your ZeroNet data with other users in same network, except if you use MultiUser plugin.

**Comment by Serkan-devel** [comment]
@DaniellMesquita there's a multiuser plugin?

**Comment by DaniellMesquita** [comment]
Yes.
This plugin is used in proxyes (clearnet sites that hosts ZeroNet for everyone access), where the changes made by users don't affect the whole installation, they can login with a privatekey.
