### ISSUE TITLE
'ConnectionServer' object has no attribute 'local_announcer' & AttributeError: 'Config' object has no attribute 'log_dir'

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1287]
* ZeroNet version: 0.6.2 r3310, Python 2.7.5, [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)], Gevent: 1.0
  * Operating system: CentOS 7 64b

Hello, are the following errors caused by non existing content.json?

$ python zeronet.py siteDownload **mysitepublichash**
- Starting ZeroNet...
- OpenSSL loaded, version: 01000207F
- Version: 0.6.2 r3310, Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)], Gevent: 1.0
SiteManager Deleting orphan site from content.db: somesiteaddress
- Opening a simple connection server
TorManager Connecting to Tor Controller 127.0.0.1:9051
TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 170 > socket.py line 342
TorManager Starting self-bundled Tor, due to Tor proxy port 127.0.0.1:9050 check error: No connection
Site:mysitepublichash **Content.json not exist: data/mysitepublichash/content.json**
Announcing...
- **Unhandled exception**: 'ConnectionServer' object has no attribute 'local_announcer'
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "/home/ZeroBundle/ZeroNet/src/main.py", line 502, in start
    actions.call(config.action, action_kwargs)
  File "/home/ZeroBundle/ZeroNet/src/main.py", line 155, in call
    func(**kwargs)
  File "/home/ZeroBundle/ZeroNet/src/main.py", line 329, in siteDownload
    site.announce()
  File "plugins/AnnounceLocal/AnnounceLocalPlugin.py", line 13, in announce
    local_announcer = self.connection_server.local_announcer
**AttributeError:** 'ConnectionServer' object has no attribute 'local_announcer'
- Unhandled exception
None
Traceback (most recent call last):
  File "zeronet.py", line 91, in <module>
    main()
  File "zeronet.py", line 64, in main
    traceback.print_exc(file=open(config.log_dir + "/error.log", "a"))
**AttributeError**: 'Config' object has no attribute 'log_dir'

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/cd822156c9fda420afeb63eda4d9637441f7393f
