### ISSUE TITLE
15441端口死活打不开

### ISSUE THREAD

**Issue by guahunyo** [HelloZeroNet/ZeroNet#1291]
### Step 1: Please describe your environment

  * ZeroNet version: _____最新
  * Operating system: _____win10
  * Web browser: _____谷歌浏览器
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____腾达fh456路由器没发开端口
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by MuxZeroNet** [comment]
> [Tenda fh456 router did not open the port](https://translate.google.com/#auto/en/15441%E7%AB%AF%E5%8F%A3%E6%AD%BB%E6%B4%BB%E6%89%93%E4%B8%8D%E5%BC%80%0A%E6%9C%80%E6%96%B0%0A%E8%B0%B7%E6%AD%8C%E6%B5%8F%E8%A7%88%E5%99%A8%0A%E8%85%BE%E8%BE%BEfh456%E8%B7%AF%E7%94%B1%E5%99%A8%E6%B2%A1%E5%8F%91%E5%BC%80%E7%AB%AF%E5%8F%A3)

[Contact Tenda instead.](http://www.tendacn.com/en/aboutus/contact.html)

**Comment by tangdou1** [comment]
路由器打不开，找路由器开发商。

**Comment by tangdou1** [comment]
这个原因应该是和ISP 有关的， 就是和你互联网服务商（电信、移动、联通、长城宽带等）有关，国内的ISP 大都只是给你局域网地址，让你能上网。就好比 ISP 有一个路由器， 它发了一个局域网地址给你的路由器，你的路由器再发一个局域网地址给你的电脑，你虽然开启了你的路由的UPNP,但是你无法保证ISP的路由器的UPNP也可开启了，所以你就打开不了15441端口。
国外的ISP一般都是给公网地址给你的路由器的，所以在国外，只要打开你的路由器的UPNP就可以成功打开15441端口。
（以上纯粹是一个来自非计算机专业人员的臆测，不保证正确）

**Comment by tangdou1** [comment]
See here
https://github.com/HelloZeroNet/ZeroNet/issues/935

**Comment by tangdou1** [comment]
plz close it
