### ISSUE TITLE
Problems with New Zite and Database

### ISSUE THREAD

**Issue by krixano** [HelloZeroNet/ZeroNet#1294]
### Step 1: Please describe your environment

  * ZeroNet version: 1.6.2 Rev 3329 and Rev 3335
  * Operating system: Linux (Solus OS)
  * Web browser: Firefox and Chrome (Google)
  * Tor status: Error (Connection Refused - not available?)
  * Opened port: yes
  * Special configuration:

### Step 2: Describe the problem:
I have created a new zite. Ever since updating to latest version of ZeroNet and creating this new zite, I am not able to get the database to work - it says no database found even though I have the dbschema file. However: Zites that were on my computer prior to updating ZeroNet still work (still show the database file in the database field).

When clicking the Reload button, this error message appears:
![image](https://user-images.githubusercontent.com/4098042/36464400-3901d00a-1695-11e8-817d-4defd5fa2865.png)

Also, for this new zite, sometimes when opening the sidebar, it is completely blank and the problem persists among refreshes. I am only able to get it to appear after I have restarted ZeroNet. However, with other zites, none of this happens.

[Link to Zite](http://127.0.0.1:43110/1f67d9PNHtTkrHYCt44PYvv1sHUMHvtxL)

Something to Note: I'm not 100% sure that this is due to an update, or even the latest update. I have only noticed this problem just after I have updated. It's possible that the problem could be due to something else completely different.

#### Steps to reproduce:

  1. Update ZeroNet to Latest version
  2. Create New Zite
  3. Add dbschema file

#### Observed Results:
Described above

#### Expected Results:

  * What did you expect to happen?
Sidebar shows up, database recognized.

**Comment by HelloZeroNet** [comment]
You have a invalid line in your dbschema.json:

```
        "zites": {
            "cols": [
                ["id", "INTEGER"],
                ["slug", "TEXT"],
                ["title", "TEXT"],
                ["description", "TEXT"],
                ["tags", "TEXT"],
                ["category_slug", "TEXT"],
                ["merger_supported", "INTEGER"],
>               ["merger_slug"],
                ["date_updated", "INTEGER"],
                ["date_added", "INTEGER"],
```

(missing the type definition)

**Comment by krixano** [comment]
Thanks. See:
> I'm not 100% sure that this is due to an update, or even the latest update. I have only noticed this problem just after I have updated. It's possible that the problem could be due to something else completely different.

Turns out I was right about that.
However, I think there should be a better error message. Also, not sure if the disappearing sidebar is related, but it seems like that shouldn't happen even with an error like that.

**Comment by HelloZeroNet** [comment]
Yeah it would be a nice to have a json schema validator with meaningful error messages. I will check the possibilities on that.
