### ISSUE TITLE
There is a 'Uncaught TypeError: Cannot read property 'setSizeLimit' of undefined' when click 'Open site and set size limit to XXMB' button. 

### ISSUE THREAD

**Issue by smcdl** [HelloZeroNet/ZeroNet#1296]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2(rev3335)
  * Operating system: Ubuntu 16.04
  * Web browser: Chrome 64.0.3282.167
  * Tor status: not available
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:

Some site can not open because the size limit too small. There was no responding when I clicked the button 'Open site and set size limit to XXMB'.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev3337 https://github.com/HelloZeroNet/ZeroNet/commit/bda31aea59fa5b694457d7abdb88ab3f9dfeb3bb
