### ISSUE TITLE
Where is locates private key for cloned site ?

### ISSUE THREAD

**Issue by RedbHawk** [HelloZeroNet/ZeroNet#1298]
I cloned blog with _clone_ button. Added some own content & when I push _**Sign & Publish new content**_ it asks my private key.
Where I can find this private key ?

**Comment by rllola** [comment]
Did you check in user.json ? But if the private key was there it should have sign for you automatically...

**Comment by imachug** [comment]
Where did you find `Sign & Publish new content`?

**Comment by krixano** [comment]
@imachug I believe ZeroBlog has a button in the bottom right corner that pops up when the owner of the zite creates a new post so that they can easily click it to sign their zite.

**Comment by RedbHawk** [comment]
In **users.json**  file that locates in _ZeroBundle/ZeroNet/data_ first find your blog address & under that address you'll find **privatekey** (**not** **_auth_privatekey_**)
