### ISSUE TITLE
Why when multiuser plugin enabled I cant delete sites?

### ISSUE THREAD

**Issue by AccountCreatr** [HelloZeroNet/ZeroNet#1299]
After enabling multiuser plugin, when I try delete site , I see:
This function is disabled on this proxy!

**Why** when multiuser plugin enabled I cant delete sites?

**Comment by HelloZeroNet** [comment]
Multiuser plugin is created for public proxies where the site deletion would be unfortunate. You can disable the restrictions by logging in to a master user (search for master_seed in data/users.json)

**Comment by BenMcLean** [comment]
I changed the master_seed in users.json to match my existing private key and this message that deleting sites is a function disabled on this proxy still appears.

**Comment by krixano** [comment]
You need to **signin** with the master seed, not change it.

**Comment by BenMcLean** [comment]
Why can't you change it???

Seems like a serious bug if you can't.

**Comment by krixano** [comment]
All of the private and public keys for each zite is generated using the master seed *I think*.

> Seems like a serious bug if you can't.

I don't see why. You can't just change your private key and have it work, right? Why would this be any different.

**Comment by BenMcLean** [comment]
Yes, you can change your private key. Just choose a new one and you get a new identity.
