### ISSUE TITLE
nginx config

### ISSUE THREAD

**Issue by 496080199** [HelloZeroNet/ZeroNet#1307]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: alpine-docker
  * Web browser: firefox
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: _add nginx_

### Step 2: Describe the problem:
when I use nginx to proxy ,the websocket connection always broken down,how to make the connection be stable?

my nginx configure like this:
server {
        listen 80;
        server_name _;
        rewrite ^(.*)$  https://$host$1 permanent;

}
server {
        listen 443 ssl;
        server_name _;
        ssl                  on;
        ssl_certificate      /etc/nginx/server.crt;
        ssl_certificate_key  /etc/nginx/server.key;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass  http://127.0.0.1:43110;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}

#### Steps to reproduce:

my website:https://172.96.226.171
,you can try it.
  

#### Observed Results:

 websocket connection lost

#### Expected Results:

  connection be stable

**Comment by stbinan** [comment]
Probably you need
```
location /Websocket {
        ...
        proxy_read_timeout 1h; #for long live websocket connetion
        ...
    }
```
Full version by lxpz

```
server {
    server_name zeronet.mydomain.tld;

    auth_basic "Protected area: ZeroNet";
    auth_basic_user_file /var/www/.htpasswd;
    
    location ~ \.(woff2|woff|ttf)$ {
        auth_basic off;

        proxy_pass http://127.0.0.1:43110;
        proxy_http_version  1.1;
        proxy_set_header Host $http_host;
        proxy_set_header    X-Real-IP   $remote_addr;
        if_modified_since   before;
    }

    location / {

        proxy_pass        http://127.0.0.1:43110;
        proxy_http_version  1.1;
        proxy_set_header    Host        $host;
        proxy_set_header    X-Real-IP   $remote_addr;
        if_modified_since   before;

        proxy_read_timeout  120s;
        proxy_send_timeout  120s;

        add_header 'Access-Control-Allow-Methods' 'GET,OPTIONS,PUT,DELETE' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Origin' '$http_origin' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,User-Agent,Keep-Alive,Content-Type,accept,origin,X-Requested-With' always;

        if ($request_method = OPTIONS ) {
            return 200;
        }
    }


    location /Websocket {
        proxy_pass http://127.0.0.1:43110;
        proxy_http_version 1.1;
        proxy_read_timeout 1h; #for long live websocket connetion
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
You also need to start ZeroNet with `$ python zeronet.py --ui_host my.domain.tld 127.0.0.1:43310 --ui_restrict 127.0.0.1`.

**Comment by 496080199** [comment]
got it,Thanks
