### ISSUE TITLE
Multiuser plugin not work with my old username/id?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1308]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Win. 10
  * Web browser: Firefox
  * Tor status: available
  * Opened port: yes

### Step 2: Describe the problem:

Hello, when i enabled Multiuser plugin and restarted ZeroNet i found that on ZeroHello left sites menu are missing my favorite sites and i had no longer access to my old username on ZeroTalk.
This was surprise to me as i though i will have access. Why is this so, can i use Multiuser plugin with old username? How?

When i disabled plugin and quit/start Zeronet, my old identity was back.

**Comment by imachug** [comment]
Find `master_seed` in `users.json`. That is your login. Then press `Sign out` on ZeroHello and then relogin with `master_seed`.

**Comment by HelloZeroNet** [comment]
By default the multiuser plugin using in-memory settings. (best suitable for proxies)
If you want to use your users.json start it using `--multiuser_local`

**Comment by slrslr** [comment]
Thank you for the reply. I tried what suggested imachug and it succeeded, BUT for both "login sessions" in ZeroHello sites menu are missing my favorite sites (yet, connected and owned sites are there) and on ZeroTalk offers me new username registration instead of using my old ID. Do you have any idea what is wrong?

I googled on what is "--multiuser_local" i tried to edit the zeronet .exe app shortcut to have this switch, after launch i was able to see favorite sites of my old user id. Not sure if it works because i restarted zeronet or because i did it with mentioned switch.

Though i think it may be good if user switching would be easier for total noobs. But downside may be that it would be easier for spammers to switch identities.

**Comment by slrslr** [comment]
I dare to submit this comment as it seems a bit related. I installed zeronet on other linux computer and logged in using my master_seed, it worked, but at zerotalk it invite me to register new account, do not offer me my login. Any suggestion on how to port my username/IDentity (@zeroid) from one computer to another the easiest way? Possible without copying files?

**Comment by HelloZeroNet** [comment]
If you visit the zeroid site, then it should recover your certificate even if you don't copy your users.json just login to your master_seed.

**Comment by slrslr** [comment]
@HelloZeroNet indeed i have not clicked Register button in ZeroTalk authorization menu because i not wanted to register new account but only login. But when i clicked that it worked, though i had to wait around 9 minutes on slow internet to download zeroid data :-/ Then appeared:
Hello, welcome to ZeroProxy!
A new, unique account created for you: ...
After ZeroTalk refresh, i can see my old nickname in authorization menu which is what i wanted. Thank you.

**Comment by imachug** [comment]
@HelloZeroNet Never knew about this, thanks!

**Comment by slrslr** [comment]
I wanted to mention that the approach of importing/recovering zeroid user using master_seed on other PC with stock zeronet installation (without importing any data/ files from your main zeronet installation) means you will not see any of yours subscriptions at ZeroHello. You will see only username mentions and be able to post new content using your imported username.

So i assume, to recover/watch your subscriptions, you have to still copy/migrate data/users.json file i assume (i found it contains subscriptions).
