### ISSUE TITLE
Why two PC in the same local network which also connect internet can not download big files quickly? I upload a big file (1GB) using one PC, but it is difficult to download it in another PC. Thanks.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1309]
### Step 1: Please describe your environment

  * ZeroNet version: _0.6.2____
  * Operating system: _WIN7____
  * Web browser: __firefox___
  * Tor status: disabled
  * Opened port: no
  * Special configuration: __no__

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by tangdou1** [comment]
It is the reason that I am in China.

**Comment by 6543** [comment]
In ZN 6.2 there should be a local node discovery but not with tor only enabled.
wich netmask do you use for these PCs?

**Comment by tangdou1** [comment]
Tor status: disabled
