### ISSUE TITLE
Allow for unicode characters in domain names.

### ISSUE THREAD

**Issue by bloff** [HelloZeroNet/ZeroNet#131]
http://127.0.0.1:43110/lýc.bit/

Fails with python exception message:
Err: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128) in UiServer.py line 71 > UiRequest.py line 64 > UiRequest.py line 389

Just curious: any plans to move to python 3? Any library dependencies which are not available there?

**Comment by bloff** [comment]
There is also an error with the encoded domain-name form:
http://127.0.0.1:43110/xn--lc-0ka.bit

Fails with python exception message:
Err: AttributeError: 'NoneType' object has no attribute 'group' in UiServer.py line 71 > UiRequest.py line 56 > UiRequest.py line 148 > UiRequestPlugin.py line 20 > UiRequest.py line 237 > UiRequestPlugin.py line 32

**Comment by bloff** [comment]
Also worth saying, when I goto http://zero/xn--lc-0ka.bit (using zeronet chrome extension), I get a weird message:
Not Found: data/xn--lc-0ka.bit/index.html

I already tried to actually create such a file in my website, to no avail.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, we going to check the possibilities. Utf-8 domain names [not supported in Namecoin](http://wiki.namecoin.info/?title=Domain_Name_Specification_2.0#Valid_Domains), the domain-name encoding could be a workaround for this problem.

Python3 is not planned yet, because most of linux distribution still comes with python2 and the gevent liblary is not supported in Python3.

**Comment by Idealcoder** [comment]
I'd like to point out a security concern with allowing UTF8 domain names. It would make it very easy to create a spoof version of a website for phishing, and use a very similar looking domain address with a different character. So I'm not sure if it is a good idea.

**Comment by deavmi** [comment]
@Idealcoder True.

**Comment by deavmi** [comment]
Keep things simple. Are there any domains on the DNS (not namecoin's DNS) that have Unicode characters other than the standard english ones in their domain name?

**Comment by HamishMacEwan** [comment]
IDN and new gTLDs have meant the era of ASCII only domain names in the DNS is over, except that they use punycode which is ASCII.  These are the xn-- strings appearing from the OP.

It's completely possible for ZeroNet (and possibly the plug-in) to recognise non-ASCII, punycode it and look it up in Namecoin's register blockchain.  It is not necessary to register the Unicode directly in Namecoin, and the OP hasn't.

Some xn-- names are working, http://127.0.0.1:43110/xn--tqh.bit for example AKA ⑂.bit (http://namecha.in/name/d/xn--tqh)

**Comment by border0464111** [comment]
As talked on https://github.com/HelloZeroNet/ZeroNet/pull/735 it seem to add more confusion then it help.

Maybe some can add a new dimention to the debate but at this point, the decision seem to be that it work as designed. Zeronet do not plan to support non-ASCII char in domain name.
