### ISSUE TITLE
Cosmetic adjustment ( 0 ) menu colors for greater visibility

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1311]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Win. 10
  * Web browser: Firefox
  * Tor status: available
  * Opened port: yes

### Step 2: Describe the problem:

When i first used Zeronet i remember i had issue with zite ( 0 ) menu, i overlooked the fact the menu can be scrolled down. And i was just writing a tutorial which reminded me this.

#### Observed Results:

menu scrollbar is black and in my case do not enough contrast with menu black background color

#### Expected Results:

Please kindly adjust colors so it can not be overlooked that there is a scrollbar in the zite ( 0 ) menu

**Comment by HelloZeroNet** [comment]
Added a bit more visible color for the scrollbar: https://github.com/HelloZeroNet/ZeroNet/commit/9d1f491a899ff773f9e1ffed0be51e1d3f00de26
