### ISSUE TITLE
Can the WebTorrent web "instant.io" be used in the ZeroNet?  Is it possible to use windows object?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1312]
Thanks for your answer.

**Comment by tangdou1** [comment]
Please close this comment. I have implement it.
http://127.0.0.1:43110/1MRDU8xYdmRqKVxomnVuh1F1YD1CJeqCa8

**Comment by krixano** [comment]
@tangdou1 I'm pretty sure you can just close this yourself.
