### ISSUE TITLE
[Suggestion] Add a button "open in folder" in the "0" to see the website source code.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1314]

**Comment by skwerlman** [comment]
this option (and probably similar ones too) should be behind some sort of 'developer mode' flag in the main options. this way, people who want these features have them, and it avoids confusing less experienced users.

**Comment by imachug** [comment]
Working on PR.

**Comment by tangdou1** [comment]
Ok, I think it has been completed by imachug！ Nice!
