### ISSUE TITLE
Sites with UTF title unable to open

### ISSUE THREAD

**Issue by saber28** [HelloZeroNet/ZeroNet#1315]
### Step 1: Please describe your environment

  * ZeroNet version: 3350
  * Operating system: ZeroNet client run on Debian 9, browser run on windows 10 and android 6
  * Web browser: Chrome 64.0.3282.186
  * Tor status: enabled
  * Opened port: yes
  * Special configuration: UI Password, Caddy reverse proxy

#### Steps to reproduce:

  1. Update to 3350
  2. Visit sites with UTF characters in title, like nekox.bit

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

Unable to load the site

#### Possible Reasons:

`window.self !== window.top` may work improperly when cross-OS and UTF characters in title, 

#### Expected Results:

  * What did you expect to happen?
Open sites with UTF characters in title like versions before 3350

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev3351 https://github.com/HelloZeroNet/ZeroNet/commit/70489871573e1fbcd0c777c02488c4ea7ffd8988
