### ISSUE TITLE
Renaming feature - big files are re-downloaded when owner rename files or change directory

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1318]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2

### Step 2: Describe the problem:

It may be good if zeronet prevent deleting and re-downloading of the big files just because zite owner renamed file or moved it into different path on the zite or if same file already exist. This feature was also described [at ZeroTalk](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1520004466_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS).

By the way i am not sure if this is technically related, but it would be convenient if ZeroNet prevent duplicity of the files as [described here](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1515669115_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS). (If Zeronet will be aware of all the big files checksums and prevent duplicity thanks to that, it would be handy.)

**Comment by caryoscelus** [comment]
Are there any updates on this?

**Comment by HelloZeroNet** [comment]
Not yet, but just started working on it.

**Comment by HelloZeroNet** [comment]
Landed in Py3/Rev4080. After renaming bigfiles the piecemap has to be re-generated, because it's also contains the file name. (alternatively to avoid re-hashing the filename could be modified in the msgpack file, but there is no built-in support for this)
