### ISSUE TITLE
How to publish websites under the command line

### ISSUE THREAD

**Issue by sxueck** [HelloZeroNet/ZeroNet#1321]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: Ubuntu 16.04 LTS  (Server)
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?
How to publish my websites under the command line？？

**Comment by imachug** [comment]
Use `zeronet.py siteSign address_of_site private_key`. This will sign & publish automatically.

**Comment by HelloZeroNet** [comment]
The you also have to add `--publish`, so: `zeronet.py siteSign address_of_site private_key --publish`
