### ISSUE TITLE
all.js.zip/all.js 404 (Not Found)

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1322]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 (rev 3356)
  * Operating system: Ubuntu 16.04
  * Web browser: Opera
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:

New ZeroNet install from ZeroBundle-linux64.tar.gz. 
Visit site moneynetwork.bit
127.0.0.1/:2571 GET http://127.0.0.1:43110/moneynetwork.bit/js/all.js.zip/all.js net::ERR_ABORTED
10:48:22.240 127.0.0.1/:2571 GET http://127.0.0.1:43110/moneynetwork.bit/js/all.js.zip/all.js 404 (Not Found)

Checked. all.js.zip was downloaded correct. Could be unzipped. Changed index.html to use all.js and site was working OK

Log starting with all.js.zip/all.js (ERROR) and page reload at 10:38:36.824 with unzipped all.js (OK)
[127.0.0.1-1520674918554.log](https://github.com/HelloZeroNet/ZeroNet/files/1799252/127.0.0.1-1520674918554.log)

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
The all.js is a special filename (it tries to compile when you request it), so please try to rename it to something else and try that way

**Comment by jaros1** [comment]
It is the first time I have seen problems with all.js.zip/all.js unzip in ZeroNet. Normally working OK. 
Tested first contact from a win10 VM using google chrome ZeroNet 0.6.2 rev 3327. No problem here. 
Will upgrade to rev 3356 and retest

**Comment by jaros1** [comment]
Tried using all.js.tar.gz/all.js instead of all.js.zip/all.js. Same error. Checked UI-server log :
[18:05:13] Ui.UiServer Error opening archive file: local variable 'header_allow_ajax' referenced before assignment
[18:05:13] Ui.UiServer 127.0.0.1 - - [2018-03-14 18:05:13] "GET /moneynetwork.bit/js/all.js.tar.gz/all.js HTTP/1.1" 404 439 0.001977

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it's fixed in Rev3367, please update and try again

**Comment by jaros1** [comment]
Thank you. Tested OK in Opera with rev 3367 and tar.gz archive
