### ISSUE TITLE
is it possible that zeronet supports backend?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1323]

**Comment by imachug** [comment]
I don't think so. `Backend` means server-side, which means `has server`. However, ZeroNet was created especially to remove servers.

In practice, (practically) everything that is possible to be done on backend is also possible in ZeroNet's frontend. You can manage files here, you have permissions, etc.

If you have any reasons to use backend, it is possible that the same can be easily done with backend, so you can ask for help here, at Gitter, at ThunderWave, at ZeroExchange, etc.

**Comment by tangdou1** [comment]
thanks for your nice answer.

**Comment by DaniellMesquita** [comment]
@tangdou1
If you ask about reading thumbnails from a video file, converting images/audios/videos, and some other backend tasks that PHP sites/server does, yes it is possible on ZeroNet by using @imachug plugins (PeerMessage/BackgroundProccessing)
