### ISSUE TITLE
Please remove it. HEUR.JS.Trojan.b

### ISSUE THREAD

**Issue by DATSEC** [HelloZeroNet/ZeroNet#1327]
**Microsoft Windows**
https://github.com/HelloZeroNet/ZeroNet-win/archive/dist/ZeroNet-win.zip

https://www.virustotal.com/ru/file/0807b49e8cbb78b81d8add93ba2e9b8c1c8dce38ee664743f9779520bdc315fd/analysis/1520756879/

**Apple macOS**
https://github.com/HelloZeroNet/ZeroNet-mac/archive/dist/ZeroNet-mac.zip

https://www.virustotal.com/ru/file/5839c5896a6d3f7d8e272c9c04e39a9f81848d257e51b7c668046b15e9bbb3b5/analysis/1520757054/

**Comment by HelloZeroNet** [comment]
It's just a false positive match, so can't do anything.
