### ISSUE TITLE
control_auth_cookie documentation is outdated 

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#1331]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: archlinux
  * Web browser: firefox
  * Tor status: always
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:
simple adding the user to tor usergroup does nothing 
#### Steps to reproduce:

  1.  follow the documentation  

#### Observed Results:

> Status: Error ([Errno 13] Permission denied: '/var/lib/tor/control_auth_cookie')

edit for the record i use this method to get zeronet nothing from aur https://github.com/HelloZeroNet/ZeroNet#linux-terminal

**Comment by HelloZeroNet** [comment]
Have you logged out, then in after you added the user to the group?

**Comment by icf20** [comment]
yes and rebooted and nothing works except editing torrc and  placing `User myusername` and then start tor like `sudo tor`

other option could be to edit /usr/lib/systemd/system/tor.service

**Comment by HelloZeroNet** [comment]
Do you have any suggestions which solution would be the best?

**Comment by didlie** [comment]
It is highly recommended that a stable Chromium build be optimized and bundled for ZeroNet. This is the only way to control updates and code deprecation.

**Comment by imachug** [comment]
Hey @didlie are you going to pack Chromium, Tor, I2P and ZeroNet in one package???

**Comment by didlie** [comment]
Yes

**Comment by icf20** [comment]
has this progressed or should i close this issue because of lack of updates ?

**Comment by HelloZeroNet** [comment]
I have tried to install the tor from apt package, but ran into systemd error "tor.service: Failed to set invocation ID on control group /system.slice/tor.service, ignoring: Operation not permitted" without modifing anything.

So I ended up running tor as the same user as ZeroNet client where there is no cookie file read permission problems.

We just started to include Tor for windows installations, probably the most compatible solution would be do the same for Linux.

**Comment by HelloZeroNet** [comment]
According to http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1528116214_16CWdkXYYRnpct8GYS7GgD6yFcJHPXfMy8/ZeroNet+Tor+permission+error this configuration of Tor works:
```
CookieAuthentication 1
DataDirectoryGroupReadable 1
CookieAuthFileGroupReadable 1
ExtORPortCookieAuthFileGroupReadable 1
CacheDirectoryGroupReadable 1
CookieAuthFile /var/lib/tor/control_auth_cookie
```
