### ISSUE TITLE
If I download the folder of a zite in computer A from computer B, can I copy the original file of the zite from computer B to the folder of the zite in computer A?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1332]

**Comment by didlie** [comment]
Yes, but you need the private key in your json file to secure changes you make to the page on computer B

**Comment by tangdou1** [comment]
I found that it is difficult to access a zite created by me from PC A in PC B sometimes. So I want to copy the file of zite from PC A to PC B. But it went wrong when I access the zite from PC B, although the file of this zite is copied to PC B indeed. It just show nothing. Weird.

**Comment by didlie** [comment]
Sounds like a reference problem in your code

**Comment by imachug** [comment]
> I found that it is difficult to access a zite created by me from PC A in PC B sometimes. So I wanted to copy the file of zite from PC A to PC B. But it went wrong when I access the zite from PC B, although the file of this zite had been copied to PC B indeed. It just show nothing. Weird.

What does it show? Did you visit the link like `http://127.0.0.1:43110/address` or ZeroHello?

**Comment by tangdou1** [comment]
Yes, I vist by the link like http://127.0.0.1:43110/{the site address}. I see the sidebar, it shows these files are not downloaded. However, I copy them to the folder of the site indeed.

**Comment by tangdou1** [comment]
It should work. Just like that the  big files can be copied from anthor way not by just downloading it.
