### ISSUE TITLE
frozen navigation when trying to return to main menu

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1334]
### Step 1: Please describe your environment

  * ZeroNet version: __current download___
  * Operating system: ___windows 10, 64 bit__
  * Web browser: __Edge___
  * Tor status: not available/always/disabled -- always
  * Opened port: yes/no -- no 
  * Special configuration: _nothing special___

### Step 2: Describe the problem:
browser froze in process when trying to navigate away from GIF page
#### Steps to reproduce:
go to gif page, click around, and try to get back to the main menu... nothing happens

#### Observed Results:
no page change, no navigation
  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?
return to the previous page, the main menu, or some other navigation menu via the user options button
![capture](https://user-images.githubusercontent.com/31107452/37565832-4d8fc7a6-2ab9-11e8-9908-67b689c6cfb9.PNG)

**Comment by skwerlman** [comment]
how did you attempt to return to the main page? is zeronet still running when this happens?

**Comment by didlie** [comment]
Conflict with the Edge browser or Edge browser settings.

**Comment by krixano** [comment]
It's not *frozen*, it just can't find the page, exactly what Edge is telling you: `can't reach this page`.

**Comment by didlie** [comment]
#1338
