### ISSUE TITLE
Rebranding! URL dependencies!

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1336]
What steps have been taken to prevent re-branding?

Does this package have URL dependencies?

Obviously the peer identities must be provided, at least partially, by at least 1 static URL referenced in the code. What is this URL?

### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by skwerlman** [comment]
what do you mean by 'rebranding'? if you mean a fork or reimplementation, there's nothing stopping that.

as far as initial peers, that's handled by connecting to one of a number of torrent trackers to bootstrap the peer list. see https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Config.py#L35 for the default list

**Comment by didlie** [comment]
Are torrents from other sources added to the list? It looks like ZeroNet is also a torrent aggregator. Is that right?

**Comment by skwerlman** [comment]
no, zeronet only uses torrent trackers to handle the sharing of peers

**Comment by didlie** [comment]
DHT will be a big step forward to an independent platform. This should be the number 1 priority.

**Comment by didlie** [comment]
#1333
