### ISSUE TITLE
TOR:ALWAYS -- Using Tor for anonymity is a self-contradicting concept

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1337]
Be aware that the Tor network cannot be used for anonymity. The Tor network itself traces the origin and destination of all requests and statistics are available.

**Comment by HelloZeroNet** [comment]
Do you have any source on this information?

**Comment by didlie** [comment]
Tor developers discussion group... only from them. No personal experience, but the developers showed us a map (location specific usage) and statistics relating to tor access.
