### ISSUE TITLE
Does not work on MS Edge. Custom ZeroNet Chromium build recommended.

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1338]
Microsoft is fighting this. The JS functionality does not work on MS Edge. I request complete departure from MS Edge compatibility, that will never be achievable.... Also custom browser from Chromium as an App to fully support ZeroNet functionality.

**Comment by HelloZeroNet** [comment]
I just tested and it's work without any problem on edge for me. A custom browser could be possible and welcome if anyone write one, but I prefer to make browser independent as it makes download-less browsing ZeroNet sites possible using open proxies.

**Comment by krixano** [comment]
*Sigh* Of course you would automatically jump to `Microsoft is fighting this.`

**Comment by didlie** [comment]
If I get the javascript failures again, I will take some screen shots and provide steps to recreate the errors

**Comment by didlie** [comment]
This might be an issue with the GIF site, but the user interface is completely frozen. This doesn't happen in Chrome; only in Endge. 
1) go to the Zero Gif page. 
2) click on one of the options, example used: r/Gifs -- the page loads properly
3) try to click on one of the other links, example used: DevopsReactions -- page doesn't change, shows as loading in the address bar on Edge
4) Wait... nothing happens
5) Wait... nothing happens
6) Try to click on another link... example used: number 0 or click on r/Gifs again --- nothing happens - no loading animation in browser address bar.
7) clicking any button here does nothing...

-- Only on Edge

Also a chat error in Edge. I don't knw if this is antispam, or an actual javascript error


Images are ordered inversely

==================

![edgeerror1](https://user-images.githubusercontent.com/31107452/37584296-992b74cc-2b5d-11e8-9014-6326018fc6ff.PNG)

![script-stopped-none-of-the-buttons-work](https://user-images.githubusercontent.com/31107452/37584309-a4a2c990-2b5d-11e8-8599-1eb32c969019.PNG)

![gifpagerror-clicked-on-most-liked-and-no-action-frozen](https://user-images.githubusercontent.com/31107452/37584324-b5daabec-2b5d-11e8-9f1a-9eca5b9ba5f8.PNG)

**Comment by didlie** [comment]
Here is the console log --- shows some video rendering errors and deprecated notice
(( I think that it might be neccessary to deploy a stable Chromium build that is known to support this application, to ensure stability and viability; or users will eventually leave when Microsoft and Google decide to deprecate functionality ))
![console-log](https://user-images.githubusercontent.com/31107452/37584451-2fb2d778-2b5e-11e8-8d73-e1169fa54d3d.PNG)

**Comment by didlie** [comment]
After a long wait, the page finally loaded.
