### ISSUE TITLE
Cross-site error "Content signing failed 'sha512'" when uploading a file

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1339]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 rev3367
  * Operating system: Windows 10 64bit
  * Web browser: Firefox
  * Tor status: available
  * Opened port: checking
  * Special configuration: VPN used

### Step 2: Describe the problem:

Hello, today me and a [few other users](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1521327196_17sKEqKEfBUwp5e5dB4irTmqc8A44jUqPS) started to see the issue when uploading files to zeronet sites like KopyKate big, IFS, ZeroUp.

It shows the [sha512 error](https://github.com/zer0net/ifs-master/issues/164)

Note that files uploaded this way remains in zeronet users directories even after you delete it on zite and zite is rechecked/updated on ZeroHello.

**Comment by HelloZeroNet** [comment]
Thanks fore reporting, I was able to reproduce and fix the problem in Rev3371 https://github.com/HelloZeroNet/ZeroNet/commit/0533f29e7a0482db7eeb85003bfae0a128d64b77
