### ISSUE TITLE
Minimize the complication creating a new website with simple form fields on creation. Add PHP 7

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1343]
Embed Xampp as an option, with full MYSQL and PHPADMIN and PHP 7. Wow... 1/2 a billion Indians will grab it and join the swarm.

**Comment by didlie** [comment]
Embed xampp

**Comment by HelloZeroNet** [comment]
Decentralized websites require different working mechanism, so unfortunately no traditional webpages will work. Adding PHP support also would introduce lots of security questions as it not sandboxed like javascript in the browser.
