### ISSUE TITLE
Requested link to step-by-step build instructions, with proven Python version number

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1345]
Please link us in the Readme documentation to step by step build instructions with the proven version of Python. Please specify specs for Windows, Linux and MacOs builds, and reference cached dependencies - i.e. this repo folder containing all the proven dependencies with in their proven version.

**Comment by HelloZeroNet** [comment]
Python is not a compiled language, so you don't have to build it.
You can install the dependencies using `pip install -r requirements.txt`, then start it with `python2 zeronet.py`

**Comment by didlie** [comment]
How do you create the windows executable?... (I'm a PHP and Javascript developer)
What version of python?

**Comment by HelloZeroNet** [comment]
I have used this script: https://github.com/HelloZeroNet/ZeroBundle/blob/master/compile/compile_win.cmd

**Comment by didlie** [comment]
looks good... yet to test
