### ISSUE TITLE
We need a Linux server module that acts as a site specific mirror... with a dedicated IP address

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1347]
So: a zeronet site owner can also make their site available on www with a traditional URL. ... as a mirror of their zeronet based zite

**Comment by HelloZeroNet** [comment]
There is a Multiuser plugin that allows you to run multiuser public proxies. As ZeroNet is a standard http server you can use Apache/Nginx to proxy the connections to it.

**Comment by didlie** [comment]
Where is the multiuser plugin? 
I can use Apache or Nginx to proxy connections to a standard www domain url. Can you be a little more specific about how I would do this?
