### ISSUE TITLE
If I create 20 websites, for example, and each has its own private key, can I backup my "wallet?"

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1348]
If a user creates multiple websites and needs to save their private keys in case of a computer failure, or if they change their computer, or if they change their OS... etc. And the user wants to restore their sites and control of their sites after a system failure (or system change) is ti possible to restore their sites from the peer network, with a private backup of public-private key pairs?

**Comment by HelloZeroNet** [comment]
Yes, you have to backup sites.json and users.json file from the data directory

**Comment by DaniellMesquita** [comment]
Reference: #1534
