### ISSUE TITLE
Previous Version Reference Request

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1351]
What previous version of ZeroNet would be best for the deployment of a single website, that does not download other websites and does not include additional zero-zites, and is fully discover-able across the zeronet network? The easiest version that is fully functional with the network and has the fewest accessories.... the easiest to dissect?

**Comment by HelloZeroNet** [comment]
There was no single-site version. For security reasons it's always recommended to run the latest version, but you can disable the plugins by adding `disabled-` prefix to the directories.
