### ISSUE TITLE
Can you tell me the reason why the feature of big file does not work well? Thanks.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1352]
### Step 1: Please describe your environment

  * ZeroNet version: __0.6.2__
  * Operating system: ___Windows7__
  * Web browser: __firefox___
  * Tor status: not available
  * Opened port: no
  * Special configuration: _no__

### Step 2: Describe the problem:

I found that when I publish a new site, the small files, near 10MB, in the site can transfer to the other's person well, however, the big files, just 18MB, cannot transfer to the other's person. It is so weird.

[Others: just for idea
And I found the big files can be tranfered by the webttorrent. It maybe a idea to combine the code of Webttorrent into the ZeroNet.
]

#### Steps to reproduce:

Publish a new site with a small file and a big file, then access the sites through another PC.

#### Expected Results:

Hope someone can fix the problem.

**Comment by imachug** [comment]
There is site size limit, so maybe it is set to ~10MB, and your 18MB file is just running out of limit.

**Comment by tangdou1** [comment]
@imachug Yes, but I set all the files to optional. So there are many small files, near 10MB. They can tranfer to other's PC. But for these big files, near 18MB, they cannot tranfer to other's PC.

**Comment by HelloZeroNet** [comment]
Does the piecemap.msgpack file got transferred? Have you requested the big file with an http request?

**Comment by tangdou1** [comment]
>Does the piecemap.msgpack file got transferred?
No, the picemap.msgpack can not tranfer to the others's PC.

>Have you requested the big file with an http request?
I can not understand. I just visit the site with the big files, but can not get the big files just get these small files. The bigfile just be smaller than 20MB, and the small file just near 10MB.

**Comment by tangdou1** [comment]
You can test these two game sites.
Site A with a 5487 KB file but no  piecemap.msgpack feature.
http://127.0.0.1:43110/1KG9WvnmV5fLvhMmqH6C78DrSdJ3teZmvV

Site B with a 5459 KB file using the piecemap.msgpack feature and a 12480 KB file using the  piecemap.msgpack feature .
http://127.0.0.1:43110/1F5p2NpSKJPD7VBZdYfytiJ6VpJkEkyQ5c/

The files of Site A can be transferred to others's PC. However, the files (only for the 5459 KB file and 12480 KB file) of Site B can not be transfered to others's PC.

**Comment by HelloZeroNet** [comment]
It took a while, but it's got downloaded for me. (the game loaded)

**Comment by tangdou1** [comment]
you download the two game sites or just the first one？

**Comment by HelloZeroNet** [comment]
The second one: http://127.0.0.1:43110/1F5p2NpSKJPD7VBZdYfytiJ6VpJkEkyQ5c/

It's recommended to have opened port or at least tor connection support for distributing big files

**Comment by tangdou1** [comment]
It is strange that I can obtain the files of the second one now. 
The toc connection is just for safe to hide ip, but would slow the connetion rate, is it right? 
So the big files connection would be not related with tor connection, is it right?

**Comment by imachug** [comment]
@tangdou1 AFAIK Tor mode allows you not to keep the port open.

**Comment by tangdou1** [comment]
Thanks for your comments. Maybe it is just the reason of my poor network environment.
