### ISSUE TITLE
Python 3 - and the need for a compiled app

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1354]
I don't know if anyone noticed, but Python is now in version 3. This means that Visual Studio defaults to Python 3. This means that downloading Python defaults to version 3. and... more importantly... this means that ZeroNet code doesn't work in the latest version of Python.

**Comment by HelloZeroNet** [comment]
It's a pretty big task, but planned later this year

**Comment by krixano** [comment]
You can download python 2.
