### ISSUE TITLE
When 0 is dragged left, you must drag it back right to get back to the site.

### ISSUE THREAD

**Issue by Ornataweaver** [HelloZeroNet/ZeroNet#1356]
Let the user just click anywhere on the page, out of the side-menu, to close it.

**Comment by Ornataweaver** [comment]
It takes so much energy to focus the mouse on the zero again then instead of clicking it, one has to drag it.
It takes so much time.

**Comment by HelloZeroNet** [comment]
In the latest Rev you can go back to page by clicking on the grayed area
