### ISSUE TITLE
When I close the ZeroNet, the tor.exe in tool/tor/ is not closed automatically.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1357]
Plz close the tor.exe automatically, when I close ZeroNet.

**Comment by HelloZeroNet** [comment]
I just tested and it's closes for me. What version of zeronet you using, Tor, Tor mode?

**Comment by tangdou1** [comment]
ZeroNet: 3377 
Tor: the latest 
Tor Mode: available

**Comment by tangdou1** [comment]
windows 7

**Comment by tangdou1** [comment]
When I close ZeroNet and want to move the directory of it, the Windows show that the tor.exe are using it and can not move the directory of ZeroNet.

**Comment by didlie** [comment]
You can open TaskManager and close Tor.exe and then all of the files can be deleted and moved.

**Comment by tangdou1** [comment]
yes, I just close the tor.exe by using Taskmanager

**Comment by tangdou1** [comment]
I found there is a start.cmd for starting tor, but no stop.cmd for stopping tor

**Comment by HelloZeroNet** [comment]
Actually it's for starting tor, so weird if it's stopping for you :)

**Comment by HelloZeroNet** [comment]
I just tested it with the latest tor.exe and it's still shutting down for me.
Have you shut it down correctly with 3dot menu on ZeroHello > Shut down ZeroNet?
Does log/debug.log contains a "TorManager Stopping..." line around the end?

**Comment by tangdou1** [comment]
Oh, I works correctly now, when I shut it down with 3dot menu on ZeroHello > Shut down .
I thought ZeroNet did not implement automatic tor shutdown, so I proposed the suggestion here. But It works well now. Maybe I close it wrongly. Anyway, Thanks very much!
