### ISSUE TITLE
[Suggestion] If I know my friend's ip address, can I make a dirrect connection with him(her), then his(her) ip appears in the Stats page, just like a ping command or input box for ip?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1358]

**Comment by didlie** [comment]
I recommend a very useful new functionality available in Chrome and Firefox that might be just what you are looking for: WebRTC. You can also see Simple WebRTC, and if you do enough research you will find many fun and useful javascript code snippets that do exactly what you are asking about.

**Comment by tangdou1** [comment]
But ZeroNet does not implement it, see:
https://github.com/HelloZeroNet/ZeroNet/issues/449

**Comment by tangdou1** [comment]
Ok, I have known something about the local net and public net. If my friend and I are in the different local nets, which means we can access the internet but get the local net ip address (it is true in china), it is impossible to connect him(her) just by the tempory public ip that is used for get information from internet.
Aslo, I know the reason why the big files can not tranfer to others well. Because the ISP (in china) just assigns a local ip address to us, although we can access the internet service. For BT transmission in ZeroNet, only the public ip address can be useful. So if nobody with a public ip address access your new site, other people only having the local ip address could not get your new site.

**Comment by tangdou1** [comment]
Luckly, we have the ipv6 address. Hope ZeroNet realse the ipv6 function.
