### ISSUE TITLE
GeoLite2 City 

### ISSUE THREAD

**Issue by donuttomypatreon** [HelloZeroNet/ZeroNet#1359]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Windows 10
  * Web browser: Waterfox
  * Tor status: Unknown
  * Opened port: No
  * Special configuration: None

### Step 2: Describe the problem:
When I was using ZeroNet, a file called GeoLite2 City was downloaded to my data directory in my ZeroNet folder. After some googling, I saw it was referenced in some code on here. Anyway I could disable random files being downloaded without my permission? Was it part of ZeroNet? I'm new to this, so apologies if I seem confused.

#### Steps to reproduce:

(don't know what this means)

#### Observed Results:

The file just sat in /data/ and I deleted it.

#### Expected Results:

I don't know

**Comment by tangdou1** [comment]
Yes, it is a part of ZeroNet. When you download it, you can see a globe in the 0 sidebar, which shows the ip address in the earth globe.

**Comment by tangdou1** [comment]
plz close it

**Comment by HelloZeroNet** [comment]
Well it could be possible to add a confirmation button before the download, but not sure if it's necessary.

**Comment by tangdou1** [comment]
It is unnecessary. It would be better to combine the GeoLite2 into the distribution.

**Comment by HelloZeroNet** [comment]
We can't do that due licensing reasons.
