### ISSUE TITLE
PROBLEM : Description Breaks Layout

### ISSUE THREAD

**Issue by S466531257BOSS** [HelloZeroNet/ZeroNet#136]
![description-breaks-layout](https://cloud.githubusercontent.com/assets/6672657/8610792/5b8d4922-26b7-11e5-9ffa-8c0ff465d078.png)

As you can see - the description given breaks the LayOut ;
Any ideas ?

THANKS FOR YOUR INTEREST .

S466531257 BOSS - PAETH CLAUDIUSRAPHAEL

**Comment by HelloZeroNet** [comment]
Fixed: Only first two lines displayed

**Comment by S466531257BOSS** [comment]
Yep , you did it
: WORKS in Chromium
