### ISSUE TITLE
IDEA : ZeroAnnounce

### ISSUE THREAD

**Issue by S466531257BOSS** [HelloZeroNet/ZeroNet#137]
I would like to see a ZeroAnnounce Platform ;
: Look at it like like

: Write ONCE
: Write ONLY if registered ( ZeroID ? )

: TARGET is announcing COPY of ZeroNet-Apps like ZeroBoard
: TARGET is also announcing self- -made | -shared sites

The least two should be split internally ( in terms of holding logs of Announcements )
: the Announcements ( is that a word ? ) should be observable by the registered User announcing its site ( -s ) ;

Hopefully
: You understand what i am aiming for ( in short )

THANKS FOR YOUR INTEREST .
S466531257 BOSS - PAETH CLAUDIUSRAPHAEL

( sry : have a poke running )

**Comment by S466531257BOSS** [comment]
P.S.
: Just to make it

: more easy to share some peronal stuff based on ZeroNet-Apps

: having ZeroNet a list of Apps ( based on their own ) ran by users

[ Compare to WordPress WorkFlow  if you mind ]

THANKS FOR YOUR INTEREST .

S466531257 BOSS - PAETH CLAUDIUSRAPHAEL

**Comment by HelloZeroNet** [comment]
I think creating a separate site for this is not necessary. A zerotalk topic is good for this ( later we can create a topic group for it if it requires).

even later, if we have more quality sites something like https://chrome.google.com/webstore/category/apps would be nice.

**Comment by grez911** [comment]
http://127.0.0.1:43110/Sites.ZeroNetwork.bit/
@HelloZeroNet I think that this is similar to what topic starter proposed. Can the issue be closed?
