### ISSUE TITLE
IPv4 addresses in logs when running with --tor always

### ISSUE THREAD

**Issue by grez911** [HelloZeroNet/ZeroNet#1371]
### Step 1: Please describe your environment

  * **ZeroNet version:** 0.6.2 r3377, Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516], Gevent: 1.1.2
  * **Operating system:** Debian GNU/Linux 9.4 (stretch)
  * **Web browser:** Mozilla Firefox Quantum 59.0.1 (64-bit)
  * **Tor status:** always
  * **Opened port:** no
  * **Special configuration:** UiPassword plugin enabled

### Step 2: Describe the problem:

I see IPv4 addresses in logs when run ZeroNet in TOR-only mode. Is this normal?

#### Steps to reproduce:

  1. Run ZeroNet with `--tor always` option.

#### Observed Results:

In ZeroNet logs:
[16:11:14] Site:1TaLkF..jipT [OK] 94.130.135.180:15441: File not changed 4/6
[16:11:14] Site:1TaLkF..jipT [OK] 89.211.224.199:15441: File not changed 5/6
[16:11:14] Site:1TaLkF..jipT [OK] 173.177.115.104:15441: File not changed 6/6
[16:11:15] Site:1TaLkF..jipT [OK] 91.124.238.172:15441: File not changed 7/6
#### Expected Results:

IPv4 addresses must not be present in logs because I use only TOR.

**Comment by HelloZeroNet** [comment]
That's normal, in Tor always mode you can connect to ipv4 peers using Tor exit nodes.

**Comment by grez911** [comment]
Oh, sorry, forgot about that.
