### ISSUE TITLE
Cannot connect to any peer(Guessing China has blocked peer server)

### ISSUE THREAD

**Issue by catalystsitaly** [HelloZeroNet/ZeroNet#1373]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Ubuntu 17.10
  * Web browser: Chromium
  * Tor status: not available
  * Opened port: no
  * Special configuration: no

### Step 2: Describe the problem:

I newly installed ZeroNet Bundle, When Loading ZeroHello, No peer was found and content.json download failed.

#### Steps to reproduce:

  1. Install Zeronet Bundle following github tutorial
  2. Start ./ZeroNet.sh
#### Observed Results:
<img width="541" alt="2018-04-03 3 23 15" src="https://user-images.githubusercontent.com/38031024/38235392-9e366b14-3753-11e8-9c59-a7529a8da79d.png">

#### Expected Results:

  * What did you expect to happen?
I am located in China.
I guess China has blocked Zeronet's peer server after a massive VPN bans and zeronet.io ban, because zeronet is becoming more and more popular in China.

**Comment by paxinla** [comment]
Same problem, I'm in China too.

**Comment by HelloZeroNet** [comment]
Thanks for the info, looks like GFW has added deep-packet-inspection and port based blocking on ZeroNet.
I was working on it in the past few days and added port-randomization and fixed implicit tls to fix DPI.
After updating to Rev3402 you should able to connect to the network again, but you will only able to connect to peers that using non-standard port.
