### ISSUE TITLE
Why my issue be deleted?

### ISSUE THREAD

**Issue by catalystsitaly** [HelloZeroNet/ZeroNet#1374]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Ubuntu 17.10
  * Web browser: Chromium
  * Tor status: not available
  * Opened port: no
  * Special configuration: no

### Step 2: Describe the problem:

I newly installed ZeroNet Bundle, When Loading ZeroHello, No peer was found and content.json download failed.

#### Steps to reproduce:

  1. Install Zeronet Bundle following github tutorial
  2. Start ./ZeroNet.sh
#### Expected Results:

  * What did you expect to happen?
I am located in China.
I guess China has blocked Zeronet's peer server after a massive VPN bans and zeronet.io ban, because zeronet is becoming more and more popular in China.

**Comment by HelloZeroNet** [comment]
It was closed, because it should work again after you update to latest version: https://github.com/HelloZeroNet/ZeroNet/issues/1373

**Comment by catalystsitaly** [comment]
@HelloZeroNet Thank you very much for your response. Sorry this is my first time to open an issue on github so I don't know you have already closed it. Thanks for your great project!
