### ISSUE TITLE
Is it right that if all the commands 'socket.socket()', 'socket.bind()', and 'socket.connect()' are modified to adapt the ipv6, and add the ipv6 tracker, then the ipv6 could be supported？

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1375]

**Comment by HelloZeroNet** [comment]
It's more complicated as it's also need to modify the protocol to allow exchange ipv6 addresses. (Peer exchange, Optional file finding)

**Comment by tangdou1** [comment]
Oh, thanks for your information. I may have a try, if it is not too difficutl for me.

**Comment by HelloZeroNet** [comment]
It's a pretty complex thing and requires multiple layer changes, so probably it's not the best way to start the modifications.

**Comment by tangdou1** [comment]
Thanks. Maybe I am thinking too much. All I can do maybe is that just add some translation. :)
