### ISSUE TITLE
Bigfile does not obey filesize limit after Rebuild and Check

### ISSUE THREAD

**Issue by thisguy43110** [HelloZeroNet/ZeroNet#1379]
### Step 1: Platforms experiencing the problem
  * ZeroNet version: v3407
  * Operating system: win10pro | Ubuntu 16
  * Web browser: firefox ESR
  * Tor status: not [available]
  * Opened port: yes
  * Special configuration:  home desktop & private proxy

### Step 2: Describe the problem:
Bigfiles autodownload does not obey file limit after Rebuild & Check Files

#### Steps to reproduce:

  1.   Visit KopyKate
  2.  Enable Doanload & Help Distribute all files
  3.  Set File Size Limit To 16MB
  4.  Let data populate 
  5.  Visit site, Pull open right side panel, and click Rebuild database
  6.  Click (Check Files) from main page ZeroHello

#### Observed Results:

Watch your limited storage box fill with a 490gb archive...
Hasn't started happening until the recent 2 updates.

#### Expected Results:

Obtain any missing files / uploads that passed the file size limit criteria.

**Comment by Balancer** [comment]
The same bug when checking files in `ZeroUp`. The Windows version of ZeroNet. **rev3412**.

**Comment by thisguy43110** [comment]
As of v3465 downloading via file limits appears to operate as expected. While larger files will be added to the BigFiles que, they will not exceed 0% completion which is acceptable.
