### ISSUE TITLE
Discover new sites and auto seed on console

### ISSUE THREAD

**Issue by gottesman** [HelloZeroNet/ZeroNet#138]
Hello, it would be great (for me as seeder) to have a way to find all (or maybe the most important or with less seeders) sites in the network to automatically start seeding those sites in console...
I have been thinking about this becouse I have a bunch of VPS on my own including some other physical PCs, and I want to help this network grow.

**Comment by grez911** [comment]
http://127.0.0.1:43110/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n/
@HelloZeroNet I think that this is similar to what topic starter proposed. Can the issue be closed?
