### ISSUE TITLE
Pinned Files do not persist after site removal.

### ISSUE THREAD

**Issue by thisguy43110** [HelloZeroNet/ZeroNet#1380]
### Step 1: Platforms experiencing the problem
  * ZeroNet version: v3407
  * Operating system: win10pro | Ubuntu 16
  * Web browser: firefox ESR
  * Tor status: not [available]
  * Opened port: yes
  * Special configuration:  home desktop & private proxy

### Step 2: Describe the problem:
Pinned files do not persist on site removal.

#### Steps to reproduce:

  1.   Pin a file
  2.  Remove the originating site
  3.  Pinned file has been removed...

#### Observed Results:

Zeronet should not auto-pin large files. Any pinning should be done manually by user.
Pinned files are marked for importance, preservation would likely be desired for that criteria.

#### Expected Results:

A pinned files should be important enough to preserved for extended storage regardless of originating site removal. For example, a user could pin a file from KopyKate, delete the site, still preserve the pinned file(s), and if visiting the site again, choose to seed that file without having to re-obtain it.

**Comment by HelloZeroNet** [comment]
Currently by default if the total sum of the optional files size reaches 10% of your storage free the client will automatically delete the most seeded files.
The pinned files are excluded from this calculation of this limit and they won't be deleted automatically.

If we stop auto pinning big files, then this limit will be reached much easily and you client will delete the previously downloaded big/optional files.

**Comment by thisguy43110** [comment]
Thanks, I did not know this.
