### ISSUE TITLE
[bug?] Can not sign some file with special name. 

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1381]
### Step 1: Please describe your environment

  * ZeroNet version: _3408____
  * Operating system: _win7____
  * Web browser: __firefox___
  * Tor status: not available
  * Opened port: no
  * Special configuration: _no___

### Step 2: Describe the problem:

When I sign a picture with "!Flame.png" or "$up006fc3.png", the picuture never apears in the content.json. Some software need the "!" or "$" in the name for special use, however, ZeroNet never sign these pictures.

**Comment by HelloZeroNet** [comment]
Currently allowed characters in filenames: a-z\[\]\(\) A-Z0-9_@=\.\+-/
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Content/ContentManager.py#L514

**Comment by tangdou1** [comment]
However, I can not add a web game, made by RPGMAKERMV, to ZeroNet. Because it need support "$" and "!" in the file name for special use.
```
Characters (img/characters)
    Images shown for the characters on the map.
    The size for a character image can be changed freely (normally 48x48), and consist of 4 directions (down, left, right, up) and 3 patterns for a total of 12 patterns that will be arranged in the provided order. A file for 1 character will be arranged into 2 rows and 4 columns equaling 8 images. The size of the character will be calculated using 1/12 of the width and 1/8 of the height of this file. Moreover, characters will be shown 6 pixels above tile so that they appear more natural when on top of buildings.

        It is possible treat 1 character as 1 file by including "$" at the beginning of the file name.
        Including a "!" at the beginning of the file name will prevent the image from being shifted 6 pixels and will no longer appear half transparent by bush elements. This is primarily used for objects found in the map such as doors and treasure chests.
        It is also possible to use the "$" and "!" special characters together.
```

**Comment by tangdou1** [comment]
I test it. It can load the js file in zip.

**Comment by tangdou1** [comment]
It can not load js file in zip

**Comment by HelloZeroNet** [comment]
I will check if filenames with $/! has any FS problems.

**Comment by tangdou1** [comment]
thanks
