### ISSUE TITLE
Missing favorite sites, user is logged out of all sites

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1382]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 rev3408
  * Operating system: Windows 10
  * Web browser: Firefox
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser plugin enabled

### Step 2: Describe the problem:

Hello, please can anyone help with [this](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1523000670_1L4dZcDF2maSKHDy788yhxpYnBWnXadUtS/What+if+i+lost+my+favorite+sites+in+menu+and+i+am+logged+out+on+sites)?

(Missing favorite sites on ZeroHello sites sidebar, user is logged out of all sites)

**Comment by HelloZeroNet** [comment]
Do you see your subscriptions/favorites in `data/users.json` file?

Eg. search for "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D" entry and there should be settings.favorite_sites node filled with the addresses you favorited.

**Comment by slrslr** [comment]
@HelloZeroNet 
The file C:\ZeroNet\data\users.json does not contain phrase "settings.favorite_sites" and i searched my backups (even old ones when fav. sites was there) and none contains it...

The file contains example this:

      "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D": {
        "auth_address": "***addresshere***", 
        "auth_privatekey": "***keyhere***", 
        "settings": {
          "favorite_sites": {}, 
          "sites_orderby": "modified"
        }
      }, 

Please kindly let me know what to check/try. Thank you

**Comment by HelloZeroNet** [comment]
Looks like it's empty for you for some reasons. The `favorite_sites` should contain the addresses. I just tried to reproduce the loss of settings/data, but without any success. Please let me know if you find a way to reproduce it.

**Comment by slrslr** [comment]
I remember i killed the .exe process at least once (maybe that could cause problem).

But "Favoriting" sites again is not a problem, it is done quickly, but bigger problem is that i have been signed off the sites. ZeroHello, do not shows any sites in newsfeed and on ZeroTalk and other sites, i am unable to login under my old identity, The Register button on sign box goes to zeroid, but no longer offer me my old "nickname". When i enable multiuser plugin, and relogin using masterseed, i can then login my old username. But apparently i am logged out of all sites.  I can relogin sites, that may not be a big problem (ZeroVoat do not shows login dialog), but what bother me is the question: "i lost my articles, forum topics subscriptions? If yes, how can i restore it, in which file they are?"

[global]
fileserver_port = 32577
language = en
optional_limit = 25.92

By the way, while i am using MultiUser plugin (without it it do not allow me to use my old identity/username) i am launching ZN using "C:\ZeroNet\ZeroNet.exe --multiuser_local", It takes a while before ZeroHello loads sites list, then when i logout (it always login my using multiuser generated username, not by my old username created when i not used multiuser plugin), so i logout and login using my old identity, it load ZeroHello, but without sites in menu and without newsfeed, CPU of ZeroNet process is 15% and HDD writing is 4MB/s for many minutes. The disk usage is linked to C:\ZeroNet\data\users.json-tmpnew. I see it multiple times even it has same PID. users.json is ~5MB. After ZeroHello loaded sites i see my recently favorited sites disappeared again and my login to zerotalk expired again.
I am using 4500 RPM HDD and 250+ zites connected, ~18GB files.

**Comment by HelloZeroNet** [comment]
> i lost my articles, forum topics subscriptions? If yes, how can i restore it, in which file they are?

These data are stored in data/users.json. You can check if there is a users.json-old or similar file in that directory that allows you to restore this data.

> CPU of ZeroNet process is 15% and HDD writing is 4MB/s for many minutes.  users.json is ~5MB

That does not looks good. I just looked my log file and I can confim that there is some problem with users.json writing. Investigating/working on fix.

**Comment by slrslr** [comment]
@HelloZeroNet Thanks, [these are log entries](https://pastebin.com/kb0zuxsp) that appeared during the time ZeroHello was loading and causing high CPU/disk showing process users.json-tmpnew . There were more entries that seemed identic, and last ones was:

[2018-04-12 08:34:07,036] DEBUG    User:SomeStringHereItisAlwaysSame  Saved in 0.325s
[2018-04-12 08:34:07,038] DEBUG    - Gevent block detected: 208.475000143
[2018-04-12 08:34:07,043] DEBUG    WorkerManager:1LdguV..iQfB Timeout, Skipping: {'optional_hash_id': None, 'site': <Site 1LdguV..iQfB>, 'done': False, 'size': 0, 'inner_path': u'content.json', 'peers': None, 'time_started': 1523514626.901, 'time_action': None, 'priority': 10000, 'failed': [], 'workers_num': 4, 'time_added': 1523514626.899, 'evt': <gevent.event.AsyncResult object at 0x0CE308B0>}
[2018-04-12 08:34:07,045] DEBUG    WorkerManager:1LdguV..iQfB nxtgbkasby63ttyi.onion:32577: Force skipping

so it was roughly 3.5 minutes entries like:
[2018-04-12 08:34:07,036] DEBUG    User:SomeStringHereItisAlwaysSame  Saved in 0.325s

was appearing.. As you can see roughly 0.25s per site and i have 250 sites+
When i re-logged as my old username using masterseed at ZeroHello, it refreshed ZeroHello and sites lists was loading almost 5 minutes...

Regarding users.json, i found it contains lines prefixed: "follow": {
So my follows seems to be not lost, but problem is i am logged out of all sites so i am no longer following the sites i followed, unless i browse users.json "follow" lines and manually copy site addresses mentioned in follow "variable" and sign in to the sites to resume my follows.

**Comment by HelloZeroNet** [comment]
I have added modifications to Rev3411 that should fix these problems. Please update and try it.

**Comment by slrslr** [comment]
@HelloZeroNet

i updated, but do not know how to verify it fixed the issue. It seems i continue being signed off the sites i was signed in before issue and when i sign such a site, i find that i am no longer subscribed to the topics (zerotalk clone) i was subscribed to.

**Comment by HelloZeroNet** [comment]
Does the "CPU of ZeroNet process is 15% and HDD writing is 4MB/s for many minutes." is still an issue after login/logout?

**Comment by slrslr** [comment]
Thank you @HelloZeroNet , now after update, CPU does not seem to be the issue (not significantly raised upon zerohello page load or re-login as different user) and HDD (5400rpm) utilization significantly increased for around 25 seconds after i selected to re-login on zerohello. I no longer seen issue with many users.json-tmpnew processes.

Though issue mentioned in my previous reply and previous replies/initial post is still there.

**Comment by HelloZeroNet** [comment]
I have also fixed the "it raises alot and stays like that for around 25 seconds." problem, so user creation should be instant now. (It probably affected public proxy performance the most)
