### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'contactSrc'

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#1384]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 (rev 3408)
  * Operating system: ubuntu 16.04
  * Web browser: Version 65.0.3325.181 (Official Build) (64-bit)
  * Tor status: disabled
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:

- 15:32:47 ValueError: invalid literal for int() with base 10: 'contactSrc' in UI-server log
- fileGet merged-MoneyNetwork/1HXzvtSLuvxZfh6LgdaqTk4FSVf7x8w7NJ/data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/content.json fails after this UI-server error. 
- siteSign fails after this error: Site sign failed: data/users/18DbeZgtVCcLghmtzvg4Uv8uRQAwR8wnDQ/content.json: VerifyError: File not allowed

web console + UI server log:
[127.0.0.1-1523626412006.log](https://github.com/HelloZeroNet/ZeroNet/files/1907791/127.0.0.1-1523626412006.log)

**Comment by HelloZeroNet** [comment]
Probably you made a `anyfilename|contactSrc` file request (`|` is not allowed in the filename and it's used to specify the file range in big files)

**Comment by jaros1** [comment]
Closing. Have only seen this error once.
