### ISSUE TITLE
why it shows this

### ISSUE THREAD

**Issue by wzhb** [HelloZeroNet/ZeroNet#1386]
### Step 1: Please describe your environment

  * ZeroNet version: _0.6.2_
  * Operating system: __win10___
  * Web browser: _chrome____
 
![image](https://user-images.githubusercontent.com/14255631/38765525-f5ad47c8-3ff5-11e8-92bf-6db11661116e.png)
why it shows upgrade failure？ it‘s my own site

**Comment by imachug** [comment]
It shows `cannot update` because noone has the site except yourself, so there is noone who can give you a newer version because your own version is the only one.

**Comment by wzhb** [comment]
I know. I have submitted the website to 0list， and the problem have been solved. thanks
