### ISSUE TITLE
"Not Found &amp;wrapper_nonce=" is back :)

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1388]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 rev3411
  * Operating system: W10
  * Web browser: Firefox
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser plugin enabled

### Step 2: Describe the problem:

In Firefox, open http://127.0.0.1:43110/Talk.ZeroNetwork.bit

Click to open some discussion topic, then click browser back button to return back to the index

then i can see in the address bar right after domain name is: ?wrapper_nonce=
And when i click to open some another topic, then i see blank page:

Not Found
&amp;wrapper_nonce=964951bf9d566a5ad7a6e462907d14ab02699ff24d300839669aff8232c6ecc6

Address is: http://127.0.0.1:43110/Talk.ZeroNetwork.bit/&wrapper_nonce=***?Topic:***_***/I+made+a+site+***

**Comment by krixano** [comment]
This happens for a lot of zites.

**Comment by HelloZeroNet** [comment]
I followed your steps, but no wrapper_nonce for me. W10 + FF 59.0.2
Is it also happening in private window?

**Comment by slrslr** [comment]
@HelloZeroNet yes, it does. [Here are](https://defuse.ca/b/YktaC6NQxdndRgsin7nypv) log entries that should be related..

**Comment by slrslr** [comment]
@HelloZeroNet this issue happen when using mentioned --multiuser-local switch, but when starting without it, there is NO issue...

**Comment by HelloZeroNet** [comment]
I just tested it with Multiuser plugin with --multiuser_local switch and it's still not happening for me. Any other tip on reproduce?

**Comment by HelloZeroNet** [comment]
I have added a fix for it: https://github.com/HelloZeroNet/ZeroNet/commit/3beab611a346a155a5efd0ab565e38ce634fe36f
Please update and see if it's worked for you.

**Comment by slrslr** [comment]
@HelloZeroNet i updated and i can confirm that in single user and also in multiuser mode i no longer see the issue.
