### ISSUE TITLE
Multiuser plugin - logged out of all sites & not subscribed; single user mode- subscribed, but can not login using old ID

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1389]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 rev3411
  * Operating system: W10
  * Web browser: FF
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser plugin

### Step 2: Describe the problem:

I am unsure if this is related to #1382 , what i see as an issue is that when multiuser plugin is enabled, i am logged in as a new identity(user) and when i re-login using my main user/identity master seed (seen in users.json i think) then i see i am logged out of all sites (logged out of zeroid?) so i need to login on each site (first site have to visit zeroid in order to login) and this is bad for me because this way i can not see my subscriptions (on zerohello newsfeed) until i login all sites i am watching, right?

By the way, even when i re-login, i no longer see i am subscribed to a topics i was subscribed (i am talking about zerotalk clone site), and when i check users.json i see that [subscriptions are there](https://pastebin.com/T4qACwZn). (yet unsure if auth_address, auth_privatekey match my current user session or what is that).

When i quit zeronet, disable multiuser plugin, start, i see i am logged out of sites, but the pages/topics i am following in users.json started to reflect that (i see button on zerotalk site is marked as following). But the problem is that when i try to login into zerotalk site, i have to click register button which bring me to zeroid where my old username is NOT recognized and it offer me button "Get auth cert".

So it seems to me that there are multiple issues related to multi user and users.json

In the meantime, please can anyone advise how to fix in users.json so in non multiuser mode the zeronet allow me to use my old identity? What to lookup and edit in users.json? I would use multiuser mode, but in this mode my subscriptions surprisingly does not work.

**Comment by HelloZeroNet** [comment]
If you remove all other users from users.json, then it will use the remaining one in single-user mode.

**Comment by slrslr** [comment]
**How i proceeded with cleaning users.json (not important for developer)**
It seems that zeronet sort usernames in users.json by the username hash/string alphabetically (from 1 to Z maybe) so when i moved first username to the end of the file, it was moved back at zeronet start. So as mentioned by HelloZeroNet i removed all other usernames except my main one from users.json. (backup file before)
Before removal of the content, i search original users.json for a word: follow
copy site address and the string in "follow" section. Example:
1AWwhg4EiWAVttfQboJZ4wJfX3WawfJT3h_1522912179
So later once i deleted all "redundant" users from users.json, i could manually open sites and topics i copied and follow them again manually. That will subscribe me to post replies, not new topics notifications.

**For ZeroNet developers**
After i removed all other users from users.json as recommended by HelloZeroNet in previous reply, i run ZN in single user mode and it worked and i see on Zerohello my favorite sites and also after zeronet start i am logged in to all sites and i am subscribed as i was before issue. **BUT !!** when i enable multiuser plugin and run ZeroNet.exe --multiuser_local and then login to my main user account using master seed, i am logged out of all sites and after relogin to them i am no longer subscribed to topics i was! And when i check content.json i see it removed all my "follows" (when i search for "follow" it says 3 matches, where before it was more than 100). It seems like some issue in multiuser plugin workings @HelloZeroNet ?

So this users.json manual edit can be also answer to issue #1382 
But be careful with multiuser plugin which MAY damage your users.json "follows".
Unsure if i caused this issue somehow or it is a bug of the zeronet multiuser plugin.

**Comment by HelloZeroNet** [comment]
I have tried to reproduce it, but still no success. Can you please try the following: 
 - F12, Storage tab, Cookies, http://127.0.0.1:43110
 - Is there multiple entries?
 - Right click on master_seed entry > delete all

Then re-login to you account and see if you can reproduce the error

**Comment by slrslr** [comment]
@HelloZeroNet hi, when i just updated to latest revision rev3417 this whole issue appears to be fixed. ZeroHello page loads faster and in Firefox i am logged in as my main and only user account as defined in users.json. When i logout and refresh zerohello, it generate new account for me and i do not loose my "follows" (zerotalk and other site topic subscriptions) in users.json. So all good, this whole issue seems to be solved on my end. :-D

The issue that is same or similar like this one is: #1382 and maybe it can be closed.

Thank you

**Comment by HelloZeroNet** [comment]
Nice, please re-open if you experience the error again

**Comment by HelloZeroNet** [comment]
Can you please send the long to tamas@zeronet.io?
