### ISSUE TITLE
Having problems after updating to 0.3.2

### ISSUE THREAD

**Issue by Snarkly** [HelloZeroNet/ZeroNet#139]
I updated to 0.3.2 but now I'm unable to edit my blog and somethings wrong with my zero id, I can't use it
![zeronet](https://cloud.githubusercontent.com/assets/8492776/9365095/aa32d62e-467d-11e5-8325-d5ad17e3727d.jpg)
![zeronet2](https://cloud.githubusercontent.com/assets/8492776/9365101/b2286b00-467d-11e5-9e46-6117173559f5.jpg)

.

**Comment by HelloZeroNet** [comment]
Looks like your identity file (data/users.json) have changed. How did you updated your ZeroNet installation? Using update button on main screen or downloaded an unpacked again?

**Comment by Snarkly** [comment]
I downloaded and unpacked again because the update date button wasn't there, if your talking about the yellow button.

**Comment by HelloZeroNet** [comment]
You have to copy your old data/users.json file to the new installation to have your identity.

**Comment by Snarkly** [comment]
OK did that but didn't seem to work so I'm going to start a new blog.
