### ISSUE TITLE
[BigFile] Invalid Literal for int() with base 10

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1394]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Windows
  * Web browser: Chrome
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

While uploading some big files I received the following error:

![lpaaa](https://user-images.githubusercontent.com/1342360/39034890-0e95160e-4446-11e8-8cbf-696f605ba603.png)

**Comment by imachug** [comment]
What is the file of the name? If it contains `|` it can be a problem.

**Comment by jaros1** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/1384
My problem was a angularJS filter |xxx. Don't know why but the image src was not parsed by angularJS and sent to UI-server with | in file name

**Comment by anoadragon453** [comment]
After playing around with it a bit more I think there was a `|` in the filename. I don't have the logs to catch it, but I also don't disallow that character when I process uploaded files.

Will replace it with something else and try from there. Hopefully should fix it :)
