### ISSUE TITLE
是不是以后都用不了了啊，一直连接不上节点。

### ISSUE THREAD

**Issue by ugvf2009** [HelloZeroNet/ZeroNet#1395]
### Step 1: Please describe your environment

  * ZeroNet version: _____0.6.2
  * Operating system: _____win10 64bit
  * Web browser: _____chrome 66.0.3359.117
  * Tor status: disabled
  * Opened port: no
  * isp-------china unicom

**Comment by imachug** [comment]
Translated:

# Cannot connect to any node.

**Comment by funny110** [comment]
@imachug Use tor always.

**Comment by wqj97** [comment]
+1

**Comment by tangdou1** [comment]
It can be closed.

**Comment by blurHY** [comment]
Tor is not needed.Adding trackers is ok
