### ISSUE TITLE
Connect to trackers using Tor meek bridges

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1396]
# Why?

The GFW started blocking the trackers we use as a result new users from problematic areas won't be able to connect to the network.

# How?

Tor meek bridges using Amazon and Azure CDN network for connection entry point which makes it hard to restrict the access based on IP or DPI rules.

# What?

We can use the meek bridges to connect to the trackers, the required modifications:

 - [x] Bundle tor client with ZeroNet distribution (currently downloaded from tor website on first startup which is not possible in some regions)
 - [x] Add pluggable transports meek-client and obfs4proxy
 - [x] Add new configuration option that controls if the tracker connection should make using tor meek bridges. (eg.: `--tracker_proxy {disable,tor}`)
 - [x] Add new configuration option to enable use of tor meek bridges. (eg.: `--tor_use_bridges`)
 - [x] Refactor announcing process to allow query/store per site announce status/statistics
 - [x] At the "Connecting..." page we should display the tracker request status and add "I need to bypass internet censorship" button that enables tor bridge usage and connects to trackers using tor
 - [x] It would be also useful to add tracker status to ZeroHello and Tor bridge usage settings

**Comment by HelloZeroNet** [comment]
Pros:
 - Relatively easy to implement
 - Tor has long history on how to avoid government censorship
 - We don't need to run our own servers
 - This way we can also connect to other http 

Cons:
 - Requires Tor to be installed/bundled (could be problem on mobile)
 - Relies on Amazon and Azure

**Comment by Chandelier309** [comment]
I'm not sure whether the trackers blocked by GFW are required by zeronet each time it starts? Or, they are only crucial for initializaion?
If only needed for initialization, is it possible for new users to use some other anti-censorship tools like [lantern](https://github.com/getlantern/lantern) or [psiphon](https://psiphon.ca/) to connect to trackers?

**Comment by HelloZeroNet** [comment]
It's required on first initialization and when you wants to visit a new site. I suppose lantern or psiphon should also work the same way as tor meek bridges works

**Comment by Chandelier309** [comment]
I see. Thanks a lot for your explanation.
As there are already so many Chinese users, Can they help in this? No decentralized trackers plan?

**Comment by DATSEC** [comment]
I think it will be interesting to unite with telegram, maybe we will come up with something new.
If of course they agree.

**Comment by HelloZeroNet** [comment]
Trackers are already decentralized, but the GFW are able to ban them based on IP address as they did with the Tor network.

Every censorship-proof network (Tor meek, Lantern, Psiphon, Telegram, Signal) uses big, popular service providers (Amazon cloudfront, Google App Engine, etc.) that GFW could not ban, because many services shares the same IP address so it would also affects them.

So right now this is the best solution we have.

**Comment by DATSEC** [comment]
Most likely they will find solutions to how to block IP addresses sooner or later.
Forcing other companies to give them IP addresses of resources they have a lot.
It is necessary to find solutions for transferring addresses through users.
We can ask the bitcoin developers to make changes to the code to transfer the addresses between users.
They have a lot of nodes https://bitnodes.earn.com/
If we propose that something essential for them they agree

**Comment by kehao95** [comment]
The embedded trackers will be blocked sooner or later. That would be an endless battle by changing IPs.
I don't know if an ZeroNet node can act as a tracker as this moment. If so, I'd suggest adding an api and corresponding UI for users to add their friends' links as trackers. By archiving these, the accessibility can propagate through real world relationships.

**Comment by HelloZeroNet** [comment]
Every peer is also acts as tracker (via PeX), but new users still need to connect somewhere. You can't just try to connect to random ips on the internet.

**Comment by drliu1202** [comment]
>I don't know if an ZeroNet node can act as a tracker as this moment. If so, I'd suggest adding an api and corresponding UI for users to add their friends' links as trackers. By archiving these, the accessibility can propagate through real world relationships

sounds like emule.

**Comment by drliu1202** [comment]
>Every peer is also acts as tracker (via PeX), but new users still need to connect somewhere. You can't just try to connect to random ips on the internet.

i think reseeding like i2p only works for single zite for now.

**Comment by HelloZeroNet** [comment]
It's added in Rev3465, 

To get tor meek bridges the user has to download the ZeroNet-win.zip again, as the previous versions did not have these files included: https://github.com/HelloZeroNet/ZeroNet-win/archive/dist/ZeroNet-win.zip

On the loading screen, it will display "Tracker connection error detected." message and add a "Use Tor meek bridges for tracker connections" button if more than 50% of the trackers fail.

By pressing that button it will enable Tor meek bridges and will use Tor for all tracker connection.

**Comment by katcom** [comment]
I have a suggestion for connection to the network .What if Magnet links assumed the role of tracker servers from which users attain initial nodes?It seems more reliable that the data necessary for initialization was, rather than from tracker servers, downloaded through magnet links authorized and issued by the developers, so that the GFW cannot stop users from connecting other nodes.

**Comment by HelloZeroNet** [comment]
> What if Magnet links assumed the role of tracker servers from which users attain initial nodes

Actually it's already supported since Rev3537 (July 18) for example: http://127.0.0.1:43110/1anysite/?zeronet_peer=1.2.3.4:43110,2.3.4.5:4300

**Comment by qjm100** [comment]
建议在i2p上建立trackers，再用i2p作为跳板连入zeronet
