### ISSUE TITLE
For what is port 36313 needs to be open ? My tor browser works and port is closed.

### ISSUE THREAD

**Issue by jebuscraisp** [HelloZeroNet/ZeroNet#1398]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____ el capitan
  * Web browser: _____ firefox
  * Tor status: port closed
![captura de pantalla 2018-04-21 a las 8 57 23 p m](https://user-images.githubusercontent.com/23113643/39090856-a55ea1de-45a6-11e8-92c4-729bf15df8fb.png)

  * Opened port: no
  * Special configuration: na

### Step 2: Describe the problem:
Should I open port 36313 ? its very obvious but I wanted to check.
#### Steps to reproduce:

 Just follow the instructions. 

#### Observed Results:

  Check the screenshot.

#### Expected Results:

  * What did you expect to happen?
To work with tor from the start.

Thank you for your precious attention.

**Comment by HelloZeroNet** [comment]
It's better if you have opened port, but browsing for the network it's not required, so you can ignore that error.
