### ISSUE TITLE
Problems using web-worker (due to iframe)

### ISSUE THREAD

**Issue by canterburycomputers** [HelloZeroNet/ZeroNet#140]
I'm hoping someone can point me in the right direction (or this can be a bad feature request).

Basically i want to use a web worker (eg. http://bgrins.github.io/videoconverter.js/demo/) but in order to do this in an iframe (zeronet wrapper), allow-same-origin needs to be in the "sandbox" attribute.

For testing I have  modified src/Ui/template/wrapper.html to add this but would like to know if there is a better way to achieve this. 

Thanks.

**Comment by HelloZeroNet** [comment]
Since every website on zeronet using the same origin (127.0.0.1) it would be unsecure to add "allow-same-origin" to sandbox parameters.

I have just tried it and successfully ran webworkers by inline them using Blob URLs: http://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers
