### ISSUE TITLE
Not working behind Nginx reverse proxy

### ISSUE THREAD

**Issue by Menci** [HelloZeroNet/ZeroNet#1400]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: xenial x64
  * Web browser: Chrome latest
  * Tor status: default enabled
  * Opened port: yes
  * Special configuration: nginx/1.10.3

### Step 2: Describe the problem:
My nginx conf:

```nginx
server {
        listen 80; 
        listen 443 ssl;

        include ssl.conf;

        server_name <DOMAIN>;

        location / {
                auth_basic "Only open to Menci and Menci's FRIENDS";
                auth_basic_user_file htpasswd;

                proxy_pass http://127.0.0.1:43110;
                proxy_http_version  1.1;
                proxy_set_header    Host        $host;
                proxy_set_header    X-Real-IP   $remote_addr;
                proxy_read_timeout  120s;
                proxy_send_timeout  120s;
        }

        location /Websocket {
                proxy_pass http://127.0.0.1:43110;
                proxy_http_version 1.1;
                proxy_read_timeout 1h;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header    Host        $host;
        }
}
```

And ZeroNet command line:

```bash
./ZeroNet.sh --ui_ip 127.0.0.1 --ui_host <DOMAIN>
```

#### Steps to reproduce:

  1. Use Nginx with ZeroNet with my configuration above.

#### Observed Results:
WebSocket 400 in Chrome console. And https://<DOMAIN>/WebSocket give me "Not a websocket!". 

#### Expected Results:
ZeroNet works just like connect directly to it with ip:port.

**Comment by ky0ncheng** [comment]
@HelloZeroNet NOT WORK

**Comment by ky0ncheng** [comment]
[07:15:26] Ui.UiServer Error 403: Invalid host:xxx.xxx.xxx

**Comment by grez911** [comment]
Try to simplify a little bit your setup:
```
location / {
    proxy_pass http://127.0.0.1:43110;
}
location /Websocket {
    proxy_pass http://127.0.0.1:43110;
    proxy_http_version 1.1;
    proxy_read_timeout 1h;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```
and run ZeroNet with command:

```
./ZeroNet.sh --ui_ip 127.0.0.1
```

I am using this config without a hitch for months for running a personal ZeroNet proxy.

**Comment by Menci** [comment]
Oh, I'm sorry that I have another reverse proxy in front of the proxy, which have a wildcard pointed to the server behind. I added the save configure to that server with the same and it works. Thanks.
