### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nicolas161** [HelloZeroNet/ZeroNet#1402]
Operating system: Linaro 2011.07 (Linux)
Python version: 2.7.2
Device: Kobo Glo HD
Kernel version (uname -r): 3.0.35+
Shell: /bin/ash

I have installed both python2.7 and the required packages (msgpack-python python-gevent) following the installation instructions. However, when running python zeronet.py inside the zeronet folder, I get a segmentation fault.

These are the last lines in the output of python -v zeronet.py:

> ./zeronet/src/lib/pyelliptic:
> ##/usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
> import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
> ##/usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
> import abc # precompiled from /usr/lib/python2.7/abc.pyc
> ##/usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
> import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
> import _weakref # builtin
> ##/usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
> import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
> ##/usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
> import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
> ##/usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
> import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
> ##/usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
> import re # precompiled from /usr/lib/python2.7/re.pyc
> ##/usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
> import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
> import _sre # builtin
> ##/usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
> import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
> ##/usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
> import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
> import encodings # directory /usr/lib/python2.7/encodings
> ##/usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
> import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
> ##/usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
> import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
> import _codecs # builtin
> ##/usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
> import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
> ##/usr/lib/python2.7/encodings/ascii.pyc matches /usr/lib/python2.7/encodings/ascii.py
> import encodings.ascii # precompiled from /usr/lib/python2.7/encodings/ascii.pyc
> Python 2.7.2 (default, Feb  4 2012, 12:18:06) 
> [GCC 4.4.5] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> -Starting ZeroNet...
> ##/mnt/onboard/.kobo/zeronet/src/main.pyc has bad mtime
> Segmentation fault

(Single '#' signs have been changed to '##' in order to stop triggering some annoying auto-formatting).

Since I am a python noob, I have no idea what the problem can be here. I was wondering if any of you python wizards know what is happening?

**Comment by skwerlman** [comment]
you are running an ancient version of python 2 on an ancient os using an ancient kernel. i'd be surprised if even half the libs 0net uses are compatible with your setup.

regardless of the root cause here, i'd strongly recommend upgrading your entire os as soon as you are able.
see [this list](https://www.cvedetails.com/vulnerability-list/vendor_id-33/product_id-47/version_id-135854/opov-1/Linux-Linux-Kernel-3.0.35.html) for a couple of good reasons

**Comment by imachug** [comment]
@skwerlman

> 2.7.2

Ancient python?

**Comment by skwerlman** [comment]
2.7.15 is the current py2; 2.7.2 was released all the way back in 2011
