### ISSUE TITLE
How to view logs on Windows?

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1406]
I don't see any easy way to do so and would like to file a bug report :)

**Comment by HelloZeroNet** [comment]
I'm using this tool: https://github.com/zarunbal/LogExpert/releases
It made my life much easier as it support live filtering / bookmarks / tabs / highlight etc.

**Comment by anoadragon453** [comment]
So this can hook into ZeroNet's logs?

**Comment by anoadragon453** [comment]
Oh I see, it can read the log files in the logs directory. Thanks!
