### ISSUE TITLE
How to mirror a ZeroNet Zite on the WWW

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1417]
I have a url: https://www.anyawsomesite.com
I want to mirror a Zite on my URL, and use my ZeroNet Zite as a host of the site itself.
How can I do this? Step by step please.

**Comment by Thunder33345** [comment]
i assume you have the source code, and the source code is pure html
all you have to do is create blank then go go the address and put the html in it

**Comment by grez911** [comment]
You can run a ZeroNet on your server and configure nginx to proxy requests from https://www.anyawsomesite.com to http://127.0.0.1:43110/yourziteaddress/
Probably you can find useful [my guide](https://grez911.github.io/zeroproxy.html) about proxy setup. I think all you need is just change one line in the nginx config:
```
proxy_pass http://127.0.0.1:43110
```
to
```
http://127.0.0.1:43110/yourziteaddress.bit/
```

P. S. This is a place for reporting issues about software, not for asking guides. Please, close this issue and create topic at [reddit](https://www.reddit.com/r/zeronet/) or ZeroTalk for a more detailed guidance.
