### ISSUE TITLE
Full server-side ZIP support

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#1433]
### Step 1: Please describe your environment

  * ZeroNet version: v0.6.2 (3467), but doesn't really matter
  * Operating system: Windows, doesn't matter
  * Web browser: Chrome, doesn't matter
  * Tor status: error, doesn't matter
  * Opened port: yes, doesn't matter
  * Special configuration: none, doesn't matter

### Step 2: Describe the problem:

Opening a file within a ZIP, e.g. `127.0.0.1:43110/something/something.zip/gfdfdgd` works. But WebSocket `fileList`, `dirList`, `fileGet`, etc. don't work.

#### Steps to reproduce:

  1. Try `fileGet("yourzip.zip/file_within_zip.txt")`

#### Observed Results:

`File doesn't exist: data/users/1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di/Standard.zip/components/button.vue`

#### Expected Results:

File content.

**Comment by DaniellMesquita** [comment]
@imachug
Does ZIP needs to extract all other files to just read one file?

**Comment by HelloZeroNet** [comment]
it just reads one file

**Comment by HelloZeroNet** [comment]
Full support of fileList, dirList, fileGet on zip/tar.gz files has been added in the latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/c8669328619f46f82ef46419b8f1566db05390d6

([fileList support has been added back in March](https://github.com/HelloZeroNet/ZeroNet/commit/e8a0d56ff8cc291f3a78c755e747f90161255d8b))
