### ISSUE TITLE
Create My Mailbox: File write error: [object Object]

### ISSUE THREAD

**Issue by dotnetspec** [HelloZeroNet/ZeroNet#1436]
### Step 1: Please describe your environment

  * ZeroNet version: _____0.6.2 rev 3467
  * Operating system: _____Win 7
  * Web browser: _____Chrome
  * Tor status: available
  * Opened port: no
  * Special configuration: ____No

### Step 2: Describe the problem:
Select ZeroMail:
Selected username: shoeswasabi789@zeroid.bit......[NO MAILBOX FOUND]
Click 'Create My Mailbox' 
Error msg appears to right: 'File write error: [object Object]'

#### Steps to reproduce:

  1. _____At http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/
Select ZeroMail
  2. _____ Click 'Create My Mailbox' 

#### Observed Results:

Error msg appears to right: 'File write error: [object Object]'

![screen shot 05-23-18 at 03 39 pm](https://user-images.githubusercontent.com/27340988/40410174-ac73ce24-5e9f-11e8-8cf7-142ff3085de1.PNG)

#### Expected Results:

 A message informing me a new mailbox for shoeswasabi789@zeroid.bit has been created

**Comment by imachug** [comment]
Wait for ZeroMail to sync completely (see that green line on top of the window)

**Comment by dotnetspec** [comment]
Thanks for the response. The email is very slow to update despite internet running well. It's been stuck on '298 left' for the past 20 min for eg. I tried opening port 11460 but I still get port closed message top right (I'm not experienced with ports). I tried stopping and re-starting ZeroNet but still 298 left. Anything I can do to get past the blockage?

**Comment by imachug** [comment]
I'd like to say that those 298 left may be just some invalid files, which were malformed by users. Anyways, after most files are synced you will be able to create mailbox.

**Comment by imachug** [comment]
TBH when I have this error I usually delete ZeroMail (open sidebar by dragging 0 in right-top corner, scroll a bit and press <kbd>Delete</kbd> button) and redownload it. This "solution" usually works.

**Comment by dotnetspec** [comment]
Thanks. I did that (had to manually delete the folder in "ZeroNet-win-dist\ZeroNet-win-dist\data" directory first)  and I get the 'successful registration' email although there are still 7 files left.
I now get emails from my Android to my laptop. Can't currently receive email from laptop to Android. I'm deleting files on Android now as well. Hopefully will have an update soon ...

**Comment by dotnetspec** [comment]
I was told that the bot doesn't work - won't send a reply to inbox so had to manually test instead.
