### ISSUE TITLE
Host site without all files downloaded or seeded

### ISSUE THREAD

**Issue by imconcerned** [HelloZeroNet/ZeroNet#144]
If I had a site where I was sharing a lot of videos, I want to create a directory that contains those videos and I want them to only be loaded if the user clicks on them. Can there be a way to make a separate content.json for directories, so that they aren't loaded with the rest of the site, and have separate seeders, etc? I could create a site for each video or couple of videos, and serve links on the main site, but a directory system would be a much better design.

**Comment by ronsoros** [comment]
this.

**Comment by deavmi** [comment]
Maybe there could be a system of requesting a file, and then torrenting it. As you request a file it gets added. Something like that.

**Comment by HelloZeroNet** [comment]
Done in version 0.3.2
