### ISSUE TITLE
zeroid not working for me

### ISSUE THREAD

**Issue by Adrianzo** [HelloZeroNet/ZeroNet#1441]
I get the message "Error while during request: error undefined" which is of no help.

Can anyone help me debug what's going on?

I've installed doing a fresh `git clone`. Maybe I should have installed to an specific version and it's broken because of some of the latest commits?

I'm running from an upgraded Linux Mint, and I've installed `tor` support as per <http://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux> without any troubles.

**Comment by Thunder33345** [comment]
you meant you try to obtain a zeroid and cant?

**Comment by imachug** [comment]
yeah

**Comment by raphyduck** [comment]
Same issue here, trying to register a new identity and getting this error "Error while during request: error
undefined"

**Comment by HelloZeroNet** [comment]
Is it working for you? https://zeroid.qc.to/ZeroID/

**Comment by raphyduck** [comment]
If by working you mean, do I see the word "OK" when I visit the page,
then yes it is :)

**Comment by HelloZeroNet** [comment]
Then please check the javascript console (F12) after you press the "Send request" button

**Comment by raphyduck** [comment]
Ok I found it: I am using noscript and ublock origin to prevent loading js script by default, and though 127.0.0.1 is whitelisted zeroid.qc.to was not. I was able to create an ID by disabling the 2 of them temporarily.

Thanks for the help

**Comment by Adrianzo** [comment]
I also had uBlock origin blocking `qc.to` part. Thanks @raphyduck 

Before closing the issued I'd like to know:

Was this part of the id registration (qc.to) done through tor? Could it be leaking my IP address to this website (specially if it has logging on)?

**Comment by HelloZeroNet** [comment]
The request is done by your browser. So if you use Tor browser, then it's hidden your IP address, if not then it's done without Tor.
