### ISSUE TITLE
What are the fundamental changes planed that make the upcoming release different from the previous stable version?

### ISSUE THREAD

**Issue by didlie** [HelloZeroNet/ZeroNet#1442]
What are the fundamental changes planed that make the upcoming release different from the previous stable version?

**Comment by imachug** [comment]
Practically none. One of the change, though, is the addition of PeerMessage plugin which will allow sites communicate with other peers, which will let you build a blockchain and other stuff. See more info here: #1425, #1430, https://github.com/HelloZeroNet/Plugin-PeerMessage

**Comment by imachug** [comment]
Yes, it can.

**Comment by imachug** [comment]
@HelloZeroNet Closing?
