### ISSUE TITLE
NEEDS TO BE UPDATED: content.json - how?

### ISSUE THREAD

**Issue by dotnetspec** [HelloZeroNet/ZeroNet#1446]
### Step 1: Please describe your environment

* ZeroNet version: _____0.6.2 rev 3467
* Operating system: _____Win 7
* Web browser: _____Chrome
* Tor status: available
* Opened port: no
* Special configuration: ____No

### Step 2: Describe the problem:
Website info panel informs me (probably correctly) that the content. json needs to be updated - how do I do that?

#### Steps to reproduce:

  1. Create site (files copied from a previous site that was experiencing problems)
  2. Sign and publish
  3. Open website data panel (top right)
  4. Site control - update - get 'site updated' message

Also tried deleting content.json ->update site (a new json file is generated) - > no change (after stopped and re-started ZeroNet)

#### Observed Results:
No change. Info panel still states:
NEEDS TO BE UPDATED: 
content.json

#### Expected Results:
 content.json will be updated when site is updated and/or signed

**Comment by HelloZeroNet** [comment]
It means that your client could not make sure that you have the latest version. This usually happens when the site has no peers.

If you own the site then you should press the sign button and your site should be ready to visited by other users.

**Comment by dotnetspec** [comment]
Thanks (I own the site) but, as mentioned in step 2, I have signed the site (numerous times). 

I visited the site through my mobile with Orbot running. My mobile found 1 peer (my laptop) and displayed 'content.json download failed' which I suspect is related to the 'NEEDS TO BE UPDATED: content.json' message in the site web app controller interface.

I originally installed and ran ZeroNet, and the site, from a thumb drive. Since I was having these problems I tried installing it to my hard drive instead. However, I continue to have the same problem there.

This problem prevents me from using ZeroNet and recommending it to others (which I'm keen to do).

**Comment by krixano** [comment]
How about give us the link? Screenshots? Console output? Something so that we can understand what's going on. We need more information.

**Comment by dotnetspec** [comment]
Here's the link:
http://127.0.0.1:43110/1C1hKsqjQTR1iy1ijB3qtrqBwfH2Hf7TMW/

Screenshots:

![screen shot 06-05-18 at 09 59 am](https://user-images.githubusercontent.com/27340988/40950992-ba360452-68a7-11e8-9f83-326ce12cbc32.PNG)
![screen shot 06-05-18 at 10 00 am](https://user-images.githubusercontent.com/27340988/40950993-ba8038ce-68a7-11e8-9fda-ea88abdc9699.PNG)
![screen shot 06-05-18 at 10 01 am](https://user-images.githubusercontent.com/27340988/40950994-bab1f2a6-68a7-11e8-92ce-18b1da408782.PNG)

Console output is either 'file updating' or 'no peers' under Squash Passion Apps.

Hope this helps ...

**Comment by dotnetspec** [comment]
Here's a mobile screenshot:
![screenshot_2018-06-05-10-06-29-896_com android chrome](https://user-images.githubusercontent.com/27340988/40951149-5cc5930e-68a8-11e8-9042-c7bf5871c1c1.png)

**Comment by dotnetspec** [comment]
Thanks. That did it ...

ZeroNet appeared to have trouble recognizing my laptop as a peer. My laptop is using the mobile as a hotspot. Perhaps sharing the network in this way, with Tor as well, created a problem? It appears that as soon as a more 'standard' situation was applied (your device becoming a peer) it resolved itself quite effectively.

Thanks again to everyone helping on this ...

**Comment by krixano** [comment]
No problem! Glad it worked for you!
