### ISSUE TITLE
Background tasks/services?

### ISSUE THREAD

**Issue by trenta3** [HelloZeroNet/ZeroNet#1447]
Is there any way to execute background tasks or services (with user permission) that persists even after the user closes the page (i.e. they are executed by the ZeroNet daemon)?

It would be awesome to have it (the ability to execute and talk with a piece of Javascript code that is runned by the daemon) as it would have many useful applications including:
* A torrent client using [WebTorrent](https://webtorrent.io/)
* The possibility to have custom (per site) DHT to distribute part of site contents that only needs random access (e.g. images in ZeroTalk discussion threads or more generally optional files)
* Other kind of work during which the user does not need to have the page of the site open

If there is no such way, is it a thing that would be useful in your opinion?
If the opinions are positive, I might implement it (I think as a Plugin is more appropriate).
Please let me know if it is a good thing or not.

Note that I'm aware of HTML Web Services but they do "expire" after the user closes the page or navigates away.

**Comment by Thunder33345** [comment]
Gitcenter did have a plan for it, while it generally focus around his P2P plugin i dont really know if he will make it to accommodate a more general uses

**Comment by krixano** [comment]
> Gitcenter did have a plan for it

Gitcenter has actually already started work on it [here](https://github.com/HelloZeroNet/Plugin-BackgroundProcessing).

**Comment by trenta3** [comment]
It seems that the plugin is almost finished, and also the on-it-dependent PeerMessage.
When will they be merged and enabled into ZeroNet release?
@imachug @HelloZeroNet @DaniellMesquita

**Comment by imachug** [comment]
The plugin is practically finished, but not tested for security - though I've made it as much secure as I think it's possible, I'd like someone else to check it. The required steps to use the plugin are mentioned in my PR.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/pull/1451.
