### ISSUE TITLE
VM装的XP SP3，好像不能用，各位有在xp系统下使用的吗？

### ISSUE THREAD

**Issue by pentestion** [HelloZeroNet/ZeroNet#1455]
{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/x-ms-application, application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml, */*", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate", 
    "HTTP_ACCEPT_LANGUAGE": "zh-cn", 
    "HTTP_CONNECTION": "Keep-Alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_USER_AGENT": "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "1382", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "autodownload_bigfile_size_limit": 1, 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "broadcast_port": 1544, 
        "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
        "config_file": "zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "download_optional": "manual", 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 0, 
        "fileserver_port_range": "10000-40000", 
        "fix_float_decimals": false, 
        "force_encryption": false, 
        "global_connected_limit": 512, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "zh", 
        "log_dir": "log", 
        "log_level": "DEBUG", 
        "max_files_opened": 2048, 
        "msgpack_purepython": false, 
        "open_browser": "default_browser", 
        "optional_limit": "10%", 
        "pin_bigfile": 20, 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_hs_port": 15441, 
        "tor_proxy": "127.0.0.1:9050", 
        "tor_use_bridges": false, 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://zero.booth.moe#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:443", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://104.238.198.186:8000", 
            "http://tracker.skyts.cn:6969/announce", 
            "http://open.acgnxtracker.com:80/announce", 
            "http://retracker.mgts.by:80/announce"
        ], 
        "trackers_file": false, 
        "trackers_proxy": "disable", 
        "ui_host": null, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "ui_trans_proxy": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceLocal", 
        "AnnounceZero", 
        "Bigfile", 
        "Chart", 
        "Cors", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.0.1", 
    "version_python": "2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.6.2 r3477", 
    "wsgi.url_scheme": "http"
}

**Comment by luoxufeiyan** [comment]
Have you tried another OS on the in the same network environment?
同网络下其他系统可以使用吗？

**Comment by tangdou1** [comment]
xp系统太老，一般在win7下使用。

**Comment by tangdou1** [comment]
It can be closed.

**Comment by blurHY** [comment]
@HelloZeroNet There are too many open issues,and most of them can be closed
