### ISSUE TITLE
Can't even register zeroid in China

### ISSUE THREAD

**Issue by dddog999** [HelloZeroNet/ZeroNet#1458]
### Step 1: Please describe your environment

  * ZeroNet version: 3477
  * Operating system: win 10
  * Web browser: vivaldi
  * Tor status: always
  * Opened port: no
  * Special configuration:

### Step 2: Describe the problem:
i delete my old users.json to register a new zeroid , 
the trackers on zerohello shows :0/5 ok,
in zeroid page :
连接中...
TRACKERS ANNOUNCING: 0, ERROR: 0, DONE: 0
找不到节点
CONTENT.JSON 下载失败

even with my old id,some new popular zite like git center that i had never connected before,I can get on too.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by dddog999** [comment]
for unknow reason i got 1 tracker works now,and registered a zeroid,but still no able to connect Git center

**Comment by blurHY** [comment]
zeronet.qc.to must be blocked.
