### ISSUE TITLE
AttributeError on sitePublish

### ISSUE THREAD

**Issue by yurkobb** [HelloZeroNet/ZeroNet#1459]
### Step 1: Please describe your environment

  * ZeroNet version: ZeroNet 0.6.2 r3477 (git commit 7bff5f562c42a4a5f73e104c0f767c1413064aa6)
  * Operating system: Fedora 28
  * Web browser: command line command
  * Tor status: always
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:
Running `./zeronet.py sitePublish ADDRESS` throws AttributeError exception multiple times (see below).

#### Steps to reproduce:

  1. run sitePublish ADDRESS

#### Observed Results:
    - Starting ZeroNet...
    - OpenSSL loaded, version: 0100020FF
    - Patching sockets to tor socks proxy: 127.0.0.1:9050
    - Version: 0.6.2 r3477, Python 2.7.15 (default, May 16 2018, 17:50:09) 
    [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)], Gevent: 1.2.2
    - Loading site...
    - Can't connect to local websocket client: 0x01: General SOCKS server failure
    - Creating FileServer....
    TorManager Connecting to Tor Controller 127.0.0.1:9051
    ConnServer Checking port 15441 using portchecker.co...
    - Unhandled exception
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 536, in run
        result = self._run(*self.args, **self.kwargs)
      File "/home/zeronet/ZeroNet/src/File/FileServer.py", line 255, in checkSite
        site.announce(mode="startup")  # Announce site to tracker
      File "/home/zeronet/ZeroNet/src/Site/Site.py", line 777, in announce
        self.announcer.announce(*args, **kwargs)
      File "plugins/AnnounceLocal/AnnounceLocalPlugin.py", line 13, in announce
        local_announcer = self.site.connection_server.local_announcer
    AttributeError: 'ConnectionServer' object has no attribute 'local_announcer'

[...]

#### Expected Results:

No exceptions taking place.

**Comment by anoadragon453** [comment]
Worth noting that I'm also getting the same issue. https://gist.github.com/anoadragon453/6ebe4414cb5a274b6918923e303564a0

**Comment by HelloZeroNet** [comment]
I have added a fix for this: https://github.com/HelloZeroNet/ZeroNet/commit/8b91abd0dc3b78bb73983cee8c26697e0abe2459

**Comment by yurkobb** [comment]
I confirm the fix is valid in my environment.
