### ISSUE TITLE
Please list what browsers actually are supported.

### ISSUE THREAD

**Issue by lewisje** [HelloZeroNet/ZeroNet#1461]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2 (rev3465)
  * Operating system: Windows 10 x64 Build 17134.112
  * Web browser: Chrome 67.0.3396.87
  * Tor status: available
  * Opened port: yes
  * Special configuration: (none)

### Step 2: Describe the problem:

I was walking through accessing ZeroNet sites with someone else who was using Mac OS X 10.7 and getting messages saying that the browser was outdated; I found [this commit](https://github.com/HelloZeroNet/ZeroNet/commit/81f196647b10e9086c159e3458f50f0437423355#diff-faa3945ca6d392977a2c7d4e1acb865f) while searching for the criteria used by ZeroNet to determine whether a browser is unsupported, and it seems to check only for the lack of WebSocket support.

It doesn't seem as if that's [the issue](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Browser_compatibility) for this particular user, because even though the last supported versions of every browser on OS X 10.7 are quite old now, they do seem to support WebSockets; still, it would be nice to at least mention in the user-facing documentation that WebSockets are required, and even what versions support WebSockets.

I couldn't ascertain the user's environment completely, and I do not have an old Intel-based Mac to test this on for myself; I thought that opening an Issue for this was preferable to commenting on the commit directly.

#### Steps to reproduce:

  1. Use a browser that does not support, or has blocked, WebSockets.
  2. Visit a ZeroSite.

#### Observed Results:

  * The user sees a message saying that the browser is outdated.

#### Expected Results:

  * The ZeroSite loads.

**Comment by HelloZeroNet** [comment]
I have added a more detailed message and a link to a page that has list of WebSocket supporting browsers: https://github.com/HelloZeroNet/ZeroNet/commit/ff85241962b511e4dd7f18c3ca3ae3f2cbe5005c

I try to support all modern browsers (FF, Chrome, Edge, Safari), I can't guarantee that it will work with any browser that support WebSockets.
