### ISSUE TITLE
How to set a proxy for zeronet?  It can't connect to any tracker.

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1475]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: win10
  * Web browser: chrome
  * Tor status: available
  * Opened port: yes
  * Special configuration: no

**Comment by tangdou1** [comment]
Only if you have a public ip not private ip. Most of public ip can only be obtained by buying from the internet service providers, like Alibaba.
