### ISSUE TITLE
changing language to "SK" on zeroHello results in an empty refreshed page and endless "connecting to"

### ISSUE THREAD

**Issue by star-buck** [HelloZeroNet/ZeroNet#1476]
0.6.3 r3500

Can someone confirm or is it just here?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed! (there was an extra `,` character at the end of sk.json translate file)

**Comment by star-buck** [comment]
:+1: 
on the same note it looks like selecting 'DE' does not seem to change anything?

**Comment by HelloZeroNet** [comment]
Yeah the de translation is still missing
