### ISSUE TITLE
.piecemap.msgpack files remains after deleting main file via ZeroHello/Files

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1485]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.3 rev3524
  * Operating system: W10
  * Web browser: FFbeta
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser_local

### Step 2: Describe the problem:

Hello, i tried to delete the big video files (example: incomplete large video files downloaded from [KopyKate](http://127.0.0.1:43110/big.kopykate.bit/) site because they eat [alot of disk space even it contains almost no real data](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1530097903_1NZftAz9VSawGF5JgMYGFv4ByoKEaQbNZu#comment_168_1NZftAz9VSawGF5JgMYGFv4ByoKEaQbNZu)) I delete them using ZeroHello/Files tab, then i see the file was deleted from the directory on my PC, though [.piecemap.msgpack files](http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1518257041_1EjCZapTECBem63aaBazBrwa9eh9AwmXuq) remains in same directories.
Is this intended? If these piecemap files are responsibility of the site programmer, maybe it can be more easy if it is built in zeronet? Thank You

**Comment by scsmash3r** [comment]
Having the same issue, so bumping up this topic with the question: what are the `*.piecemap.msgpack` files and why don't they delete with the parent (big) file?

**Comment by HelloZeroNet** [comment]
> what are the *.piecemap.msgpack files

They similar to .torrent files: contains the correct hash of the individual parts/pieces of a big file. Yeah, probably the correct behavior would be deleting if someone deletes a bit file using ZeroHello Big file section.

**Comment by HelloZeroNet** [comment]
This feature is added by https://github.com/HelloZeroNet/ZeroHello/commit/324e7a0973f3eaff3ba51ee1fd358cf17facc9ed

After this modification the piecemap file will be also deleted if the file selected and deleted at Bigfile section on ZeroHello
