### ISSUE TITLE
Blocklist feature - no auto-updating of the local user/site blocklist

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1489]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.3 rev3540
  * Operating system: W10
  * Web browser: FF

### Step 2: Describe the issue:

Hello, i think the Zeronet has ContentFilter plugin which can be used by the [blocklist](http://127.0.0.1:43110/blocklist.bit) sites. Thank you for the blocklist feature!

When i "subscribe" to some sites blocklist, and admin add new sites, it will be automaticaly propagated into my local blocklist i think. (1) **In case of users blocklist, the user have to re-visit the blocklist and switch off/on the blocking in order to update it with newly added users**. Should this be made to auto update?

(2) **In case admin remove some site from blocklist, it may not update local blocklists of the people who subscribbed it**, according to the [comment](http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1oranGeS2xsKZ4jVsu9SVttzgkYXu4k9v/16NS3rBdW9zpLmLSQoD8nLTtNVsRFtVBhd/1532060914) of one zeronet user: "my removal of these entries from Nopelist doesn't mean removal from local blocklists. You would have to clear out entries added from Nopelist and toggle blocking back on again."

**Comment by HelloZeroNet** [comment]
>  In case of users blocklist, the user have to re-visit the blocklist and switch off/on the blocking in order to update it with newly added users.

It should update the list automatically for the subscribed users, no need to re-visit the site. The file reload is triggered when the user receives the updated file or if you sign the new file. (so editing the files locally will not update your client automatically)
