### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by kseistrup** [HelloZeroNet/ZeroNet#149]
Please support Python3.

**Comment by ncripshun** [comment]
I'd likely say that someone will eventually port it.

The developer probably wanted to reach as many people as possible as easy as possible. Most OS's such as Mac and popular Linux builds all have Python 2.7 by default.

**Comment by kseistrup** [comment]
(For certain values of “popular”, yes. ArchLinux has Python3 as its default.)

I agree, I just wanted to make sure there was a formal issue concerning this.

**Comment by HelloZeroNet** [comment]
Yes the main reason was the fact that most linux distribution comes with Python 2 and it has more mature libraries. (and the speed is also somewhat better)

Some months ago the gevent event library ported to Python 3, so I think it shouldn't be hard to make the project compatible both with Python 2 and 3.

**Comment by DoWhileGeek** [comment]
I've started work on this, hopefully we can get a couple PRs going until we have full agnostic support.

**Comment by kseistrup** [comment]
@DoWhileGeek cool! :+1:

**Comment by leycec** [comment]
Python 2 is now [less than three years from the chopping block](https://pythonclock.org). :hocho: 

ZeroNet's transition to Python 3 needs to be feature complete *before* 2020, Python 2.7's proposed end-of-life (EOL) date. While feasible and indeed necessary, this transition is likely to prove non-trivial – which is to say, "It's gonna hurt." There's really no getting around that. [`six`](https://pypi.python.org/pypi/six) helps, but it's no panacea. The syntactic and semantic differences between Python 2 and 3 are sufficiently profound (particularly with respect to string handling) that the two could be said to be different languages entirely – albeit closely related languages.

Ssomeone just needs to bite the thankless bullet and start doing it. The sooner this painful migration begins, the sooner this painful migration ends. Or, to paraphrase an [ancient Chinese and/or African proverb](https://s-media-cache-ak0.pinimg.com/originals/ad/12/56/ad125658e28ffd37f5e72502ca41ce87.jpg):

> The best time to migrate to Python 3 was two years ago. The second best time is today.

**Comment by yurivict** [comment]
I wonder how do other python projects cope with this problem. How do they manage to run on both 2.X and 3.X systems? Do they all have to use some compatibility interfaces with two implementations behind them?

**Comment by skwerlman** [comment]
there are compatibility mechanisms in python to help handle the transition, like the `six` library, and `from __future__ import foo`

**Comment by noxarivis** [comment]
TickTock
https://pythonclock.org

**Comment by grez911** [comment]
@HelloZeroNet Please, add some labels on this issue, it's important issue.

**Comment by noxarivis** [comment]
So... Whats the plan now?....
Do we wait?

Also @HelloZeroNet 

why is it labled "hard" if you said:
"Some months ago the gevent event library ported to Python 3, so I think it shouldn't be hard to make the project compatible both with Python 2 and 3."

???

**Comment by HelloZeroNet** [comment]
I have not started working on it yet, so no ETA

**Comment by noxarivis** [comment]
the python foundation  will drop py2 so ... 

if the porting is not done until the counter droped to "Zero" there is "Zero" reason to invest any longer into this project.


i dont care if u never worked with py3.

py2 is in legacy mode, it is only supported to give people time to port apps to py3. so use that time already, else this project will be gone because it wont work on recent systems! there is no option to not port it to py3, it HAS to be ported. So when does it happen?

Some systems use py3 already as default.

**Comment by krixano** [comment]
@noxarivis  Pestering him isn't gonna make the transfer go any faster. Also, you can't expect someone to know the future like that. Problems arise, etc. which is *precisely* the reason why pretty much no company gives ETA on things like this.

**Comment by HelloZeroNet** [comment]
Python 2 still supported until 2020 so it's not a priority yet.

**Comment by filips123** [comment]
@HelloZeroNet Any update?

Some Linux distributions (Ubuntu 18.04) removed Python 2. Users will now have to install Python 2 manually to use ZeroNet.
Also, it is only few more than one year left to transfer project, because Python 2 will not be supported in 2020 anymore.

**Comment by HelloZeroNet** [comment]
I will check the possibility later this year.

**Comment by krixano** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/1773

**Comment by ergoithz** [comment]
Python2 in 2019 (even on 2015 it kinda was) not acceptable. Most mayor distro core packages have been already migrated as Python 2 end of life support is very near. This doesn't make this project very trustworthy on the technical side.

**Comment by HelloZeroNet** [comment]
You can try the python3 version here: https://github.com/HelloZeroNet/ZeroNet/tree/py3

**Comment by krixano** [comment]
He would have known that had he even **looked** at the issue I linked to.

**Comment by imachug** [comment]
Can we close this issue as we have #1773 already?
