### ISSUE TITLE
zeronet dont close

### ISSUE THREAD

**Issue by alex37330** [HelloZeroNet/ZeroNet#1490]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: windows 7 pro
  * Web browser: chrome last version
  * Tor status: always
  * Opened port: yes
  * Special configuration:none

#### Steps to reproduce:

  1.just launch zeronet
  2.wait for launching and openport and connection with tor

#### Observed Results:

after that i can shut down zeronet but it will always in  ram and i use tor too for my torretn client and him to i can shut it down but it stay in my ram
![image](https://user-images.githubusercontent.com/30521714/43039948-5f343bf4-8d38-11e8-87b9-100709d56a98.png)

**Comment by HelloZeroNet** [comment]
Have you closed the client using the web interface or by using the taskbar icon?

**Comment by alex37330** [comment]
Problem solved it was PC who can Purge the memory barret
