### ISSUE TITLE
 I can not add a web game, made by RPGMAKERMV, to ZeroNet. Because it need support "$" and "!" in the file name for special use.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1491]

**Comment by didlie** [comment]
Try using an reversible encryption scheme, like zlib. Thats what I use to add full symbol support for my website.

**Comment by tangdou1** [comment]
Just ignore it. Godot engine is good.

**Comment by didlie** [comment]
btob -> atob functions in Javascript seem to work great
