### ISSUE TITLE
How is this different from IPFS?

### ISSUE THREAD

**Issue by Porco-Rosso** [HelloZeroNet/ZeroNet#150]
Hi, As i understand this project is a combination of bittorent decentralised technology and bitcoin-like crypto to serve web pages.
How is this different from https://github.com/ipfs/ipfs/ where both of these technologies are already implemented?
Apart from TOR compatibility, every feature of ZeroNet is already implemented in IPFS. Am I wrong? could you share some light on this?

**Comment by HelloZeroNet** [comment]
IPFS does not support dynamic content as far as I know and the content distribution works differently. There is lots of similar project out there ZeroNet created to focus on simplicity, easy of usage and user experience.

**Comment by JayBrown** [comment]
From what the IPFS developers said, IPFS does support dynamic content. As for TOR or VPN etc., IPFS works flawlessly on top of that, as ZeroNet does.

**Comment by weakish** [comment]
> From what the IPFS developers said, IPFS does support dynamic content.

You can distribute `dynamic content` via IPFS.
ZeroNet is full stack dynamic, but IPFS only provides the backend of dynamic site.
For now, static sites with a lot of files, use IPFS.
Dynamic sites like forum or ZeroMe, use ZeroNet.
Small static site, use either.

**Comment by alugarius** [comment]
i use ipfs for everything, zeronet is cool but it is slow on boot

**Comment by HelloZeroNet** [comment]
The startup speed zeronet has been fixed, please check the blog for instructions
