### ISSUE TITLE
Share trackers between peers [In progress]

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1507]
# Why?

To make the network more decentralized and avoid easy blocking of trackers.

# What?

Allow the users to automatically share tracker list with each other.

# How?

At the startup and once every hour the client asks 5 peers for new trackers.

New peer request method:
- announceList: Returns user's all trackers that has been received from other peers and it was sucessfully announced in the past hour.

The trackers are saved in data/trackers.json:

```json
{"shared": {
	"zero://any.address:port": {
		"time_added": 123891237832,
		"time_found": 39827138921,
		"time_success": 1231231232,
		"latency": 0.34
	}
}}
```

If the user has the Bootstrapper plugin enabled and opened port, then it's automatically adds the client's public ip to the shared trackers list. 

## Plan

 - [x] Save/store/load shared trackers in trackers.json
 - [x] announceList peer request method
 - [x] Update stats of shared trackers
 - [x] Filter out dead trackers from responses
 - [x] Update tracker list at the beginning and every hour
 - [x] Remove dead trackers after 30 failed request
 - [x] Automatically add my ip Bootstrapper plugin is enabled and we have opened port
 - [x] Testing

**Comment by DaniellMesquita** [comment]
User need to configure to get trackers in 1 hours, 30 minutes, or less.

**Comment by HelloZeroNet** [comment]
Landed in rev3565, the tracker discovery is reduced to 5 min currently. (Maybe we can increase later)

**Comment by April93** [comment]
@HelloZeroNet perhaps have it able to be customized in the /Config? I've taken the opportunity to remove all of my non-ZN trackers. Would love to be able to bump the count up a bit to make things a bit more reliable.
