### ISSUE TITLE
Make ZeroNet work with JS disabled

### ISSUE THREAD

**Issue by asdedhj** [HelloZeroNet/ZeroNet#1512]
Suggestion: Allow ZeroNet to work with JavaScript disabled. This can help prevent certain possible privacy/security issues in JS.[1](https://www.makeuseof.com/tag/3-ways-javascript-can-used-breach-privacy-security/),[2](https://www.torproject.org/docs/faq.html.en#TBBJavaScriptEnabled)

JS is awesome but users should be able to control when it is used.

**Comment by satoshisfriendz** [comment]
I agree. Noscript is a default goto firefox addon for a reason.

**Comment by HelloZeroNet** [comment]
If you add the /raw/ prefix, then you can browse sites that does not requires js, eg:
http://127.0.0.1:43110/raw/1AsRLpuRxr3pb9p3TKoMXPSWHzh6i7fMGi/en.tar.gz/index.html
