### ISSUE TITLE
[Question] ZeroFrame: how to prompt to user clone the zite?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1519]

**Comment by DaniellMesquita** [comment]
@krixano

**Comment by DaniellMesquita** [comment]
This info should be useful in Dev Center zite.
I have the FrameworkJS zite, and a button to create a new project (zite) based on FrameworkJS (clonning).

**Comment by satoshisfriendz** [comment]
Sounds decent friends! Give it a whirl!

**Comment by DaniellMesquita** [comment]
@HelloZeroNet

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by DaniellMesquita** [comment]
AnthyG

**Comment by DaniellMesquita** [comment]
I researched about it, inspecting Git Center's source.
It uses ZeroPage library.

When click in a button with `id` `"create_repository"`:

> 	.then(() => {
> 		let button = document.getElementById("create_repository");
> 		button.classList.remove("button-disabled");
> 		button.onclick = () => {
> 			Repository.createRepo(zeroPage);
> 		};
> 	});

It calls `Repository.createRepo`, powered by ZeroPage:

> Repository.createRepo = zeroPage => {
> 	return zeroPage.cmd("siteClone", ["1RepoXU8bQE9m7ssNwL4nnxBnZVejHCc6"]);
> };

![image](https://user-images.githubusercontent.com/6765277/44501953-b138d680-a665-11e8-9450-9d333a169346.png)

**Comment by DaniellMesquita** [comment]
Update: FrameworkJS supports ZeroNet clonning.
http://127.0.0.1:43110/1Fmwk685eaX7GjoQ7JKo3QvywizGfnYRCB/
