### ISSUE TITLE
单线程cpu占满, 其他线程cpu几乎为0

### ISSUE THREAD

**Issue by xxxsen** [HelloZeroNet/ZeroNet#1524]
### Step 1: Please describe your environment

  * ZeroNet version: __0.6.2(rev3417)___
  * Operating system: __ubuntu16.04___
  * Web browser: __chrome___
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: ____

#### Steps to reproduce:

  1. __打开zeroup___
  2. __勾选"下载并帮助分发所有文件"___
  3. __之后刷新zeroup页面___

#### Observed Results:

刷新zeropup页面后会卡住很久才加载出页面, 期间单个线程CPU占满。
```htop info
 1127 xxxx        20   0 2080M 1051M  6628 R 100.  6.6 12h13:28 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80
 3113 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.80 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 7256 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:10.18 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 3115 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.59 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 1665 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.95 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 1121 xxxx        20   0 19584  2116  2116 S  0.0  0.0  0:00.00 /bin/bash ../Python/python zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80
 3114 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.49 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 3116 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.43 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 3117 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.43 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 3155 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:19.88 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 7257 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:10.21 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
 7258 xxxx        20   0 2080M 1051M  6628 S  0.0  6.6  0:10.17 ../Python/python2.7 zeronet.py --ui_ip * --ui_host zeronet.xxxx.com:80 
```

#### Expected Results:
能够正常的打开页面。

**Comment by tommykakashi** [comment]
Simply help him with translation:
**Steps to reproduce:**

1. Open zeroup
2. Check "Download and help distribute all files"
3. Then refresh the zeroup page

**Observed Results:**
It took long to load the page of zeroup after refreshing. During the period, there is only one thread of CPU bumping up. Others are almost 0.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
This is expected due Python's GIL: https://en.wikipedia.org/wiki/Global_interpreter_lock

The only way to utilize multi-core with ZeroNet right now is to start multiple cilent on the same machine with different sites (and different --ui_port and --file_server port)
