### ISSUE TITLE
[Question] How convert user master seed to bitcoin address?

### ISSUE THREAD

**Issue by danimesq** [HelloZeroNet/ZeroNet#1525]

**Comment by DaniellMesquita** [comment]
You can add questions like this to the FAQs.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme
Yes, it is what I'm talking about.
How to discover the private key of a master seed?

**Comment by HelloZeroNet** [comment]
There is no such thing as "private key of the master seed", you can generate private keys from master seed, but you won't be able to get back to the master seed from those private keys

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme
I have the master seed of the @peeper user, and I know it is a Bitcoin address associated to this user, and signs with privatekey.
This is what I'm trying to discover.
