### ISSUE TITLE
[Question] Zites can upload files to clearnet sites?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1526]

**Comment by leftside2** [comment]
Clearnet server can be monitoring its own zeronet server and the zeronet server is continuously updating, let's say, ZeroUp, and once there's a new upload on zeronet, the clearnet server may copy it to its web folder internally and add a link to the file on its web page.

**Comment by DaniellMesquita** [comment]
Thanks.
So zite owner can't yet send files to clearnet without this trick (like send a file using an API using pure JS)?

**Comment by leftside2** [comment]
@DaniellMesquita , At least one of the zeronet users' PC should behave like web bot to upload zeronet data to clearnet sites. (P.S. The above mentioned clearnet server which is monitoring zeronet can have a web bot to upload the zeronet files to any clearnet sites it wants.)
