### ISSUE TITLE
Imageboardmorphing

### ISSUE THREAD

**Issue by dobrosketchkun** [HelloZeroNet/ZeroNet#153]
Is it possible to add some feauters to make zeroblog engine looks like imageboard (with some deal with config maybe, to hold other main functionality):
- Comments with formating and images (or even blog-post functionality)
- Hide nicknames (optional)

**Comment by border0464111** [comment]
It's quite possible. It's can be done by editing your site code. you can take inspiration in the reactGif or 0chan sites.

**Comment by grez911** [comment]
Please, consider to open this issue in the relevant repository: https://github.com/HelloZeroNet/ZeroBlog
@HelloZeroNet Please, close.
