### ISSUE TITLE
[Question] Cryptography - Reverse Bitcoin keys

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1537]
I know this can sound off-topic, but it is related to #1536 issue.

When reverse a Bitcoin privatekey, the result addrees is also reverted?
For sample:
Privatekey `5ZN...` generates the `1SAMPLE...` address.
Privatekey `5ZN...` reverted is `...NZ5`, so the result BTC address is `...ELPMAS1` (reverse of `1SAMPLE`)?

**Comment by mkg20001** [comment]
The key is a base58 encoded hash of the public key.
Therefore if you reverse the public key, you get an entierly different address, even though that doesn't make sense at all from a mathematicall prespective.
Keys are made of specifically calculated numbers that satisfy certain criteria (ex: for RSA all numbers muste be primes) and reversing them doesn't "magically" generate valid ones.
```shell
# example with helloworld hashed with SHA-1
$ echo helloworld | sha1sum
e7509a8c032f3bc2a8df1df476f8ef03436185fa  -
$ echo dlrowolleh | sha1sum
a8c7fff2d25e48728c572fe9e8c8c67575a0fd39  -
```

**Comment by DaniellMesquita** [comment]
Thanks, well explained.
