### ISSUE TITLE
 __init__() takes exactly 4 arguments (2 given)  TrayiconPlugin.py", line 67

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1539]
### Step 1: Please describe your environment

  * ZeroNet version:ZeroNet 0.6.3 r3550
  * Operating system: W10 64
  * Web browser: Chrome
  * Tor status: available
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:

```
Traceback (most recent call last):
  File "zeronet.py", line 19, in main
    main.start()
  File "F:\Zeronet2\core\src\main.py", line 543, in start
    actions.call(config.action, action_kwargs)
  File "F:\Zeronet2\core\src\main.py", line 158, in call
    back = func(**kwargs)
  File "plugins\Trayicon\TrayiconPlugin.py", line 67, in main
    lambda res: gevent.spawn_later(0.1, self.quitServers)
TypeError: __init__() takes exactly 4 arguments (2 given)
```

Because of that,there isn't zeronet icon in tray.
If i disable the trayicon plugin,zeronet will works.

BTW,there is some encoding errror in tor error info `TorManager Tor controller connect error: error: [Errno 10061] [Error 10061] 目芫薹印 `

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed in latest version: https://github.com/HelloZeroNet/ZeroNet/commit/53a8c2d574d8221cd9a93bf14e0a67dbe167b21f#diff-96bfdc2cfcb5739e88aad648cba5e983
