### ISSUE TITLE
How do you sync file changes?

### ISSUE THREAD

**Issue by randoms** [HelloZeroNet/ZeroNet#154]
I am trying to find out how you sync file changes. It seems that changes are pushed directly from changer to other peers. However if we get 1K peers hosting the site(which is really common for a normal site), 1K requests will be pushed from the changer, and all the other peers will download new content directly from the changer. This will lose the power of decentralize.
If a peer is not online when change request was pushed. How could it get the lasted content of the site. Will it download content.json each time it starts up?
How do you sync up database? If a new record was inserted into database, will you update the whole database to other peers?
I really love the idea of decentralize web, and I am making something like this. It will be great help if you can share some of you ideas.

**Comment by HelloZeroNet** [comment]
The client only send the changes to [some other peers](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Site/Site.py#L314), then if someone receive a valid new modification he will inform about it 3 other random peers.

In this way you only have to send your modification to 1-2 peer then (probably) it will spread between everyone.

**Comment by randoms** [comment]
Thanks for your response. But this will cause a potential lose of data. For example in a messaging board program like ZeroBorard. If user A made a comment, and user B made a comment before A's comment sync to all the other peers. Then A's comment will be overwritten. Because we have two version of data record, and B's version is newer. You said you take the latest changes in the document.
Do you have any work around for this?

**Comment by HelloZeroNet** [comment]
ZeroBoard is an outdated site (it was the first site of zeronet). ZeroTalk solved this problem: 
Every user has his/her own file to distribute comments/topics/upvotes/etc. and they are signed and timestamped by the owner on modification. So no problem happens if someone did an another modification at the same time because its writes in an another file.

**Comment by randoms** [comment]
But all these files will be added to something like content.json. He still has the chance to miss some content. 
If we want the content to be the same, we must have the same page file. And if we want to edit it without conflict then a lock is needed. I digged into [ceph](https://github.com/ceph/ceph) yesterday. And I think their method is really good to follow. They used an ordered list of all peers, editions are only allowed on the first peer called primary node, this is something like a lock. In zeronet's case, if you want to make a comment, check if you have the same content with the primary node. If not then sync your files with it. Push your changes to the primary node, and primary node will sync your changes to other peers.

**Comment by HelloZeroNet** [comment]
Everone has his/her own content.json file that is timestamped separately, so no lock needed.
