### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1540]
Internal error: AttributeError: 'NoneType' object has no attribute 'strip'
UiWebsocket.py line 81 > UiWebsocket.py line 267 > UiWebsocket.py line 1041 > TorManager.py line 284 > TorManager.py line 303

**Comment by HelloZeroNet** [comment]
Thanks for reporting it should be fixed in latest version: https://github.com/HelloZeroNet/ZeroNet/commit/8738817eab7f2b6e4ed1515292070a79b618b90f#diff-d8841277993f336590a11cd5623974c9
