### ISSUE TITLE
Enhancement: Add description when adding permission

### ISSUE THREAD

**Issue by trenta3** [HelloZeroNet/ZeroNet#1545]
A lot of permissions (I don't know the exact list of which are available) don't have any description.
For example the permission `Merger:___` says nothing about it, and as a user the first time I saw it in GitCenter I did not know what I was granting...

**Comment by DaniellMesquita** [comment]
Permissions should also show the risks.

**Comment by DaniellMesquita** [comment]
Reference: #1547

**Comment by HelloZeroNet** [comment]
For me it displays:
```
This site requests permission: Merger:Hello
Read and write permissions to sites with merged type of Hello (0 sites)
```

**Comment by trenta3** [comment]
Sorry I think I didn't remembered it well. Tried on a new installation of ZeroNet and it works also for me.
I just didn't find the description in 
https://github.com/HelloZeroNet/ZeroNet/blob/030ad0a8de20443eabbb454ffba3b02d620af93f/src/Ui/UiWebsocket.py#L827-L833

**Comment by DaniellMesquita** [comment]
@HelloZeroNet

Can a site have write permission to other sites that aren't merged?

**Comment by HelloZeroNet** [comment]
Yes, using Cors:1anysiteaddress
