### ISSUE TITLE
Internal error: RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1551]
I downloaded some zites, then received this message.

> Internal error: RuntimeError: dictionary changed size during iteration
> UiWebsocket.py line 81 > UiWebsocket.py line 267 > NewsfeedPlugin.py line 40

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in latest Rev: https://github.com/HelloZeroNet/ZeroNet/commit/89c871f171a7b82f5c92b1c7e19ef83b0c94d8e6
