### ISSUE TITLE
Is there a way to obtain user public key given its address?

### ISSUE THREAD

**Issue by trenta3** [HelloZeroNet/ZeroNet#1554]
I know that the address of a site / user is an hash of its public key, and therefore the point on the elliptic curve cannot be recovered from it alone.

I want to know what function in ZeroNet allows me to get user public key.
I think there should be one such method because it is mandatory to have the public key in order to verify signatures as for ECDSA.

@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
it's not possible to recover public key from an address. (which is a hash of a public key)
but you can recover public key from a signiture.

so verification done by signiture -> public key -> address (but the opposite way is not possible)

**Comment by trenta3** [comment]
Thank you, I've also found the method `src/lib/pybitcointools/bitcoin/main.py#ecdsa_recover` which does exactly this.
