### ISSUE TITLE
UiWSGIHandler error

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1557]
zeronet 3576

ERROR    - UiWSGIHandler error: error: [Errno 10053]  in UiServer.py line 40 > pywsgi.py line 910 > pywsgi.py line 896 > pywsgi.py line 742 > pywsgi.py line 764 > pywsgi.py line 723 > pywsgi.py line 702 > _socket2.py line 419 > _socket2.py line 355 > _socket2.py line 323

**Comment by DaniellMesquita** [comment]
@tangdou1
