### ISSUE TITLE
Doesn't work on Linux Mint

### ISSUE THREAD

**Issue by Austin-Williams** [HelloZeroNet/ZeroNet#156]
I'm running Linux Mint 17 Qiana xfce 64-bit.

I followed the install instructions on the github page and get the following error:

``` 
user ~/ZeroNet-master $ python zeronet.py
- Starting ZeroNet...
[22:36:57] - Version: 0.3.2 r360, Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2], Gevent: 1.0
[22:36:57] - OpenSSL loaded, version: 01000106F
[22:36:57] - Creating UiServer....
[22:36:57] Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json
[22:36:57] - Removing old SSL certs...
[22:36:57] - Creating FileServer....
[22:36:57] ConnServer Error: Unsupported msgpack version: (0, 3, 0) (<0.4.0), please run `sudo pip install msgpack-python --upgrade`
```
I tried running: `sudo pip install msgpack-python --upgrade` as suggested. 

It installs msgpack-python successfully, but I get the same error when trying to start ZeroNet.

**Comment by Austin-Williams** [comment]
I resolve the issue. Mint had an old version of msgpack installed and it was 'owned' by the OS. So even `sudo pip .... -upgrade` wouldn't actually update msgpack.
I uninstalled the old msgpack via the Application Manager, then reinstalled msgpack via command line, and the error went away.

**Comment by koeur2pi** [comment]
Same issue with Linux Mint 17.2 (Cinnamon, x64).  But I can not manage to install the newer msgpack, some details would be welcome.  Nor the terminal nor the software manager (Menu > Administration > Software manager > search "python-msgpack") does allow me to install a version different from v0.3.0-1 :(

**Comment by HelloZeroNet** [comment]
You have to remove it using software manager then install using `sudo pip -U msgpack-python`

If this is fails:
 - Download msgpack from: https://github.com/msgpack/msgpack-python/archive/0.4.6.tar.gz
 - Unpack anywhere
 - Copy copy the `msgpack` directory to the same directory where your `zeronet.py` is
