### ISSUE TITLE
Error when rebuilding ZeroMe database

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1561]
Internal error: ProgrammingError: Cannot operate on a closed database.
UiWebsocket.py line 81 > UiWebsocket.py line 267 > SidebarPlugin.py line 737 > SiteStorage.py line 163 > DbCursor.py line 75

**Comment by HelloZeroNet** [comment]
Probably it was due the same reasons as #1563
