### ISSUE TITLE
Another error when rebuilding ZeroMe database

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1563]
Internal error: AttributeError: 'NoneType' object has no attribute 'set'
UiWebsocket.py line 81 > UiWebsocket.py line 267 > SidebarPlugin.py line 737 > SiteStorage.py line 170

**Comment by HelloZeroNet** [comment]
I'm suspecting it was due two concurrent rebuild going on the same site. I have added a fix for it in the latest Rev: https://github.com/HelloZeroNet/ZeroNet/commit/4fe33268ac10c816a134abfb2d0b04ca1c2f076c
