### ISSUE TITLE
zites with href="#heading" opens a empty new tab

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1565]

**Comment by HelloZeroNet** [comment]
I just tested using http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1536120595_1EAD2zXkzgJf6M7xQ4jG5FHCxUTez9NJJ4/0net+io+Peer+Exchange+PEX#comment_635_1NWh3WAty57FH8at1WtrZigMrdhrDkuPzh in FF/Chrome and it does not opens new tab for me
