### ISSUE TITLE
[Question] How to create sections (for includes topics) on ZeroTalk clone?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1566]

**Comment by tangdou1** [comment]
modify your data.json
Like:
first:
      {
            "topic_id": 1517727826,
            "title": "xxxxx",
            "body": "yyyyyyyy",
            "added": 1517727824
        },
then
     {
            "type": "group",
            "topic_id": 1517727826,
            "title": "xxxxx",
            "body": "yyyyyyyy",
            "added": 1517727824
        },

**Comment by DaniellMesquita** [comment]
@tangdou1
I did it on Notepad, but the title/body of all my posts had disappeared.

**Comment by tangdou1** [comment]
@DaniellMesquita  Yes, you should find its topic_id, first try its http address in the browser, you can find this topic, then add one or two posts under it, finnally you can find the topic group when coming back to your homepage.

**Comment by blurHY** [comment]
this issue should be closed

**Comment by DaniellMesquita** [comment]
@tangdou1
Thanks.

Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1576
