### ISSUE TITLE
The earth globe does not show in the side bar in rev.3591 when changing language to PL, RU, SK, TR or ZH.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1569]
The earth globe in the sidebar doesnot work now in rev.3576

firefox 61

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it was a tricky one, but fixed in Rev3594 https://github.com/HelloZeroNet/ZeroNet/commit/52081f4a2aab2747e3b37bfe2ed6b67f12488b2b
