### ISSUE TITLE
[Feature request] Allow sites to be able to specify if an update is valid or not

### ISSUE THREAD

**Issue by trenta3** [HelloZeroNet/ZeroNet#1570]
# What?
Allow sites to specify javascript code to check that a valid update has been received.

In `content.json` add field `update_verifier` which value should be a valid javascript file with a function `verify_update` which gets as parameter the path and the content of the modified file and can read other files using `fileGet`. The result is a boolean specifying wheter the update is valid or has to be rejected.

# Why?
This can be useful if, for example, we want to ensure that peers only send valid json files, or to restrict modifications to a database table only by some trusted entities...

At the same time, it is not the most desirable solution...

**Comment by HelloZeroNet** [comment]
ZeroNet client can't execute javascript code, so unfortunatelly it's not possible.

**Comment by imachug** [comment]
Wait a bit, what about BackgroundProcessing?!

**Comment by trenta3** [comment]
Well one could include a JS interpreter in Python, like [jispy](https://github.com/polydojo/jispy), [pyduktape](https://github.com/stefano/pyduktape) or [pyMiniRacer](https://github.com/sqreen/PyMiniRacer) (found with a fast google search).

I think the added value of this could be limitless.
We could extend such idea to execute scripts from sites in a sandboxed environment / interpreter at various actions to add many way to get the sites to be interactive.

For example, ZeroMail could execute a script that decodes new mail each time a new file arrives and if they are for the current user, it could notify him in some way.

By the way, I'm just using the issue to drop random ideas, hoping that someone (even myself) will then come along and implement code for them.

**Comment by trenta3** [comment]
@imachug I see only now your reply. I like the idea a lot. I think we should take some time to design an easily extensible system to have scripts executed when some actions occur.

I could only think of "new file received" event, but there should be a lot of others.

Just a question: if we resolve to adding that to BackgroundProcessing, will each site execute its own thread? Can it be set up as to have a single execution thread that dedicates a small amount of time to each site? (I'm obviously more in favour of the second solution)

**Comment by imachug** [comment]
> Just a question: if we resolve to adding that to BackgroundProcessing, will each site execute its own thread? Can it be set up as to have a single execution thread that dedicates a small amount of time to each site? (I'm obviously more in favour of the second solution)

ZeroNet uses gevent library, which simulates multithreading (real mutlithreading is slower because of GIL). So it in fact does what you've just said.

**Comment by HelloZeroNet** [comment]
I don't think running untrusted code by the zeronet client is a good idea. It would result in lots of different attack surface and it would also make alternative implementations harder. I think if we want to do pre-processing we have to do it in the browser.

**Comment by trenta3** [comment]
Concerning untrusted code, we could use an external project that has been
tested extensively.

I don't understand what do you mean by executing in the browser.
To open a page and let it do the processing stuff and then retrieve the
result in some way? I think this could make processing updates very slow
(given the usual time needed to load a page) and could in the next future
impair scaling.

**Comment by imachug** [comment]
In case we really need security, we could use Selenium and execute JS code in browser.

**Comment by krixano** [comment]
@HelloZeroNet 
You already have the possibility of running untrusted code by the client by allowing plugins and by allowing JavaScript (zites can easily contact clearnet servers, for example). As long as the *only* thing a python script used by BackgroundProcessing can do is call the ZeroFrame API and do things deemed safe (addition, store stuff in memory, etc.). Furthermore, the whole concept of permissions, in my mind, is supposed to prevent zites from doing whatever they wanted unless the user allows it, which is the same thing that happens with plugins (you allow the plugin by installing it). BackgroundProcessing uses a permission.
