### ISSUE TITLE
When about:blank, openning empty page

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1572]

**Comment by HelloZeroNet** [comment]
Please be more specific and fill the template that the repository offers you when you create the issue

**Comment by DaniellMesquita** [comment]
Visit:
http://127.0.0.1:43110/1Fmwk685eaX7GjoQ7JKo3QvywizGfnYRCB/
Then click on Forum.

**Comment by HelloZeroNet** [comment]
You have to use target="_blank" instead of target="blank"

**Comment by DaniellMesquita** [comment]
@HelloZeroNet 
> To fix it change target="blank" to target="_blank"

What is the difference?

**Comment by DaniellMesquita** [comment]
@krixano
Can you do a trick for this work, like in hashs on URLs?

**Comment by krixano** [comment]
Warning: this code isn't tested, and probably isn't 100% correct, but it should be *similar* to this.
```javascript
var elements = document.querySelectorAll("a[target^='blank']");
for (element in elements) {
    element.target = "_blank";
}
```

**Comment by HelloZeroNet** [comment]
> What is the difference?

target=blank means: open the link in a window named "blank"
target=_blank means: open the link in a new window

I have to correct myself: Probably it won't work even if you change it to "_blank". I'm not sure why, but opening links to new window does not works from sandboxed Iframe.

I recommend to put 
```
 <base href="" target="_top" id="base">
 <script>base.href = document.location.href.replace("/media", "").replace("index.html", "").replace(/[&?]wrapper=False/, "").replace(/[&?]wrapper_nonce=[A-Za-z0-9]+/, "")</script>
```
To all ZeroNet site's html `<head>` tag. It will fix the # hashtag links and opens the normal links to the out frame by default.
