### ISSUE TITLE
Can't post on clonned ZeroTalk forum

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1573]
http://127.0.0.1:43110/1DS3W1EqALVYyyWoKxFPezffx2V6e8gzTU/

Stuck on loading. Not even the user folder is created.

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev3594 https://github.com/HelloZeroNet/ZeroNet/commit/57f3cee390d6b4000b2801a4d400077127857788
