### ISSUE TITLE
[Feature] Dark mode theme to save our eyes

### ISSUE THREAD

**Issue by vRobM** [HelloZeroNet/ZeroNet#1574]
Please add a Dark background with Light text option for all UI elements.

**Comment by anoadragon453** [comment]
Really this should be up to each site, but you could add a dark theme for ZeroHello. Dark themes for ZeroBlog, ZeroMe, etc. can all be implemented by others.

**Comment by DaniellMesquita** [comment]
What he says is an API on ZeroNet, where sites can detect light/dark mode, like they detects the language?

**Comment by HelloZeroNet** [comment]
Added in 0.6.4
