### ISSUE TITLE
Feature read more on ZeroHello

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1575]
I have a Zeronet client with 3300+ zites and growing.
So i need that.

**Comment by anoadragon453** [comment]
What exactly are you asking for?

**Comment by imachug** [comment]
@anoadragon453 He asked to load first 100 sites on ZeroHello and add `More...` button. When you click, it 100 more sites are loaded, etc.

**Comment by anoadragon453** [comment]
Ah ok, yes that makes sense.

**Comment by HelloZeroNet** [comment]
It's added in lastest version of ZeroHello (by default only displays 100 sites)
