### ISSUE TITLE
Didn't showing post data (but I don't deleted it) on ZeroTalk

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1576]
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1534205182_15hL2gR4oCSgKBbndn3MxY8Hc5xoy1vqCe/ZeroNet+Plus+discussion+topic

**Comment by HelloZeroNet** [comment]
You json data file is invalid, if you fix it, then it will be visible:
```
Error: Parse error on line 389:
... 1536113204		}],		{			"comment_id": 5
---------------------^
Expecting 'STRING', got '{'
```
Using: https://jsonlint.com/

**Comment by DaniellMesquita** [comment]
Now it is a valid json, and I signed/published.
But yet, can't see post data, and can't post/like/comment.

**Comment by HelloZeroNet** [comment]
Yeah, it's a bit tricky and took me a while to find what's the problem: your data.json is saved with UTF8 BOM you have to save it without the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) to make it work.

It depends on your editor how to do that. I use Sublime Text, so in my case: File>Save with encoding>UTF-8

**Comment by DaniellMesquita** [comment]
Maybe is because of it that I could not move to another ZeroMe Hub.
