### ISSUE TITLE
Sqlite full text search.

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1581]
Does zeronet support it?
Maybe that's the best solution for searching.
Although horizon is using database,it's still slow.
Google says the FTS is so fast.

**Comment by HelloZeroNet** [comment]
No, FT search not compiled with python:
```py
import sqlite3

conn = sqlite3.connect("test.db")
conn.execute("CREATE VIRTUAL TABLE data USING fts3()")

> sqlite3.OperationalError: no such module: fts3

conn.execute("CREATE VIRTUAL TABLE data USING fts4()")

> sqlite3.OperationalError: no such module: fts4

```

**Comment by blurHY** [comment]
Available in python3.I tested

**Comment by blurHY** [comment]
In [5]: conn.execute("CREATE VIRTUAL TABLE data1 USING fts4()")
Out[5]: <sqlite3.Cursor at 0x28bfda55c00>

**Comment by HelloZeroNet** [comment]
It's good to know, so you have the answer: It will be available after we moved to python3 :)

**Comment by blurHY** [comment]
Yeah
