### ISSUE TITLE
Remove BitcoinECC dependency

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1585]
As far as I can see, BitcoinECC is only used for backwards-compatible methods, which I am not sure are still in use (please correct me if I'm wrong).

BitcoinECC is only used in [src/Crypt/CryptBitcoin.py](https://github.com/HelloZeroNet/ZeroNet/blob/bc227b5f561416f418014d9bccf95b405e34a14a/src/Crypt/CryptBitcoin.py):

https://github.com/HelloZeroNet/ZeroNet/blob/bc227b5f561416f418014d9bccf95b405e34a14a/src/Crypt/CryptBitcoin.py#L34-L43

https://github.com/HelloZeroNet/ZeroNet/blob/bc227b5f561416f418014d9bccf95b405e34a14a/src/Crypt/CryptBitcoin.py#L53-L57

https://github.com/HelloZeroNet/ZeroNet/blob/bc227b5f561416f418014d9bccf95b405e34a14a/src/Crypt/CryptBitcoin.py#L60-L75

I believe the `signOld` method can be removed immediately since it is only used in tests. The others seem a little more rooted in some useful methods.

What are your thoughts on this lib @HelloZeroNet, is it difficult to just strip out at the moment?

**Comment by HelloZeroNet** [comment]
Yes, it should be stripped out and ZeroBoard should be removed. (as it's the only active site that using old-style signing)

**Comment by DaniellMesquita** [comment]
@HelloZeroNet
You can add it to a "Python 3" milestone

**Comment by satoshisfriendz** [comment]
Very good idea! Thank you so much!

**Comment by purplesyringa** [comment]
Why exactly was old-style signing incorrect?

**Comment by HelloZeroNet** [comment]
I did not compared the implementation with other libs, but the lib author said the generated private/public keys are not secp256k1 compatible.

(we can close this as the lib was removed)

**Comment by purplesyringa** [comment]
Lol, this error is awesome. The lib uses `"\80"` instead of `"\x80"` for private key encoding. That's the only thing that makes the private key incorrect. (I still wouldn't recommend it though because it doesn't even check the checksum).
