### ISSUE TITLE
Chinese users needs IPv6 and DHT

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1589]
- [ ] IPv6 will make chineses have a faster and more reliable ZeroNet (#148)
- [ ] DHT is more robuts than peer exchange (#57)

**Comment by April93** [comment]
No need to wait on IPv6 trackers anymore, since we have bootstrapping. Should be fairly quick to implement (just add in a third address type).

**Comment by satoshisfriendz** [comment]
So close this?

**Comment by April93** [comment]
@satoshisfriendz it's not implemented yet. So it's still an issue. Especially for Chinese users.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/pull/1592

**Comment by blurHY** [comment]
@shortcutme  I think this issue is a duplicate,and it could be closed
