### ISSUE TITLE
PDFs not working properly through links (at least in Chrome)

### ISSUE THREAD

**Issue by zebMcCorkle** [HelloZeroNet/ZeroNet#159]
Take a look at http://zeronet.classcoder.com/1CVj75bq24SzjQZfMpDAgHAHGjMUNFukYU/index.html and press the link for "About ZeroNet:" it won't go anywhere! Now, take the direct link (http://zeronet.classcoder.com/1CVj75bq24SzjQZfMpDAgHAHGjMUNFukYU/about-zeronet.pdf) and it works! It seems links don't work like we're used to...

**Comment by HelloZeroNet** [comment]
To improve security every ZeroNet site runs in a sandboxed iframe. 
Looks like the browsers does not allow to load pdf to iframe. To load to the top frame you have to add `target="_top"` to your a html tag or `<base href="" target="_top"/>` to head to automatically convert every link on your site.
