### ISSUE TITLE
[Bug] Login button is hidden on HelloZero on Android

### ISSUE THREAD

**Issue by BenMcLean** [HelloZeroNet/ZeroNet#1593]
![20180912_120221](https://user-images.githubusercontent.com/1747250/45441139-e98b6d80-b683-11e8-9e23-e8555a8cc774.jpg)

This happens on both Chrome and FireFox, even when selecting "Desktop site".

 Please fix so that all buttons are accessible!

**Comment by HelloZeroNet** [comment]
The Logout button is only visible if you have the UiPassword plugin enabled

**Comment by BenMcLean** [comment]
While you're at it, would you consider adding zeroid.bit to the list of recommended sites. That's a site which new users are going to want to jump on right away IMO.

**Comment by anoadragon453** [comment]
@HelloZeroNet Ah ok, I'm just silly and need to disable that then. Thanks!

**Comment by anoadragon453** [comment]
We want to encourage decentralization of ID providers, so it's best that users either find them naturally through zites or perhaps there could be some sort of list with statistics on number of users currently. @HelloZeroNet what's the status on having 1iDxxx* regexes that sites can specify for ID providers?

**Comment by BenMcLean** [comment]
> We want to encourage decentralization of ID providers,

That's fine.

> so it's best that users either find them naturally through zites

Eww, no.

> or perhaps there could be some sort of list with statistics on number of users currently.

Better.

Why not consider a ZeroNet powered wiki project specifically for curating the best ZeroNet content for new users to try out?

**Comment by anoadragon453** [comment]
This has been done in a number of ways already. There's ZeroWiki: 
http://127.0.0.1:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/?Page:list-of-zites 
ZeroSites: http://127.0.0.1:43110/Sites.ZeroNetwork.bit/ ImportantZites: 
http://127.0.0.1:43110/15Pf9VVuDT8NSWj1qUBh4V89yPmrmzRw6a ImportantZites 
2: http://127.0.0.1:43110/1MiS3ud9JogSQpd1QVmM6ETHRmk5RgJn6E/?/ But none 
of them really caught on. iirc there should be something like ZeroSites 
but with time-weight application, where the links votes degrade over 
time and eventually expire after a week or something, meaning the list 
of links will change and evolve, encouraging people to keep coming back 
and checking out new sites.

We also need a way to showcase different developers and their projects, 
give them a following, make them feel what they're making is important. 
That's the way to draw in more developers.

**Comment by HelloZeroNet** [comment]
I made various changes on ZeroHello and it should fix this issue.
