### ISSUE TITLE
 Invalid value of Custom socks proxy address for trackers: tor (does not matches /.+:[0-9]+/)

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1600]
rev3594
Change the `Proxy for tracker connections` setting to `Custom` and save,then set it to `Tor`.

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev3609 https://github.com/HelloZeroNet/ZeroNet/commit/2a1849d027a7dee06808b2ac3bb88ba7652a11e3
