### ISSUE TITLE
[Feature] Search in other peers' databases.

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1602]
The way to search on zeronet is different to clearnet.
You know,search engine is important.
We could just write a zeronet-search-engine with a simple index of crawled zites.
But that's not enough.

**Comment by DaniellMesquita** [comment]
Good!
I suggested another, maybe it is something like: https://github.com/HelloZeroNet/ZeroNet/issues/1603

**Comment by blurHY** [comment]
Instead of getting files from other peers,we just query in their databases.Then the peers return the search result to us.For examle,there is a ZeroTalk zite which has only a few user,so we can search in these users' database to find the topic we want and determine to download the zite.

**Comment by blurHY** [comment]
Uh,how to ensure the search result is not faked.

**Comment by blurHY** [comment]
Generate signatures for each document unit (#1513).And the search results are serveral document units.Then we can check whether it is faked or not.But we still can't ensure that the search results are the best match.

**Comment by blurHY** [comment]
Using merkle tree (trenta3’s suggestion)

**Comment by blurHY** [comment]
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1536913855_1JcHMiQxXHX9q3ZK2LF9rZjvg3MUtTpcK
