### ISSUE TITLE
[Discussion] Credit system.Anti-spam and detecting bots.

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1608]
There are a lot of spammers&bots on the zeronet.It became a problem now.
And zeronet is still growing,so we should find a solution

**Comment by HelloZeroNet** [comment]
It's really hard to create a fair credit system in an anonymous/open system.

The shared blocklist feature was added to solve this problem.

**Comment by blurHY** [comment]
Credit system issue is also should not be closed.This is useful for search engine.I'd like it automated to accept/ignore report.

**Comment by DaniellMesquita** [comment]
> Downsides: Though this feature in its current state is no/or very low efficient against automated bots i think (automated botnet vs human person who manually manage blocklist) and also blocklist user have to trust the blocklist admin/s so they will not include innocent users or users who post spam on certain site, but on other zeronet sites they post useful content.

This downside explains all.
Say that a credit system will not introduced because ZeroNet is open, it is hypocrisy.

**Comment by krixano** [comment]
@DaniellMesquita That's not what he said. He said it'll not be introduced because **it's hard** with an open system, not because it's open. The stress is put on it being hard.
