### ISSUE TITLE
How about adding the on/off button for Bootstrapper or Multiusers plugin in CONFIG page?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1609]
It can be connvinient for users.They donot need change the name of plugin manually or set the value in conf file.

**Comment by HelloZeroNet** [comment]
I don't think it would be a good idea for Bootstrapper as it's only recommended to run if you have stable connection and you willing to run 24/7

**Comment by DaniellMesquita** [comment]
Isn't good a switch for a plugin that overwrites content.json every time it is disable/enabled.

**Comment by blurHY** [comment]
Maybe a plugin managing page.

**Comment by tangdou1** [comment]
There should be some description of these additional plugins for users in help file (such as https://zeronet.readthedocs.org ). I would never know these useful additional plugins if others didnot tell me about that (I just thought these plugin would be deleted by you in future).

**Comment by DaniellMesquita** [comment]
@tangdou1

Sorry for the off-topic, but about your IPv6 pull request? It is with conflict with new ZeroNet updates

**Comment by tangdou1** [comment]
Add some introduciton for disabled plugin in
 https://github.com/HelloZeroNet/ZeroNet/wiki/Introduction-for-default-disabled-plugin

> 
> 
> @tangdou1
> 
> Sorry for the off-topic, but about your IPv6 pull request? It is with conflict with new ZeroNet updates

I believe the official ipv6 support would appear soon.
