### ISSUE TITLE
Better UI for deleting a node

### ISSUE THREAD

**Issue by risoul** [HelloZeroNet/ZeroNet#161]
When we want to stop a seed and delete the node, the confirmation button appears at the top right. Not fast when deleting lot of nodes.

Solutions?
- allow to press enter to confirm deletion
- put delete confirmation button near the node

**Comment by HelloZeroNet** [comment]
Good idea, added notification button/input autofocus in latest update: 917393c0227b1e87d9206b25dbb17941d7692fac
Probably a multiple site selection will be required sooner or later to make it more comfortable.
