### ISSUE TITLE
Can't talk on ZeroTalk 

### ISSUE THREAD

**Issue by BenMcLean** [HelloZeroNet/ZeroNet#1611]
My attempts to talk or even vote on ZeroTalk just show the three dots animation forever. It never actually posts anything. What can I do to fix this? There's no error message to research.

**Comment by anoadragon453** [comment]
Anything in the JavaScript console?

**Comment by DaniellMesquita** [comment]
@BenMcLean 
Do you updated your ZeroNet?

**Comment by HelloZeroNet** [comment]
Please use the given template for reporting errors.

**Comment by BenMcLean** [comment]
I'll definitely be looking at the javascript console to see if there's an error when I get a chance

**Comment by DaniellMesquita** [comment]
I had the same error, then I updated ZeroNet to the latest version.
Do you manually edited your content.json? Maybe this also can be the error, if you saved it as UTF-8-BOM

**Comment by BenMcLean** [comment]
Javascript console says:
`"[ZeroTalk] Websocket callback not found: Object { cmd: "response", to: 11, result: undefined }"`

ZeroNet debug log says:
`[19:56:52] Site:1TaLkF..jipT data/users/BigString/data.json fileGet error: [Errno 2] No such file or directory: u'./data/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/data/users/BigString/data.json'`

Where I think "BigString" is my public key?

**Comment by anoadragon453** [comment]
Wait did the file get deleted? Beforehand it was just a mismatched size.

Did you try manually signing your content.json from the sidebar?

**Comment by DaniellMesquita** [comment]
@BenMcLean
You manually edited your content.json?
If yes, maybe you haved it as UTF-8-BOM.
Open it on Notepad++ and save as only UTF-8.

**Comment by BenMcLean** [comment]
This is on Ubuntu. (Notepad++ is only for Windows AFAIK) I edited something
with Gedit a while back to assign my private key to be able to delete
zites. Maybe that was it? I'll check.

**Comment by DaniellMesquita** [comment]
Yes, is this.
Open in Notepadqq (it is like Notepad++ but for Linux) and saves as UTF-8 without BOM

**Comment by krixano** [comment]
It doesn't really matter what text editor you use...

**Comment by DaniellMesquita** [comment]
> It doesn't really matter what text editor you use...

I'm suggesting a text editor where can change the UTF-8 format. Most of common notepads doesn't supports it.

**Comment by BenMcLean** [comment]
OK it turns out I only edited users.json

I never edited content.json

So that's not it.

**Comment by BenMcLean** [comment]
I reinstalled ZeroNet from scratch. Now I can post on ZeroTalk! But ZeroTalk always says "4 file update failed" in the sidebar. What do I do about that?

**Comment by krixano** [comment]
@DaniellMesquita You're wrong. Most text editors are default to UTF-8, even Notepad on Windows.
