### ISSUE TITLE
ZeroHello [ bug ]   Sidebar.prototype.setHtmlTag  Can not read .. of null

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1614]
```
    Sidebar.prototype.setHtmlTag = function(res) {
>>>      if (this.tag.find(".content").children().length === 0) {
```
```
> this.tag
null
```

**Comment by HelloZeroNet** [comment]
I just added some changes/optimizations to sidebar in Rev3608, can you please check if you can reproduce the error?

**Comment by blurHY** [comment]
I forgot how did i produce the error,maybe it just occurs occasionally.Add `if(this.tag)` could solve that
