### ISSUE TITLE
Language sufixes (such as chinese and simplified chinese), detects the country of a language (pt, pt-br)

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1616]
It is using Portuguese (Portugal) as default.

**Comment by HelloZeroNet** [comment]
Yeah currently work like this:
```
        try:
            language, enc = locale.getdefaultlocale()
            language = language.split("_")[0]
        except Exception:
            language = "en"
```
We could add an exception for pt-br or we could remove the language "autodetect" part, start in english by default and let the users to pick the language if they want.

**Comment by DaniellMesquita** [comment]
> could remove the language "autodetect" part, start in english by default and let the users to pick the language if they want

Never do it, or newbie users will be confused, and you need them.
Like Windows needed Start menu for newbies.

**Comment by DaniellMesquita** [comment]
> We could add an exception for pt-br

Or auto detect languages that haves a suffix, for sample, traditional and simplified chinese.

**Comment by HelloZeroNet** [comment]
Added in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/b089355b5ac08e600f1b9fdc5ac12d6c5e15b19d

I was unable to test, so it would be helpful if you can confirm the detection on a new installation

**Comment by DaniellMesquita** [comment]
You could make it more generic instead of directly refering to pt-br, also to support chinese and traditional chinese. There are other languages with country variation.
