### ISSUE TITLE
UiWSGIHandler error [Errno 32] Broken pipe in UiServer.py line 40

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1618]
UiWSGIHandler error: error: [Errno 32] Broken pipe in UiServer.py line 40 > pywsgi.py line 871 > pywsgi.py line 862 > pywsgi.py 

[See Log at pastebin](https://pastebin.com/Q0e8M4xN)

From https://github.com/blurHY/Horizon/issues/7#issuecomment-421740294

**Comment by HelloZeroNet** [comment]
For some reasons the browser does not closed the connection properly. Probably you can ignore it.

**Comment by blurHY** [comment]
Why not to add some try...catch.. ?

**Comment by HelloZeroNet** [comment]
It can be an error in browser/proxy/network connection, so I think it's worth logging. Actually I never got it, so no idea when and why is it happening.

**Comment by imachug** [comment]
BTW, I get this error too, but couldn't debug it.

**Comment by DaniellMesquita** [comment]
@blurHY

**Comment by blurHY** [comment]
@slrslr

**Comment by slrslr** [comment]
@DaniellMesquita @blurHY when i try to repeat what i did when the Broken pipe error appeared (first time opening new zite (horizon)), then i no longer see this error, so i do not think it is related to Horizon zite. I found it today once in the log, but i do not believe we can find the cause. It can be too difficult to catch it while these things come to play:
ZeroNet
Overloaded PC
My ISP connectivity
My OpenVPN server and its connectivity
PS @blurHY : i will be watching your search engine to see how it works and [report any issue](https://github.com/blurHY/Horizon/issues) i find.
