### ISSUE TITLE
provide a http proxy

### ISSUE THREAD

**Issue by aaannndddyyy** [HelloZeroNet/ZeroNet#162]
Please provide a http proxy so that I can change my browser to use that one to access zeronet sites.
I may not want them all to be localhost links because of security issues with that

**Comment by Angristan** [comment]
+1

**Comment by HelloZeroNet** [comment]
Providing a centralized http proxy would go against the purpose of the network.

**Comment by Angristan** [comment]
Yes, but let me take an exemple : 
I have a very bad internet connection, but my linux server has a good one. I install Zeronet and my server with a proxy so *I* can access it without overloading my upload

**Comment by HelloZeroNet** [comment]
It's possible, you have to start it using `zeronet.py --ui_ip "*"`

More info: http://zeronet.readthedocs.org/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine

**Comment by Angristan** [comment]
Awesome :D

**Comment by aaannndddyyy** [comment]
You misunderstood me.
I don't want a central server.
I want zeronet to be accessible on my computer, but in my browser I want to enter zeronet addresses, not local host, like when I use tor to surf the www

**Comment by HelloZeroNet** [comment]
it's possible if you redirect *.bit and zero domains to 127.0.0.1:43110
this extensions to this for your: https://chrome.google.com/webstore/detail/zeronet-protocol/cpkpdcdljfbnepgfejplkhdnopniieop/
you will able to access eg http://zeronetwork.bit directly

**Comment by aaannndddyyy** [comment]
So ZN already has that feature?
I could set 127.0.0.1:43110 as the proxy in my browser and then I can 
directly navegate to http://zeronetwork.bit/ ?
I'll try when I get home...

( the addon only is for chrome chrome and only if I install the 
extension, so I want a solution without addon/extension )
