### ISSUE TITLE
Multi-processing : While i'm searching with Horizon,i can't open ZeroHello(it says loading).

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1620]
rev3597
Is it because zeronet doesn't use multi-processing?

**Comment by HelloZeroNet** [comment]
Yes, zeronet is single-threaded right now.

**Comment by blurHY** [comment]
Is multi-processing planed ?

**Comment by HelloZeroNet** [comment]
Yes, I will check the possibility when moving to python3
