### ISSUE TITLE
MultiUser plugin: don't automatically show user seed/privatekey (for privacy)

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1630]

**Comment by Thunder33345** [comment]
the user master seed is never shown
unless they choose to show it

the USER:(1smth)
i am not really sure what that's called or is shown to public

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
The multiuser plugin made for proxies. If you don't show the private key, then the user won't be able to use it later.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
> The multiuser plugin made for proxies. If you don't show the private key, then the user won't be able to use it later.

The multiuser plugin made for both local installations and proxies, working very well.
I'm not talking about not showing the privatekey, as this is really needed. The suggestion is a button to show the privatekey or save it as .txt to a drive. More secure on public places, where the privatekeys can be seen on the screen.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/547
