### ISSUE TITLE
The peer table in bootstrapper.db is strange because you can not know the ip4 address for a onion peer, also you can not konw the onion address for a ip4 peer.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1637]
**Why not just use "address" for "ip4" and "onion", just like the peer table in content.db and "address" is alse compatible for ip6.**

**Comment by HelloZeroNet** [comment]
Not sure why did I chosen the separate fields, but probably it would be better use same "address" field and a separate type (ipv4, ipv6, onion) to allow fast, indexed filtering

**Comment by tangdou1** [comment]
The .db format has been upgraded in the official ipv6 support in rev.3802.
