### ISSUE TITLE
It is not easy to know how many zites I am serving, I must count them one by one.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1638]

**Comment by blurHY** [comment]
sitelist api ?

**Comment by DaniellMesquita** [comment]
ZeroHello could introduce a counter on top of site list.
Or you can submit a pull request: https://github.com/HelloZeroNet/ZeroHello

**Comment by tangdou1** [comment]
> 
> 
> ZeroHello could introduce a counter on top of site list.
> Or you can submit a pull request: https://github.com/HelloZeroNet/ZeroHello

Yes, I can code for it. But I dont know whether HelloZeroNet like it or he want to implement in anthor way, so I may just wate my time if he donot like my code style or my web design. Also it is a small job if he wants to implement it, I just give a suggestion.

**Comment by HelloZeroNet** [comment]
I have added the number of served sites to two places: 

- Stats tab on ZeroHello, Total size block: 26.57 MB IN 14 SITES
- The site filter field will also display it if you search for something eg: (found 1 of 14 sites)
