### ISSUE TITLE
Remove no longer required files

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#164]
Periodically (or when new content.json received) delete files that not included in new content.json anymore.

+ add new command to ZeroFrame API: fileDelete

**Comment by edisontrent** [comment]
Good too see that this is planned. Exactly what my site needs.

**Comment by HelloZeroNet** [comment]
Added in Rev409: 917393c0227b1e87d9206b25dbb17941d7692fac
