### ISSUE TITLE
Isn't showing my own IPv4 tracker address (bootstrap)

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1642]

**Comment by HelloZeroNet** [comment]
Please be more specific and use the template to report bugs.

**Comment by imachug** [comment]
Err... sidebar?

**Comment by DaniellMesquita** [comment]
When using IPv4, it isn't showing my bootstrap IP address

**Comment by HelloZeroNet** [comment]
Do you have opened port?

**Comment by DaniellMesquita** [comment]
No, because of my modem

**Comment by HelloZeroNet** [comment]
Then it won't add to the list as it would not work for other users.
