### ISSUE TITLE
System notification e.g. Tray icon

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1651]
Outlook notifies me by adding a icon to the tray

**Comment by krixano** [comment]
The Windows version of ZeroNet already adds a Tray Icon to provide quick options to, for example, shutdown ZeroNet, etc. Are you suggesting another tray icon be put to provide notifications.

I'd rather ZeroNet support the native OS's notification system instead of a tray icon approach.

**Comment by blurHY** [comment]
I've blocked all the system notifications,because there's something makes me annoyed. So outlook notifies me by **adding a new tray icon** to the tray.The new tray icon will stay here for a few seconds,then it will be hided.

**Comment by HelloZeroNet** [comment]
I think it would be better to use the browser's notification system as it more cross-platform, could work in mobile, etc.
