### ISSUE TITLE
[Question] Can run more than one ZeroNet instance?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1653]

**Comment by imachug** [comment]
It can if you set different data folders and port (via CLI arguments).

**Comment by DaniellMesquita** [comment]
But isn't uiserver to make it accessible via LAN?

**Comment by imachug** [comment]
No, it's `fileserver`.

**Comment by DaniellMesquita** [comment]
What port you recommend? That is less probably to be used.

**Comment by imachug** [comment]
`7832`.

**Comment by leftside2** [comment]
Do we need a kind of the duplicate of the Zeronet directories, or just execute the same zeronet.py?

**Comment by DaniellMesquita** [comment]
I'm asking this because I'll create a app framework for ZeroNet based on Electron/Cordova, for dedicated apps (replacing ZeroHello to the app zite, and only storing ID providers.

**Comment by blurHY** [comment]
It just needs different ui-server and file-server port

**Comment by leftside2** [comment]
@blurHY , Any possibility to have different tor IP address for each instance??

**Comment by leftside2** [comment]
My main process : $ ./ZeroNet.sh --tor always --tor_controller 127.0.0.1:9151;
error msg: None.

Additional instance : $ ./ZeroNet.sh --ui_port=8090;
error msg: Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 11] Resource temporarily unavailable)

**Comment by blurHY** [comment]
You need two zeronet folders

**Comment by leftside2** [comment]
@blurHY , that's the answer what I wanted! :100:

**Comment by HelloZeroNet** [comment]
You can, but you need to specify unique values for data_dir, log_dir, fileserver_port, uiserver_port

**Comment by DaniellMesquita** [comment]
Why need to specify data_dir, log_dir, if ZeroNet instance could detect from which folder it is running?

**Comment by DaniellMesquita** [comment]
Also, when detecting that another instance is running, run in fileserver/uiserver ports with increased number.

**Comment by HelloZeroNet** [comment]
Changing data_dir and log_dir is only necessary if you try to run it from the same directory (using the same binary). I think silently running it on different port would be a bad idea as most of the users don't want to run multiple instances.
