### ISSUE TITLE
[Question] ZeroNet on mesh networks

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1654]
@HelloZeroNet @shortcutme 

Sorry for those questions, but they are needed.

Regarding LocalPeerDiscovery, what are the plugins that handles this?
I'm not seeing the "Local" message on sidebar. @imachug is this because one of your plugins?

When I setup a WiFi router that haves no internet connection, and connect to it with my computer, then other users using mobile connects, they can download sites from me in all speed of the network without relying Internet?

And if my computer is connected to two WiFi networks, using a USB dongle? Users that connects to the second WiFi where the dongle connects, other users also haves access? There are security threats about it?

**Comment by HelloZeroNet** [comment]
By using the local discovery you should able to discover the computers that are on the same networks as you and serving sites you are interested in even if there is internet connection.

As for security: This feature requires to broadcast your list of sites to other peers on the network.

**Comment by DaniellMesquita** [comment]
You say that I'm not clear on my questions, but I detailed a lot and not replied.
