### ISSUE TITLE
OpenSSL not working on 64-bit Windows

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#1655]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.3 (rev3576)
  * Operating system: Windows 10, 64 bit
  * Web browser: Firefox
  * Tor status: error
  * Opened port: yes
  * Special configuration: none

#### Steps to reproduce:

  1. Buy 64-bit processor
  2. Install 64-bit Windows
  3. Run ZeroNet

#### Observed Results:

I get:

```
Internal error: WindowsError: [Error 193] %1 is not a valid Win32 application
UiWebsocket.py line 81 > UiWebsocket.py line 267 > CryptMessagePlugin.py line 34 > CryptMessagePlugin.py line 14 > CryptMessage.py line 8 > builtins.py line 96 > __init__.py line 16 > builtins.py line 96 > openssl.py line 504 > openssl.py line 501 > openssl.py line 73 > __init__.py line 366
```

This happens because the DDL ZeroNet uses to load OpenSSL is 32-bit. However, my Python is 64-bit, and a 64-bit application cannot use a 32-bit DLL.

#### Expected Results:

It works.

#### Temporary Solution:

Install 32-bit Python.

**Comment by HelloZeroNet** [comment]
Yes, it's a known problem, there is only 32bit distribution of ZeroNet right now. (it works on both 32bit and 64bit windows)

You can fix it by replacing the dlls in src/lib/opensslVerify with https://indy.fulgan.com/SSL/openssl-1.0.2p-x64_86-win64.zip ones.

With moving to python3 it's also planned to remove the lib dir and use systems installed ones (with PIP) or the bundled ones in case of binary distributions, so we can have both 32bit and 64bit versions for windows.

**Comment by imachug** [comment]
@HelloZeroNet Uploading big files doesn't seem to work.

If you upload a file to [KxoNetwork](http://127.0.0.1:43110/1GTVetvjTEriCMzKzWSP9FahYoMPy6BG1P) (I just uploaded a plugin), I get this error:

```
[08:20:11] - UiWSGIHandler error: TypeError: 'NoneType' object is not subscriptable in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 908 > helper.py line 304 > Bigfile/BigfilePlugin.py line 101 > PeerHashfield.py line 56
```

Sounds like the hash is None.

If I upload a file to ZeroUp, I get this:

```
[08:34:44] - UiWSGIHandler error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 813: character maps to <undefined> in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 908 > helper.py line 304 > Bigfile/BigfilePlugin.py line 102 > OptionalManager/OptionalManagerPlugin.py line 72 > Bigfile/BigfilePlugin.py line 370 > Bigfile/BigfilePlugin.py line 458 > cp1251.py line 23
```

In case you need the files, here they are:

[For KxoNetwork](https://github.com/HelloZeroNet/ZeroNet/files/3052756/Plugin-PeerMessage-py3.zip)
[For ZeroUp](https://github.com/HelloZeroNet/ZeroNet/files/3052755/sublime_merge_build_1107_x64_setup.zip)

**Comment by canewsin** [comment]
Is this still an issue ? I think I don't face on latest win dist !
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
Yeah, it can be closed (actually we have only binaries for 64bit currently)
