### ISSUE TITLE
How about improving the burdern of signing in order to prevent spammer.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1660]

**Comment by Thunder33345** [comment]
while looks good, we should take note that this will also may affect mobile users who would have the least POW to sign

lets assume the spammer runs over some PC, which means if we want to even make it remotely hard, we need to make it harder for PC to sign

which will forcefully make it even harder for mobile, and laptop to sign
which could be annoying

**Comment by HelloZeroNet** [comment]
Yeah the problem if for example we require 1 minute POW from every user before sending a message (would be a really bad user experience), then a spammer with a decent CPU/GPU would still able to spam 1 message/second

**Comment by Thunder33345** [comment]
i think you are missing the point here,
yes you make it hard for below average users
but will still have no effects to above average users(which we assume where spammers are)

POW is never meant to be a magical spell that solve everything
so far the most notable and reasonable example is bitcoin using POW to make it unprofitable to attack bitcoin
sure you can do a double spend attack, but the cost will always outweigh what you get by attacking it
