### ISSUE TITLE
"This function is disabled on this proxy!" for master_seed

### ISSUE THREAD

**Issue by BenMcLean** [HelloZeroNet/ZeroNet#1662]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.2
  * Operating system: Ubuntu
  * Web browser: Chrome
  * Tor status: not using
  * Opened port: yes
  * Special configuration: Multiuser plugin turned on, users.json edited to make master_seed be my own private key

#### Steps to reproduce:

  1. Turn on multiuser plugin. Edit users.json to change master_seed and restart ZeroNet
  2. Download a zite.
  3. Login with your private key (the one master_seed was set to) and try to delete the zite.

#### Observed Results:

"This function is disabled on this proxy!"

#### Expected Results:

Delete the site. There should be no such thing as functions "disabled on this proxy" for master_seed, no matter how the server is configured.

**Comment by Thunder33345** [comment]
start zeronet with ` --multiuser_local` to tell zeronet to enable unsafe functions since you are the only one using it

**Comment by Thunder33345** [comment]
that means anyone who can access your proxy regardless of IP can do so
so you should also enable passwordUI to prevent unauthorized access

**Comment by BenMcLean** [comment]
OK ... can I authorize specific users to delete zites and undertake other functions but not authorize others?

**Comment by BenMcLean** [comment]
multiuser_local fixed my problem. Thanks!

Although I'd still like to know how to authorize multiple users

**Comment by HelloZeroNet** [comment]
The users that are in the data/users.json file are acts as master users with no restrictions. So if you add the users master_seed there then by that you can authorize multiple users.
