### ISSUE TITLE
I click a  zite link in one zite, it just show nothing

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1670]
ZeroNet version: 3616
browser: firefox
Os: vps: debian, my own computer: win7

zeronet is in vps.

Press F12
SecurityError: Permission denied to access property "toString" on cross-origin object

in
```
// If we are inside iframe escape from it
if (window.self !== window.top) {
	window.open(window.location.toString().replace(/([&?])wrapper=False/, "$1").replace(/&$/, "").replace(/[&?]wrapper_nonce=[A-Za-z0-9]+/, ""), "_top");
	document.write("Escaping from iframe...");
	window.stop();
	document.execCommand("Stop", false);
}

// We are opened as a parent-window
else if (window.opener && window.opener.location.toString()) {
	document.write("Opened as child-window, stopping...");
	window.stop();
	document.execCommand("Stop", false);
}
```

**Comment by imachug** [comment]
Browser, OS?

**Comment by HelloZeroNet** [comment]
Is this happens for every site or just some specific sites?

**Comment by tangdou1** [comment]
> 
> 
> Is this happens for every site or just some specific sites?

I add the link in my site. Each time I click it, the "SecurityError: Permission denied to access property "toString" on cross-origin object" would show in console.
<a href="/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n" target="_blank">http://127.0.0.1:43110/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n</a>

**Comment by HelloZeroNet** [comment]
Unfortunately target="_blank" does not work well with sandboxed iframe. I recommend to open all links to same page and use target="_top" for all links or adding <base target="_top"> to header. (see zerotalk for example)
