### ISSUE TITLE
rev3616:  Sidebar.prototype.stopDragX :  _this.tag is null

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1676]
Ubuntu18.04;Firefox62

![default](https://user-images.githubusercontent.com/33171396/46468198-5668d200-c802-11e8-9a79-e14a5a3f010d.png)

**Comment by HelloZeroNet** [comment]
Thanks for reporting I have added a fix for it in Rev3619 https://github.com/HelloZeroNet/ZeroNet/commit/424b36ffca79238e9895052c1d56153f8590bbae
