### ISSUE TITLE
Please allow the Percent sign as a valid file name character

### ISSUE THREAD

**Issue by geekless** [HelloZeroNet/ZeroNet#1678]
Example URL with Percent-encoding: `somedomain/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80.html`
Displayed in a browser as: `somedomain/Пример.html`

I was trying to make a ZeroNet mirror for some clearnet sites. Surprisingly, it is not generally possible, since ZeroNet doesn't allow using Percent-encoded URIs as valid file names. The Percent sign is missing from the list of allowed characters in `ContentManager.py`:

```
    def isValidRelativePath(self, relative_path):
        if ".." in relative_path:
            return False
        elif len(relative_path) > 255:
            return False
        else:
            return re.match("^[a-z\[\]\(\) A-Z0-9_@=\.\+-/]+$", relative_path)

    def sanitizePath(self, inner_path):
        return re.sub("[^a-z\[\]\(\) A-Z0-9_@=\.\+-/]", "", inner_path)
```

**Comment by HelloZeroNet** [comment]
I'm not fan of utf8 filenames: it's harder to handle, debug and not compatible with every file systems, so I would avoid using it, but utf8 filenames supported inside zip files, so you can compress it, then access the files like somedomain/archive.zip/Пример.html (not all zip compressor supports utf8 filenames, I recommend to use 7zip)

**Comment by imachug** [comment]
Additionally, @HelloZeroNet, I'd recommend allowing # and @ and = and some other special characters.

**Comment by geekless** [comment]
@HelloZeroNet,

> I'm not fan of utf8 filenames: it's harder to handle, debug and not compatible with every file systems

It is NOT utf8 filenames. It is good old plain ascii filenames, that are totally compatible with any file system. Can you tell me, what a file system is not compatible with the percent sign?

**Comment by HelloZeroNet** [comment]
@imachug: as you can see in the included source code @ and = are allowed, adding # would be problematic as it has special meaning in browser urls: opening /anydoman/anyfi#le.txt will lead to GET /anydomain/anyfi

@geekless when you enter `somedomain/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80.html` to the browser will send the exactly same request as you enter `somedomain/Пример.html`

**Comment by imachug** [comment]
@HelloZeroNet Yeah, I see the problem. In my case, I was only going to use `fileGet`, as it would simplify it, but I see that it would bring some difficulties in URL, so I've already came up with a solution: `#` -> `charCodeAt("#")`

**Comment by bAndie91** [comment]
guys, IMO files in a zite should not only compatible with web usage, personally I wish they were more like network filesystems. Unicode support is pretty good nowadays. I completely disagree denying any char in zeronet filenames. When you are about to access them via http interface, you `urlEncode` them. Always. If the underlaying filesystem happens to not to cope with certain filenames, then it's a typical case of "you can not host this site as-is". So speaking of access via http, urlEncoding can encode all filenames which supported by any filesystem, even more, because `%00`. So please do unicode.
