### ISSUE TITLE
[Question] ZeroFrame command to get IPv4 / IPv6 address of peers?

### ISSUE THREAD

**Issue by trenta3** [HelloZeroNet/ZeroNet#1682]
Is it possible for a site to get a list of the addresses peers the current client is connected to?

This would be very useful if one wants to use e.g. [Webtorrent](webtorrent.io), [GUN](gun.eco) (a graph database) or other in-browser things that require peer addresses to work properly. This would enable their use on ZeroNet, completely decentralized.

Don't know if it has "deanonimizing" implications: e.g. one site may georesolve those IPs and guess our location, or something like that. In that case one could have such a feature on permission.

**Comment by HelloZeroNet** [comment]
To create a direct webrtc connection you need a stun server that holds the ip addresses (similar to tracker, but stores more information), so getting the list of ip will not work.

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Protocols
