### ISSUE TITLE
Blank whitespace forum posts should not be allowed

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#169]
If you wanted you could make a post on the forum module with a title consiting of a space and a body content consisting of a space. This should not be allowed.

**Comment by HelloZeroNet** [comment]
thanks, fixed: https://github.com/HelloZeroNet/ZeroTalk/commit/935a4e0b3fcdae5dbf439bb0564b7128939a2b75

**Comment by deavmi** [comment]
@HelloZeroNet pleasure :+1:
