### ISSUE TITLE
[Question] How much numbers ZeroHello can show?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1692]
If there is 1K peers on a site, it shows 1000.
But if haves 50K? 50000? Too long.
This could support to show begining at:

- [ ] 1K
- [ ] 1mi
- [ ] 1bi

**Comment by HelloZeroNet** [comment]
Normally it won't store more than 1k peers, so you should not see larger numbers than that.

**Comment by DaniellMesquita** [comment]
User could not store more peers?

**Comment by HelloZeroNet** [comment]
It's unnecessary, and would increase the mem, cpu, db usage

**Comment by DaniellMesquita** [comment]
But if user wants and haves a good computer for it?
