### ISSUE TITLE
The number of sites of one peer in Stats page is too small. 

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1695]
### Step 1: Please describe your environment

  * ZeroNet version: __3616___
  * Operating system: ___win7_and debian_
  * Web browser: ___firefox__
  * Tor status: disabled
  * Opened port: yes/no
  * Special configuration:  no

### Step 2: Describe the problem:

There is only 10 sites for the peer of PC B in the Stats page of zeronet in PC A, the PC B has hundreds of sites though. 

#### Expected Results:

  The number of sites should be in consistence with the realistic number of sites in PC B.

**Comment by HelloZeroNet** [comment]
It only displays the number of sites that present on both peers. Also it's not the exact number as this calculation is based on results from trackers. 
It only used for calculate how valuable this peer for you: if your client reaches the maximum connection limit it closes the peer with the less sites value.
