### ISSUE TITLE
ZeroFrame API: command to open zite folder on explorer

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1697]

**Comment by Thunder33345** [comment]
and add that to explore on the sidebar too(might not work for proxies need edge case handling)

**Comment by HelloZeroNet** [comment]
There is already a OPEN SITE DIRECTORY on the sidebar and we have API command for this, but its limited to admin sites due security reasons.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet What are the security implication of a zite prompt (on user click) to open its own folder?

**Comment by krixano** [comment]
One that I could think of is a zite that continually opens the folder every second, for example.

**Comment by DaniellMesquita** [comment]
But the API could prevent it
