### ISSUE TITLE
Collapsible hub list on zite instead of having its own list

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1698]

**Comment by HelloZeroNet** [comment]
One merged site can belongs to multiple merger sites and a site can be merger site for multiple type of merged sites, so would add lots of unnecessary complication

**Comment by DaniellMesquita** [comment]
With CORS, is really needed for a merged site belong to multiple merger sites?

**Comment by krixano** [comment]
Yes, because CORS is currently read-only.

**Comment by HelloZeroNet** [comment]
The main difference is with merger site you will have one database, with cors there will be separate database for every site.

**Comment by DaniellMesquita** [comment]
But I heard CORS can also write

**Comment by imachug** [comment]
Let me ask, where did you hear that?

**Comment by DaniellMesquita** [comment]
On GitHub, but I don't remember in which repo
