### ISSUE TITLE
Sub hubs

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1699]
Like notification feed haves categories, hubs can have categories and be inside other hubs in collapsible list

**Comment by HelloZeroNet** [comment]
One merged site can belongs to multiple merger sites and a site can be merger site for multiple type of merged sites, so would add lots of unnecessary complication

**Comment by DaniellMesquita** [comment]
Unless you rethink well and change how hubs works.
A hub belonging to more than one site is the unnecessary complication
