### ISSUE TITLE
Grammar error on ZeroHello module page

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#170]
The sentence in the pruple banner `This site currently served by 70 peers without any central server.` is grammatically incorrect and should be `This site is currently served by 70 peers without any central server.` **is** was needed.

Also I think this (for some reason) appelas to me to phrase it like this: `This site is currently being served by 70 peers without any central server.`

**Comment by zebMcCorkle** [comment]
I'm no ultimate grammar guru, but I believe the original is correct grammar.

**Comment by deavmi** [comment]
It just doesn't sound right to me.

**Comment by deavmi** [comment]
This sentence `This site currently served by 70 peers without any central server.` sound sbetter when it is part of a bigegr picture.

`This site, currently served by 70 peers without any central server. (adjectival phrase), is a very popular site.`

**Comment by HelloZeroNet** [comment]
I'm not a native speaker, so I googled for "currently served by", first page matches:
- Churches currently served by the EAMC Parish Nurse Program
- Line 52 will pass under the River Ij, currently served by GVB ferries.
- Water Supply to an Area of a City currently berved by a ...
- Schools currently served by the Chula Vista Nature Center ...
- Community currently served by long distribution lines
- majority of owners in an area not currently served by the waterwork
- Murcia is currently served by two airports 
- Which country is not currently served by peace corps
- The LDS Meeting House is currently served by City wastewater
- City Utilities invites neighborhood associations currently served by Aqua Indiana water service to include this column

So booth looks valid to me...

**Comment by deavmi** [comment]
Okay. :smile: Thanks for putting in the effort.

**Comment by ThomasdenH** [comment]
As a standalone sentence it is not fully correct, but often headlines and short descriptions tend to leave out those words. This structure is correct when it is a side-remark in the sentence, e.g. "Churches currently served by a program tend to have a closer community than regular churches." In that case, the expected 'that are' can be left out.

**Comment by deavmi** [comment]
Okay, so it takes out tedious words then. Okay. :smile:
