### ISSUE TITLE
LocalNetwork: offline file/zite request

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1702]
* Offline user tries to download ZeroUpdate
* This request is announced to all other local peers, and if one is online, he can bridge the download or seed if it is already downloaded

**Comment by geekless** [comment]
I've been thinking about the bridging feature for long time, but I still have no good ideas on implementing it.

**Comment by DaniellMesquita** [comment]
http://127.0.0.1:43110/zeromedium.bit/?/15hL2gR4oCSgKBbndn3MxY8Hc5xoy1vqCe/how-do-i-envision-zeronet-to-be-ready-for-mass-of-users-part-1

**Comment by HelloZeroNet** [comment]
It's already working that way since the local peer discovery plugin

**Comment by DaniellMesquita** [comment]
But how offline user knows that online user bridge a download for he, that online user didn't haves?

**Comment by HelloZeroNet** [comment]
Of Course it's only working for sites that the other user already downloaded. I think it would be bad idea to run a proxy on a machine by default.

**Comment by DaniellMesquita** [comment]
Not to run a proxy, but receive notification that user wants to download contents to be bridged, then receive back when they are downloaded.
