### ISSUE TITLE
Git plugin

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1704]

**Comment by Thunder33345** [comment]
explanation??

**Comment by DaniellMesquita** [comment]
A untamperable plugin where sites can manage git features, such as archiving like IPFS and site's repo.

**Comment by HelloZeroNet** [comment]
There is a javascript implementation of Git that you can use if you really need.

**Comment by imachug** [comment]
BTW, I haven't found any working Git implementation in JavaScript that really works. Basically, that's the reason I made Git Center that uses my own library.

**Comment by DaniellMesquita** [comment]
> BTW, I haven't found any working Git implementation in JavaScript that really works. Basically, that's the reason I made Git Center that uses my own library.

Git Center needs a little attention in important things that are missing
