### ISSUE TITLE
Picture in picture mode

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1707]
For sample, load ZeroID inside a site that requested it.

**Comment by HelloZeroNet** [comment]
Trying to implementing browser into a browser sound like a bloat for me

**Comment by DaniellMesquita** [comment]
It is browser into browser? o.o

**Comment by krixano** [comment]
Yall are really talking about iframes, right?

**Comment by DaniellMesquita** [comment]
Yes
iFrames to implement PiP mode to make user registration easier
