### ISSUE TITLE
Detect pt-br language on zeronet.io

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1708]

**Comment by HelloZeroNet** [comment]
Can you please check your browser's accept-header value on: http://www.reliply.org/tools/requestheaders.php ?

**Comment by DaniellMesquita** [comment]
![image](https://user-images.githubusercontent.com/6765277/47087098-8eecb080-d1f1-11e8-86ca-11b8725069fc.png)

**Comment by HelloZeroNet** [comment]
Your browser report only "en-US" as accepted language, so there is no way to serve pt-br language based on that information

**Comment by DaniellMesquita** [comment]
I'd tested and it is working.
Thanks
