### ISSUE TITLE
Add a promise-based version of cmd to ZeroFrame.coffee

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1714]
In every new zite I make, I like to have both a `ZeroFrame.cmd` and `ZeroFrame.cmdp` available, the latter being exactly the same as `cmd` except it returns a promise once finished instead of requiring a callback.

Here is `cmdp` implemented in JS:

```
    cmdp(cmd, params={}) {
        return new Promise((resolve, reject) => {
            this.cmd(cmd, params, (res) => {
                if (res && res.error) {
                    reject(res.error)
                } else {
                    resolve(res)
                }
            })
        })
    }
```

I assume https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/UiConfig/media/js/utils/ZeroFrame.coffee is the file we'd need to add this to, however I'm unfamiliar with coffeescript.

**Comment by HelloZeroNet** [comment]
Actually its included to the "Create, new empty site template": https://github.com/HelloZeroNet/ZeroHello/blob/master/template-new/js/ZeroFrame.js#L75

It could be also added to UiConfig and other ZeroFrame implimentations, but since that part not using it I think its not necessary

**Comment by anoadragon453** [comment]
Ahh, I thought this was the source file from which that came from. Glad to hear it's included!
