### ISSUE TITLE
Found a bug in the forum module

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#172]
1. Make a comment or post somewhere that has a value (text) that is very long.
2. Post the comment or new topic
3. You will get an invalid private key error (but it will still post)

As long as that long-valued post or comment exists, you will continuously get an `Invalid private key` error until you delete that long-valued post.

If you made a long-valued post, you can still post (with an error) but not comment.
If you made a long-valued comment, you can still comment and post.

**Comment by imachug** [comment]
@HelloZeroNet This issue is connected to ZeroTalk, not ZeroNet core, and is actually outdated because we have better error messages -- can we close it?
