### ISSUE TITLE
Tracker window opening above the page

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1721]
Just opening the trackers results in the modal appearing above the page.

![image](https://user-images.githubusercontent.com/1342360/47177816-c0f93200-d319-11e8-8fb1-da48f913c036.png)

**Comment by HelloZeroNet** [comment]
Fixed: https://github.com/HelloZeroNet/ZeroHello/commit/9da599f1194d8ec5ab584638492c16518ec33591

**Comment by anoadragon453** [comment]
Thanks!
