### ISSUE TITLE
Need to publish site?

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1723]
@imachug 
![image](https://user-images.githubusercontent.com/6765277/47190977-e3d81600-d31a-11e8-978a-2879a7fb85e1.png)

**Comment by HelloZeroNet** [comment]
Trackers got announced every 20 minutes. If for some reasons you need it immediately you can push the update button.

(btw I think sharing a screenshot of your computer is never a good idea)
