### ISSUE TITLE
Updates isn't shown on ZeroHello

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1724]
I clonned ZeroHello repo into its site, and changed Left.css.
Run ZeroNet .exe with --debug flag, disable cache on browser, but ZeroHello isn't updated.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 

How can users contribute to ZeroHello if they can't see what they changed?

**Comment by HelloZeroNet** [comment]
It should be changed. You also need to enable the "This is my site" on sidebar.
