### ISSUE TITLE
Another bug in forum module

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#173]
1. Create a forum topic
2. Click on the topic to view it
3. Delete the topic whilst you are viewing the full topic
4. It will still exist on the system.

For example: http://talk.zeronetwork.bit/?Topic:21_1JdoX9KdJeRVjN9zvK8N9C5jybEHzZe8n/f

**Comment by deavmi** [comment]
Does this big still exist?

**Comment by HelloZeroNet** [comment]
this is not a bug, but how zeronet works: you can't modify other user's data file

**Comment by deavmi** [comment]
Okay cool. Another issue closed :)
