### ISSUE TITLE
Bootstrapper nodes as relay server

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1734]

**Comment by DaniellMesquita** [comment]
Move the rest of the title as issue description

**Comment by DaniellMesquita** [comment]
About your IPv6 pull request?
Please can you resolve the conflicts with the latest ZeroNet updates?
@HelloZeroNet @shortcutme when you will review this pull request?

**Comment by tangdou1** [comment]
> About your IPv6 pull request?
> Please can you resolve the conflicts with the latest ZeroNet updates?
> @HelloZeroNet @shortcutme when you will review this pull request?

It is a small conflict, just the number of version.
If shortcutme is ready to ignore that ipv6 pull request, there will be more conflict files. Anyway, hope that ipv6 pull request can provide a little help to the future ipv6 function designed by shortcutme in zeronet.

**Comment by HelloZeroNet** [comment]
Original title: "A idea that improve current performance of connecting : based on the fact that many users are passive users, while only a few users are active users ( means having public ip), a picture or any optional file uploaded by user A(passive) can be downloaded by user B (also passive), only when a kind and active user C is willing to seed this file of user A and the user B luckly find user C through trackers. However, these active and kind users are so few compared to the number of passive users ( I would say  99.99999% of users in china is passive users). A suggestion is that the zero tracker ( bootstrapper tracker) can aslo pay a role like a relay server in software Syncthing which just help user B connect to A."

**Comment by tangdou1** [comment]
Reference 
https://github.com/ntop/n2n

**Comment by tangdou1** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/844
