### ISSUE TITLE
Limit maximum optional file size for proxies

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1735]

**Comment by HelloZeroNet** [comment]
Original Title: Suggestion: "How about adding a total maximum optional file in the side bar to limit the total size of optional file. It is very useful for the public proxy, or anyone using this public proxy (like 0net.io) can download his optional file that would quickly use up the free space of disk of that public proxy."

**Comment by HelloZeroNet** [comment]
I have added a --bigfile_size_limit to Rev3688 that allows setting a maximum file size for downloaded big files

**Comment by DaniellMesquita** [comment]
@anoadragon453 could you document `--bigfile_size_limit` and all other multiuser/zeronet CLI flags?

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme 
Multiuser settings could be on /Config page
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1759

**Comment by tangdou1** [comment]
> 
> 
> I have added a --bigfile_size_limit to Rev3688 that allows setting a maximum file size for downloaded big files

Thx for your work. But it is not my intention. My meaning is that for there should be a total optional file limit for each site.
