### ISSUE TITLE
Ability to detect when siteClone command fails

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1737]
Currently when a site issues a `siteClone`, it has no way to tell if the clone was successful for not. For instance, when using a proxy, a `siteClone` may fail because the proxy has disabled that particular command.

It would be helpful for the command to return an error message or `"ok"`, which *should* be backward compatible if I'm not mistaken as it currently does not return anything.

Thanks!

**Comment by DaniellMesquita** [comment]
Not only site clone, but also other commands.
Verify via script if:
1. It fails
2. Disabled by proxy

**Comment by HelloZeroNet** [comment]
You get error message if it's disabled by the proxy. Returning a message on successful clone is kind of pointless, because you got redirected to the new site immediately, so you won't have time to parse the message.

**Comment by HelloZeroNet** [comment]
> Page.cmd("siteClone", "1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8", console.log)
> {error: "You don't have permission to run siteClone"}

**Comment by anoadragon453** [comment]
Great, thanks!
