### ISSUE TITLE
Logrotate

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1739]
### Why?

The log files could eat up significant amount of disk space after some day of running

### How?

Create new logfile every day, only keep last 10 one.

### Plan

 - [x] Move current debug.log to debug-2018-05-25-10_25_15.log at startup and every 24 hour
 - [x] Only keep last 10 log files

**Comment by imachug** [comment]
Please, make it optional, by allowing the user to set the limit (1 day/2 days/10 days/1 month can be useful) and disable it at all.

**Comment by Thunder33345** [comment]
optional + options

**Comment by anoadragon453** [comment]
Usually logs rotate on filesize rather than time so that people know the exact max filesize the logs can be.

Then instead of multiple hours/day/month options you can just set the size in bytes.

**Comment by HelloZeroNet** [comment]
I never seen a log rotate based on size (just checked my /etc/logrotate.d and all rotates daily/monthly) and I see no reason to disable it, but the number of the kept files will be configurable

**Comment by anoadragon453** [comment]
I know systemd (journalctl) does, but after looking it up I think you're right, most things seem to go off time rotation.

You learn something new every day :D

**Comment by tangdou1** [comment]
The idea of deleting the oldest information is also useful in zeronet sites because not every one want to his or her sites become larger with time and the latest information often is the most careful for people.

**Comment by HelloZeroNet** [comment]
Added in Rev3703: https://github.com/HelloZeroNet/ZeroNet/commit/c77e403f2765c89881de7eb6e09d5127bedde931
