### ISSUE TITLE
Prevent needing to disable HTTP Cache during development

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1740]
The browser's cache unfortunately makes development difficult as it needs to be disabled, and the browser's developer tools kept open. One small trick that can be done is append a version number to the file's import to force a refresh. For example:

```
<script src="my/script.js?v=1.1"></script>
```

However updating this version number every time an edit is made is arguably even more work for site developers... unless we could automate this behavior.

If, on page load, ZeroNet would append an auto-incrementing number to each imported resource (CSS, JS) such the unix timestamp, this problem would be solved.

Would it be possible for ZeroNet to do this processing to HTML files before serving them to the browser?

As more motivation I had a friend starting ZeroNet development today and he got stuck and confused after his site wasn't updating when he changed it. Took him an hour of frustration to eventually contact me and I told him about the cache. I know it's on our docs, but people don't always check or read that far :)

**Comment by HelloZeroNet** [comment]
it would be easier to disable the cache, but it would reduce the performance

**Comment by anoadragon453** [comment]
Perhaps disable the cache in `--debug` mode?

**Comment by HelloZeroNet** [comment]
I don't think that all developers runs in debug mode, so maybe `--http_cache_owned_sites` (disabled by default)

**Comment by anoadragon453** [comment]
My only problem with this is that it doesn't seem much different than asking people to disable the cache in the developer tools.

Is it possible to only disable the cache for owned sites?

**Comment by krixano** [comment]
The main problem I have with the cache situation is that zites sometimes don't update unless the user clears the cache. We could do the whole appending version number to file name, but I think there's a better way. I think what @styromaniac proposes would be good, if possible.

**Comment by styromaniac** [comment]
Owned sites never cached + checksum versioning

**Comment by HelloZeroNet** [comment]
The resource cache is 10 minutes, so I dont think that it's really affects any, non developer user.
Adding a checksum would require constant checking of etags that makes the caching less efficient

**Comment by krixano** [comment]
I think, when a zite is updated, the client keeps track of that, and when a file is requested, it can check if it's in this array and send a no cache header

**Comment by HelloZeroNet** [comment]
The clien won't request the file if it's cached, so no point to return the no cache header

**Comment by krixano** [comment]
Right.... ech

**Comment by anoadragon453** [comment]
I vote to start with disabling cache for owned sites and iterate from there?

**Comment by krixano** [comment]
> The resource cache is 10 minutes, so I dont think that it's really affects any, non developer user.

I kinda disagree with this. If I have to get a *very* important fix out in under 10 minutes, I don't want my zite to be unusable for 10 minutes.

**Comment by styromaniac** [comment]
>Adding a checksum would require constant checking of etags that makes the caching less efficient

Relevant response below after I elaborated the thought behind it on riot.im

> So force recache when the first call from the browser after the site update?

It's this doable?

**Comment by HelloZeroNet** [comment]
i can add a {site_modified} variable that automatically got replaced with the modified value in site's root content.json and with the current time if the site is owned

so you can add it to js and css files as get paramter

**Comment by anoadragon453** [comment]
That sounds simple and elegant! I'm on board.

**Comment by styromaniac** [comment]
I know I'm kind of breaking a GitHub rule by making a comment only showing my approval, but yes, I approve.

**Comment by anoadragon453** [comment]
Awesome, thanks! I'll make sure to add it to the documentation :)
