### ISSUE TITLE
Hashes instead of site addresses on blacklists

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#1742]
To provide absolute legal immunity, allow blocklist admins to use checksums of site public key strings instead of unhashed public key strings, and have ZeroNet hash the public keys of seeded and clicked site's public keys to check against blocklists' hashes. This kind of thing had its day in court before and gladly the ruling wasn't against the favor of those who have hyperlinks to illegal content, but someday, somewhere, that could change, and that is reason enough to provide such a feature.

The idea is that with this option, site addresses are forward hashed so they aren't retrievable, reversible nor useful to visit offending sites any longer.

**Comment by styromaniac** [comment]
I'd think that some algorithms will be quite difficult to brute force, enough that it would be easier for them to find the sites themselves instead, at least, and yeah, added difficulty to reversing the hashes makes unnecessary attention less likely and makes users who seed a blocklist site feel more immune themselves. Right now, all I can do is disable hyperlinks, which doesn't stop the addresses from being accessible. That might not be enough. I imagine it's not always for the lack of knowledge how to admin a blocklist site that people don't create their own, as I've said on ZeroMe and ZeroTalk that I would offer assistance to teach how they work.

**Comment by styromaniac** [comment]
Well, so far there hadn't been any reviews made public of blocklist validity as per its stated purpose, and this would be an option to prehash site addresses. Nothing will stop people from making their own blocklist that's fully transparent, and it would be possible to validate the hashes. If for instance I put out there a whirlpool hash of the name of the lightbulb inventor's name in and say "this is a whirpool hash of the lightbulb inventor's name," then it can be verified the same as a site without any means of providing the source text, using research without the answer "Thomas Edison" provided.

**Comment by Thunder33345** [comment]
yep as mentioned previously
>someone can easily create a rainbow hash table for all "decently" known zeronet sites

basically by crawling all existing zeronet sites and produce a hash of them to be matched latter
opposed to bruteforcing it

**Comment by styromaniac** [comment]
That would be an effort that can't be pinned upon me, like if I say there's a sunken ship full of gold out there somewhere in one of the oceans, they will still be making an effort that is entirely their own to locate it.

**Comment by DaniellMesquita** [comment]
Isn't good to block content as blind, there could be innocent content that can be added to those lists

**Comment by styromaniac** [comment]
I explain above that verification is possible if titles are provided.

**Comment by DaniellMesquita** [comment]
But titles can be invented

**Comment by DaniellMesquita** [comment]
Titles can be faked?

**Comment by styromaniac** [comment]
Faked titles can't be verified.

**Comment by Thunder33345** [comment]
in it's defense, yes it can be blocked but it's more of a "warning" UI rather then straight out silently blocking it like userblocks

**Comment by styromaniac** [comment]
PornographyBlocklist is down. Food for thought.

**Comment by HelloZeroNet** [comment]
Added in Rev3734: https://github.com/HelloZeroNet/ZeroNet/commit/3923f2baf494e174ce77b6c2a0e04116635ecb7c

The hash can be calculated using `address_sha256 = "0x" + hashlib.sha256(address).hexdigest() `
