### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#176]
On this page here: http://zeronet.readthedocs.org/en/latest/help_zeronet/network_protocol/

The description for the `ping` function says `Pong` rather than `Ping`. `i` is very near to the `o` on the keyboard, so this is a typo.

**Comment by HelloZeroNet** [comment]
Its error: the response to the ping is "Pong"

**Comment by deavmi** [comment]
Oh I think I see. `Ping Pong`. ~ Very poetic. I should read the focus fully before making an error report.
