### ISSUE TITLE
PeerMessage/BackgroundProccessing plugin: Run NodeJS codes with authorization of users

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1762]
With it, ZeroNet zites can have the most advanced features from PHP servers, but with NodeJS/distributed way

**Comment by DaniellMesquita** [comment]
http://www.devengineering.com/blog/testing/run-nodejs-script-python

**Comment by HelloZeroNet** [comment]
I still don't support running third party code on client-side and I don't see why would we need to involve nodejs in it.

**Comment by DaniellMesquita** [comment]
> I still don't support running third party code on client-side and I don't see why would we need to involve nodejs in it.

Because zites are done in JavaScript, and NodeJS is JavaScript

**Comment by DaniellMesquita** [comment]
Moved: https://github.com/HelloZeroNet/Plugin-BackgroundProcessing/issues/2

**Comment by filips123** [comment]
> > I still don't support running third party code on client-side and I don't see why would we need to involve nodejs in it.
> 
> Because zites are done in JavaScript, and NodeJS is JavaScript

But zites are sandboxed and isolated. NodeJs isn't and running malicious NodeJs script can affect and damage computer.
