### ISSUE TITLE
ProgrammingError: Cannot operate on a closed database. 

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1764]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 rev3688
  * Operating system: Linux Debian
  * Web browser: Firefox
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

Hello, i am using Zeronet 0.6.4 rev3688 and when i add a search phrase (domainname.bit) to the newsfeed search field (Search in sites) on ZeroHello then my computer start lagging (non fluent scrolling, delays between applications switching) and zeronet debug.log hits following entries in rapid succession:

> Site:1HmJ7G..1fSj Error importing merged-ZeroMe/1UDbADib99KE9d3qZ87NqJF2QLTHmMkoV/data/userdb/userkeyhere/content.json: ProgrammingError: Cannot operate on a closed database. in SiteStorage.py line 151 > ContentFilterPlugin.py line 165 > SiteStorage.py line 90 > Db.py line 276 > DbCursor.py line 161 > DbCursor.py line 70

Similar issue was reported here #1665 

Can you please fix it or let me know if more information is needed?

**Comment by HelloZeroNet** [comment]
I suspect it's killing the db connection because its looks idle (killed automatically after 5min of no command executed)

Can you check if there is a line that contains "ZeroMe.db closed in" before the first appearance of that line?

**Comment by slrslr** [comment]
> Can you check if there is a line that contains "ZeroMe.db closed in" before the first appearance of that line?

Yes. In debug-last.log i found 4 lines of that kind:

> DEBUG    Db:ZeroMe /media/veracrypt1/ZeroNet/data/userkeyhere/merged-ZeroMe/ZeroMe.db closed in 0.015s, opened: 174
> DEBUG    Db:ZeroMe /media/veracrypt1/ZeroNet/data/userkeyhere/merged-ZeroMe/ZeroMe.db closed in 0.001s, opened: 111
> DEBUG    Db:ZeroMe /media/veracrypt1/ZeroNet/data/userkeyhere/merged-ZeroMe/ZeroMe.db closed in 0.001s, opened: 34
> DEBUG    Db:ZeroMe /media/veracrypt1/ZeroNet/data/userkeyhere/merged-ZeroMe/ZeroMe.db closed in 0.010s, opened: 2

before the first appearence of ProgrammingError lines mentioned above.

**Comment by HelloZeroNet** [comment]
Is any of these lines are close to the "ProgrammingError: Cannot operate on a closed database." line?

**Comment by slrslr** [comment]
No. It is not.
I visualise it:

...
...
"ZeroMe.db closed in"
7 minutes
"ProgrammingError: Cannot operate"...
"ProgrammingError: Cannot operate"...
"ProgrammingError: Cannot operate"...
6 minutes
"ZeroMe.db closed in"
...
...

there was no "ZeroMe.db closed in" between the ProgrammingErrors

**Comment by slrslr** [comment]
It appears to be fixed in recent revision, no more errors: https://github.com/HelloZeroNet/ZeroNet/issues/1665#issuecomment-436836991

**Comment by slrslr** [comment]
I seen this error again today on different, new revision 4404, WIndows 10:

> ERROR    Site:18Pfr2..pSzh WebSocket handleRequest error: ProgrammingError: Cannot operate on a closed database. in core/src/Ui/UiWebsocket.py line 79 > ... > OptionalManager/UiWebsocketPlugin.py line 163 
>  {"cmd":"optionalFileList","params":{"filter":"","address":"18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh","limit":1000},"wrapper_nonce":"somestringhere","id":5}

that site is kopykate, i tried to open [latest videos](http://127.0.0.1:43110/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/?Latest)
