### ISSUE TITLE
请问怎样才能实现网站聚合呢？

### ISSUE THREAD

**Issue by tenchu-admin** [HelloZeroNet/ZeroNet#1765]
我想建一个网站，里面分为几大模块，每个模块为独立的网站，这样方便管理，请问该怎么去实现这个网站聚合呢？谢谢！

**Comment by DaniellMesquita** [comment]
使用合并网站功能。
https://www.gitbook.com/@daniellmesquita/spaces/the-truth-about-zeronet/

**Comment by tenchu-admin** [comment]
非常感谢！！！谢谢！

**Comment by DaniellMesquita** [comment]
更多感谢 @imachug 写的。
我刚上传它作为GitBook并发送给你链接。
