### ISSUE TITLE
请问大家有没遇到过拦截跨源请求的问题？

### ISSUE THREAD

**Issue by tenchu-admin** [HelloZeroNet/ZeroNet#1767]
目前服务器已成功运行，我的首页中有个js文件，里面调用了另外一个.json文件，但在实际运行时，无法读取json数据，查看浏览器控制台发现有以下信息，不知道该如何解决，还请大家帮帮忙，万分感谢！

已拦截跨源请求：同源策略禁止读取位于 http://127.0.0.1:43110/xxx/js/xxx/xxx.json 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。

**Comment by blurHY** [comment]
Page.cmd("fileGet",["the-file-you-want"],file=>{/*code to process*/})

**Comment by blurHY** [comment]
用中文问，不太好吧

**Comment by tenchu-admin** [comment]
非常感谢！哎，实在没办法，英语太差，怕写出来都没人懂。。。再次感谢！
