### ISSUE TITLE
New ZeroNet logo

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#177]
The current logo was created in rush, some first ideas for new one:
![zeronet_logos](https://cloud.githubusercontent.com/assets/10350359/10103145/ac9cc8a6-63a2-11e5-9e2b-b35efec37a32.png)

Which one do you like? Other designs also welcome.

**Comment by bashrc** [comment]
Second one.

**Comment by zacharycp** [comment]
They all look great but the center top is my favorite.

**Comment by SkyzohKeyx** [comment]
The 2nd one is beautiful !

**Comment by Idealcoder** [comment]
I like the second one. My only question would be how good it looks as a
small 16x16 icon ( for taskbar icon etc. ) as I'm not sure if the shadows
and gradients would work at that size

**Comment by HelloZeroNet** [comment]
In smaller sizes it can be simplified:
![zeronet_favicon_smooth](https://cloud.githubusercontent.com/assets/10350359/10117719/4162b6b8-6460-11e5-8e48-9466bf6dac73.png)

**Comment by HelloZeroNet** [comment]
with 45° rotation:
![45](https://cloud.githubusercontent.com/assets/10350359/10117880/28ef3d84-6467-11e5-8f18-5050e13ad10a.png)

**Comment by s0r00t** [comment]
2nd one master race!

**Comment by ThomasdenH** [comment]
I still like the second one without rotation the best.

**Comment by SkyzohKey** [comment]
same as my up neighbors ;)

**Comment by dobrosketchkun** [comment]
Second and fourth

**Comment by makdisse** [comment]
2nd without rotation is the best!
ps: amazing how you manage to be a capable designer and developer at the
same time!

**Comment by TheNain38** [comment]
2nd without rotation

**Comment by sbDevGit** [comment]
first one

**Comment by HelloZeroNet** [comment]
a more lightweight idea:
![logo2](https://cloud.githubusercontent.com/assets/10350359/10891948/1e7cd21a-81a1-11e5-8658-4cb62b8c7dfe.png)

**Comment by almet** [comment]
We probably should close this :)
