### ISSUE TITLE
Community Themes

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#1771]
I would have fun creating themes for sites if this were made easy to understand what affects what like a live editor, without the possibility of losing changes if themes are switched or sites update. Users don't have to even trust me with a file I could change from my own site, but just copy CSS code they can preview by reading first, paste into an input box with a live preview, give it a name, and apply changes, being able to switch themes from ZeroHello. Something like that, anyway. Allow the user to set a fallback theme if a site doesn't have a theme under the name of the preferred theme.

I'm thinking a site just for sharing, searching and favoriting themes might be neat too. Think of it like how you can already do this for Firefox, but for individual sites.

**Comment by HelloZeroNet** [comment]
I think its out of scope of ZeroNet, but there is a site for that: https://userstyles.org/
