### ISSUE TITLE
A request for port to haiku os.

### ISSUE THREAD

**Issue by skarmiglione** [HelloZeroNet/ZeroNet#1775]
### Step 1: Please describe your environment
Can you please add a option to get ZeroNet working on haiku Os please, i am bigfan of the two 
initiatives.
But Haiku es a great Operating systema and there are other big good apps too, is a good way to propagate this initiative in people who love the risk in the testing. 

  * Operating system: _____ Haiku Os
  * Web browser: _____ WebPositive
  * Tor status: not available/always/disabled : Disabled
  * Opened port: yes/no    no
  * Special configuration: ____ It is not ported to haiku yet
 
There are a lot of librarys but i am not programer then i just get frustrated in that wish.

**Comment by krixano** [comment]
I would like this a lot. I was able to get some of the libraries installed (msgpack and I think a few others), **except** for gevent, because it uses libev (or libuv) which hasn't been ported to haiku yet. I believe HaikuPorts is working on porting one of these (I think libuv).

**Comment by GatoAmarilloBicolor** [comment]
I did ported it now, helped by someone there, was easy, now Haiku OS is working. 

![image](https://user-images.githubusercontent.com/12539219/87907914-1f8d9b80-ca2b-11ea-8e3f-b5ae0037bde1.png)

Thanks
