### ISSUE TITLE
Provide a function for when site_info has been resolved

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1777]
Consider the following example:

```
class ZeroApp extends ZeroFrame {
  onOpenWebsocket() {
    zeroframe.cmd("wrapperSetLocalStorage", {"score": 500}, null);
  }
}

zeroapp = new ZeroApp()
```

If one runs this, they get `TypeError: this.site_info is null`. That is because even though the Websocket has been opened, (I assume) the ZeroNet daemon has not yet returned `site_info` to the UiWrapper.

While this is just a toy example, I have run into problems with this on ZeroLSTN, often needing to use the following trick just to ensure `site_info` has been loaded before performing some tasks:

```
class ZeroApp extends ZeroFrame {
  onOpenWebsocket() {
    setTimeout(() => {
      zeroframe.cmd("wrapperSetLocalStorage", {"score": 500}, null);
    }, 50);
  }
}

zeroapp = new ZeroApp()
```

`site_info` was resolved, but we potentially lost a few ms in the process.

Is it possible to provide a `ready()` function, either one that can be overridden or one that is run when `site_info` has been retrieved. It could even work like the following:

```
const zeroframe = new ZeroFrame();

zeroframe.onReady = function() {
  console.log("Ready!");
}
```

**Comment by HelloZeroNet** [comment]
Actually it was a bug and it's fixed in Rev3704 https://github.com/HelloZeroNet/ZeroNet/commit/06fbcde81578db1db1139ee0d3ee8f3bc522157c

**Comment by anoadragon453** [comment]
Ohh, no way. Wonderful! I'll update the docs accordingly.
