### ISSUE TITLE
update.py was emptied when i ran it while computer was out of disk space

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1779]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4
  * Operating system: Linux debian
  * Web browser: FF

### Step 2: Describe the problem:

Hello,

apparently Zeronet on my Linux failed because i ran out of disk space, but i have not spotted it and tried to restart/update zeronet, but it failed and when starting ZN again, i seen:

> - Starting ZeroNet...
> [16:32:32] - Unhandled exception: 'module' object has no attribute 'openLocked'
> Traceback (most recent call last):
>   File "/home/lynx/Apps/ZeroBundle/ZeroNet/zeronet.py", line 18, in main
>     import main
>   File "/home/lynx/Apps/ZeroBundle/ZeroNet/src/main.py", line 48, in <module>
>     lock = helper.openLocked("%s/lock.pid" % config.data_dir, "w")
> AttributeError: 'module' object has no attribute 'openLocked'

The zeronet.py starting line 18 was about updater, and i found update.py file is empty. It is strange it was emptied, though out of disk space is my fault that brings bad consequences. I had updater.py backup form my Windows PC so i copied it over and ZN updated and starting good.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme
