### ISSUE TITLE
Shutdown via GUI

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#178]
I think I nice feature would be to have on the home-screen `ZeroHello` two buttons at the top of the screen that can 1. restart the client and 2. shutdown the client.

**Comment by HelloZeroNet** [comment]
You can use the taskbar icon to shutdown: right click > exit

**Comment by deavmi** [comment]
But what if you are running your own private proxy and need to restart the ZeroNet client? I think this would be a great function.

**Comment by Idealcoder** [comment]
If you were running it as a private proxy surely you would want it to run
24x7 anyway?

**Comment by deavmi** [comment]
I might be running low on bandwidth on my port forwarded router, hence I do not want it to always be running.
