### ISSUE TITLE
Don't delete optional files on owned sites

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#1788]
Optional files from one of my own sites seem to have gone missing. I noticed this a while after my drive ran out of space, so I'm thinking Zeronet may have cleaned up optional files from my own site to create space. Is this possible? Would 'help distribute all files' on my own site stop this if that is indeed the case?

from http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1543189245_1GDcCK6cWoj98mg541Yj9rW1nwXcBz87eE

**Comment by styromaniac** [comment]
I think this happened to me before.

**Comment by slrslr** [comment]
recent problem with site files spotted, but possibly not related: #1790

**Comment by HelloZeroNet** [comment]
Added in Rev3734: https://github.com/HelloZeroNet/ZeroNet/commit/0157ade1c9149f6bc9fca46825eb55f94a854460
