### ISSUE TITLE
HTML File Indexing

### ISSUE THREAD

**Issue by deavmi** [HelloZeroNet/ZeroNet#179]
It would be nice to have a new module that can be used for hosting files or just a new feature to ZeroNet that indexes sites with no `index.html` file.

**Comment by deavmi** [comment]
Should I keep this open? Do you think this would be a helpful feature? Anyone? @HelloZeroNet

**Comment by wigy-opensource-developer** [comment]
If you just want to seed a folder, bittorent is your friend. If you only want to use the "torrent folder that can be changed" feature of ZeroNet and ignore the user interface and database features, someone could create a ZeroNet site for that without touching the core functionality. Or maybe this zite will solve your use-case: http://127.0.0.1:43110/1GrtBsG57kjU2Z3iAQebG9D5c8CRDRLoPj/

**Comment by deavmi** [comment]
You can close this I guess. I don't need to have this feature. I can 
just index stuff by myself.
