### ISSUE TITLE
Latest rev3728 fails to sign the content

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1790]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 rev3728
  * Operating system: Windows 7 64bit
  * Web browser: Firefox 63
  * Tor status: avail.
  * Opened port: no
  * Special configuration:
data_dir = D:\ZeroNet\data
trackers_file = data/1JuwWYEgApiBVNyGxhvNYyohsv4YMtxy7M/trackers_all.txt
#tor = disable
fileserver_port = ***
language = en
optional_limit = 150
multiuser_local

### Step 2: Describe the problem:

Hello, this MAY be an important problem in latest revision. Please read on [here](http://127.0.0.1:43110/Me.zeronetwork.bit/?Post/1SunAWK2VUT9GQK32MpwRfFPVgcBSJN9a/17zoTjVZEBUdo6uAvQvtbih7ibBMHQRsrH/1543230590). Search on that page for: "Hi, this is possibly another mistery" (may need a bit of scrolling).

Summary: in latest revision on Windows when user sign his site, it do not add site files into content.json saying in debug.log: [ERROR] Invalid filename: pathtositefile
On dynamic site like zerotalk, user new content or updates do not gets propagated (or it propagates nothing?) and old content possibly gets removed.
On old ZN revision (0.6.3 rev3576), the issue is not there. Please kindly can anyone verify on Windows whether own site signing works and main site content.json contains files of the site?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in Rev3729: https://github.com/HelloZeroNet/ZeroNet/commit/e4352743293b24112cfaaf875648b5a46d4104a6#diff-8fddfd9ebb27329fde8fa7eb72e7f796

The problem was with the win-style data_dir configuration value. (I think it also affected earlier versions of ZeroNet)

**Comment by slrslr** [comment]
So it affected only Windows users who are using data_dir config. option in their zeronet.conf or as a parameter of ZeroNet.exe?
If these users "recently" published some content on their or anyone elses site, then all their content was de-published from sites and they need to update zeronet and again visit all sites where they published some changes in order their content gets again propagated to other peers? Thank you for the fix.

**Comment by HelloZeroNet** [comment]
Yes, only affected users who had "\" character in --data_dir value and making some changes should work as republishing the content
