### ISSUE TITLE
Can not use urllib in ZeroNet plugin

### ISSUE THREAD

**Issue by 0polar** [HelloZeroNet/ZeroNet#1795]
When I writing plugin:

```py
import urllib2
from Plugin import PluginManager

@PluginManager.registerTo("UiRequest")
class UiRequestPlugin(object):
	def actionWrapper(self, path, extra_headers=None):
		return urllib2.urlopen("http://localhost").read()
```
I meet `BadStatusLine` error
When I change `http://localhost` to `http://example.com`, it won't throw error, but it will stuck in loading.

----

There are must some monkey patch that I don't know.
Any help?

**Comment by HelloZeroNet** [comment]
You can use the example from the Sidebar plugin: https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/Sidebar/SidebarPlugin.py#L571

**Comment by 0polar** [comment]
Not helpful.
It still throw `IOError: ('http protocol error', 0, 'got a bad status line', None)`
And your [helper](https://github.com/HelloZeroNet/ZeroNet/blob/f0f9b93694b8df6515c8f73c52a0d05b39a61ce9/src/util/helper.py#L152) is just for SSL, does not affect normal HTTP.
May you need try my code for yourself.

**Comment by HelloZeroNet** [comment]
Are you sure the server is working properly?
Does `python -c "import urllib2; print urllib2.urlopen('http://localhost').read()"` works?

**Comment by 0polar** [comment]
It works in terminal, but it not work in ZeroNet plugin.
Previously I try this in my Windows desktop, now I try again in new Debian VPS, it throw `IOError: [Errno socket error] [Errno 111] Connection refused`

**Comment by 0polar** [comment]
It works in terminal, but it not work in ZeroNet plugin.

Previously I try this in my Windows desktop, now I try again in new Debian VPS, it show log
`[15:04:07] - UiWSGIHandler error: AttributeError: 'UiWSGIHandler' object has no attribute 'code' in UiServer.py line 40 > pywsgi.py line 495 > pywsgi.py line 486 > pywsgi.py line 372` and browser page stuck in loading.
