### ISSUE TITLE
Websocket connection with HTTP_HOST "127.0.0.1" denied access

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#1799]
Trying to make a websocket connection from Godot to ZeroNet fails by default as the `HTTP_HOST` env property of the connection is `127.0.0.1` instead of `127.0.0.1:43110`. This is likely an issue on Godot's websocket library side, but would adding `127.0.0.1` and `localhost` to the list of default allowed hosts be a problem in any way?

As a reminder, the current default values are `zero`, `127.0.0.1:zeronet_port` and `localhost:zeronet_port`.

**Comment by HelloZeroNet** [comment]
Actually I think we could white-list any ip address as dns rebinding attacks is only affects domain names

**Comment by anoadragon453** [comment]
Oh, ok, I shall make a PR for that then.
