### ISSUE TITLE
Top level URL doesn't show URL of iframe

### ISSUE THREAD

**Issue by doublec** [HelloZeroNet/ZeroNet#18]
When navigating a ZeroNet site the top URL in the browser doesn't change. It stays as the address for the top level of the site. This makes creating internal links to sites in ZeroNet difficult.

You can right click on a link and copy/paste it. But this leaves the "/media" path in the URL and when you visit it it displays at the top level, not in the iframe with the Websocket magic around it.

Would it be possible to change the top level URL when navigating? Maybe using a fragment identifier that the top level JS parses to navigate the iframe?

**Comment by HelloZeroNet** [comment]
you can use <a href="/13TSUryi4GhHVQYKoRvRNgok9q8KsMLncq/2015/01/15/decentralized-websites-with-zeronet.html" target="_top">Some link</a>

**Comment by doublec** [comment]
I'm meaning more in the case of a user browsing a site wanting to get a link to share.  They can't copy/paste the URL in the browser because it stays as the top of the site and doesn't change. If they copy the URL of a page or link on a page they get the '/media/...' link which they have to edit.

**Comment by HelloZeroNet** [comment]
If you add target="_top" it will change the browser bar url
