### ISSUE TITLE
In `user_contents`, what the different between `archived`, `archived_before`, `permission_rules`?

### ISSUE THREAD

**Issue by 0polar** [HelloZeroNet/ZeroNet#1803]
They are all looks for banning someone, but I need more detail.

In https://zeronet.io/docs/site_development/content_json/#user_contents , I didn't find `archived`, `archived_before`, you need to update the docs.

**Comment by HelloZeroNet** [comment]
The difference is if you add a directory name in the user_contents/archived node with a future date, then it will be deleted in all computer immediately and won't allow to create it again until the specified date. 
If you add it to permissions node, then it won't delete it, but it will not allow any more updates from the user (but the site owner can change it).

The archived_before is the same as archived, but it will be applied to all users. So if you add `"archived_before": 1523088096`, then it will delete all user directories that has "modified" value earlier than 1523088096 in content.json
