### ISSUE TITLE
Certificateless accounts

### ISSUE THREAD

**Issue by Thunder33345** [HelloZeroNet/ZeroNet#1812]
Basically another type of account that can be generated on demand without any involvement of certificate authority or public free floating certificate.

This type of account has no "domain" unlike normal certs generated id that have @zeroid.bit for example.
This type of account CANNOT be assigned a username, username is based on the public key of the address, though you could use POW to get certain prefix/suffix.

There's only `auth_address` and `auth_privatekey` for this kind of account, maybe a custom nick+note for user to not get confused over which is for what.
Users can have as many accounts of this type as they want in one master seed.

# why?

this enforces a true unique name and also allow privacy oriented sites to allow this kind of id without compromise of users sharing the same names to impersonate others, while remained decentralized.

# implications

since this "id" have no suffix of @... unlike every other id, this might be a bad idea as it would be hard to "permission" it, for example how would we "allow" it?
using cert_signers wont wont because it has no suffix and nor a public key,
and to say set it with a differing amount of "space" it wouldn't be possible to directly target it

Possible proposal to rectify this would be to append @selfsign(or something), to the end of it when in programmatic operation and choose to omit it when displaying to end users, basically it's only there for operations like cert_signers and permissions, and only there when it's necessary. seems hacky solution though

Since the username is a blob of huge string of character,
there should be a unique icon gen(with high entropy) using public key to prevent impersonating,
since it's long it could be trucened if user wish so to be like first1234567...last123

It's possible that these kind of account would make it more easier to "spam" sites, but that's ultimately up to site owner's discretion to support this or not, not like free float private keys of cert authorities dosent exist already

**Comment by HelloZeroNet** [comment]
you can already create self-signed certificates in the browser, which is same as you described.

**Comment by trenta3** [comment]
You can see Nanasi text board
http://127.0.0.1:43110/16KzwuSAjFnivNimSHuRdPrYd1pNPhuHqN/ to see it
implemented.
Basically each user creates a certificate in the browser and can then use
it to sign messages.

Il giorno lun 10 dic 2018 alle ore 12:15 ZeroNet <notifications@github.com>
ha scritto:

**Comment by Thunder33345** [comment]
@HelloZeroNet @trenta3 i think you glossed over this important point
> This type of account CANNOT be assigned a username, username is based on the public key of the address, 
> this enforces a true unique name and also allow privacy oriented sites to allow this kind of id without compromise of users sharing the same names.

while yes you can create a self signed cert but you cannot allow self signed certs without enforcing user names
removing the capability of users choosing their name is a way "negate" that
it also resolves the "everyone uses different self signer services" 'problem'

**Comment by trenta3** [comment]
@Thunder33345 In your site you could choose to not display `cert_user_id`, but show the `auth_address` instead. This way `cert_user_id` would not have any significance in the displayed text.

While this could be enforced by the backend, it is already doable.

**Comment by Thunder33345** [comment]
i guess this is actually doable, why make that if something else works
i think thought too much about some way to fully ditch the whole certs and signing without thinking about that point (personally i hated it and despised it, it's like the only centralized thing that will screw over the whole decentralized system, but that is a rant for another day)

for the "too many self sign certs", who cares i guess who did anyways? 
¯\\_\(ツ\)\_\/¯

for the multiple usernames thing
>Users can have as many accounts of this type as they want in one master seed.

i will consider that to be resolved under #1813 

i shall consider this this closed then, maybe another day...

**Comment by trenta3** [comment]
> i guess this is actually doable, why make that if something else works [...]
> for the "too many self sign certs", who cares i guess who did anyways?
> ¯\_(ツ)_/¯

You seem a little bit ironic in your reply. If there is something that enhances ZeroNet and that is not already provided I'm with you, but you should explain it clearly. On the other hand, the way of thinking "this is doable, don't make it because something else works" is actually useful to keep ZeroNet core code as small as possible (it helps readability, vulnerability analysis, etc.).

If I sounded rude before, please excuse me.
I write here just to add my two cents (this time to signal an existing implementation from which to learn), and the one who really decides what gets implemented at the end is @HelloZeroNet

**Comment by Thunder33345** [comment]
sorry for my tone, i dont really like the cert system, but everything you said perfectly countered my points.
dont like usernames? use their auth address at frontend and everything is solved

>On the other hand, the way of thinking "this is doable, don't make it because something else works" is actually useful to keep ZeroNet core code as small as possible (it helps readability, vulnerability analysis, etc.).

and yeah no need to spend work on such if it already can already be accomplished(considering it's also a one man dev)

the "maybe another day" is referring to maybe ill somehow think of another reason in the future that makes this worth revisiting

**Comment by krixano** [comment]
The **user** should have the choice of not using a username. This isn't currently possible, as it's the site/site owner's choice.

However, this will break many zites unless each zite checks for a null cert_user_id and replaces it with auth_address in that case.

**Comment by Thunder33345** [comment]
> The user should have the choice of not using a username. This isn't currently possible, as it's the site/site owner's choice.
> 
> However, this will break many zites unless each zite checks for a null cert_user_id and replaces it with auth_address in that case.

That's good point, maybe something like pollyfill username to be auth address?
I think it's a double edged sword as this introduce more unexpected behavior rather than failing fast and hard for devs to fix...

> Additionally, there should be a way of more quickly creating new id's/certificates as well as a way for site owners to determine whether anonymous certs are accepted.
>
>The problem with self-signing certificate authorities (kaffieid and any future ones) is that the site must accept each one. Instead, the site should be able to say whether anonymous certs are accepted or not, then all certs that are self-signed should be accepted.

I think this is more of a "minor" problem rather than a critical one, yeah now owner has to find out all the possible self signing certs to add them, and users have to hold bunch of certs from different provider.
Though i would be glad to be able to see all self signing begin unified into one simple "thing".

>I also think sites should be able to restrict what these "anonymous" self-signed certs can do, which means we need a way of introducing this concept into the permissions stuff in content.json files.

like what kind of "options" do you think so that should be valid??
we have file size rules, we could splice files into multiple jsons files, like votes, comments, posts
and set anonymous ids to have 0 vote size etc

**Comment by Thunder33345** [comment]
wouldnt that be userid@1powcertprovider?
and user would need to pull a new one from thin air to keep it anonymous
but i guess this makes things way easier to be done so +1
