### ISSUE TITLE
UpnpError: Failed to communicate with igd using port 43254 on local machine after 3 tries.

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1824]
Version: 0.6.4 r3728, Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)], Gevent: 1.3.7
Windows10

**Comment by blurHY** [comment]
Why qbittorrent works on the same computer

**Comment by HelloZeroNet** [comment]
Probably it using different algorithm to communicate with the router.
