### ISSUE TITLE
Why not use the project board ?

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1826]

**Comment by grez911** [comment]
Just to explain your message: https://help.github.com/articles/about-project-boards/

**Comment by HelloZeroNet** [comment]
I feel this a bit overlaps with the issues. Have you seen a project actively using this feature?

**Comment by skwerlman** [comment]
i think the main goal of that feature is to provide context for issues by making it clearer what issues are at what stage (i.e. in discussion, being worked on, testing, etc)

**Comment by parkour86** [comment]
The bootstrap github page uses the project board for tracking feature requests and bugs. It does overlap with the issues tab but I think it would help organize them better.
https://github.com/twbs/bootstrap

**Comment by blurHY** [comment]
@HelloZeroNet Please add todos.For example,bug fix.
