### ISSUE TITLE
fileQuery produce error

### ISSUE THREAD

**Issue by MingchenZhang** [HelloZeroNet/ZeroNet#1827]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 rev3729
  * Operating system: windows 10
  * Web browser: firefox
  * Tor status: says available
  * Opened port: yes
  * Special configuration: no

### Step 2: Describe the problem:
site execute "this.cmd('fileQuery', {dir_inner_path:'content.json', query: 'address'}, console.log)" cause the following error to appear as notification
`Internal error: TypeError: 'unicode' object does not support item assignment`
`UiWebsocket.py line 82 > UiWebsocket.py line 266 > UiWebsocket.py line 648 > QueryJson.py line 58`

#### Steps to reproduce:

  1. create new empty site 
  2. add previous line in onOpenWebsocket
  3. open the site page

#### Observed Results:
no result returned, but an error shows up

#### Expected Results:
show the address of the current site?

I understand it is not a recommended API, but it is a bug nonetheless.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, Fixed in Rev3748: https://github.com/HelloZeroNet/ZeroNet/commit/4c675b83117ec18b3df4eaad877d8cc1b28de585
