### ISSUE TITLE
UiServer.py error after update

### ISSUE THREAD

**Issue by YSHZdive** [HelloZeroNet/ZeroNet#1828]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 rev3741
  * Operating system: windows 8.1
  * Web browser: firefox
  * Tor status: says available
  * Opened port: no
  * Special configuration: no

### Step 2: Describe the problem:
`Err: AttributeError: 'module' object has no attribute 'inet_pton' in UiServer.py line 106 > UiRequest.py line 112 > UiRequest.py line 87 > UiRequest.py line 67`
#### Steps to reproduce:

  1. open 127.1.0.0:43110 after update

#### Observed Results:

no result returned, but an error shows up

#### Expected Results:

show the main page

**Comment by imachug** [comment]
What is your Python version? Are you using bundled version?

**Comment by YSHZdive** [comment]
Python version - 2.7, bundled.
