### ISSUE TITLE
Default path in users directory

### ISSUE THREAD

**Issue by RemiZOffAlex** [HelloZeroNet/ZeroNet#1834]
In file src/Config.py line 50

```Python
start_dir = os.path.expanduser("~/Library/Application Support/ZeroNet").decode(sys.getfilesystemencoding())
```

Directories in home dir users is match with created user. This is be to ~/.library or other [dot]DIRNAME. Linux system auto hide directory beginning dot.

**Comment by HelloZeroNet** [comment]
"~/Library/Application Support/ZeroNet" is only used in MacOS client to store the data as /Application is not writeable
