### ISSUE TITLE
[Plugin propose] Converter (or ScriptEcho)

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1835]
There are lots of platforms where ZeroNet could be powering: Ethereum, Cordova, Electron.
But every of them needs their own plugin, to translate/convert/re-pass the API from iFrame and echo on the main frame.
But there could be a plugin to take selected scripts type to be copied and work on the main frame. This plugin could be modular, having scripts (acting like sub-plugins) with instructions about which type of JS should be converted to work on main frame (those sub-plugins/scripts can be Ethereum, Cordova, Electron, etc).
Also, this plugin could convert LocalStorage scripts to work on the main frame as ZeroFrame's LocalStorage.
@imachug @rllola please share your thoughts

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
Please add more details and example use cases.

**Comment by DaniellMesquita** [comment]
> Please add more details and example use cases.

The first comment already haves details and example use cases.

## Current problems and use cases
Right now, ZeroNet sites can't use Cordova/Electron APIs inside an app built with those frameworks (because Cordova/Electron script calls will come from an iframe).
Same for Ethereum: an ZeroNet site can't communicate with MetaMask (browser extension) because the Ethereum script calls come from an iframe.

## Solution through a plugin
Plugin to take selected scripts type to be copied and work on the main frame. This plugin could be modular, having scripts (acting like sub-plugins) with instructions about which type of JS should be converted to work on main frame (like permissions, accepting only specific JS calls - those sub-plugins/scripts can be Ethereum, Cordova, Electron, etc). Every module from this plugin will contain the accepted JS calls.

**Comment by HelloZeroNet** [comment]
I'm not sure how does these plugins works, but you can add NOSANDBOX property to the site which is disables the sandboxing and you can reach the namespace by window.top

**Comment by DaniellMesquita** [comment]
> I'm not sure how does these plugins works

There isn't an already existing plugin about that; that's clearly an suggestion.

> but you can add NOSANDBOX property to the site which is disables the sandboxing and you can reach the namespace by window.top

That is bad.
And getting rid of iframe is better and less complex than creating that plugin.
