### ISSUE TITLE
Electron: Instead of pointing to an index.html, point to a ZN address

### ISSUE THREAD

**Issue by DaniellMesquita** [HelloZeroNet/ZeroNet#1837]
I'd tried that on 2017, but it shows a error message, something about CORS.
How can ZN sites work through NWjs/Electron?

**Comment by HelloZeroNet** [comment]
Not sure what you mean, can you please explain?

**Comment by DaniellMesquita** [comment]
@HelloZeroNet
Well, Cordova/NWjs/Electron apps points to an .html file to be its UI.
On case of ZeroNet, those native app frameworks could point to an ZN address (HTTP) instead of an local HTML.

**Comment by HelloZeroNet** [comment]
I neved tried these apps, but you can load http in electron: https://electronjs.org/docs/api/browser-window
