### ISSUE TITLE
怎样分发新站点

### ISSUE THREAD

**Issue by Wings-Fantasy** [HelloZeroNet/ZeroNet#1839]
我创建了一个网站，写好了源代码，使用分发命令的时候提示我没有用户。
当然会没有用户啊，这是一个新网站，节点数一定只有我一个啊。
看官方的手册，那条命令是分发给其他节点。我这里没有其他节点，新网站怎么发布？

**Comment by blurHY** [comment]
让别人访问你的网站就行

**Comment by Wings-Fantasy** [comment]
我电脑是内网，开不了端口

**Comment by blurHY** [comment]
应该是不影响的。

**Comment by tangdou1** [comment]
通过 0net.io 等公共代理帮你做种

**Comment by tangdou1** [comment]
it can be closed.
