### ISSUE TITLE
Err: TypeError: sha256() argument 1 must be string or buffer, not None in UiServer.py ...

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1846]
### Step 1: Please describe your environment

  * ZeroNet version: 3746
  * Operating system: Windows
  * Web browser: Firefox

### Step 2: Describe the problem:

On page
http://127.0.0.1:43110/pmontesa.bit

I see an error:
Err: TypeError: sha256() argument 1 must be string or buffer, not None in UiServer.py line 106 > UiRequest.py line 158 > UiConfigPlugin.py line 21 > MultiuserPlugin.py line 56 > ContentFilterPlugin.py line 191

full details [here](https://pastebin.com/6WACTVTZ)

Is this site misconfigured or is that Zeronet issue? If it is site issue, can this be somehow indicated in error so i do not submit bug reports here?

Thank you

**Comment by HelloZeroNet** [comment]
The domain name does not exsits: https://namecha.in/name/d/pmontesa

but the displayed error is still a problem

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in Rev3748: https://github.com/HelloZeroNet/ZeroNet/commit/4c675b83117ec18b3df4eaad877d8cc1b28de585
