### ISSUE TITLE
Automatically update trackerlist from a github repo

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1852]

**Comment by HelloZeroNet** [comment]
The list got updated on from github/zeronet on update, but these trackers became less important since the announceshare plugin, that updates the list of trackers continusly

**Comment by blurHY** [comment]
Peers are much fewer than several months ago in China.Maybe the gov blocked more trackers

**Comment by DaniellMesquita** [comment]
@blurHY
> Peers are much fewer than several months ago in China.Maybe the gov blocked more trackers

Do you have friends on that country?

**Comment by blurHY** [comment]
Yeah

**Comment by tangdou1** [comment]
> Do you have friends on that country?

because he is also chinese. hahaha...

**Comment by DaniellMesquita** [comment]
> I did reviewd and currently working on ipv6 support based on that

You should merge the commits and modify on base of it, to credit the efforts of @tangdou1

**Comment by DaniellMesquita** [comment]
> If you too care about an free Internet on your country, and on this case needs more trackers, I ask both you to buy pendrives/SD cards and distribute copies of ZeroNet that is already with bootstrapper plugin (for trackers - needs fixed IP) and some useful sites pre-downloaded.
> Also, @tangdou1 , instead of quoting me on jokes, better if you would mention @HelloZeroNet @shortcutme to review your IPv6 pull request

@blurHY 
On the case of IPv6 is implemented, no need to have fixed IP address for IPv6 trackers when using CJDNS
