### ISSUE TITLE
Error loading trackers file: [Errno 2] No such file or directory: './data....

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1853]
### Step 1: Please describe your environment

  * ZeroNet version: 3750
  * Operating system: Linux Debian
  * Web browser: Firefox
  * Tor status: error

### Step 2: Describe the problem:

Hello, after i added: data/1Q9LrWv27gyToaqDXA2GF2ZSA6PhznX7z1/data/trackers_all.txt
into: "Trackers files" field
on page: http://127.0.0.1:43110/Config/
and saved, then restarted zeronet

during launchg on this Linux Debian PC i see numerous errors:

Error loading trackers file: [Errno 2] No such file or directory: './data/1Q9LrWv27gyToaqDXA2GF2ZSA6PhznX7z1/data/trackers_all.txt'

I made sure to visit that zite, but errors still appears.

i am not sure why zeronet is prepending ./ before the path

i am launching zeronet by calling default zeronet script /home/myname/ZeroBundle/ZeroNet.sh

zeronet.conf contains:
trackers_file = data/1Q9LrWv27gyToaqDXA2GF2ZSA6PhznX7z1/data/trackers_all.txt

**Comment by slrslr** [comment]
i forgot to mention that my data folder is located on different mount point than my zeronet.py

zeronet.conf:
data_dir = /media/abc/ZeroNet/data

while i am launching /home/myname/ZeroBundle/ZeroNet.sh

**Comment by HelloZeroNet** [comment]
The trackers file is relative to ZeroNet.sh, so I recommend to add a synlink of /media/abc/ZeroNet/data to data dir to that directory

**Comment by slrslr** [comment]
I see, though it may be better if zeronet detect right path based on zeronet.conf (if it contains data_dir variable or no), people share trackers lists like this:
data/../../file.txt
and if one have relocated data dir, he may miss the silent errors (mentioned in this issue) if he use Windows.
