### ISSUE TITLE
A Port Scanner and Automatic Open Port Selection Mode Built Into ZeroNet Would Be A Life Saver

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#1857]
It's becoming my go-to thing to scan for ports for ZeroNet to use, and port scanners have gotten me where I needed to experience ZeroNet at full speed.

This would be a good thing to put before new users to try instead of digging into router settings, especially when some routers aren't that functional (UPNP doesn't work on the PoS modem/router combo I'm renting even though it's a listed feature) or they don't have admin privileges to make changes there, plus going into router settings is only excessive work if there's already a TCP port open. Port scanners remove a lot of steps and trouble.

"So why not just stick with port scanner apps?"

That's not the point. This is something that probably only I had discovered out of ZeroNet's entire population, and better than making a post on ZeroTalk that would get buried is to present this as a native feature to ZeroNet, and selecting the port automatically if the user prefers.

It's as important as the UPNP port puncher.

**Comment by HelloZeroNet** [comment]
You mean try to bind and test connecting from outside every port between 1000-65535?

**Comment by styromaniac** [comment]
I use this to scan open ports. Hopefully the code is commented well enough.

https://github.com/stealthcopter/AndroidNetworkTools

If ZeroNet can do that, more people will get the most out of ZeroNet in a very simple way.

**Comment by rllola** [comment]
I like the idea and I believe it can be quite useful. Also port scanning in python is really easy to implement.

You can use something scapy if you are lazy : https://scapy.net/

**Comment by HelloZeroNet** [comment]
I still don't fully understand how would it work, what ip and ports do you scan with it?

**Comment by rllola** [comment]
If I understand it well, the idea would be to have a plugin that would replace Port Checker (https://portchecker.co/) and scan your ip address for an open port and will choose this one for Zeronet.

Quite often UPnP doesn't work for me neither and I am working from cafe/hotel/house so I don't have access to the router settings.

Another option would be port forwarding ? Can we do that ?

I really don't know much about network.

**Comment by HelloZeroNet** [comment]
Yeah Upnp support in public places are very rare, but I don't think that routers will forward random ports to you internal ip address. So I still don't see how is this improve the situation.

**Comment by rllola** [comment]
> Yeah Upnp support in public places are very rare, but I don't think that routers will forward random ports to you internal ip address. So I still don't see how is this improve the situation.

Yeah I just realize that you have map to your internal ip address so it will not work.

**Comment by rllola** [comment]
@HelloZeroNet Can we do port forwarding somehow ? Again I am not entirely sure how it would work but could it bypass the router restriction ?

**Comment by duckartes** [comment]
Hidden sites on Tor ignore port restrictions, as far as I've experienced :)

**Comment by styromaniac** [comment]
Huh? I find open ports in the wild.

I don't have access to my OWN router even, because this router has a bug that locks out the admin just for overriding DNS settings.

It also worked at the library.

I believe you have to scan the gateway for open ports.

**Comment by HelloZeroNet** [comment]
You may find open ports, but it's useless if the incoming connections are not forwarded to your machine.

**Comment by styromaniac** [comment]
But I don't have any port forwarded from my router to my phone.

**Comment by styromaniac** [comment]
https://play.google.com/store/apps/details?id=threads.server

This, like the port scanner I linked, is finding the open ports on my router. 4001 and 5001.

**Comment by styromaniac** [comment]
Suggest those ports to the user and any likely candidates to work out. Or... make a list showing the IP addresses and port numbers of other nodes.

**Comment by styromaniac** [comment]
I'm closing this issue because it looks like ZeroNet is finding open ports or successfully port punching now. The port was randomly selected, yet it's open and I'm running a tracker.
