### ISSUE TITLE
Problems on Arch Linux

### ISSUE THREAD

**Issue by DoctorJellyface** [HelloZeroNet/ZeroNet#187]
(I have used the AUR package, but that shouldn't change anything)

Hey. So I wanted to try out zeronet, but after installing it I found out that there's `#!/usr/bin/env python` at the start of the scripts, which default to Python 3 on Arch Linux, resulting in a while bunch of error. Any idea how to fix it without `sed`ing?

Thanks.

**Comment by HelloZeroNet** [comment]
You can start it using `python2 zeronet.py`

**Comment by DoctorJellyface** [comment]
```
$ python2 /usr/bin/zeronet.py
- Starting ZeroNet...
Traceback (most recent call last):
  File "/usr/bin/zeronet.py", line 14, in main
    import main
ImportError: No module named main
Traceback (most recent call last):
  File "/usr/bin/zeronet.py", line 54, in <module>
    main()
  File "/usr/bin/zeronet.py", line 40, in main
    traceback.print_exc(file=open("log/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'
```

**Comment by HelloZeroNet** [comment]
The current (working) directory must be where you unpacked zeronet, so:

- `wget https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz`
- `tar xvpfz master.tar.gz`
- `cd ZeroNet-master`
- `python2 zeronet.py`

**Comment by DoctorJellyface** [comment]
Hm, works great, thanks. Looks like the package is faulty.
