### ISSUE TITLE
My VPS with only ipv6 also shows ipv4 opened in Hello page.

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1872]
3807 version

**Comment by HelloZeroNet** [comment]
If you search for "(ipv4) using checkPortchecker result:" in the log what's the result? Does it have ipv4 address as ip and opened is True?

**Comment by tangdou1** [comment]
Ok, I fix it in 
https://github.com/HelloZeroNet/ZeroNet/pull/1876/commits
