### ISSUE TITLE
ipv4 opened when recheck port

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1880]
rev.3818

Problem:
I donot have public ipv4, it will show `ipv4 closed` in the first start. Because 
` PeerPortchecker Checking port 23144 (ipv4) using checkCanyouseeme result: {'ip': 'xxx.xxx.xxx.xxx', 'opened': False}`
However, when I recheck port in the Hello page, it show `ipv4 opened`. Because
`ConnServer Server port opened based on configuration ipv4: True, ipv6: True`

Cause:

The `config.ip_external` will save my external ipv4 address.

```
    def portCheck(self):
        if config.ip_external:
            for ip_external in config.ip_external:
                SiteManager.peer_blacklist.append((ip_external, self.port))  # Add myself to peer blacklist

            ip_external_types = set([helper.getIpType(ip) for ip in config.ip_external])
            res = {
                "ipv4": "ipv4" in ip_external_types,
                "ipv6": "ipv6" in ip_external_types
            }
            self.port_opened.update(res)
            self.log.info("Server port opened based on configuration ipv4: %s, ipv6: %s" % (res["ipv4"], res["ipv6"]))
            return res
```

**Comment by HelloZeroNet** [comment]
Fixed by https://github.com/HelloZeroNet/ZeroNet/commit/f706f7508eac8afd39c85818cb5ca9401473004b
