### ISSUE TITLE
Include Lity as a library like what was done with JQuery

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#1885]
This is absolutely the lightbox of my dreams right here:

https://sorgalla.com/lity/

Anything this beautiful... I think would fit into the heart of ZeroNet the way those other included libraries do.

**Comment by rllola** [comment]
If you want to use it for one of your site you can just add it for your site. Like for example in `js/` folder where the `ZeroFrame.js` is and you can load it in your `index.html`.

**Comment by HelloZeroNet** [comment]
Yeah, please add it to your site if you want to use it, as the used/included libs with the ZeroNet can change anytime
