### ISSUE TITLE
Consistent Old Bug: Opening Sidebar crashes ZeroNet

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#1897]
I made sure that over many months of seeing this that this is in fact the problem. I think the Geolite City Database has to do with it.

Using Android (ZeroNet-Kivy)

**Comment by imachug** [comment]
Why was this closed? @styromaniac

**Comment by styromaniac** [comment]
I was thinking it's more to do with Kivy, or mistakenly closed it. IDK. I know it's not resolved.
