### ISSUE TITLE
If miniupnpc -e ZeroNet fails, try without -e

### ISSUE THREAD

**Issue by arthurlutz** [HelloZeroNet/ZeroNet#19]
My version of miniupnpc doesn't understand "-e ZeroNet" but the rest of the command is right. Maybe there could be a test or a try/except to do it without the -e option.

**Comment by HelloZeroNet** [comment]
I think its fixed in latest version:
https://github.com/HelloZeroNet/ZeroNet/blob/a977feec330a024686518ce6c374167d63d564f2/src/File/FileServer.py#L54
