### ISSUE TITLE
ZN fails to find OpenSSL on NixOS

### ISSUE THREAD

**Issue by skwerlman** [HelloZeroNet/ZeroNet#1907]
### Step 1: Please describe your environment

  * ZeroNet version: rev3852
  * Operating system: NixOS
  * Web browser: Tor Browser/Firefox
  * Tor status: always
  * Opened port: no
  * Special configuration: Installed using a package override:
```nix
{ config, pkgs, ... }:

{
  nixpkgs.config.packageOverrides = pkgs: rec {
    zeronet = pkgs.lib.overrideDerivation pkgs.zeronet (attrs: rec {
      buildInputs = with pkgs; [ openssl_1_1 ];
      version = "0.6.5-git";
      src = pkgs.fetchFromGitHub {
        owner = "HelloZeroNet";
        repo = "ZeroNet";
        rev = "174e8d3c19e4dbe53bdab95db0aa3de416249df3";
        sha256 = "0bbmjbz36nlf7il0ph2i7s32jnlxq2v0wc8nxi4aaqxns8qy2jkf";
      };
    });
  };
}
```

#### Steps to reproduce:

  1. install zeronet and openssl
  2. start zeronet
  3. debug log notes that openssl failed to load

#### Observed Results:

  * OpenSSL fails to load, because ZeroNet does not look for it in the correct location

#### Expected Results:

  * ZeroNet should find OpenSSL without issues.

----

On NixOS, the standard paths are not used; rather, the environment variable `LD_LIBRARY_PATH` is used to tell ld where to find libraries. ZeroNet should respect this environment variable when loading OpenSSL in order to be compatible with NixOS.

**Comment by HelloZeroNet** [comment]
Actually ZeroNet currently needs openssl 1.0.x, can you try if that package is installed?

**Comment by skwerlman** [comment]
It fails with either package. The issue is that OpenSSL will be at `/nix/store/<some hash>-openssl-<version>/lib/`, which is not a predictable path.

**Comment by rllola** [comment]
I have started a VM with NixOS. I have been able to reproduce this.

From what I understand, Zeronet is going to be look for the path of the lib and then open it : 
https://github.com/HelloZeroNet/ZeroNet/blob/bc227b5f561416f418014d9bccf95b405e34a14a/src/lib/opensslVerify/opensslVerify.py#L195-L206

It is calling this `getLibraryPath` function : https://github.com/HelloZeroNet/ZeroNet/blob/master/src/util/SslPatch.py#L13-L39

It will not look into the `LD_LIBRARY_PATH` so in NixOS it will return null.

However you can get the library by loading it if the path to openssl has been loaded in `LD_LIBRARY_PATH` by just calling it : `ssl_lib = ctypes.CDLL('libcrypto.so')`
with `LD_LIBRARY_PATH` having our openssl path `/nix/store/<some hash>-openssl-<version>/lib/`

So we could try first to load the library using `ctypes.CDLL('libcrypto.so')` and if it fails look for the path in others directories?

**Comment by HelloZeroNet** [comment]
Probably it would be better to do it same way as for ANDROID_APP_PATH: list directory of LD_LIBRARY_PATH, then pick the first libcrypto(1.0.x) from it, because for example I only have libcrypto.so.1.0.2 and libcrypto.so.1.1 files on debian, but no libcrypto.so (not sure what about other OS)

**Comment by rllola** [comment]
Ok yeah that would work. 

It would be added here then? https://github.com/HelloZeroNet/ZeroNet/blob/master/src/util/SslPatch.py#L13-L39

I can prepare a PR with the modification.

**Comment by HelloZeroNet** [comment]
yeah, thats the best place, btw we need openssl 1.0.x, so the best would be to first search for libcrypto.so.1.0* in LD_LIBRARY_PATH
