### ISSUE TITLE
Database rebuild says successfull but log showed error

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#1908]
I am trying to rebuild the database and the UI message says that everything went well when in the log I have an error message.

![screenshot from 2019-02-19 13-37-45](https://user-images.githubusercontent.com/1772945/53015669-e4f58d00-344b-11e9-9bda-6a2a1a053cec.png)
![screenshot from 2019-02-19 13-38-13](https://user-images.githubusercontent.com/1772945/53015670-e58e2380-344b-11e9-90d4-35c01dc441bf.png)

**Comment by rllola** [comment]
**How to reproduce**

This error was created because of an error (copy/pasta) in the definition of the dbschema. See patch https://github.com/rllola/mixtape/pull/44/files

**Fix**
Currently the function `actionDbRebuild` return ok whatever happens (https://github.com/HelloZeroNet/ZeroNet/blob/py3/plugins/Sidebar/SidebarPlugin.py#L784-L791). If it fails it should return False or catch the error and return it to the interface.

**Comment by rllola** [comment]
I can confirm that this is also happening in `py3`.

**Comment by HelloZeroNet** [comment]
Fixed by: https://github.com/HelloZeroNet/ZeroNet/commit/9cda561091d3ae8e13625f2660af2dce212a9966

Possible improvement: return more detailed error message.

**Comment by rllola** [comment]
I think `checkTables` should raise an error instead of returning `False`. When I tried it fails in many places... This error should catch to not stop the app from running. Should I go for that ?

**Comment by HelloZeroNet** [comment]
Yeah you need to add a try/catch block everywhere, but it would be a nice improvement

btw dbRebuild right now never returns True, so https://github.com/HelloZeroNet/ZeroNet/commit/9cda561091d3ae8e13625f2660af2dce212a9966#diff-aa66f3ebb15e6e0a2751f67fe9ced6b8R791 will always show an error.

**Comment by rllola** [comment]
I am on it but it might take sometimes.

I know that I verified that it will return the error but I am not sure it will show the correct message if successful... Let me check if it doesnt I will patch it.

**Comment by rllola** [comment]
It was indeed missing a `return True` at one point to avoid it to return the error message. See https://github.com/HelloZeroNet/ZeroNet/pull/2045

I have tested it in case with error in dbschema.json and without error this time.

Concerning the error catching it seems that I have to do something with gevent because of the Noparallele wrapper? https://github.com/HelloZeroNet/ZeroNet/blob/fb3c5eaafaa9087640106dc24773010eaf81e0b1/src/Site/SiteStorage.py#L116-L119

**Comment by HelloZeroNet** [comment]
Hm, yes, I can confim it's not working because of noparallel...check if there is an easy fix for that

**Comment by HelloZeroNet** [comment]
I have added a modification in Rev4104 that should raise the exception correctly for function with noparallel decorator https://github.com/HelloZeroNet/ZeroNet/commit/862e19a26390c28d92d548e17b4fff797661f34f

**Comment by rllola** [comment]
Here the PR but I am really not sure... https://github.com/HelloZeroNet/ZeroNet/pull/2047

Anyway I can add test to this ?
