### ISSUE TITLE
How to use another browser?

### ISSUE THREAD

**Issue by kiridu1988** [HelloZeroNet/ZeroNet#1909]
How to automatically launch a specific browser after launching ZeroNet?

**Comment by kiridu1988** [comment]
Anyone?

**Comment by kiridu1988** [comment]
Thanks for the help, developers!
You don't even know your own program. :(

**Comment by rllola** [comment]
Zeronet automatically open your default browser. You can just change your default browser.

You also can open the browser of your choice and access Zeronet from there.

**Comment by kiridu1988** [comment]
You did not answer my question.
And everything that you said, I already know.

**Comment by kiridu1988** [comment]
https://github.com/HelloZeroNet/ZeroNet-win
Where is the source code of the exe file for Windows?

**Comment by kiridu1988** [comment]
https://github.com/HelloZeroNet/ZeroNet-mac
Where is the source code of the exe file for Mac?
Why is everything so unorganized?

**Comment by imachug** [comment]
1. Don't expect us to answer soon -- I think most ZeroNet developers seldom check GitHub.
2. We *do* know our program. Prove the opposite if you tell us we don't.
3. The source code of the exe file for Windows is in this very repository.
4. The exe file for Mac doesn't exist ¯\_(ツ)_/¯. Use "app" instead please.
5. It's not disorganized, it just makes more sense to have different repos for different builds if you have platform-dependent binaries (binaries, not source code).

Now to your question:

Either use `--open_browser chrome` (for example) CLI option, or use add `open_browser=chrome` line to `zeronet.conf`, like this:

```
[global]
open_browser=chrome
```

The full list of supported browsers can be found [here](https://docs.python.org/2/library/webbrowser.html).

If this answers your question, please close this issue.

**Comment by kiridu1988** [comment]
What is the direct link to the sorce code of exe file?
I do not need Chrome, I want to specify the relative path to the browser.

**Comment by imachug** [comment]
Here is the source code: https://github.com/HelloZeroNet/ZeroNet. Seriously, that exe is just a bundled python version.

As for the relative path, let me take a look -- I will try to find a way.

**Comment by kiridu1988** [comment]
ZeroNet.exe?

I created a shortcut and added
--open_browser="C:\Users\user\Desktop\znbrowser\FirefoxPortableWin\FirefoxPortable.exe "%s"

but it does not work.

**Comment by kiridu1988** [comment]
--open_browser="C:\Users\user\Desktop\znbrowser\FirefoxPortableWin\FirefoxPortable.exe "%s"

Not work

**Comment by kiridu1988** [comment]
So how to solve this problem?

**Comment by rllola** [comment]
>     1. Don't expect us to answer soon -- I think most ZeroNet developers seldom check GitHub.
> 
>     2. We _do_ know our program. Prove the opposite if you tell us we don't.
> 
>     3. The source code of the exe file for Windows is in this very repository.
> 
>     4. The exe file for Mac doesn't exist ¯\_(ツ)_/¯. Use "app" instead please.
> 
>     5. It's not disorganized, it just makes more sense to have different repos for different builds if you have platform-dependent binaries (binaries, not source code).
> 
> 
> Now to your question:
> 
> Either use `--open_browser chrome` (for example) CLI option, or use add `open_browser=chrome` line to `zeronet.conf`, like this:
> 
> ```
> [global]
> open_browser=chrome
> ```
> 
> The full list of supported browsers can be found [here](https://docs.python.org/2/library/webbrowser.html).
> 
> If this answers your question, please close this issue.

Good catch. My apologies I forgot about this feature. 

+1 @imachug

**Comment by rllola** [comment]
> ZeroNet.exe?
> 
> I created a shortcut and added
> --open_browser=C:\Users\user\Desktop\znbrowser\FirefoxPortableWin\FirefoxPortable.exe "%s"
> 
> but it does not work.

You need to add it in the `zeronet.conf` like written in the answer.

**Comment by kiridu1988** [comment]
[global]
open_browser=C:\Users\user\Desktop\znbrowser\FirefoxPortableWin\FirefoxPortable.exe "%s"

does not work

**Comment by rllola** [comment]
For me it worked removing `"%s"` but I am on ubuntu and I was trying with chromium.

I will try too day on Windows.

**Comment by kiridu1988** [comment]
I removed "%s".
Only ZeoNet was launched, but not the browser.

**Comment by rllola** [comment]
I tested on Windows. I have the same issue. Only Zeronet is running and the browser doesn't open. 

zeronet.conf
````
[global]
fileserver_port = 31881
open_browser = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe "%s"
````

The log doesn't show any error message neither : 
```
[11:27:23] - Creating UiServer....
[11:27:23] - Removing old SSL certs...
[11:27:23] - Starting servers....
[11:27:23] Ui.UiServer --------------------------------------
[11:27:23] Ui.UiServer Web interface: http://127.0.0.1:43110/
[11:27:23] Ui.UiServer --------------------------------------
[11:27:23] - Opening browser: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe "%s"...
[11:27:24] TorManager Connecting to Tor Controller 127.0.0.1:9051
```

Could you specify which version of Zeronet you are using and which browser you want to use ? And maybe the logs ?

I am not a Zeronet dev but I can try to help...

**Comment by kiridu1988** [comment]
Probably there are bugs that need to be fixed.

**Comment by HelloZeroNet** [comment]
Custom browser not supported currently, but if you know the exact path to the executable you can create a .bat file to start it.

**Comment by kiridu1988** [comment]
I'll wait a couple of years when it starts working.

**Comment by imachug** [comment]
> 
> 
> Custom browser not supported currently, but if you know the exact path to the executable you can create a .bat file to start it.

This is weird, because AFAIK `webbrowser` module supports browsers defined by their path in case the string includes `%s`. So, using `path/to/browser "%s"` should work, not sure what went wrong.

**Comment by swar-sudo** [comment]
> > Custom browser not supported currently, but if you know the exact path to the executable you can create a .bat file to start it.
> 
> This is weird, because AFAIK `webbrowser` module supports browsers defined by their path in case the string includes `%s`. So, using `path/to/browser "%s"` should work, not sure what went wrong.

I solved it by putting parentheses on the path, like this:

[global]
open_browser="C:\Program Files\Tor Browser\Browser\firefox.exe" %s

Although the problem remains when clicking on the status icon
