### ISSUE TITLE
Random port

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1915]
Though it seems useless, in some cases, it could solve the problem

**Comment by HelloZeroNet** [comment]
There is a port randomization on first startup. It could be possible to randomize it on every startup, but then it would not be possible to use tracker-less, previously saved peer list as port will change more often.

**Comment by blurHY** [comment]
Send the port we use next time to connected peers ?

**Comment by HelloZeroNet** [comment]
Ok, but when is next time?

**Comment by blurHY** [comment]
Set a time interval to send the 'next port' regularly

**Comment by Thunder33345** [comment]
cant someone malicious like GFW make fake peers to intercept ports to block "soon"?

**Comment by purplesyringa** [comment]
@HelloZeroNet Given that this issue has been inactive for a long while and has some difficulties (even in theory), could we close it?
