### ISSUE TITLE
SiteAnnouncer.py - trackers - need more than 1 value to unpack

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1917]
### Step 1: Please describe your environment

  * ZeroNet version: 3853
  * Operating system: Linux
  * Web browser: Firefox
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

I am seeing multiple errors like following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/me/ZeroBundle/ZeroNet/src/Site/SiteAnnouncer.py", line 89, in announce
    trackers = self.getAnnouncingTrackers(mode)
  File "/home/me/ZeroBundle/ZeroNet/src/Site/SiteAnnouncer.py", line 57, in getAnnouncingTrackers
    trackers = self.getSupportedTrackers()
  File "/home/me/ZeroBundle/ZeroNet/src/Site/SiteAnnouncer.py", line 52, in getSupportedTrackers
    trackers = [tracker for tracker in trackers if helper.getIpType(self.getAddressParts(tracker)["ip"]) != "ipv6"]
  File "/home/me/ZeroBundle/ZeroNet/src/Site/SiteAnnouncer.py", line 175, in getAddressParts
    ip, port = address.rsplit(":", 1)
ValueError: need more than 1 value to unpack
```

as a autput of running zeronet process. Did i added some wrong tracker into Config?

when i restarted zeronet, i found it failed with [Segmentation fault message](https://pastebin.com/0tVE0X2B)

When i start ZN again, it started, though still numerous errors "need more than 1 value to unpack" and ZeroHello trackers button shows TRACKERS: WAITING...

**Comment by HelloZeroNet** [comment]
Yes, you always have to specify the port, so eg. instead of https://3.tracker.eu.org/announce use https://3.tracker.eu.org:443/announce

**Comment by slrslr** [comment]
While Config page does not explain this, maybe can be good if Zeronet does not fail as a result of invalid tracker URL, but skip it. Not every user is experienced enough to be able to discover cause of the issue like this and fix it.
