### ISSUE TITLE
Zeronet Python3 requirements.txt wrong module names

### ISSUE THREAD

**Issue by llelectronics** [HelloZeroNet/ZeroNet#1929]
The requirements.txt for the python3 version is listing some wrong modules. 
Like **geventwebsocket** should be **gevent-websocket** and **bencode** should be **bencode.py** otherwise it will complain about missing modules or modules that cannot be build when using pip to download those.

**Comment by HelloZeroNet** [comment]
Thanks for reporting it was fixed yesterday: https://github.com/HelloZeroNet/ZeroNet/blob/py3/requirements.txt
