### ISSUE TITLE
PluginManager Plugin Bootstrapper load error: DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#1930]
### Step 1: Please describe your environment

  * ZeroNet version: 3853
  * Operating system: Linux
  * Opened port: yes
  * Special configuration: multiuser_local ; Python 2.7.12

### Step 2: Describe the problem:

My Linux Ubuntu zeronet proxy was told to download a few sites one by one using "zeronet.py siteDownload" command and i found it stuck after one of the sites and this is last lines which "hangs" and prevent continuing:

```
PluginManager Plugin Bootstrapper load error: DatabaseError: database disk image is malformed in PluginManager.py line 50 > builtins.py line 96 > __init__.py line 1 > builtins.py line 96 > BootstrapperPlugin.py line 11 > BootstrapperDb.py line 17 > BootstrapperDb.py line 33 > Db.py line 74 > Db.py line 65 > Db.py line 139 > DbCursor.py line 90
PluginManager Plugin Chart load error: DatabaseError: database disk image is malformed in PluginManager.py line 50 > builtins.py line 96 > __init__.py line 1 > builtins.py line 96 > ChartPlugin.py line 13 > ChartDb.py line 12 > ChartDb.py line 65 > Db.py line 75 > DbCursor.py line 90
```

if interested, previous command that went thru, not stuck [had same error](https://pastebin.com/6bd2SPYk).

How to prevent this or autofix it

**Comment by HelloZeroNet** [comment]
Unfortunately there is no way to fix malformed sqlite databases, so you have to delete data/chart.db and data/bootstrapper.db.

The [Python3 version](https://github.com/HelloZeroNet/ZeroNet/tree/py3) (currently still in testing stages) using secure way to handle db files and hopefully it will prevent these kind of errors from happening.

**Comment by slrslr** [comment]
thank you for explanation
