### ISSUE TITLE
Menu options Version and shutdown on Hello ZN site not visible on low density device with Opera

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#1936]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5.2
  * Operating system: Android
  * Web browser: Opera
  * Tor status: na
  * Opened port: na
  * Special configuration: ____

### Step 2: Describe the problem:
Menu options Version and shutdown on Hello ZN site not visible on low density device with Opera.
See the screenshot.

#### Steps to reproduce:

  1. Open hello ZN site with opera
  2. Go to hamburger menu
  3. Notice that Version info and Shutdown are not visible

#### Observed Results:
Version info and Shutdown are not visible. See the screenshot.

#### Expected Results:
Options should be visible. Especially when running ZN directly on device to prevent battery drain.
Visible menu should be scrolling instead of background layer.

![Screenshot_20190324-194702_Opera](https://user-images.githubusercontent.com/11329331/54884302-799a4300-4e6f-11e9-86d5-79516151c286.jpg)

**Comment by tangdou1** [comment]
there is a same problem when you visit zeronet through proxy in mobile phone browser.

**Comment by HelloZeroNet** [comment]
Thanks for reporting I changed the left side to be scrolled on the full element not just the site list:
https://github.com/HelloZeroNet/ZeroHello/commit/3c2023abe3e9791274d8e629e8df634b977bda62
