### ISSUE TITLE
A bug about content-type?

### ISSUE THREAD

**Issue by tangdou1** [HelloZeroNet/ZeroNet#1940]
### Step 1: Please describe your environment

  * ZeroNet version: 3860
  * Operating system: `remote zeronet on Debian9` / `local zeronet on windows 7`
  * Web browser: _firefox66
  * Tor status: not available
  * Opened port: yes
  * Special configuration: _no___

#### Steps to reproduce:

  1. Open the zite `http://127.0.0.1:43110/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/` through `local` ZeroNet
  2. Press F12, you can find the content-type of `http://127.0.0.1:43110/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/fonts/material-icons/MaterialIcons-Regular.woff2` is `application/octet-stream`.
  3.  However, Open the zite `http://remote zeronet's ip:port/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/` through `remote` ZeroNet.
 4. Press F12, you can find the content-type of `http://remote zeronet's ip:port/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/fonts/material-icons/MaterialIcons-Regular.woff2` is `text/html; charset=utf-8`, which means the font source would be blocked by browser due to cors problem and the content-type is also wrong.

#### Observed Results:

 Some source cannot be read when using remote zeronet.

#### Expected Results:

the content-type should be consistent.

**Comment by tangdou1** [comment]
maybe it is just a python version problem. (Debian 9 use python 2.7.13)

**Comment by HelloZeroNet** [comment]
What happens if you open the `http://remote zeronet's ip:port/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/fonts/material-icons/MaterialIcons-Regular.woff` directly? Does the file content got displayed?

**Comment by tangdou1** [comment]
> 
> 
> What happens if you open the `http://remote zeronet's ip:port/14c5LUN73J7KKMznp9LvZWkxpZFWgE1sDz/fonts/material-icons/MaterialIcons-Regular.woff` directly? Does the file content got displayed?

@HelloZeroNet 
It will be downloaded directly.

[MaterialIcons-Regular.zip](https://github.com/HelloZeroNet/ZeroNet/files/3016080/MaterialIcons-Regular.zip)

**Comment by tangdou1** [comment]
![捕获](https://user-images.githubusercontent.com/35254744/55128551-f4ed4480-514e-11e9-9107-8ff830896d73.jpg)

**Comment by krixano** [comment]
Why was this closed? It looks like it's a bug with a **more up to date** version of python.

**Comment by HelloZeroNet** [comment]
I just tested with python 2.7.9 (Linux), 2.7.13 (Linux), 2.7.14 (Win), 3.5.3 (Linux), 3.7.1 (Win) and the result is the same everywhere:

```
$ python -c "print(__import__('mimetypes').guess_type('hello.woff2'))"
(None, None)
```
In this case ZeroNet should return "application/octet-stream" as content type. Whats your result to this command?

**Comment by tangdou1** [comment]
> 
> 
> I just tested with python 2.7.9 (Linux), 2.7.13 (Linux), 2.7.14 (Win), 3.5.3 (Linux), 3.7.1 (Win) and the result is the same everywhere:
> 
> ```
> $ python -c "print(__import__('mimetypes').guess_type('hello.woff2'))"
> (None, None)
> ```
> 
> In this case ZeroNet should return "application/octet-stream" as content type. Whats your result to this command?

Yes, it return `(None, None)`.

**Comment by HelloZeroNet** [comment]
What's on the preview/response tab? Is it the font itself or a html code?
(The Connection: close is also interesting, because it should always return keep-alive)

**Comment by tangdou1** [comment]
it is the font itself, shown in:

![capture](https://user-images.githubusercontent.com/35254744/55283698-79cc9e00-539b-11e9-9bed-f3e8cf257da7.png)

**Comment by krixano** [comment]
I'm on python 3.7.2. Here's what I get for these:

1.) `print(__import__('mimetypes').guess_type('MaterialIcons-Regular.woff'))`
`(None, None)`

2.) `print(__import__('mimetypes').guess_type('test.woff2'))`
`(None, None)`

**Comment by tangdou1** [comment]
>  on python 3.7.2. Here's what I get for these:

Yes, when I use the python3 version of zeronet on the same machine. The content-type problem also disappears. So this is just a python's problem (python 2.7.13 on Debian 9) not a zeronet's bug.
So just close this issue.

**Comment by krixano** [comment]
Wait... we're not supposed to be getting `(None, None)` right? Aren't we supposed to be getting `('application/font-woff', None)`?

Can you stop freaking closing issues until we know *for sure* the problem is solved!

**Comment by HelloZeroNet** [comment]
Python itself does not have entry for web font content-type: https://github.com/python/cpython/blob/master/Lib/mimetypes.py#L402

So it depends on the operating system configuration if its application/font-woff or None. In case of None we return "application/octet-stream" as content-type which works for browsers I tested.

To make it more predictable we could write our own content-type resolver that does not depends on operating system configuration files.

**Comment by krzotr** [comment]
> To make it more predictable we could write our own content-type resolver that does not depends on operating system configuration files.

Instead of creating own resolver we can create own file which contains specified content-types and extensions e.g.

file `/tmp/mime.types`
```
    application/font-woff   woff
    font/woff2              woff2
```

Just run
```
import mimetypes
mimetypes.init(['/tmp/mime.types']);

mimetypes.guess_type('MaterialIcons-Regular.woff2');    # returns ('font/woff2', None) - perfect
```

Regarding source code of [mimetypes.init function](https://github.com/python/cpython/blob/master/Lib/mimetypes.py#L345). We can create own `mime.types` file which does not depend on operating system configuration files - only specified content-types and extensions entries `mimetypes.init` will be loaded.

**Comment by tangdou1** [comment]
When enable the ui_password plugin , the problem will reproduce .

**Comment by HelloZeroNet** [comment]
Unfortunately it happens because some http requests (eg. font resource requests) does not contains the cookie required for the authentication, so the login screen getting served instead of the resource.

**Comment by ghost** [comment]
> So it depends on the operating system configuration if its application/font-woff or None. In case of None we return "application/octet-stream" as content-type which works for browsers I tested.
> 
> To make it more predictable we could write our own content-type resolver that does not depends on operating system configuration files.

@HelloZeroNet If you are still planning on fixing this, this should be reopened.

**Comment by ghost** [comment]
#2248

**Comment by SuperSandro2000** [comment]
This happened to me when I did not have ``/etc/mime.types`` installed. On Debian you miss ``mime-support`` and on alpine ``mailcap``

Edit: well, it fixes ``print(__import__('mimetypes').guess_type('test.woff2'))`` but not the content type problem.
