### ISSUE TITLE
Stuck at Starting servers with 1 % cpu usage

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#1949]
Cloned github zeronet repo
 Ubuntu vps
 Opened port: yes

Database may be malformed.

**Comment by HelloZeroNet** [comment]
Is there anything in log/debug.log?

**Comment by blurHY** [comment]
![image](https://user-images.githubusercontent.com/33171396/55465316-73eeeb00-562f-11e9-8a15-63e1cf7876ed.png)
![image](https://user-images.githubusercontent.com/33171396/55465329-7bae8f80-562f-11e9-8c17-4c6b86c3802a.png)

Without enabling debug mode, it shows nothing.
I don't know what it was doing, just stuck there

**Comment by blurHY** [comment]
How I can improve the performance of zeronet which has a lot of sites ?
`curl 127.1:43110` always takes a long time to respond.

**Comment by blurHY** [comment]
@shortcutme

**Comment by HelloZeroNet** [comment]
So you had a data dir with lots of sites, then cloned the latest source, copied the data dir and the db was malformed, right?

**Comment by blurHY** [comment]
Nope, I cloned zeronet and started crawler
