### ISSUE TITLE
Application version information disclosure on "403 Forbidden" page

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#1977]
This ticket is related to #1976.

Tested on latest git versions of 0.7.0 and 0.6.5

When we add two dots in URL e.g. `http://127.0.0.1:43110/a../` we see `403 Forbidden` page with `Details` - a full list of HTTP headers, all configuration parameters of ZeroNet, list of enabled plugins and specified versions (python, zeronet, gevent).

In some cases, we can expose the real IP address of the server behind the proxy. We can also very easy check version of ZeroNet client or python

This list should be available when `debug` or `verbose` parameter is set to `on`.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, I have made a change in latest rev that only displays the details in debug mode
