### ISSUE TITLE
Adding new section to zeronet.conf make zeronet not starting

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#1978]
### Step 1: Please describe your environment

  * ZeroNet version: py3
  * Operating system: linux
  * Web browser: Firefox
  * Tor status: 
  * Opened port: 
  * Special configuration:

### Step 2: Describe the problem:

Added a `[namecoin]` section to `zeronet.conf` and ZeroNet doesn't want to start normally. I got the following error:

```
zeronet.py: error: unrecognized arguments: --namecoin_host 127.0.0.1 --namecoin_rpcport 8336 --namecoin_rpcpassword kek --namecoin_rpcuser nah
``` 

#### Steps to reproduce:

  1. Modify `zeronet.conf` by adding a section
  2. start ZeroNet

#### Observed Results:

Crash
```
zeronet.py: error: unrecognized arguments: --namecoin_host 127.0.0.1 --namecoin_rpcport 8336 --namecoin_rpcpassword kek --namecoin_rpcuser nah
``` 

#### Expected Results:

It start like normal

**Comment by HelloZeroNet** [comment]
You have to create a ConfigPlugin to make it work, for example:
https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/disabled-Multiuser/MultiuserPlugin.py#L221

**Comment by rllola** [comment]
Working so I am closing this.
