### ISSUE TITLE
Doesn't show what I am writing

### ISSUE THREAD

**Issue by franc3** [HelloZeroNet/ZeroNet#1981]
I am on the latest version of ZerNet
I am on Linux (Fedora 29 on Gnome)
Firefox 66
I have a closed port

When I write something in a forum it doesn't appear what I write during I am writing. When I publsh it, it is all OK.

To repruduce it simply write somewhere something

![Screenshot from 2019-04-13 18-10-42](https://user-images.githubusercontent.com/46760284/56082299-7d3e3b80-5e17-11e9-8bdf-eb600c0a730e.png)
![Screenshot from 2019-04-13 18-10-45](https://user-images.githubusercontent.com/46760284/56082301-7fa09580-5e17-11e9-8f7f-9b9f48551ba3.png)

**Comment by skwerlman** [comment]
this is a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1283086

**Comment by imachug** [comment]
As this issue is unrelated to ZeroNet and is already tracked by Mozilla, can we close this? @HelloZeroNet
