### ISSUE TITLE
Signatures not recognized after upgrading to Python 3

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#2000]
### Step 1: Please describe your environment

  * ZeroNet version: v0.7.0 (rev4080)
  * Operating system: Windows (but should be reproducible on all OSes)
  * Web browser: doesn't matter
  * Tor status: doesn't matter
  * Opened port: doesn't matter
  * Special configuration: none

#### One-line TL;DR

Compressed recovered public keys are not supported by libsecp256k1message.

#### A bit longer TL;DR

KaffieID, CryptoID and several other providers generate signatures like this:

```
H6YkcFTuwKMVMHI2yycGQIFGbCZVNsZEZvSlOhKpHUt/BlADY94egmDAWdlrbbFrP9wH4aKcEfbLO8sa6f63VU0=
```

If you base64-decode this, you get this: *(newlines mine)*

```
1f
a624 7054 eec0 a315 3072 36cb 2706 4081 466c 2655 36c6 4466 f4a5 3a12 a91d 4b7f
0650 0363 de1e 8260 c059 d96b 6db1 6b3f dc07 e1a2 9c11 f6cb 3bcb 1ae9 feb7 554d
```

The first integer (`0x1f`) specifies the Recovery ID. Since it's greater than `0x1e`, we understand that the "recovered public key" is "compressed". `pybitcointools` support this. OpenSSL supports this. `libsecp256k1` (which is the default library!) does not.

#### The full issue

The verifying works like this:

1. Decode public key from the signature
2. Hash it to get address
3. Compare to the expected address

This is the difference: in case the signature uses uncompressed public key, you get this: *(newlines mine)*

```
04
86bf45b660266d383fbd9046e7ed54c3255ab9bc6e11dc7bdb5a2ef94fa41e49
aa5baacddf555d8891ec2c9f52e7b770a470586efacdb765cba245f4e6602d0a
```

If it uses compressed public key, you get this:

```
02
86bf45b660266d383fbd9046e7ed54c3255ab9bc6e11dc7bdb5a2ef94fa41e49
```

Since the strings are different, the hash is different as well, so the address differs. OpenSSL and pybitcointools support this behaviour, libsecp256k1message doesn't.

#### Steps to reproduce:

```
btctools.ecdsa_recover("1NQUem2M4cAqWua6BVFBADtcSP55P4QobM#web/gitcenter", base64.b64encode(b"\x1f\xa6$pT\xee\xc0\xa3\x150r6\xcb'\x06@\x81Fl&U6\xc6Df\xf4\xa5:\x12\xa9\x1dK\x7f\x06P\x03c\xde\x1e\x82`\xc0Y\xd9km\xb1k?\xdc\x07\xe1\xa2\x9c\x11\xf6\xcb;\xcb\x1a\xe9\xfe\xb7UM"))
# -> 0286bf45b660266d383fbd9046e7ed54c3255ab9bc6e11dc7bdb5a2ef94fa41e49 (original signature used)
btctools.ecdsa_recover("1NQUem2M4cAqWua6BVFBADtcSP55P4QobM#web/gitcenter", base64.b64encode(b"\x1b\xa6$pT\xee\xc0\xa3\x150r6\xcb'\x06@\x81Fl&U6\xc6Df\xf4\xa5:\x12\xa9\x1dK\x7f\x06P\x03c\xde\x1e\x82`\xc0Y\xd9km\xb1k?\xdc\x07\xe1\xa2\x9c\x11\xf6\xcb;\xcb\x1a\xe9\xfe\xb7UM"))
# -> 0486bf45b660266d383fbd9046e7ed54c3255ab9bc6e11dc7bdb5a2ef94fa41e49aa5baacddf555d8891ec2c9f52e7b770a470586efacdb765cba245f4e6602d0a (after replacing `0x1f` with `0x1b`, i.e. using compressed recovered public key).
```

**Comment by HelloZeroNet** [comment]
Thanks for the info. It would be nice if someone could check on possible fix for this issue.

**Comment by HelloZeroNet** [comment]
Should be fixed in Rev4089:
The fix: https://github.com/HelloZeroNet/ZeroNet/commit/617027eb52d63e4cafe52c15f2b15567ededcf04
The test case: https://github.com/HelloZeroNet/ZeroNet/commit/6b9106b1782a7989ebbfae955fbc5c556ba0aef9
