### ISSUE TITLE
No such file or directory: u'...data/1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp/messages.json'

### ISSUE THREAD

**Issue by JediKnightChan** [HelloZeroNet/ZeroNet#2004]
### Step 1: Please describe your environment

  * ZeroNet version: last stable
  * Operating system: Windows
  * Web browser: Opera
  * Tor status: disabled
  * Opened port: no

### Step 2: Describe the problem:
When I try to send a message on ZeroBoard, it shows "Message submit failed!
undefined"

LOG: [2019-04-30 04:51:53,174] ERROR    Site:1Gfey7..fcdp messages.json fileGet error: [Errno 2] No such file or directory: u'C:/Users/JediKnight/Downloads/ZeroNet-win-dist/data/1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp/messages.json'

**Comment by HelloZeroNet** [comment]
The ZeroBoard is marked deprecated and no longer supported in latest versions.
I just removed the reference from the main page.
