### ISSUE TITLE
How to build ZeroNet from source for windows

### ISSUE THREAD

**Issue by DATSEC** [HelloZeroNet/ZeroNet#2009]
I can not find instructions on how to build code from sources
The end result is needed such https://github.com/HelloZeroNet/ZeroNet-win/archive/dist/ZeroNet-win.zip

**Comment by HelloZeroNet** [comment]
Here is the script I use: https://github.com/HelloZeroNet/ZeroBundle/blob/master/compile/compile_win.cmd (may need to change the path of the tools)
