### ISSUE TITLE
Resulting .zip archive of the site is corrupted

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2010]
### Step 1: Please describe your environment

  * ZeroNet version: 3864
  * Operating system: W10
  * Web browser: FF
  * Tor status: available

### Step 2: Describe the problem:

I backed up "ZeroBlog Plus" (15mSYzsDxzarssqtV1pFPKqoCTaLdjVB2f) clone and when i opened it in the archiver app i seen only one file in it (.7z archive), when i tried to extract it, it said Headers Error Unconfirmed start of archive Warnings: There are some data after the end of the payload data
Data error: name of the 7z archive

when i renamed the 7z archive to short simple name, and run zip function again it then complained about content.json to be "Data error". I tried to extract using 7z and also using Windows built in archiving app.

**Comment by stbinan** [comment]
If you are talking the backup feature on ZeroHello or on "0" zite config panel, I have the same issue on FF in Archlinux, and this command fixs the zip file:
`$ zip -F file.zip --out new.zip`

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it was only able to reproduce the problem on Python3, but I think it should be the same problem. Fixed in https://github.com/HelloZeroNet/ZeroNet/commit/c165d21d9573164bed0dd5939c547cd862dd739b Rev3865
