### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'log_dir'

### ISSUE THREAD

**Issue by neighborBoy0** [HelloZeroNet/ZeroNet#2013]
### Step 1: Please describe your environment

  * ZeroNet version: __Rev3864___
  * Operating system: __Mac OS 10.14.4___
  * Web browser: __Safari & Chrome___
  * Tor status: not available
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:
I can't start ZeroNet on my computer. When I run zeronet.py, there will be an error and I didn't find a solution to fix it.
and in fact [cd82215](https://github.com/HelloZeroNet/ZeroNet/commit/cd822156c9fda420afeb63eda4d9637441f7393f) is not suitable for my situation.
#### Steps to reproduce:

  1. __download ZeroNet-mater from github___
  2. __open the .zip and enter the directory___
  3. __"python2 ./zeronet.py"___

#### Observed Results:

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/46868461/57282802-162a4480-70ae-11e9-9a1c-8c91637b5419.png">

**Comment by imachug** [comment]
Did you install the required libraries? The following commands should fix it:

```shell
python2 -m pip install requests
python2 -m pip install gevent
```

If you have any more problems, I'm ready to help.

**Comment by neighborBoy0** [comment]
yes, I have already install these libs, but it doesn't work. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/46868461/57567597-12632e80-73dc-11e9-81f7-3e012569c5e9.png">

**Comment by neighborBoy0** [comment]
and I'm trying to make a P2P website. Could you please tell me how can I call python files in zeronet? Thank you for your help.

**Comment by HelloZeroNet** [comment]
There is a binary package for MacOS, please try that one:
https://github.com/HelloZeroNet/ZeroNet-mac/archive/dist/ZeroNet-mac.zip
You can start from the terminal using $ ~/ZeroNet.app/Contents/MacOS/ZeroNet

**Comment by imachug** [comment]
@neighborBoy0 Have you resolved the issue? I can't reproduce the bug on my Mac as well, so it would be great if you told us about the progress on this.

@HelloZeroNet Can this be closed for inactivity?
