### ISSUE TITLE
[Proposal]: Open ui_port with UPnP when bind to all interfaces

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#202]
So you won't have to forward the port in the router manually

With another setting to allow opening ui_port with UPnP

**Comment by grez911** [comment]
UPnP is implemented.
@HelloZeroNet Can the issue be closed?

**Comment by HelloZeroNet** [comment]
Binding to ui to a public interface is usually not a good idea, and it would make that mistake easier.
