### ISSUE TITLE
VerifyError: Content too large: in main.py line 198 > ContentManager.py line 736 > ContentManager.py line 841

### ISSUE THREAD

**Issue by anoduck** [HelloZeroNet/ZeroNet#2030]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5
  * Operating system: Ubuntu Disco
  * Web browser: Firefox 67.0 && Firefox Dev.
  * Tor status: enabled && always
  * Opened port: yes
  * Special configuration: N/A

### Step 2: Describe the problem:

When attempting to sign my site I receive the following error:

`VerifyError: Content too large 99999999B > 10485760B, aborting task... in main.py line 198 > ContentManager.py line 736 > ContentManager.py line 841`

#### Steps to reproduce:

  1. Have a large site
  2. Attempt to sign it.
  3. Receive error

#### Observed Results:

  * What happened?

https://asciinema.org/a/H5fTY5spiv3Pl8UeDrGd9Xqgj

#### Expected Results:

  * What did you expect to happen?

To sign and publish my site

**Comment by aomanchuria** [comment]
Just got the same error for my images site

**Comment by imachug** [comment]
Open sidebar, increase site size limit, profit.

**Comment by aomanchuria** [comment]
okay...

**Comment by aomanchuria** [comment]
AHHHHHHH! you grab the little site symbol at the upper right corner and you drag it to the left! then you reveal that side panel!  I get it!

**Comment by imachug** [comment]
That's right. If this resolves your issue, please close it.

**Comment by imachug** [comment]
@HelloZeroNet Could you close this issue please?

**Comment by aomanchuria** [comment]
unfortunately I can't I don't know how.
