### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yanxiatingyu** [HelloZeroNet/ZeroNet#2042]
What communication protocol is used between tracker and peer? Is it the http protocol like bittorrent? Between peer and peer? Thanks

**Comment by imachug** [comment]
ZeroNet uses its own protocol for p2p.

As for trackers, you have to define what trackers you're taking about. There are zero:// trackers, which are actually other ZeroNet peers, which use ZeroNet's own protocol. For other trackers, the classic way (that all torrent trackers use) is used (check the code [here](https://github.com/HelloZeroNet/ZeroNet/blob/116347ef669d8cadf92f6698171fa5d439ae6cb3/src/Site/SiteAnnouncer.py#L325)).
