### ISSUE TITLE
Zeronet community will always be small due to license

### ISSUE THREAD

**Issue by Corsairs** [HelloZeroNet/ZeroNet#2048]
I read the license and was a bit shocked
https://github.com/HelloZeroNet/ZeroNet/blob/master/LICENSE

 Copyright (C) 1989, 1991 Free Software Foundation, Inc., <http://fsf.org/>
 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, **but changing it is not allowed.**

 **State changes
 Disclose source
 Same license**

What we have, you can not sell a product without the source code, you can not change the code and even the name, you can not sell without the source code.

Maybe I'm wrong, but I see it like that.

In fact, we get a project that is fighting for decentralization but does not support it itself.

I believe that we need a license where the zeronet allows everyone to change the license is the main thing that should symbolize the zeronet.

https://github.com/bitcoin/bitcoin/blob/master/COPYING

**Comment by ValdikSS** [comment]
You're misunderstanding license text.

This license is GNU GPLv2, a pretty common license for software. Linux kernel uses it.
"but changing it is not allowed" refers to the license text, not to the source code of the software. You're not allowed to change the license text, but you allowed to change the source code.
You're indeed obligated to provide source code of ZeroNet and changes to the source code if you do any modifications, but it is allowed to sell both ZeroNet and your own software which uses ZeroNet.
You can use ZeroNet in your non-GPL software and you don't need to disclose code of your software as long as you use it via console API or browser HTML API and do not directly integrate it into your own (python) application.

>I believe that we need a license where the zeronet allows everyone to change the license is the main thing that should symbolize the zeronet.

What does that mean? Why you want to change the license of any software, and how do you imagine that? MIT license of Bitcoin (the one you linked) does not allow that either (it allows sublicensing though, but that's different matter).

I recommend you to find out more about software licenses. There are a lot of explanations on the internet if you don't understand exact text of the license.
