### ISSUE TITLE
Pinned status not visible with long file names

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2051]
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1561523274_16NS3rBdW9zpLmLSQoD8nLTtNVsRFtVBhd/My+videos+on+KopyKate+are+not+auto+pinned+but+on+my+site+my+videos+are

**Comment by styromaniac** [comment]
Actually, they are auto-pinned, but the files tab on ZeroHello has text overflowing the rows. ZH needs fixing,

Also, a reminder that maybe we need to have it ask whether or not you want to sync all your files on a per site or every site basis.

**Comment by styromaniac** [comment]
This should probably be relabeled or closed.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I made a change on ZeroHello that will break the file name if necessary to display the pinned status: https://github.com/HelloZeroNet/ZeroHello/commit/58db466d54dc1a656a4eea8d0ed34fa455e37d91

**Comment by styromaniac** [comment]
Please add width to between the column separators. The checkboxes are tiny buttons next to URLs. If you accidentally click the URL, you have to select them again.

Place in the right panel a toggle to pin/download and unpin own files for the visited site.

On ZH in the files tab, expand this option for all seeded sites with one toggle.
