### ISSUE TITLE
Change default branch to py3

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#2054]
As far as I know, `master` branch hasn't been updated recently, and most development is done on `py3` branch. I propose changing the default branch to `py3`, which will:

1. Make it easier to make PRs and not get weird "This PR cannot be automatically merged" messages because of wrong target branch,
2. Show the most recent on the home repository page,
3. And will calculate the contributions in GitHub Insights.

**Comment by HelloZeroNet** [comment]
Yeah, I think time to do that. Possible ways:
 - Make a new branch from current master as "Py2", merge Py3 to master
 - Rename current master to Py2, rename Py3 to master (actually I never renamed a branch, so not sure if it works)

**Comment by imachug** [comment]
I would vote against 2. - this means that we would have to force-push master, thus people who prefer to use `git pull` will make a merge commit, and PRs would become a mess than (they have a merge commit, you don't, etc.). So I vote for 1.

**Comment by filips123** [comment]
@HelloZeroNet Is there any update about ZeroBundle for Python 3?

**Comment by HelloZeroNet** [comment]
I just changed the default branch on GitHub to py3.

Bundle for Linux 64bit coming soon. (I almost finished it) Do you think if we need 32bit versions?
Windows bundle link added to readme.md

**Comment by imachug** [comment]
Closing as fixed
