### ISSUE TITLE
On dark theme highlighted search words are not visible.

### ISSUE THREAD

**Issue by kotenok2000** [HelloZeroNet/ZeroNet#2055]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5 rev3866
  * Operating system: windows 10
  * Web browser: 
  * Tor status: available
  * Opened port: yes
  * Special configuration: ____

### Step 2: Describe the problem:
https://imgur.com/a/WTiKk5L
#### Steps to reproduce:

  1. _____On dark theme highlighted search words are not visible.
  2. _____
  3. _____

#### Observed Results:
On dark theme highlighted search words are not visible.  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.
https://imgur.com/a/WTiKk5L

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, should be fixed by https://github.com/HelloZeroNet/ZeroHello/commit/2ce7015316d1727d0094ecc7e0099e6d154db4a5
