### ISSUE TITLE
Allow Pointer Lock API in iframe

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroNet#2057]
[Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API) is blocked in sandboxed iframes. Can you allow it for usage?

**Comment by imachug** [comment]
Looks like adding `allow-pointer-lock` to iframe sandbox is enough. I'll make a PR right now

**Comment by imachug** [comment]
There, done.

**Comment by filips123** [comment]
@imachug It works with your fix. Thank you.

**Comment by imachug** [comment]
@filips123 The change to py3 branch has been merged. Is this enough to mark this issue as closed?

**Comment by filips123** [comment]
@imachug If needed it can also be merged into Python 2. Do you think this is needed? If not, I will close this issue?

**Comment by imachug** [comment]
Python 2 isn't actively maintained, and Python 3 supports a lot more features already, and ZeroBundle and such switch to Python 3 soon -- so, personally, I think we can close this. @HelloZeroNet, please reopen this if I'm wrong.

**Comment by filips123** [comment]
Ok

**Comment by HelloZeroNet** [comment]
Yeah, the python2 version only receives bugfixes. For new features it's recommended to update to the py3 version.

**Comment by filips123** [comment]
@HelloZeroNet When will ZeroBundle for Python 3 be ready?
