### ISSUE TITLE
When access is forbidden using ui_restrict, it should also forbid the access to the login page of ui_password

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#207]

**Comment by grez911** [comment]
@HelloZeroNet Please, review https://github.com/HelloZeroNet/ZeroNet/pull/1082

**Comment by grez911** [comment]
@HelloZeroNet Please, review the pull request.

**Comment by grez911** [comment]
@TheNain38 @HelloZeroNet Please, close.
