### ISSUE TITLE
ZeroHello all buttons unresponsive. No menus pop-up

### ISSUE THREAD

**Issue by madsci1016** [HelloZeroNet/ZeroNet#2075]
I have a node that was working fine, but now on ZeroHello none of the menus (like trackers, Tor, Port or any of the site sub menu accessed through the three little buttons) will open. I can open sites and they work fine, just can't get to any menus on ZeroHello. 

Tried multiple browsers. 

Single error in browser console goes :
`Uncaught TypeError: Cannot read property 'date_added' of undefined
    at FeedList.render (all.js?lang=en&site_modified=1562292014:2758)
    at Array.<anonymous> (all.js?lang=en&site_modified=1562292014:2189)
    at doRender (all.js?lang=en&site_modified=1562292014:920)`

Related?

**Comment by Merith-TK** [comment]
Having this issue as well.

**Comment by geekless** [comment]
This should probably be reported to https://github.com/HelloZeroNet/ZeroHello/issues

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed by https://github.com/HelloZeroNet/ZeroHello/commit/070516782c3817a2eb35c28f477f84116bf043a2

**Comment by madsci1016** [comment]
Confirmed, thanks.
