### ISSUE TITLE
How to recovery ZeroID?

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2076]
SO basically, i had the ZeroID user `merithtk`
Issue is, i pulled a dumb while trying to debug a issue i was having and delete my folder, is there a WAY at ALL to recover this? or is it just lost to the void?

**Comment by Merith-TK** [comment]
Update, I used recovery software to get my certificate files back
the ones highlighted. Do i just... drop them in?

![image](https://user-images.githubusercontent.com/10422110/60750082-56942a80-9f58-11e9-8216-da43e2fcb929.png)

**Comment by Merith-TK** [comment]
Okay, so the `sites.json` file is INDEED important, thought it was a backup of what sites you've been on. also the sites config for `zeroid.bit` IS important to keep your id's

**Comment by Merith-TK** [comment]
Still dont have my login certificate?
![image](https://user-images.githubusercontent.com/10422110/60750512-41ba9580-9f5e-11e9-9603-ea297edb454f.png)

**Comment by geekless** [comment]
You need your old users.json to put in place of the new one to recover the old ID.

**Comment by Merith-TK** [comment]
I have that, it's still not recovering my data.

**Comment by Merith-TK** [comment]
Unfortunately, all that is in there (for some reason) is a entry for the hello page.

**Comment by Merith-TK** [comment]
I found my issue. 

the recovered file had lost a good chunk of the last site config at the bottom. because of this, the syntax was BROKEN and i had to use VSCode to double check the syntax
(ended with
```
      <REDACT>": {
        "auth_address": "<REDACT>", 
        "auth_privatekey": "<REDACT>"
      },
```
instead of the proper 
```
       <REDACT>": {
        "auth_address": "<REDACT>", 
        "auth_privatekey": "<REDACT>"
      }
    }
  }
}
```



I would recommend there being a easy backup button to make sure its intact

**Comment by imachug** [comment]
In most cases, it's next to impossible to recover JSON, as it may be corrupted in several ways. So I don't think that making a "make everything work" button is possible.

**Comment by geekless** [comment]
> In most cases, it's next to impossible to recover JSON, as it may be corrupted in several ways. So I don't think that making a "make everything work" button is possible.

Maybe, some plugin for making an encrypted (with a user-supplied password) backup of the master seed? And for restoring it as well.

**Comment by Merith-TK** [comment]
I think Geekless is onto something?

**Comment by rllola** [comment]
+1 for @geekless 

Are you thinking of having it backed up on the user computer or on a server ? If it is encrypted with a strong password the latest would be reasonable but let's be honest users don't know how to pick password...

**Comment by Merith-TK** [comment]
I think the users pc, like store it in a password protected zip file or
encode it in the backup location, perhaps using a cryptographic key (same
style used by the zites service,)

It's just a thought that would be neat to see implemented,

Most of the hard part would be getting the encryption thing to work right,
or maybe have a one click button that just copies it into a encrypted zip
file using the home zite link as the encryption key, so that way it will be
tougg to crack for people not on the ZeroNetwork.

**Comment by rllola** [comment]
I think it is a great idea.

We can even imagine to let the user do it from the ZeroHello page like for the update.

**Comment by Merith-TK** [comment]
I really need to brush up on my python.. I'm a bash script junket...

**Comment by rllola** [comment]
It seems that this lib doesn't support the creation of encrypted zip. It only allows you to extract it. So we will need an other library or to use a command line. The latest might be a bit tricky if we want to have it working on the all 3 platforms.

**Comment by Merith-TK** [comment]
Maybe utilize some native system stuff?


I've used If statements ALOT (look at akg-git) and maybe in the python, we
can see what system is it being run on, (windows/cygwin will be using the
same libraries) and for Linux/Mac, use libraries that work for that?
