### ISSUE TITLE
[Proposal]: Prompt for authentification based on interface

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#209]
There should be an option to choose wether or not prompt for authentification based on interface

**Comment by HelloZeroNet** [comment]
Not sure what do you mean

**Comment by TheNain38** [comment]
For example: If you connect on loopback interface it didn't prompt for authentification, but if it is the LAN or WAN interface then it could prompt for authentification

**Comment by HelloZeroNet** [comment]
You can use the "Keep signed in" checkbox to keep your computer password-less on loopback

**Comment by TheNain38** [comment]
Yes, I didn't think of that, you can close this issue if you want

**Comment by HelloZeroNet** [comment]
It could still make sense, but i think its not worth the added complexity
