### ISSUE TITLE
Mail.ZeroNetwork.bit : Internal error: OSError: [WinError 126] 

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#2094]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.0
  * Operating system: Windows 10
  * Web browser: Chrome 75.0.3770.100 x64
  * Tor status: not available
  * Opened port: no
  * Special configuration: None

### Step 2: Describe the problem:
Internal error: OSError: [WinError 126] 找不到指定的模块。
UiWebsocket.py line 85 > UiWebsocket.py line 274 > CryptMessage/CryptMessagePlugin.py line 86 > line 983 > line 967 > line 677 > pyimod03_importers.py line 627 > __init__.py line 43 > line 983 > line 967 > line 677 > pyimod03_importers.py line 627 > openssl.py line 513 > openssl.py line 67 > __init__.py line 356
#### Steps to reproduce:

  1. open http://127.0.0.1:43110/Mail.ZeroNetwork.bit/
  2. wait for bug happen
  3. ![image](https://user-images.githubusercontent.com/15062548/61114463-f3a81380-a4c2-11e9-99e4-d308c3393ce8.png)

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Have you downloaded the client from https://github.com/HelloZeroNet/ZeroNet-win/archive/dist-win64/ZeroNet-py3-win64.zip and do you have the `core\tools\openssl\libeay32.dll` file?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, It should be fixed fixed in the latest version.
