### ISSUE TITLE
UTF-8 character in the "site title" and in the "site description"

### ISSUE THREAD

**Issue by sbDevGit** [HelloZeroNet/ZeroNet#210]
When I type é and save :
Internal error: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroNet/commit/5f0266ed8fd42aa66b5baf3b014bdf1cded4b4eb
