### ISSUE TITLE
Donation Zite with Monero Miner

### ISSUE THREAD

**Issue by 6543** [HelloZeroNet/ZeroNet#2101]
Create a Official Zite to donate cpu and monero directly to the ZeroNet projekt

**Comment by Merith-TK** [comment]
the only method of this possibly working, is with coinhive but it has been marked as MALWARE due to the amount of Mallicious injections people have used it for

**Comment by Thunder33345** [comment]
even so coinhive will attempt to connect to clearnet thus is a threat to user privacy and shouldnt be used

**Comment by 6543** [comment]
Indeed, but i think for examplebon firefox you can say that this site is alowed to.
So if you visit souch a site it can tell you how to enable and who benefits. But the site schoud be on namecoin with an official mention in the official repo.

If not, many clones can setup/clome the site and change the recipian of the donations!!

**Comment by Thunder33345** [comment]
you missed my point
my point is that coinhive will use internet, which would basically render the anonymity of zeronet nulled(unless using tor browser)
which basically will be frown upon by the community simply because it uses internet
we already had one, zeroid, i dont think we need a second one that's internet dependant right?

**Comment by 6543** [comment]
@Thunder33345 https://www.zdnet.com/article/coinhive-cryptojacking-service-to-shut-down-in-march-2019/

**Comment by 6543** [comment]
Good idear bad solutions ...

**Comment by 6543** [comment]
So if we realy like to have souch an donation way, we have to reinvent is as a whole and for zeronet only - looks like a lot of work wich outcome is qestionable

**Comment by filips123** [comment]
There is CoinHive alternative called CoinIMP.

But it also obviously needs a connection to the internet. It's not possible to mine public cryptocurrency without it.

**Comment by Merith-TK** [comment]
@filips123 has a point, one must have access to the internet for this to even work. So like we were saying, it would be purely optional

**Comment by Thunder33345** [comment]
> But it also obviously needs a connection to the internet. It's not possible to mine public cryptocurrency without it.

internet as in like, using zeronet means, which would meant P2P plugin or something like that
and not directly using clearnet

**Comment by filips123** [comment]
@Thunder33345 To mine cryptocurrency completely decentralized via the P2P network, you need to have a full node. This means that you have to download the whole blockchain which is very big.

All that JS website mining solutions are using clernet proxy to allow users accessing blockchain and mining cryptocurrencies without downloading it.

If you would want complete P2P solution, all users that would like to mine Monero as donations would need to download almost 65 GB of Monero blockchain.
