### ISSUE TITLE
How to know which python version the client is using ?

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroNet#2104]
I was wondering if there is a way to know which python the user have ? I am interesting in this to make a smart guess on which version of the plugin I want to show for download.

If we can't do that could we add an api for that ?

I know that it is the last year that python 2 is supported so it is maybe not that useful but it might come handy for plugin devs.

**Comment by HelloZeroNet** [comment]
Anything above Rev4000 is a python3 based client, before that is python2
