### ISSUE TITLE
Unhandled exception: ImportError: bad magic number in 'geventwebsocket': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by shamies** [HelloZeroNet/ZeroNet#2111]
### Step 1: Please describe your environment

  * ZeroNet version: _____
  * Operating system: _____
  * Web browser: _____
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by devarped** [comment]
Why did you close this? Did you fix the issue? If yes, would you mind telling us how?

**Comment by devarped** [comment]
Whatever, I've found a solution (delete all .pyc files) myself.
