### ISSUE TITLE
zn.amorgan.xyz never connects to my node

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2112]
Both are on Py2 branch. ZeroNet-Kivy here, as usual.

Somehow there's a fragmentation here. It doesn't matter which ISP I use. T-Mobile has open ports, so no problem with ports while outdoors, yet this issue I report persists either way. I see no problem with trackers. The proxy produces errors trying to download updated optional index.html files from Kave. My new optional files don't download to the proxy from Kave nor KopyKate BIG Official. Storage space remaining are plenty on both.

>DATA/BLENDERMOVIES/INDEX.HTML DOWNLOAD FAILED

Proxy: rev3863, Tor Available
Mine: rev3866, Tor Disabled

Until other peers download these optional files, the proxy won't be retrieving them.

0net.io is also struggling. 0net.eu.org too.

Are all these proxies in Europe?! None are connecting to my node.

Not a single working proxy connects. I've tried them all.

**Comment by HelloZeroNet** [comment]
Do you have "in" connections on the /Stats page?

**Comment by styromaniac** [comment]
Incoming? That's 0%

**Comment by HelloZeroNet** [comment]
Then probably your are not actually in connectable mode, so you can't accept incoming connections. In this mode creating new site or uploading optional files can be problematic.

**Comment by styromaniac** [comment]
What's the solution? Port forwarding? Why do required files distribute but optional files don't? Makes no sense to me.

**Comment by HelloZeroNet** [comment]
Port forwarding or enable tor. 

You can push the changed non-optional files to any connectable peer. 

For optional files when a client receives a new content.json and it has auto-download enabled it will start to look for peers that has that new, added file, then connect to them. 

So the client don't know who will interested in your new optional file, so you can't connect to them, they have to find and connect to you.

**Comment by styromaniac** [comment]
I'll close this until I find anything unusual.
