### ISSUE TITLE
Keeping files online forewer using the Safe Network (chunk+copy) file storage technology

### ISSUE THREAD

**Issue by mx5kevin** [HelloZeroNet/ZeroNet#2113]
**Is your feature request related to a problem? Please describe.**

File Storage Problem:

- I'ts not possible to keep online the files 24/7 without non stop running the compjuter.
- Large (Optional Files) goes fast offline. But the system are indexed them forewer in the system.
- If the file are not popular and have periodic downloads the bandwidth are limited.
- Must wait all File/Zite owner to a downloader too keep the file online. Without this not possible to upload the files in the system. And reduce minimal the server electrocity costs.
- Users must wait sometimes too long to get a file. Or the file are newer get downloaded
- In clearnet all files 24/7 avaible. With high download speed.
- Playing  problems with streamable HTML5 media files. Wheare users need to get the files directly, high download speed, with stable download process.
- If a user have low upload speed. And sharing lot of files. Another users can download the files from other sources. So the bandwidth will be high an unlimited.

Security issue:

- Tourgh VPN, TOR ALWAYS MODE, or PROXY with test downloads i'ts possible to monitor the current user tracing back the download/upload traffic if only one people seed the current file. If tourgh 1 tunnel this data collected to serval users I'ts not so easy to track back the site or file owner.

- Less visited optional files not resistence for censorship. If the owner are shooted down the file are dead. So with the current setup its possible to shoot down large sites. Wheare the zite have many visitors. But incude many optional files what have variable seeder. And wheare wee need minimum 1 seeder who have all files. If wee need too keep all files online. If we talk about large services the chance is getting bigger only the site owner have all files.

**Describe the solution you'd like**

Description of the technology: https://www.youtube.com/watch?v=U1ffmf6z50E
                                              And
                                               https://www.youtube.com/watch?v=RdGH40oUVDY
                                            
A storage system where stored all files in chunks in a encrypted data storage. And multiple copies of the files. In the ZeroNet usrers compjuters. Distributed among themselves the data. And when a user need a file collect the pieces from another ZeroNet users. The users are store only chunks and not the full file. So their does not have to wory the are storing illegal content. And file owners can upload to this storage and does not have to wait a users who download the current file or zite and help to seed it. This is a secondary storage what helping and fix the issues with the current storage system.

**Describe alternatives you've considered**

https://safenetwork.org/

Similar techology

https://freenetproject.org/

**Comment by HelloZeroNet** [comment]
I'm prefer to know what files I'm actually hosting instead of random data, but if you want to you can use freenet/madisafe to serve the big files .
