### ISSUE TITLE
recover ZeroID

### ISSUE THREAD

**Issue by ZarkBit** [HelloZeroNet/ZeroNet#212]
hello all, how can I recover my old ZeroID account? my old ZeroNet folder got kaput.

**Comment by TheNain38** [comment]
@ZarkBit Normally if you don't have a backup of data/users.json you cannot recover it :(
This file contains all your identites and it also contains your certs. And the ZeroID account is a cert

**Comment by TheNain38** [comment]
@HelloZeroNet This issue can be closed? The op don't seems to be here...
