### ISSUE TITLE
ZeroNet doesn't reconnect to trackers after a few minutes of internet disconnection.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2121]
My cell service is suspended at the moment and as a result I see ZeroNet only connects to two trackers at most after at least a few minutes without internet connectivity. Sometimes it's no trackers. Restarting ZeroNet is required to resolve it. I think the tracker rating algorithm doesn't take into account temporary internet service interruption.

How it rates trackers should be done in comparison to other trackers or... if none work, don't rate them poorly. One and/or the other would prevent this bug if I understand how ZeroNet handles trackers.

**Comment by styromaniac** [comment]
This is getting really annoying having to restart ZeroNet between distant hotspots.

**Comment by HelloZeroNet** [comment]
I made some changes in the recent version:
 - It won't increment the error value if no internet connection detected https://github.com/HelloZeroNet/ZeroNet/commit/3696db89ab40279072a40ced8a655fc23822dc13
 - It will announce to all trackers in force mode: https://github.com/HelloZeroNet/ZeroNet/commit/eeaa5d21d8e96f7627116feb99a8118310ca23a6
