### ISSUE TITLE
Unable to connect to ZeroNet (over Whonix Gateway setup)

### ISSUE THREAD

**Issue by lks7hda** [HelloZeroNet/ZeroNet#2124]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.4 Rev3660
  * Operating system: Ubuntu (Whonix)
  * Web browser: Tor (Whonix)
  * Tor status: always
  * Opened port: yes
  * Special configuration: VPN on host (Ubuntu); fresh an updated Whonix setup

### Step 2: Describe the problem:
cannot launch ZeroNet

#### Steps to reproduce:

followed installation instraction on
https://www.whonix.org/wiki/ZeroNet

#### Observed Results:

user@host:~/ZeroNet$ ./zeronet.py --tor always --fileserver_ip 10.152.152.11
- Starting ZeroNet...
['/home/user/ZeroNet/src', '/home/user/ZeroNet/src/lib', '/home/user/ZeroNet', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/home/user/ZeroNet/plugins']
[13:15:55] PluginManager Plugin AnnounceBitTorrent load error: ModuleNotFoundError: No module named 'bencode' in PluginManager.py line 139 > AnnounceBitTorrent/__init__.py line 1 > AnnounceBitTorrent/AnnounceBitTorrentPlugin.py line 6
[13:15:55] PluginManager Plugin AnnounceLocal load error: ModuleNotFoundError: No module named 'msgpack' in PluginManager.py line 139 > AnnounceLocal/__init__.py line 1 > AnnounceLocal/AnnounceLocalPlugin.py line 7 > AnnounceLocal/BroadcastServer.py line 8 > Msgpack.py line 5
[13:15:55] PluginManager Plugin Bigfile load error: ModuleNotFoundError: No module named 'merkletools' in PluginManager.py line 139 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[13:15:55] - Libsecp256k1 load failed: No module named 'coincurve', try to load OpenSSL
[13:15:55] - OpenSSL load failed: No module named 'bitcoin', falling back to slow bitcoin verify
[13:15:55] - Unhandled exception: No module named 'geventwebsocket'
Traceback (most recent call last):
  File "./zeronet.py", line 18, in main
    import main
  File "/home/user/ZeroNet/src/main.py", line 63, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/home/user/ZeroNet/src/Plugin/PluginManager.py", line 148, in loadPlugins
    func()
  File "/home/user/ZeroNet/plugins/UiConfig/UiConfigPlugin.py", line 17, in importPluginnedClasses
    from Ui import UiWebsocket
  File "/home/user/ZeroNet/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/home/user/ZeroNet/src/Ui/UiServer.py", line 10, in <module>
    from geventwebsocket.handler import WebSocketHandler
ModuleNotFoundError: No module named 'geventwebsocket'
---

#### Expected Results:

launch ZeroNet; access 127.0.0.1:43110

**Comment by HelloZeroNet** [comment]
Please try to run `sudo python3 -m pip install -r requirements.txt` as the documentation on the wiki is a created for previous version (python2-based) of zeronet.

**Comment by lks7hda** [comment]
```
user@host:~$ sudo python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
```

So, I installed pip
`user@host:~$ sudo apt install python-pip`
`user@host:~$ sudo apt install python3-pip`
```
user@host:~$ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

```
user@host:~/ZeroNet$ sudo python3 -m pip install -r requirements.txt
Requirement already satisfied: gevent>=1.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.3.7)
Collecting msgpack>=0.4.4 (from -r requirements.txt (line 2))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x77e03b4a2e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/msgpack/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x77e03b4ba048>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/msgpack/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x77e03ba76208>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/msgpack/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x77e03ab48978>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/msgpack/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x77e03ab489b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/msgpack/
  Could not find a version that satisfies the requirement msgpack>=0.4.4 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for msgpack>=0.4.4 (from -r requirements.txt (line 2))
```
checked msgpack-python

```
user@host:~$ sudo apt-get install msgpack-python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python-msgpack' instead of 'msgpack-python'
python-msgpack is already the newest version (0.5.6-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by lks7hda** [comment]
Wait I see a mistake in my setup let me double check this first !
I will use my snapshot and start from the beginning.
I'll come back to you with a status update.

**Comment by lks7hda** [comment]
`sudo python3 -m pip install -r requirements.txt` worked !
Thanks for your support

Looking forward to ZeroNet :)
