### ISSUE TITLE
ModuleNotFoundError: No module named 'geventwebsocket'

### ISSUE THREAD

**Issue by jodobear** [HelloZeroNet/ZeroNet#2127]
### Environment:

  * ZeroNet version: ZeroNet-py3.tar.gz
  * Operating system: Linux Mint 19 Tara
  * Web browser:  n.a.
  * Tor status: not available
  * Opened port: n.a.
  * Special configuration: venv

### Problem:

When executing `zeronet.py` i get the error `ModuleNotFoundError: No module named 'geventwebsocket'`

#### Steps to reproduce:

  1. Untar zeronet
  2. Start venv, install requirements
  3. execute `python3 zeronet.py`

#### Observed Results:

Requirements.txt has `websocket-client` and `gevent-websocket` lines but, I guess they are broken?

![zeronet-websocketError](https://user-images.githubusercontent.com/36855907/62533826-e83cd380-b847-11e9-8057-c6dd1d321deb.png)

#### Expected Results:

Requirements.txt to install the dependencies and for zeronet to work.

**Comment by HelloZeroNet** [comment]
It happened because it installed dependencies to python2. 

Thanks for reporting, I just corrected the instructions: https://github.com/HelloZeroNet/ZeroNet#other-platforms-install-from-source
