### ISSUE TITLE
Unhandled exception: ArgumentError: argument --multiuser_local: conflicting option string: --multiuser_local

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2130]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.0 (rev4163)
  * Operating system: W10
  * Web browser: FF

### Step 2: Describe the problem:

Yesterday i was exploring the http://127.0.0.1:43110/Plugins/ page first time, surprisingly on first page load, it disabled multiuser_local plugin for me without me requesting that. I clicked the switch to enable it again. Today i did zeronet restart (it was due to the update i requested) and then during start, i seen the error in the title of this issue.

Error.log file:

> Traceback (most recent call last):
>   File "C:\ZeroNet-win-dist-win64\core\zeronet.py", line 18, in main
>     import main
>   File "C:\ZeroNet-win-dist-win64\core\src\main.py", line 64, in <module>
>     config.loadPlugins()
>   File "C:\ZeroNet-win-dist-win64\core\src\Config.py", line 461, in loadPlugins
>     ConfigPlugin(self)
>   File "C:\ZeroNet-win-dist-win64\core\src\Config.py", line 456, in __init__
>     self.createArguments()
>   File "C:\ZeroNet-win-dist-win64\core\plugins\disabled-Multiuser\MultiuserPlugin.py", line 234, in createArguments
>     return super(ConfigPlugin, self).createArguments()
>   File "C:\ZeroNet-win-dist-win64\core\plugins\Zeroname\UiRequestPlugin.py", line 30, in createArguments
>     return super(ConfigPlugin, self).createArguments()
>   File "C:\ZeroNet-win-dist-win64\core\plugins\Multiuser\MultiuserPlugin.py", line 230, in createArguments
>     group.add_argument('--multiuser_local', help="Enable unsafe Ui functions and write users to disk", action='store_true')
>   File "argparse.py", line 1367, in add_argument
>   File "argparse.py", line 1571, in _add_action
>   File "argparse.py", line 1381, in _add_action
>   File "argparse.py", line 1520, in _check_conflict
>   File "argparse.py", line 1529, in _handle_conflict_error
> argparse.ArgumentError: argument --multiuser_local: conflicting option string: --multiuser_local
> 

I found i had --multiuser_local switch in my program launcher, so i removed that. Also i had two Multiuser folders in plugins folder. One enabled (date of the folder was old) and one disabled (newer date of the folder). So i used newer one and older deleted. Now it is launching OK.

Regular user may not understand from the error i received that he has a duplicate plugin folder.
Unsure what does the /Plugins page if the plugin is in two folders (enabled, disabled)

**Comment by HelloZeroNet** [comment]
For me looks like you have both disabled-Multiuser and Multiuser directory in your plugins directory and this caused the error. Right now both plugin enabled.
I recommend to delete disabled-Multiuser plugin to fix the issue.

Since the last update there is two way to enable a disabled plugin: 
 - Rename the directory and remove the "disabled-" prefix (old way)
 - Enable it using the web ui: this way it won't rename the directory, but write the setting to data/plugins.json

**Comment by slrslr** [comment]
yes, that error appear when i have both "disabled-Multiuser" and "Multiuser" directory in my plugins directory, when i removed disabled* one as you suggested, it launch OK.
May be good if zeronet would ignore the "disabled-*" directory and proceed because there is enabled directory for the plugin. Or if it report easy readable explanation why it could not start (Multiuser plugin is duplicate in the ZeroNet/plugins directory).

**Comment by slrslr** [comment]
@HelloZeroNet this issue does not seem to be caused by me, but by zeronet inproperly copying the Multiuser plugin folder to disabled-Multiuser on Zeronet restart (during update). This does not happen on shutdown, but only on restart (probably during shutting down, not during boot).

Please check the script why it copying my plugin folder (happens only for a Multiuser plugin. As mentioned when i first visited the /Plugins page, i surprisingly found it marked Multiuser plugin as disabled, but i switched back to enabled.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was able to reproduce and fix the problem with the updater script: https://github.com/HelloZeroNet/ZeroNet/commit/7801937f74934553ab92d3014c73ef33c93feea4

I recommend to manually overwrite the updater script `update.py` with https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/py3/update.py to avoid the same problem at the next update

**Comment by slrslr** [comment]
yes, i tested and problem solved, thx
