### ISSUE TITLE
I have 0 trackers

### ISSUE THREAD

**Issue by alphapeg** [HelloZeroNet/ZeroNet#2134]
I have 0/49 trackers but able to write on zerotalk
![trackers on zeronet](https://user-images.githubusercontent.com/53961480/62817433-a4c2bd80-bb04-11e9-95cc-11dfeb4025dd.png)

**Comment by blurHY** [comment]
@HelloZeroNet As I said, ZeroNet is dying in China.
@alphapeg It's ok

**Comment by April93** [comment]
You can see that you *are* connecting to the trackers, but don't have 100% connection to them. IE some packets are properly sending, others are failing. AFAIK that means it should still be working?

**Comment by alphapeg** [comment]
@april93 yes and no I am able use zerotalk and mail but I can't go anywhere else, it freezes at 0 peers when entering a site.

**Comment by blurHY** [comment]
It's a common problem in China, but unfortunately, no solution except using a proxy.
________________________________

**Comment by styromaniac** [comment]
If you don't have the latest revision in the Py3 branch, it might be ZeroNet deferring trackers from a loss of internet connection.

I've reported this and that's where the fix would be. If that's the problem and you can't/won't upgrade to Py3 branch, then you have to restart when your internet connection resumes.

**Comment by alphapeg** [comment]
> 
> 
> If you don't have the latest revision in the Py3 branch, it might be ZeroNet deferring trackers from a loss of internet connection.
![outdated](https://user-images.githubusercontent.com/53961480/62827335-341ab000-bb9b-11e9-86a0-1f22016446cc.png)
> 
> I've reported this and that's where the fix would be. If that's the problem and you can't/won't upgrade to Py3 branch, then you have to restart when your internet connection resumes.

So, how do I get the latest revision? Restarting Zeronet doesn't work.
