### ISSUE TITLE
Fully Back End website support (PHP, MYSQL, NODEJS, etc) 

### ISSUE THREAD

**Issue by GeorgeGkas** [HelloZeroNet/ZeroNet#214]
Is it possible to host a forum or any website that uses PHP and MYSQL on ZeroNet? Cause I tried to add a `index.php` with mysql support sample and I got error `index.html` message.

It it possible to add it in future versions?

**Comment by HelloZeroNet** [comment]
With ZeroNet you have an SQL server running on localhost that is always accessible, so you don't need backend servers running nodejs or php.

P2P sites requires different thinking than traditional Client <-> Server approach, but porting single page applications could be possible. 

Presentation about how does ZeroNet works: https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000
And there a "Tutorial of creating server-less, SQL backed, real-time updated P2P chat application using ZeroNet in less than 100 lines of code" in ZeroBlog

**Comment by GeorgeGkas** [comment]
And if I want to use PHP code eg. to read SQL, manage files, etc can I do it ?

**Comment by HelloZeroNet** [comment]
You have to use javascript + html, executing php/python/etc. code would not be safe.

**Comment by GeorgeGkas** [comment]
of course it wouldn't. Hmmm ok thank you. It's a good project.
