### ISSUE TITLE
Load debug variable from zeronet.conf, like in version

### ISSUE THREAD

**Issue by mkg20001** [HelloZeroNet/ZeroNet#2140]
### Step 1: Please describe your environment

  * ZeroNet version: Rev4172
  * Operating system: Android 9 / LOS 16
  * Web browser: Firefox Klar Android
  * Tor status: not available
  * Opened port: no
  * Special configuration: android

#### Steps to reproduce:

  1. Set `debug = ` in zeronet.conf, which did enable debug mode in python2 version
  2. Launch zeronet android app

#### Observed Results:

  * zeronet starts without debug mode

#### Expected Results:

  * It should start in debug mode, like the python2 version did

#### Background:

It's hard to set cli arguments in the service, since it gets started in a nonstandard way. As such, having the option of setting things via zeronet.conf would be nice.

**Comment by imachug** [comment]
Works fine for me on laptop (Win7). Can you reproduce the bug on a desktop or on mobile only?

**Comment by mkg20001** [comment]
Just read through the logs. Seems to actually work fine (`Config(...debug=True)`), but I assumed debug was disabled since it doesn't print any error messages. Currently trying to figure out what doesn't work that it can't download zerohello.

In that case, why isn't it printing those error messages anywhere? Or is there another debug flag for connection/fetching debugging?

**Comment by imachug** [comment]
`debug_socket`

**Comment by mkg20001** [comment]
I'll test it and close the issue afterwards

**Comment by imachug** [comment]
@mkg20001 Have you tried it yet? :D

**Comment by mkg20001** [comment]
It seems to be enabled, but I couldn't yet verify because I had another issue and then didn't have any more time to develop the app for now.

So, I'll assume that this works and close the issue now ^^
