### ISSUE TITLE
failed loading Libsecp256k1 and OpenSSL lib, under termux, falling back to slow bitcoin verify.

### ISSUE THREAD

**Issue by peter-tank** [HelloZeroNet/ZeroNet#2143]
---
name: Bug report
about: Create a report to help us improve ZeroNet
title: 'failed loading Libsecp256k1 and OpenSSL lib, under termux, falling back to slow bitcoin verify.'
labels: 'Libsecp256k1, OpenSSL, termux'
assignees: ''

---

### Step 1: Please describe your environment

  * ZeroNet version: rev4176
  * Operating system: android (aarch64)
  * Web browser: Firefox, Chrome
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: `--ui_ip "127.0.0.1 --proxy 127.0.0.1:1080 --trackers_proxy 127.0.0.1:1080 --ip_external <external_ipaddress>`

#### Steps to reproduce:

  1. apt install python
  2. make install [Libsecp256k1](https://github.com/bitcoin-core/secp256k1){commit fa3301713549d118e57ebe6551d062903ddd6b63}
  3. make install [OpenSSL](https://www.openssl.org/source/openssl-1.0.2s.tar.gz)
  4. apt install virtualenv
  5. virtualenv --system-site-packages --no-download --python=python3.7 "zeronet_py3"
  6. source "zeronet_py3/bin/activate"
  7. pip install -r "${pwd}/ZeroNet-py3/requirements.txt"
  8. pip list
```Package           Version  
----------------- ---------
asn1crypto        0.24.0   
base58            1.0.3    
bencode.py        2.1.0    
certifi           2019.6.16
cffi              1.12.3   
chardet           3.0.4    
coincurve         12.0.0   
gevent            1.4.0    
gevent-websocket  0.10.1   
greenlet          0.4.15   
idna              2.8      
libsecp256k1      0.1      
maxminddb         1.4.1    
merkletools       1.0.3    
msgpack           0.6.1    
pip               19.2.1   
pyasn1            0.4.6    
pycparser         2.19     
pyelliptic        1.5.6    
pysha3            1.0.2    
PySocks           1.7.0    
python-bitcoinlib 0.10.1   
rsa               4.0      
setuptools        41.0.1   
six               1.12.0   
urllib3           1.25.3   
virtualenv        16.7.2   
websocket-client  0.56.0   
wheel             0.33.4
```

#### Observed Results:

  * (zeronet_py3) $
    > `python -V`
    > Python 3.7.4
    > `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`
    > OpenSSL 1.1.1c  28 May 2019
    > `
  * start zeronet in DEBUG mode
    > Watchdog fs listener could not be loaded: No module named 'watchdog'
    > PluginManager Loading plugin: CryptMessage (builtin)
    > WARNING: linker: /data/data/com.termux/files/home/zeronet_py3/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x2f8
    > WARNING: linker: libsecp256k1.so.0: unused DT entry: type 0x6ffffef5 arg 0x300
    > Libsecp256k1 load failed: dlopen failed: cannot locate symbol "secp256k1_ecdsa_recoverable_signature_convert" referenced by "/data/data/com.termux/files/home/zeronet_py3/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m.so"..., try to load OpenSSL
    > OpenSSL lib not found in: /data/data/com.termux/files/usr/lib (list index out of range)
    > Gevent block checker started
    > OpenSSL load failed: undefined symbol: SSLeay, falling back to slow bitcoin verify

#### Expected Results:

  * "Slow verifycation library" warnings in ZeroHello Page.

**Comment by HelloZeroNet** [comment]
Based on https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233456

you have to configure libsecp256k with `--enable-experimental --enable-module-ecdh --enable-module-recovery` options

**Comment by peter-tank** [comment]
@HelloZeroNet Thanks for the details, fixed now:
  > INFO     - Libsecpk256k1 loaded: CompiledLib in 0.969s
