### ISSUE TITLE
failed in BroadcastServer: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0

### ISSUE THREAD

**Issue by peter-tank** [HelloZeroNet/ZeroNet#2144]
---
name: Bug report
about: Create a report to help us improve ZeroNet
title: "failed in BroadcastServer: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0"
labels: 'BroadcastServer, termux'
assignees: ''

---

### Step 1: Please describe your environment

  * ZeroNet version: rev4176
  * Operating system: android (aarch64)
  * Web browser: Firefox, Chrome
  * Tor status: disabled
  * Opened port: yes
  * Special configuration: `--ui_ip "127.0.0.1 --proxy 127.0.0.1:1080 --trackers_proxy 127.0.0.1:1080 --ip_external <external_ipaddress>`

#### Steps to reproduce:

  1. apt install python
  2. make install [Libsecp256k1](https://github.com/bitcoin-core/secp256k1){commit fa3301713549d118e57ebe6551d062903ddd6b63}
  3. make install [OpenSSL](https://www.openssl.org/source/openssl-1.0.2s.tar.gz)
  4. apt install virtualenv
  5. virtualenv --system-site-packages --no-download --python=python3.7 "zeronet_py3"
  6. source "zeronet_py3/bin/activate"
  7. pip install -r "${pwd}/ZeroNet-py3/requirements.txt"
  8. pip list
```Package           Version  
----------------- ---------
asn1crypto        0.24.0   
base58            1.0.3    
bencode.py        2.1.0    
certifi           2019.6.16
cffi              1.12.3   
chardet           3.0.4    
coincurve         12.0.0   
gevent            1.4.0    
gevent-websocket  0.10.1   
greenlet          0.4.15   
idna              2.8      
libsecp256k1      0.1      
maxminddb         1.4.1    
merkletools       1.0.3    
msgpack           0.6.1    
pip               19.2.1   
pyasn1            0.4.6    
pycparser         2.19     
pyelliptic        1.5.6    
pysha3            1.0.2    
PySocks           1.7.0    
python-bitcoinlib 0.10.1   
rsa               4.0      
setuptools        41.0.1   
six               1.12.0   
urllib3           1.25.3   
virtualenv        16.7.2   
websocket-client  0.56.0   
wheel             0.33.4
```

#### Observed Results:

  * (zeronet_py3) $
    > `python -V`
    > Python 3.7.4
    > `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`
    > OpenSSL 1.1.1c  28 May 2019
    > `
  * start zeronet in DEBUG mode
    > Watchdog fs listener could not be loaded: No module named 'watchdog'
    >  DEBUG    ConnServer Conn# 4 100.36.xxx.xx [?] > Closing connection: 100.36.xxx.xx Connect error: ModuleNotFoundError: No module named 'lib.PySocks' in ConnectionServer.py line 208 > Connection.py line 132, waiting_requests: 0, sites: 0, buff: 0...
    > INFO     - Creating FileServer....
    > ERROR    FileServer IPv6 check error: 'super' object has no attribute 'bind'
    > DEBUG    ConnServer Supported IP types: ['ipv4']
    > DEBUG    BroadcastServer Sending discover request (force: False)
    > DEBUG    BroadcastServer Broadcast using ips ['192.168.x.xxx'] on port 1544: discoverRequest
    > WARNING  BroadcastServer Error sending broadcast using ip 192.168.x.xxx: 'super' object has no attribute 'bind'
    > ERROR    BroadcastServer Socket bind to :1544 error: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0

#### Expected Results:

  * No such errors.

**Comment by peter-tank** [comment]
Maybe could help:
  > DEBUG    ConnServer Conn#77 216.189.xxx.xx [?] > Closing connection: 216.189.xxx.xx Connect error: ModuleNotFoundError: No module named 'lib.PySocks' in ConnectionServer.py line 208 > Connection.py line 132, waiting_requests: 0, sites: 0, buff: 0...

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in latest version: https://github.com/HelloZeroNet/ZeroNet/commit/d93e89899b0edc41c6861078352fb0f2aaeb5e57

**Comment by peter-tank** [comment]
@HelloZeroNet U got one, but error in BroadcastServer remains, just OK with it or is resolving it on another issue? Am i missing some point in configure, bcz no such error in my centos system that configured with external ip.
  > ERROR BroadcastServer Unable to listen on port 1544

**Comment by HelloZeroNet** [comment]
I spent some time with this issue and looks like due to a bug PySocks can't proxy UDP sockets when gevent used:

```py
import socket
import gevent
import gevent.monkey
gevent.monkey.patch_all()
import socks

s = socks.socksocket(socket.AF_INET, socket.SOCK_DGRAM)
s.set_proxy(socks.SOCKS5, "127.0.0.1", 8080)
s.settimeout(1)
s.sendto(b"test", ("127.0.0.1", 12000))

data, server = s.recvfrom(1024)
```

```
Traceback (most recent call last):
  File "E:\Web\2019-08-15\test2.py", line 10, in <module>
    s.sendto(b"test", ("127.0.0.1", 12000))
  File "C:\python3\lib\site-packages\socks.py", line 367, in sendto
    self.bind(("", 0))
  File "C:\python3\lib\site-packages\socks.py", line 340, in bind
    super(socksocket, self).bind(*pos, **kw)
AttributeError: 'super' object has no attribute 'bind'
```

I have created an issue for it (https://github.com/Anorov/PySocks/issues/129), but the fix is not easy, so I think our best option now is disable UDP communications when proxy is used.

Btw BroadcastServer is only used in local peer discovery that probably would not work with proxies anyway.

**Comment by peter-tank** [comment]
Tanks for your times spends on this great project.
