### ISSUE TITLE
Console logging should be disabled by default if the Multiuser plugin is enabled

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#2151]
It's a bit of a privacy leak to have your proxy's logs showing to anyone that visits it. ~~`console_log_level` should be set to `off` by default~~ (I actually don't know what the correct option is here) if the Multiuser plugin is enabled.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, this should be fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/d166a16a247f44831b0bb12e24ac32733e7c6312#diff-e0d03f51569d71c57acfb58cd0aa5e8bR44
