### ISSUE TITLE
Allow a site to bust out of IFrame

### ISSUE THREAD

**Issue by github-zeronet** [HelloZeroNet/ZeroNet#2154]
**Is your feature request related to a problem? Please describe.**

The types of sites we can create is very limited today by CORS and IFrame limitations.  

**Describe the solution you'd like**
Allow sites the option to be served outside of IFrame. 

I realize the first reaction will be security concerns.  But, keep in mind, this is only for site owners choosing to do this.  By default, sites will continue to operate under the IFrame.  

I don't understand the concerns about file access because these files are all viewable and editable by any user via their file system.  You would want to enforce directory traversal protections, of course.  And you can, if needed, refactor it so the site's static content is in a folder inside the base site folder.  If a browser has no way to traverse to parent folders, then only the static content can be accessed.  

As for API limitations, perhaps there is a happy way to put the IFrame inside the site, instead of outside, perhaps with a tag the server can recognize and replace.  

We could have a permission on content.json that allows a site to be served without the IFrame being wrapped around it, but allows a tag inside the site's content that can be replaced by NZ with the IFrame.

**Describe alternatives you've considered**
Anything and everything that solves CORS and IFrame issues.  

**Additional context**
There is no known way to get a simple static Angular 8 site up and running in ZN due to the limitations of the IFrame.  The demo site works without an issue in Apache HTTPD.  

Here is documentation in ZN of that test and the resulting issues:  

[Testing a static Angular site in ZeroNet](http://127.0.0.1:43110/1KmgpXc9BLFxw1ccGANYVzvDh3YG95tSe3/?Topic:1565993644_1D9oYXWZH2S55PeoCFDKTqq8roNXqZqP7n/Testing+a+static+Angular+site+in+ZeroNet)

... for the ZeroNet ecosystem!

**Comment by imachug** [comment]
@github-zeronet Could you please mention that you are not the ZeroNet creator (or maintainer) in your profile bio? You can easily get confused with @HelloZeroNet.

*offtopic: @HelloZeroNet could you check your ZeroMail please?*

**Comment by HelloZeroNet** [comment]
Actually there is a NOSANDBOX permission:
`Page.cmd("wrapperPermissionAdd", "NOSANDBOX")`
This will remove the sandbox property/limitations from that Iframe

offtopic: @imachug replied

**Comment by imachug** [comment]
*offtopic: @HelloZeroNet please check the reply*

**Comment by github-zeronet** [comment]
Thank you, @HelloZeroNet !  That resolved it.

**Comment by imachug** [comment]
@github-zeronet No it's not a solution.

**NOSANDBOX is all-caps for a reason. If you give a site NOSANDBOX permission, that site can do anything on your computer: run any apps, set up a locker and what not.**

**Keep safe, people!**

The real solution is to call `(new ZeroFrame()).monkeyPatchAjax()` and then load your app.
