### ISSUE TITLE
Visitors are able to install plugins on proxies

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2155]
I was able to install the example plugin and restart the proxy here:

https://awesome-zeronet.herokuapp.com/12pPwpQ3wSoEtvN549ZVGUpj3HejtBrX3k/

Permission isn't denied.

**Comment by imachug** [comment]
Hotfix: `pluginAdd` -> `pluginAddRequest` in MultiuserPlugin.py.

**Comment by styromaniac** [comment]
http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1565965808_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di#

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I just fixed it: https://github.com/HelloZeroNet/ZeroNet/commit/1d5bde01cc85efdea4c37d238885d04de0c42362

This is not the first time of this type of error: The current way of handling the permissions of the commands are potential source of errors. I'm working on a better, function-decorator based command flagging.

**Comment by HelloZeroNet** [comment]
I have changed the permission list to function decorators in the latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/376fd0d43957a31271bff12e99b0fe8951402b66

This is more error-proof as it follows the function renames and typos.
