### ISSUE TITLE
"Proxy for tracker connections" must be automaticaly set to Tor if user choose "TOR: Always"

### ISSUE THREAD

**Issue by HostFat** [HelloZeroNet/ZeroNet#2158]
If the user set "TOR: Always", the connections to the trackers will slowly stop working.

To fix it, the user has to go to the Zeronet settings, and set "Proxy for tracker connections" to "Tor".

I think that this should be done automatically, without any user intervention, to make it more user friendly.

EDIT:
I was wrong, it still doesn't work.

**Comment by HelloZeroNet** [comment]
I just tested and it's work for me with both "Proxy for tracker connections: Disable" and "Proxy for tracker connections: Tor" in Tor: always mode

The UDP trackers won't work, but thats expected as Tor does not support UDP connections,

What's error messages do you see if you search for "announce failed" in log/debug.log?

**Comment by HostFat** [comment]
But with "Proxy for tracker connections: Disable", I guess that it opens a privacy issue, trackers will know about the IP of the users.

**Comment by HelloZeroNet** [comment]
In Tor: Always mode every connection made using the Tor network, so in  "Proxy for tracker connections: Disable" it will still use Tor.

Udp trackers starts with udp://, so zero:// and http[s]:// ones should work in Tor mode.

**Comment by HostFat** [comment]
Ok, thanks. It seems working right, maybe I had mess up some settings ...
