### ISSUE TITLE
Error when running siteCreate command from command prompt: Unhandled exception: RuntimeError: input(): lost sys.stdin

### ISSUE THREAD

**Issue by coreyharden** [HelloZeroNet/ZeroNet#2159]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5
  * Operating system: Windows 10 Home
  * Web browser: none... i was running a command in the command prompt
  * Tor status: available
  * Opened port: yes
  * Special configuration: no

### Step 2: Describe the problem:
ran the **zeronet siteCreate** command from within the command prompt and received the below error. Also, no site was created and no private key created either

**Unhandled exception: RuntimeError: input(): lost sys.stdin**

#### Steps to reproduce:

  1. open command prompt within the zeronet folder and run the **zeronet siteCreate** command

#### Observed Results:
Below is the error log from the error:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\ZeroNet-win-dist-win64\core\zeronet.py", line 19, in main
    main.start()
  File "C:\Users\User\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 533, in start
    actions.call(config.action, action_kwargs)
  File "C:\Users\User\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 111, in call
    back = func(**kwargs)
  File "C:\Users\User\Downloads\ZeroNet-win-dist-win64\core\src\main.py", line 148, in siteCreate
    if input("? Have you secured your private key? (yes, no) > ").lower() == "yes":
RuntimeError: input(): lost sys.stdin

#### Expected Results:
I expected to have a new site created and receive a private key for publishing the site
![commandPromtSiteCreate](https://user-images.githubusercontent.com/8691332/63234275-94949780-c202-11e9-92be-acee5ed34925.JPG)

**Comment by imachug** [comment]
`ZeroNet-win-dist` does not support console operations. Please use ZeroHello to create a site.

**Comment by HelloZeroNet** [comment]
There is a lib/ZeroNet.cmd that has console output and should support these commands

**Comment by imachug** [comment]
Still, I wouldn't recommend using `siteCreate`: it generates the private key as a random key, not as a masterseed child, which means that you won't be able to recover it.

**Comment by coreyharden** [comment]
> Still, I wouldn't recommend using `siteCreate`: it generates the private key as a random key, not as a masterseed child, which means that you won't be able to recover it.

Alright, thanks @imachug and @HelloZeroNet! I just saw on https://zeronet.readthedocs.io/en/latest/using_zeronet/create_new_site/ how to run the command on windows... I was running it incorrectly. Just curious @imachug, do you know of a better way to get a private key for publishing your site?

**Comment by imachug** [comment]
> Just curious @imachug, do you know of a better way to get a private key for publishing your site?

I usually use ZeroHello to create a site. Open [ZeroHello](http://127.0.0.1:43110/), click menu icon (`:`) next to "Hello ZeroNet_", choose "Create new, empty site". A new site will be created for you immediately. You'll see the site address either in the address bar on in the sidebar. The private key is seldom required, but it's in your `users.json`.
