### ISSUE TITLE
New API function: Publickey functions

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#216]
- userPublickey -> return: Get user's publickey delivered from privatekey
 - userDecrypt encrypted_text -> return: Decrypted text using current user's privatekey
 - cryptEncrypt publickey, text -> return: Encrypted text

- [x] Implement API commands
- [x] Static prototype of the site
- [x] Welcome/Registration screen
- [x] Register user's publickey
- [x] Send message
- [x] List incoming messages
- [x] List sent messages
- [x] Mark new, unread messages
- [x] Contact list
- [x] Faux delete from incoming folder
- [x] Echo bot for testing the service
- [ ] Later: Message thread list

**Comment by HelloZeroNet** [comment]
Problems:
 - the current library does not support encrypting / decrypting, so have to find an another for this task
 - Is it secure to use the same private key for signing and encrypting? https://bitcointalk.org/index.php?topic=374085.msg4004761#msg4004761

**Comment by TheNain38** [comment]
It would be cool, I was going to ask for something like this to send encrypted messages between other users, so it would be possible to exchange data directly to someone without others knowing the content

**Comment by alxbob** [comment]
Which library is this? I think a basic  public key / private key ability embedded in zeronet will be very useful for a lot of projects

**Comment by alxbob** [comment]
https://bitcointalk.org/index.php?topic=145098

**Comment by HelloZeroNet** [comment]
I successfully encrypted/decrypted texts using bitcoin private/publickeys, the speeds (the lib using c based openssl):

OpenSSL init 0.40299987793
Encrypt 100x... 1.45700001717
Decrypt 100x... 0.694000005722

If we want to hide the message recipient (and probably we do) then we have to try to decode all messages that is going through the system.
To do this efficiently we have to mark and cache messages that we have already checked. So we need a zeronet built-in cache system (probably sqlite based) that is multi-user friendly or we can store the messages in browser's localstorage.

**Comment by TheNain38** [comment]
@HelloZeroNet Cool :)

**Comment by alxbob** [comment]
Neat :) I dont know what library did you use but we ca use bitmessage too

**Comment by HelloZeroNet** [comment]
For experimentation I tried javascript based encrypt/decrypt solution (bitcore), but it's around 80x times slower, so it's not really an option.

**Comment by HelloZeroNet** [comment]
After doing some research encrypting using only the ecc public key ([bitmessage method](https://github.com/Bitmessage/PyBitmessage/blob/master/src/highlevelcrypto.py#L23)) is not secure eg.: https://www.reddit.com/r/Bitcoin/comments/2ntpvh/bitcrypt_encryption_with_bitcoin_addresses/cmhmny9

So I changed the code from `eccEncypt(text)` to:
`eccEnrypt("ZNE1" + aes_key + aes_iv + aesEncrypt(aes_key, aes_iv, text))`

(similar to [electrum's encryption](https://github.com/spesmilo/electrum/blob/ae425764237d89a5e16db4f984406509f08f2601/lib/bitcoin.py#L541), but without hmac)

The encryption/decryption speed is similar, but it's add + 276 bytes to every message.

It would be nice if someone with more experiment in this field give some advice if its a good way to encrypt messages like this.

**Comment by alxbob** [comment]
https://github.com/yann2192/pyelliptic we can use this library. It is cryptografically secure

**Comment by HelloZeroNet** [comment]
The 'cryptografically secure' is not depends on liblary, but the algorithm.

**Comment by alxbob** [comment]
This library is used by bitmessage and it is secure. The link on reddit you post is about bitcrypt library not pyelliptic. Actually you can talk to atheros directly i did that he is very helpful

**Comment by HelloZeroNet** [comment]
The crypto API commands are implemented:
 - cryptEncrypt(text, publickey) -> Encrypt a text using the public key, Return: Encrypted text using base64 encoding
 - cryptDecrypt(encrypted_text, privatekey) -> Decrypt a text using the private key, Return: Decrypted text
 - userPublickey() -> Returns user's public key unique to site, Return: Public key
 - userDecrypt(encrypted_text) -> Decrypt a text using the user's site unique private key, Return: Decrypted text
 - userDecryptBatch(encrypted_texts) -> Decrypt a list of texts using the user's site unique private key, Return: List of decrypted texts

In the next weeks i'm going to create the messaging site to see if its works correctly, then release the plugin

**Comment by alxbob** [comment]
Neat!

**Comment by alxbob** [comment]
Please add message sighing too https://github.com/yann2192/pyelliptic

**Comment by HelloZeroNet** [comment]
Every published file is signed by your client, so not necessary to sign messages.

**Comment by alxbob** [comment]
The ability to sign contracts between 2 users using this function?

**Comment by HelloZeroNet** [comment]
You can create a file containing the contract the sign it using the client.

**Comment by alxbob** [comment]
And then send it to the other user to sign too? I think its easier through the api commands that us you said are already implemented. Encrypt decrypt sign a message are basic commands

**Comment by HelloZeroNet** [comment]
Yes, you have to send the contract to other user to be able to sign it. Currently only features are implemented that has benefit for any of demo sites to avoid bloating and currently no site planned yet that has anything to do with contracts.

**Comment by HelloZeroNet** [comment]
Added my ideas and questions here: https://www.reddit.com/r/crypto/comments/3t6vnm/need_guidelines_for_ecc_based_messaging/

**Comment by alxbob** [comment]
Good work! Maybe adding encrypting messages for multiple users too...

**Comment by HelloZeroNet** [comment]
I have thought about multiple recipient messaging, it would be possible using the second method:
 - Generating new AES key for the group
 - Encrypt the generated AES key for every users publickey in the group
 - Encrypt message using the generated aes key

So one time, per group overhead would be: (227byte + 70byte) * User number in the group. After the group secret is shared the message sending space would be same as for single recipient sending.

Its also possible using the first method, but then it would be count as separate messages. So if you want to send it to 5 user it will take 5x more space. 

Probably I will choose the first method as its simpler to implement, so it will not feature group messaging.

**Comment by alxbob** [comment]
If the api commands are ready maybe others can help to. Whatever is better.

**Comment by HelloZeroNet** [comment]
Added in 0.3.4
