### ISSUE TITLE
The new Version: 0.7.0 r4188 has bug with nginx and ssl

### ISSUE THREAD

**Issue by tianlichunhong** [HelloZeroNet/ZeroNet#2168]
I use nginx and ssl to proxy zeronet， the configuration is as follows:
server {
    listen 4337 ssl;

    server_name       www.xxx.com;
    ssl on;
    ssl_certificate      /etc/letsencrypt/live/www.xxx.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/www.xxx.com/privkey.pem;

    ssl_session_timeout 5m;

    location / {
        proxy_pass http://127.0.0.1:43110;
        proxy_set_header Host $host; #get rid of media referrer error
        proxy_http_version 1.1;
        proxy_read_timeout 1h; #for long live websocket connetion
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
  }
 previous it work. but new version does not work. the erro show that:
Ui.UiServer Error 403: Invalid origin: https://www.xxx.com:4337

Version: 0.7.0 r4188 , please help.

**Comment by imachug** [comment]
Try adding the following to zeronet.conf to `[global]` section:

```
ui_host =
 www.xxx.com
```

**Comment by HelloZeroNet** [comment]
I'm not 100% sure about ngnix config, but here is what changed in Rev4187: https://github.com/HelloZeroNet/ZeroNet/commit/b871849df45cc5da9eff0ca780c0c8afe0e8a0cd

So for websocket connections the Origin header should be "http[s]://$host"

**Comment by tianlichunhong** [comment]
> Try adding the following to zeronet.conf to `[global]` section:
> 
> ```
> ui_host =
>  www.xxx.com
> ```

this also not work. I have use this configuration.

**Comment by peter-tank** [comment]
@tianlichunhong works for me:
```
		proxy_set_header Host 127.0.0.1;
		proxy_set_header Origin http://127.0.0.1;
```

**Comment by tianlichunhong** [comment]
> proxy_set_header Origin http:

Yes, this work.
I change my configuration as follows, it work. Thank you very much!
server {
listen 4337 ssl;

server_name       www.xxx.com;
ssl on;
ssl_certificate      /etc/letsencrypt/live/www.xxx.com/fullchain.pem;
ssl_certificate_key  /etc/letsencrypt/live/www.xxx.com/privkey.pem;
ssl_session_timeout 5m;
location / {
    proxy_pass http://127.0.0.1:43110;
    proxy_set_header Host  www.xxx.com; 
    proxy_set_header Origin https://www.xxx.com;
    proxy_http_version 1.1;
    proxy_read_timeout 1h; #for long live websocket connetion
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
}

**Comment by anmol26s** [comment]
@tianlichunhong 
Can you show me complete nginx configuration? 
I am unable to make reveres proxy through nginx. There should be dedicated document for reverse proxies.

**Comment by HelloZeroNet** [comment]
I have added an example configuration for Nginx that works with the latest, Python3 version of ZeroNet: https://zeronet.io/docs/faq/#how-to-configure-nginx-reverse-proxy-for-zeronet
