### ISSUE TITLE
ZeroNet needs a better UI Design - Navigation Header Bar

### ISSUE THREAD

**Issue by defnax** [HelloZeroNet/ZeroNet#217]
I think the Main Page of ZeroNet needs a better design...
Its too big.. it takes so much space....i love the new Side Bar for stats.

Hello
ZeroNet_
This site currently served by ++ peers without any central server. 
Connected sites:

ZeroNet needs more a SocialNet based Design... with useful Navigation Menus:

at Top a Navigation Header Bar like example Twitter would be nice:
Main ( ZeroNet Main Page)
Messages ( if ZeroNet supports anytime Email like Messaging)
Network (Network Page)
Zero ID Profile Button (Display which Zero ID you using, not sure if possible to switch ) 
Plugins 

maybe more ideas...first need a good looking design for easy navigation

**Comment by HelloZeroNet** [comment]
ZeroNet is an application framework not a social site. Every site is totally independent, so you can create your own startup page if you want, the ZeroHello is just a site on ZeroNet. The source code is here: https://github.com/HelloZeroNet/ZeroHello

**Comment by defnax** [comment]
I mean a nice Navigation Menu at top it would be very useful,

**Comment by border0464111** [comment]
I could be an improvement, Do you have any mockup to show ?

**Comment by grez911** [comment]
Non-constructive criticism.
@HelloZeroNet Can the issue be closed?
