### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by RonaldBolado** [HelloZeroNet/ZeroNet#2170]
https://www.virustotal.com/gui/file/9c39e54971296f5344852dd49c03a749c885ab828fc89721fe8a1e793b550fbe/detection

Is the rar safe or not?

**Comment by imachug** [comment]
First, only 2 antiviruses detect something, and they aren't well-known; second, ZeroNet code doesn't have a virus. So I'd assume this is a false positive.

**Comment by HelloZeroNet** [comment]
Yeah, unfortunately nothing we can do about false-positive results
