### ISSUE TITLE
Is it possible to share zeronet with others by VPS

### ISSUE THREAD

**Issue by tianlichunhong** [HelloZeroNet/ZeroNet#2171]
Is it possible to let others to use zeronet by private proxy? For example, I deploy zeronet on my VPS. My friends can use my VPS to register and login zeronet, just as twitter. And he also can use same ID to login through other person's private VPS.
If zeronet can support this function, will solve the GFW problem. Because there will be a lot of private VPS to support zeronet. And GFW can't block them.

**Comment by imachug** [comment]
Sure. Just setup a public ZeroNet proxy and enable UiPassword plugin.

**Comment by peter-tank** [comment]
Have you ever enabled the Multiuser plugin?
You can bind ZeroNet to 127.0.0.1 then share it with port mapping progs (such as dokodemo-door protocol offerred by V2Ray, but I did'nt find any GUI's support customed inbound configuration till now), assuming you want keep your ZeroNet Proxy in private.

**Comment by tianlichunhong** [comment]
> Sure. Just setup a public ZeroNet proxy and enable UiPassword plugin.

I had used this configuration. However, it is not suitable for the multi-person sharing mode.

**Comment by tianlichunhong** [comment]
> Have you ever enabled the Multiuser plugin?
> You can bind ZeroNet to 127.0.0.1 then share it with port mapping progs (such as dokodemo-door protocol offerred by [V2Ray](https://v2ray.com/chapter_02/protocols/dokodemo.html), but I did'nt find any GUI's support customed inbound configuration till now), assuming you want keep your ZeroNet Proxy in private.



> Have you ever enabled the Multiuser plugin?
> You can bind ZeroNet to 127.0.0.1 then share it with port mapping progs (such as dokodemo-door protocol offerred by [V2Ray](https://v2ray.com/chapter_02/protocols/dokodemo.html), but I did'nt find any GUI's support customed inbound configuration till now), assuming you want keep your ZeroNet Proxy in private.

Multiuser plugin is only for a person use different ID. It is not suitable to the scenario where multiple users use multiple IDs.

**Comment by filips123** [comment]
> Multiuser plugin is only for a person use different ID. It is not suitable to the scenario where multiple users use multiple IDs.

Multiuser plugin (in non-local mode) is made for public proxies where multiple users use the same proxy, but with a different account.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?
