### ISSUE TITLE
Update site shows confusing status when outdated

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2174]
### Step 1: Please describe your environment

  * ZeroNet version: 4197
  * Operating system: Windows

### Step 2: Describe the problem:

When i am having outdated revision of the Zeronet, the update site (http://127.0.0.1:43110/1uPDaT3uSyWAPdCv1WkMb5hBQjWSNNACf) is showing confusing text that i am up to date. It should say something like:
"Not up to date" or "Outdated Zeronet!"
[UPDATE TO LATEST VERSION]

**Comment by HelloZeroNet** [comment]
What does the "Latest version:" and the "Your version:" lines say to you?

**Comment by slrslr** [comment]
> What does the "Latest version:" and the "Your version:" lines say to you?

On the mentioned update site i see:
Your version: 0.7.0 (rev4197)
Latest version!
[Update to latest version]

after update i see:
Your version: 0.7.0 (rev4203)
On the edge with the latest revision!
[Update to latest version]

**Comment by slrslr** [comment]
I see you have modified the update page.

Here is how it looked when outdated:

> Your version: 0.7.0 (rev4203)
> Outdated!
> Update to latest version

then a status window appeared: "Failed to execute script boot" OK

These was last lines from the debug.log

> 
> ERROR    - UiWSGIHandler error: KeyError: 'content.json' in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 908 > TranslateSite/TranslateSitePlugin.py line 47 > ContentDbDict.py line 59
> ERROR    - UiWSGIHandler error: KeyError: 'content.json' in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 908 > TranslateSite/TranslateSitePlugin.py line 47 > ContentDbDict.py line 59
> ERROR    - UiWSGIHandler error: ConnectionAbortedError: [WinError 10053] Software v hostitelském počítači ukončil vytvořené připojení in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 910 > pywsgi.py line 757 > pywsgi.py line 778 > pywsgi.py line 742 > pywsgi.py line 704 > _socket3.py line 458 > _socketcommon.py line 374 > _socketcommon.py line 303 > _socket3.py line 439
> ERROR    - UiWSGIHandler error: ConnectionAbortedError: [WinError 10053] Software v hostitelském počítači ukončil vytvořené připojení in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 910 > pywsgi.py line 757 > pywsgi.py line 778 > pywsgi.py line 742 > pywsgi.py line 704 > _socket3.py line 458 > _socketcommon.py line 374 > _socketcommon.py line 303 > _socket3.py line 439
> INFO     - All server stopped

Then process disappeared and i started zeronet, it started OK. Update page shows correctly:

> Your version: 0.7.1 (rev4206)
> On the edge with the latest revision!
> Update to latest version

So this issue is solved..

**Comment by slrslr** [comment]
I am reopening this, because issue reappear. i have rev4238 on my Windows PC and Update zite http://127.0.0.1:43110/1uPDaT3uSyWAPdCv1WkMb5hBQjWSNNACf shown confusing message like "Latest version!" despite the version was outdated. So i was not having latest version. There was rev4241 to which i have just updated.
