### ISSUE TITLE
ZeroNet tends to crash when I make changes to Syncronite.txt

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2175]
I see this happen about half the time. I think it's related. I'm still on Py2 (ZeroNet-Kivy) rev 3866.

Syncronite is a site of mine solely for updating a list of quality BitTorrent trackers.

http://127.0.0.1:43110/15CEFKBRHFfAP9rmL6hhLmHoXrrgmw4B5o/

**Comment by HelloZeroNet** [comment]
Does it crash immediately or after a while? It could help if you have some specific errors in debug.log and error.log

**Comment by styromaniac** [comment]
It happens immediately.
