### ISSUE TITLE
Launch Tor Browser on ZeroNet app start

### ISSUE THREAD

**Issue by vik01** [HelloZeroNet/ZeroNet#2177]
In start.py I noticed "default_browser" argument, is there a way to make it into Tor Browser somehow? If it's NOT the default browser but I want 0net application open the startpage in Tor Browser and not it my_any_everyday_browser.

**Comment by imachug** [comment]
Yeah, put the following to zeronet.conf:

```
[global]
default_browser = path/to/tor/browser "%s"
```
