### ISSUE TITLE
Sorry, you can't delete your own site. Please remove the directory manually.

### ISSUE THREAD

**Issue by payalord** [HelloZeroNet/ZeroNet#2178]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.0
  * Operating system: Win7
  * Web browser: Chrome
  * Tor status: Enable
  * Opened port: not sure
  * Special configuration: none

### Step 2: Describe the problem:
I created new website. And I'm the only 1 peer and owner. Then I wanted to delete it. And got message: "Sorry, you can't delete your own site. Please remove the directory manually.". So I tried to remove directory manually and then delete website again. Even if I remove directory manually, I'm getting again same error message when trying to delete website. So I can't delete it anyway. So how can I then delete my website?

#### Steps to reproduce:

  1. Create website
  2. Delete website

or

  1. Create website
  2. Delete manually website directory
  3. Delete website

#### Observed Results:

Got error message: "Sorry, you can't delete your own site. Please remove the directory manually."

#### Expected Results:

That my website will be deleted completely.

**Comment by purplesyringa** [comment]
@HelloZeroNet What about showing a confirmation instead?

@payalord A hack for now: you can open your site, open the sidebar and press "Delete" there.

**Comment by HelloZeroNet** [comment]
Yeah probably we could add confirmation instead

**Comment by Thunder33345** [comment]
why was that added initially? was it intended "safeguard"?
or some sort of thing that caused bugs
also will this remove site private keys?

**Comment by purplesyringa** [comment]
> was it intended "safeguard"?

This

>  or some sort of thing that caused bugs

Deleting the site from ZeroHello is the same as deleting it from sidebar. I've never had any problems with deleting a site from sidebar, so I don't think it'll introduce any bugs.

>  also will this remove site private keys?

It will

**Comment by payalord** [comment]
Here is screenshot: https://ibb.co/stKSdmt
Do you mean deleting from sidebar like this? If yes then on my end it is not working and I'm getting error message as you can see on this screenshot.

**Comment by HelloZeroNet** [comment]
I have added a new message and a link that point to the sidebar when you try to delete your own site: https://github.com/HelloZeroNet/ZeroHello/commit/1ec6cf9affbcda2e0e6a412e93ce4b9c4e375cdd
