### ISSUE TITLE
TorManager error on connection to tor is unclear

### ISSUE THREAD

**Issue by twerq** [HelloZeroNet/ZeroNet#2188]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: Linux Mint
  * Web browser: Chromium
  * Tor status: not available
  * Opened port: no
  * Special configuration: no

#### Steps to reproduce:

  1. Configure tor service like described in the FAQ
  2. Run zeronet

#### Observed Results:

 ` TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection`

#### Expected Results:

  More descriptive error log with file|dir access issue mention.

Yes, I do know there is mentioned in the FAQ to check the file's user group in `/var/run/tor`. But the error in zeronet startup log gives no info about file access status and tells about issue with connection to service.
I believe it'd be clarified because when I investigated this behavior, after several hours I tried py2.7 zeronet version and had seen more descriptive error message. Then checked `/var/run/tor` permissions and discovered wrong sticky bit set for this catalog. File permissions were correct.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, it's fixed in the latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/2de35266c4200929a37d0b8796ba30f281a18e5e
