### ISSUE TITLE
WebSocket handleRequest error: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2190]
### Step 1: Please describe your environment

  * ZeroNet version: 4206
  * Operating system: Windows 10

### Step 2: Describe the problem:

debug.log file:

> INFO     Db:ZeroUp Table comment_votes outdated...version: 0 need: 3, rebuilding...
> 
> ERROR    Db:ZeroUp Error creating table comment_votes: OperationalError: index uri already exists in Db.py line 267 > DbCursor.py line 169 > DbCursor.py line 159 > DbCursor.py line 107
> 
> ERROR    Site:1HeLLo..Tf3D 1ZGagD38ypjSoUrpNEGaPFmAMKFcdud7C feed query Posts error: DbTableError: index uri already exists in Newsfeed/NewsfeedPlugin.py line 72 > SiteStorage.py line 199 > SiteStorage.py line 86 > Db.py line 273
> 
> ERROR    Site:1uPLoa..dmQc WebSocket handleRequest error: IndexError: tuple index out of range in UiWebsocket.py line 187 > MergerSite/MergerSitePlugin.py line 168 > MergerSite/MergerSitePlugin.py line 147 > UiWebsocket.py line 705 > Debug.py line 18

When i click to rebuild ZeroUp database, i find errors in debug.log:

> ERROR    - Unhandled exception: [(<class 'sqlite3.DatabaseError'>, DatabaseError('database disk image is malformed'), <traceback object at 0x000002C8E21A1408>)]
> 
> ERROR    - Unhandled exception: [(<class 'sqlite3.DatabaseError'>, DatabaseError('database disk image is malformed'), <traceback object at 0x000002C8DCE561C8>)]

and the site db stays at strange small size 4kB

When did "Check Files" and "Update" of the Site:1uPLoa..dmQc, then i finally seen no error upon zeroup db rebuild, except following upon page reload:

> ERROR    - Unhandled exception: [(<class 'sqlite3.DatabaseError'>, DatabaseError('database disk image is malformed'), <traceback object at 0x000002C8D705F108>)]

is it due to malformed content.db ?

**Comment by HelloZeroNet** [comment]
I'm not sure where is that error comes from, is there any more details in log/error.log?
Can you please also post the dbschema.json of the site? (I suspect it's not the "official" ZeroUp as there is no comment_votes table there)
Are other sites working well?

**Comment by purplesyringa** [comment]
Based on `...dmQc` suffix, it's the official one.

**Comment by slrslr** [comment]
Error.log was not updated (is empty).
dbschema.json file of that 1uPLoa..dmQc site is [here](https://privatebin.net/?b026deabc9d1162b#HimCNXhTSL3JpT8TuZihUwrh3FsTEWFV48Aj1fcxq6mr)

> Are other sites working well?

yes, other sites are loading ok.

I tried to use all zeronet files from original backup (should be same current revision) except data folder where i only replaced (after backup) content.db file.
the log files shows:

> Db:ContentDb Error loading content.db: DatabaseError: database disk image is malformed in ContentDb.py line 22 > Db.py line 110 > DbCursor.py line 107, rebuilding...

content.db got nulled to 4kB size and debug.log is stuck at "INFO     - Creating UiServer....", zeronet process CPU activity is high, disk activity seems very low.

After one hour debug.log shows two errors:

> ERROR    - Unhandled exception: [(<class 'RuntimeError'>, RuntimeError('dictionary changed size during iteration'), <traceback object at 0x00000250011B52C8>)]
> ERROR    - Unhandled exception: [(<class 'sqlite3.OperationalError'>, OperationalError('database or disk is full'), <traceback object at 0x00000250694D2F88>)]
error.log nothing, disk is not full and is NTFS filesystem. Content.db got rebuild apparently - 164MB

Then i found [Windows bundle download link](https://github.com/HelloZeroNet/ZeroNet-win/archive/dist-win64/ZeroNet-py3-win64.zip) on README page and i used it to launch zeronet, but upon loading zerohello newsfeed, the errors mentioned remains:

> [2019-09-10 09:27:15,009] INFO     Db:ZeroUp Table comment_votes outdated...version: 0 need: 3, rebuilding...
> [2019-09-10 09:27:15,015] ERROR    Db:ZeroUp Error creating table comment_votes: OperationalError: index uri already exists in Db.py line 267 > DbCursor.py line 169 > DbCursor.py line 159 > DbCursor.py line 107
> [2019-09-10 09:27:15,016] ERROR    Site:1HeLLo..Tf3D 1ZGagD38ypjSoUrpNEGaPFmAMKFcdud7C feed query Posts error: DbTableError: index uri already exists in Newsfeed/NewsfeedPlugin.py line 72 > SiteStorage.py line 199 > SiteStorage.py line 86 > Db.py line 273

a few minutes later "sqlite3.OperationalError'>, OperationalError('database or disk is full')" as before..

I renamed zeroup directory, deleted the zeroup site, renamed back, renamed zeroup.db file, visited site, it rebuilt the db and i see the db size is not 4kB, but correct - 456kB. Upon loading zerohello newsfeed it no longer complains about zeroup related "corruption".

**I spotted another issue - zeronet shows nearly no connectivity and data transfer, port: "checking" and tor: "error" and zeronet process can not be shutdown, only killed** (i waited a few hours and did a few starts).

Here is the workaround that removed several issues: in zeronet.conf have:
tor_controller = 127.0.0.1:9151
tor_proxy = 127.0.0.1:9150
and launch Tor browser which launched its Tor proccess. Following things started working: IPv4 port began to be detected as closed (not "checking") and **network activity started - including non-Tor connections on /Stats. Zerohello obviously started using Tor:available
Moreover, surprisingly zeronet now can shutdown its process without problem (without tor browser running it could not shutdown). I think this indicate some bug, because non-tor connectivity should work even in tor:error mode and quitting zeronet too.

When i quit Tor browser and restart zeronet, there is WinError 10053 in debug.log and no other connections - a dead log, port: "checking", no IPv4 activity, tor: error (could not start bundled tor, giving no error), ZN can not shutdown its process.
I tried to disable enable all connection & tor related settings in zeronet.conf and these does not have any effect on this issue. Why ZN is relying on tor and without it can not shutdown, can not make non-tor connections?

Mentioned ZeroUp and ZeroHello errors remains:

> ERROR    Db:ZeroUp Error creating table comment_votes: OperationalError: index uri already exists in Db.py line 267 > DbCursor.py line 169 > DbCursor.py line 159 > DbCursor.py line 107
> 
> ERROR    Site:1HeLLo..Tf3D 1ZGagD38ypjSoUrpNEGaPFmAMKFcdud7C feed query Posts error: DbTableError: index uri already exists in Newsfeed/NewsfeedPlugin.py line 72 > SiteStorage.py line 199 > SiteStorage.py line 86 > Db.py line 273
>

**Comment by slrslr** [comment]
@HelloZeroNet @imachug
bumping this and one more update:

> Are other sites working well?

I seen the same errors on Kopykate site:

> [* *:*3:11,179] ERROR    Site:18Pfr2..pSzh WebSocket handleRequest error: IndexError: tuple index out of range in UiWebsocket.py line 187 > MergerSite/MergerSitePlugin.py line 168 > MergerSite/MergerSitePlugin.py line 147 > UiWebsocket.py line 705 > Debug.py line 18
...
> [*:*3:22,622] ERROR    Site:18Pfr2..pSzh WebSocket handleRequest error: IndexError: tuple index out of range in UiWebsocket.py line 187 > MergerSite/MergerSitePlugin.py line 168 > MergerSite/MergerSitePlugin.py line 147 > UiWebsocket.py line 705 > Debug.py line 18

(after some time keeping the site openned. I do not see it immediately after page load, it pop up after a few minutes [being on site](http://127.0.0.1:43110/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/?Channel=caropc4@zeroid.bit) and clicking Seed buttons). PS i thought the site is not a merger type.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was able to reproduce it. Working on it...

**Comment by HelloZeroNet** [comment]
Fixed in Rev4210: https://github.com/HelloZeroNet/ZeroNet/commit/96759e9303f15a823a8f6871e59a0e84a740264f

**Comment by slrslr** [comment]
> 
> 
> Fixed in Rev4210: [96759e9](https://github.com/HelloZeroNet/ZeroNet/commit/96759e9303f15a823a8f6871e59a0e84a740264f)

it updated to rev4210 and bundled tor.exe was started and working. IPv4 port properly detected as closed.

These are the errors that are still found in the debug.log:

> 
> INFO     Db:ZeroUp Table comment_votes outdated...version: 0 need: 3, rebuilding...
> 
> ERROR    Db:ZeroUp Error creating table comment_votes: OperationalError: index uri already exists in Db.py line 267 > DbCursor.py line 169 > DbCursor.py line 159 > DbCursor.py line 107
> 
> ERROR    - UiWSGIHandler error: KeyError: 'content.json' in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 908 > TranslateSite/TranslateSitePlugin.py line 47 > ContentDbDict.py line 59

error.log is empty

**Comment by HelloZeroNet** [comment]
Probably that error comes from a different site that also named the database ZeroUp, because ZeroUp does not have any comment_votes table.

There should be a `Db:ZeroUp Connected to ....` line before that that shows the path of the site

**Comment by slrslr** [comment]
i think that the database problem (mentioned in my previous post) is in the site 1ZGagD38ypjSoUrpNEGaPFmAMKFcdud7C
[its admin](http://127.0.0.1:43110/1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT/?Topic:1557261503_17ArNJgy6YwDKjMSsnx1es2ie5jLHJbD9P) will need to fix it i assume
