### ISSUE TITLE
IPFS based ZeroNet, what's your opinion

### ISSUE THREAD

**Issue by blurHY** [HelloZeroNet/ZeroNet#2194]
https://gitlab.com/ipzn/ipzn

@shortcutme @HelloZeroNet

**Comment by danimesq** [comment]
Instead of creating a fork of ZeroNet, just create a bridge app.

**Comment by blurHY** [comment]
Never.
________________________________

**Comment by emacsenli** [comment]
what is the advantage of combination of ipfs and zeronet?
can this solve the problem of being blocked by GFW?
