### ISSUE TITLE
start fail on Raspberry Pi

### ISSUE THREAD

**Issue by chenxuuu** [HelloZeroNet/ZeroNet#2195]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
  * Web browser: none
  * Tor status: not available
  * Opened port: no
  * Special configuration: none

#### Steps to reproduce:

wget https://github.com/HelloZeroNet/ZeroNet/archive/py3/ZeroNet-py3.tar.gz
tar xvpfz ZeroNet-py3.tar.gz
cd ZeroNet-py3
sudo python3.7 -m pip install -r requirements.txt
python3.7 zeronet.py

#### Observed Results:

```bash
pi@raspberrypi:~/hd/zeronet/ZeroNet-py3 $ python3.7 zeronet.py
- Starting ZeroNet...
[14:36:49] - Unhandled exception: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/site-packages/gevent/libuv/_corecffi.abi3.so)
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    import main
  File "/home/pi/hd/zeronet/ZeroNet-py3/src/main.py", line 59, in <module>
    from Debug import DebugHook
  File "/home/pi/hd/zeronet/ZeroNet-py3/src/Debug/DebugHook.py", line 10, in <module>
    from . import Debug
  File "/home/pi/hd/zeronet/ZeroNet-py3/src/Debug/Debug.py", line 77, in <module>
    gevent.spawn(testBlock)
  File "src/gevent/greenlet.py", line 588, in gevent._greenlet.Greenlet.spawn
  File "src/gevent/greenlet.py", line 213, in gevent._greenlet.Greenlet.__init__
  File "src/gevent/_hub_local.py", line 80, in gevent.__hub_local.get_hub_noargs
  File "/usr/local/lib/python3.7/site-packages/gevent/hub.py", line 414, in __init__
    self.loop = self.loop_class(flags=loop, default=default) # pylint:disable=not-callable
  File "/usr/local/lib/python3.7/site-packages/gevent/hub.py", line 428, in loop_class
    return GEVENT_CONFIG.loop
  File "/usr/local/lib/python3.7/site-packages/gevent/_config.py", line 50, in getter
    return self.settings[setting_name].get()
  File "/usr/local/lib/python3.7/site-packages/gevent/_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "/usr/local/lib/python3.7/site-packages/gevent/_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "/usr/local/lib/python3.7/site-packages/gevent/_config.py", line 223, in _import_one_of
    return self._import_one(candidates[-1])
  File "/usr/local/lib/python3.7/site-packages/gevent/_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/site-packages/gevent/libuv/loop.py", line 15, in <module>
    from gevent.libuv import _corecffi # pylint:disable=no-name-in-module,import-error
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/site-packages/gevent/libuv/_corecffi.abi3.so)
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md
```

#### Expected Results:

should be started, but not

**Comment by purplesyringa** [comment]
Looks like you have a too old version of glibc. Try running the following:

```bash
sudo apt-get update && sudo apt-get install libc6
```

**Comment by chenxuuu** [comment]
@imachug  thanks, I try this, but still error with it

**Comment by HelloZeroNet** [comment]
Whats your `ldd --version`?

you can try `sudo python3.7 -m pip remove gevent`
`sudo apt install python3-gevent`

**Comment by chenxuuu** [comment]
@HelloZeroNet 
`ldd (Debian GLIBC 2.24-11+deb9u3) 2.24`
version is too old?

**Comment by HelloZeroNet** [comment]
It's normal for debian 9. When pip install executed it should compile for your system, but for some reason it's got compiled for debian 10 libc.

**Comment by chenxuuu** [comment]
> 
> 
> Whats your `ldd --version`?
> 
> you can try `sudo python3.7 -m pip remove gevent`
> `sudo apt install python3-gevent`

my python3.7 was installed by compiling source code, should I recompile this?

**Comment by krzysztof113** [comment]
@chenxuuu Can you check if you got python3-dev and then reinstall dependencies?
sudo apt-get install python3-dev

**Comment by krzysztof113** [comment]
@HelloZeroNet There are multiple problems with source installation on raspberry pi. It looks like the reason for that is that pypi.org no longer provides some packages that pip looks for. Installing them with apt instead resolves all the issues. I can make fresh install to get all apt only packages but will need pi dedicated section in instructions. Let me know.

**Comment by HelloZeroNet** [comment]
sometimes `python3 -m pip install -U pip`, fixes missing pypi urls, but installing it from apt also should be fine. What packages should be installed from pip?

**Comment by krzysztof113** [comment]
here's example (dependency for coincurve)
python3 -m pip install pkg-config
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/pkg-config
but installable from apt

**Comment by HelloZeroNet** [comment]
I don't have this package installed, and I have not found anything after searching it on google.

**Comment by krzysztof113** [comment]
On Raspberry Pi?

**Comment by HelloZeroNet** [comment]
On Win/Linux, but the dependencies should be same in every platform.

**Comment by krzysztof113** [comment]
Correct me if I'm wrong but it goes like this. 
If pip doesn't find prebuild library (wheel) it will compile it. So the pkg-config is not need to run ZN but to build dependencies.

**Comment by HelloZeroNet** [comment]
you are right, but there is no pkg-config python/pip package. It's a gcc/make dependency.

**Comment by chenxuuu** [comment]
my python3.7 was compiled from source code
I'll try reinstall from apt

**Comment by krzysztof113** [comment]
Overall mentioned by me problems are only specific to Rasbian stretch (Debian 9). On Raspbian 10 source installation goes smooth. I found issues potentially related #2109, #2002, #1838

**Comment by chenxuuu** [comment]
I reinstall python from apt, it works
thanks for everyone!
