### ISSUE TITLE
Internal error: TypeError: encoding without a string argument

### ISSUE THREAD

**Issue by TheresaQWQ** [HelloZeroNet/ZeroNet#2196]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: Windows 10 1903
  * Web browser: Chrom latest
  * Tor status: always
  * Opened port: no
  * Special configuration: none

#### Steps to reproduce:
sorry, i don't know.

#### Observed Results:

Internal error: TypeError: encoding without a string argument
UiWebsocket.py line 187 > MergerSite/MergerSitePlugin.py line 156 > MergerSite/MergerSitePlugin.py line 137 > User.py line 78 > Noparallel.py line 57 > Noparallel.py line 50 > User.py line 63 > CryptBitcoin.py line 68
#### Expected Results:

  * What did you expect to happen?

**Comment by purplesyringa** [comment]
That doesn't sound well .It looks like your users.json was corrupted. It should look like this:

```json
{
 "1Maukn6........................BLP": {
  ... something goes here ...
  "master_seed": "..."
  ... something goes here ...
 }
}
```

(except that the address and master_seed should be different). Can you please check that the master_seed is not missing? (Don't post it here though, it should be kept secret)

**Comment by TheresaQWQ** [comment]
> That doesn't sound well .It looks like your users.json was corrupted. It should look like this:
> 
> ```json
> {
>  "1Maukn6........................BLP": {
>   ... something goes here ...
>   "master_seed": "..."
>   ... something goes here ...
>  }
> }
> ```
> 
> (except that the address and master_seed should be different). Can you please check that the master_seed is not missing? (Don't post it here though, it should be kept secret)

Thank you, I have already fixed it.
