### ISSUE TITLE
TypeError: memoryview: a bytes-like object is required, not 'str' when try to download resource from not activated zite

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#2197]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4210
  * Operating system: Fedora 30 x64
  * Web browser: Chromium
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

I have not activated zite `1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h` yet. I found on another zite link to the movie on GIF Time. I opened link. My browser waits very long time for http response. In the meantime i see error in console.

#### Steps to reproduce:

  1. Please do not activate zite `GIF Time` - `1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h`
  2. Go directly to  http://127.0.0.1:43110/1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h/data/mp4-devopsreactions/3827.mp4
  3. See the console log

#### Observed Results:

Console shows:
```
[21:11:56] - UiWSGIHandler error: TypeError: memoryview: a bytes-like object is required, not 'str' in UiServer.py line 41 > pywsgi.py line 924 > pywsgi.py line 910 > pywsgi.py line 757 > pywsgi.py line 778 > pywsgi.py line 742 > pywsgi.py line 704 > _socket3.py line 457 > _socket3.py line 45
```

#### Expected Results:

I should see 403 error because I have not activated zite `1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h` yet.

I think 403 status code is better then 404 because i do not have access to that resource, I have to activate zite first. I mean go to http://127.0.0.1:43110/1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h

**Comment by HelloZeroNet** [comment]
Thanks for reporting, should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/93e6ec4933b8d2a8a3fea4900a2e939d3985cb4d (It should display a prompt dialog if you want to add the site)
