### ISSUE TITLE
"Web interface bind error" but ZeroNet is still working

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#2199]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4214
  * Operating system: Fedora 30 x64
  * Web browser: Chromium
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

I have binded another service on port `43110`. After I run ZeroNet on the same port in logs I see error but ZeroNet is still working.

#### Steps to reproduce:

  1. bind service on port `43110` - e.g. `nc -k -l 127.0.0.1 43110`
  2. Make sure ZeroNet use port from step 1 (`ui_port = 43110`)
  2. run ZeroNet

#### Observed Results:

Console shows error `exiting.... ` but ZeroNet client is still working

```
[15:25:36] Ui.UiServer Web interface bind error, must be running already, exiting.... [Errno 98] Address already in use: ('127.0.0.1', 43110)
```

#### Expected Results:

ZeroNet should exit when cannot bind on specified port.

#### fileserver_port

The same situation when you try to bind on `fileserver_port` port. ZeroNet is still working.

```
[15:33:56] ConnServer StreamServer listen error: [Errno 98] Address already in use: ('0.0.0.0', 44444)
```

**Comment by HelloZeroNet** [comment]
Now it should drop error and shut down UiServer if FileServer binding fails: https://github.com/HelloZeroNet/ZeroNet/commit/d7db631b9524e2ca2e5481721d86289dcd2732a5
