### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by bugmenot2** [HelloZeroNet/ZeroNet#220]
"GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch", 
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8", 
    "HTTP_CACHE_CONTROL": "max-age=0", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_REFERER": "http://127.0.0.1:43110/ZeroUpload.bit/?wrapper_nonce=bc050f29c68379a2401e2a6301a46b3a4e1b8fe9d9b32d889572ec6f76c04fc4", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/45.6.11.385 Chrome/45.0.2454.93 Safari/537.36", 
    "PATH_INFO": "/ZeroUpload.bit/", 
    "QUERY_STRING": "wrapper_nonce=bc050f29c68379a2401e2a6301a46b3a4e1b8fe9d9b32d889572ec6f76c04fc4", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "2279", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
        "config_file": "zeronet.conf", 
        "data_dir": "data", 
        "debug": false, 
        "debug_socket": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "homepage": "1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr", 
        "ip_external": null, 
        "log_dir": "log", 
        "msgpack_purepython": true, 
        "open_browser": "default_browser", 
        "proxy": null, 
        "size_limit": 10, 
        "stream_downloads": false, 
        "trackers": [
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.aletorrenty.pl:2710/announce", 
            "http://tracker.skyts.net:6969/announce", 
            "http://torrent.gresille.org/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "use_openssl": true, 
        "use_tempfiles": false
    }, 
    "plugins": [
        "Sidebar", 
        "Stats", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.0.1", 
    "version_python": "2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.3.3 r618", 
    "wsgi.url_scheme": "http"
}

Could this be caused by giving your-self a name change (by editing the user.json file). I changed by name before touching ZeroUpload and it as not caused issues else where.

**Comment by bugmenot2** [comment]
Could this be caused by giving your-self a name change (by editing the user.json file). I changed by name before touching ZeroUpload and it as <b><i>not</i></b> caused issues else where.

**Comment by HelloZeroNet** [comment]
Sorry, this looks like ZeroUpload related error, so I can't fix it. Official sites that I able to modify: https://github.com/HelloZeroNet?tab=repositories
