### ISSUE TITLE
Nginx reverse proxy：Invalid origin: https://domain.com

### ISSUE THREAD

**Issue by TheresaQWQ** [HelloZeroNet/ZeroNet#2208]
### Step 1: Please describe your environment

  * ZeroNet version: latest
  * Operating system: Ubuntu 18.04.3 LTS
  * Web browser: Chrome
  * Tor status: not available
  * Opened port: yes
  * Special configuration: ____

https is work, but websocket console display Invalid origin: https://domain.com

**Comment by TheresaQWQ** [comment]
![Chrome console](https://user-images.githubusercontent.com/22370654/65755102-0686c780-e145-11e9-8476-3e8a4b91b063.png)

**Comment by purplesyringa** [comment]
Have you added `https://domain.com` or `domain.com` to `ui_host` configuration key?

**Comment by purplesyringa** [comment]
@TheresaQWQ Did that help?

**Comment by ghost** [comment]
I would use Apache if I'm you. @imachug I'm sure that your suggestion not worked. Actually you need two server to proxy from clearnet to ZeroNet. One is where zeronet is running and you need to unset the headers which added by ZeroNet. This server should accept incoming connections only from the front-end server on port 80 and forward it to 43110. 

On the front-end you should redirect port 80 to 443 and proxy that to the back-end server xx.xx.xx.xx:80 here you can set headers! 

I think this issue related to that he proxy request to xx.xx.xx.xx:43110/raw/example.bit

In any case the back-end server should only download the site from your local machine where you update and sign everything over tor! Do not use the back-end to publish/update your sites!

**Comment by purplesyringa** [comment]
Why would you need two servers? Can't you just make the ZeroNet instance listen on port 80 publically?

**Comment by ghost** [comment]
@imachug @HelloZeroNet You need two server because one removes the headers added by ZeroNet and the other adding new ones. Not to mention that is safer! 

I currently proxy on the front-end example.org:443 to "backendip-xx.xx.xx.xx:80/raw/BitcoinAddress". -FIREWALL- The back-end listens on port 80 and forwards it to 43110. Works perfectly. No sandbox whatsoever... Caching however... you know...

**Comment by ghost** [comment]
@TheresaQWQ Try using Apache and as I said do not publish on the Proxy back-end! Only use your local machine preferably with Tor on and in Tor Browser. I checked around and find that you MUST create a new site by command line _zeronet.py siteCreate_! Put your files into your new "BitcoinAddress" and than _zeronet.py siteSign_. MANUALLY! After this open the site using your proxy which will also download that. Again, **do not use the back-end to create/clone sites**!

**Comment by imachug** [comment]
Why would you need to add or remove headers? There are quite a lot ZeroNet proxies online like z.hex3.cf but they only have a single server.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?

**Comment by HelloZeroNet** [comment]
Yes, using apache/nginx is the recommended way to setup. 
(It would be great if someone could add it to the [faq](https://github.com/HelloZeroNet/Documentation/blob/master/docs/en/faq.md) with some example config)

**Comment by purplesyringa** [comment]
Is "Is it possible to install ZeroNet to a remote machine?" section the right place to update?

**Comment by HelloZeroNet** [comment]
I think it would be better to create a new section: "How can I run a public ZeroNet proxy?" and add a link to it to the "Is it possible to install ZeroNet to a remote machine?" section.
