### ISSUE TITLE
Blog needs improvments 

### ISSUE THREAD

**Issue by Snarkly** [HelloZeroNet/ZeroNet#221]
Cloning the blog was a good idea but it needs a dashboard like wordpress has so people can change the look of the blog easier and add media easier. ![new-wp-dashboard](https://cloud.githubusercontent.com/assets/8492776/11361057/3eac8f86-9258-11e5-9e61-c9b46d3fce17.png)

**Comment by HelloZeroNet** [comment]
The ZeroBlog is only an example site, there is lots of space (and working hour) of improvements, but I will leave it to other developers.
