### ISSUE TITLE
Address blacklist does not work correctly

### ISSUE THREAD

**Issue by krzotr** [HelloZeroNet/ZeroNet#2210]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4221
  * Operating system: Fedora 30 x64
  * Web browser: Chromium
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

I want to block Git Center (`1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t`) Zite permanently even I do not want to download it.
I enabled `ContentFilter` plugin and put address to the `filters.json` file.
When I go directly to the Zite `/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t` - everything is OK - Zite is blocked.
When I use `Get All Sites` (`/1Ake2MmwxDgst5M8WqoyNLjDQj2pcPj5zL/`) to add address which is already on blacklist - (Zite uses `mergerSiteAdd` command) -  Zite is not blocked, is normally downloaded.

#### Steps to reproduce:

  1. Create file `data/filters.json`
  ```
{
   "siteblocks":{
      "1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t":{
         "date_added":1569622557,
         "reason":"Test only"
      }
   }
}  
  ```
  2. Run ZeroNet
  3. Go to `http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t`
  3.1. Go to `http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t/index/`
  4. On both sites you should see `Site Blocked` message - correct
  5. Go to `Get All Sites `http://127.0.0.1:43110/1Ake2MmwxDgst5M8WqoyNLjDQj2pcPj5zL/`
  6. Put `1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t`
  7. Press `Step 1` and `Step 2` - you should see `Added 1 new site`
  8. Go to `http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t/`
  9. You see `Git Center` - Zite is on blacklist but is working
  
#### Observed Results:

Two things:
1. You can get access to the Zite even you added to the blacklist
2. API command `mergerSiteAdd` does not support blacklist

#### Expected Results:

When I blacklist Zite I should see `Site Blocked` message even website has been downloaded.
When I blacklist Zite I should not be possible to download Zite - remove from blacklist first

**Comment by HelloZeroNet** [comment]
Thanks fore reporting, it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/43c366d2fb1860711bb08c1869a9749da600ea5f
