### ISSUE TITLE
文档太烂

### ISSUE THREAD

**Issue by fzpixzj90h7baqieoop5hg** [HelloZeroNet/ZeroNet#2212]
什么都没有,加载layui都不知道怎么弄进去,网上资料太少,定制性太差,更别提什么维护了,不能用mysql和php就拉倒了,我加载个jQuery都不行,怎么着,让我手写一个?那别的呢?全部手写?

**Comment by purplesyringa** [comment]
1. There are tutorials on ZeroBlog as well as [my tutorials](https://github.com/krixano/ZeroNet-Dev-Center/issues/28). I believe these two things can help.
2. Whilst there's little information online, you can find a lot on zites and https://zeronet.io/docs.
3. You are coming to a decentralized project and asking for PHP and MySQL, seriously? Btw, we support SQLite.
4. ZeroNet was created for people who can't speak up in the World Wide Web, no wonder there are morr strange views on ZeroNet.
5. If you can't load jQuery you have probably never *ever* used jQuery, did you? Come on, it's a single file and a single tag.

**Comment by anoadragon453** [comment]
@imachug please don't be so accusatory. Decentralized services are still in their infancy and a lot of people don't know exactly how things translate from the centralized world.

**Comment by fzpixzj90h7baqieoop5hg** [comment]
sorry,My fault,just hope better

Andrew Morgan <notifications@github.com> 于2019年10月2日周三 上午5:23写道：

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this issue be closed?
