### ISSUE TITLE
Use a Content Delivery Network (CDN)

### ISSUE THREAD

**Issue by realabbas** [HelloZeroNet/ZeroNet#2219]
**Is your feature request related to a problem? Please describe.**
Yes, the resources are served within the domain, hence decreases the overall speed of the page

**Describe the solution you'd like**
Use a Content Delivery Network (CDN)

![image](https://user-images.githubusercontent.com/43527087/66395432-0a440500-e9f5-11e9-8e52-fd8009e369e6.png)

**Additional context**
**See the full report:** https://gtmetrix.com/reports/zeronet.io/m9viQuBW

**Comment by HelloZeroNet** [comment]
Thanks, for the suggestion, but it's intentional: serving resources from CDN sites could have security and privacy issues, so I think they should be avoided if possible.

**Comment by purplesyringa** [comment]
+1 for privacy, -1 for security though. If you're talking about security as in "the CDN hosts exactly what I want", you can use `integrity` attribute to avoid that problem.

**Comment by realabbas** [comment]
I understand the concern, but the images and other public files can be served from CDN

**Comment by purplesyringa** [comment]
Hm. Known images loaded from clearnet IP with a known referrer... If zeronet.io used CDN, those who value privacy would have to start Tor just to download a single ZIP. I doubt those difficulties can be ignored.
