### ISSUE TITLE
siteSign

### ISSUE THREAD

**Issue by alxbob** [HelloZeroNet/ZeroNet#222]
siteSign in debian distro (8/7) doesnt work

- OpenSSL loaded, version: 01000105F
Traceback (most recent call last):
  File "zeronet.py", line 15, in main
    main.start()
  File "src/main.py", line 331, in start
    actions.call(config.action, action_kwargs)
  File "src/main.py", line 96, in call
    func(**kwargs)
  File "src/main.py", line 156, in siteSign
    site_data = user.getSiteData(address)
AttributeError: 'NoneType' object has no attribute 'getSiteData'

**Comment by HelloZeroNet** [comment]
Probably there is no user exists in your data/users.json file. Start zeronet normally to generate one for your then it will be fine.

**Comment by alxbob** [comment]
I run it on linux no x11 only cli and no user is generated !

**Comment by HelloZeroNet** [comment]
yeah, the user is generated on first web request, so it can be problematic on headless mode. Pushed a quickfix, after updating it should work now: 675bd462556c541d65e2d95f91f899146a373aad

**Comment by alxbob** [comment]
I use ssh tunnel to create the first user thanks anyway
