### ISSUE TITLE
Visual bug on Grant button on merger prompt

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroNet#2222]
### Step 1: Please describe your environment

  * ZeroNet version: 435a3c285ec59d94f7b9756de9cb158e79270f21
  * Operating system: Debian Buster
  * Web browser: Firefox nightly v71a
  * Tor status: n/a
  * Opened port: n/a

### Step 2: Describe the problem:

I received a visual bug on the zerome merger site permissions prompt where the Grant button is cut off.

#### Observed Results:

![image](https://user-images.githubusercontent.com/1342360/66708563-24aa1580-ed4a-11e9-8325-d5d42d83f5a9.png)

![image](https://user-images.githubusercontent.com/1342360/66708596-a732d500-ed4a-11e9-86ba-31c4483e63ae.png)

![image](https://user-images.githubusercontent.com/1342360/66708598-b0bc3d00-ed4a-11e9-83a3-6837ffc2547f.png)

#### Expected Results:

The Grant button to be shown in its entirety.

**Comment by purplesyringa** [comment]
Let me burst in and also mention that this issue sometimes happens to other notifications as well. Btw, notifications don't automatically resize when you change their content.

**Comment by HelloZeroNet** [comment]
Should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/8d88cfcd68ba5b78b9a63dc2c585c83c7b9abeac in Rev4252

![image](https://user-images.githubusercontent.com/10350359/67823080-fe160980-fac1-11e9-81b2-061da77321b9.png)
