### ISSUE TITLE
DNS vs Reverse Proxy and /RAW/

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2224]
Hi!

I have described in details at https://github.com/HelloZeroNet/ZeroNet/pull/2214 and https://github.com/HelloZeroNet/ZeroNet/issues/2208 problems regarding /raw/. I think ZeroNet should not enforce headers and sandbox when /RAW/ is requested! 

This will solve a lot of problems. Check this: https://github.com/HelloZeroNet/ZeroNet/issues/2208

**Comment by imachug** [comment]
A private key can only be recovered if you sign something twice using the same random number, which is next to impossible

**Comment by purplesyringa** [comment]
@HelloZeroNet TBH this looks nonsense. Headers are required to forbid sites to access other sites. Can this be closed?

**Comment by HelloZeroNet** [comment]
I think it's better to have consistent security requirements.
I recommend to add the hosts to `--ui_host` or use apache/nginx to proxy the request
