### ISSUE TITLE
ZeroID registration fails with error "Error while during request: error undefined"

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2229]
### Step 1: Please describe your environment

  * ZeroNet version: 4241
  * Operating system: W10
  * Web browser: FF
  * Special configuration: mutiuser plugin

### Step 2: Describe the problem:

Try to switch to some user certificate that you never used to registered ZeroID for it.
Try to register new ZeroID at http://127.0.0.1:43110/1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz/
You may receive error "Error while during request: error
undefined"

**Comment by HelloZeroNet** [comment]
Thanks for reporting, this should be fixed now.

**Comment by oldsiks** [comment]
This problem has not been fixed yet

**Comment by caryoscelus** [comment]
@oldsiks that particular instance of a problem was fixed

now we have similar problem, but it isn't going to be fixed, because nobody has access to zeroid server/private keys anymore
