### ISSUE TITLE
1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp/ZeroNet/src/lib/BitcoinECC/__init__.py'   missing

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#2234]
### Step 1: Please describe your environment

  * ZeroNet version: latest container LOL
  * Operating system: docker
 

### Step 2: Describe the problem:

run the update is broken

#### Steps to reproduce:

  1. set container
  2. go to 1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp/
  3. then apply the update

#### Observed Results:

`Update error: [Errno 2] No such file or directory: u'./data/1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp/ZeroNet/src/lib/BitcoinECC/__init__.py'- Starting ZeroNet...`

#### Expected Results:

  * What did you expect to happen?

get the update

**Comment by HelloZeroNet** [comment]
Yeah, the docker image is broken and outdated, I will try to figure out how to update it to the latest version

**Comment by rllola** [comment]
@HelloZeroNet I can take a look if you are too busy. I also used the docker container.

**Comment by HelloZeroNet** [comment]
@rllola  That would be great, to be honest I have not used docker before.

**Comment by filips123** [comment]
@HelloZeroNet Current `Dockerfile` in `py3` branch is actually correct. However, it is not published to [Docker Hub](https://hub.docker.com/r/nofish/zeronet). Changing `Dockerfile` is not really needed, as you probably just need to publish new version to Docker Hub.

**Comment by rllola** [comment]
@filips123 is right. The `py3` version of the `Dockerfile` should be published to the docker hub.

However it does not fix this issue... I am not sure how to reproduce it.

@icf20 Did you use `docker build` command or did you download the image through Docker Hub ? Would also help to know which version of ZeroNet you are running in the container... You can check it by doing `docker logs`.

**Comment by icf20** [comment]
@rllola 

> did you download the image through Docker Hub ? 

yes

> Would also help to know which version of ZeroNet you are running in the container

i remove the container, i cant help on that

**Comment by rllola** [comment]
Thank you @icf20.

I can't reproduce this. But like it was mentioned before the docker hub version is using a really outdated version of ZeroNet and use python 2. 

Publishing a more recent build to docker hub should help.

@HelloZeroNet do you think you can update it ? I think it would avoid future hassle. Maybe we can automatize this ?

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, I think it's done: https://hub.docker.com/r/nofish/zeronet/builds

**Comment by rllola** [comment]
The latest build works fine. I believe this issue can be closed.
