### ISSUE TITLE
ZeroID registration fails with error "Error while during request: error undefined"

### ISSUE THREAD

**Issue by Logusrei** [HelloZeroNet/ZeroNet#2235]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Windows 10
  * Web browser: Yandex Browser
  * Tor status: always
  * Opened port: yes
  * Special configuration: no

### Step 2: Describe the problem:

Not work ZeroID registration fails with error "Error while during request: error undefined"

**Comment by purplesyringa** [comment]
@HelloZeroNet Can you please renew zeroid.qc.to certificate?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed!
