### ISSUE TITLE
Zeronet bridge - dedicated class

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#2236]
This is a working concept for a redirector zeronet bridge that can be shared instead of regular ZN links.

It detects if ZN is working on a computer and then redirects to Zeronet url or offers option to download Zeronet client. The idea is to help people which are unfamiliar with ZN and don't know what to do with regular ZN link and have to google for it.

It works with css class and is kind of hacky. As feature request I ask for a dedicated css class in HelloZN.
It such case css modifications wouldn't break the functionality.

**Comment by purplesyringa** [comment]
@HelloZeroNet @filips123 For the record: we can use `.zeronet.link` as the default suffix when we switch to better site handling. IPFS guys were going to use `.ipfs.dweb.link` or similar.

**Comment by filips123** [comment]
@imachug But `.ipfs.dweb.link` is actually existing public IPFS instance. So, in case in there is public ZeroNet instance, the suffix should be `.zeronet.dweb.link` (or any other public instance/proxy domain). But for local ZeroNet instances, only `.zeronet` should be used.

**Comment by purplesyringa** [comment]
> But for local ZeroNet instances, only .zeronet should be used.

Why though? `.zeronet.link` or similar look great to me, whilst to `.zeronet` TLD is not registered globally and thus won't be allowed by many filters and people who don't have ZeroNet installed will have no idea how to install it.

**Comment by filips123** [comment]
@imachug Because `.link` is real TLD so `.zeronet.link` would mean that there is real server publically hosted on it (and that all requests are made to it). IPFS's `.ipfs.dweb.link` is actually also just a (centralized) IPFS proxy open to the web.

But `.zeronet` would be special-use domain so it is clear that it is used for something else than normal internet. Note that Tor also uses `.onion` in a similar way.

**Comment by krzysztof113** [comment]
@HelloZeroNet If you would like to make this recommended way of sharing links in clearnet I'm ok with transferring domain etc for security reasons.
