### ISSUE TITLE
Content Signing Error: FOREIGN KEY

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2247]
### Step 1: Please describe your environment

  * ZeroNet version: Latest ast of 1512PST -8, 10-25-2019
 * Operating system: Windows 10 Pro, 1903 (BUILD: 18352.418)
  * Web browser: Chrome
  * Tor status: Confused as to what your asking here
  * Opened port: no
  * Special configuration: None

### Step 2: Describe the problem:
Occasionally, i get a `Content Signing Error` that i was not getting back on the python2.7 builds after updating to the new py3 builds
#### Steps to reproduce:
I dont know, im having this issue

all i was doing was trying to make a post on ZeroTalk
#### Observed Results:
[!img](https://i.imgur.com/Uky8hNs.png)
#### Expected Results:
Normal Posting

**Comment by HelloZeroNet** [comment]
Please try to open the sidebar and Rebuild the database for that site

**Comment by purplesyringa** [comment]
@HelloZeroNet That error message mentions ContentDb, doesn't it? In cade rebuilding doesn't help, you can stop ZeroNet, delete data/content.db file and start ZeroNet again. It might take a while to restore the database.

**Comment by Merith-TK** [comment]
I just deleted the zite and redownloaded it, it fixed it
