### ISSUE TITLE
Fonts don't work in Tor Browser

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2249]
Gettings CORS error because Tor thinks the font is from a different origin. If you look at the request headers, you'll see that origin is null.

![Screenshot from 2019-10-26 18-56-41](https://user-images.githubusercontent.com/4098042/67627485-f2f17e00-f822-11e9-8274-2752ac7c453d.png)
-----
![Screenshot from 2019-10-26 18-59-40](https://user-images.githubusercontent.com/4098042/67627486-f422ab00-f822-11e9-8171-8203df71f4d4.png)

**Comment by HelloZeroNet** [comment]
After some testing: It happens because Tor browser sends the header `Referer: http://127.0.0.1:43110/` instead of `Referer: http://127.0.0.1:43110/1Site...` 

ZeroNet currently only adds `Access-Control-Allow-Origin = "*"` If the the referer matches the site address. I think we can remove this limitation, because by using the link tag it's possible to load the resource anyway. As it was demoed on site 1ScanCY9fjmjanDt7NwvyNQCL16hqWnVM.

**Comment by hacktivist** [comment]
@HelloZeroNet @krixano : https://github.com/HelloZeroNet/ZeroNet/pull/2248/commits/091f30fbd7163a28736e970f9a432b67d4dab4c7

**Comment by ghost** [comment]
@HelloZeroNet @krixano https://github.com/HelloZeroNet/ZeroNet/pull/2248/commits/3e6087dae6fcb1b723f65ccb2b0e19c2b0de770c

**Comment by ghost** [comment]
This can be closed.

**Comment by purplesyringa** [comment]
This should only be closed when your PR is merged.

**Comment by ghost** [comment]
> This should only be closed when your PR is merged.

:tada:

**Comment by ghost** [comment]
@HelloZeroNet I thought you already fixed this referer thing. There was an issue a while ago talking about referers being changed by browsers.... I think @anoadragon453 created the issue for this.

The issue I'm talking about is #1931
(sidenote, that last comment I made 17 days ago happened to be a bug in my own code and seemingly unrelated the the issue that *was fixed* because I was one of the people who tested it in Firefox Private mode)

**Comment by HelloZeroNet** [comment]
Thanks for reporting this should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/270f3e9ffdf45ac402aee5d8e714290af209402a in Rev4250

**Comment by ghost** [comment]
Thanks @HelloZeroNet !
