### ISSUE TITLE
[Consult] What method did you use to package the program?

### ISSUE THREAD

**Issue by mo-han** [HelloZeroNet/ZeroNet#2251]
Hi, just curious and wanna learn something new.
I saw the `ZeroNet.pkg` file in the released version (win64), which is a new form to me.
Tried to search in the net but cant get any results, just want to know what kind of method did you use to package zeronet and what's inside this `zeronet.pkg` file.
Thanks.

**Comment by HelloZeroNet** [comment]
It's generated by PyInstaller using this script: https://github.com/HelloZeroNet/ZeroBundle/blob/py3/compile_win.cmd

It has a tool (pyi-archive_viewer) to inspect these packages: https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#inspecting-archives

**Comment by mo-han** [comment]
Hi,
I've checked the .cmd and .spec files, also learned the "archive" thing on pyinstaller.readthedocs.io, but still have no idea how that "zeronet.pkg" file is generated. Could you please tell me something more about it?
Thanks.

**Comment by HelloZeroNet** [comment]
It's automatically generated by the pyinstaller script by running `py -3 -m PyInstaller script/pyinstaller_win.spec -y` line
