### ISSUE TITLE
Chao Italian Ristorante :)

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2256]
Pizza, Pizza! :rofl: :astonished:

**Comment by ghost** [comment]
#2248

**Comment by ghost** [comment]
@HelloZeroNet This isn't an issue regarding ZeroNet code and doesn't use one of the provided templates so it should be closed.

**Comment by hacktivist** [comment]
@krixano I can open empty issue as well you fucking maniac!

**Comment by ghost** [comment]
Of course you can... doesn't mean your issue is not irrelevant.

**Comment by ghost** [comment]
Looks like there was **plenty** discussion in #2248 to me. Stop lying, god damn...
Me, @imachug , and @HelloZeroNet all disagreed with your caching. Get over it.

**Comment by hacktivist** [comment]
You @krixano said here: https://github.com/HelloZeroNet/ZeroNet/pull/2248#discussion_r339604806
> I'll be making my own PR.
What this mean that because I sent a PR with MY modifications what you wanted to steal and claim, you was fast contacted @shortcutme and @HelloZeroNet to close my PR fast as possible!

**Comment by hacktivist** [comment]
You archived what you wanted. @shortcutme broken apart my PR and fast implemented and all this because of you! Disgusting that this can happen when someone wish to contribute!

**Comment by hacktivist** [comment]
> Looks like there was **plenty** discussion in #2248 to me. Stop lying, god damn...
> Me, @imachug , and @HelloZeroNet all disagreed with your caching. Get over it.

At least they helped and did not wanted to claim ownership over my Pull Request! You are a disgusting piece of shit!

**Comment by ghost** [comment]
Uh, no... lol

As you can see, my commit was done within the same hour as nofish's commits. I didn't even get a chance to make the PR, lol. Secondly, I had no contact with nofish whatsoever aside from that issue where **multiple people told you the caching was the wrong thing to do**.

![Screenshot from 2019-10-28 12-16-46](https://user-images.githubusercontent.com/4098042/67700997-1cbeb800-f97d-11e9-93e5-00c2e819021f.png)
![Screenshot from 2019-10-28 12-16-38](https://user-images.githubusercontent.com/4098042/67701000-1fb9a880-f97d-11e9-8bf2-15bb3b6bfc05.png)


And finally, you can see in my commit on my ZeroNet fork, I didn't even take your code, so stfu.

**Comment by hacktivist** [comment]
> I'll be making my own PR.

is very clearly saying you wanted to claim ownership over my modification and have a new pull request in your name! Remember this also? https://github.com/HelloZeroNet/ZeroNet/pull/2248#discussion_r339610967

**Comment by ghost** [comment]
No it's not. It's very clearly saying I'll be implementing the same idea with my own code. Additionally, this is evidenced in the differences between my commit and your pr... if you bothered to look.

**Comment by hacktivist** [comment]
:rofl: You are a retarded fuck! Get lost man!

**Comment by ghost** [comment]
I didn't know that to just *make* a PR you had to copy code. Hm... interesting. Because I thought making a PR involved writing changes in a fork and clicking "create pr" on github.

**Comment by hacktivist** [comment]
Difficult to talk yourself out of this... Feels shit huh? :rofl:

**Comment by ghost** [comment]
I don't need to talk myself out of anything. You can literally *see* proof that I didn't copy your code on GitHub. So no, doesn't "feels shit" (you forgot the work "like" btw).

**Comment by hacktivist** [comment]
> PR you had to copy code. 
I come up with some solution including for your shitty font loading problem in Tor Browser! https://github.com/HelloZeroNet/ZeroNet/issues/2249 

So don't fuck with me man or you will cry like a baby in the end!

**Comment by ghost** [comment]
![Screenshot from 2019-10-28 12-30-09](https://user-images.githubusercontent.com/4098042/67701912-cfdbe100-f97e-11e9-9e8c-31794bb0fb2e.png)

**Comment by ghost** [comment]
> So don't fuck with me man or you will cry like a baby in the end!

I'll be reporting this as a threat.

**Comment by hacktivist** [comment]
:rofl: Run report me!

**Comment by ghost** [comment]
I guess the issue resolved. :clap:
