### ISSUE TITLE
ZeroNet

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2257]
:+1:

**Comment by purplesyringa** [comment]
> This Hungarian guy who don't speak English

> people who caching applications

> decide what ... ZeroNet works

### 🤦‍♂

**Comment by hacktivist** [comment]
Well, at least you get the idea.

**Comment by purplesyringa** [comment]
Ok... Can you please explain what the vulnerability is and how your PR fixed it?

**Comment by hacktivist** [comment]
How many times I need to say that the header `Referrer-Policy: "no-referrer"` fixing [reverse tabnabbing](https://www.owasp.org/index.php/Reverse_Tabnabbing)? 
@HelloZeroNet or @shortcutme have no clue what is this header and thinks that is the same as attribute `rel="noreferer noopener"` BUT **IS NOT THE SAME!**

**Comment by purplesyringa** [comment]
Ok... now how does that help if it's *iframe* that opens links, not wrapper?

**Comment by purplesyringa** [comment]
> BUT IS NOT THE SAME

But... why? [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) says that it's the same.

**Comment by purplesyringa** [comment]
By the way, you forgot "r".

**Comment by hacktivist** [comment]
**IT IS NOT THE SAME!** I did not forget the r!

**Comment by purplesyringa** [comment]
Ok, can we assume it was just a typo? I mean, you'd still google the correct pronounciation before using it and I *think* browsers would tell you if you used an invalid rel value.

**Comment by HelloZeroNet** [comment]
I just tested and no-referrer does not fixes tabnabbing:

Without Referrer-Policy: "no-referrer":
 - Chrome + same origin: no referrer, window.opener limited
 - Chrome + different origin: no referrer, window.opener limited
 - Firefox + same origin: referrer present, window.opener limited
 - Firefox + different origin: referrer present, window.opener limited

With Referrer-Policy: "no-referrer":
 - Chrome + same origin: no referrer, window.opener limited
 - Chrome + different origin: no referrer, window.opener limited
 - Firefox + same origin: no referrer, window.opener limited
 - Firefox + different origin: no referrer, window.opener limited

So it has no effect on the linked issue

**Comment by purplesyringa** [comment]
@HelloZeroNet I guess that's because we use `sandbox`, right?

**Comment by HelloZeroNet** [comment]
The header never ment to fix the tabnabbing. It just removes the referrer header, but the linked issue nothing to do with the referrer header.

**Comment by ghost** [comment]
He escaping sandbox while using `target _blank`! https://github.com/HelloZeroNet/ZeroNet/commit/e82155aac4e75b1e67ae3f569a912b8f40fc8f48

**Comment by purplesyringa** [comment]
🤦‍♂ That sandbox is not the sandbox we're using. You could only have access to the wrapper if you were the wrapper... And that's literally impossible.

**Comment by hacktivist** [comment]
This keyword does not create a hyperlink, but annotates any other hyperlinks created by the element (the implied hyperlink, if no other keywords create one). [Link type "noreferrer"](https://html.spec.whatwg.org/dev/links.html#link-type-noreferrer)

What this mean is that if you have a link in a RDFa than actually you the RDFa distiller can't process none of your links! 

`<a property="schema:url" href="https://example.org/" rel="noopener noreferrer">https://example.org/</a>`

**Comment by HelloZeroNet** [comment]
So looks like we can agree on you can't fix the linked issue with http headers.
