### ISSUE TITLE
Custom bootstrap nodes for full Tor support

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#226]
Plugin for custom torrent-tracker like bootstrapping, it will allow full Tor support with hidden addresses
 - Allows to store Tor/ipv6/i2p addresses
 - Announce multiple site in one request

New FileRequest command:
 - announce:
```
{
 "sites": [hash1,hash2, ..], 
 "port": 15441, 
 "onion": "3fyb44wdhnd2ghhl", 
 "onion_publickey": "publickey for onion address",
 "onion_sign": "signed hashes array to provide proof of onion_address", 
 "onion_sign_this": 439284923849,
 "need_type": ["tor","ip4", "ip6"], 
 need_num=10
}
```
Return: 
```
[
 { "ip4": [address1, address2], "onion": [address1, address2]}, "onion_sign_this": current_timestamp}
]
```

`onion_sign_this` is only returned if new address is added for onion address. It's required to avoid signing up addresses you don't own. If `onion_sign_this` is in the returned result then the client has to sign it using the onion address's RSA private key and execute the announce request again with `onion_publickey`, `onion_sign` and `onion_sign_this` fields added.

New command line option: --tor, values
 - Always: Open hidden service on startup, use Tor for every connection, do not bind on normal ip
 - Enable: If no external IP then open Tor hidden serice on startup, use Tor only for onion addresses (default mode)
 - Disable: Do not use Tor at all

Disable [unnecessary](https://www.reddit.com/r/onions/comments/27a64z/https_everywhere_onions/chz70i9) SSL encryption on onion address connects (speeds up connection time)

- [x] New FileRequest command: announce
- [x] Modify zeronet to support bootstrapping from other clients
- [x] Onion address cryptographic functions (sign, verify, pubkey to onion address)
- [x] Onion address support for Bootstrapper
- [x] Onion address support for ConnectionServer
- [x] Disable SSL over Tor connections
- [x] Store Tor clients
- [x] Exchange Tor clients over PEX
- [x] Start/stop hidden services on site visit/delete
- [x] Test Connection peer lock
- [x] Display Tor status in ZeroHello
- [x] Only Tor mode
- [x] Disable Tor mode
- [x] Support Tor control port auth
- [x] Bootstrap statistics page
- [x] Batch onion announce
- [x] Option to keep ssl certs to allow cert pinning
- [x] Do some real-life testing
- [x] Pack Tor client with ZeroNet
- [x] New command line option: --tor

**Comment by str4d** [comment]
Regarding the note about including I2P addresses, it would be a good idea to read I2P's BitTorrent docs (linked in #45) to check how I2P's slight torrent protocol differences would affect ZeroNet. I don't think it should overly affect this ticket, but I'm not familiar with ZeroNet specifics.

Disclaimer: I'm an I2P developer (and happy to answer questions!)

**Comment by alxbob** [comment]
+1

**Comment by HelloZeroNet** [comment]
new ADD_ONION and DEL_ONION commands for per site (and preferably per user) different onion address: https://github.com/Yawning/torspec/blob/master/control-spec.txt

**Comment by alxbob** [comment]
Shouldn't also each seeder start a hidden service for each site he/she servers?

**Comment by HelloZeroNet** [comment]
what do you mean?

**Comment by alxbob** [comment]
I mean each seeder should run a tor hidden service to actually serve .onion sites right?

**Comment by HelloZeroNet** [comment]
The new ADD_ONION and DEL_ONION commands allows to create and remove hidden services using the onion controller API. So if you visit a new ZeroNet site then a new hidden service (.onion address) will be created for it and also new .onion addresses will be generated when you restart your client.

**Comment by alxbob** [comment]
Neat ! Thanks for the explanation check the links i wrote about here too :

https://github.com/HelloZeroNet/ZeroNet/issues/60

**Comment by HelloZeroNet** [comment]
Done in Version 0.3.5
