### ISSUE TITLE
Where you spending $90,000 which donated to ZeroNet?  

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2261]
I'm very interested how you planning to spend this money? 

In Budapest this amount of money is equals to about 26,516,459 HUF with what you can buy a little castle.

I'm very sure you will not spend any money from this to run ZeroNet gateways for the public and even if you would run it certainly you will host the servers in some shitty country like Hungary, USA, Israel...

**Comment by HelloZeroNet** [comment]
I don't have any plans yet. Right now I don't have any financial problems and I can sustain myself without using the donations.
