### ISSUE TITLE
How the $90,000 USD will be used which donated to ZeroNet?

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2262]
@HelloZeroNet said: 
> I don't have any plans yet. Right now I don't have any financial problems and I can sustain myself without using the donations.

**I can understand you and I think you did a great job @shortcutme!** I'm just angry at you for other reasons.

Use the donations but with limit! I don't think anyone would have problem with that if you use let's say $2,000 USD!

**Comment by ghost** [comment]
If I'm you I would run a bunch of servers for years and use them as public gateways to ZeroNet! **That would help people!** You can ban video streaming on them to save bandwidth.

**Comment by LWSS** [comment]
I'm actually lookin at a 2004 lambo
