### ISSUE TITLE
Copyright and License: Information about the copyright notice and license location in ZeroNet source code.

### ISSUE THREAD

**Issue by antifa** [HelloZeroNet/ZeroNet#2272]
https://github.com/HelloZeroNet/ZeroNet/issues/2271

You cant say GPLv3+ and Apache 2.0! **You are not licensing Apache!** You upgrading the license of ZeroNet!

**Comment by antifa** [comment]
I also note that this: 
> [if you accept switching to an Apache-compatible license](https://github.com/HelloZeroNet/ZeroNet/issues/2271)
**is absolutely ruining ZeroNet!** 

Why people who don't understand licenses trying to switch? 

**YOU CAN'T INCLUDE GPL LICENSED SOFTWARE IN A SOFTWARE WHICH IS LICENSED UNDER APACHE!**

**Comment by filips123** [comment]
> Notice: "Apache-compatible licenses" here refers to both MIT license and BSD 2/3 clause licenses.

**Comment by antifa** [comment]
Say it than explicitly!

**Comment by filips123** [comment]
It is said explicitly in the voting issue.

**Comment by antifa** [comment]
:confused:

**Comment by krixano** [comment]
> Switching to Apache-compatible license would require all GPL dependencies to be replaced. Not allowing the switch to a different license (therefore keeping GPLv2) would also require all GPLv3 dependencies, as well as Apache dependencies, to be replaced.

**Comment by antifa** [comment]
Just upgrade the license to GPL-3.0-or-later! 
Why you need to complicate it?

**Comment by krixano** [comment]
Because as clearly shown in the issue, not everyone wants GPLv3

**Comment by antifa** [comment]
Well, not everyone can get ice cream either! GPL-3.0-or-later is the most compatible license and if ZeroNet really cares about the future than the upgrade should be done soon as possible!

**Comment by krixano** [comment]
But we have to get agreement from all contributors, don't we? You can't force people to switch to a license that they don't want to switch to.

**Comment by antifa** [comment]
You don't have too! There is no other option! You just wasting your time! You can't keep it under GPLv2 **and you can't change the license to any other license!**

**Comment by antifa** [comment]
The pull request: https://github.com/HelloZeroNet/ZeroNet/pull/2270 have two files `COPYING` with the full text of GPLv3 and `LICENSE` where is the copyright notice and makes ZeroNet's license GPL-3.0-or-later! 

Need to create more new files also because of the requirements. Having this, for example list of contributors on GitHub only is not enough specially if someone distributes a copy of ZeroNet offline.

**Comment by filips123** [comment]
> Need to create more new files also because of the requirements. Having this, for example list of contributors on GitHub only is not enough specially if someone distributes a copy of ZeroNet offline.

Can't you just link those GitHub things from README? Having so many files (and with duplicated content from GitHub website) makes no sense.

**Comment by antifa** [comment]
@filips123 No. See example: **GIMP** https://github.com/GNOME/gimp/blob/mainline/AUTHORS
(GIMP uses LGPLv3)

**Comment by filips123** [comment]
GIMP's GitHub repository is just a mirror from another server. That's why it stores those things in files.

**Comment by antifa** [comment]
It is make sense! `LICENSE` is the **license** and `COPYING` is the full text of the GPLv3 license! 

> You should have received a copy of the GNU General Public License along with this program.

**Comment by antifa** [comment]
> `LICENSE` should just contain license text, while "copyright notice" should be in README.

README is not detected by GitHub as the source of the license! 
See https://github.com/antifa/ZeroNet

**Comment by 0x6a73** [comment]
@HelloZeroNet It looks like trolls are spamming the issue tracker again. It'd be great if you could help with that. Thanks.

@antifa Rewrite your first post, but slowly this time. Due to your broken english it's hard to understand what you mean.

**Comment by antifa** [comment]
Delete your comment @0x6a73! You are not welcome here. We are talking about something and I have doubt you have any constructive comments.

**Comment by filips123** [comment]
> README is not detected by GitHub as the source of the license!

Yes, as GitHub uses `LICENSE` file as source.

Basically, files should stay as they are currently, only `LICENSE` needs to be updated to contain new full license text and README needs to be updated to include license notice.

**Comment by 0x6a73** [comment]
@antifa "Delete your comment"? I have a right to state any opinion here as long as it's legal according to the law in the USA.

**Comment by 0x6a73** [comment]
Also, "wasting your time"? What do you mean? There is no such thing as specified amount of time since your "discovery" to when some unspecified very bad event happens.

**Comment by antifa** [comment]
@filips123 That would mean that you can license it only GPLv3 but **not** GPLv3-or-later! If need the later and it should be "or-later" than you must have this structure. README also should not contain copyright notice because is not its function!

**Comment by filips123** [comment]
If you want "or-later", you specify this in README:

> # License

> This library is licensed under the GPLv3+ license. See the LICENSE file for details.

**Comment by 0x6a73** [comment]
>README also should not contain copyright notice because is not its function!

Just because something isn't meant to be used that way doesn't mean it can't be.

**Comment by filips123** [comment]
Also, most newer open source projects are using structure I specified. GIMP (and other projects) which still uses multi-file structure were made a long time ago when GitHub didn't have such features.

**Comment by antifa** [comment]
You can't @filips123! You need to have this: 

```
ZeroNet
Copyright (C) 2015–2020  ZeroNet contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

-- See the 'COPYING' file in this directory for details.
```
This will be detected correctly by any scanner (https://github.com/filips123/scancode-toolkit) which scanning for copyright and licenses!

**Comment by 0x6a73** [comment]
@antifa Also, if you ever "doubt" something, then the best choice is to just check it out instead of straight up discarding it :)

**Comment by TundraFizz** [comment]
Funny how somebody named @antifa is trying to make authoritarian decisions without wanting anybody else a say in it...

**Comment by antifa** [comment]
In this case `LICENSE` will be detected as **GPL-3.0-or-later** and `COPYING` where the full unedited version of license is, will be detected as GPLv3.0. 

![ZeroNet Copyright and License](https://i.imgur.com/xSnXJsj.png "ZeroNet Copyright and License")

**Comment by 0x6a73** [comment]
@antifa Thanks for taking a less aggressive stance in this issue (and changing that issue name, lol)

**Comment by antifa** [comment]
Can someone post this image from here to: https://github.com/HelloZeroNet/ZeroNet/issues/2271? 

![Open-Source License Compatibility Diagram](https://2015.igem.org/wiki/images/2/29/CamJIC-Practices-CompDiagram.png "Open-Source License Compatibility Diagram") 
Source: Cambridge-JIC

**Comment by antifa** [comment]
It is clear most people don't understand https://github.com/HelloZeroNet/ZeroNet/issues/2271 that is why need some image there to show what is going on. 

You can't say GPLv3+ and Apache! GPLv3 supporting Apache 2.0! 

This is **nonsense**: 
> **Apache** if you accept switching to an Apache-compatible license. 

How many times I need to say can't change from GPL to something else!?

@krixano man, please correct yourself, you intentionally misleading all previous contributors!

**Comment by FrogCast** [comment]
@antifa 
What languages can you speak?
Your english is very broken and it is hard to ascertain exactly what you are trying to say.

**Comment by antifa** [comment]
I speak Spanish if needed, but GitHub is English unfortunately. `quit()`

**Comment by 0x6a73** [comment]
@antifa Let's settle this once and for all, answer simply to these two questions:
1. Do you consider ZeroNet's (and all of its versions) license revoked?
2. Does a project with a revoked license end up in public domain or becomes a proprietary software?

**Comment by antifa** [comment]
First of all,
I :heart: ZeroNet!

1, The license is automatically terminated and this not only means that GPLv2 but **all license which included in ZeroNet**,  for example AGPL-3.0-or-later and GPL-3.0 is also terminated automatically. 

2, A previously GPL licensed software if the license is terminated, becomes a software in the **public domain**! It can't become proprietary since that would mean that all forks and everyone with a copy of ZeroNet source code would need to delete that. 

Note that GPLv3 has provisions for termination which is way better than any other license. See, Section 8 https://www.gnu.org/licenses/gpl-3.0-standalone.html#section8

> Termination of your rights under this section does not terminate the licenses of parties who have received copies or rights from you under this License.

**Comment by antifa** [comment]
@filips123 Is worth noting that if anyone modifies Zeronet source code while still compying with the GPLv3 license he/she/they eventually **can add themselves to the contributors file** what they received with the copy of the source code! 

I do know that @HelloZeroNet (@shortcutme) has a practice of closing pull requests and don't gives credit to contributors but this is a limitation which can't be exercised anymore. Each person who contributes to the source code by any means whatever is a pull request or a merge in his/her/they repository is a contribution and he/she/they become also owners of copyright. 

I think is necessary to understand if pull requests are closed intentionally for example because @shortcutme don't like the requesting person is a violation of the license because it is excluding some people from contributing to ZeroNet and to the community as a whole. I consider this a restriction.

I seen that @HelloZeroNet copied some part of the code from a pull request and merged his own way the same code while he may slightly modified, and that is a copyright infringement. Is like copy someone else work from a book, rewriting and claiming copyright over that part without giving credit to the originator.

**Comment by namazso** [comment]
@antifa yes they very well can change the license of the source code to a more relaxed GPLv3 compatible license. There is no outside GPL code included in ZeroNet code.  There are GPLv3 libraries used, but the code for those is not here. Licensing this code under -say - Apache2 would mean that the code here is under Apache2, and the released binaries would need to be relicensed to GPLv3 (which Apache2 allows) because of the included GPLv3 dependencies which force the change.
Consequenrly, the current GPLv2 license on the code is also completely legal (opposed to what you've been spamming the issue tracker with). The only consequence of these incompatible licenses is that after building ZeroNet you are not allowed to redistribute the build due to complying with all the licenses when distributing is impossible. This is similar to the case of FFMPEG.
A way for ZeroNet to sidestep this issue without a license change would be releasing an easy to use compile kit, that compiles ZeroNet on each users own device. This practice is adapted by other projects, like Bukkit (a minecraft server-side plugin API).

**Comment by antifa** [comment]
I kindly request to close: #2273 
This voting is nonsense with this invented license combinations. I repeat again, that you **can't change the license from GPL** to LAX or any other license! **Is forbidden!** 
Apply the license GPLv3+ and we can close all issues related to licensing.

**Comment by antifa** [comment]
@namazso An Apache licensed software **can't** include any GPL licensed code! As I said there is no way to change from GPL to something else!

**Comment by namazso** [comment]
@antifa Do you see any GPL'd code other than ZeroNet's in this repo? 
I don't.
The builds indeed will because of the dependencies, which would indeed mean the builds themselves must be under GPLv3. Apache2 is also GPL compatible, therefore including ZeroNet's would-be-Apache2 code in the binaries, relicensed to GPLv3 would be ok too.

**Comment by antifa** [comment]
@namazso You misunderstand how GPLv3 and Apache 2.0 is compatible. 

An **Apache 2.0** licensed software **can't** include **any GPL** licensed code! :stop_sign: 
A **GPLv3** licensed software **can** include any **Apache 2.0** licensed code! :heavy_check_mark: 

ZeroNet **can't** change **from GPL to any other license**! :stop_sign: 

@namazso : Yes there is various code from third parties in ZeroNet source code, see here: https://c143a6e5-74e9-4e11-8f68-9fcac2eb0a4d.htmlpasta.com/

**Comment by antifa** [comment]
You said; 
> not allowed to redistribute the build

**There is no such thing as you are not allowed to distribute in GPL!** In GPLv3 you can even have a patent which includes ZeroNet!

**Comment by namazso** [comment]
Shouldn't have said `repo`. Indeed the license might need some clarification about how it doesn't apply to all the stuff that has their independent license.

However, you seriously misunderstood what "including" means. Until "linked" together, the code of ZeroNet, or any libraries for that matter are completely independent works. Sure, they can't *work* independently, but they can be distributed independently and licensed independently.

As for what happens after linking, you're correct about that you can't license the binary under Apache2, it needs to be under GPLv3. Which it could be if ZeroNet code was Apache2, because Apache2 is compatible to be relicensed to GPLv3.

If you want an example of this working, check out the FFMPEG project.

**Comment by namazso** [comment]
As for your last comment, I'm wondering if you have a hard time understanding English.

**Comment by antifa** [comment]
I udnerstand you but you don't understand the licenses. You can't just relicense from GPL to Apache! It is forbidden! You can't link together Apache 2.0 and GPLv2! Forget that.

**http://gplv3.fsf.org/wiki/index.php/Compatible_licenses**

**Comment by namazso** [comment]
@antifa i suggest that you familiarize yourself with the text of the GPLv2 license, available here: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
I recommend reading this part specifically:
> 2. You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions:
This means, you can modify it however you want, you only need to comply with the listed terms below it when you distribute the work based on the original work.

**Comment by namazso** [comment]
Also, I imagine Stallman crawling into your bedroom to check that you surely haven't linked together GPLv2 and Apache2 libraries for private use. Nonsense.

**Comment by antifa** [comment]
I do understand everything written there trust me. 

There is no such thing as abandoning GPL and switching to other license at will! 
There are more than **1,900 fork** of ZeroNet and this would create a lot of legal problems not to mention compatibility.

**Comment by antifa** [comment]
> Also, I can imagine Stallman crawling into your bedroom to check that you surely haven't linked together GPLv2 and Apache2 libraries for private use. Nonsense.

Since when ZeroNet is for private use only? :thinking:

**Comment by namazso** [comment]
My proposed solution for this mess would be clarifying which works in the repo are licensed under which license, abandoning all binary distributions, and developing a program that helps users download and compile / link the works needed for ZeroNet to function into a binary. This way we can avoid any license change.

In the very unlikely case that you suggest that linking together GPLv2 and Apache2 on your own machine for private use would be violating the license, it would still be the users violating the licenses independently and not ZeroNet. I'd count that as problem solved too.

**Comment by namazso** [comment]
> Since when ZeroNet is for private use only? 🤔

you said that you aren't allowed to link together Apache2 and GPLv2, as opposed to me saying that you just can't distribute the result. Me linking things together on my machine and not distributing the result is private use as far as I'm aware.

**Comment by antifa** [comment]
We are not discussing your private use of the software. You are free to do whatever you like for your private use. You however can't upload it to nowhere and can't distribute it either.

**Comment by antifa** [comment]
@namazso 
> users violating the licenses independently and not ZeroNet 

Seriously? :rofl: I will not fork anything from you ever! :rofl:

**Comment by mknepper** [comment]
@antifa 

Can you state in one or two sentences, succinctly and clearly, what you want changed?

**Comment by namazso** [comment]
> Seriously? rofl I will not fork anything from you ever! rofl

you sure have shown me

**Comment by antifa** [comment]
@namazso I don't want to show you nothing. :1st_place_medal:

**Comment by antifa** [comment]
@mknepper who said I want to change anything?

**Comment by imachug** [comment]
As we have #2274 now, can this issue be closed? @antifa I don't want to pollute our issue tracker.
