### ISSUE TITLE
You CAN'T switch from GPL to any other license! The voting should be about GPLv3 or GPLv3+ not about nonsense!

### ISSUE THREAD

**Issue by antifa** [HelloZeroNet/ZeroNet#2274]
I see the new voting in https://github.com/HelloZeroNet/ZeroNet/issues/2273
Lax/Permissive license this is NOT POSSIBLE! Don't even vote about it!

**And I also request to allow me to vote!** 
I also contributed to ZeroNet but @shortcutme given no credit whatsoever!

**Comment by krixano** [comment]
> Switching to a Lax/Permissive would require all GPL dependencies to be replaced. Not allowing the switch to a different license (therefore keeping GPLv2) would also require all GPLv3 dependencies, as well as Apache dependencies, to be replaced.

**Comment by antifa** [comment]
You don't understand do you? **You can't switch the GPL license to anything else!** 
You either keep GPLv2 and get rid of many things, or upgrade to GPLv3+ and everything is fine!

**Comment by imachug** [comment]
> You can't switch the GPL license to anything else!

Please show me a point in GPL license that says that changing license to non-GPL is not allowed.

**Comment by antifa** [comment]
@imachug I suggest to abandon the voting! You are a manipulative trash!
https://github.com/HelloZeroNet/ZeroNet/issues/2276#issuecomment-549246045
