### ISSUE TITLE
Wrong handling of a zite downloading - missing index.html error even it is not missing

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2277]
### Step 1: Please describe your environment

  * ZeroNet version: 4253
  * Operating system: Win
  * Web browser: FF beta

### Step 2: Describe the problem:

For a few seconds (?) the zeronet shows an error that the index.html is missing upon loading site http://127.0.0.1:43110/17aqJNrBjH63D5kgjLLfFi3FZVtW74JDxS/ for the first time. But after a while, index is downloaded automaticaly and the error disappear and real page appear.
I think this is confusing for the site visitors so they may close the page and never realize it is just zeronet showing false information for a few seconds.

#### Steps to reproduce:

Try to visit above linked zite for the first time and watch what will happen.

**Comment by antifa** [comment]
I agree with you, this is a big problem. ZeroNet should not display this message when there is an index.html file. 

ZeroNet is slower than IPFS regarding this. I also seen the issue you describing.

**Comment by HelloZeroNet** [comment]
For me it asks to increase the size limit, then after clicking on set size limit to 500mb button it downloads and displays the index.html. 

Update: I was able to reproduce the problem in FF. (previously tested in Chrome)

**Comment by HelloZeroNet** [comment]
Thanks for reporting this should be fixed in rev4259: https://github.com/HelloZeroNet/ZeroNet/commit/ac6900729281fc3ac7bb2ceb73a13b33794b8a4b

**Comment by slrslr** [comment]
@HelloZeroNet i have seen this issue re-appear today.

I see that the fix was in  plugins/TranslateSite/TranslateSitePlugin.py
made in Nov 11. I see on my computer (Linux) that i also have this file with same modification date and apparently containing the fix.
While i am having Zeronet rev4322 i have seen this issue today on site 1XinYeo9fCjP5VrayvR6iBMzyyWWq963J

**Comment by HelloZeroNet** [comment]
In the past days there were many fixes related to multi-threading issues that could have effect like this. Please update to latest version (Rev4358) and see if it's helps.

**Comment by slrslr** [comment]
@HelloZeroNet yes, i am in latest version rev4360 on Windows 10 i tried to backup site 1XinYeo9fCjP5VrayvR6iBMzyyWWq963J directory and then delete the site via zerohello. Waited until directory disappear. And visit the site again it was stuck on the "progress screen" after downloading content.json. then after many minutes i reloaded page, just to see it requires to increase the site limit. I think the prompt should appear without the need to reload the page.
When i confirm to increase size and open site, it shown Index not found kind of error for 6 seconds (wrong) and then it loadeded the index page (automatically without me refreshing).
So i think this issue remains and should be reopened @HelloZeroNet

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was unable to reliably reproduce it, but it did happened some times on slow connection. (tested with tor:always)
I have added fixes in Rev4394 the hopefully will solve this issue: https://github.com/HelloZeroNet/ZeroNet/commit/76e4b75c2d4d7bc2580feeb5296586dcf3fd814d, https://github.com/HelloZeroNet/ZeroNet/commit/c1ad7914f1834bdcee945237d1f24e74d812afb1
