### ISSUE TITLE
How to connect ZeroNet to the Tor Network?

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#228]
I started the Tor Browser, restarted ZeroNet and nothing happened. There is just the text "TOR: Waiting". How can I connect to the Tor Network introduced in version 0.3.5 (r830)? Maybe the issue is already posted here.

**Comment by koyuawsmbrtn** [comment]
Read the FAQ, followed the instructions but the same thing happened.

**Comment by HelloZeroNet** [comment]
What platform are you using?

**Comment by koyuawsmbrtn** [comment]
Ubuntu GNOME 15.10

**Comment by HelloZeroNet** [comment]
please try the instructions in #229, it helped there

**Comment by koyuawsmbrtn** [comment]
Okay, thanks for helping.

**Comment by Fil** [comment]
I'm looking for similar instructions for OSX + Tor Browser.

I've tried several things but can't find what to do.

in `tools/tor/torrc` I'm trying with:

```
ControlPort 9151
SOCKSPort 9150
CookieAuthentication 0
```

TorBrowser seems to be using SOCKS5 on :9150 (??)

**Comment by HelloZeroNet** [comment]
Tor by default running on ports 9050/9051. if you want to use it with Tor browser's tor instance you have start zeronet using `--tor_proxy 127.0.0.1:9150 --tor_controller 127.0.0.1:9151`

**Comment by Fil** [comment]
It works!  But then, what's the torrc file for?

**Comment by HelloZeroNet** [comment]
On windows tor is automatically downloaded on first startup that that's the configuration file for it. it's not used on other platforms

**Comment by Fil** [comment]
OK so it's a documentation issue. Here's some text that could be added to
“Frequently asked questions - ZeroNet” just after the Linux block:
http://zeronet.readthedocs.org/en/latest/faq/#how-to-use-zeronet-with-tor

```
### How to make ZeroNet work with Tor Browser under OS X?

Install TorBrowser.app; it exposes ports 9150 (SOCKS proxy) and 9151
(Control Port).

Launch `python start.py --tor always --tor_proxy 127.0.0.1:9150
--tor_controller 127.0.0.1:9151`

```

**Comment by HelloZeroNet** [comment]
It's not recommended to use the Tor browser's tor instance, because if you close the browser zeronet will also loose the connection. Running tor as system service is better: https://www.torproject.org/docs/tor-doc-osx.html.en

**Comment by Fil** [comment]
1. I understand. Not sure I fully agree, I like the idea to have zeronet connect through TorBrowser: it makes things easier to install and understand (is it on, is it off? You can see it immediately).
2. Currently the zeronet docs leads to Tor official install page, which in turn recommends TorBrowser in **bold face** on the first line of https://www.torproject.org/docs/tor-doc-osx.html.en 

Now, here's what happens when I quit TorBrowser.app and browse to a site that isn't available locally:
```
[15:39:22] TorManager Tor addOnion error:
[15:39:22] - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 69, in announceTracker
    onion = self.connection_server.tor_manager.getOnion(site.address)
  File "/Users/fil/Source/zeronet/ZeroNet/src/Tor/TorManager.py", line 256, in getOnion
    self.site_onions[site_address] = self.addOnion()
  File "/Users/fil/Source/zeronet/ZeroNet/src/Tor/TorManager.py", line 197, in addOnion
    res = self.request("ADD_ONION NEW:RSA1024 port=%s" % self.fileserver_port)
  File "/Users/fil/Source/zeronet/ZeroNet/src/Tor/TorManager.py", line 229, in request
    return self.send(cmd)
  File "/Users/fil/Source/zeronet/ZeroNet/src/Tor/TorManager.py", line 235, in send
    conn.send("%s\r\n" % cmd)
  File "/usr/local/lib/python2.7/site-packages/gevent/socket.py", line 437, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
```

**Comment by HelloZeroNet** [comment]
If you often leaves and re-joins the network, then it is bad for you: You client has to re-validate the contents by ask updates to all site you have visited before and it's also results lots of unreliable/unreachable peers which is bad for the network.

**Comment by Fil** [comment]
I don't quit TorBrowser.app very often, it was just for testing :)

When it comes to online/offline connectivity, I guess it's the same problem with tor as a service.

**Comment by HelloZeroNet** [comment]
For windows there is an "expert bundle" that contains tor.exe, so we can download/configure/start it automatically, it would be nice to have same way for mac, but i have not found binary tor.app distribution yet

**Comment by koyuawsmbrtn** [comment]
Mac OS is a Unix based system, so the Linux binaries should work with Mac, I guess.

**Comment by HelloZeroNet** [comment]
No, they not working, but there is no binary for Linux neither

**Comment by koyuawsmbrtn** [comment]
What about this?

https://www.torproject.org/docs/tor-doc-osx.html.en

**Comment by HelloZeroNet** [comment]
It works, see: https://github.com/HelloZeroNet/ZeroNet/issues/228#issuecomment-204717804

**Comment by NullFlex** [comment]
Or you can use proxifier, and set your proxy to 127.0.0.1:9150

**Comment by imachug** [comment]
@HelloZeroNet This issue is resolved -- can we close it?
