### ISSUE TITLE
Block Antifa - He's a Spammer

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2283]
Antifa/Hacktivist (his previous 4 accounts had the name "Hacktivist") has called multiple people "Polish". Someone else in #2269 also noted that he's able to respond 24/7, which is interesting.

Additionally, he is harassing everyone here and spamming issues and posts. I know I'd appreciate it if you just blocked him from the repo, because he's been doing this for over a week now and I'm just about fed up with it.

#2273 #2276

**Comment by ghost** [comment]
I agree with @krixano . Moreover, over past several days @antifa has commited countless violations of various software licenses, GitHub Terms of Service and even committed several crimes according to the law of USA.

EDIT: I've also reported his fake domains (namely - zeronet.host and zeronet.website) to abuse@namecheap.

**Comment by HelloZeroNet** [comment]
I just blocked him/her.
