### ISSUE TITLE
THEY LYING TO YOU AND MISLEADING YOU IN THE VOTING! 

### ISSUE THREAD

**Issue by LiberateZeroNet** [HelloZeroNet/ZeroNet#2285]
Everyone! https://github.com/HelloZeroNet/ZeroNet/issues/2273

@krixano and @imachug intentionally misleading everyone who contributed to ZeroNet! @shortcutme even closed various issues regarding the license to hide the reason of the voting! 

@imachug Yesterday;
### TRIED TO CLAIM PROPRIETARY RIGHTS OVER ZERONET!

I urge everyone to vote to GPLv3+ and liberate ZeroNet!

**Comment by 0x6a73** [comment]
Fuck off antifa

**Comment by 0x6a73** [comment]
@HelloZeroNet Could you block him, please?

**Comment by LiberateZeroNet** [comment]
The truth painful isn't? Fuck you you neo-Nazi shithead!

**Comment by 0x6a73** [comment]
For anyone not familiar with the entire situation: @LiberateZeroNet keeps creating new Github accounts, keeps spamming the issue tracker and making false accusations, while not wanting to discuss the license issue, calling everyone nazis instead.

**Comment by krixano** [comment]
To add onto this, his previous accounts were hactivist (he's created around 4 accounts with this name and deleted them) and antifa. He's been doing this for over a week.

I'm going to link screenshots of all of his previous comments under the account hacktivist.

![Screenshot from 2019-11-01 11-10-15](https://user-images.githubusercontent.com/4098042/68142588-5b142400-fef5-11e9-8e76-bef1908b6ffd.png)
![Screenshot from 2019-11-01 11-10-04](https://user-images.githubusercontent.com/4098042/68142602-61a29b80-fef5-11e9-9fdd-5b75f2e6b75e.png)
![Screenshot from 2019-11-01 11-09-41](https://user-images.githubusercontent.com/4098042/68142661-7c751000-fef5-11e9-9803-68d537b7adf8.png)
![Screenshot from 2019-10-28 12-31-16](https://user-images.githubusercontent.com/4098042/68142707-96165780-fef5-11e9-82c9-741e1a2d5043.png)
![Screenshot from 2019-10-28 12-30-09](https://user-images.githubusercontent.com/4098042/68142727-99114800-fef5-11e9-9d60-ece749158ba7.png)
![Screenshot from 2019-10-28 12-23-46](https://user-images.githubusercontent.com/4098042/68142734-9b73a200-fef5-11e9-8153-03084a2c6432.png)
![Screenshot from 2019-10-28 12-20-49](https://user-images.githubusercontent.com/4098042/68142742-a0d0ec80-fef5-11e9-88ea-5c60f7e6001c.png)
![Screenshot from 2019-10-28 11-54-44](https://user-images.githubusercontent.com/4098042/68142762-ab8b8180-fef5-11e9-8a2d-db54231a058c.png)
![Screenshot from 2019-10-28 11-52-17](https://user-images.githubusercontent.com/4098042/68142771-ae867200-fef5-11e9-8c45-a6cfb6432d1f.png)
![Screenshot from 2019-10-28 11-48-42](https://user-images.githubusercontent.com/4098042/68142790-b80fda00-fef5-11e9-9458-ce8a355e8473.png)
![Screenshot from 2019-10-28 11-47-04](https://user-images.githubusercontent.com/4098042/68142795-ba723400-fef5-11e9-99e4-71a2e67f273a.png)
![Screenshot from 2019-10-28 11-41-53](https://user-images.githubusercontent.com/4098042/68142810-c100ab80-fef5-11e9-9d32-684a6ebcef85.png)
![Screenshot from 2019-10-28 11-41-15](https://user-images.githubusercontent.com/4098042/68142813-c4943280-fef5-11e9-8d5b-c66947e35312.png)
![Screenshot from 2019-10-28 11-39-49](https://user-images.githubusercontent.com/4098042/68142824-c827b980-fef5-11e9-84ab-f31b3f8d84e6.png)
![Screenshot from 2019-10-28 11-37-46](https://user-images.githubusercontent.com/4098042/68142833-ccec6d80-fef5-11e9-8c0f-93d41259d347.png)
![Screenshot from 2019-10-28 11-36-22](https://user-images.githubusercontent.com/4098042/68142838-cfe75e00-fef5-11e9-90a7-a60eee58ecf1.png)
![Screenshot from 2019-10-28 11-18-22](https://user-images.githubusercontent.com/4098042/68142877-e392c480-fef5-11e9-966f-f87dd3eb34e6.png)
![Screenshot from 2019-10-28 11-07-22](https://user-images.githubusercontent.com/4098042/68142884-e7bee200-fef5-11e9-8532-c725fd40dede.png)
![Screenshot from 2019-10-28 10-01-14](https://user-images.githubusercontent.com/4098042/68142915-f4433a80-fef5-11e9-95b5-12d1152e64d9.png)
![Screenshot from 2019-10-28 09-59-17](https://user-images.githubusercontent.com/4098042/68142929-fc02df00-fef5-11e9-837d-ff39e6984dff.png)
![Screenshot from 2019-10-28 09-44-03](https://user-images.githubusercontent.com/4098042/68143005-1ccb3480-fef6-11e9-9b0f-6b341e626d11.png)
![Screenshot from 2019-10-28 09-43-54](https://user-images.githubusercontent.com/4098042/68143012-205ebb80-fef6-11e9-8566-c03cec7dc338.png)
![Screenshot from 2019-10-28 09-43-30](https://user-images.githubusercontent.com/4098042/68143030-2fde0480-fef6-11e9-9c02-1f6437be5387.png)
