### ISSUE TITLE
Documentation issue -  localhost

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#2288]
Documentation issue
In https://github.com/HelloZeroNet/ZeroNet#how-can-i-create-a-zeronet-site there is http://localhost:43110 instead of http://127.0.0.1:43110. It would be better to have coherent entry point for future situations like pattern match and batch updating.

**Comment by ghost** [comment]
Technically they both work, but 127.0.0.1:43110 is the most commonly used and what's opened by default by the client. I agree that that tutorial should be more consistent by using 127.0.0.1:43110.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroNet/commit/d3a0f5c26893bbca1fcd3e666bc62f9e08fa5727
