### ISSUE TITLE
backup zeroid

### ISSUE THREAD

**Issue by HarpyX** [HelloZeroNet/ZeroNet#2289]
i would like to have a way to backup my zeroid so i can reuse it insted of having to make a new one diferent from the one i used before each time i reinstall it if i lose my data, i can re download all the sites i had lost but my id i can never use again if i lose. please can you guys provice this or at least tell me what files i need to backup in order to preserve my zeroid

**Comment by purplesyringa** [comment]
All your private keys are stored in `data/users.json` file. If you want to backup your ZeroID, site private keys and encryption keys, that's everything you need. You might also want to backup `data/sites.json` (downloaded site list), `data/filter.json` (if you use blocklists) or the whole `data` directory if you don't want to redownload everything.

**Comment by purplesyringa** [comment]
@HarpyX Did that answer your question?

**Comment by HarpyX** [comment]
> @HarpyX Did that answer your question?

yes thank you

**Comment by purplesyringa** [comment]
@HarpyX @HelloZeroNet can someone close the issue please?
