### ISSUE TITLE
Tor control port authentication

### ISSUE THREAD

**Issue by voteforcoffee** [HelloZeroNet/ZeroNet#229]
The installation instructions for using ZeroNet through Tor on Linux (https://github.com/HelloZeroNet/ZeroNet/blob/master/tools/tor/manual_install.txt) say to uncomment the following line in the torrc file

    #ControlPort 9051

However, my torrc (Ubuntu 14.04, Tor 0.2.7.6) says right after that line

    ## If you enable the controlport, be sure to enable one of these
    ## authentication methods, to prevent attackers from accessing it.
    #HashedControlPassword
    #CookieAuthentication 1

That sounds like it would be a bad idea to not do this. The tools/tor/torrc file that is used for Windows I believe, has the line CookieAuthentication uncommented., so I tried uncommenting that line in my own torrc, but then ZeroNet reports an error saying it doesn't have permission to read the cookie file, seems to need root access.

**Comment by HelloZeroNet** [comment]
The Tor controll protocol (port 9051) only accept connections from 127.0.0.1, but if multiple user has access to your computer then it's recommended to enable CookieAuthentication.

You don't need root access, but you need to add to Tor's user group the user you use to run zeronet.

Steps to do this under Debian: http://zeronet.readthedocs.org/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

It should be similar under Ubuntu.

**Comment by voteforcoffee** [comment]
Awesome, thanks for the quick and detailed reply! The Debian instructions worked fine on Ubuntu, even the group name is the same (debian-tor). Works like a charm now :)
