### ISSUE TITLE
 An owner of this repository has limited the ability to comment from new users. 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2290]
An owner of this repository has limited the ability to comment from new users.

**Comment by zeronettimemachine** [comment]
before you ask why I not using: 
`new_content["youttimestamp_in_json"] = int(time.time()) `

The reason is that I have more than this in my `content.json` and if I don't do how I did in the [opening comment](https://github.com/HelloZeroNet/ZeroNet/issues/2290#issue-518645694) than I get:
`Sign error: TypeError: Object of type set is not JSON serializable`

**Comment by zeronettimemachine** [comment]
@filips123 any comment?

**Comment by purplesyringa** [comment]
Is there any reason for using `modified` for your value instead of another name? Based on your username, `_last_update` should work well (notice that I used `_` because that name might collide with some site-specific settings).

**Comment by zeronettimemachine** [comment]
@imachug where are tho site specific settings? I just found one in UiRequest.py which was "modified" and nowhere else. However as I said the ContentManager.py is full of modified and very difficult to navigate the code. Everything just thrown there no distinction whatsoever.

> Is there any reason for using modified for your value instead of another name? 
That what I'm saying. I'm not using it!

**Comment by zeronettimemachine** [comment]
@imachug Let me help you. I'm the same person who you hate and I'm using other timestamps along with the basic POSIX of what is shipped with ZeroNet. I also get rid of the zeronet_version from content.json for a very good reason. I think POSIX is nice to check when the content is modified but it is unreliable!

**Comment by purplesyringa** [comment]
> where are those site specific settings?

I mean, some sites (e.g. ZeroTalk and Git Center) use content.json to store their settings there.

**Comment by purplesyringa** [comment]
> I'm using other timestamps along with the basic POSIX of what is shipped with ZeroNet

Hm, if you're using POSIX timestamp already, can you maintain *both* `modified` and `_my_fancy_modified`? This will allow your modification to be ZeroNet-compatible. I also don't see any problems with this.

> I also get rid of the zeronet_version from content.json for a very good reason.

Can you elaborate please? AFAIK we don't use it but it might be a good way to monitor how people update.

**Comment by purplesyringa** [comment]
Also, `modified` is used directly for p2p communication to spread user file updates. Replacing it will most likely render ZeroNet unusable.

**Comment by zeronettimemachine** [comment]
> I mean, some sites (e.g. ZeroTalk and Git Center) use content.json to store their settings there.

That's is fine @imachug since I don't use any of those... 


> > I'm using other timestamps along with the basic POSIX of what is shipped with ZeroNet
> 
> Hm, if you're using POSIX timestamp already, can you maintain _both_ `modified` and `_my_fancy_modified`? This will allow your modification to be ZeroNet-compatible. I also don't see any problems with this.
> 

I use left POSIX as you shipped because its good but I needed something more so in the night I wrote something. 

> > I also get rid of the zeronet_version from content.json for a very good reason.
> 
> Can you elaborate please? AFAIK we don't use it but it might be a good way to monitor how people update.

Are you sure need to **monitor** people? This is something what ZeroNet should never do! If you send the version number may someone will come up with a ZeroDay or just come to GitHub check the issues and will attack people who has a specific version... 

I think is a risk to send version number in content.json and again is **unethical to monitor those numbers** by you or anyone else!

**Comment by zeronettimemachine** [comment]
> Also, `modified` is used directly for p2p communication to spread user file updates. Replacing it will most likely render ZeroNet unusable.

I'm not sure you need POSIX timestamp for these... I said I left POSIX in ZeroNet bit needed to change many things and now I still have 32 `modified` to replace... I need to test every single of them...

**Comment by purplesyringa** [comment]
> That's is fine @imachug since I don't use any of those...

So are you going to make a private-use ZeroNet fork? I guess it's fine then.

> If you send the version number may someone will come up with a ZeroDay or just come to GitHub check the issues and will attack people who has a specific version...

Not really. Trial-and-error would work as well even if we didn't send version.

**Comment by purplesyringa** [comment]
> and again is unethical to monitor those numbers by you or anyone else!

But why? It's quite useful for development, isn't it? We send the version in p2p protocol but I don't know why it's used in content.json actually. @HelloZeroNet Is there a reason?

**Comment by zeronettimemachine** [comment]
> > That's is fine @imachug since I don't use any of those...
> 
> So are you going to make a private-use ZeroNet fork? I guess it's fine then.

Far as I see it is still working with other nodes. I found no problem until now. 
Private use, yeah this already sounds like IPFS private network but its ZeroNet :)

**Comment by purplesyringa** [comment]
> I found no problem until now.

You're probably going to notice it later, lol. Currently `listModified` p2p command accesses ContentDb to get `modified` property, and that one is filled from content.json. Thinking more about that, you might be able to use either of these solutions:

- Either leave `modified` as-is and add your own property;
- If you want to change the way files are checked / downloaded, replace `modified` with something like version number (i.e. something that increases every time a change is made) and possible also use another property for version metadata or something;
- Another way is to replace `modified` with your own object and modify half of ZeroNet code to parse that value correctly.

I don't understand what your usecase is. I think that option 2 will work for you but if it doesn't, I would need some more information to help you. You can publish it here or to imachug@gmail.com if you want to keep it secret.

**Comment by zeronettimemachine** [comment]
@imachug I would be happy to publish it here even make a PR but I don't want again just give code and get no credit for it.

**Comment by zeronettimemachine** [comment]
I added the ISO 8601 (UTC) timestamp to my content.json as follows: 
```
        #Unix and ISO Timestamp
        unix_timestamp = int(time.time())
        utc_iso_timestamp = str(datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc).isoformat(timespec='milliseconds'))
        new_content["timestamp_unix"] = unix_timestamp
        new_content["timestamp_utc"] = utc_iso_timestamp
```

This is human-readable and maybe it is even more useful than simply using the unix timestamp.

File: [ContentManager.py.txt](https://github.com/HelloZeroNet/ZeroNet/files/3816347/ContentManager.py.txt)

**Comment by zeronettimemachine** [comment]
Tell me if you see something wrong in my file..

**Comment by zeronettimemachine** [comment]
I was used first `json.dumps` but abandoned quickly the idea after a few test;

json.dumps produce this: 
` "timestamp_utc": "\"2019-11-06T03:27:06.340973Z\"", ` :x: 

my solution produces this:  
`"timestamp_utc": "2019-11-06T05:02:09.671Z",` :heavy_check_mark:

**Comment by purplesyringa** [comment]
Actually, it *is* UTC time [as per this SO answer](https://stackoverflow.com/a/16554944). I am not sure why json.dumps provides incorrect results, let me take a look.

**Comment by zeronettimemachine** [comment]
@imachug Don't forget to `import datetime`! 

I don't used stackoverflow to craft the code above.

**Comment by purplesyringa** [comment]
That SO answer was just to explain that `time.time()` returns UTC time (at least on common OSes).

**Comment by purplesyringa** [comment]
Actually you haven't replaced all "modified" instances, e.g. here:

```python
                    sign_content = sign_content.replace(
                        '"modified": %s' % repr(modified),
                        '"modified": %s' % modified_fixed
                    )
```

Make sure to fix those as well.

**Comment by zeronettimemachine** [comment]
@imachug That is why I opened the topic! :)

**Comment by zeronettimemachine** [comment]
For those who say I contribute nothing to ZeroNet: https://github.com/HelloZeroNet/ZeroNet/issues/2273

**Comment by zeronettimemachine** [comment]
> Actually, it _is_ UTC time [as per this SO answer](https://stackoverflow.com/a/16554944). I am not sure why json.dumps provides incorrect results, let me take a look.

`json.dumps` gives good results but is enclosed like`\"datetime\"` I think is better how I did here: 
`utc_iso_timestamp = str(datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc).isoformat(timespec='milliseconds'))`

**Comment by purplesyringa** [comment]
`modified_fixed` stands for "recovered" or something like that here. Some Python implementations might give slightly incorrect results so ZeroNet fixes them.

**Comment by purplesyringa** [comment]
TBH I don't see any reason for any additional quotes

**Comment by ghost** [comment]
I agree with @imachug . I don't see any reason for doing that either.

**Comment by zeronettimemachine** [comment]
> `modified_fixed` stands for "recovered" or something like that here. Some Python implementations might give slightly incorrect results so ZeroNet fixes them.

What you mean by incorrect result? **You mean incorrect timestamp?** Than we do have a problem!

@0x6a73 please get lost I talking with @imachug about something important. Thank you!

**Comment by zeronettimemachine** [comment]
> TBH I don't see any reason for any additional quotes

Yeah that I fixed. No additional quotes in my code. Just said to you I used `json.dumps` and given me additional quotes: `"timestamp_utc": "\"2019-11-06T03:27:06.340973Z\"",`

**Comment by purplesyringa** [comment]
> You mean incorrect timestamp?

The timestamp was *mostly* correct, but it could be off by one or two digits because that's how floating arithmetic works.

**Comment by ghost** [comment]
@zeronettimemachine Since you've opened an open issue, then it's meant for public discussion ;)

Also, since we're working on relicensing the project, accepting new contributions may be a legal problem, at least until we resolve the licensing conflict. I'd advise to wait a few days until we settle on it.

**Comment by zeronettimemachine** [comment]
> > You mean incorrect timestamp?
> 
> The timestamp was _mostly_ correct, but it could be off by one or two digits because that's how floating arithmetic works.

I seen that in the python code. I think we should switch to this format; `2019-11-06T05:02:09.671Z`
and verify this one instead of the POSIX!

**Comment by purplesyringa** [comment]
Why's that? How is this new format better than POSIX timestamp?

**Comment by zeronettimemachine** [comment]
I really need to write that down now? This going to be long.

**Comment by ghost** [comment]
@imachug I agree. Creating new formats for the sole purpose of making them is both troublesome and increasing chances for a new security bug.

@zeronettimemachine Yes, please share your point of view with us.

**Comment by zeronettimemachine** [comment]
The biggest thing why the switch needed is that POSIX gives you only seconds. Like this one for example: 

```
$ date -d @1573012034
Wed 06 Nov 2019 03:47:14 AM GMT
```

Formatting the timestamp as I implemented will give more stability. you @imachug just confirmed what I seen in the source code, that is struggle with the timestamp.

> The timestamp was mostly correct, but it could be off by one or two digits because that's how floating arithmetic works.

ISO 8601 and many other RFC already have a long discussion about this, I believe that using the timestamp as **2019-11-06T05:02:09.671+00.00** (millisecond accuracy + timezone) way better than using posix.

**Comment by zeronettimemachine** [comment]
#ISO Timestamp 
        utc_iso_timestamp = str(datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc).isoformat(timespec='milliseconds'))
        new_content["timestamp_utc"] = utc_iso_timestamp

Will produce **2019-11-06T05:02:09.671+00.00** in `content.json`

**Comment by ghost** [comment]
OK, but why do you think that this may improve stability? What kind of time conflict could this prevent?

**Comment by zeronettimemachine** [comment]
@0x6a73 If you know the function of the **timestamp** this case in `content.json` and you know the purpose of `content.json` than you already know the answers.

**Comment by zeronettimemachine** [comment]
@imachug 

`$ date --utc +%FT%T.%3NZ` 
same as;

> ```
>     #ISO Timestamp 
>     utc_iso_timestamp = str(datetime.datetime.utcnow().replace(tzinfo=datetime.timezone.utc).isoformat(timespec='milliseconds'))
>     new_content["timestamp_utc"] = utc_iso_timestamp
> ```

Will produce **2019-11-06T05:02:09.671+00.00** (with millisecond accuracy + timezone).

I will test this for a while if no one else want to do it. I support to replace the timestamp and validate this one instead.
