### ISSUE TITLE
Voting fraud! How a guy named @krixano thinks he is the Mozilla Organization? Let me tell you.

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2291]
@krixano is a big fraud. The guy thinks that he is Mozilla! :rofl: You man never will be part of Mozilla and the voting can be closed when the majority more than 50% voted to **GPLv3+**!  

Mozilla is a big family and everyone knows the other and they helping each other.  Nothing like ZeroNet...
If I would see you @krixano probably I would just spit on your face. 
ref: https://github.com/HelloZeroNet/ZeroNet/issues/2273

**Comment by purplesyringa** [comment]
Eh, we aren't as big as Mozilla but before you came here, we were quite a good community.

**Comment by ghost** [comment]
3 person you call community? @imachug @krixano and @shortcutme ? :rofl: So big community...

**Comment by purplesyringa** [comment]
Add filips123, anoadragon453, geekless, glightstar and quite a few other active users.

**Comment by ghost** [comment]
Can you check out the other topic @imachug ? I close this...
