### ISSUE TITLE
Don't Redownload Files Upon Updates // Use CRDTs For Content Updates

### ISSUE THREAD

**Issue by Miserlou** [HelloZeroNet/ZeroNet#2292]
Hello, all!

I'm just discovering this project now, but I find it extremely exciting. There are a lot of really good decisions under the hood here, and I'm looking forward to being part of this community.

From my initial impression, there seem to be two main technical drawbacks compared to other P2P projects (though many more advantages): dependency on trackers (which is [already under discussion here](https://github.com/HelloZeroNet/ZeroNet/issues/1998) and is not a pressing issue), and the need to re-download the entire MySQL database whenever an update occurs.

It may be better to instead use [conflict free replicated data types](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type), as used by the `dat` and Etherpad projects, to avoid the need to resend the entire MySQL database whenever services are dynamically updated.

If my understanding of how P2P MySQL replication works is wrong, then please forgive me and treat this as a documentation bug! I'd love to know more details about how updates are negotiated and propagated across a swarm. (Surely there will be conflicts if SQL statements are shared between peers?)

Anyway, hello! Thanks for reading, and thanks for this project! Looking forward to contributing here and building ZeroNet services.

**Comment by zeronettimemachine** [comment]
Welcome! I just quickly add that I don't use MySQL at all and I think it should be not default in ZeroNet. I personally hate databases. But this again my own opinion.

**Comment by purplesyringa** [comment]
Actually, ZeroNet doesn't distribute the whole database. Instead, it distributes *data files* which are usually JSON files, optionally compressed. For example, your ZeroTalk posts are stored in `data/users/youraddress/data.json` file which gets distributed via p2p.

The database is created locally and is not shared. It is only used to speed up queries and can be in theory removed. Notice that this database is read-only; so sites modify data files to make a comment, then ZeroNet distributes this file update via p2p and updates the local database. When other peers receive data file update, they also reload this file to update their local database. As most files are small enough, database updates are usually very fast.

**Comment by Miserlou** [comment]
(Thank you very much for your swift replies!)

Ah, that's interesting, I didn't understand that. (I don't think that's explained in the documentation!)

Does that mean that the `data.json` files are redistributed in their entirety upon content change? 

For instance, imagine I am hosting a video on a "ZeroTube" YouTube alternative. If I'm hosting a video (I assume b64 or bencoded in my `data.json` file), if I decide to change a single pixel in the video, will the entire video be redistributed to peers? If so, then a trie/CRDT system could be implemented here to make the change propagation radically more efficient. If I'm wrong, what format do updates take?

Thank you for holding my hand through this!

**Comment by purplesyringa** [comment]
ZeroNet doesn't use database for blobs, they are just stored as files. It's however rather common to store metadata in data files and big data in separate files; for example, ZeroUp does exactly this.

Now, if we're talking about separate files, ZeroNet distributes files *diff* instead of files themselves whenever possible. If that's impossible (e.g. the peer doesn't have any previous file version), so-called *big* files (more than 10MB IIRC) are split into 0.5MB (again, the value might be slightly off here but it doesn't matter much) chunks that can be fetched from several peers in parallel, like Torrent.

**Comment by Miserlou** [comment]
Ah, okay! There it is. Are they just normal diff/patch format files?

**Comment by purplesyringa** [comment]
Almost. You can check the format at `src/util/Diff.py`.

**Comment by ghost** [comment]
Also, ZeroNet uses SQLite btw.

**Comment by Miserlou** [comment]
Ah. The wikipedia article is wrong then.

**Comment by zeronettimemachine** [comment]
> When other peers receive data file update, they also reload this file to update their local database.

Doing so by looking the timestamp right? https://github.com/HelloZeroNet/ZeroNet/issues/2290 :+1:

**Comment by purplesyringa** [comment]
Do you think this issue is resolved or do you have any other questions? If you don't, would you close this issue please?

**Comment by Miserlou** [comment]
I think this issue is resolved, but I still think that this should be documented somewhere.

Dat has this page: https://datprotocol.github.io/how-dat-works/

It'd be great if ZN could have something similar.

**Comment by HelloZeroNet** [comment]
Yeah thanks for the link, it looks great. We only have the basics in the gdocs presentation: https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000&slide=id.g9a1cce9ee_0_4

It would be great to have something similar, but not sure how deep should we go.
