### ISSUE TITLE
@krixano! Stop attacking Jeremy Rand! He is a greater man than you ever will be!

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2293]
The voting I criticized from the very beginning because it is **shady and misleading** and it is created by @krixano who voted GPLv3-only immediately when the poll opened. He since that manipulates people adding more choices and things. It is a disgrace! I also contributed to ZeroNet and I was not even able to vote because @krixano blocking me!  

I was various times also said that **the voting is unfair** and clearly favors and pushes for GPLv3-only. 
ref: https://github.com/HelloZeroNet/ZeroNet/issues/2273

I hope everyone will continue to vote for **GPLv3+**!

**Comment by ghost** [comment]
@HelloZeroNet It'd be great if you could block him. I've already reported his account.

**Comment by ghost** [comment]
:rofl: You do nothing in ZeroNet just looking for me and reporting my accounts? :rofl: What a joke you are @0x6a73 !

**Comment by purplesyringa** [comment]
What the heck! @HelloZeroNet Can we make a cooldown already or at least block users faster? ZeroNet issue tracker is being needlessly spammed. @zeronettimemachine Please don't create any issues anymore, use the ones you've created already.

**Comment by ghost** [comment]
@zeronettimemachine 

>you do nothing in Zeronet

Hm? I'm using it on daily basis, so certainly I'm present in the Zeronet network.

**Comment by ghost** [comment]
@HelloZeroNet Also, I'd recommend to try temporarily blocking newly registered users from posting in the issue tracker, at least until we decide on the next licensing scheme.

https://help.github.com/en/github/building-a-strong-community/limiting-interactions-in-your-repository

**Comment by ghost** [comment]
It the vote favors GPLv3-only, then why does the vote text say that the option that allows for GPLv3+ is recommended?

**Comment by ghost** [comment]
Btw, a person can change their mind. I've since changed my mind on GPLv3+, so now that's what I've voted for.

**Comment by HelloZeroNet** [comment]
This is not a chat, please use email for personal communication
