### ISSUE TITLE
Is not ZeroNet maintainer who decide the license of my contribution! I'm the one who reported license issues in ZeroNet and I'm a contributor like any of you! I urge ZeroNet to be licensed as GPLv3+ and NOT GPLv3-only! Switching to other licenses is NOT permited under GPL and by the vote either as I see!

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2294]
I will never allow one person to say that my contribution is under which license! **Every contributor to ZeroNet has a voice to say which license should be used!** This includes me too! 

ref: https://github.com/HelloZeroNet/ZeroNet/issues/2273 
(I need to open new issues because I'm blocked from talking on the voting)

**Comment by ghost** [comment]
@zeronettimemachine You didn't contribute anything yet though.

@HelloZeroNet Could you block the troll again, please?

**Comment by zeronettimemachine** [comment]
Troll is your mom! I do send code to ZeroNet while you just spamming everything for days!

**Comment by ghost** [comment]
> @zeronettimemachine You didn't contribute anything yet though.
> 
> @HelloZeroNet Could you block the troll again, please?

@0x6a73 @imachug 
I **contributed** to `UiRequest.py` and now I **contribute** to `ContentManager.py` + one little change again in `UiRequest.py`)

**Comment by ghost** [comment]
Not to mention the whole voting is started because of me! @JeremyRand please see the closed issues regarding the `LICENSE`!

Well, @JeremyRand all those issues has been gone because of suspension, now I see, but everyone remembers it! Right @filips123 and @imachug ? 

ZeroNet does have serious licensing issues and so those licenses has been automatically terminated! One of the licenses ZeroNet violated is suspended which is AGPLv3+! When ZeroNet will finally have GPLv3+ and should have! Then, AGPLv3+ will be reactivated automatically! 

The Apache license is also revoked and is very had in GPLv2 to get back those rights namely you need to contact the licensor and ask it. If the GPLv3+ upgrade is imminent than the Apache 2.0 also reactivates because you corrected your mistakes soon as you was able to do!

**Comment by HelloZeroNet** [comment]
Stop it
