### ISSUE TITLE
Issues with Cloudflare 

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2295]
### Step 1: Please describe your environment

  * ZeroNet version: ZeroNet 0.7.1 r4206
  * Operating system: Archlinux
  * Web browser: Chrome
  * Tor status: not available
  * Opened port: yes
  * Special configuration: Caddy Server for reverse proxy to clearnet, `basicauth` directive. (Cloudflare security enabled < this is causing the issue)

### Step 2: Describe the problem:
```
Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/95c75768/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-Qd2I5FAUfeZSSfs2E2XG48a53uvX7XfBglJX2BV4irEaeRguliiljfDHTGAcsy9F'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
I even disabled NoScript to see if it was an issue, same error without NoScript

#### Steps to reproduce:
Make a Clearnet node,
put said node behind Cloudflare and use their IP Protection proxy
It appears to be random 

#### Observed Results:
https://i.imgur.com/2rhdH20.png
![image](https://user-images.githubusercontent.com/10422110/68520790-909b7300-024f-11ea-8a2b-0af55254f857.png)

https://i.imgur.com/5s8ywiz.png
![image](https://user-images.githubusercontent.com/10422110/68520845-10294200-0250-11ea-9617-4d350ecba4c4.png)

#### Expected Results:
* Expected to load page normally

#### My Guess?
* Zeronet has some external js injection protection? if so, how do i whitelist cloudflare?

**Comment by purplesyringa** [comment]
On what sites does that happen?

**Comment by Merith-TK** [comment]
`/*`

litterally everything except `/Debug` as far as i can tell,
here is the exported harfile from chrome (acts as network log)

[zero.example.com.log.har.txt](https://github.com/HelloZeroNet/ZeroNet/files/3826918/zero.example.com.log.har.txt)

**Comment by purplesyringa** [comment]
Ok, so it looks like CloudFlare uses a script loader to load our scripts. ZeroNet uses CSP for security and adds nonce to all scripts; the logs you sent show that cloudflare didn't add the nonce to its script loader. I would recommend you to disable Rocket Loader. [Here's a link](https://documentation.deadlinefunnel.com/article/511-how-to-disable-cloudflare-rocket-loader) that shows how to do that.

**Comment by Merith-TK** [comment]
hey that fixed it!
I would reccomend putting that somewhere accessible for users!

**Comment by filips123** [comment]
@imachug Can ZeroNet be fixed to also support sites with enabled Rocket Loader? Or maybe Cloudflare can fix this on their end?

**Comment by purplesyringa** [comment]
CloudFlare refers to Rocker Loader as to an unsafe speed up, so I guess it'd be better just to disable it.

**Comment by filips123** [comment]
@imachug Yes, but this is just some workaround for the actual issue. It would be good to check why exactly it happens and how to fix it.

**Comment by HelloZeroNet** [comment]
It happens because the wrapper has a security header that only allows to load scripts that has the correct random nonce in the tag to protect against possible sandbox escape / script injection.
It could be possible to disable this feature, but it would reduce the security, so it's not recommended.

**Comment by Merith-TK** [comment]
Would it be possible to whitelist specific external JS files from the settings? 
For example, whitelisting cloudflare rocket.js? 


This way a user must WANT to allow that js to load, it would be handy for cloudflare protected nodes to increase their speed,

**Comment by filips123** [comment]
@HelloZeroNet Yes, but why does Cloudflare breaks it?

**Comment by Merith-TK** [comment]
@filips123 he basically explained it, Zeronet has Script Injection protection and breaks itself instead of breaking itself and showing an error along the lines of `Script injection detected from https://externet.clearnet.com/script.js`

**Comment by HelloZeroNet** [comment]
As far I know there is no way to whitelist a specific js file. Actually cloudflare could parse the header and inject the script tag with the correct script-nonce, but it's not implemented.

**Comment by filips123** [comment]
Could we then submit a bug report to Cloudflare? Rocker Loader could really be useful as most public ZeroNet proxies are running quite slow.

**Comment by Merith-TK** [comment]
Maybe we could patch the js? See if it works using a webserver software and
embed the new js? If I understood how it worked in the first place

**Comment by HelloZeroNet** [comment]
Actually I don't think if rocket loader make significant difference. Based on the faq it just merges and preloads js/css files, but we already do this.

But you can give a try by removing https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Ui/UiRequest.py#L284-L285 lines

**Comment by purplesyringa** [comment]
Eh, removing nonces doesn't look like a good idea to me. That's kinda unsafe, isn't it?

**Comment by Merith-TK** [comment]
@HelloZeroNet couldnt we just whitelist ajax.cloudflare.com?
