### ISSUE TITLE
How to change the logo of a ZeroBlog ?

### ISSUE THREAD

**Issue by sbDevGit** [HelloZeroNet/ZeroNet#230]
I tried to add an image called `logo.png` to `SITE_HASH/img/.`
and I signed the `content.json` thanks to the right window
and then I tried to published it
But the image doesn't change

How can I do this ?

**Comment by HelloZeroNet** [comment]
you have to edit css/all.css and put this line to the top:
`.left .avatar { background-image: url(../data/img/logo.png) }`
