### ISSUE TITLE
Znet/Console does not load

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2301]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 
  * Operating system: Arch
  * Web browser: Firefox
  * Tor status: Availble, tracker
  * Opened port: yes
  * Special configuration: Reverse Prxy

### Step 2: Describe the problem:
127.0.0.1:43110/Console does not load

#### Steps to reproduce:
Attempt to access `127.0.0.1:43110/Console

#### Observed Results:
```
Server error
Err: Exception: Here is your console in UiServer.py line 129 > UiRequest.py line 188 > UiRequest.py line 837
``` is shown to the user
#### Expected Results:
Somthing, i am more just curious about what it is

**Comment by HelloZeroNet** [comment]
This is the normal behavior: for debugging it raises an error, which spawns a web console if you have [werkzeug](https://werkzeug.palletsprojects.com/en/0.15.x/debug/#) package installed and you are in debug mode.
