### ISSUE TITLE
The strange "MasterSeed". Bitcoin address generation pattern in ZeroNet.

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2302]
Hi!

I created quiet a few sites and I see a pattern which makes me worry. 
The first sites Bitcoin address begins with **11** than the next generated addresses begin with: _12_, _13_, _14_, _15_, _16_, _17_, _18_, _19_ than _1A_, _1B_, _1C_ and continues with this pattern to infinity. 

Is this normal? If so, than why? I think there is a chance of Bitcoin address collision! 
I also got a few Bitcoin address which is not 34, but _33 character long_.

**Comment by ghost** [comment]
@imachug @HelloZeroNet

**Comment by ghost** [comment]
There is possibility while `siteCreate` to generate a Bitcoin address without the master_seed?

**Comment by ghost** [comment]
action.add_argument('--use_master_seed', help="Allow created site's private key to be recovered using the master seed in users.json (default: True)", type="bool", choices=[True, False], default=True)

action.add_argument('--use_master_seed', help="Allow created site's private key to be recovered using the master seed in users.json (default: True)", type="bool", choices=[True, False], default=**False**)

Never mind, solved without your help. Great community! :rofl:

**Comment by masterseed** [comment]
I change the value from `True` to `False` in the code above, guess what happened? 

? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y
- Please, secure it now, you going to need it to modify your site!
? Have you secured your private key? (yes, no) > y

**Comment by ghost** [comment]
The pattern of the Bitcoin addresses generated with `master_seed` looks suspicious. If every user has only one site than each user will have a Bitcoin address begin with **11**. This is something you should investigate.

**Comment by ghost** [comment]
These Bitcoin addresses generated by the `master_seed`: 

**11**2T3UW8p2nqfBa73wy6Fc9FmWrHvDNcy9
**12**3T7dC8hC7iC6amDkjwo9re8LWuxpk9AR
**13**3xyzA4Mp2nznyubTQ6bx2fcDmrYG8ZLv
**14**5fa7qJyaVHRgYK7KHkwrGMgo1fbVoa7a
**16**M4bzNK3Wyx7trSus2e3rP9VxMBXq1cuV
**17**3sejW8afQR7hoREHcSXX5aCDUTBycedH
**18**6krwuWqPZgGa754LfXETMCaC63XeZ1KX
**19**GS6hk1QTdrc6qDbte2Bvj924ATw3XyT
**1A**jT1d5X8LKGgQCMWd5znVeei98kR1Y7u8
**1B**rhMA7GdxwAbJzBFg4JkVayrHYEBCNiJG
**1C**thntVHwXDgnwex7NZtqf7vfkhwC4dkPE
**1D**DBQMznkWPbXWR7aE384fz1Ceb55WntS
**1E**e4r2RUzqJhyesYpKxgq8odq9GTT1HNCk
**1Ei**tqPviM5ootkHhgeP1z6EZ5waXFXiYC
**1Ei**W67hRAZVAwssyv95hjBgEe5eTgYtFZy
**1F**LaF1e4iXrRHZHboCuYykbN3PhZoDgtQH
**1f**yC5q7dg9L5dkL3jrJptPDNqitHeNQgG
**1G**LcGANyHQKTitLR1sXH3xqTBjFEgQrfBx
**1HQ**AHPrajQ8zJ6Lex1WaWST91BGD2Ebqdh
**1HQ**k9sJyTxzr34Stsqs53BDMM9xpq88mBe
**1J1**cMmHjGjy6BYHekk4pJftHzGFsYUCz9C
**1J2**e1tDmEy9SJH619E8H9Vy7Y1xDG5SSqo
**1J**AvRWSYBMhMdinSm3kWEmNxLhYx8sHovp

**Comment by HelloZeroNet** [comment]
Not for me, I just generated 3 site adress with master_seed on:
 - 1Mzzf9DNaU3zyzjy9yMj39cJSy7Rz9wg4u (site index: 11054063)
 - 1FpXtq8ScR27G4EDJAj82agJdWYDVVwsXe (site index: 54521713)
 - 13ciYDST44j3PELKxVPbujNAcD2um3AiDc (site index: 92140404)

**Comment by purplesyringa** [comment]
To add to what nofish said: now what? It would matter if private keys were generated unrandomly but these are just addresses.

**Comment by ghost** [comment]
@HelloZeroNet keep on generating the addresses. 
@imachug if you publish more than 100 site on ZeroNet than an observer can tell that you used `master_seed` to generate the addresses. This by itself is a problem. 

Most addresses generated using `master_seed` have 2 **or more** common characters and following the 1+_123456789ABCDEFGHJKLMNPQ_ pattern over and over. After a time there is no address left which begins with the **12** characters and the loop continues as **121** 122, 123, 12A, 12B etc.

**Comment by HelloZeroNet** [comment]
This is normal, some characters/prefixes are more common, others less:


vanity | difficulty
-- | --
1AAAAA | 259,627,881
1QLbz6 | 259,627,881
1QLbz7 | 837,596,142
1aaaaa | 15,318,045,009
111111 | 1,099,511,627,776

More info and source: https://en.bitcoin.it/wiki/Vanitygen

**Comment by purplesyringa** [comment]
> keep on generating the addresses.

Lol, of course you'll get a nice sequence if you try searching it for a long while...

> @imachug if you publish more than 100 site on ZeroNet than an observer can tell that you used master_seed to generate the addresses. This by itself is a problem.

Eh... no it's not.

> Most addresses generated using master_seed have 2 or more common characters and following the 1+123456789ABCDEFGHJKLMNPQ pattern over and over. After a time there is no address left which begins with the 12 characters and the loop continues as 121 122, 123, 12A, 12B etc.

Cool! We've just broken SHA-256 as well as elliptic curve-based cryptography! Or you're just pretending which is most likely, judging by your username and registration date.

**Comment by ghost** [comment]
I can't register to ask a question? :thinking: You also would judge by my skin color? 
I doubt you even know what is elliptic curve-based cryptography. 

Check this out: **BIP32-Ed25519** Hierarchical Deterministic Keys over a Non-linear Keyspace https://cardanolaunch.com/assets/Ed25519_BIP.pdf

**Comment by purplesyringa** [comment]
> I doubt you even know what is elliptic curve-based cryptography.

I wrote my own cryptography libs but ok, I've just learned something new about myself.

**Comment by ghost** [comment]
I see nothing in your repositories which worth to mention.
