### ISSUE TITLE
BIP32-Ed25519

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2303]
Hierarchical Deterministic Keys over a Non-linear Keyspace https://cardanolaunch.com/assets/Ed25519_BIP.pdf

**Comment by ghost** [comment]
@imachug @HelloZeroNet I needed to open a new issue because you closed the previous: https://github.com/HelloZeroNet/ZeroNet/issues/2302

**Comment by HelloZeroNet** [comment]
You don't need to open a new issue: you can comment on a closed issue.

I think current bip32 derivation works for bitcoin clients, then it should be fine for us as well.

**Comment by ghost** [comment]
Not for me, I going to rewrite ZeroNet and distribute a way more advanced version.

**Comment by purplesyringa** [comment]
Great! Just do it then.

**Comment by ghost** [comment]
I doing right now.

**Comment by ghost** [comment]
We don't need Nazi Hungarians to decide about how we protect our privacy!
