### ISSUE TITLE
Hungarian neo-Nazi Tamas Kocsis alias "ZeroNet" is a terrorist right-wing fascist!

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2304]
Tamas Kocsis is a Hungarian neo-Nazi shithead who censoring GitHub and hiding the fact that he is a **criminal copyright infringer who infringes other peoples copyrights and violates various licenses for years!**

I urge you maniac fascists shit to stop distributing ZeroNet right now or replace the license with GPLv3+[!](https://github.com/HelloZeroNet/ZeroNet/issues/2273) 
You currently illegally distributing ZeroNet!

**Comment by ghost** [comment]
@imachug @HelloZeroNet close the fucking voting and replace the license with **GPLv3+** because **ZERONET IS DISTRIBUTED ILLEGALLY**!

**Comment by HelloZeroNet** [comment]
no one cares

**Comment by gthedevel** [comment]
Zeronet will never be GLPv3+ since a considerable amount of contributors are for GPLv3 only. Deal with it and take your meds.
