### ISSUE TITLE
[IDEA] access `.onion` urls

### ISSUE THREAD

**Issue by Merith-TK** [HelloZeroNet/ZeroNet#2305]
**Describe the solution you'd like**
So since Tor is integrated with Zeronet, i was thinking that we could simply add a proxy settings (reverse proxy with the webserver software where the 'header's are set to the actual `.onion` address?)

where you can access a `.onion` address with something like 
`127.0.0.1:43110/tors/www.facebookcorewwwi.onion` for HTTPS and
`127.0.0.1:43110/tor/www.facebookcorewwwi.onion` for HTTP

yes i used facebooks onion address as an example

**Describe alternatives you've considered**
Meh its just a thought i had, can be closed if you like and think its too stupid

**Comment by purplesyringa** [comment]
Hm, tbh I have no idea how it'd work with ZeroNet. ZeroNet is decentralized while Tor onion sites are centralized, so it'd be difficult to merge them.

**Comment by Merith-TK** [comment]
I was thinking it would just be a way to access Tor Sites (via the sandboxing) easily

**Comment by purplesyringa** [comment]
Hm, I don't really see the point in using ZeroNet instead of Tor Browser in this case. Tor Browser has always provided better sandboxing than ZeroNet. This doesn't mean that ZeroNet is unsafe, but it means that ZeroNet is not truly anonymous.

**Comment by George-Soros** [comment]
Check this out @imachug @HelloZeroNet ! 
# https://www.reddit.com/r/Bitcoin/comments/dtid99/george_soros_on_bitcoin/ :rofl:

**Comment by HelloZeroNet** [comment]
it's really out of the scope of the project

**Comment by Merith-TK** [comment]
understandably, it was just a small idea i thought of while trying to make accessing tor easier

**Comment by HelloZeroNet** [comment]
Also I think most of the sites won't work as a subdirectory as they have absolute referrences in the html.
