### ISSUE TITLE
RSS functionality

### ISSUE THREAD

**Issue by sbDevGit** [HelloZeroNet/ZeroNet#231]
I 'm thinking about the idea to implement a RSS module to follow specific ZeroBlogs
If it is possible ?

**Comment by HelloZeroNet** [comment]
Unfortunetly its not possible. (there is no server-side rendering in zeronet)

**Comment by TheNain38** [comment]
It might be possible to have possibility to be warned when desired content has been updated

**Comment by HelloZeroNet** [comment]
Thinking a bit more about it RSS could be possible by also generating the static XML file at new post, but i'm not sure if RSS is widely used anymore.

**Comment by TheNain38** [comment]
I'm using RSS feeds for some things

**Comment by bashrc** [comment]
Yes, if there are blogs out there then it would be useful to know when new posts appear.

**Comment by brabalan** [comment]
I use RSS extensively. I don’t know what the alternative is, besides constantly reloading sites.

If the RSS was generated along with / from the html file, I think it would work. One would simply point the aggregator to the generated, static file.

**Comment by HelloZeroNet** [comment]
Probably Twitter/Facebook killing it: http://www.google.hu/trends/explore#q=RSS
But I agree, it would be useful addition for ZeroBlog.

**Comment by TheNain38** [comment]
You could add a new command to have a RSS feed be generated based on some html elements you give in arguments?

**Comment by HelloZeroNet** [comment]
No need new command, you can currently write files using the ZeroFrame API

So instead only adding the new blog post to data/posts.json you also add it to rss.xml file
