### ISSUE TITLE
dark, system and light translation has not been updated

### ISSUE THREAD

**Issue by eduardoaddad** [HelloZeroNet/ZeroNet#2314]
Only translation for Theme: has been added

"Dark": "Escuro",
"System": "Sistema",
  "Light": "Claro",

**Translation missing:**

"CONNECTED SITES":  "Sites conectados",
"All": "Tudo",
"Post": "Postagem",
"from 1 sites em 0.01s": "De 1 em 0.01s",
"Filter: File name":  "Filtrar: Nome do arquivo", 
"Runtime files":  "Arquivos de tempo de execução", 

![Captura de Tela (10)](https://user-images.githubusercontent.com/16819380/68969137-06a95800-07c3-11ea-936d-cf4f2b7a0943.png)
![Captura de Tela (11)](https://user-images.githubusercontent.com/16819380/68969140-06a95800-07c3-11ea-90f1-0277548ce58f.png)

**Comment by HelloZeroNet** [comment]
Thanks, I have added updated the file. The `Post` and `Runtime files` part is not possible to translate as it comes dynamically from data files.
https://github.com/HelloZeroNet/ZeroHello/commit/13f4839d607c8f959b86bb0adde0f86952630772
