### ISSUE TITLE
Where is the user.json file of the mac version zeronet?

### ISSUE THREAD

**Issue by omaidb** [HelloZeroNet/ZeroNet#2316]
### Step 1: Please describe your environment

  * ZeroNet version: _0.71____
  * Operating system: ___macos__
  * Web browser: _____chrome
  * Tor status: not available/always/disabled  disabled
  * Opened port: yes/no no
  * Special configuration: ___no_
Where is the user.json file of the mac version zeronet?

**Comment by HelloZeroNet** [comment]
It's located at `~/Library/Application Support/ZeroNet/data` or in data directory next to ZeroNet.app (if it's running from user-writeable directory)

You should also able to see it using ZeroHello 3dot menu > Show data directory

**Comment by purplesyringa** [comment]
It is `/Users/yourusername/Library/Application Support/ZeroNet/data/users.json` (not user.json).

*I will refresh before commenting next time*

**Comment by omaidb** [comment]
Think
