### ISSUE TITLE
Signing sites created without master_seed, manually building users.json 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2318]
I generated sites without using `master_seed` which resulted in an empty `users.json` and so now I need to sign manually each and every site I updated.  

It is possible to include the private keys in the `users.json` and sign the content without manual copy-paste?

Example: 
```
  "sites": {
   "1SXdA93APFMLZJ4qgDCB6K3GEhNmZUepN7": {
    "privatekey": "5KrbW8hQVccTY7TNaMfmSVSJyDCk5QGe5k3K7YiL4BUhg5nCfaV"
   }
  }
```

Is this will allow me to sign the sites I created without the `master_seed`?

**Comment by ghost** [comment]
Ping: @imachug @filips123

**Comment by HelloZeroNet** [comment]
Yes, you can also use the sidebar "Add saved privatekey" feature

**Comment by ghost** [comment]
~~I don't have that "sidebar" because I use `py3` on GNU/Linux.**~~ So now I start building the `users.json` manually with the private keys. Thank you @HelloZeroNet 

** Got it where.
