### ISSUE TITLE
Can't download a large file

### ISSUE THREAD

**Issue by gjedeer** [HelloZeroNet/ZeroNet#2319]
### Step 1: Please describe your environment

  * ZeroNet version: Your version: 0.7.1 (rev4287)
  * Operating system: Ubuntu 16.04
  * Web browser: Firefox
  * Tor status: not available
  * Opened port: no
  * Special configuration: ____

#### Steps to reproduce:

  1. Visit http://127.0.0.1:43110/1HegcCNqxTuhPaHmjZwPGZ9LY34vXD6H1V/data/files/e5372/E5372_Update_21.290.23.00.00_webui_17.100.19.01.00_mod1.5.7z

#### Observed Results:

* Never downloads
* When the download link is clicked from the website [1], the website briefly displays "connection to ui websocket lost"
* The file is present when I download the whole site using context menu in ZeroHello and then do Save as .zip

1 - http://127.0.0.1:43110/1HegcCNqxTuhPaHmjZwPGZ9LY34vXD6H1V/?Post:5

#### Expected Results:

  * The file should have been downloaded
  * The file is 5MB so it fits in the 20MB limit.

**Comment by purplesyringa** [comment]
Can you attach the logs please?

**Comment by HelloZeroNet** [comment]
For me it looks like there is no seeder for the file currently. Other file (E5770s_UPDATE_21.329.01.00.00_mod2.3_WEBUI_17.100.19.01.00_MRE5_mod2.3.7z) has been downloaded successfully for me.


The "connection to ui websocket lost" message happens because firefox closes websocket connections when you try to navigate away from the page even if the request not responded yet.

**Comment by gjedeer** [comment]
I thought so too, but file is present when I download the whole site using context menu in ZeroHello and then do Save as .zip.

http://127.0.0.1:43110/ZeroNet-Internal/Zip?address=1HegcCNqxTuhPaHmjZwPGZ9LY34vXD6H1V

```
➜  mozilla_gdr0 unzip -l Huawei%20internals-backup-2019-11-19_13_21.zip | grep E5372_Update_21.290.23.00.00_webui_17.100.19.01.00_mod1.5.7z
  5242880  2019-11-16 18:52   data/files/e5372/E5372_Update_21.290.23.00.00_webui_17.100.19.01.00_mod1.5.7z
```

Logs: in a moment I'll try again and post logs.

**Comment by HelloZeroNet** [comment]
The file in the zip is just a sparse file filled with zeros.

**Comment by gjedeer** [comment]
Okay, closing the issue then (though maybe the error message on timeout could explain that there's no peers). Thank you for your support.
