### ISSUE TITLE
Merger sites

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#232]
The Merger sites feature allow to to query and display other site's data. Using this its possible to create infinitely scalable social sites by having separate sites for every user profile, so you will get updates for profiles that you follow.

ZeroMe: A twitter-like social site
 - [x] Layout mockups:
  - [x] Welcome page
  - [x] Profile profile
  - [x] User search
  - [x] News feed
 - [x] Static html version
  - [x] Welcome page
  - [x] Profile profile
  - [x] User search
  - [x] News feed
 - [x] Logo
 - [X] Merger site permission handling/request
 - [X] New database structure to allow easier and faster joins
 - [X] Merge sub-site data files to merger site's database
 - [X] Sub-site adding/delete/list
 - [x] Make Sign/File oprations merger site compatible: actionSiteSign, actionSitePublish, actionFileWrite, actionFileDelete, actionFileGet, actionFileRules
 - [x] Profile page data structure
 - [x] Merger site rebuild DB
 - [x] Profile page db structure
 - [x] User directory data structure
 - [x] User directory db structure
 - [x] Update database on new merger/merged site add/remove
 - [x] User directory
 - [x] Sub-site feed listing
 - [x] Profile creation
 - [x] Profile page
 - [x] Profile editing
 - [x] Posting
 - [x] Post editing
 - [x] Post deleting
 - [x] Activity list
 - [x] Like
 - [x] Commenting
 - [x] Comment editing
 - [x] Comment deleting
 - [x] Follow profile
 - [x] List followed users
 - [x] Auto download new site on follow
 - [x] Following without registered profile
 - [x] Also update user database on profile modification
 - [x] User content delete solution for efficient user directory archiving
 - [x] Avatar upload

Later:
 - [ ] Re-share
 - [ ] File upload
 - [ ] Image upload with thumbnail generation (optional files)

ZeroHello:
 - [ ] Group sites by type

**Comment by alxbob** [comment]
Why this is closed? Its not going to be implemented?

**Comment by HelloZeroNet** [comment]
Merger sites #232: Open

**Comment by gigq** [comment]
With this feature does it mean your local zeronet node won't have to download these sub sites until the user requests them? I'm trying to think through the scalability implications of hosting a large site on zeronet and this is one of my concerns. Also useful for splitting a site up so the sqllite files for each site can stay small.

Is this only limited to user sites? I can think of some cases where it would be useful to use this feature even if they were coming from the same publisher. For example a reddit clone where you only want to follow and download a few subreddits not the entire reddit site.

Would these sub sites have the same features as existing zeronet sites? Could you nest them however many levels deep that you want?

**Comment by HelloZeroNet** [comment]
Yeah, it's also add possibility to have a merged reddit-like site. It's won't be limited to user sites, so it could also help single-user sites.

Currently only planning one level nesting.

**Comment by alxbob** [comment]
Query and display would be from the main site (zerome)? For eg searching and opening a user profile inside central /zerome.bit ?

**Comment by alxbob** [comment]
Any time estimation?

**Comment by HelloZeroNet** [comment]
I haven't started it yet...In the next few months

**Comment by alxbob** [comment]
Thanks keep up :)

**Comment by HelloZeroNet** [comment]
After thinking about it for a while, i'm not sure if one site per user is a good solution

### One user per site

Every user has his/her own site, if you want to follow someone you start seeding the site. If you want to stop following simply remove site from seeding.

Pros:
 - No one can modify your profile, but you
 - ZeroID independent (comments still requires zeroid)
 - Probably easier to implement

Cons:
 - Initial seeding can be problematic
 - Needs lots of connections (5connection/site is minimum to make sure you got every update)
 - More network communication (tracker announce requests)
 - More files and hdd space requirement on hdd (if you comment on multiple profile you only need new file for every profile)
 - Less privacy: You exactly know who follows who (tor improves this)

### More user per site

Instead of one site per user create "hub" sites that hosts a few 100 users. (10MB limit enforces decentralization)

Pros:
 - Initial seeding is no problem, because you joining to an already seeded hub
 - Does not need many connection
 - Other ppl only know what hubs you are following, but not the exact users

Cons:
 - There is a hub owner, who has ability to modify/remove users
 - ZeroID required to join a hub
 - You get the changes for every profile on the hub

But if you don't want to trust the hub owner, then you can create your own hub and this also eliminates the other "Cons".

So I think the user hub solution is better in every aspects.

**Comment by alxbob** [comment]
I think One user per site is more scalable and and gives the ability to users to do everything they want (selective seeding). Network communication is needed and thats the point of p2p protocols. More user per site has privacy issues to on who is the hub owner (plus need of zeroid thats for now centralized) and making closed communities of hubs not open ones. I don't want my hub for a social network but a hub everybody could be a member!

**Comment by HelloZeroNet** [comment]
One use per site is less scalable, because you need 5+ connection per site, so if you follow 200 users it means minimum 1000 concurrent connections which is not really sustainable. If the hub owner delete/censorship your posts you are free to switch to an another one, so its not really an issue.

Central messaging / automatically seeding every site without any control is against zeronet philosophy and does not really works with many users.

**Comment by alxbob** [comment]
And the hubs whould not have any communication between them?

**Comment by HelloZeroNet** [comment]
You can use your zeroid to communicate on any hub (there is no difference on this between one site per user and multiuser hubs)

**Comment by alxbob** [comment]
I think one difference is seeding a profile you don't want in the hub...And the only option is to switch hub...and loose all your follower/following posts..

**Comment by HelloZeroNet** [comment]
You will only see users in your newsfeed that you are really following (like you can follow only some of the topics on zerotalk), but you will keep receiving/seeding updates for this profiles

**Comment by alxbob** [comment]
I think a big problem in zeronet is searching and index...so information is lost..maybe searching inside a hub could be available? And muting will implemented as merger functionality?

**Comment by HelloZeroNet** [comment]
You can easily index zeronet content, since everything is stored on your computer in json files. There is already a search engine with indexed content: http://zeroexpose.com/

The muting feature is independent from merger sites

**Comment by alxbob** [comment]
The fact that everything is stored on your local files it doesn;t make it easy to locate a user based on his username or content this particular user wrote (site/users/data/1......./data.json). And how i would connect to other users in my hub or hub if i cant find them. Or i cant locate a subject someone wrote? Why should i really on external search engines? Or i should post in 3 different sites my profile link blog so someone could find me. I think search should me embedded in every site to make it easier zerotalk/zeroblog/zeromail/zerome for everyone to access and to avoid duplication. I think muting should be available for merger sites to so a user can press a block button and delete/stop seeding someone profile content.

**Comment by HelloZeroNet** [comment]
If you want to search in content that you don't have, then you need external services. Searching can be implemented to zerotalk/blog/etc. it's only matter of javascript code and it's not related to merger sites in any way. The muting feature is also unrelated to merger sites, if you start seeding a hub it does not mean you will start following every user automatically.

**Comment by HelloZeroNet** [comment]
Created an idea to be able to search in every site you serving: https://github.com/HelloZeroNet/ZeroNet/issues/419

**Comment by alxbob** [comment]
So what did you choose? Hub sites? If so i hope we don't end up with one user per hub

**Comment by HelloZeroNet** [comment]
I have not started implementing it yet, but I think the hub sites is the only possible, scalable implementation and its also better for privacy

**Comment by alxbob** [comment]
At least would be a connection between hubs? For querying data? Can multiple hubs be part of a site type? Something like hub of hubs? Else this doesn't solve much and i am still afraid we end up with one hub per user so it will be the same like one site per user

**Comment by HelloZeroNet** [comment]
Every hub site will be totally independent (there will be no difference between hub sites and any other current site), but it's not a problem, because the merger sites will solve this problem.

If you willing to host your content 0-24 then you can create your own hub, but inactive/not seeded profile sites will be  removed.

**Comment by PeterCxy** [comment]
I do not think seperating sites a good idea. Why should we have a merger site when we can just create more independent smaller sites? Does it mean some kind of "centralization" when we are depending on merger sites?

**Comment by HelloZeroNet** [comment]
Yes, it's more centralized, but there is no other way if you want to list/interact content in one place

**Comment by idlesong** [comment]
I think one user per site is more more attractive.  If there's any chance, please treat this as a prime consideration.

Why I think zeronet social is very attractive? 

1.  I have the total control of my date. That's why I choose p2p social instead of centralized site.
1.  My data will always online. Because my friends(followers) have big willing to seeding my site.

The more user per site solution is less attractive.

1. I lost my total control. It's hard to choose a hub, because we have very small information of the hub.  
I need to choose a hub. I will worry about that he may banned my site, if he don't like my content. If I changed my hub, I may need to inform my followers that I changed my hub and ask them to seed again. Because the hub can modify my data, then it can fake me: Banned my profile and say I have changed to a fake profile. Because my followers have seeding the hub for a while, they may trust the hub. Because we have few information to choose a hub, maybe in the future, who have many servers and bandwidth will gain most users. 
2. My followers need to seed other 99 users they don't want to follow. This may decrease their willing to seed the sites.

Please forgive my poor English:)

**Comment by HelloZeroNet** [comment]
Like is said before: if you want you will be able to create your own hub, so don't have to rely on anyone

**Comment by idlesong** [comment]
Yes I know, create my own hub is a solution. But if there are many users like me care about the control of own data. Then this solution would be less attractive.

**Comment by idlesong** [comment]
For the issues of one user per site solution
- (a)Initial seeding can be problematic
- (b)Needs lots of connections (5connection/site is minimum to make sure you got every update)
- (c)More network communication (tracker announce requests)
- (d)More files and hdd space requirement on hdd (if you comment on multiple profile you only need new file for every profile)
- (e)Less privacy: You exactly know who follows who (tor improves this)
-----------------------------
Consider most zeronet users don't treat 1.easy to use and 2.decrease hdd space as top priority, so (a),(c) are not big problem right now.
And with tor, (e) also can accept.
So the really problem are (b) and (c). Am I right?

**Comment by HelloZeroNet** [comment]
If you create your own hub it's exactly the same as one user per site solution

**Comment by idlesong** [comment]
I will take more time to think about this. Thanks for your hard work, it is really awesome.

**Comment by HelloZeroNet** [comment]
any suggestions for the social site name?

**Comment by cyrixhero** [comment]
MeetZero is good!

**Comment by makdisse** [comment]
I vote for ZeroSociety or ZeroMe

**Comment by Snarkly** [comment]
You might consider not using zero in the name here are some more ideas for a name. 
Chatter
Blabber
ChitChat
Babble

**Comment by OliverCole** [comment]
@makdisse ZeroSociety was my first thought too - http://mrrobot.wikia.com/wiki/Fsociety :)

**Comment by alxbob** [comment]
Zerotopia

**Comment by idlesong** [comment]
Zerome or myzero

**Comment by alxbob** [comment]
Users from different hubs will have the ability to share content?

**Comment by HelloZeroNet** [comment]
Every zeronet site is totally independent. Hub = ZeroNet site

**Comment by alxbob** [comment]
So no

**Comment by antiphase0** [comment]
GroundZero should be avoided because it has negative cultural connotations in the U.S. (the site of the wreckage of the World Trade Center buildings on 9/11 is still referred to as "ground zero") and, of course, Japan (Nagasaki and Hiroshima were ground zero for nuclear bombs).

I agree with @makdisse, ZeroMe and MeetZero are the most appealing choices from the list.

I also have a less serious name suggestion taken from the Star Trek universe: "[Unimatrix Zero](https://en.wikipedia.org/wiki/Unimatrix_Zero)," which is the name of a censorship-free decentralized social network of rogue Borg. Perhaps it's silly, but I had to mention it given the obvious parallels.

**Comment by homersimpsons** [comment]
I'm sorry but I don't have read all he discussion, but instead of one/more user per site I have an idea:
create bundle sites to hold content, it's base on one user per site, but, for exampe with some people you get 30+ common friend, then all this could be bundle with this group of friends. this will limit the number of connection needed and keep enough data data online.

**Comment by alxbob** [comment]
Some short of pm's could be trivially added?

**Comment by iShift** [comment]
ZSociety

**Comment by Split7fire** [comment]
ZeroMe :+1:

**Comment by 62gs8ha** [comment]
Would it be possible to create a normal website which isolates large media files or sections of the website so that a viewer onlky downloads them when they try to view it?

Or is the Merger Sites feature only restricted to the social site being planned?

**Comment by HelloZeroNet** [comment]
@62gs8ha: Merger site (and zeronet) is mainly for data-based sites, but you can define optional files that only downloaded when the user's browser requests it. 
Example: https://github.com/HelloZeroNet/ReactionGIFs/blob/master/content.json#L1796 
site: http://127.0.0.1:43110/1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h (currently has 560 MB of video, but they only downloaded if your client's browser requests it)

**Comment by 62gs8ha** [comment]
@HelloZeroNet Thanks. Can you explain the syntax of that Optional Files argument? So say if I wanted to make MP3 embedded audio or embedded PDfs optional, how would I do it? What are the js and css arguments in that syntax string?

**Comment by HelloZeroNet** [comment]
the syntax is a standard called regexp (http://www.petefreitag.com/cheatsheets/regex/)
 - `"optional": ".*\.(jpg|png|gif)"` will make all png, jpg, gif file optional on your file (not recommended if you have other, smaller images in your site, eg your logo)
 - `"optional": "(data/videos/.*|data/documents/.*)"` will make all files inside data/videos and data/documents directory optional

**Comment by Split7fire** [comment]
@HelloZeroNet, so when the release date? :)

**Comment by HelloZeroNet** [comment]
@Split7fire If I can't find any more bug then tomorrow.

**Comment by HelloZeroNet** [comment]
I think i was able to fix all the bugs, tomorrow morning i going to re-check everything, then publish it

**Comment by haschimoto** [comment]
Zerotopia would have been awesome.

**Comment by HelloZeroNet** [comment]
If you already upgraded to 0.4.0, then you can help testing ZeroMe: its visible at ZeroHello's "More sites" section.

**Comment by wigy-opensource-developer** [comment]
Great news! Is there a zite address you could share with us?
