### ISSUE TITLE
/Benchmark site error invalid regular expression flag

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2320]
### Step 1: Please describe your environment

  * ZeroNet version: 4287
  * Operating system: w10
  * Web browser: Firefox BETA
  * Tor status: available

### Step 2: Describe the problem:

In my case, http://127.0.0.1:43110/Benchmark shows following error in developer console:
SyntaxError: invalid regular expression flag sBenchmark:42:50
when i click Start benchmark button, then i see:
ReferenceError: stream is not definedBenchmark:117:5
and nothing happens on site

**Comment by HelloZeroNet** [comment]
Thanks for reporting fixed in Rev4290 https://github.com/HelloZeroNet/ZeroNet/commit/6262c808863df1adbbeb22431ce5b22f1c2a4e41
