### ISSUE TITLE
how to use ZeroNet in iran ?

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2322]
As you have heard, Iran has cut the internet. And most people don't have internet access.

So we need a service like ZeroNet without any public endpoint or trackers
My first test to launch ZeroNet inside Iran failed because ZeroNet needed the Internet

Is this possible? How?

**Comment by purplesyringa** [comment]
I'm afraid it's impossible. AFAIK (I might be wrong though) Iran cuts all outgoing/incoming connections which means that there is no way to connect any computers to build a network.

**Comment by filips123** [comment]
But does it cut only connections to outside countries or also internal communication?

If there is still some internal communication available, it might be possible to use ZeroNet with local tracker list.

**Comment by SwissConfederation** [comment]
@ahmadly You can use ZeroNet in Iran! What OS you are using? Don't listen to @filips123 and @imachug they are fascists. I have tested ZeroNet on VPS in Tehran and works perfectly.

**Comment by SwissConfederation** [comment]
@ahmadly First of all. Without Internet ZeroNet will not work. Second, @imachug and @filips123 don't know anything about Iran. You can run ZeroNet in Iran! You can use it with Tor and if you are paranoid you can also use **Tor + obsf4 bridges**!

**Comment by filips123** [comment]
They didn't just block ZeroNet. They completely cut off the internet, without any communication. In this case, you couldn't use ZeroNet or any other internet service.

But I think they now restored internet so it should work again.

**Comment by SwissConfederation** [comment]
When western propaganda media says Iran have no Internet they referring to inaccessible Facebook, Twitter, WikiPedia and to be honest all of these services are serving the worlds biggest terrorist government, the United States of America. You are an Islamophobic person.

**Comment by filips123** [comment]
> When western propaganda media says Iran have no Internet they referring

Was internet completely disabled or was just communication to other countries blocked? Do you have any proof of this?

In the first case, you can't use ZeroNet, but in the second case, you can use it with local trackers.

> You are an Islamophobic person

Yes? No...

**Comment by SwissConfederation** [comment]
The point is @ahmadly can use ZeroNet even when Twitter and other terrorist backed services are offline. Be honest, I fully support both the "firewall of China" and Iran when they blocking Twitter, Facebook, WikiPedia or other US based services which used by the US government to spread propaganda.

**Comment by filips123** [comment]
> I fully support both the "firewall of China" and Iran when they blocking

I don't. Although many of that sites are used to spread propaganda (by US, Iran, China..., it actually doesn't matter), there are better ways to fight against this, not with blocking them.

**Comment by SwissConfederation** [comment]
You are a western maniac. I get it. I also live in the west and yet I fully against any of the services I mentioned above. I even have 12.000 followers on Twitter. You think I give a damn? These services based in the United States and not China, not Russia who spies on the entire world! It is the United States of America and also the United States of America supports more than 70% of the worlds dictators not to mention have more than 1000 military bases in 120 countries! China and Russia or Iran have all right to defend themselves!
