### ISSUE TITLE
How to sign multiple zites at once? 

### ISSUE THREAD

**Issue by howtozeronet** [HelloZeroNet/ZeroNet#2325]
Hi,

I created multiple zites without using the master_seed option and now my users.json is empty. I need to manually add the private key to each zites I modified which takes a very long time. 

My questions are: 

How to build manually the users.json with the private keys?
It is possible to sign multiple zites at once? 

If I create a file like signing.sh and including the following lines will work? 

python3 zeronet.py siteSign data/xxxxxxxxxx1 &&
python3 zeronet.py siteSign data/xxxxxxxxxx2 &&
python3 zeronet.py siteSign data/xxxxxxxxxx3 &&
python3 zeronet.py siteSign data/xxxxxxxxxx4 &&
python3 zeronet.py siteSign data/xxxxxxxxxx5 &&
python3 zeronet.py siteSign data/xxxxxxxxxx6 &&
python3 zeronet.py siteSign data/xxxxxxxxxx7

or I can use _python3 zeronet.py siteSign data/._ to sign all the zites in the data folder?

**Comment by HelloZeroNet** [comment]
You can't sign multiple site at once, you have to execute separate siteSign for every site.

**Comment by howtozeronet** [comment]
So this will work? This are separate commands. 

python3 zeronet.py siteSign data/xxxxxxxxxx1 &&
python3 zeronet.py siteSign data/xxxxxxxxxx2 &&
python3 zeronet.py siteSign data/xxxxxxxxxx3 &&
python3 zeronet.py siteSign data/xxxxxxxxxx4 &&
python3 zeronet.py siteSign data/xxxxxxxxxx5 &&
python3 zeronet.py siteSign data/xxxxxxxxxx6 &&
python3 zeronet.py siteSign data/xxxxxxxxxx7

**Comment by HelloZeroNet** [comment]
You need to use the site address as argument not the directory

**Comment by howtozeronet** [comment]
thank you!
