### ISSUE TITLE
0.7.1Unable to start the program after unzipping

### ISSUE THREAD

**Issue by dhueys** [HelloZeroNet/ZeroNet#2327]
What exactly happened?

**Comment by HelloZeroNet** [comment]
Please provide more information (use the issue template)

**Comment by dhueys** [comment]
### Step 1: Please describe your environment

  * ZeroNet version:0.6.5(rev3870)
  * Operating system: win10 1909
  * Web browser:Firefox
  * Tor status: always
  * Opened port:closure
  * Special configuration: /

### Step 2: Describe the problem:

#### Steps to reproduce:

  1. Download and unzip 0.7.1
  2. Copy the code from 0.7.1 to the ZeroNet-win-dist code

#### Observed Results:

  Double click on ZereNet, no response (Nodes cannot be updated until 0.7.1 is not updated)
