### ISSUE TITLE
Error message when posting a message on zeronet Content signing failed Contains too large 51829B> 50000B

### ISSUE THREAD

**Issue by omaidb** [HelloZeroNet/ZeroNet#2329]
### Step 1: Please describe your environment

  * ZeroNet version: _0.71____
  * Operating system:  debian10_____
  * Web browser: __frifox___
  * Tor status: always
  * Opened port: yes/no
  * Special configuration: __no__

### Step 2: Describe the problem:
在zerome发布消息时，会弹出一个错误
Error message when posting a message on zeronet
Content signing failed
Contains too large 51829B> 50000B
![image](https://user-images.githubusercontent.com/18365223/69623350-adbca800-107d-11ea-94d1-cc35b89e3a64.png)

**Comment by purplesyringa** [comment]
This means that the site you're posting the content on does not allow you to use so much space. You should either delete your old messages or ask the site owner to increase your space limit.

**Comment by omaidb** [comment]
@justinwiley @imachug  The site in question is here. I have deleted this site from the menu on the left of zerohello, but the error persists.
http://10.2.2.1:43110/17cNRuQ37T4u8uCeeNoxtVDyv9X57MBPbp/

**Comment by omaidb** [comment]
Solved the problem, here the parameter is filled in 1024, after the value is smaller, sending the article is normal
![image](https://user-images.githubusercontent.com/18365223/69657729-d06ab300-10b5-11ea-9156-311b5d1e90c4.png)

**Comment by purplesyringa** [comment]
Oh, were you the owner of the site?

**Comment by omaidb** [comment]
> 哦，您是网站的所有者吗？
I ’m not the site owner, and he has a new error。I don't know where to remove this wrong site, I didn't find it
![image](https://user-images.githubusercontent.com/18365223/69829355-94bd1e00-125a-11ea-969d-5cdd204fcbaf.png)
![image](https://user-images.githubusercontent.com/18365223/69829386-b28a8300-125a-11ea-8206-186886f4446b.png)

**Comment by ghost** [comment]
62331B is more than 50000B

How you managed to have a max file size limit less than **486.96 Kb**? 
If it's not your site than why you care? :rofl:

**Comment by purplesyringa** [comment]
> If it's not your site than why you care?

Probably because it's his data. It looks like you're running out of space on ZeroMe. I'll take a look at your account rn.

**Comment by omaidb** [comment]
I ignored the error and after a few days the error suddenly disappeared。I want to know what is going on with this mistake ..., which hero can explain how it works

**Comment by omaidb** [comment]
我决定结束这个问题
