### ISSUE TITLE
New ZeroHello with News feed

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#233]
Allow to sign up to database queries, so you can have one, unified list of latest blog posts/comments/replies.

Todo:
 - [x] Static version of new ZeroHello
 - [x] Implement new commands
 - [x] Modify ZeroBlog to allow signup to New posts/Username mentions/Comments
 - [x] Modify ZeroTalk to allow signup to New topic/Username mentions/Comments
 - [x] Site listing on new ZeroHello
 - [x] Display site errors and notifications
 - [x] Site commands on new ZeroHello: Pause, Delete, Clone
 - [x] Display newsfeed on new ZeroHello
 - [x] Merge similar newsfeeds
 - [x] Real-time updated feed
 - [x] Welcome message
 - [x] Tor/Port open status to new ZeroHello
 - [x] Settings: Always Tor mode, Update all sites, Update to latest ZeroNet version
 - [x] New logo favicon/systray
 - [x] Test in Firefox/IE/Safari
 - [x] Multi user login/logout
 - [x] UiPassword logout
 - [x] Disable some admin function when using Multiuser plugin

New commands:
 - [x] feedFollow feeds -> Set queries that user follows {Name: Query, ...}
 - [x] dbQueryFeed -> List last results from signed up queries (admin permission required)

~~UI modifications idea 1:~~
 - ~~Add new tab to sidebar~~
 - ~~Add per site notification count to ZeroHello~~

UI modifications idea 2:
 - Create a new ZeroHello with newsfeed-like activity listing

Query specification:
 - event_uri: unique id of the event
 - type: article, topic, comment, message, image, news, mention, album, warning, error, info
 - date_added
 - title
 - body
 - url

Query examples:
Last posts in ZeroBlog:
 ```sql
SELECT 
 post_id AS event_uri
 "article" AS type,
 date_published AS date_added,
 title AS title,
 body AS body,
 "/Post:" || post_id AS url
FROM post ORDER BY date_published DESC
 ```

New topic in ZeroTalk:
```sql
SELECT 
 topic_id || "_" || topic_creator_json.directory AS event_uri,
 'topic' AS type,
 added AS date_added,
 "New topic: " || title AS title,
 body AS body,
 "/Topic:" || topic_id || "_" || topic_creator_json.directory AS url
FROM `topic`
LEFT JOIN json AS topic_creator_json ON (topic_creator_json.json_id = topic.json_id)
ORDER BY added DESC
```

Last posts in ZeroTalk mentioned username:
```sql
SELECT 
 topic_uri AS event_uri,
 'mention' AS type,
 added AS date_added,
 body AS body
FROM comment 
WHERE body LIKE '%@nofish%' OR body LIKE '%[nofish]%' 
ORDER BY added DESC
```

In the current form ZeroMail messages unfortunately won't be possible to put in the News feed

**Comment by HelloZeroNet** [comment]
Currently I preferring the second UI solution: So a new ZeroHello with News feed

**Comment by TheNain38** [comment]
And for ZeroMail, normally it is possible to know when you receive an email?

**Comment by HelloZeroNet** [comment]
No, unfortunetly ZeroMail integration won't be possible in current form.

**Comment by TheNain38** [comment]
Ah, I see why, but if I remember, the metadata aren't encrypted, and it's possible to know if you receive an email, but not decrypt content

**Comment by HelloZeroNet** [comment]
The metadata is also encrypted, so without decrypting it its not possible to know if you or someone else received a message.

**Comment by TheNain38** [comment]
Ah, I was wrong then... Sorry

**Comment by TheNain38** [comment]
You could add an API to have a "(1)" or "(2)" etc... appearing in the title, like it is on github.
So, for example, ZeroMail could be displaying this when there is new mails, it could be like a notification.

**Comment by HelloZeroNet** [comment]
Yeah, its a good idea and title-changing ZeroFrame API command is planned.

**Comment by idlesong** [comment]
This feature seams like a kind of zerome, they seams very familiar.

**Comment by idlesong** [comment]
Is it possible to use this feed news to replace the zerome? So you do not need to maintain two apps.  There will be many kind of feeds, blog, forum.., we can use lists to filter them. Server a site is like follow a site:)

**Comment by HelloZeroNet** [comment]
what is ZeroMe? The difference from merger sites (#232) is it does not allow content creation and listing is simpler, but it's similar.

**Comment by idlesong** [comment]
OK, I understand. I just think if this news feed can replace the ZeroMe would be very cool. (ZeroMe: A twitter-like social site)

**Comment by TheNain38** [comment]
You could add a way to pin sites, like the "Some sites we created:" sites are

**Comment by HelloZeroNet** [comment]
that screen only visible until you have something on your newsfeed, but pinning site to left side could be a good idea and planned later

**Comment by TheNain38** [comment]
![capture](https://cloud.githubusercontent.com/assets/13149763/12751139/b12e749e-c9bb-11e5-8612-3b9840b1b893.PNG)
There is also this graphical bug.

**Comment by HelloZeroNet** [comment]
Fixed the menu bug.
