### ISSUE TITLE
Feature Request: Place all Identity Specific Files to a Separate Folder Named "identity"

### ISSUE THREAD

**Issue by martinvahi** [HelloZeroNet/ZeroNet#2332]
Currently the identity related files seem to reside loosely at the "data" folder, at 

    <ZeroNet instance root folder>/data

If there were

    <ZeroNet instance root folder>/data/identity

and all of the local server instance identity related files, for example private keys, were placed to that folder, then it would be possible to replace that folder with a symlink to a mounted encrypted file system folder. 

The possibility to replace that folder with a symlink would also simplify scripting. For example, one might want to write a Bash alias that swaps the target of the symlink, which allows the downloaded zite data to be re-used by multiple identities without making any modifications to the ZeroNet core code. That kind of identity switching mechanism does not (or at least should not, if everything is kept clean at the ZeroNet architecture) interfere with any of the multi-identity plugins/modules that other people might prefer to use. 

From security point of view it is not a perfect identity switching mechanism, because for the sake of saving disk space and download time, the downloaded zites are shared between multiple identities, but it is helpful in cases, when the identity switch is done mainly to confuse search engines.

Thank You.

**Comment by filips123** [comment]
Can't you already make symlink just for file?

As identity is mostly on one file (`data/users.json`) I don't see a particular reason to move it to separate folder, if the file itself can be symlinked.

**Comment by martinvahi** [comment]
@filips123 

> Can't you already make symlink just for file?

I can, but it would be a MESS, because the moment they change the number of files during the natural development of the ZeroNet, the symlink creation code has to be updated. If the files were in a folder and they decide to change the name of the folder, then there's only one change group at the symlink creation code, but if the identity related files were all symlinked individually, then there's a need to update the symlink creation code every time ANY of the identity related file name or existence changes. 

Suppose some new fancy module wants to implement its own identity management system and wants to use its own database, may be an SQLite database. In the case of the folder, none of my code would need to change, but in the case of the alternative, for those people, who do not have the fancy module installed, my code MIGHT work, but for others it will DEFINITELY NOT work as long as I have updated my code to take to account the existence of that fancy module. And then the symlink creation code author has to start tracking all of the changes, the possible modules, the name changes or creation/deletion of the ZeroNet core specific identity files. 

I prefer a solution without such a mess.

**Comment by martinvahi** [comment]
I also point out that the `data/users.json` that You mentioned does not hint at all that this is the file related to IDENTITIES. What users? Any user posting to a forum? If that is the file for the local identities, then a person should NOT have to start reading separate documentation to figure out that this is the ONLY  file that holds the information about local identities. On the other hand, if there is a folder with the name of `data/identity` or, better yet, in plural, `data/identities`, then that question gets answered WITHOUT NEEDING TO START LOOKING FOR THAT INFORMATION FROM DOCUMENTATION.

**Comment by filips123** [comment]
> I can, but it would be a MESS, because the moment they change the number of files during the natural development of the ZeroNet, the symlink creation code has to be updated.

What do you mean with this?

> I also point out that the data/users.json that You mentioned does not hint at all that this is the file related to IDENTITIES. What users?

It contains your public and private keys, IDs, auth addresses for sites...

> On the other hand, if there is a folder with the name of data/identity or, better yet, in plural, data/identities, then that question gets answered WITHOUT NEEDING TO START LOOKING FOR THAT INFORMATION FROM DOCUMENTATION.

What?

Isn't `users.json` already good way to describe that file contains users?

Having folder which contains just one file would also be a mess.

**Comment by martinvahi** [comment]
> > I can, but it would be a MESS, because the moment they change the number of files during the natural development of the ZeroNet, the symlink creation code has to be updated.
> 
> What do you mean with this?

I mean that the symlink creation code has to include the list of files that need to be symlinked, including their names.



> > I also point out that the data/users.json that You mentioned does not hint at all that this is the file related to IDENTITIES. What users?
> 
> It contains your public and private keys, IDs, auth addresses for sites...
> 
> > On the other hand, if there is a folder with the name of data/identity or, better yet, in plural, data/identities, then that question gets answered WITHOUT NEEDING TO START LOOKING FOR THAT INFORMATION FROM DOCUMENTATION.
> 
> What?
> 
> Isn't `users.json` already good way to describe that file contains users?
> 
> Having folder which contains just one file would also be a mess.

Oh well, if You say that it's just that ONE users.json, then I'll live with that until something breaks. If something breaks, then I'll re-open this feature-request. Thank You for the answers.

P.S. if the users.json data records were written in an SQLite database, then the SQLite engine would handle thread safety. Does the code that reads-writes the users.json handle the case, where 2 or more server processes try to read/write the same file? Lack of data corruption in that scenario guaranteed? The same with other "JSON-file-poor-man-s-databases", if they exist.

**Comment by filips123** [comment]
Yes, there is only one `data/users.json`. This shouldn't break unless something very big is changed, but the same could happen with folders.

Note that better user managing and signing API would be good. With this, I mean easier support to let plugins/code store and sign data in different ways, for example, in folders, memory, SQLite, browser extensions...

You might want to open a new feature request for this.

**Comment by HelloZeroNet** [comment]
> P.S. if the users.json data records were written in an SQLite database, then the SQLite engine would handle thread safety. Does the code that reads-writes the users.json handle the case, where 2 or more server processes try to read/write the same file? Lack of data corruption in that scenario guaranteed?

If you don't add anything manually, then every data in users.json is originates (and recoverable) from the `"master_seed"` in users.json. So I recommend to have separate users.json in that case: if the master_seed is the same in the two file, then it will generate the same prublic/private keys for the sites.

**Comment by martinvahi** [comment]
> Note that better user managing and signing API would be good. With this, I mean easier support to let plugins/code store and sign data in different ways, for example, in folders, memory, SQLite, browser extensions...
> 
> You might want to open a new feature request for this.

Thank You both for the answers, but as of 2019_12 I'm too stupid for that. I even failed to get the newest and greatest ZeroNet, as cloned from this repository, to run, so I experimented with various older versions in the trunk and wrote a 3 Bash scripts based wrapper to one of the versions from 2018

https://technology.softf1.com/software_by_third_parties/ZeroNet/

I even got it to run, with one hick-up/hangup_event, on Win10 Linux layer, the [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/faq), Debian distribution. I did not expect to talk about the Win10 usage in English, whcih is why I used Estonian at the screen video, where I show, which of the 3 lines among my 3 Bash scripts should be commented out to make it run on Win10, but there's not that much text there, so it's probably understandable to anybody regardless of the Estonian language.

https://technology.softf1.com/software_by_third_parties/ZeroNet/2019_11_24_initially_failing_and_Ctrl-c-killed_unprepared_Estonian_demo_t1_how_to_get_the_2018_11_08_ZeroNet_Rev3703_mmmv_repackaging_t1_to_run_on_Windows10_Linux_layer.webm

With that, the Linux version of 2018 ZeroNet works "on Windows" without Windows specific code. I even uploaded the repackaging deliverables to SourceForge:

https://sourceforge.net/projects/mmmv-repackaging-projects-t1/files/repackaging_projects/repackaged_ZeroNet/
