### ISSUE TITLE
Signers, multi-user

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2337]
Hi! 

If I grant rights to edit and sign the page using `signers` in `content.json` there is way to revoke these rights in a later time? 

I assume a signer can't take over or claim a site since he/she don't know the corresponding privatekey. It would be great to have multi-user documented. @imachug can you write this up?

**Comment by purplesyringa** [comment]
Just in case... *Never* allow anyone to sign root content.json, only other content.json's. That's because clients wouldn't know whether site owner added them or they added themselves so ZeroNet *always* rejects content.json's that aren't signed with site private key.

@HelloZeroNet Can we remove `signers` field support for root `content.json` please?

**Comment by ghost** [comment]
> Just in case... Never allow anyone to sign root content.json, only other content.json's.

What other content.json? Sub-folders **doesn't** have a content.json far as I see. That would be great. 

Imagine a news website like news.example.org where each category can have different signers like news.example.org/united-states/index.html and different signers for news.example.org/russia/index.html

The root signs all files in the sub-folders so if a sub-folder has new content which is signed by other than the site owner would break all the signatures in the root. 

Do you have an example @imachug ?

**Comment by purplesyringa** [comment]
> Sub-folders doesn't have a content.json far as I see.

They do, take a look at ZeroTalk. There's data/users/content.json.

> Imagine a news website like news.example.org where each category can have different signers like news.example.org/united-states/index.html and different signers for news.example.org/russia/index.html

I'd do the following:

- Root `content.json` would be used for site code;
- Include `data/content.json` to `content.json`, this one would just be a common root for all data;
- Include `data/united-states/content.json` to `data/content.json` *with the correct signing keys*;
- Include `data/russia/content.json` to `data/content.json`, same here.

You (as a developer) would then sign root `content.json` and authors would sign `data/whatever/content.json`.

**Comment by ghost** [comment]
For these I need to exclude the **data/bitcoinaddress/russia/** in data/bitcoinaddress/content.json. 

I see your example and you should note that the data folder doesn't have content.json! 

When I include data/bitcoinaddress/russia/content.json to data/bitcoinaddress/content.json and the signer signs his content.json than the root will need to resign again the root content.json because the sub-folder's json is changed!

**Comment by purplesyringa** [comment]
> I see your example and you should note that the data folder doesn't have content.json!

Oh? It does. I think I forgot some more (obvious to me) details though: exclude `data/.*` from `content.json`. Also exclude `russia/.*` and `united-states/.*` from `data/content.json`, as always.

**Comment by ghost** [comment]
The data folder doesn't have content.json! 

/opt/zeronet/data# ls
`
  cacert-rsa.pem  chart.db	  content.db-shm      lock.pid	     users.json
1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D  cakey-rsa.pem   chart.db-shm  content.db-wal      plugins.json
1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F  cert-rsa.csr    chart.db-wal  GeoLite2-City.mmdb  sites.json
  cert-rsa.pem    content.db	  key-rsa.pem	      trackers.json
`

Excluding everything like `russia/.*` and `united-states/.*` also excluding `content.json` in those folders.

**Comment by purplesyringa** [comment]
@SwissConfederation I was referring to site's data folder.

**Comment by purplesyringa** [comment]
> Excluding everything like russia/.* and united-states/.* also excluding content.json in those folders.

No it doesn't as long as you add child content.json's to their parent content.json to `include` section.

**Comment by ghost** [comment]
Again, if I include the `content.json` at parent, than when the child signs his own `content.json`, than I need to resign the root `content.json` because the content the child `content.json` is **changed**!

**Comment by purplesyringa** [comment]
No you don't. That child content.json is ignored by root content.json so it doesn't have to be modified. You might wonder how the child file gets broadcasted but that's another story...

@HelloZeroNet Can you close this orphaned issue please?
