### ISSUE TITLE
Add a way to have shorter and readable addresses using a config file, like it is in I2P (e.g. An address book)

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#234]
So, you could have a shorter address for your own site which exists just for you, because you added it in a config file. Like you can do in I2P router console, there is an "address book"

**Comment by HelloZeroNet** [comment]
I don't think its necessary, you can use the browser's bookmark or if you want shorter address you can register a .bit domain (costs only 0.01USD)

**Comment by TheNain38** [comment]
Yes, but it requires to pay something, and having to deal with a registar or downloading the blockchain and renew the registration, with this, you can add a short, rememberable name

**Comment by HelloZeroNet** [comment]
The other way is using vanitygen: https://en.bitcoin.it/wiki/Vanitygen

You can generate custom bitcoin address eg. 1TheNain38HtKNngkdXEeobR76b53LETtpyT using, it also make easier to find your directory, data dir, in the logs and the browser will also complete it if you type "1TheNain38" in the browser bar.

**Comment by TheNain38** [comment]
Thank you, I didn't know that
