### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#2341]
### Step 1: Please describe your environment

  * ZeroNet version: latest manual bundle
  * Operating system: Debian stretch
  * Web browser: na
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: na

### Step 2: Describe the problem:
During manual install on rasberry pi 2 on Debian
https://github.com/HelloZeroNet/ZeroNet#install-from-source
error message appears:
Command "python setup.py egg_info" failed with error code 1

#### Steps to reproduce:
https://github.com/HelloZeroNet/ZeroNet#install-from-source

#### Observed Results:
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-
####### Solution
This helped:
python3 -m pip install setuptools
so I guess it should be added to requirements.txt

**Comment by purplesyringa** [comment]
Did you run setup.py yourself or did pip call it? It looks weird, this has never happened before.

**Comment by krzysztof113** [comment]
Actually there are multiple problems on raspberry and py3 and I see few open issues from other people. I'll try make it running and reference them in new issue.

**Comment by krzysztof113** [comment]
@imachug 
Could use some help on this:
error: invalid command 'bdist_wheel'
but looks like it's gone:
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/bdinst-wheel/
