### ISSUE TITLE
Certificates are not checked, before they are added.

### ISSUE THREAD

**Issue by pexo-zn** [HelloZeroNet/ZeroNet#2349]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5 (rev3853)
  * Operating system: Fedora 29
  * Web browser: Tor Browser
  * Tor status: always
  * Opened port: no
  * Special configuration: -

### Step 2: Describe the problem:

Like the title says, certificates are not checked, before they are added.

#### Steps to reproduce:

1. Make a new zite.
2. Call `this.cmd("certAdd", ["anon.mysite", "web", "1QKzd48LZUA8p4s", "Totally-a-valid-signature=lol"])`

#### Observed Results:

ZeroNet will just accept this obviously wrong certificate. This is the entry in users.json:
```
      "anon.mysite": {
        "auth_address": "14BcMpfJzrhieAHcyj3YvkqYkpKGvNwsP8", 
        "auth_privatekey": "5[redacted]", 
        "auth_type": "web", 
        "auth_user_name": "1QKzd48LZUA8p4s", 
        "cert_sign": "Totally-a-valid-signature=lol"
      }
```

#### Expected Results:

ZeroNet should not accept certificates with wrong/invalid signatures.

**Additional context**
This issue is mirrored from the [GitCenter ZeroNet repository](http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t/repo/issues/view/?1P4w4Rvh4vS9r6G5xTiSh8qEW87EKZtnJB/7@1DfrA2M9Qra6stqT6tzwNMYNweswY54KAC)(you need to install ZeroNet to visit this link)

**Comment by HelloZeroNet** [comment]
I have tried to implement this, but it's not possible, because the accepted certificate signer site is specified by the site, so we can't verify if it's a valid signature.
