### ISSUE TITLE
'file_done' event may be fired before new data is not yet added to the database.

### ISSUE THREAD

**Issue by pexo-zn** [HelloZeroNet/ZeroNet#2352]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.0 (rev4188)
  * Operating system: Fedora 30
  * Web browser: Tor Browser
  * Tor status: always
  * Opened port: no
  * Special configuration: -

### Step 2: Describe the problem:

The only way to check for a zite whether or not new content is available to render is to listen to the `file_done` event/channel, however that event will be fired before the sqlite database as added the new data if a large `data.json`(~10MB) update happened. Essentially the database lags behind in adding all of the entries, such that an sql query that would be done in response to updated data(the `file_done` event) happens (and is carried out) before all of the data is in the database, resulting in some data that is not displayed until a new `file_done` event updates the page.

#### Steps to reproduce:

1. Make a test zite, where data is displayed by an sqlite query.
2. The zite listens on `file_done` in the `siteChanged` channel for updates to the zite and updates the display with the results of a sql query.
3. Update the zite with a large data file (10MB ~150 medium sized entries).

#### Observed Results:

Depending on hardware speed, of 150 entries that should've been displayed only 120 are displayed. After the zite is updated with another (even unrelated) data the number of displayed entries is 150.

#### Expected Results:

150 displayed entries after the file update

#### Proposed solutions:

In order of most logical to least logical(in my opinion):
1. Add a `databaseChanged` channel to listen to
2. Add a `database_done` to `siteChanged`
3. Only fire `file_done` if the database is done adding the new data.

**Additional context**
This issue is mirrored from the [GitCenter ZeroNet repository](http://127.0.0.1:43110/1GitLiXB6t5r8vuU2zC6a8GYj9ME6HMQ4t/repo/issues/view/?1P4w4Rvh4vS9r6G5xTiSh8qEW87EKZtnJB/10@1DfrA2M9Qra6stqT6tzwNMYNweswY54KAC)(you need to install ZeroNet to visit this link)

**Comment by pexo-zn** [comment]
Previous conversation on GitCenter:
- >nofish@zeroid.bit commented on Sep 1 2019
    
    Yes, file_done should only get fired after it's got inserted to the database. I also found similar bug some days ago (not sure if it's related), but I wasn't able to reproduce it since then. I will try to do a test site with bigger data file.

**Comment by HelloZeroNet** [comment]
I wasn't able to reproduce the problem. (tested with a 6MB sized json file imported to db)
