### ISSUE TITLE
Persian Forum

### ISSUE THREAD

**Issue by amiremohamadi** [HelloZeroNet/ZeroNet#2355]
Is there any way to create a forum?!
Iranians want a persian forum :(

**Comment by filips123** [comment]
1. Create a Persian translation of original ZeroTalk.
  * This will just translate UI for original ZeroTalk, but the content will remain in English.
  * Translations can be found [here](https://github.com/HelloZeroNet/ZeroTalk/blob/master/languages/hu.json).
  * Save them into JSON as it is done [for other languages](https://github.com/HelloZeroNet/ZeroTalk/blob/master/languages/hu.json).
  * Submit PR with changes to [ZeroTalk repository](https://github.com/HelloZeroNet/ZeroTalk).

---

2. Clone ZeroTalk.
   * Open ZeroHello.
   * Find ZeroTalk in the list of sites.
   * Click three dots and then clone.

![clone](https://user-images.githubusercontent.com/16626308/70396495-d0e64080-1a09-11ea-8436-553602256059.png)

---

3. Configure cloned site as you want.
   * Change title and name.
   * Change description.
   * Change admins and sticky topics.

---

4. Make it known.
   * Share it on original ZeroTalk.
   * Submit PR to [ZeroTalk repository](https://github.com/HelloZeroNet/ZeroTalk) which adds link to your clone.

**Comment by amiremohamadi** [comment]
@filips123 thanks for quick response :+1:
