### ISSUE TITLE
Allow  "domain-name-yo": "", in content.json, ignored by clients without the plugin.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2360]
Unless Android gets the Py3 branch soon, I think there should be a line that the Py2 branch and non-users of the Name.yo plugin can ignore.

So if I add
> "domain-name-yo": "Syncronite.yo",

to the site's content.json, then users of the plugin can rejoice and those without the plugin can still navigate from ZeroHello to the site without error.

**Comment by filips123** [comment]
Better to just have `domain` key, but ignore it if plugin that is used by that domain does not exists. Having separate key for every domain plugin would just create a mess. Then, this can also be backported to Python 2.7 and Kivy version.

Note that @mkg20001 was working on Python 3 support for Android. That PR was merged, but I don't know if it works.

**Comment by HelloZeroNet** [comment]
The domain key is only used in ZeroHello, so we only need to modify that page to only use it if there is a plugin that supports it.

https://github.com/HelloZeroNet/ZeroHello/blob/master/js/PageSites/Site.coffee#L215

**Comment by styromaniac** [comment]
> Better to just have `domain` key, but ignore it if plugin that is used by that domain does not exists. Having separate key for every domain plugin would just create a mess. Then, this can also be backported to Python 2.7 and Kivy version.
> 
> Note that @mkg20001 was working on Python 3 support for Android. That PR was merged, but I don't know if it works.

True. I'm glad that a solution is coming, regardless.

**Comment by styromaniac** [comment]
> The domain key is only used in ZeroHello, so we only need to modify that page to only use it if there is a plugin that supports it.
> 
> https://github.com/HelloZeroNet/ZeroHello/blob/master/js/PageSites/Site.coffee#L215

Will this only require ZeroHello to be updated, or will people have to upgrade ZeroNet?

**Comment by filips123** [comment]
Just ZeroHello as it is just a site.
