### ISSUE TITLE
ZeroNet Censorship! .bit domains not working with ZeroNet! 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2361]
I have registered a domain with the `.bit` tld and configured the name accordingly, also included in the `content.json` file the `domain` field but can't get it work! 

Ping: @HelloZeroNet @JeremyRand @imachug

**Comment by filips123** [comment]
You need to wait some time so that domains are updated.

**Comment by ghost** [comment]
It is updated for about 18 hours now!

**Comment by filips123** [comment]
Is it listed [here](http://127.0.0.1:43110/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/)?

**Comment by ghost** [comment]
No.

**Comment by ghost** [comment]
For that matter another domain I registered and configured more than **2 week** ago also not in this list you linked!

**Comment by filips123** [comment]
Then you need to wait until it will be. Sometimes this is quick, but sometimes it takes a few days (or more)...

**Comment by ghost** [comment]
WTF is this list anyways? Who manages it? Is this not some kind of **censorship**? Basically saying hey if I don't add your .bit domain to this list managed by me than your .bit domain will not work with ZeroNet! 

For me sounds like censorship!

**Comment by filips123** [comment]
Suprise, @HelloZeroNet manages it...

The reason why this list is used is that there isn't any other good option for interacting with blockchain without downloading it. I don't think users will want to download 6GB of blockahain data just to view domain. But if you want using local Namecoin blockchain, use [ZeronameLocal](https://github.com/HelloZeroNet/ZeroNet/tree/py3/plugins/disabled-ZeronameLocal) plugin.

**Comment by ghost** [comment]
This is **ABSURD**! If @HelloZeroNet manages this list than he can also remove any domain from it which **IS CENSORPSHIP**!

**Comment by filips123** [comment]
Who said that you need to use Namecoin? And how would you interact with it without list?

**Comment by ghost** [comment]
This goes to Reddit! Don't you claim that ZeroNet is censorship resistant when one guy can add or remove .bit domains from a list at his own will! 

And with this blocking zeronet sites! This is how censorship works! 
You blaming me because I use Namecoin and the .bit tld? How dare you! @JeremyRand tell me your opinion.

**Comment by filips123** [comment]
We've already seen that Reddit really likes you.

**Comment by filips123** [comment]
Again, how would you interact with it without list? And who said that you **need** to use Namecoin?

**Comment by ghost** [comment]
Hardcoding it and run a cluster where can access Namecoin blockchain on a few servers. 
@HelloZeroNet has about **10 Bitcoin** sent to him as donations for this project! He can use that huge amount of money to rent the servers and use it for the Namecoin blockchain. 

That is absolutely bullshit if he can add or remove domains at his own will! **This is exactly how censorship works!**

**Comment by filips123** [comment]
> Hardcoding it and run a cluster where can access Namecoin blockchain on a few servers.

What do you mean with this? It would still run in *centralized* servers so there won't be any benefit.

**Comment by ghost** [comment]
These are just servers with let's say .onion addresses where ZeroNet connects to check the blockchain. **Leaving ZeroNet to open for censorship is absurd and unacceptable!**

**Comment by filips123** [comment]
And of course that servers can't be compromised or censored. Who runs that servers can still manage all domains.

**Comment by ghost** [comment]
I can run the server, I'm not afraid to pay $5 for a server with 20 Gb space... There should be a plugin or something to point ZeroNet to a server with the Namecoin blockchain. **Better put this directly into the Config of ZeroNet!**

But to have one list what one guy manages and he decide what .bit domains will resolve is absurd!

**Comment by filips123** [comment]
> I can run the server, I'm not afraid to pay $5 for a server with 20 Gb space...

Yes, but then you can still manage that server.

> There should be a plugin or something to point ZeroNet to a server with the Namecoin blockchain.

[ZeronameLocal](https://github.com/HelloZeroNet/ZeroNet/tree/py3/plugins/disabled-ZeronameLocal)

> Better put this directly into the Config of ZeroNet!

Domain plugins should be plugins included in core, but not directly in core.

> But to have one list what one guy manages and he decide what .bit domains will resolve is absurd!

And if *you* run your server and everyone uses it, you can also manage domains. That is also absurd!

**Comment by ghost** [comment]
But the question comes up how others can resolve the domain if they don't have this in the Config of ZeroNet.. 

Maybe the best would be to have an option to add "bitresolve" field in content.json and there everyone can state the server where the blockchain can be accessible for ZeroNet.

**Comment by ghost** [comment]
One thing is for sure this can't stay how it is now! He don't update the list anyway so no matter if you register a .bit domain or not it will not work with ZeroNet without begging mr holly @HelloZeroNet to include those domains in the list. 

This is absurd! **How can someone claim censorship resistance when he himself able to censor any site on ZeroNet????**

**Comment by filips123** [comment]
Nobody said that you must use Namecoin.

**Comment by ghost** [comment]
Tell this to @JeremyRand who even advertise ZeroNet on Namecoin.org!

**Comment by purplesyringa** [comment]
*/ban @ezdr*

You can run a local ZeroName instance or use another DNS like Name.YO.

**Comment by ghost** [comment]
The local ZeroName instance will not solve anything because other people unable to visit the mydomain.bit domain anyway!

**Comment by ghost** [comment]
> _/ban @ezdr_

Sure, when someone comes and exposes how @HelloZeroNet censoring ZeroNet than he is already attacked, blamed and subject to ban! What kind of person are you? **Don't you claim that ZeroNet is censorship resistant when one guy can censor the whole thing!**

**Comment by filips123** [comment]
> Tell this to @JeremyRand who even advertise ZeroNet on Namecoin.org!

Again, in any case, you will have to rely on centralized provider. And just that you know, most programs (browser extensions) that use Namecoin also rely on centralized servers.

> You can run a local ZeroName instance or use another DNS like Name.YO.

Or ENS. Or classic DNS. Or just Bitcoin address.

> The local ZeroName instance will not solve anything because other people unable to visit the mydomain.bit domain anyway!

@HelloZeroNet runs some script that fetches data from blockchain and puts them to Zeroname site. Maybe that script stopped for some reason, but it can be restartzed so your domain will work.

And if you rely on another centralized server, that server can also crash and all domains will stopped working. ZeroNet initially used centralized server (DNSChain), but it was discontinued so **all** domains would stopped wotrking if ZeroNet wouldn't be updated to use Zeroname site.

> Don't you claim that ZeroNet is censorship resistant when one guy can censor the whole thing!

And relying on your centralized clearnet Namecoin proxy would solve this?

**Comment by ghost** [comment]
Doesn't change the fact that ZeroNet can be censored by one guy[!](https://github.com/HelloZeroNet/ZeroNet/issues/2273)

**Comment by filips123** [comment]
Again, **who said that you have to rely on Namecoin to use ZeroNet???**

**Comment by ghost** [comment]
@JeremyRand we need to block in namecoin the possibility to configure .bit domains with ZeroNet!

**Comment by filips123** [comment]
?

**Comment by ghost** [comment]
@JeremyRand we can check the JSON field data and if "zeronet" is in it than we can block the domain registration or nameupdate.

**Comment by filips123** [comment]
Or just block **you**.

**Comment by filips123** [comment]
Again, **most programs that use Namecoin (and any other decentralized name system) use it with centralized clearnet servers**! Will you block all of them??

**Comment by ezdr** [comment]
I wish a horse put his dick into your ass and comes out in your mouth!

**Comment by ghost** [comment]
# Just making sure that .bit domains can't be configured for ZeroNet! ZeroNet censoring .bit domains and one guy has the availability to remove any .bit tld from the entire ZeroNet network!!!!

**Comment by filips123** [comment]
Every program that uses Namecoin relys on centralized servers!!!

**Comment by ghost** [comment]
@JeremyRand @imachug 

## ZeroNet censoring .bit domains and one guy has the availability to remove any .bit tld from the entire ZeroNet network!!!!

**Comment by filips123** [comment]
Every program that uses Namecoin relys on centralized servers!!!

**Comment by ghost** [comment]
@JeremyRand @imachug
## ZeroNet censoring .bit domains and one guy has the availability to remove any .bit tld from the entire ZeroNet network!!!!

**Comment by purplesyringa** [comment]
@HelloZeroNet Close this issue please.

**Comment by filips123** [comment]
And update Zeroname list 😀

**Comment by krzysztof113** [comment]
Beside the usually spamming antifa (or what you are called now) is a little right.
The dependency on one person is overall wrong. For example when accident happens. 
Some systems use majority decision making. When someone is compromised the rest can ensure system works and is not for example censored.
I don't know how it is with Zeronet.

**Comment by HelloZeroNet** [comment]
How do you define majority in a system where there is no verified identities?

**Comment by filips123** [comment]
@krzysztof113 I partly agree with you. However, as I previously said, it is hard to design and use system that is efficient, safe, user-friendly and decentralized at same time.

> And it is actually not so easy to implement a really decentralized solution. Almost every third-party domain system for integration with ZeroNet (or any other project) would require either:
> 
> * Complete protocol implementation with locally stored data (which in case of blockchain-based systems means to have the whole blockchain stored locally).
> * Data stored in a custom location (like Zeroname site).
> * Data from a third-party provider (like Infura for Ethereum).

**Comment by krzysztof113** [comment]
I totally mean the infrastructure behind, not the Zeronet. For ZN current status with signers etc is pretty great and will work by itself.

**Comment by ghost** [comment]
> Suprise, @HelloZeroNet manages it...
> 
> The reason why this list is used is that there isn't any other good option for interacting with blockchain without downloading it. I don't think users will want to download 6GB of blockahain data just to view domain. But if you want using local Namecoin blockchain, use [ZeronameLocal](https://github.com/HelloZeroNet/ZeroNet/tree/py3/plugins/disabled-ZeronameLocal) plugin.

Pardon my ignorance, but can't this data be stored in a similar way Bitcoin"s blockchain data is stored? I mean, its blockchain is huge and yet people don't have to download tons of gigabytes to use it. How's Zeronet data different and why can't be it stored in the same way as BTC transactions data?

**Comment by filips123** [comment]
> I mean, its blockchain is huge and yet people don't have to download tons of gigabytes to use it. 

If they want to use it in completely decentralized way, they *have to* download tons of gigabytes. But they can also simply use some online wallets, which are centralized, and something like this is currently used by ZeroNet.

> How's Zeronet data different and why can't be it stored in the same way as BTC transactions data?

And how are BTC transactions data stored? Isn't the only way of accessing them to download blockchain - either locally or using some online service?

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I think I found the problem, re-synced the namecoin client and it should work now.

I agree that the current operation method is not the best, and if it's possible, then we should find a more decentralized way to resolve the domains.

**Comment by JeremyRand** [comment]
So obviously this issue is a trolling attempt, not a serious bug report.  That said, I'll comment on my position here.  (I'll use singular first-person here because in practice, for the last couple years, liasoning with ZeroNet is my job at Namecoin, but I don't have any reason to think that any other Namecoin devs disagree with my take).

Am I unhappy that ZeroNet uses unnecessarily centralized resolution by default?  Yes, without a doubt.  However, I am not in the business of shitting on projects, or refusing to work with them, just because they have shortcomings.  In order for me to shit on a project over something like this, the project would need to demonstrate that they don't care about those shortcomings and have no intention of fixing them.  That is not the case for ZeroNet; I've spoken with both Tamas and Lola extensively, and it is clear to me that they want to fix those issues.  Work is ongoing to fix the situation (and this is a collaboration between me and Tamas and Lola), so I'm satisfied and have no intention of removing mentions of ZeroNet from Namecoin.org.  Why is it taking a while to get the situation fixed?  Because it's hard for me to get funding for ZeroNet-related Namecoin work, so I usually need to find a way to justify that work as relevant to another use case, and find a way to implement those deliverables so that they meet the requirements of the other use case but happen to also make things better for ZeroNet.  This will hopefully change in early 2020.  I was hoping to meet up with Tamas and/or Lola at 36C3 to discuss our next steps in this department, but unfortunately it looks like neither of them will be there this year.  I'll probably spend some time talking with them in January to coordinate things.

Anyway, yes, everyone involved knows that the current situation is not great, and everyone involved is trying to get the situation fixed.  Shitposting about it is not going to get it fixed any faster (but obviously getting the situation fixed was not ever the goal of our Antifa troll).

Cheers.

**Comment by filips123** [comment]
Unfortunately, that centralized resolution is not really "unnecessary". Currently, this is the only efficient way to query blockchain without downloading it. Because in any case, you will either have to download whole blockchain or rely on centralized resolution.

**Comment by JeremyRand** [comment]
> Unfortunately, that centralized resolution is not really "unnecessary". Currently, this is the only efficient way to query blockchain without downloading it. Because in any case, you will either have to download whole blockchain or rely on centralized resolution.

@filips123 I'm not going to dignify this issue (which was started by a troll and should just die) by getting into further serious discussion, but your statement is not completely accurate.  There are a variety of approaches to authenticating name lookups that are substantially less centralized than what ZeroNet uses now [1]; I've already discussed this in significant detail with both Tamas and Lola.  This month is not a good time to rehash those discussions on GitHub (I'm busy getting ready for 36C3), but at this point most of the work remaining is an engineering/implementation effort, not design/research.  If you're curious, feel free to contact me via some channel that isn't a GitHub issue started by a troll, but don't expect me to be around until January at the earliest.

Cheers.  :)

/me will not be replying further in this issue.  Let the shitpost die.

[1] EDIT: And no, I'm not talking about multisig-signed centralized resolution.  That's generally the kind of "solution" proposed by clowns who have no solution.

**Comment by filips123** [comment]
@JeremyRand When you will have time, could you continue discussiong that alternative solutions for domain queryng? And yes, use new new normal GitHub issue for that, not this one...

**Comment by blurHY** [comment]
This issue sounds quite funny. Lol
But indeed, central point failure is a
 problem.

**Comment by canewsin** [comment]
Since I feel I can solve any type of problem I will come with solution for this in few days, I had already solution in my mind but I want to do some research on that.
