### ISSUE TITLE
GitHub exposed the IP address of HelloZeroNet

### ISSUE THREAD

**Issue by decentralizedauthority** [HelloZeroNet/ZeroNet#2369]
@HelloZeroNet your IP address pretty nicely exposed by GitHub.

{ 
  "ip": "37.191.45.214",
  "hostname": "catv-37-191-45-214.catv.broadband.hu",
  "city": "Budapest",
  "region": "Budapest",
  "country": "HU",
  "loc": "47.4984,19.0404",
  "org": "AS6830 Liberty Global B.V.",
  "postal": "1117",
  "timezone": "Europe/Budapest",
}

**Comment by decentralizedauthority** [comment]
5353/udp  open|filtered **zeroconf** :rofl:

**Comment by decentralizedauthority** [comment]
@imachug is this a normal policy at GitHub to expose IP addresses?

**Comment by imachug** [comment]
Where did you find that information?

**Comment by decentralizedauthority** [comment]
In the security logs :roll_eyes:

**Comment by HelloZeroNet** [comment]
I'm not a developer of github, so i can't fix it. you should report it to the proper repository.

**Comment by decentralizedauthority** [comment]
It is absurd what they do, don't you think?

**Comment by HelloZeroNet** [comment]
You should report is, maybe they will give you some bounty for this. I don't want to steal it from you.
