### ISSUE TITLE
Upload logs after failure, remove sometimes failing coverage check

### ISSUE THREAD

**Issue by decentralizedauthority** [HelloZeroNet/ZeroNet#2372]
@HelloZeroNet 

Here: https://github.com/HelloZeroNet/ZeroNet/commit/bde8b30d5cc2bbc25bf60d2a013880f7f7597e83

This: 
```
after_failure:
  - zip -r log.zip log/
  - curl --upload-file ./log.zip https://transfer.sh/log.zip 
```

Should be replaced with this: 
```
after_failure:
  - tar -cvpzf log.tgz log
  - curl -F "file=@log.tgz" https://file.io
```

**Comment by HelloZeroNet** [comment]
Does not looks good: "Simply upload a file, share the link, and after it is downloaded, the file is completely deleted."
