### ISSUE TITLE
Unhandled exception: UnboundLocalError: local variable 'is_prev_builtin' referenced before assignment

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2376]
### Step 1: Please describe your environment

  * ZeroNet version: 4381?
  * Operating system: W10
  * Web browser: FF beta
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser

### Step 2: Describe the problem:

On Windows 10 i have just updated zeronet py3 rev 4360 to newest version (4381?) using the updater zite. When i then started zeronet, it failed with error:

> Traceback (most recent call last):
>   File "C:\ZeroNet-win-dist-win64\core\src\Plugin\PluginManager.py", line 138, in loadPlugins
>     sys.modules[plugin["name"]] = __import__(plugin["dir_name"])
>   File "C:\ZeroNet-win-dist-win64\core\plugins\Chart\__init__.py", line 1, in <module>
>     from . import ChartPlugin
>   File "C:\ZeroNet-win-dist-win64\core\plugins\Chart\ChartPlugin.py", line 14, in <module>
>     db = ChartDb()
>   File "C:\ZeroNet-win-dist-win64\core\plugins\Chart\ChartDb.py", line 11, in __init__
>     self.checkTables()
>   File "C:\ZeroNet-win-dist-win64\core\src\Db\Db.py", line 278, in checkTables
>     cur = self.getSharedCursor()
>   File "C:\ZeroNet-win-dist-win64\core\src\Db\Db.py", line 254, in getSharedCursor
>     self.connect()
>   File "C:\ZeroNet-win-dist-win64\core\src\Db\Db.py", line 132, in connect
>     self.log.debug("Connect called by %s" % Debug.formatStack())
>   File "C:\ZeroNet-win-dist-win64\core\src\Debug\Debug.py", line 91, in formatStack
>     tb = formatTraceback([[frame[1], frame[2]] for frame in inspect.stack()[1:]], limit=limit)
>   File "C:\ZeroNet-win-dist-win64\core\src\Debug\Debug.py", line 42, in formatTraceback
>     if is_prev_builtin and not is_last and fold_builtin:
> UnboundLocalError: local variable 'is_prev_builtin' referenced before assignment
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ZeroNet-win-dist-win64\core\zeronet.py", line 16, in main
>     import main
>   File "C:\ZeroNet-win-dist-win64\core\src\main.py", line 75, in <module>
>     PluginManager.plugin_manager.loadPlugins()
>   File "C:\ZeroNet-win-dist-win64\core\src\Plugin\PluginManager.py", line 140, in loadPlugins
>     self.log.error("Plugin %s load error: %s" % (plugin["name"], Debug.formatException(err)))
>   File "C:\ZeroNet-win-dist-win64\core\src\Debug\Debug.py", line 82, in formatException
>     tb = formatTraceback([[frame[0], frame[1]] for frame in traceback.extract_tb(exc_tb)])
>   File "C:\ZeroNet-win-dist-win64\core\src\Debug\Debug.py", line 42, in formatTraceback
>     if is_prev_builtin and not is_last and fold_builtin:
> UnboundLocalError: local variable 'is_prev_builtin' referenced before assignment

**Comment by HelloZeroNet** [comment]
Thanks for reporting should be fixed in Rev4382 https://github.com/HelloZeroNet/ZeroNet/commit/feb58e4b0e38ff309172ac7770a410469a0144db

**Comment by slrslr** [comment]
Yes, it started working when i replaced content of the C:\ZeroNet-win-dist-win64\core\src\Debug\Debug.py by the [updated file](https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/feb58e4b0e38ff309172ac7770a410469a0144db/src/Debug/Debug.py) content. Make sure the update is published on updater zite so others do not end up with ZN failing to start. Thanks
