### ISSUE TITLE
Unhandled exception: UnboundLocalError: local variable 'is_prev_builtin' referenced before assignment

### ISSUE THREAD

**Issue by eduardoaddad** [HelloZeroNet/ZeroNet#2377]
### Step 1: Please describe your environment

  * ZeroNet version: Rev4381
  * Operating system: Windows 10
  * Web browser:Chrome
  * Tor status: always
  * Opened port: no
  * Special configuration: No

### Step 2: Describe the problem:

While updating the error occurred

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by eduardoaddad** [comment]
[debug.log](https://github.com/HelloZeroNet/ZeroNet/files/4013015/debug.log)
[error.log](https://github.com/HelloZeroNet/ZeroNet/files/4013016/error.log)

**Comment by HelloZeroNet** [comment]
Thanks for reporting there is already an issue for it: https://github.com/HelloZeroNet/ZeroNet/issues/2376

I will fix it in the next hours.

**Comment by HelloZeroNet** [comment]
It's got fixed in Rev4382. To make it work again you have to replace ZeroNet-win-dist-win64\core\src\Debug\Debug.py file with https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/feb58e4b0e38ff309172ac7770a410469a0144db/src/Debug/Debug.py
