### ISSUE TITLE
greenlet.py problems

### ISSUE THREAD

**Issue by Visentinel** [HelloZeroNet/ZeroNet#2379]
### Step 1: Please describe your environment

  * ZeroNet version: 4389
  * Operating system: Win Server 2016 standard
  * Web browser: N/A
  * Tor status: Available
  * Opened port: yes
  * Special configuration: ____

#### Steps to reproduce:

  1. Run Zeronet
  2. _____
  3. _____

#### Observed Results:

Unhandled exception: KeyError: '1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz' in greenlet.py line 766 > OptionalManager/ContentDbPlugin.py line 97

Unhandled exception: RuntimeError: dictionary changed size during iteration in greenlet.py line 766 > core/src/util/helper.py line 234 > OptionalManager/OptionalManagerPlugin.py line 43

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
Thanks fore reporting fixed in Rev4394 https://github.com/HelloZeroNet/ZeroNet/commit/39442977dbd800c709663e2ee4c076cf17bafffc, https://github.com/HelloZeroNet/ZeroNet/commit/2b5e57e840e49d8e7a6f2fb78dba44a468682dfb
