### ISSUE TITLE
Unhandled exception: OSError: [WinError 123] The filename, directory name or volume label syntax is incorrect

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2381]
### Step 1: Please describe your environment

  * ZeroNet version: 4382
  * Operating system: W10
  * Web browser: FF beta
  * Tor status: available
  * Opened port: no
  * Special configuration: multiuser

### Step 2: Describe the problem:

at the beginning of the debug.log file:

> ERROR    - Unhandled exception: AttributeError: module 'main' has no attribute 'file_server' in greenlet.py line 766 > Chart/ChartCollector.py line 171 > 29

more than thousand lines like:

> ERROR    - Unhandled exception: OSError: [WinError 123] The filename, directory name or volume label syntax is incorrect: 'C:/ZeroNet-win-dist-win64/data/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/U:' in greenlet.py line 766 > Bigfile/BigfilePlugin.py line 777 > core/src/Site/Site.py line 819 > Bigfile/BigfilePlugin.py line 595 > 409 > core/src/Site/SiteStorage.py line 248 > ... > os.py line 211 > 211 > 211 > 211 > 211 > 211 > 221

Also this error:

> ERROR    WorkerManager:18Pfr2..pSzh 1.2.3.4:12345: Error writing data/users/17xHfjLGre52DGaWUeT3aWxtSxPNZK5W1J/1577654428-Interstellar.2014.mp4|432013312-433061888: [WinError 123] The filename, directory name or volume label syntax is incorrect: 'C:/ZeroNet-win-dist-win64/data/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/U:'

it happen also for other zite - Millchan.
Should i try something?

**Comment by Visentinel** [comment]
I was about to report this one to, i had thousands of the winerror 123 aswell

**Comment by HelloZeroNet** [comment]
I was unable to reproduce it so far, does it happen for every big file on only this site?

Eg. does http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:126:New+version:+0.6.2 play for you?


Do you have other startup/configuration parameters? ("U:" looks weird in the path error)

**Comment by slrslr** [comment]
@HelloZeroNet 

I started ZN (without any command line parameters, just clicking .exe) with [this zeronet.conf](https://privatebin.net/?fb44e78370da4f62#3WCjCuXeQ9MySNHfyVWaXnyj2ej7FjSg8aAbY493tWVV) and opened sites for which errors appeared and this time in debug.log was no error like ones mentioned in the first post - so just opening the site does not trigger the error. That mentioned errors "OSError: [WinError 123]" started appearing when i tried to download never downloaded bigfile by opening the site **[here](http://127.0.0.1:43110/18Pfr2oswXvD352BbJvo59gZ3GbdbipSzh/?Video=1578411068_1Fza2SFyqmiLLUc99fACNkDNPQ7k4V3935)**.

Same errors started appearing automatically for other site that i help distribute that also containing bigfiles. By now there are hundreds of such errors.

Playback of yours mentioned video worked without errors since i had it downloaded already..

The U: is the drive letter on Windows where zeronet is located (same like C:\) ...

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was able to reproduce and fix it in Rev4397 https://github.com/HelloZeroNet/ZeroNet/commit/224093b3dd9b7ee4f332811cddccbaf123090fa3
