### ISSUE TITLE
[Request] Implement GitHub actions for building and unit testing

### ISSUE THREAD

**Issue by sergei-bondarenko** [HelloZeroNet/ZeroNet#2382]
Why not to use GitHub actions for building and unit testing? They [provide](https://github.com/features/actions) free virtual machines for open source projects of all kinds of operating systems (Windows, macOS, Linux).

**Comment by filips123** [comment]
ZeroNet currently uses Travis CI for tests.

However, we could switch to GitHub Actions and also use them for more complete testing (more systems, testing bundles, testing Docker), building bundles, publishing changes... As GitHub Actions provide support for multiple workflows, more things could be tested at the same time.

**Comment by ghost** [comment]
:nauseated_face: :sneezing_face:

**Comment by ghost** [comment]
Travis is a big failure.
