### ISSUE TITLE
Add a special key in content.json to have sites redirecting to another ZeroNet site

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#239]
It would be useful when changing site address, and also in ZeroHello it could have a special thingy, like having the old address being at the bottom of the rectangle of the new address?

**Comment by HelloZeroNet** [comment]
It's simple to do with javascript or meta headers

**Comment by TheNain38** [comment]
Yeah, but it would permit having a redirecting site, that could appear differently, since it would be possible to know it is one

**Comment by HelloZeroNet** [comment]
You can also add your redirect message/rectangle to html if you prefer that way

**Comment by TheNain38** [comment]
You can close this issue I guess?

**Comment by HelloZeroNet** [comment]
After thinking bit more about it it could make sense if you want to transfer your site's ownership.
- The site new owner generates a new address
- You put "transfer": "newsiteaddress" to content.json
- When the clients receive that they rename the directory to "newsiteaddress" and transfer the settings (size limit, etc.), so they don't have to re-download everything or won't notice anything

But it's a very special case (currently i skipping features that affects < 20% of users), so it could wait.

**Comment by TheNain38** [comment]
Maybe you could open another issue? Or me?
