### ISSUE TITLE
ZeroNet high RAM during start causing tens of minutes swapping on Windows

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2397]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4397
  * Operating system: Windows 10
  * Web browser: Firefox beta
  * Tor status: available
  * Opened port: no

### Step 2: Describe the problem:

After starting ZeroNet, it started using alot of memory and Windows 10 stated heavily swapping to HDD so the computer was hardly useable. The screenshot was made after tens of minutes of high swapping, when computer started well responding and stopped swapping (thanks to zeronet high RAM usage).

![zeronet-ram-usage-after-stopped-swapping](https://user-images.githubusercontent.com/6596726/72431452-cc414480-378c-11ea-8fa8-57bfa0996cd8.jpg)

During the swapping, the Windows's resource monitor app (on the screenshot) shown significant amount of RAM marked in orange color (on the screnshot you can see 81MB, but it was gigabytes during swapping/ZN start) . And it decreased by like 2MB per second to the point you see on the screenshot. That orange kind of memory is described as "changed" and which content has to be written to the HDD before use. In the Windows's Resource monitor (keyb. shortcut Win + R, and execute "resmon"), Memory tab you can discover details about particular memory types to understand the screenshot.

Zeronet's debug log shows some interesting lines. Watch the timeflow. It shows time gaps of many minutes without any log lines - my log level is INFO, not DEBUG though. Here are the gaps:

> [2020-01-15 **10:01**:16,942] ERROR    - Unhandled exception: OperationalError: cannot VACUUM from within a transaction in greenlet.py line 766 > Chart/ChartDb.py line 133 > core/src/Db/Db.py line 150 > core/src/Db/DbCursor.py line 107
> [2020-01-15 **10:21**:44,879] INFO     SiteManager Deleting orphan site from content.db: 1NGvTpGdiZBxSf9btyudGDs6m5YxSQz7tn

> [2020-01-15 **10:23**:57,903] INFO     Site:1MMtNy..7Hjd ContentDb not initialized, load files from filesystem...
> [2020-01-15 **10:42**:39,617] INFO     Site:1Pof7m..pizH ContentDb not initialized, load files from filesystem...

[zeronet.conf](https://privatebin.net/?14fab2b3ec89ddd7#ChRW8rED5JHV3cUkUY7gQh4kW3Sj81LJ9wveccbHWNNq) (pa ssword: zn)
[debug.log](https://privatebin.net/?a44c79d0b1ca566b#2GCG15gSQurieGnLtFMc8FQdUMyWxLpgLaMBMgtEoSHM) (pa ssword: zn)
[/Stats](https://privatebin.net/?0488155c07de85f4#9xhQVM6XikaLE3XhvNwQB4C7jY6WytJV93tp4mF5Prcv) (pa ssword: zn)

I will gladly supply more details if needed or try some things. Thank you

**Comment by HelloZeroNet** [comment]
I was unable to reproduce the error, but I have added some modification in Rev4399 that should fix issues based on the logfile:
https://github.com/HelloZeroNet/ZeroNet/commit/62a2ec7254172bbfd80a51fa2a6b93a0a49010b1
https://github.com/HelloZeroNet/ZeroNet/commit/3e08eabc86b9c4def0ff6a803d07772c99a75a14
https://github.com/HelloZeroNet/ZeroNet/commit/2b7aebd89ddcbcf03c28c0cce8a82712157eef3a
https://github.com/HelloZeroNet/ZeroNet/commit/a9368bb3c8dbbccfcb95e2d335ef3427f2955196

It's still no reason for high memory usage, I will run more tests on content.db rebuild to see if I can reproduce the issue.

What the size of your sites.json, users.json, content.db, chart.db files?

**Comment by slrslr** [comment]
> What the size of your sites.json, users.json, content.db, chart.db files?

Hi,

sites.json 131MB
Site 1ChByYBAm9S5pT7F3pckjSTb2wxTaYwGeX remaining to update around 2 million optional files - images. That site block starts at line 74 666 and ends on line 2 269 893. File has around 2 300 000 lines. But this memory/SWAP issue was not there maybe a month ago even i had this site added and downloading.

users.json 2.5MB

content.db 833MB

chart.db 167MB

>  I have added some modification in Rev4399

should i try to update?

**Comment by slrslr** [comment]
i have upgraded to recent version (Version: 0.7.1 r4399) using py3 updater zite. The restart was good without any freezing and only errors was:

> ERROR    Db#0:Chart Commit error: OperationalError: cannot commit - no transaction is active in core/src/Db/Db.py line 165 (reason: Interval)
> ...
> ERROR    WorkerManager:1ADQAH..g6aA iphere:porthere: Error writing data/users/userhere/namehere-thumb.jpg: Worker stopped

one day later i shutdown zeronet and started it. no swapping, memory usage of the process is good.

only errors:

> ERROR    Db#0:Chart Commit error: OperationalError: cannot commit - no transaction is active in core/src/Db/Db.py line 165 (reason: Interval)
> ...
> ERROR    - Unhandled exception: AttributeError: 'NoneType' object has no attribute 'ip' in greenlet.py line 766 > core/src/Peer/Peer.py line 348

maybe this issue can be closed? @HelloZeroNet

**Comment by HelloZeroNet** [comment]
Thanks for the feedback, I looking into the problems

**Comment by HelloZeroNet** [comment]
I was able to fix some of the problems and added more debugging where I was unable to reproduce.
