### ISSUE TITLE
32-bit OpenPGP fingerprint in README.md is insecure

### ISSUE THREAD

**Issue by JeremyRand** [HelloZeroNet/ZeroNet#2399]
### Step 1: Please describe your environment

  * ZeroNet version: 224093b3dd9b7ee4f332811cddccbaf123090fa3
  * Operating system: Whonix
  * Web browser: Tor Browser
  * Tor status: N/A
  * Opened port: N/A
  * Special configuration: N/A

#### Steps to reproduce:

  1. Open the `README.md`.
  2. Look for the OpenPGP fingerprint.

#### Observed Results:

> Email: hello@zeronet.io (PGP: CB9613AE)

This is a 32-bit fingerprint, which is insecure.

#### Expected Results:

The full 160-bit fingerprint should be provided.

According to https://github.com/HelloZeroNet/ZeroNet/issues/759#issuecomment-274913998 , the 160-bit fingerprint is `960F FF2D 6C14 5AA6 13E8 491B 5B63 BAE6 CB96 13AE`, but @HelloZeroNet should probably confirm that himself.

**Comment by Crypto-Anarchist** [comment]
@JeremyRand that is correct. It is insecure in that form how @HelloZeroNet published his fingerprint. 

`gpg --list-key` should show the full fingerprint for example: 

pub   rsa4096 2016-09-21 [C] [expires: 2020-09-16]
      **2133BC600AB133E1D826D173FE43009C4607B1FB**
uid           [ unknown] Nick Mathewson <nickm@alum.mit.edu>
uid           [ unknown] Nick Mathewson <nickm@wangafu.net>
uid           [ unknown] Nick Mathewson <nickm@freehaven.net>
uid           [ unknown] Nick Mathewson <nickm@torproject.org>
sub   rsa4096 2016-09-23 [S] [expires: 2020-09-16]
sub   rsa4096 2016-09-23 [E] [expires: 2020-09-16]

In any way I don't think that anyone want to send to @HelloZeroNet encrypted messages. Why would anyone need that? He is not the owner of the ZeroNet software, he is just someone who started the project and owns this repository. Even without Tamas Kocsis or GitHub ZeroNet will stay and will be developed independently.

**Comment by Crypto-Anarchist** [comment]
Ohh, yeah one more thing @JeremyRand, @HelloZeroNet can sign his own public key (.asc) and publish the signature (.asc.sig) for verification. I do not imported you key Jeremy Rand because you are a disaster in managing Namecoin and be honest I want you to be kicked out of the Namecoin project.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, fixed: https://github.com/HelloZeroNet/ZeroNet/commit/914576b9db6a12aeeb6a2e0f4236fefed2b7526e
