### ISSUE TITLE
I can't get function Passback Value！

### ISSUE THREAD

**Issue by jingyuexing** [HelloZeroNet/ZeroNet#2409]
I use Angular frame to development a website ,but i use the cmd function can't get passback value,just have a log,so, i use webSocket test,this is can't work. 

```js
controller('A', ['$scope', function($scope) {
  class Friends extends ZeroFrame{
    info(){
      this.cmd("siteInfo",[],function(info){
        $scope.webSiteInfo = info;
        //info is undefined
      });
    }
  }
  var F = new Friends();
}])
```

**Comment by jingyuexing** [comment]
## this is        Design flaws????

**Comment by HelloZeroNet** [comment]
I'm not familiar with angular, but do you see the siteInfo sent on the websocket? You can check it on the F12 JS Console Network tab

**Comment by purplesyringa** [comment]
Don't create several ZeroFrame objects, use a single global object instead.

**Comment by jingyuexing** [comment]
about use a single global object,NO!
because zeronet use iframe tag to build web pages,so,i can't use global object,and i tested,this way can't work .because have two scope,the page scope,in the iframe scope

**Comment by jingyuexing** [comment]
the cmd function is not immediate passback value,so,i want to creat a websocket ,when i create websocket,the connect is close, can't to connect uiWebsocket.

**Comment by purplesyringa** [comment]
> about use a single global object,NO!
> because zeronet use iframe tag to build web pages,so,i can't use global object,and i tested,this way can't work .because have two scope,the page scope,in the iframe scope

I'm not sure if you understood me. I mean something like a singletone. Instead of instancing new ZeroFrame instances on every route, create ZeroFrame once at the start of the app.

**Comment by jingyuexing** [comment]
> > about use a single global object,NO!
> > because zeronet use iframe tag to build web pages,so,i can't use global object,and i tested,this way can't work .because have two scope,the page scope,in the iframe scope
> 
> I'm not sure if you understood me. I mean something like a singletone. Instead of instancing new ZeroFrame instances on every route, create ZeroFrame once at the start of the app.

Emmmmmm,it don't get passback value

**Comment by jingyuexing** [comment]
```js
var ZF = new ZeroFrame();
var websiteInfo;
ZF.cmd("siteInfo",[],function(info){
  websiteInfo = info;
})
```
```js
main.controller('testCtrl', ['$scope', function($scope){
  $scope.webSite={
    address:websiteInfo.address,
    peer:"",
    auth_key:websiteInfo.auth_key;
  }
}]);
```
the $scope.webSite is undefined,

![image](https://user-images.githubusercontent.com/19589872/73827212-18d2e980-483a-11ea-987d-48e8c42ff666.png)

**Comment by jingyuexing** [comment]
when i get value ,is undefined

**Comment by purplesyringa** [comment]
You should only use the info when the data has arrived. I haven't worked with Angular but the idea is to make the address and auth_key properties reactive, defaulting to null or some other empty value. When the siteInfo response is received, update the properties and re-render changed data. If you need the address to make some requests, another possible solution is to only start Angular when the data is received, i.e. inside the callback.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?
