### ISSUE TITLE
Zeronet pages stopped loading for me in Firefox beta on Windows (TypeError: window.wrapper is undefined)

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2412]
### Step 1: Please describe your environment

  * ZeroNet version: latest py3 and also py2
  * Operating system: Windows 10
  * Web browser: Firefox beta (latest - 73.0)

### Step 2: Describe the problem:

Recently (last couple of days) Firefox beta on Windows 10 is unable to properly display zeronet dynamic pages. It loads just frame, background colors, maybe logo. HTML pages seems OK.

Screenshot:
![firefox-beta-73 0-zeronet](https://user-images.githubusercontent.com/6596726/73980364-f4edd180-4927-11ea-8780-5b393d1e15c7.gif)

The developer console of the browser shows error like TypeError: window.wrapper is undefined

Other browser that i tried (Chromium) loads dynamic pages OK.. I am unsure what Mozilla changed and if that is a temporary change or if it can be just issue on my side. I restarted browser and cleared browser cache for the 127.0.0.1.

**Comment by HelloZeroNet** [comment]
I can't reproduce it in FF 73.0b12 (64-bit) (developer edition)

Does this loads for you: https://zeronet.now.im/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D ?

**Comment by JuanitoAlimana** [comment]
Ok.

**Comment by slrslr** [comment]
I have found the cause. In Incognito browsing window, page loaded OK.
Then i disabled browser extension called Chameleon for 127.0.0.1:43110 and it started working. So this may not be Firefox or Zeronet issue.
