### ISSUE TITLE
To reach the general public: Browser addon to browse on the ZeroNet

### ISSUE THREAD

**Issue by friday-james** [HelloZeroNet/ZeroNet#2416]
**Is your feature request related to a problem? Please describe.**
It is not encouraging for the general public to install all the packages in order to explore the ZeroNet.

**Describe the solution you'd like**
Aiming to let users to browse the ZeroNet with traditional browsers seamlessly, it should be a good idea to add a Chrome / Firefox plugin for ZeroNet

**Comment by filips123** [comment]
Problem is that ZeroNet relies on low-level network communication and file access which is quite hard to achieve with WebExtensions API. Also, it is written in Python and not so modular, but it may be possible to port it with WebAssembly, but the main problems are still modularity and low-level access.

However, [anshorei@zeroid.bit](http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Profile/1MoonP8t4rk9QamBUPh5Aspkwa1Xhf5ux2/1CgdRv2BFaVqNfmK3qGVYDuA7EDmk8dJVS/anshorei@zeroid.bit) is developing [ZeruNet](http://127.0.0.1:43110/4mVJrvB1XqtC4Aq55BmXyf9yXUN9iWwd8), which is ZeroNet implementation in Rust. I think it will be more modular and will support WebAssembly porting, so it might be possible to use it as an addon. However, it is currently not finished and not all things work yet.

**Comment by friday-james** [comment]
Thanks for your explanation. I guess I'll simply close this issue. Hope that ZeroNet will become popular in the near future. ;)
