### ISSUE TITLE
Need an Option to Provide Custom OpenSSL binary

### ISSUE THREAD

**Issue by canewsin** [HelloZeroNet/ZeroNet#2418]
I'm creating an Android client for ZeroNet, app is targeting Api 29, we cannot provide executable binary in app's home directory according to Android 10 (Api 29) Changes, app native dir is not static which changes on app reinstall so we need a configuration option for providing custom openssl binary position.

**Comment by canewsin** [comment]
i added required parameter on my fork, https://github.com/canewsin/ZeroNet/commit/4541ae78e7d1d55e634f05975797f2b1ad161693
I don't know why but parameter is not recognised by ZeroNet, it's not just for that but even --config_file parameter is also not recognised

error 
```
zeronet.py: error: unrecognized arguments: --config_file='C:\\Users\\PramUkesh\\Documents\\delete\\ZeroNet-py3\\zeronet.conf'
```

similar error occurs to added parameter

**Comment by canewsin** [comment]
@HelloZeroNet

**Comment by purplesyringa** [comment]
I'm not sure but you should try to use a space instead of `=`.

**Comment by canewsin** [comment]
> I'm not sure but you should try to use a space instead of `=`.

I already tried that, I works(--config_file) with space and what about about the --openssl_path option it still throws the error.
one thing to be noted is the normal convention of cmd parameters is 
> program arg=value arg2=value
why don't this project follow the normal conventions, I tried almost 4 + hours because of this convention and there is no documentation about code development any where.

**Comment by canewsin** [comment]
I made a pull request regarding this
https://github.com/HelloZeroNet/ZeroNet/pull/2422
@HelloZeroNet @imachug

**Comment by HelloZeroNet** [comment]
> program arg=value arg2=value
> why don't this project follow the normal conventions, I tried almost 4 + hours because of this convention and there is no documentation about code development any where.

The argument parsing are handled by the standard python [argparse](https://docs.python.org/3/library/argparse.html) library. As far I know there is no way to enable support for `--key=value`, but I think `--key value` format is also pretty common:

```
$ curl --config=hello
curl: option --config=hello: is unknown
````

**Comment by canewsin** [comment]
I just followed code convention of the repo and made code changes for openssl issue, hope will merged soon @HelloZeroNet

**Comment by canewsin** [comment]
Fixed with https://github.com/HelloZeroNet/ZeroNet/pull/2426

**Comment by HelloZeroNet** [comment]
To avoid confusion I have renamed it to `--openssl_bin_file` (executable openssl bin) and added `--openssl_lib_file` (.so / .dll library) argument as it could be in different location
https://github.com/HelloZeroNet/ZeroNet/commit/1cc0ec3f31b3b8db4a534ec64ebe82629b81fa2e
