### ISSUE TITLE
ContentFilter - unable to "Ignore blocking and visit the site"

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2419]
### Step 1: Please describe your environment

  * ZeroNet version: 4404
  * Operating system: W10
  * Web browser: FF beta

### Step 2: Describe the problem:

Hello, i am subscribbed to a [blocklist](http://127.0.0.1:43110/13CgSQeywg2ius5pjXVCk7dKUCRkz5xvW3/) and when i try to visit one listed site clicking "Ignore blocking and visit the site", it does nothing and the developer console says:

> [ZeroFrame] Unknown request Object { cmd: "setServerInfo", params: {…}, id: 8 } ZeroFrame.js:98:21

It happens for multiple blocklist sites and happen both in Firefox and Chrome.

**Comment by HelloZeroNet** [comment]
Thanks for reporting I was able to reproduce it with other problems: In Rev4411 I have re-factored the way it handles the blocklist and it should work now. https://github.com/HelloZeroNet/ZeroNet/commit/bc76bf291a48411bdaa1071883d216bbf02b10cc
