### ISSUE TITLE
Ui.UiServer Error 403: Invalid origin

### ISSUE THREAD

**Issue by rvs75** [HelloZeroNet/ZeroNet#2420]
### Step 1: Please describe your environment

  * ZeroNet version: 0.6.5 r3870 (Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-46-generic x86_64)
  * Operating system: WIndows 10
  * Web browser: Firefox 72.0.2
  * Tor status: always
  * Opened port: yes
  * Special configuration: Running ZeroNet on a Webserver

### Step 2: Describe the problem:

Since yesterday our open Zeronet Server did not work. At the Log file we find these error messages:

```
- Starting ZeroNet...
[10:52:09] - Libsecpk256k1 loaded: CompiledLib in 0.036s
[10:52:09] - Version: 0.7.1 r4206, Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0], Gevent: 1.4.0
[10:52:09] - Creating FileServer....
[10:52:09] - Creating UiServer....
[10:52:09] - Removing old SSL certs...
[10:52:09] - Starting servers....
[10:52:09] Ui.UiServer --------------------------------------
[10:52:09] Ui.UiServer Web interface: http://*:43110/
[10:52:09] Ui.UiServer --------------------------------------
[10:52:10] PeerPortchecker Checking port 18567 (ipv4) using checkPortchecker result: {'ip': 'xxx.xxx.xxx.xxx', 'opened': True} in 0.790s
[10:52:10] ConnServer Server port opened ipv4: True, ipv6: None
[10:52:26] Ui.UiServer Added 127.0.0.1:43110 as allowed host

[10:52:47] Ui.UiServer Error 403: Invalid origin: https://www.example.com
[10:52:57] Ui.UiServer Error 403: Invalid origin: https://www.example.com
[10:53:08] Ui.UiServer Error 403: Invalid origin: https://www.example.com
[10:53:19] Ui.UiServer Error 403: Invalid origin: https://www.example.com
[10:53:29] Ui.UiServer Error 403: Invalid origin: https://www.example.com

```

ZeroNet is running behind a transparent proxy (apache2).

Aapche Config looks like that:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName www.example.com
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	Header add "Access-Control-Allow-Origin" "*"

	RewriteEngine on
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
        RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
        RewriteRule .* ws://127.0.0.1:43110%{REQUEST_URI} [P]
	

    	ProxyTimeout 3600
    	ProxyPass /zerotalk http://127.0.0.1:43110/Talk.ZeroNetwork.bit
    	ProxyPassReverse /zerotalk  http://127.0.0.1:43110/Talk.ZeroNetwork.bit

    	ProxyPass /Websocket http://127.0.0.1:43110/
    	ProxyPassReverse /Websocket http://127.0.0.1:43110/

...
</VirtualHost>
</IfModule>
```

#### Steps to reproduce:

  1. open a zn page
 

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

![grafik](https://user-images.githubusercontent.com/1433227/74144265-b6dd0000-4bfc-11ea-89e2-9c52cba222e1.png)

#### Expected Results:

  * What did you expect to happen?

Open a ZeroNet Page.

**Comment by slrslr** [comment]
This is likely non helpful, but try to check [this comment](https://github.com/HelloZeroNet/ZeroNet/issues/624#issuecomment-257161984). It shows an example of the Zeronet Apache virtualhost file.

**Comment by purplesyringa** [comment]
> `Header add "Access-Control-Allow-Origin" "*"`

This is unrelated to your problem but please don't do this. Disabling CORS allows all zites to steal proxy user's info, e.g. their private keys.

**Comment by rvs75** [comment]
> 
> 
> > `Header add "Access-Control-Allow-Origin" "*"`
> 
> This is unrelated to your problem but please don't do this. Disabling CORS allows all zites to steal proxy user's info, e.g. their private keys.

OK, done.

**Comment by rvs75** [comment]
> 
> 
> This is likely non helpful, but try to check [this comment](https://github.com/HelloZeroNet/ZeroNet/issues/624#issuecomment-257161984). It shows an example of the Zeronet Apache virtualhost file.

Did not help.

**Comment by rvs75** [comment]
The problem is here (UiRequest.py:711):

```
  if origin_host != host and origin_host not in self.server.allowed_ws_origins:
    ws.send(json.dumps({"error": "Invalid origin: %s" % origin}))
    return self.error403("Invalid origin: %s" % origin)
```

I commented out these lines and it is running again.
Of course it would be better to know how I can add my domain to the allowed_ws_origins.

**Comment by purplesyringa** [comment]
Have you tried to add your domain to ui_host config variable?

**Comment by rvs75** [comment]
Yes I have. The same error message appears.

**Comment by rvs75** [comment]
I have my config here: /opt/ZeroBundle/ZeroNet/zeronet.conf
How can I check the config? 
If I run 

> ./ZeroNet.sh getConfig 

my var ui_host did not appears.

**Comment by HelloZeroNet** [comment]
In Chrome please after opening the site and see the error check the js console (F12) > Network tab > Websocket connection
You should see like this:
Request URL: wss://domain.com/ZeroNet-Internal/Websocket?wrapper_key=...
Host: domain.com
Origin: https://domain.com

**Comment by rvs75** [comment]
Host: www.example.com
Origin: https://www.example.com

**Comment by rvs75** [comment]
So, yes I do

**Comment by HelloZeroNet** [comment]
The probably the Host does not get passed to the zeronet http server.

Try adding: `Header set Host "www.example.com"`

Probably you will see invalid host error, to fix it you need to add `ui_host = www.example.com` to zeronet.conf or start it with --ui_host www.example.com

**Comment by rvs75** [comment]
I logged the python vars and now I know what's wrong:

-  origin_host: www.example.com
-  host: 127.0.0.1:43110

> Try adding: Header set Host "www.example.com"

Did not work.

**Comment by HelloZeroNet** [comment]
I'm not familiar with Apache, but based on https://serverfault.com/questions/557233/apache-proxy-http-redirect-to-ip-and-set-hostname `ProxyPreserveHost On` should be the correct solution

**Comment by rvs75** [comment]
It works. This was the solution:

ProxyPreserveHost on
ProxyErrorOverride Off

Thanks
