### ISSUE TITLE
WebSocket handleRequest error: KeyError ; DbQuery error: AttributeError: 'NoneType' object has no attribute 'execute' ...

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2423]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4411, Python 3.7.3
  * Operating system: W10
  * Web browser: FF beta

### Step 2: Describe the problem:

Hello, after i tried to visit [blocklisted](http://127.0.0.1:43110/13CgSQeywg2ius5pjXVCk7dKUCRkz5xvW3) site 1NZNtZQZHQRJXafvJpmY5jgqwRaCEZMsUc and clicking to "Remove from blocklist and visit the site", then it loaded the site. I then deleted it (possibly before it completed downloading), then i checked the debug.log to see [ERRORS for that site](https://pastebin.com/raw/NJ6V0npi). **When i tried again**, then Websocket error no longer appeared, but the error "DbQuery error: AttributeError: 'NoneType' object has no attribute 'execute'" remained.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/9b85d8638d30205c72ca8c8c162bcd01022f5405
