### ISSUE TITLE
Unhandled exception: AttributeError: 'ConfigPlugin' object has no attribute 'getCmdlineValue'

### ISSUE THREAD

**Issue by wait4zer0** [HelloZeroNet/ZeroNet#2430]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: windows
  * Web browser: edge
  * Tor status: not available/always/disabled
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. after i download new version and copy that file into the directory
  2. _____
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?

**Comment by d2ouble** [comment]
[debug.log](https://github.com/HelloZeroNet/ZeroNet/files/4228356/debug.log)
