### ISSUE TITLE
Starting ZeroNet fresh forces you to make a ZeroMe profile even if you have one already.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2433]
I don't know why I can't avoid having to create a new profile. I download the hubs after ZeroMe to prevent such a thing, but it no longer works. I'm still forced to create a profile now.

This occurs on Android and Linux, py3, latest revision.

**Comment by styromaniac** [comment]
Looks like this was fixed.

**Comment by HelloZeroNet** [comment]
Probably related to https://github.com/HelloZeroNet/ZeroNet/issues/2434
