### ISSUE TITLE
Site Data not downloading for new installation

### ISSUE THREAD

**Issue by canewsin** [HelloZeroNet/ZeroNet#2434]
### Step 1: Please describe your environment

  * ZeroNet version: 4452
  * Operating system: Windows / Android
  * Web browser: Edge latest
  * Tor status: available
  * Opened port: yes 

### Step 2: Describe the problem:
If you install zeronet with latest revision, site data is not downloading, but if we have site data, then sites are working as usual
#### Steps to reproduce:
update zeronet to latest rev

if it is fresh install open zerotalk

if you already have data folder rename to data-org as backup and restart zeronet
and open zerotalk

it shows Initial sync in progress...

after some time site showing as your own site.

#### Observed Results:
![Annotation 2020-02-21 172010](https://user-images.githubusercontent.com/26790557/75032379-7881f380-54ce-11ea-8b4a-d1283fc69eee.png)

#### Expected Results:
Should download site data.

**Comment by canewsin** [comment]
@shortcutme @HelloZeroNet this bug status is severe so prioritise this.

**Comment by canewsin** [comment]
Rev 4404 working correctly, thus commits after this causing issues.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I can confirm something is bad...working on it

**Comment by HelloZeroNet** [comment]
It was broken by https://github.com/HelloZeroNet/ZeroNet/commit/d2627f36d5cce66f6bfdcf22843554b50b9a68fa in Rev4411
Fixed in Rev4455 https://github.com/HelloZeroNet/ZeroNet/commit/f0a706f6ab847ba22798a8107b4b1f15d79de6b7
