### ISSUE TITLE
Is it possible to use sites for react inside zeronets?

### ISSUE THREAD

**Issue by corsairs** [HelloZeroNet/ZeroNet#2435]
https://ru.reactjs.org/

I would like to connect the site to the react.js. Will such sites be supported internally by zeronet?

**Comment by purplesyringa** [comment]
Yeah, just make sure to include React.js with `<script>` tag.

**Comment by mahdi-ln** [comment]
On an ordinary web server below address load [Trader Joe](https://traderjoexyz.com) front-end but not zeronet:
http://127.0.0.1:43110/17X73Q16Ea1tofWS33TXdaB6DZEUo956Ab/
