### ISSUE TITLE
Stream big file upload

### ISSUE THREAD

**Issue by purplesyringa** [HelloZeroNet/ZeroNet#2436]
**Is your feature request related to a problem? Please describe.**
I need to upload a big file (say, 2 GiB) from a web app but I generate the data dynamically. I can't save the whole file to memory because it might not fit, so I'd like to stream it. It seems like using ReadableStream as request body is what I'm looking for but unfortunately no browsers support it.

**Describe the solution you'd like**
An API call similar to `bigfileUploadInit` to create a new WebSocket, not an HTTP stream. It would be used like this:
```javascript
const size = 1024 * 1024; // 1 MiB
const origin = location.href.replace(/(\:\/\/.*?)\/.*/, "$1").replace("http", "ws");
const {url} = await page.cmdp("bigfileUploadInitWebsocket", ["test.bin", size]);
const ws = new WebSocket(url.replace("{origin}", origin));
let pos = 0;
ws.onmessage = e => {
    if(e.data === "poll") {
        part = (new Uint8Array(1024)).buffer; // for example
        ws.send(part);
        pos += part.byteLength;
    }
};
```
Some non-intuitive details:
1. The backend should send `"poll"` message after it receives a packet, asking you to send a new packet. This is required because there's no way to control websocket send queue (as opposed to classic file upload when the browser handles it) so sending too much data might break the process. Sending packets only when the backend tells you is a decent workaround.
2. A `"poll"` message should be sent by the backend when the socket is open. Alternatively, the client could just listen to `open` websocket event but a `"poll"` message looks more consistent.

**Describe alternatives you've considered**
1. Asking the browser developers to allow using ReadableStream as request body. :man_shrugging: 
2. Using `fileWrite`: it uses too much memory.
3. Using the main websocket for file upload instead of a separate one. This is something to consider. I (intuitively) think that using a separate websocket would block the main one less but I'm not sure.

**Additional context**
[Standards](https://github.com/whatwg/fetch/pull/425)

**Comment by HelloZeroNet** [comment]
Yeah looks like there is no way to stream client-generated content to http request body. Streaming to separate websocket channel sounds like a good idea, but needs some benchmark on performance also on client and server side

**Comment by purplesyringa** [comment]
I get 35 Mbps upload speed with websockets (both with and without hashing, so it's a network problem). XHR is waaay faster.

**Comment by purplesyringa** [comment]
Interestingly, using a simple server with `websocket` package gives 120-130 Mbps when uploading a file and 350 Mbps when uploading zeroes. This probably means it's either `gevent-websocket` that's slow or there are too many tasks executing in parallel in a single process.

```python
import asyncio
import websockets


async def handler(websocket, path):
    await websocket.send("poll")
    while True:
        await websocket.recv()
        await websocket.send("poll")


start_server = websockets.serve(handler, "localhost", 8765, max_size=2 ** 23)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by purplesyringa** [comment]
Uploading the same file to ZeroUp Unlimited (official ZeroUp doesn't allow so big files) gives me around 800 Mbps. The difference is still too big...

**Comment by purplesyringa** [comment]
A simple Python script gives me around 450 mbps which already looks good.

```python
import asyncio
import websockets
import time

async def main():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as ws:
        time_start = time.time()
        bytes_sent = 0
        while True:
            await ws.recv()
            block = b"x" * (2 * 1024 * 1024)
            await ws.send(block)
            bytes_sent += len(block)
            print(int(bytes_sent / 1024 / 1024 * 8 / (time.time() - time_start)), "mbps")

asyncio.get_event_loop().run_until_complete(main())
```

To sum up:

- The browser is a bit slow
- `gevent-websocket` is slow
- websockets are slow

:man_facepalming:

**Comment by purplesyringa** [comment]
Yeah, `gevent-websocket` is the main problem. 40 Mbps (`gevent-websocket`) vs 450 Mbps (`websockets`). Switching looks like a great opportunity to increase performance and get rid of an incompatible library (license-wise). What do you think? @HelloZeroNet

**Comment by purplesyringa** [comment]
AFAIK `gevent-websocket` is the only websocket library that supports gevent. We could switch to asyncio but you said you don't like it, and also gevent is faster than asyncio according all the benchmarks I could find. It looks like we should either patch `gevent-websocket` or create our own library. The first approach would probably be simplier but the latter one can potentially give better results and resolve license problems.

**Comment by purplesyringa** [comment]
I think I have identified the lag reason:

```python
for i in range_type(self.length):
    payload[i] ^= mask[i % 4]
```

It's *really* dumb but it takes Python a second to loop through a 1 MiB array. wtf

Without these 2 lines, I get 1700 Mbps throughput.

**Comment by purplesyringa** [comment]
I've managed to get 240 Mbps throughput with some optimizations but it's still too slow. @HelloZeroNet Is there any probability I may use a native module to make this run faster?

**Comment by HelloZeroNet** [comment]
Other idea: multi-request XHR. Add extra argument that makes the hashing function wait for more data and create separate post for every X MB.

**Comment by purplesyringa** [comment]
I'm afraid creating a new connection per each MiB is going to be too slow. I've managed to get gevent-websocket load data at 740 Mbps btw! That's even more than `websockets`. That might be enough.

**Comment by purplesyringa** [comment]
Do you think you can merge the PR? @HelloZeroNet
