### ISSUE TITLE
demo.zeronet.io is not served over HTTPS

### ISSUE THREAD

**Issue by zebMcCorkle** [HelloZeroNet/ZeroNet#244]
My ZeroProxy (https://zeronet.classcoder.com) runs over HTTPS, which works great for just about everything: except for ZeroID. `demo.zeronet.io` is served over HTTP, which Chrome complains about when an AJAX request goes through for it from HTTPS. This is quite breaking for my ZeroProxy, and it would be great if `demo.zeronet.io` had a Let's Encrypt cert or something.

**Comment by HelloZeroNet** [comment]
changed to https, please test

**Comment by zebMcCorkle** [comment]
Works!
