### ISSUE TITLE
windows defender flairs up when visiting this zite

### ISSUE THREAD

**Issue by sdtqwe4ty** [HelloZeroNet/ZeroNet#2440]
### Step 1: Please describe your environment

  * ZeroNet version: ___0.7.1 (rev4223)__
  * Operating system: __Windows 10 pro version_1903_OS build:18362.535_
  * Web browser: __ Tor browser 9.0.5___
  * Tor status: always
  * Opened port: yes
  * Special configuration: ____

#### Steps to reproduce:

  1. ___visit this zite:http://127.0.0.1:43110/13eFkhbXXQcJqd729zRLL9tMxxhz9d4UA6/__
  2. _____
  3. _____

#### Observed Results:

https://files.catbox.moe/bwb75x.PNG

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
The page is openly using javascript based cryptominer:

http://127.0.0.1:43110/13eFkhbXXQcJqd729zRLL9tMxxhz9d4UA6/CpuContribute.html

It's harmless, you can even disable it, not sure why is defender nagging about it, but it's safe to ignore.
