### ISSUE TITLE
RaspberryPi _ Launching zeronet _  Segmentation fault

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#245]
My error :

```
 pi@raspberrypi ~/myPrograms/ZeroNet-master $  python zeronet.py
 - Starting ZeroNet...
 [10:34:13] - OpenSSL loaded, version: 01000105F
 [10:34:13] - Version: 0.3.5 r859, Python 2.7.3 (default, Mar 18 2014, 05:13:23) 
 [GCC 4.6.3], Gevent: 0.13.6
 [10:34:13] - Creating FileServer....
 Segmentation fault
```

**Comment by HelloZeroNet** [comment]
Try update the packages, gevent 0.13 seems very old. (2012)

**Comment by sbDevGit** [comment]
I tried 
     sudo pip install gevent --upgrade
It fails with
     sudo pip update gevent
     ERROR: unknown command

p/pip-s8lODB-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-armv7l-2.7
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-armv7l-2.7/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of greenlet
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-jXs0nN/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-s8lODB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-jXs0nN/greenlet

**Comment by border0464111** [comment]
At this point, it looks like a pip problem more then zeronet. Is this still an issue with updated libs ?
