### ISSUE TITLE
Installation issue (Linux) : "... Please install setuptools."

### ISSUE THREAD

**Issue by koeur2pi** [HelloZeroNet/ZeroNet#246]
python get-pip.py --user gevent msgpack-python
Collecting gevent
  Using cached gevent-1.0.2.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.

uname -a
Linux Boop 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

 lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa

**Comment by HelloZeroNet** [comment]
Looks like you missing some package that required by pip. The Debian install method should work on mint: https://github.com/HelloZeroNet/ZeroNet#debian

**Comment by koeur2pi** [comment]
Ok, when trying to use the debian pack, I get : 
`python zeronet.py
- Starting ZeroNet...
[20:05:19] - OpenSSL loaded, version: 01000106F
[20:05:19] - Version: 0.3.5 r859, Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2], Gevent: 1.0
[20:05:19] - Creating FileServer....
[20:05:19] TorManager Tor controller connect error: [Errno 111] Connection refused
[20:05:19] ConnServer Error: Unsupported msgpack version: (0, 3, 0) (<0.4.0), please run `sudo apt-get install python-pip; sudo pip install msgpack-python --upgrade``

Any idea please ?

**Comment by HelloZeroNet** [comment]
To update msgpack without PIP:
- Download msgpack from: https://github.com/msgpack/msgpack-python/archive/0.4.6.tar.gz
- Unpack anywhere
- Copy the msgpack directory from it to the same directory where your zeronet.py is

**Comment by koeur2pi** [comment]
Thank you. The first solution work.
In the future, I will try to use Docker for easier installation.
