### ISSUE TITLE
Always revise rev number for Important Updates.

### ISSUE THREAD

**Issue by canewsin** [HelloZeroNet/ZeroNet#2477]
@imachug pushed the fix for openssl library search path, but due to non change of rev number bug still exists on repo, so for this type of fixes always change rev number before pushing changes.
@HelloZeroNet

**Comment by canewsin** [comment]
@HelloZeroNet 
Wait once, latest commits completely breaks ZeroNet Mobile.
@imachug I tried manually downloading zeronet Repo with latest commit below error occurs
![Screenshot_2020-03-15-11-17-53-216_in canews zeronet](https://user-images.githubusercontent.com/26790557/76696351-6d2a7e00-66b0-11ea-826e-195c8f6ba404.jpg)
![Screenshot_2020-03-15-11-18-02-175_in canews zeronet](https://user-images.githubusercontent.com/26790557/76696350-6ac82400-66b0-11ea-8ab5-594fbbc241b8.jpg)

**Comment by purplesyringa** [comment]
You have some really weird OpenSSL version I guess... Could you please send me the library for tests?

**Comment by canewsin** [comment]
@imachug Those available on github binaries, how do you test those, those are android binaries.

**Comment by canewsin** [comment]
OpenSSL version source used v 1.1.1
https://github.com/yan12125/python3-android/blob/9adbcfaca37f40b7a86381f83f0f6af4187233ae/pybuild/packages/openssl.py#L20

source repo 
https://github.com/python/cpython-source-deps/tree/openssl-1.1.1

**Comment by purplesyringa** [comment]
Is there any way to modify the code for your Android client in-place? Probably some directory I could change, or you could make a custom build for me with a custom `actionServerFileWrite` UIWebsocket command?

**Comment by canewsin** [comment]
Currently, I was using this for python side code
https://github.com/canewsin/python3-android/tree/python3.8

I don't understood what you are asking about `actionServerFileWrite` though.

**Comment by canewsin** [comment]
ok you want use custom ZeroNet repo, i will try to make it, do you have build system for android ? you also need flutter build system, the easiest thing is modify ZeroNet repo send it to me or host it on github releases , i will make a custom build to do use that repo.

**Comment by purplesyringa** [comment]
Is the source code stored as plain `.py` files?

**Comment by canewsin** [comment]
yes, there is no change in py files those serve as py files.

**Comment by purplesyringa** [comment]
Great, can you please make a custom build with the following code added to the end of `src/Ui/UiWebsocket.py`:

```python
    @flag.admin
    def actionServerFileWrite(self, to, path, content_base64):
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), path), "wb") as f:
            import base64
            f.write(base64.b64decode(content_base64))
        self.response(to, "ok")

    @flag.admin
    def actionServerFileRead(self, to, path):
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), path), "rb") as f:
            import base64
            self.response(to, base64.b64encode(f.read()).decode())
```

**Comment by canewsin** [comment]
@imachug will do

**Comment by canewsin** [comment]
did this code available on github ?

**Comment by purplesyringa** [comment]
Nope I guess, but it's just a 15-line modification you could apply to the latest `py3`.

**Comment by canewsin** [comment]
ok i will update when build is ready, which arch(arm64/armeabi/x86_64) your device is ?

**Comment by purplesyringa** [comment]
aarch64

**Comment by canewsin** [comment]
do you want to use it a different package ? if i use same package name you have to uninstall previous one and install custom one. i was using different package for custom build.

**Comment by purplesyringa** [comment]
Yeah, please use a different one.

**Comment by canewsin** [comment]
@imachug 
Download this file and rename it .apk and install
[app-arm64-v8a-release.zip](https://github.com/HelloZeroNet/ZeroNet/files/4333960/app-arm64-v8a-release.zip)

**Comment by purplesyringa** [comment]
Ok... sorry for asking, but could you please make another build for me with the same change, but based on the old version (i.e. the one that's on Google Play right now).

**Comment by canewsin** [comment]
@imachug
I already expected this, so I  made a modular build, you don't need a seperate build, I had to change files on GitHub releases I will notify you once done.

**Comment by canewsin** [comment]
@imachug changed bins on github, you have to clear app data( not cache ) in app settings and reopen the app, it will download new zeronet(changed) repo and binaries.

**Comment by purplesyringa** [comment]
@canewsin The problem should now be fixed (thanks for the build btw), please make sure it works for you too!

**Comment by canewsin** [comment]
@imachug fixed for me as well.
