### ISSUE TITLE
Even with latest commits had a Websocket error.

### ISSUE THREAD

**Issue by canewsin** [HelloZeroNet/ZeroNet#2480]
@imachug 
I merged and tested https://github.com/HelloZeroNet/ZeroNet/pull/2475
Still there are errors occurred below is only log I get.
![IMG_20200316_161929](https://user-images.githubusercontent.com/26790557/76749774-15b90a80-67a3-11ea-936d-adba9319e7c3.jpg)

**Comment by canewsin** [comment]
This happens, when I browse those sites Mail, HelloZeroNet, Talk

**Comment by canewsin** [comment]
i think error pointing __init_.py in this file
https://github.com/HelloZeroNet/ZeroNet/blob/19f003141b75940ecfbe3039ca4203f6b37c8c75/src/lib/gevent_ws/__init__.py

**Comment by HelloZeroNet** [comment]
Fixed by https://github.com/HelloZeroNet/ZeroNet/pull/2475?

**Comment by purplesyringa** [comment]
Probably not. I'll check what's wrong again.

**Comment by canewsin** [comment]
@imachug the image had 4 errors, except first one all the three had disappeared

**Comment by purplesyringa** [comment]
@canewsin The first error has no traceback. Are you running ZeroNet with `--debug`?

**Comment by canewsin** [comment]
@imachug no, I will try with it.

**Comment by canewsin** [comment]
@imachug I was not able to reproduce it for now, but it happens in this class
https://github.com/HelloZeroNet/ZeroNet/blob/6beb76eac8f6cadfab97dcc6c1800c21aa0ae1fa/src/Ui/UiServer.py#L29
it may be helpful to you.

**Comment by canewsin** [comment]
closing this, since I cannot reproduce, if I can, I will open another issue with more verbose.
