### ISSUE TITLE
Dot-files

### ISSUE THREAD

**Issue by purplesyringa** [HelloZeroNet/ZeroNet#2484]
### Step 1: Please describe your environment

  * ZeroNet version: v0.7.1 (r4462)
  * Operating system: Ubuntu
  * Web browser: Firefox
  * Tor status: available
  * Opened port: yes
  * Special configuration: none

### Step 2: Describe the problem:

Site 1N9sU8qh3S4ei9PHE1qQyYPbcckJomvwMd can't be downloaded. From logs:

```
[08:17:28] Site:1N9sU8..vwMd content.json: verify sign error: VerifyError: Invalid relative path: .git/COMMIT_EDITMSG in ContentManager.py line 1000 > 880
```

It looks like ZeroNet doesn't like directories which start with a dot, but it has no problems with e.g. `dir/.file`. It looks like this change was added after the site was signed and backward compatibility was broken. Personally, I don't see any threat in `.`, given that we've already ensured there's no `..`. Also, `\\` is not handled, only `/`. Do you think we can replace the original check:

```python
def isValidRelativePath(self, relative_path):
    if ".." in relative_path.replace("\\", "/").split("/"):
        return False
    elif len(relative_path) > 255:
        return False
    elif relative_path[0] in (".", "/"):  # Starts with
        return False
    elif relative_path[-1] in (".", " "):  # Ends with
        return False
    elif re.match(r".*(^|/)(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9]|CONOUT\$|CONIN\$)(\.|/|$)", relative_path, re.IGNORECASE):  # Protected on Windows
        return False
    else:
        return re.match(r"^[^\x00-\x1F\"*:<>?\\|]+$", relative_path)
```

with:

```python
def isValidRelativePath(self, relative_path):
    if ".." in relative_path.replace("\\", "/").split("/"):
        return False
    elif len(relative_path) > 255:
        return False
    elif relative_path[0] in ("/", "\\"):  # Starts with
        return False
    elif relative_path[-1] in (".", " "):  # Ends with
        return False
    elif re.match(r".*(^|/)(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9]|CONOUT\$|CONIN\$)(\.|/|$)", relative_path, re.IGNORECASE):  # Protected on Windows
        return False
    else:
        return re.match(r"^[^\x00-\x1F\"*:<>?\\|]+$", relative_path)
```

?

#### Steps to reproduce:

  1. Open http://127.0.0.1:43110/1N9sU8qh3S4ei9PHE1qQyYPbcckJomvwMd/

#### Observed Results:

`CONTENT.JSON DOWNLOAD FAILED`

#### Expected Results:

The site loads correctly.

**Comment by wandrien** [comment]
The bug seems to be introduced in https://github.com/HelloZeroNet/ZeroNet/commit/d569d9488a521379c57e7e580089c95e2b2e3ba7
Also, no tests for that specific case have been added.

AFAIK, the unix-like `.blabla-config` files have been working on all Windows versions and are used by a lot of ported software.

The docs:

> https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

**Comment by wandrien** [comment]
Seems fixed.

**Comment by purplesyringa** [comment]
Right, I saw a commit fixing this.

**Comment by HelloZeroNet** [comment]
Yeah, thanks for reporting, fixed in rev 4471: https://github.com/HelloZeroNet/ZeroNet/commit/31d43049153477e0a5545fe5f192b08b27f8a02f
