### ISSUE TITLE
Websocket Invalid HTTP method error in debug mode

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#2486]
### Step 1: Please describe your environment

  * ZeroNet version: Rev4462
  * Operating system: Win10
  * Web browser: Chrome
  * Tor status: disabled
  * Opened port: no
  * Special configuration: --debug with Werkzeug (0.14.1) installed

#### Steps to reproduce:

 - start with zeronet.py --debug

#### Observed Results:

 - Websocket connection failed
 - Logged: `<gevent._socket3.socket object, fd=1456, family=2, type=1, proto=0>: Invalid HTTP method: '\x81³ï ÈL\x94\x02«!\x8b\x02òn`

**Comment by HelloZeroNet** [comment]
cc @imachug

**Comment by HelloZeroNet** [comment]
Related code: https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Ui/UiServer.py#L138 (works if I remove this section)

**Comment by purplesyringa** [comment]
Got it.

**Comment by purplesyringa** [comment]
I can reproduce the bug on Firefox, perhaps Werkzeug overrides some of my handlers.

**Comment by HelloZeroNet** [comment]
This is the wrapper function that that make it broke:
https://github.com/pallets/werkzeug/blob/master/src/werkzeug/debug/__init__.py#L294

Replacing it with `return self.app(environ, start_response)` fixes the issue (ofc this is not a solution as it make the module module useless)

**Comment by purplesyringa** [comment]
Do you know why

```python
return self.app(environ, start_response)
```

works but

```python
yield from self.app(environ, start_response)
```

doesn't? :)

**Comment by HelloZeroNet** [comment]
don't know exactly, but the difference: in the second case self.app won't get called until the start of the iteration of the function.

**Comment by purplesyringa** [comment]
I've managed to fix it I think. I knew the difference but I had no idea it could apply here.

**Comment by HelloZeroNet** [comment]
Thanks, I can confirm it works now! wohoo

**Comment by purplesyringa** [comment]
We have a failing master now though, lol.

*UPD*: It's just a Travis bug, it's fine.

**Comment by HelloZeroNet** [comment]
Probably because I merged it before the tests

**Comment by purplesyringa** [comment]
Yeah, I think so.
