### ISSUE TITLE
Changing ZeroFrame license

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroNet#2499]
It would be good to change and better define license of ZeroFrame library.

It is currently developed and published in this repository, so it is probably also licensed as GPLv2, just like the rest of ZeroHello. This makes it harder (actually impossible if we are strict) to use it in any site that it is licensed other than GPLv2, so most of current sites.

To fix this, you should update the license of ZeroFrame library to something like MIT. This probably won't be hard, as all commits are made by you so you won't need agreement from others. To do this, you would probably just need to add some notice as a comment to that file, and as MIT is compatible with GPLv2, this shouldn't cause problems with the rest of repository.

/cc @shortcutme @imachug

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, I have changed it to MIT:
https://github.com/HelloZeroNet/ZeroHello/blob/master/template-new/js/ZeroFrame.js
