### ISSUE TITLE
Error when ContentManager doesn't return file info

### ISSUE THREAD

**Issue by splix** [HelloZeroNet/ZeroNet#250]
In following lines (UIWebscoket.py:274):

```
file_info = site.content_manager.getFileInfo(inner_path)
inner_path = file_info["content_inner_path"]
```

`.getFileInfo` could return `False` and app will throw:

```
WebSocket handleRequest error: TypeError: 'bool' object has no attribute '__getitem__' in UiWebsocket.py line 96 > UiWebsocket.py line 174 > UiWebsocket.py line 309 > UiWebsocket.py line 275
```

**Comment by Fil** [comment]
I just get a smiliar error:
` Site:113VKv..Gqm8 WebSocket handleRequest error: TypeError: 'bool' object does not support item assignment in UiWebsocket.py line 98 > UiWebsocket.py line 178 > UiWebsocket.py line 454`

The site is a ZeroBlog clone, http://127.0.0.1:43110/113VKvZjeD442BDZ2vF9aXfPnFqDJ8Gqm8/ ; I can see that when I update it locally by adding a post, the new version is not available on the zeronet proxies I have tried (for instance https://www.zeropro.xyz/113VKvZjeD442BDZ2vF9aXfPnFqDJ8Gqm8/?Post:13 ).

**Comment by HelloZeroNet** [comment]
It happens when data/users/content.json is not signed correctly and your root content.json is also missing some information (eg the ignore node)

**Comment by Fil** [comment]
too much fiddling I guess :)
Started again fom scratch and the error has disappeared

**Comment by border0464111** [comment]
> Started again fom scratch and the error has disappeared
Without a way to reproduce it, sadly This issue will hang here indefinitely :s 
Closing ?

**Comment by mishfit** [comment]
It might be worthwhile catching this particular scenario and improving logging here.

**Comment by MuxZeroNet** [comment]
It is important to detect and avoid type errors in parts responsible for loading `content.json`. Here is a related case in which type errors are discovered in FileServer code: [MuxZeroNet/Fuzzing/Fuzzing Log/ Round 1/README.md](https://github.com/MuxZeroNet/Fuzzing/blob/master/Fuzzing%20Log/Round%201/README.md#type-error)
