### ISSUE TITLE
Support for compressed Bitcoin vanity addresses

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroNet#2501]
**Is your feature request related to a problem? Please describe.**

For example, I want to have a vanity address for my site. I use some vanity generator (like VanityGen or VanitySearch) to generate it and get address and private key.

But Bitcoin has two types of classic (`1`) addresses: compressed and uncompressed. And it seems that ZeroNet only supports uncompressed version, which makes it impossible to use it with compressed vanity addresses (it is possible if you convert it to uncompressed version but this doesn't make sense because you would lose vanity prefix).

For example, let's say that I generated some compressed vanity address, for example `1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io` (it's not vanity or used on any site but just example). Its compressed private key is `L3ocupNWioTwhLgu64xcSs5mGSZEPd6LevpUMmiZ2Q8E25Pah1x9`. Based on bitaddress.org, the uncompressed version of this private key is `5KJp75PYf21fg3eb1F3BJBtq6K2QstgGnJBJXXyYGiweqq25stV`, which results in `1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d` as uncompressed address.

I can successfully use `1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d` (uncompressed address) as address of my site. Signing it with uncompressed private key works normally.

However, given that my vanity address is compressed, I want to to use it for site address. So I create site with "vanity" compressed address `1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io` in the same way as previously. But when I try to sign it, it doesn't work.

When I try to sign it with compressed private key, it results in this signing error:

```
Error signing content.json
Private key invalid! Valid signers: ['1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io'], Private key address: 1CVdzwL9c2WVEkHMmkrHS9o6CD4WQaj2iR
```

When I try it with uncompressed private key, it also results in a similar error:

```
Error signing content.json
Private key invalid! Valid signers: ['1FQbDerUcLDTDYe1FqXnQrgzww4DA7C9io'], Private key address: 1K5XQVPpdxAyBnocSp6GhqnfJ77TESQB7d
```

In this case, you can see that it detects private key's address as uncompressed version, but fails to sign it because I want to use it on compressed address.

**Describe the solution you'd like**

ZeroNet should support both compressed and uncompressed Bitcoin addresses.

**Comment by filips123** [comment]
I modified `src/Crypt/CryptBitcoin.py` to use `is_compressed=True` in `privatekeyToAddress` and `sign` function, then sign site using uncompressed version of private key, and it worked. However, now uncompressed address can't be signed.

Is there any way to support both addresses? Maybe first try to sign with uncompressed address and then compressed? Any better solution?

**Update:** Based on [this Bitcointalk message](https://bitcointalk.org/index.php?topic=129652.msg1384929#msg1384929), the difference between compressed and uncompressed *private* key is "a flag bit to the base58 encoding of the private key, notifying the importer whether or not to use the compressed public keys." So, if ZeroNet could detect this flag, it could determine if this is compressed or uncompressed key and then correctly use `is_compressed` argument.

[Also](https://bitcointalk.org/index.php?topic=129652.msg1687617#msg1687617), "to create the WIF, suitable for importing later, you take the 32 byte binary private key, prepend the 0x80 bytes, and append the 0x01 flag for compression, then run through base58encode and the output is the WIF.  For reference, to create an uncompressed WIF, just don't append the 0x01 before encoding." This probably means that `sslcrypto` needs to be updated to handle this `0x01` flag and ZeroNet to correctly use it? @imachug

**Comment by HelloZeroNet** [comment]
Btw as far as I know vanitygen only supports/generated uncompressed addresses.

**Comment by filips123** [comment]
But there is also VanitySearch which by default searches compressed addresses.
