### ISSUE TITLE
What is the algorithm for forward-hashing site addresses on a blocklist?

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2505]
I never got a hint at what it ended up being. I want to hash these addresses sooner than later.

Is it documented anywhere?

Also, you need to link to the documentation site on ZeroHello.

**Comment by purplesyringa** [comment]
You can use `"0x" || sha256(address)` instead of the site address, e.g. `0xf69941233e191d9e00f0cd16c5da10b0124d1c0a498b5ecfa1448b21a3eb0094` instead of `1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D`.

**Comment by styromaniac** [comment]
> You can use `"0x" || sha256(address)` instead of the site address, e.g. `0xf69941233e191d9e00f0cd16c5da10b0124d1c0a498b5ecfa1448b21a3eb0094` instead of `1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D`.

Give me a full example blocklist entry.

Edit: Ohh. I see the pattern. 0x(sha256checksum) without the parenthesis, right? So f69941233e191d9e00f0cd16c5da10b0124d1c0a498b5ecfa1448b21a3eb0094 becomes 0xf69941233e191d9e00f0cd16c5da10b0124d1c0a498b5ecfa1448b21a3eb0094

**Comment by purplesyringa** [comment]
Exactly, the `"0x" || sha256(address)` is a well-known (hopefully) pseudocode for "concatenate string 0x with the sha256-hash of address".

**Comment by styromaniac** [comment]
> Exactly, the `"0x" || sha256(address)` is a well-known (hopefully) pseudocode for "concatenate string 0x with the sha256-hash of address".

I speak Layman's English though. LOL
