### ISSUE TITLE
[enhancement]: show size of webpages on info cards

### ISSUE THREAD

**Issue by star-buck** [HelloZeroNet/ZeroNet#251]
like showing "number of people distributing website", maybe the info on how big each website is could be added as important info on main page cards, so people know approx. how much space is taken per website

**Comment by border0464111** [comment]
Number of peers for each site is now shown on the left of front page. Site size and others storage info can be seen on "files" tab. 

This enhancement have been successfully implemented.

**Comment by HelloZeroNet** [comment]
Site size is also visible if you choose "Order by site size" on ZeroHello
