### ISSUE TITLE
Generate QR codes for sites by default

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2511]
I recommend to generate QR codes for the site addresses as default. We can save them along with index.html which generated after `siteCreate`. 

What you think @imachug @filips123 @HelloZeroNet ? 

It would be more useful than just print the "Hello [site address]"

https://github.com/lincolnloop/python-qrcode :thinking:

**Comment by purplesyringa** [comment]
You can always generate a QR code from a link, ZeroNet sites are no different from clearnet sites in this point. I think this only makes sense in case we add something else to the links, e.g. we could share peer list (*and* this is quite useful if you, say, want to share a zite with your neighbour so the peers are still available).

**Comment by ghost** [comment]
I not referring to URL like 127.0.0.1:43110/1BTCaddressalsoURL , **I referring to only the Bitcoin address** which is written to the `index.html` when `siteCreate`!

**Comment by filips123** [comment]
But what's point of this? When you start developing a site, you will most likely rewrite `index.html` and delete QR code so there is no point in generating QR code. But you can always manually create QR code, and site developer can also do this if he wants.

**Comment by purplesyringa** [comment]
> I not referring to URL like 127.0.0.1:43110/1BTCaddressalsoURL , I **referring to only the Bitcoin address** which is written to the `index.html` when `siteCreate`!

Then I don't see how this is useful. You won't be able to use this address anyway even if you share it, perhaps sharing URL is more helpful.

**Comment by ghost** [comment]
:sob:
