### ISSUE TITLE
ZeroNet is unusable, broken, not working at all, no updates, no sites nothing

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2513]
@imachug @filips123 

Because of Tamas Kocsis @HelloZeroNet messing with people now we have a trash pile of unusable things what we call zeronet: https://github.com/HelloZeroNet/ZeroNet/issues/2512 

Because of the master_seed bullshit recently and **silently without asking anyone anything** **Tamas Kocsis changed the settings to use master_seed at all times**, resulted in an absolutely unusable ZeroNet. Congratulations you maniac idiot! 

You need to make a backup of your privatekeys and not forcing everyone for your stupid master_seed!!!! Those who want to turn it off master_seed will have a big mess in users.json and will result in failure and error messages and ultimately ZeroNet can't be used anymore. 

**According to GPLv3 license you can't implement any kind of restriction in the software which makes it unusable**, which is exactly what happened. Turning off master_seed in config will result in an unusable ZeroNet, **even siteSign will fail!**

**Comment by ghost** [comment]
# @filips123 :middle_finger: :kissing_heart:  :rofl:

**Comment by purplesyringa** [comment]
> According to GPLv3 license you can't implement any kind of restriction in the software which makes it unusable, which is exactly what happened. Turning off master_seed in config will result in an unusable ZeroNet, even siteSign will fail!

Sidenote: this is not a restriction, moreover, `master_seed` is enabled by default so users who don't mess up with options won't get broken files. Your point is similar to "running `rm -rf --no-preserve-root /` broke my computer, it's because the developers added `--no-preserve-root` option".

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?
