### ISSUE TITLE
Horrendous Performance Regression with "OWNED SITES"

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2516]
This was the reason why The Eternal Word *was* slow on my devices, because of this: If I say this is my site, then the site will be slow.

http://127.0.0.1:43110/1Mjd9zn88kNX1QEkFaq2MrWeMthnR15Fga/

You might need to grab the package from its GitHub site to try.

https://github.com/PR0M3TH3AN/eternal-word

Whatever is doing this, I want it to be turned off or set to a much lower polling rate.

**Comment by rllola** [comment]
Hey styromaniac!

I am a bit confuse what is this site doing ? Is it yours ?

I notice there is some dependencies loaded from other sites (like google fonts) and a tracker... I don't think it is good practice. 

Make me wonder do we have something to track stuffs being downloaded from clearnet ?

**Comment by styromaniac** [comment]
> Hey styromaniac!
> 
> I am a bit confuse what is this site doing ? Is it yours ?
> 
> I notice there is some dependencies loaded from other sites (like google fonts) and a tracker... I don't think it is good practice.
> 
> Make me wonder do we have something to track stuffs being downloaded from clearnet ?

I didn't create the site. I only published it. The external resources are not entirely of the matter, but you are somewhat correct. It's one of the issues.

**Comment by ghost** [comment]
@rllola 
> I notice there is some dependencies loaded from other sites (like google fonts) and a tracker... I don't think it is good practice.

@styromaniac 
> The external resources are not of the matter, but I understand you don't like external resources.

I don't like external resources. :rofl: 
Personally I think this has something to do with UI. :thinking:

**Comment by rllola** [comment]
> I didn't create the site. I only published it. The external resources are not entirely of the matter, but you are somewhat correct. It's one of the issues.

I see :thinking: . So the issue affect a site that user own. I can investigate that. Could you point me which version of ZeroNet you are using ?

**Comment by styromaniac** [comment]
> > I didn't create the site. I only published it. The external resources are not entirely of the matter, but you are somewhat correct. It's one of the issues.
> 
> I see  . So the issue affect a site that user own. I can investigate that. Could you point me which version of ZeroNet you are using ?

Rev4473 Py3 on Linux and Android

**Comment by ghost** [comment]
Try this: http://127.0.0.1:43110/raw/1Mjd9zn88kNX1QEkFaq2MrWeMthnR15Fga/
If its good, you need a reverse proxy to http://127.0.0.1:43110/raw/1Mjd9zn88kNX1QEkFaq2MrWeMthnR15Fga/ from your domain.tld and that's all. 

> Rev4473 Py3 on Linux and Android

:astonished: Termux? :rofl:

**Comment by styromaniac** [comment]
> Try this: http://127.0.0.1:43110/raw/1Mjd9zn88kNX1QEkFaq2MrWeMthnR15Fga/

No change in performance.

>  Termux?

There's a newer Android app out there for ZeroNet.

**Comment by ghost** [comment]
> There's a newer Android app out there for ZeroNet.

Seriously? Direct link to apk please. I run Lineage OS, so no Google Play, or even YouTube for that matter.

**Comment by HelloZeroNet** [comment]
Thanks for reporting it happens because it checks the signed files modified status on owned site load.
https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/Ui/UiWebsocket.py#L1031

Which can be slow for many files. Working on fix...

**Comment by HelloZeroNet** [comment]
It should be fixed in Rev4478: https://github.com/HelloZeroNet/ZeroNet/commit/ad3920b26a50f4eaaa674d62531bd365c8ce1a0c

**Comment by styromaniac** [comment]
> > There's a newer Android app out there for ZeroNet.
> 
> Seriously? Direct link to apk please. I run Lineage OS, so no Google Play, or even YouTube for that matter.

https://github.com/canewsin/ZeroNet/releases/tag/android-v0.4.8

**Comment by styromaniac** [comment]
> It should be fixed in Rev4478: [ad3920b](https://github.com/HelloZeroNet/ZeroNet/commit/ad3920b26a50f4eaaa674d62531bd365c8ce1a0c)

Seems like it. It certainly isn't hanging as much anymore. TEW just happens to still be slow on my phone even when not marked as owned, but no horrible hangs anymore yet. ZeroMe Luna (my site) is now working 100% for me.

TEW might prove itself as the most taxing site on ZeroNet, so it might be useful for finding ZeroNet's bottlenecks.

**Comment by styromaniac** [comment]
I'm not sure it was fixed yet. Still very slow.

**Comment by HelloZeroNet** [comment]
Only when it's marked as owned or anyway?

**Comment by styromaniac** [comment]
Both. ZeroNet is slow with other owned sites, but is the worst with TEW, owned or not.

ZeroNet needs to optimized for sites like TEW (26K+ files) and owned sites.
