### ISSUE TITLE
Debian cleared (removed) all modules! ZeroNet broken by Debian! Python 3.8

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2517]
After apt update && apt update && apt autoremove --purge on Debian removed all requirements! I have that feeling that is related to Python 3.8... 

@imachug @HelloZeroNet @filips123 

- Starting ZeroNet...
[09:26:06] PluginManager Plugin Bigfile load error: ModuleNotFoundError: No module named 'merkletools' in PluginManager.py line 138 > Bigfile/__init__.py line 1 > Bigfile/BigfilePlugin.py line 20
[09:26:06] PluginManager Plugin CryptMessage load error: ModuleNotFoundError: No module named 'base58' in PluginManager.py line 138 > CryptMessage/__init__.py line 1 > CryptMessage/CryptMessagePlugin.py line 7 > CryptBitcoin.py line 12 > __init__.py line 4 > 1 > aes.py line 4 > __init__.py line 2 > ecc.py line 4 > _ecc.py line 4
[09:26:06] - Version: 0.7.1 r4473, **Python 3.8.2** (default, Apr  1 2020, 15:52:55) 
[GCC 9.3.0], Gevent: 1.4.0
[09:26:06] - Unhandled exception: No module named 'base58'
Traceback (most recent call last):
  File "zeronet.py", line 17, in main
    main.start()
  File "/opt/zeronet/src/main.py", line 602, in start
    actions.call(config.action, action_kwargs)
  File "/opt/zeronet/src/main.py", line 133, in call
    back = func(**kwargs)
  File "/opt/zeronet/src/main.py", line 141, in main
    from Ui import UiServer
  File "/opt/zeronet/src/Ui/__init__.py", line 1, in <module>
    from .UiServer import UiServer
  File "/opt/zeronet/src/Ui/UiServer.py", line 10, in <module>
    from .UiRequest import UiRequest
  File "/opt/zeronet/src/Ui/UiRequest.py", line 14, in <module>
    from User import UserManager
  File "/opt/zeronet/src/User/__init__.py", line 1, in <module>
    from .User import User
  File "/opt/zeronet/src/User/User.py", line 9, in <module>
    from Crypt import CryptBitcoin
  File "/opt/zeronet/src/Crypt/CryptBitcoin.py", line 12, in <module>
    from lib import sslcrypto
  File "/opt/zeronet/src/lib/sslcrypto/__init__.py", line 4, in <module>
    from .openssl import aes, ecc, rsa
  File "/opt/zeronet/src/lib/sslcrypto/openssl/__init__.py", line 2, in <module>
    from .ecc import ecc
  File "/opt/zeronet/src/lib/sslcrypto/openssl/ecc.py", line 4, in <module>
    from .._ecc import ECC
  File "/opt/zeronet/src/lib/sslcrypto/_ecc.py", line 4, in <module>
    import base58
ModuleNotFoundError: No module named 'base58'
---
Please report it: https://github.com/HelloZeroNet/ZeroNet/issues/new?assignees=&labels=&template=bug-report.md

**Comment by filips123** [comment]
What was the output of `apt autoremove --purge`?

**Comment by ghost** [comment]
@filips123 

I cleaned the system after that so I have absolutely no logs whatsoever. I use [BleachBit](https://www.bleachbit.org/) version 3.9.0 to clean the system. I do remember a lot of python related package has been removed. 

Now I did a pip3 install -r requirements.txt here is the output: 

Ignoring gevent: markers 'python_version < "3.8"' don't match your environment
Collecting gevent>=1.5.0a2
  Downloading gevent-1.5.0-cp38-cp38-manylinux2010_x86_64.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 737 kB/s 
Requirement already satisfied: msgpack>=0.4.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.6.2)
Collecting base58
  Downloading base58-2.0.0-py3-none-any.whl (6.0 kB)
Collecting merkletools
  Downloading merkletools-1.0.3.tar.gz (8.3 kB)
Collecting rsa
  Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: PySocks>=1.6.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (1.6.8)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8)) (0.4.2)
Requirement already satisfied: websocket_client in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (0.53.0)
Collecting gevent-ws
  Downloading gevent_ws-2.0.8-py3-none-any.whl (6.1 kB)
Collecting coincurve
  Downloading coincurve-13.0.0-cp38-cp38-manylinux2010_x86_64.whl (517 kB)
     |████████████████████████████████| 517 kB 870 kB/s 
Requirement already satisfied: maxminddb in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (1.4.1)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/lib/python3/dist-packages (from gevent>=1.5.0a2->-r requirements.txt (line 2)) (0.4.15)
Collecting pysha3>=1.0b1
  Downloading pysha3-1.0.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 769 kB/s 
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from coincurve->-r requirements.txt (line 11)) (0.24.0)
Collecting cffi>=1.3.0
  Downloading cffi-1.14.0-cp38-cp38-manylinux1_x86_64.whl (409 kB)
     |████████████████████████████████| 409 kB 864 kB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 716 kB/s 
Building wheels for collected packages: merkletools, pysha3
  Building wheel for merkletools (setup.py) ... done
  Created wheel for merkletools: filename=merkletools-1.0.3-py3-none-any.whl size=5909 sha256=cd33b4d41363c49d4d592a6e26102d5b2e80c95d21c1955db175a9a2afe0e70c
  Stored in directory: /root/.cache/pip/wheels/b3/86/d3/3314b01697d92937a60e9d178f19cb640ac92041d3cfd55ae6
  Building wheel for pysha3 (setup.py) ... done
  Created wheel for pysha3: filename=pysha3-1.0.2-cp38-cp38-linux_x86_64.whl size=151951 sha256=c2dd379a6e090839d34a14c8faf81341438895cde5eb84fdf009e39a5903bee8
  Stored in directory: /root/.cache/pip/wheels/ee/35/47/386d23587167a3b03fc702b6be1ff60c92fddbeef125873088
Successfully built merkletools pysha3
Installing collected packages: gevent, base58, pysha3, merkletools, rsa, gevent-ws, pycparser, cffi, coincurve
  Attempting uninstall: gevent
    Found existing installation: gevent 1.4.0
    Not uninstalling gevent at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'gevent'. No files were found to uninstall.
Successfully installed base58-2.0.0 cffi-1.14.0 coincurve-13.0.0 gevent-1.5.0 gevent-ws-2.0.8 merkletools-1.0.3 pycparser-2.20 pysha3-1.0.2 rsa-4.0


notice **Not uninstalling gevent at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'gevent'. No files were found to uninstall.**

**Comment by filips123** [comment]
Did you initially install dependencies with APT or pip? Also, did you updated from Python 3.7 (or some older version) to 3.8?

If you updated Python, your dependencies from previous Python version were not transferred to 3.8. Then BleachBit probably recognized them as unimportant and deleted them.

And your problem with Gevent is similar to [this](https://askubuntu.com/questions/797058/not-uninstalling-paramiko-at-usr-lib-python2-7-dist-packages-outside-environme). It probably means that you installed Gevent with `apt install python3-gevent` and not with pip. Because of that, pip can't update it. To update all dependencies successfully with pip, you first need to remove all APT-installed dependencies (`apt remove python3-gevent`) and then run pip.

**Comment by ghost** [comment]
apt update && apt full-upgrade && apt autoremove --purge && apt autoclean && apt clean
Pretty much updating from python 3.7 to 3.8 and yes it is possible I did installed requirements using apt. Maybe even better to do that than using pip.

**Comment by ghost** [comment]
**apt remove --purge python3-gevent**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-aiodns python3-greenlet python3-ipykernel python3-jupyter-client python3-jupyter-core python3-nbformat python3-plotly python3-pycares python3-retrying python3-texttable python3-zmq
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  python3-gevent* python3-grequests* theharvester*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 8,274 kB disk space will be freed.
Do you want to continue? [Y/n]

**Comment by filips123** [comment]
Yes, you should uninstall Gevent from APT and install it using pip. Problem is that Gevent from APT does not have 1.5.0, which is the only version which supports Python 3.8.

**Comment by ghost** [comment]
@filips123 The problem is that I do use **the Harvester** which you guessed it, use **python3-gevent** https://github.com/laramies/theHarvester

**Comment by filips123** [comment]
Then you either need to:

* Install ZeroNet in virtualenv and keep the Harvester and Gevent from APT, or
* Remove the Harvester and Gevent from APT, install them [from source](https://github.com/laramies/theHarvester/wiki/Installation) and install Gevent for ZeroNet using pip.

**Comment by ghost** [comment]
**ZeroNet never works from virtualenv, I tried also in venv** 

> which is the only version which supports Python 3.8

Not true. I can use ZeroNet with gevent 1.4.0-1.1 in Python 3.8

**Comment by filips123** [comment]
> ZeroNet never works from virtualenv, I tried also in venv

This is not true.

> I can use ZeroNet with gevent 1.4.0-1.1 in Python 3.8

Yes, it installs correctly. But does it actually works when you try to use it in ZeroNet?

**Comment by ghost** [comment]
Yes, it works.

**Comment by ghost** [comment]
thank you @filips123 I close this now
