### ISSUE TITLE
Tamas Kocsis is a piece of shit! WORSE he is a the most disgusting human being! 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2525]
@imachug @filips123 Look at this fucking retard! Closed again: https://github.com/HelloZeroNet/ZeroNet/pull/2522 

@HelloZeroNet reopen the pull request and merge it you retarded shit!

**Comment by HelloZeroNet** [comment]
Please fork the project, so you can merge your commits there.

**Comment by ghost** [comment]
You're a fucking idiot man!

**Comment by ghost** [comment]
I will never request to merge anything just to make your face more shiny before girls who sucking your dick after TED talks. ZeroNet is not successful because of you and your attitude. Shame on you I hope other contributors will stop contributing to your shit. Yes, I take the source code and will distribute it without even mentioning your name you fuck. How many of my pull request you have closed? You are disgusting boy!
