### ISSUE TITLE
Shame on you! ZeroNet is not successful because of you! 

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2526]
@imachug @filips123 this @shortcutme guy should be kicked out of this project, at least need to call contributors to use a different repository! 

I will never request to merge anything just to make your face more shiny before girls who sucking your dick after TED talks. ZeroNet is not successful because of you and your attitude. Shame on you I hope other contributors will stop contributing to your shit. Yes, I take the source code and will distribute it without even mentioning your name you fuck. How many of my pull request you have closed? You are disgusting boy!

https://github.com/HelloZeroNet/ZeroNet/issues/2525

**Comment by HelloZeroNet** [comment]
Sorry, I won't accept PR from you, hope you understand.

Please fork the project already and make it successful!

**Comment by ghost** [comment]
get a grip on yourself @shortcutme @HellZeroNet 
# :vomiting_face:
