### ISSUE TITLE
Kabd be a faszom te gyoker, en tudok magyarul, mit gondolsz te egyedul vagy a vilagon? xD

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2527]
Ej ej ej kicsihajo a Duna feneken :rofl:

**Comment by ghost** [comment]
Meg barataid se maradnak ha ennyire nagyaratardod magad te huje... En segiteni akartam. 

In the end you will have no friends, I wanted to help you idiot. (approx translation)

**Comment by HelloZeroNet** [comment]
I don't mind, please mind your own business.
