### ISSUE TITLE
Please ask the user if they want to delete the site private key from users.json while deleting the site from their device

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2534]
I can no longer update ZeroMe Luna now. This is the reason: The user is not informed on private key deletion, and it's not optional.

This isn't wise to assume the user would know the effect and to not provide a choice for or against that.

**Comment by styromaniac** [comment]
I've recovered the private key, so don't feel bad. Just better inform the user and make private key deletion an explicit choice.

**Comment by HelloZeroNet** [comment]
What you mean by private key deletion?

**Comment by styromaniac** [comment]
> What you mean by private key deletion?

Deleting a site you own deletes the site private key from users.json on the same device.

**Comment by styromaniac** [comment]
Maybe it shouldn't delete the key at all since there is an option on the sidebar anyway.

**Comment by HelloZeroNet** [comment]
Thanks for the suggestion, in Rev4493 I have added a notification about private key deletion on site delete:

https://github.com/HelloZeroNet/ZeroNet/commit/4eb50377c387743df2bf0c93fbd35d63a9661aea
