### ISSUE TITLE
Downloads still don't resume unless ZeroNet is restarted.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2535]
When watching a documentary, if I leave the apartment (internet disconnects), then I can't get ZeroNet to resume downloading the video unless I restart ZeroNet.

This is one of the biggest annoyances about ZeroNet.

**Comment by HelloZeroNet** [comment]
Does the sited get updated when you back online?

**Comment by styromaniac** [comment]
> Does the sited get updated when you back online?

Only on restart. Maybe after a long wait it might also, but I'm not sure.

Even if it's just a need to update the site in question, that's not clear to the user, so auto-update all sites when the internet connection resumes.

**Comment by styromaniac** [comment]
Hmm. Restarting ZeroNet in fact doesn't resume downloads. Oops.

How would we solve this?
