### ISSUE TITLE
Compatibility of other plugins (UiPluginManager) with MergerSite

### ISSUE THREAD

**Issue by filips123** [HelloZeroNet/ZeroNet#2540]
**Is your feature request related to a problem? Please describe.**

Based on MergerSite's source code, the plugin only modified some of WebSocket actions to correctly resolve `merged-` paths and changes a few other (unrelated to this) methods for correct handling of paths and site updates.

However, UiPluginManager uses `site.storage.loadJson` and to check plugin info and directly copies plugin from `inner_path`. This makes it impossible to correctly load plugin from another merged site. Loading plugins in a such way would be very useful in (currently unexisting) "plugin store" sites, where each plugin could be hosted on separate merged site.

Additionally, I'm also developing my own plugin that would similarly need to access files from merged sites. More specifically, it would need to resolve `inner_path` (if it is `merged-` path), separate it into site address and actual `inner_path` and then use those two variables for accessing/working with files.

**Describe the solution you'd like**

I think that a good way of doing this would be to somehow expose [`checkMergerPath`](https://github.com/HelloZeroNet/ZeroNet/blob/py3/plugins/MergerSite/MergerSitePlugin.py#L31-L52) from MergerSite plugin to other plugins. Then, both UiPluginManager and my plugin could use that function to site address and `inner_path` from it and use them for handling files.

**Comment by filips123** [comment]
I think I know how could I implement this and will try to create PR tommorow.

**Comment by HelloZeroNet** [comment]
I have not tested, but using the "as" command should work: `Page.cmd("as", [mergedsiteaddres, "PluginAddRequest", "plugindirectory"])`

**Comment by filips123** [comment]
Yes, this should probably work, but it is not documented anywhere. ZeroFrame documentation just lists `as` as admin command without any mention that it works with merged sites.

**Comment by nomagics** [comment]
don't waste your time @filips123 I for example don't even ever used merger. For that matter the plugin is disabled and removed completely in my fork. (Not public yet)

**Comment by filips123** [comment]
> I for example don't even ever used merger

Sure, if you don't need that plugin don't use it...

**Comment by nomagics** [comment]
Be honest with you, I don't even use ZeroNet because I created a new software based on ZeroNet, I renamed and changed a lot of things to make it better. I will son upload it to the Free Software Foundation's website and distribute it there instead on shitty GitHub..

**Comment by HelloZeroNet** [comment]
Thanks for the idea, I have changed the `as` command documentation to make it clear that it works with CORS/MergerSite plugin as well: https://zeronet.io/docs/site_development/zeroframe_api_reference/#as

**Comment by filips123** [comment]
Thanks! I'm will close this issue because using `as` command should work.

Can you also check if there are some other commands that are listed as ADMIN while they also work with CORS/MergerSite plugin and mark them if needed?
