### ISSUE TITLE
all.js didn't load in Firefox Nightly when UiPassword enabled

### ISSUE THREAD

**Issue by earthengine** [HelloZeroNet/ZeroNet#2544]
### My Environment
  * ZeroNet version: 0.7.1 (rev4206)
  * Operating system: Windows
  * Web browser: Firefox Nightly 77.0a1 (2020-04-30)
  * Tor status: not available
  * Opened port: yes
  * Special configuration: UiPassword Turned on

### The problem:
When the UiPassword turned on, the login form will set a session cookie. Firefox Nightly downloads the all.js file, but later when it opens the websocket it violates the Content Security Policy set by Mozilla.

Chrome  81.0.4044.129 instead, shows a warning message in the delovper console:

>A cookie associated with a cross-site resource at http://127.0.0.1/ was set without the `SameSite` 
> attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are 
> set with `SameSite=None` and `Secure`. You can review cookies in developer tools under 
> Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

#### Steps to reproduce:

  1. Download and install the given version of Firefox
  2. Download and install ZeroNet
  3. Enable plugin UiPassword
  4. Open http://127.0.0.1:43110 in Firefox and enter the password

#### Observed Results:
A blank page with only the ZeroNet icon in the right top corner.

#### Expected Results:
A fully functional page like in Chrome  81.0.4044.129.

**Comment by earthengine** [comment]
Firefox Nightly didn't allow sessions tracking in a HTTP site, even it is in localhost. To workaround, people need to use [local-ssl-proxy](https://www.npmjs.com/package/local-ssl-proxy) or similar.

ZeroNet should consider provide things like that out of box.

**Comment by HelloZeroNet** [comment]
Thanks for the tip, creating a self-signed ssl could be a solution or by using letsencrypt + dyndns-like service.

Unfortunately we have seen various issue with cookie based authentication + sandboxed iframes: eg. css font file requests are called without any cookies, so some alternative would be nice, eg. ssl cert based authentication.

**Comment by filips123** [comment]
Why Multiuser plugin, which also uses a cookie, works but UiPassword doesn't?

**Comment by HelloZeroNet** [comment]
Because in the Multiuser plugin we only use the cookie when we load the wrapper html and for the websocket connection, which booth outside of the iframe.

Actually we could do the same for the Multiuser plugin, but then it could be possible to read static files without authentication. As a partial workaround for the problem we could combine the cookie based authentication with IP based white listing: 

for wrapper and websocket (both outside of iframe) we require cookie auth, when the cookie found we add the requester client's ip (and maybe user agent as well) to a white list and then we allow static file requests from this ip even without auth cookie for some hours.

**Comment by HelloZeroNet** [comment]
I have implemented this workaround in Rev4485, please check if it's works for you: https://github.com/HelloZeroNet/ZeroNet/commit/36d96d484ed8dc3370c2dab9b50b714af702a2c4

A site to test css font load / fetch api: http://127.0.0.1:43110/1N12YHEhrB2QjMmh2NUHqEuE6ffC7JEiB7

**Comment by earthengine** [comment]
@HelloZeroNet I have tried your workaround and get errors:

```
Err: AttributeError: 'UiRequest' object has no attribute 'isWrapperNecessary' in UiServer.py line 106 > UiPassword/UiPasswordPlugin.py line 67 > UiRequest.py line 163 > UiPluginManager/UiPluginManagerPlugin.py line 33 > UiPassword/UiPasswordPlugin.py line 70
```

I think there are other changes needed - I am running a stable version.

(I do cloned and developed the github PR, but I didn't do distribution tests - I only test updating the UiPasswordPlugin.py in my Zeronet folder, and apply the change in the git repo, I don't know how to use a Github version in windows)

**Comment by HelloZeroNet** [comment]
Yeah, you also need to update src/Ui/UiRequest.py: https://github.com/HelloZeroNet/ZeroNet/commit/07faa3d6d3bd8f6c786d2345ed232740936cd32a

**Comment by earthengine** [comment]
Hi @HelloZeroNet 

I confirmed that your fixes works by patching my stable release with those commits.

- The test site shows the proper result: the fonts were loaded.

![image](https://user-images.githubusercontent.com/2227031/82315452-aa8fec80-9a0e-11ea-8688-1657829e8e55.png)
(test result of Firefox Nightly 78.0a1 (2020-05-18) (64-bit))

Cheers.

**Comment by HelloZeroNet** [comment]
Thanks for testing!

**Comment by earthengine** [comment]
Although this is closed but I got to inform that there is one remaining issue of the commit on [36d96d4](https://github.com/HelloZeroNet/ZeroNet/commit/36d96d484ed8dc3370c2dab9b50b714af702a2c4). This bug causes 

```
Server error
Err: AttributeError: 'UiRequest' object has no attribute 'cleanup' in UiServer.py line 106 > UiPassword/UiPasswordPlugin.py line 61
```
when the session was expired. The fix is to change the code in line 61 from

```python
self.cleanup()
```
to
```python
self.sessionCleanup()
```
It is late for my day, so I leave this fix with you.

**Comment by HelloZeroNet** [comment]
Yeah it was fixed in Rev4486: https://github.com/HelloZeroNet/ZeroNet/issues/2544#issuecomment-630798932
