### ISSUE TITLE
Err: AttributeError: 'UiRequest' object has no attribute 'cleanup' in UiServer.py

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2549]
### Step 1: Please describe your environment

  * ZeroNet version: r4485
  * Operating system: Raspbian
  * Web browser: FF beta
  * Special configuration: UIpassword

### Step 2: Describe the problem:

i seen this error when opening a zite. i seen it also on next zeronet start (after some time passed)

"Server error
Err: AttributeError: 'UiRequest' object has no attribute 'cleanup' in [UiServer.py](https://github.com/HelloZeroNet/ZeroNet/search?q=UiServer.py&unscoped_q=UiServer.py) line 118 > UiPassword/[UiPasswordPlugin.py line 61](https://github.com/HelloZeroNet/ZeroNet/blob/0a9391d28bf6c133d634913a5ed58b6568c10f0b/plugins/disabled-UiPassword/UiPasswordPlugin.py#L61)"

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in Rev4486: https://github.com/HelloZeroNet/ZeroNet/commit/8db4344171ccda541a38013b85ea19ede1e14604
