### ISSUE TITLE
Web push notifications

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#255]
https://blog.mozilla.org/blog/2016/01/25/firefox-can-now-get-push-notifications-from-your-favorite-sites/
Is it possible to add an API to allow authorized sites to use push notifications?

**Comment by HelloZeroNet** [comment]
serviceworkers does not works within sandboxed iframe. it can be implemented in zeronet to display newsfeed events, but its still an expermiental technology, so maybe later when it's become more mature

**Comment by TheNain38** [comment]
Yeah, I though too that it would be cool implementing it when it would be more mature, I opened this is as a reminder

**Comment by purplesyringa** [comment]
@HelloZeroNet This is now implemented. Can we close this?
