### ISSUE TITLE
UiWSGIHandler websocket error: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by gqgs** [HelloZeroNet/ZeroNet#2557]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 rev4486
  * Web browser: Chrome

### Step 2: Describe the problem:

`UiWSGIHandler websocket error: TypeError: 'NoneType' object is not iterable in UiServer.py line 50 > pywsgi.py line 924 > __init__.py line 266`

#### Steps to reproduce:

1. Use the `BigfileUploadInit` command to upload a file using the protocol "websocket"

#### Observed Results:

The file is uploaded correctly but the error above occurs after `actionBigfileUploadWebsocket` finishes processing the requests.

It seems `self.result` is still uninitialized when this method is being invoked but I didn't look too much into it.
https://github.com/HelloZeroNet/ZeroNet/blob/eeb48fc72e14ae2055cb2608bb838bd77edf21c3/src/lib/gevent_ws/__init__.py#L263-L269

In the browser the websocket logs the following error:
`One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1`

#### Expected Results:

The command to be executed without errors.

**Comment by purplesyringa** [comment]
Can you reproduce the bug if you replace lines 266 and 267 with `pass`?

**Comment by gqgs** [comment]
@imachug It seems that is enough to fix it. Everything is working fine and without errors if I don't close the websocket.
However, if I close it I'm getting another error after the first successful upload and the subsequent uploads get corrupted.
`UiWSGIHandler websocket error: EOFError:  in UiServer.py line 50 > pywsgi.py line 923 > UiServer.py line 115 > UiRequest.py line 155 > Bigfile/BigfilePlugin.py line 92 > 101 > 318 > 294 > 268 > 88 > __init__.py line 92`

Am I really expected to never manually close the connection?

**Comment by purplesyringa** [comment]
No idea, this code used to work. You *should* close the connection after uploading all the data. Could you, by any chance, use the same socket for several files or something like that?

**Comment by gqgs** [comment]
I don't think so. A new websocket object is being created for each file so I also think it's strange that they are interfering with each other. I will look into it.

Anyway, I think #2558 should fix the original problem.
