### ISSUE TITLE
When clicking on ZeroNet trayicon, or when auto opening browser when Launching ZeroNet it redirects to old ZeroHello site

### ISSUE THREAD

**Issue by TheNain38** [HelloZeroNet/ZeroNet#256]

**Comment by HelloZeroNet** [comment]
the browsers are caching redirects, you have to clear cache to make it forget the old address: http://superuser.com/questions/304589/how-can-i-make-chrome-stop-caching-redirects

**Comment by HelloZeroNet** [comment]
Added a workaround to this problem by opening directly the site when clicking on the trayicon
