### ISSUE TITLE
Don't let the bullies get to you, Nofish. They're after us all. They have nothing to live for but to cause hurt.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2567]
They're after me too. It's because they want to emotionally exhaust important members of ZeroNet one-by-one.

http://127.0.0.1:43110/Talk.ZeroNetwork.bit/?Topic:1590345225_14X7YqX1gTpjnnsLEbLfk1V3Wjs8tNztaA/Styromaniac

**Comment by HelloZeroNet** [comment]
I'm fine, just having a side-project that takes much more time than I expected :)
