### ISSUE TITLE
Add an auto sign & publish option.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2569]
I have an app to automatically update the trackers list for Syncronite. I want an optional feature to sign and publish automatically when a change to the file(s) is detected, so then I don't have to sign and publish manually.

This way, updates to the trackers list happen as soon as possible.

**Comment by styromaniac** [comment]
I've figured out how to automate all of this already and I don't think this feature request is important anymore.

**Comment by HelloZeroNet** [comment]
Yeah probably it's easier to do with a simple bash script:

```
#!/bin/bash
while true; do

inotifywait -e modify,create,delete,move -r /path/to/your/dir && \
python3 zeronet.py siteSign address --publish
done
```

**Comment by styromaniac** [comment]
curl "https://ngosang.github.io/trackerslist/trackers_all_ip.txt" > /home/styromaniac/ZeroNet-linux-dist-linux64/data/15CEFKBRHFfAP9rmL6hhLmHoXrrgmw4B5o/cache/1/_h_.html
/home/styromaniac/ZeroNet-linux-dist-linux64/ZeroNet.sh siteSign 15CEFKBRHFfAP9rmL6hhLmHoXrrgmw4B5o
/home/styromaniac/ZeroNet-linux-dist-linux64/ZeroNet.sh sitePublish 15CEFKBRHFfAP9rmL6hhLmHoXrrgmw4B5o

I just use the above in an sh file, with crontab repeating the script at 6:20pm EDT.

**Comment by styromaniac** [comment]
I'm thinking now that this would be a nice feature for those who don't know how to create a programmatic sh file, such as myself. I don't understand programmatic code examples unless it's including text from my use case.

Mirroring sites repeatedly in anticipation of a change would benefit from this.

I've been thinking of creating a pornsters blocklist that copies ssdifnskdjfnsdjk's blocklist's users.json and only publishing if a change is detected. The reason is that I don't agree with his sites.json entries not being hashed on a potentially illegal basis, and that porn sites are easily avoidable anyway.
