### ISSUE TITLE
ZeroNet doesn't warn of seeded sites SHA-256 summed on blocklist.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2571]
I have the fake spammer blocklist seeded. This is on my blocklist (MOAB) via SHA-256 checksum. I'm not warned that I'm seeding the site.

**Comment by HelloZeroNet** [comment]
Thanks for reporting I have fixed it in Rev4493:

https://github.com/HelloZeroNet/ZeroNet/commit/79d26060b3e8184a1b16a8fd7baae6ef8710b441
https://github.com/HelloZeroNet/ZeroHello/commit/61cc9e47fee29455d9ffbf5714a1ac054267a8da

**Comment by styromaniac** [comment]
I mean ZeroHello doesn't warn you about this.

**Comment by HelloZeroNet** [comment]
Yes, I have added a notification to ZeroHello and it should warn now (also need to update the client to Rev4493)

**Comment by styromaniac** [comment]
> Yes, I have added a notification to ZeroHello and it should warn now (also need to update the client to Rev4493)

4486 is unable to upgrade to 4493 on Android. This explains why I didn't see your patch work yet.

This happened with an earlier revision as well.

See: http://127.0.0.1:43110/15UYrA7aXr2Nto1Gg4yWXpY3EAJwafMTNk/?Topic:1590525289_16NS3rBdW9zpLmLSQoD8nLTtNVsRFtVBhd/+Bug+4478+4486+revision+upgrade+not+possible
