### ISSUE TITLE
Unhandled exception: StopIteration: No more data to unpack. in greenlet.py line 766

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#2576]
### Step 1: Please describe your environment

  * ZeroNet version: 4493
  * Operating system: Linux Debian 9
  * Web browser: FF
  * special config. threads_fs_write = 4;threads_fs_read = 4

### Step 2: Describe the problem:

Three errors in the debug.log:

> Unhandled exception: StopIteration: No more data to unpack. in greenlet.py line 766 > Worker.py line 208 > 154 > Bigfile/BigfilePlugin.py line 409 > 393 > 387 > Msgpack.py line 100 > _unpacker.pyx line 562 > 489

First error in context:

> [2020-06-23 06:22:42,090] DEBUG    Site:1ADQAH..g6aA Pex result: from 2 peers got 3 new peers.
> [2020-06-23 06:22:42,093] DEBUG    Db#0:Bootstrapper New peer: b'addresshere' signed: False
> [2020-06-23 06:22:42,094] DEBUG    ConnServer Conn#2180 iphere [v2] > Announce 9 sites (onions: 1, onion_check: 0.000s, db_onion: 0.000s, db_ip: 0.000s, peerlist: 0.001s, limit: 30)
> [2020-06-23 06:22:42,172] **ERROR    - Unhandled exception: StopIteration: No more data to unpack. in greenlet.py line 766 > Worker.py line 208 > 154 > Bigfile/BigfilePlugin.py line 409 > 39$**
> [2020-06-23 06:22:42,176] DEBUG    ConnServer Conn#2182 iphere [?] > Incoming connection...
> [2020-06-23 06:22:42,303] DEBUG    ConnServer Conn#2180 iphere [v2] > Socket error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1: invalid start byte in Conn$
> [2020-06-23 06:22:42,303] DEBUG    ConnServer Conn#2180 iphere  [v2] > Closing connection: MessageLoop ended (closed: False), waiting_requests: 0, sites: 0, buff: 1...
> [2020-06-23 06:22:42,337] DEBUG    Site:1ADQAH..g6aA Retry 23632 bad files
> [2020-06-23 06:22:42,389] DEBUG    Site:1ADQAH..g6aA New downloadFile pool: len: 23415, only if bad: True
> [2020-06-23 06:22:42,424] DEBUG    Site:1ADQAH..g6aA Loaded json: 300 (latest: data/users/addresshere/content.json)
> [2020-06-23 06:22:43,328] DEBUG    ConnServer Conn#2183 iphere [?] > Incoming connection...
> [2020-06-23 06:22:43,328] DEBUG    ConnServer Conn#2183 iphere [?] > Crypt in connection using implicit SSL
> [2020-06-23 06:22:43,660] DEBUG    ConnServer Conn#2184 iphere [?] > Incoming connection...
> [2020-06-23 06:22:43,661] DEBUG    ConnServer Conn#2184 iphere [?] > Crypt in connection using implicit SSL
> [2020-06-23 06:22:44,264] DEBUG    ConnServer Conn#2182 iphere [?] > Crypt in connection using implicit SSL
> [2020-06-23 06:22:44,740] DEBUG    Site:1ADQAH..g6aA Queried hashfield from 3 peers in 2.767s
> [2020-06-23 06:22:45,820] DEBUG    - Gevent block detected: 0.150s
> [2020-06-23 06:22:45,857] DEBUG    ConnServer Conn#2185 iphere [?] > Connecting... (site: Site 1ADQAH..g6aA)
> [2020-06-23 06:22:47,083] DEBUG    ConnServer Conn#2181 iphere [v2] > Changing unpacker to bin type (unprocessed bytes: 0)
> [2020-06-23 06:22:47,687] DEBUG    Db#0:Bootstrapper Commited in 1.007s (reason: Interval)
> 

Suddenly the site mentioned in the log is unable to display any content from the DB, happen on two computers (Raspbian buster and Debian stretch). Rebuilding, reloading the site's DB and restarting ZN not helped.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/6776dabdb30307b87ad4b0667f16b0bdcf07c19a in Rev4496
