### ISSUE TITLE
Deleting file server port number from the config page makes ZeroNet unable to run.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2577]
I thought this would randomize the file server port number, but it doesn't. Instead, the user has to edit zeronet.conf to have a specific port number to make ZeroNet work again.

Rev 4493 on Linux.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/ddbd5c7b19d4c13d6369b20a41b979cde36117fd in rev4496
