### ISSUE TITLE
Unhandled exception: ModuleNotFoundError: No module named 'gevent'

### ISSUE THREAD

**Issue by theredenemy** [HelloZeroNet/ZeroNet#2580]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Windows 10
  * Web browser: Chrome
  * Tor status: not available/always/disabled
  * Opened port: yes
  * Special configuration: ____

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

Traceback (most recent call last):
  File "F:\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\zeronet.py", line 16, in main
    import main
  File "F:\ZeroNet-win-dist-win64\ZeroNet-win-dist-win64\core\src\main.py", line 9, in <module>
    import gevent
ModuleNotFoundError: No module named 'gevent'

#### Expected Results:

  * What did you expect to happen?

**Comment by HelloZeroNet** [comment]
You need to start zeronet.exe, or lib\zeronet.cmd (for command line) or install the required modules using `python3 -m pip install -r requirements.txt`
