### ISSUE TITLE
Error in Android app (rev4496)

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2583]
Unhandled exception: ValueError: unknown address family 10 in greenlet.py line 766 > Peer.py line 345 > helper.py line 140

**Comment by HelloZeroNet** [comment]
looks like the python/kernel was compiled without ipv6 support: https://github.com/svinota/pyroute2/issues/348

**Comment by canewsin** [comment]
@styromaniac upcoming version will come with ipv6 support.

**Comment by canewsin** [comment]
@HelloZeroNet you can close this, latest zeronet mobile has ipv6 support.

**Comment by HelloZeroNet** [comment]
cool, thanks

**Comment by HelloZeroNet** [comment]
cool, thanks
