### ISSUE TITLE
Switched Theme in PT-BR

### ISSUE THREAD

**Issue by mateusfg7** [HelloZeroNet/ZeroNet#2585]
**The black theme and the white theme are switched in the Portuguese language (PT-BR)**

_should be dark_
![image](https://user-images.githubusercontent.com/40613276/86786994-005e3980-c03b-11ea-87d3-84bb2bab1ad1.png)

_should be white_
![image](https://user-images.githubusercontent.com/40613276/86787087-1bc94480-c03b-11ea-8562-f155ac89c94d.png)

---

  * ZeroNet version: 0.7.1
  * Operating system: Parrot Sec 4.8
  * Web browser: Firefox 77.0
  * Tor status: disabled
  * Opened port: no

**Comment by styromaniac** [comment]
The words are switched around.

**Comment by HelloZeroNet** [comment]
Thanks for reporting it should be fixed now
