### ISSUE TITLE
Sidebar file manager

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2594]
Managing files from the site using the sidebar seems like a nice idea.

**Comment by HelloZeroNet** [comment]
Good idea, I think the it would be better to have a built-in file listing mode with editing options (copy, move, text file edit) for site admins (eg. http://127.0.0.1:43110/list/1SiteAddress) with a link to it to the sidebar.

It could be also useful if someone does not want to create index.html, just share some files. If no index.html found in the directory we could redirect to this page automatically.

**Comment by styromaniac** [comment]
A code editor would be neat! Beaker Browser has such an app and it's very convenient.

**Comment by mx5kevin** [comment]
It would be useful to connect the .json file data and the files using a progress bar and difrent colors.It could be an advanced option to all zites.All files listed in content.json It would be worth listing based on this.

Example:

File Options

Dowload file,delete file,select file with select file option as as with torrent files,pause file download,edit .json files,search files.

Files

1.Not downloaded files like gray color (using the json file file list)
2.Half finished and downloaded files what exit in the folder
3.Files what downloaded but the .json file are changed and not part of the zite anymore (using a color).This can help people to delete outdated files.

Multiple user sites like ZeroUp

Using the username@zeroid.bit: +hash using red dots or etc forward other users from whom we have downloaded something.And another users using gray color.

**Comment by HelloZeroNet** [comment]
I have added a new UiFileManager plugin that allows list, create, edit and delete site files:

![editor](https://user-images.githubusercontent.com/10350359/94179496-dc253280-fe9c-11ea-85f9-2c396e72b8a1.png)

Features: 

 - Automatically redirect to the list if there is no index.html in the directory
 - Js/html/py/coffee/go/css/rust/xml/json/markdown highlight, json validation, Sublime text like line editing, using the CodeMirror editor library
 - Add not yet downloaded optional files to the list (italic filename, gray file size text)
 - Mark new and modified, ignored files with different color (green, blue, gray background)

**Comment by styromaniac** [comment]
Can this file editor prevent a noob from messing up their files?
