### ISSUE TITLE
testing some html nd php fails

### ISSUE THREAD

**Issue by therealelyayo** [HelloZeroNet/ZeroNet#2601]
### Step 1: Please describe your environment

  * ZeroNet version: _____latest as of this post
  * Operating system: _____ubuntu 18 on azure with sudo access
  * Web browser: _____none
  * Tor status: not available/always/disabled no tor
  * Opened port: yes/no  yes
  * Special configuration: ____none

#### Steps to reproduce:

  1. _____creating a html file with this `<meta http-equiv="REFRESH" content="0; https://google.com/index.php?email=<?php echo $_GET['email']; ?>">`
  2. _____ going to it with broser
  3. _____

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?
its a simple redirect but not working

**Comment by purplesyringa** [comment]
I believe you wanted to attach an HTML file but it's missing. If you wanted to add inline code, tags might be eaten by GitHub formatting, wrap it in ``` instead (I'm using ''' to show the syntax in the example below because otherwise it thinks it's a code marker):

```
 '''html
 <b>Hello, world!</b>
 '''
```

...produces:

```html
<b>Hello, world!</b>
```

While `<b>Hello, world!</b>` without ``` produces <b>Hello, world!</b>

**Comment by HelloZeroNet** [comment]
ZeroNet does not includes php runtime, so you can't use php codes in ZeroNet sites, but you can do similar using JavaScript
