### ISSUE TITLE
ZeroNet with Tor

### ISSUE THREAD

**Issue by PMinhDuc** [HelloZeroNet/ZeroNet#2609]
![Screenshot from 2020-08-21 23-12-38](https://user-images.githubusercontent.com/62635143/90911895-d9e63900-e403-11ea-9d9b-2fc99349bed6.png)
This is what my torrc file look like and I don't know how to configure it to work with ZeroNet.

**Comment by HelloZeroNet** [comment]
You have to add

ControlPort 9051
CookieAuthentication 1

to the config and probably you also have to give read permission to the generated authentication cookie file to your client's user:

https://zeronet.io/docs/faq/#how-to-make-zeronet-work-with-tor-under-linuxmacos

**Comment by ihateiframes** [comment]
@PMinhDuc @HelloZeroNet  You should not change the torrc file for Tor Browser! Use **apt install tor** and edit the torrc file there **/etc/tor/torrc**!! In tor browser under **about:config** add the **127.0.0.1:43110** value to your "no proxy on" (with port number).

**Comment by PMinhDuc** [comment]
> @PMinhDuc @HelloZeroNet You should not change the torrc file for Tor Browser! Use **apt install tor** and edit the torrc file there **/etc/tor/torrc**!! In tor browser under **about:config** add the **127.0.0.1:43110** value to your "no proxy on" (with port number).
