### ISSUE TITLE
Zeronet Node Module

### ISSUE THREAD

**Issue by azcoppen** [HelloZeroNet/ZeroNet#261]
How feasible would it be to package Zeronet into an NPM module, like torrent-stream? (https://github.com/mafintosh/torrent-stream)

Would be very convenient to access the Zeronet network by proxy from within Node apps from a pre-packaged mod rather than just a typical GET:

e.g. app.js

var zeronet = require('zeronet');

var options = {
  host: 'somezeronetaddr.bit',
  path: '/foo.html'
};

zeronet.get(options, function(resp){
  resp.on('data', function(chunk){
    //do something with chunk
  });
}).on("error", function(e){
  console.log("Got error: " + e.message);
});

**Comment by HelloZeroNet** [comment]
NPM is for javascript, ZeroNet is written in Python, which has PIP instad of NPM. You can use `pip install -r requirements.txt` to install dependencies.
