### ISSUE TITLE
official torbrowser bundle

### ISSUE THREAD

**Issue by OrionRandD** [HelloZeroNet/ZeroNet#2612]
The official torbrowser bundle - I am using debian/linux -
does not have the fields for setting up the manual proxy 
for using zeronet.sh with it
How can I setup zeronet in this official torbrowser?
https://dist.torproject.org/torbrowser/9.5.4/tor-browser-linux64-9.5.4_en-US.tar.xz
:(

**Comment by HelloZeroNet** [comment]
I have just tested it with Tor browser 9.5.4 on Windows and it works for me after setting `no_proxies_on` to `127.0.0.1 ` on page `about:config`.

Can you access http://127.0.0.1:43110 using normal browser or by curl?

It should look like this:
```
$ curl -v http://127.0.0.1:43110
* Rebuilt URL to: http://127.0.0.1:43110/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 43110 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:43110
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 301 Redirect
< Location: /1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D
< Date: Sun, 06 Sep 2020 14:57:15 GMT
< Transfer-Encoding: chunked
<
Location changed: /1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D* Connection #0 to host 127.0.0.1 left intact
```

**Comment by OrionRandD** [comment]
Thx a lot.
Finally worked ;)
