### ISSUE TITLE
TOR issue

### ISSUE THREAD

**Issue by mpancorbo** [HelloZeroNet/ZeroNet#262]
When I set `tor = always` in my zeronet.conf file I get following error message in console:

     TorManager Tor addOnion error: 510 Unrecognized command "ADD_ONION"

The web interface works, but with lot of bugs.

Is it a bug? or... What am I doing wrong?

**Comment by HelloZeroNet** [comment]
You have to update your Tor to make it work

**Comment by mpancorbo** [comment]
Thank you!

I simply supposed that jessie provides the proper version of tor.
