### ISSUE TITLE
[CorsPlugin] Internal error: AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by scsmash3r** [HelloZeroNet/ZeroNet#2625]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1 r4206, Python 3.7.3
  * Operating system: Ubuntu 18.04.5 LTS
  * Web browser: FF 81.0
  * Tor status: always
  * Opened port: yes

### Step 2: Describe the problem:

While doing `cmd` for `corsPermission` on certain zites, wrapper notification error is shown with message:
```
Internal error: AttributeError: 'NoneType' object has no attribute 'replace'
UiWebsocket.py line 79 > UiWebsocket.py line 234 > Cors/CorsPlugin.py line 90 > __init__.py line 19
```
 
#### Steps to reproduce:

  1. Clone new default zite template.
  2. Make sure `Cors` plugin is enabled (it should be enabled by default)
  3. Do: `ZeroFrame.cmd("corsPermission", "17a8dbHs6vTp2HcSgocUe3QKaXMJz9YkD4")`

#### Observed/Expected Results:

Result is observed while at `localhost` with 0 active peers, and zite was published only for yourself (but I doubt it matters).
While most of `corsPermission` requests are working as expected, some of them throwing an error described above.

I am trying to implement some kind of search between pretty big list of zites. Each zite, in order to be available for reading its files, needs to be requested with a cors permission. For tests, I went with popular zites addresses (and they were already on my local machine) and some unpopular ones, from [ZeroNet domain name registry](http://127.0.0.1:43110/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/).

I.e. there are three addresses on the list<sup>1</sup>:
```
kin.bloc.bit | 1Ako7M79KEGSdntHD53ycnRmUuzhyNxuuM
test.bloc.bit | 17a8dbHs6vTp2HcSgocUe3QKaXMJz9YkD4
blocbit.bit | 12PdTeR8FagmHbysqnViPxYAEXXpvUy2SA
```

While `corsPermission` command fires just fine with first or last address in the list<sup>1</sup>, it fails to fire with this one: `17a8dbHs6vTp2HcSgocUe3QKaXMJz9YkD4`.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I can confirm it happens when the site has been already added before, but the content.json file has not been downloaded yet or it does not have "title" in content.json.

**Comment by purplesyringa** [comment]
I think this can now be closed @HelloZeroNet?

**Comment by HelloZeroNet** [comment]
It's fixed by https://github.com/HelloZeroNet/ZeroNet/commit/785d2351ebf0b852e90eba64eeccd1c05925e340 in Rev4536
