### ISSUE TITLE
Attach a bitcoin wallet to every ZeroID

### ISSUE THREAD

**Issue by kahpecuce** [HelloZeroNet/ZeroNet#263]
I wonder if that is possible, which in turn might be used to tip the content creator one likes.

**Comment by HelloZeroNet** [comment]
It's possible already: Every user and site identified by a Bitcoin address. You can see the user's address by hovering on username eg. on ZeroTalk.

**Comment by kahpecuce** [comment]
So, technically I can tip that user (and he can retrieve the amount as long as he has the private key?)

**Comment by HelloZeroNet** [comment]
Yes, your ZeroID's private key is in data/users.json file (auth_privatekey part) Its saved in WIF format that supported by most of the Bitcoin clients.

**Comment by kseistrup** [comment]
I have successfully imported a ZeroNet private key into my bitcoin instance using the `importprivkey` RPC call. It sould work in the GUI client also.

**Comment by almet** [comment]
This issue should be closed :)
