### ISSUE TITLE
[CorsPlugin] Multicors: is it possible?

### ISSUE THREAD

**Issue by scsmash3r** [HelloZeroNet/ZeroNet#2630]
Currently, there is a [CorsPlugin](https://github.com/HelloZeroNet/ZeroNet/blob/py3/plugins/Cors/CorsPlugin.py), which allows you to use a `cmd` for granting cross-site access. As far as I can see, it works this way:

1) You request for access by doing `page.cmd("corsPermission", ziteAddress)`
2) `wrapperConfirm` is fired to confirm Cors request, where user can "Grant&add" (if zite was not downloaded locally yet), "Grant" (if zite exists in local data) or user can close the wrapper toast.
3) Zite is copied to your local data (or permission is granted, if already there)
4) You then have an option to reach `"inner_path"` (directory/file) with `cors-` prefix to work with other zite's contents.

The inconvenient part comes up when you have a bunch of zites to grant cors to. 
I.e. if I have 20 or more zites to be cors'ed, I will need to do something like:

```js
for (let key in zitesList) {
  page.cmd("corsPermission", zitesList[key]);
}
```

But it will fire up only 2 active toast messages at a time (two last ones) - other messages will disappear.
I've came up with a workaround, relying on promises:

```js
// Sends a cmdp, waits for resolving and then self-calls this func again without queued element
  getCorsPermissionsOneByOne(zitesList = ['zite1', 'zite2', ... , 'zite20']) {
    console.info("Waiting for " + zitesList[0]);
    page.cmdp("corsPermission", zitesList[0]).then(
      (resolve) => {
        inactiveZites.splice(0, 1);
        if (inactiveZites.length !== 0) this.getCorsPermissionsOneByOne(zitesList);
      }
    );
  }
```

While this works as I need to, the user still will need to click "Grant&add" button 20 or more times. 

**The solution I would like to see**
Would it be possible to add some sort of multiple cors request to a bunch of zites in one call? I.e., you can pass an array of zites in arg `page.cmdp("corsPermission", arg)`, and user will be alerted with just one toast message with something like: "This site requests read permission to **20 sites**" (where **20 sites** could be a link -> when clicked, slides down the div with all the addresses to see).

_The main aim for me is to make it easier for user to grant cors for a bunch of resources. From the point of UI/UX, it is better for user to click just once to grant required permissions instead of clicking them one by one for a (possible) long period of time._

Misc questions: what possible pitfalls can there be? How will it download/hang some of unreachable zites and how to track their downloading/copying process?

**Comment by purplesyringa** [comment]
IIRC I've already patched (or at least made a PR) to allow passing an array of sites to `corsPermission`; let me check if that was actually merged.

**Comment by purplesyringa** [comment]
It looks like I've written the patch but haven't submitted it. Please check if the patch in #2631 works for you, hopefully it'll get merged soon.

**Comment by scsmash3r** [comment]
> It looks like I've written the patch but haven't submitted it. Please check if the patch in #2631 works for you, hopefully it'll get merged soon.

Yup, it works! Now to wait until it is applied. For now I can use fallback to my old method (one by one), if client's ZN version is lower than v. with applied patch, I think.
