### ISSUE TITLE
Annoying notification onOpenWebsocket and onCloseWebsocket

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [HelloZeroNet/ZeroNet#2638]
It is very annoying to see every two second notifications about "Connection with UiServer Websocket was lost. Reconnecting..." and "Connection with UiServer Websocket recovered."

I have changed 2 seconds to 30 but has no any effect... @imachug @HelloZeroNet

**Comment by imachug** [comment]
This shouldn't normally happen. What browser are you using? Are there any network errors connected to the websocket? (open 'Network' devtools tab, find an URL like '/ZeroNet-Internal/Websocket', check the response code, etc.)

**Comment by JabbaDesilijicTiure** [comment]
@imachug 
If I run with --debug I get:

[18:23:50] Ui.UiServer 127.0.0.1 - - [2020-10-12 18:23:50] "GET /ZeroNet-Internal/Websocket?wrapper_key=2b004f179793254f9ee60aeb038a0619e1b16c8dad371e657a64e8b5cc0435cb HTTP/1.1" **404** 194 0.000750

Under Network in devtools (firefox) this is not 404, it is HTTP 101.

**Comment by JabbaDesilijicTiure** [comment]
Solved. 

The problem was missing hyphen in my fork:
```
# Internal functions
        elif "/ZeroNet Internal/" in path:
            path = re.sub(".*?/ZeroNet Internal/", "/", path)
```
