### ISSUE TITLE
Signing content.json adds needless trailing whitespace after commas

### ISSUE THREAD

**Issue by voteforcoffee** [HelloZeroNet/ZeroNet#264]
If you sign a content.json file, a space is inserted after every comma at the end of a line. My text editor (Github's Atom) and I'm sure some others too automatically remove trailing whitespace after saving a file since trailing whitespace serves no purpose, so if you have your ZeroNet site under git version control, these lines with the trailing whitespace removed all appear as changed in git every time you make a change to the file.

I can turn off that functionality in my text editor but that would just be a workaround. It would be better if this could be fixed in ZeroNet itself, unless the trailing whitespace after the commas is actually needed for some reason.

**Comment by HelloZeroNet** [comment]
Added to latest version: https://github.com/HelloZeroNet/ZeroNet/commit/61cfb8aa2ff222b9a92e466dddf59c8d92f8e772#diff-0823b49a6bc2f350e7c6134f24e9440dR211

**Comment by voteforcoffee** [comment]
Awesome, thanks!
