### ISSUE TITLE
Unobvious redirection to site file list

### ISSUE THREAD

**Issue by purplesyringa** [HelloZeroNet/ZeroNet#2654]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.2 (rev4538, 29dac8a1889e6c23773292718bec813e00ae2d74)
  * Operating system: Linux
  * Web browser: doesn't matter
  * Tor status: doesn't matter
  * Opened port: doesn't matter
  * Special configuration: none

### Step 2: Describe the problem:

Sometimes I'm redirected to /list/1Address when downloading a site for the first time. I believe this usually happens when the size of the files attached to the root `content.json` is larger than allowed. It's not obvious what one has to click after increasing the size limit.

#### Steps to reproduce:

Download some site with lots of files at root, e.g. [ZAlex's blog](http://127.0.0.1:43110/1HKcfPD3LhwzgrSwkSFFKUiTJJ3MvbgRTw/).

#### Observed Results:

Watch file list opening (only content.json ATM).

![image](https://user-images.githubusercontent.com/16370781/96481055-b3961b80-1243-11eb-856e-fbb14c142a48.png)

#### Expected Results:

The user should be redirected to site root after accepting the limit. Also, showing only `content.json` is useless, perhaps required but not downloaded files should be shown too (greyed out). Site title & description should be shown too.

**Comment by JabbaDesilijicTiure** [comment]
That is interesting. What plugin you use for the LIST? I never even seen 127.0.0.1:43110**/list/** for 3 years. Maybe you running with too much plugin @imachug.

**Comment by purplesyringa** [comment]
Commit f0b0f57643edf002548b9962fcf63e578605af34.

**Comment by JabbaDesilijicTiure** [comment]
This is a plugin. It has nothing to do with ZeroNet or its core functionalities.

**Comment by purplesyringa** [comment]
It is a part of ZeroNet repository, hence I'm reporting the problem here.

**Comment by JabbaDesilijicTiure** [comment]
There should be a different repository for plugins. Just like there is a different repository for HelloZeroNet_ , ZeroMe, and others.

**Comment by purplesyringa** [comment]
> There should be a different repository for plugins. Just like there is a different repository for HelloZeroNet_ , ZeroMe, and others.

Ask nofish to do that, I don't have enough privileges.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was able to reproduce and fix the problem in Rev4555

https://github.com/HelloZeroNet/ZeroNet/commit/a1105562cddd053fab7d5715025a98fc8d6bcc94
