### ISSUE TITLE
File browser thinks ogg files are editable.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2656]
![Screenshot_20201020-162928](https://user-images.githubusercontent.com/43807387/96640631-74be9f00-12f1-11eb-913b-6b8d14e925c0.png)

**Comment by JabbaDesilijicTiure** [comment]
LOL :rofl:

**Comment by JabbaDesilijicTiure** [comment]
@styromaniac take a look at https://github.com/HelloZeroNet/ZeroNet/pull/2657/files#diff-7e8d4a72fd3f5dfb486ac0bd395fe33d2ba5d32336079c79bba4d7062650e9ee

**Comment by styromaniac** [comment]
> @styromaniac take a look at https://github.com/HelloZeroNet/ZeroNet/pull/2657/files#diff-7e8d4a72fd3f5dfb486ac0bd395fe33d2ba5d32336079c79bba4d7062650e9ee 

Okay. I looked at it.

**Comment by JabbaDesilijicTiure** [comment]
@styromaniac and? It works?

**Comment by styromaniac** [comment]
> @styromaniac and? It works? 

Oh. I didn't test it. Only my phone can connect to the internet right now, anyway, and I'm using ZeroNet Mobile.

**Comment by JabbaDesilijicTiure** [comment]
I'm pretty sure it works. 

@imachug the android app has an "**Offers in-app purchases**" on Google Play which is a bad sign. 
@styromaniac I not recommend using the android app.

**Comment by purplesyringa** [comment]
> I'm pretty sure it works.

Of course it does not. You're looking for this line:

https://github.com/HelloZeroNet/ZeroNet/blob/29dac8a1889e6c23773292718bec813e00ae2d74/plugins/UiFileManager/media/js/FileList.coffee#L1

I believe it should be a text file whitelist instead of blacklist though. Perhaps whitelisting txt, json, html, css, js and a few others I can't remember now should work.

**Comment by purplesyringa** [comment]
> The applications logo is based on the logo of the Electrum bitcoin wallet, **I strongly recommend to remove the ZeroNet Mobile** if you have Electrum installed and you have bitcoin in that wallet.

Now *that* is an interesting way to find malicious packages. Oh, its icon is similar to Electrum, oh fuck, remove it ASAP!

**Comment by styromaniac** [comment]
> I'm pretty sure it works.
> 
> @imachug the android application has an "**Offers in-app purchases**" on Google Play which is a bad sign.
> @styromaniac I'm not recommending using the android application.
> 
> The applications logo is based on the logo of the Electrum bitcoin wallet, **I strongly recommend to remove the ZeroNet Mobile** if you have Electrum installed and you have bitcoin in that wallet.

I don't have any BTC.

**Comment by JabbaDesilijicTiure** [comment]
> > I'm pretty sure it works.
> 
> Of course it does not. You're looking for this line:
> 
> https://github.com/HelloZeroNet/ZeroNet/blob/29dac8a1889e6c23773292718bec813e00ae2d74/plugins/UiFileManager/media/js/FileList.coffee#L1
> 
> I believe it should be a text file whitelist instead of blacklist though. Perhaps whitelisting txt, json, html, css, js and a few others I can't remember now should work.

@imachug I see thanks. 
**ZeroNet is basically a JavaScript software full of shitty coffee scripts**, even on GitHub shows that ZeroNet is a JavaScript application. I'm getting very tired of @HelloZeroNet and his stupid plugins which are all JavaScript. 

In the other hand the application on Google Play has permissions like BILLING which along with Electrum and ZeroNet running can result in stolen funds. Why need ZeroNet Mobile BILLING permission? I tell you, because it is a scam! 

@styromaniac just disable the UiFileManager. Why you need it anyway? There is many other file managers you can use even on your Tablet.

**Comment by JabbaDesilijicTiure** [comment]
I remember the time when keyboards was free from the Microsoft logo... ZeroNet is going in the wrong way if everything is developed for Windows... They love privacy... They spy on ZeroNet users with Prism hand in hand with NSA... Still @styromaniac just disable all the plugins you don't need. ZeroNet ships a lot of trash by default all them JavaScripts...

**Comment by purplesyringa** [comment]
> **ZeroNet is basically a JavaScript software full of shitty coffee scripts**

![](https://i.kym-cdn.com/entries/icons/mobile/000/027/475/Screen_Shot_2018-10-25_at_11.02.15_AM.jpg)

How would you make a web application without JavaScript?

**Comment by purplesyringa** [comment]
> In the other hand the application on Google Play has permissions like BILLING which along with Electrum and ZeroNet running can result in stolen funds. Why need ZeroNet Mobile BILLING permission? I tell you, because it is a scam!

Then report it to the correct repository, nofish has no connection with the ZeroNet-kivy project.

**Comment by purplesyringa** [comment]
> Tell me @imachug why the plugin need a different list of mime types when UiRequest already has them

That is a good question. Perhaps it'd be a good idea to use server-side `mimetype` module to detect file types without additional detection by browser. @HelloZeroNet Agreed?

**Comment by JabbaDesilijicTiure** [comment]
@imachug 
> How would you make a web application without JavaScript?

The problem not the use of JavaScript, rather that in the past past few years python is slowly replaced by JavaScript! 
Right now, since the begging of this year, **ZeroNet has more JavaScript than Python code!**

**Comment by purplesyringa** [comment]
This does not imply that Python is being replaced, it just means more JS code is added. I don't see how this is a problem.

**Comment by JabbaDesilijicTiure** [comment]
@HelloZeroNet merge https://github.com/HelloZeroNet/ZeroNet/pull/2657 and close this issue.

**Comment by JabbaDesilijicTiure** [comment]
@HelloZeroNet please close this issue. 
Solved by https://github.com/HelloZeroNet/ZeroNet/commit/54fb2fde7c5423e758636170cf177e2966984911

**Comment by JabbaDesilijicTiure** [comment]
@HelloZeroNet please merge https://github.com/HelloZeroNet/ZeroNet/pull/2661 and close this issue.

**Comment by purplesyringa** [comment]
# :roll_eyes:

**Comment by HelloZeroNet** [comment]
It should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/4f6833c488258d4a34242a3c589da89b8c0ba417 in Rev4539
