### ISSUE TITLE
Document available features of htaccess?

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2658]
I've never seen anyone else use htaccess on ZeroNet before. I know some features appear unavailable, but below works to stream WebM videos in the browser.

>\# This forces WebM videos to open in the browser while without the lightbox.
><FilesMatch "\.(?i:webm)$">
>    ForceType application/octet-stream
>    Header set Content-Disposition attachment
><\/FilesMatch>

And I'm wondering why entering multiple file types with | separating them doesn't work.

**Comment by purplesyringa** [comment]
Are you sure it works because of .htaccess, not because of ZeroNet core? What happens if you just delete .htaccess?

**Comment by styromaniac** [comment]
> Are you sure it works because of .htaccess, not because of ZeroNet core? What happens if you just delete .htaccess?

WebM videos would no longer open in the browser without JS and video elements.

For ZeroNet, a name before .htaccess is needed so it's not hidden. Mine is Kave.htaccess

**Comment by purplesyringa** [comment]
There is no mention of htaccess in all ZeroNet code, I'm sure there is another explanation.

**Comment by JabbaDesilijicTiure** [comment]
@styromaniac are you kidding me right? 

Here is your video player: 

```
<video controls poster="theimage.png">
  <source src="thevideo.webm" type="video/webm">
  <source src="thesamevideo.pm4" type="video/mp4">
  <track label="Russian" kind="subtitles" srclang="en" src="thesubtitle.vtt" default>
</video>
```

If you need professional web development you may consider hire a web developer! **.htaccess has nothing to do with ZeroNet because your Zeronet data folder is not located under /var/www!**

**Comment by styromaniac** [comment]
> @styromaniac are you kidding me right? 
> 
> Here is your video player: 
> 
> ```
> <video controls poster="theimage.png">
>   <source src="thevideo.webm" type="video/webm">
>   <source src="thesamevideo.mp4" type="video/mp4">
>   <track label="Russian" kind="subtitles" srclang="en" src="thesubtitle.vtt" default>
> </video>
> ```
> 
> If you need professional web development you may consider hire a web developer! **.htaccess has nothing to do with ZeroNet because your Zeronet data folder is not located under /var/www!** 

I could swear it was the reason that WebM would play in the browser instead of download.

I prefer writing less code if possible, in part because I want people who might clone the site to have some shortcuts to desired results. I have a lightbox if you don't mind JS, and htaccess if you do mind JS. No need for the video tag. Everything works, just use an anchor tag around an image tag.

Also, numerous video players on a page is bad. I've heard enough complaints to shift away from having multiple video players embedded.

No need to be rude about it, and I've known about the video tag ever since 2010.

I'll close this issue and see if the lack of htaccess is going to work the same as with htaccess these days.
