### ISSUE TITLE
Benchmark 

### ISSUE THREAD

**Issue by JabbaDesilijicTiure** [HelloZeroNet/ZeroNet#2666]
@imachug sslcrypto_fallback is **faster** than sslcrypto!

![Screenshot_2020-10-31 Screenshot cleaned](https://user-images.githubusercontent.com/71508279/97779969-933a5b00-1b79-11eb-91fd-750de9e662a1.png)

**Comment by imachug** [comment]
No it's not. It's 0.139s per 20 ops on fallback and 0.249s per 200 ops on native.
