### ISSUE TITLE
Fix a typo in the French Translation

### ISSUE THREAD

**Issue by TTTaevas** [HelloZeroNet/ZeroNet#2669]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Windows 10
  * Web browser: Firefox 82.0.2
  * Tor status: always
  * Opened port: yes
  * Special configuration: none

### Step 2: Describe the problem:

The French translation has a typo.

#### Steps to reproduce:

  1. Launch ZeroNet in the French language  
  2. Right click on the ZeroNet logo on the bottom right of the screen

#### Observed Results:

  * When right clicking on the ZeroNet logo, you can see the typo
![Capture](https://user-images.githubusercontent.com/67872932/97880043-f74b5380-1d20-11eb-8808-9f72598951d0.PNG)

#### Expected Results:

  * Not seeing the typo

**Comment by HelloZeroNet** [comment]
Thanks, merged
