### ISSUE TITLE
Cross-access to zero-net sites

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#267]
What do you think about cross access to zero-net sites? it would be useful for making site (for example) jquery with latest script that can be included to all other sites

**Comment by HelloZeroNet** [comment]
I think sharing scripts is a bad idea: It increase centralization and the CDN site owner would able to inject scripts to other sites.

**Comment by iShift** [comment]
integrity can help, https://www.w3.org/TR/SRI/ like in bootstrap http://getbootstrap.com/getting-started/ 
(integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7")

**Comment by HelloZeroNet** [comment]
Still don't think it's worth relying on a central site to save 1-200kbyte storage

**Comment by Idealcoder** [comment]
Also, if we have local de-duplication on the filesystem storage or network then there is no benefit at all in a space saving.

**Comment by iShift** [comment]
ok
