### ISSUE TITLE
ZeroNet Mobile on Play Store missing

### ISSUE THREAD

**Issue by SysError99** [HelloZeroNet/ZeroNet#2677]
### Step 1: Please describe your environment

  * ZeroNet version: unknown
  * Operating system: Android
  * Web browser: -
  * Tor status: -
  * Opened port: -
  * Special configuration: -

### Step 2: Describe the problem:
ZeroNet Mobile is missing from Play Store. Opening from browser shows 'URL request is invalid'

##### Method 1
  1. Go to Play Store
  2. Search for ZeroNet
  3. ZeroNet Mobile official client is missing
##### Method 2
  1. Search for ZeroNet Mobile on Google
  2. ZeroNet Mobile does appear on search result, tap on it.
  3. Play Store reports that 'requested URL is invalid'

#### Expected Results:

Being able to download ZeroNet Mobile, from both APK or Play Store

**Comment by styromaniac** [comment]
Google removed it. They did the same thing with LBRY.

**Comment by HelloZeroNet** [comment]
Thanks for reporting/info, I replaced the link with: https://github.com/canewsin/zeronet_mobile/releases

**Comment by styromaniac** [comment]
> Thanks for reporting/info, I replaced the link with: https://github.com/canewsin/zeronet_mobile/releases

ZeroNet.io still doesn't have a working link.

**Comment by HelloZeroNet** [comment]
Thanks, fixed and also added XDA Labs link
