### ISSUE TITLE
Allow fully expanding the modified files notification or just make it wider by default.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2680]
![Screenshot_20201118-083437](https://user-images.githubusercontent.com/43807387/99536952-082ed280-2979-11eb-8977-1ccfebbd8d50.png)
I can't see what files are changed when the path text is too long.

The reason I need this is because hackers tamper with my files, so I need to know which files were fucked with. This would have been most helpful when this happened to The Eternal Word.

I was using NetGuard to potentially block the hackers over LTE+, but it keeps disabling for no apparent reason, so I might have to just deal with these hacks if I can't avoid them. This issue is very important to me.

**Comment by HelloZeroNet** [comment]
This feature got added in Rev4550: it should show the full list of modified files after click on the truncated list of filenames.

https://github.com/HelloZeroNet/ZeroNet/commit/52d6c9fedfc29f1ea91308bcf82f0d6c18c97d67
