### ISSUE TITLE
If IPv6 support is missing or broken, ZeroNet won't start if file server network is set to IPv6 only.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2681]
### Step 1: Please describe your environment

  * ZeroNet version: Version 0.7.2 (rev4550)
  * Operating system: Android 9
  * Web browser: Any
  * Tor status: available
  * Opened port: yes

#### Steps to reproduce:

  1. Grab app-release-v0.7.5-beta_1.apk. IPv6 support is broken in it.
  2. Go to the config page.
  3. Set file server network to IPv6 and restart ZeroNet.

#### Observed Results:

  * ZeroNet does not start.

#### Expected Results:

  * ZeroNet should still be able to start. In case of an error starting up like IPv6 support being broken, revert to the last working setting.

**Comment by HelloZeroNet** [comment]
I can confirm this behavior. The UiServer will be shut down if the FileServer fails to start (`bind(): bad family`):

https://github.com/HelloZeroNet/ZeroNet/blob/py3/src/File/FileServer.py#L378

It was added to avoid starting a non-functional client. I think it's not necessary anymore and a warning will be enough on ZeroHello, but need some testing.

**Comment by HelloZeroNet** [comment]
This was fixed in Rev4551 https://github.com/HelloZeroNet/ZeroNet/commit/38a3ea63737f43a5470f5e02549df8c3594902f8

If you unable to start the client I recommend to edit zeronet.conf and remove `fileserver_ip_type = ipv6` line

**Comment by styromaniac** [comment]
> This was fixed in Rev4551 [38a3ea6](https://github.com/HelloZeroNet/ZeroNet/commit/38a3ea63737f43a5470f5e02549df8c3594902f8)
> 
> If you unable to start the client I recommend to edit zeronet.conf and remove `fileserver_ip_type = ipv6` line

On ZeroNet Mobile, that's not possible. Thank you for fixing this.

**Comment by HelloZeroNet** [comment]
There is no built-in way do it, but still possible to edit the config file on Android: On my device the config file located at `/data/data/in.canews.zeronet/files/ZeroNet-py3` (may require root access to edit)

**Comment by styromaniac** [comment]
> There is no built-in way do it, but still possible to edit the config file on Android: On my device the config file located at `/data/data/in.canews.zeronet/files/ZeroNet-py3` (may require root access to edit)

I don't have root and I can't find it.
