### ISSUE TITLE
show ZEROID on landing page

### ISSUE THREAD

**Issue by kahpecuce** [HelloZeroNet/ZeroNet#269]
There is quite an empty space on the upper portion of the landing page, so I was wondering if it would be possible to show the current/default ZeroID and, maybe if there are any new incoming mails in ZeroMail on the upper bar, or on top left corner.

![image](https://cloud.githubusercontent.com/assets/16450950/13032745/4af60f2a-d307-11e5-82f9-1ad9e9287742.png)

**Comment by HelloZeroNet** [comment]
Unfortunately its not possible to query zeromails, because they are encrypted in the database. ZeroID is not really useful by itself, you will be redirected to it when you need to register a new one.
