### ISSUE TITLE
ZeroNet compiled from source doesn't shutdown when clicking this button.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2690]
![Screenshot from 2020-12-01 11-43-56](https://user-images.githubusercontent.com/43807387/100769882-a2a40280-33ca-11eb-8d97-4bbb80003f49.png)

**Comment by HelloZeroNet** [comment]
Do you see any errors in the terminal? Does the confirmation dialog appears on top-right corner of the window?

**Comment by styromaniac** [comment]
I haven't been starting it with terminal, but I'll try. The confirmation dialog appears and I click, but nothing happens.

**Comment by styromaniac** [comment]
Weird. It works now. I guess it just takes a moment.

**Comment by styromaniac** [comment]
Weird. It works now.
