### ISSUE TITLE
ERROR - Unhandled exception: TypeError: an integer is required

### ISSUE THREAD

**Issue by canewsin** [HelloZeroNet/ZeroNet#2699]
### Step 1: Please describe your environment

  * ZeroNet version: Rev4551
  * Operating system: ZeroNetMobile/Android
  * Web browser: InApp
  * Tor status: Available
  * Opened port: no
  * Special configuration: ____

### Step 2: Describe the problem:
ERROR - Unhandled exception: TypeError: an integer is required (got type bytes) in greenlet.py line 766 > FileServer.py line 343 > gevent/_socketcommon.py line 176 > ... > event.py line 268 > 296 > 286 > 266 > 211 > gevent/_tblib.py line 371 > ... > 202
#### Steps to reproduce:

  1. Install Latest App from Play Store and Run.

**Comment by canewsin** [comment]
@HelloZeroNet @shortcutme

**Comment by HelloZeroNet** [comment]
Hm, I'm unable to reproduce the problem, does it happens on latest, Rev4555 and if it's don't then on previous, 4550?

**Comment by canewsin** [comment]
> Hm, I'm unable to reproduce the problem, does it happens on latest, Rev4555 and if it's don't then on previous, 4550?

It still exists on Rev4555
Here is the traceback 
![Screenshot_2020-12-14-09-26-10-073_in.canews.zeronetmobile.jpg](https://user-images.githubusercontent.com/26790557/102038960-98ccc700-3dee-11eb-8875-165de22df319.jpg)

**Comment by canewsin** [comment]
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
Based on https://github.com/gevent/gevent/issues/1491 it happens if you have outdated (<1.5a2) gevent with Python 3.8
