### ISSUE TITLE
I can't increase users data maximum size

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#270]
i have site http://127.0.0.1:43110/1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE/ (Clone of zero talk ) i want to increase user data on site but new version on file don't propagate to users.

i use that commands:

1. zeronet.py siteSign 1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE --inner_path data/users/content.json
2. zeronet.py siteSign 1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE
3. zeronet.py siteVerify 1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE
4. zeronet.py sitePublish 1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE

what i have in /content.json: 

```
 "includes": {
  "data/users/content.json": {
   "signers": [ "" ],
   "signers_required": 1
  }
```
in /data/users/content.json 
```
{
 "files": {},
 "ignore": ".*",
 "modified": 1455546464.475202,
 "signs": {
  "1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE": "HKqBU/zIRsMGrrFFaeTWgFvNf7pxkUNhdIs5jcCs10g9XVJ/BdNA4T1/NAzT32g0bgyK4L3WYleOdA+rJrNusRQ="
 },
 "user_contents": {
  "cert_signers": {
   "zeroid.bit": [ "1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz" ]
  },
  "permission_rules": {
   ".*": {
    "files_allowed": "data.son",
    "max_size": 30000
   },
   "bitid/.*@zeroid.bit": { "max_size": 40000 },
   "bitmsg/.*@zeroid.bit": { "max_size": 15000 }
  },
  "permissions": {
   "bad@zeroid.bit": false,
   "gomzik@zeroid.bit": { "max_size": 100000 },
   "nippletwister@zeroid.bit": { "max_size": 100000 },
   "shift@zeroid.bit": { "max_size": 100000 }
  }
 }
}
```

**Comment by HelloZeroNet** [comment]
`zeronet.py siteSign 1Apr5ba6u9Nz6eFASmFrefGvyBKkM76QgE --inner_path data/users/content.json --publish` should help

**Comment by iShift** [comment]
wow, that works, thanks!
