### ISSUE TITLE
Site folder and its contents don't delete when "deleting" site

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2704]

**Comment by HelloZeroNet** [comment]
Does it happens for every site or just for some sites?
Does it deletes some ile or nothing at all?

**Comment by styromaniac** [comment]
> Does it happens for every site or just for some sites?
> Does it deletes some ile or nothing at all?

For [Kave](http://127.0.0.1:43110/1KN5zRytGbGqLNdemuoLC6gS44fwM9h38s/) I noticed that nothing gets deleted. I haven't tested other sites.

**Comment by styromaniac** [comment]
I can't seem to reproduce this anymore. I should have noted what it happened on.

**Comment by styromaniac** [comment]
This happens on Android and Linux with owned sites.
