### ISSUE TITLE
Https reverse proxy results in blank pages with only sidebars using Chrome.

### ISSUE THREAD

**Issue by zhouzhiwen2000** [HelloZeroNet/ZeroNet#2712]
When using Chrome to access a reverse proxied zeronet site, the CORB feature of Chrome kicks in.
Here are the two warnings:
Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://mydomain/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/css/all.css?site_modified=1604369175".

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://mydomain/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/css/all.css?site_modified=1604369175 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Here is my nginx config:
```
server {
    listen 80;
    listen [::]:80;
    server_name mydomain;
    location /.well-known {
        root /var/www/html;
    }
    location / {
        return 301 https://mydomain$request_uri;
    }
}

server {
    listen 443 ssl;

    server_name        mydomain;
    ssl on;
    ssl_certificate        /etc/letsencrypt/live/mydomain/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/mydomain/privkey.pem;
    ssl_session_timeout 5m;
	error_page 502 /index.html;
	location = /index.html {
                root /var/www/html/website;
        }
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host $host; #get rid of media referrer error
        proxy_http_version 1.1;
        proxy_read_timeout 1h; #for long live websocket connetion
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

**Comment by ghost** [comment]
I don't think you know how to setup a reverse proxy. 

`error_page 502 /index.html ` <---- Send a 503 error instead!

For reverse proxy you can also get rid of the location because it makes no sense: 

`	location = /index.html {
                root /var/www/html/website;`

**Comment by zhouzhiwen2000** [comment]
Oh, that's residual for torjan web server.
Removing these lines makes no difference.

**Comment by zhouzhiwen2000** [comment]
The reverse-proxyed website works well under FireFox.

**Comment by ghost** [comment]
@zhouzhiwen2000 I don't think you know what are you doing. Saying things like "`the reverse-proxyed website works well under FireFox`". If you do setup reverse proxy correctly than **doesn't matter what browser you are using**!

You sending various error codes for index.html and you have a location in config for what you shouldn't! I suggest you to find a professional who can set up your server correctly.

**Comment by zhouzhiwen2000** [comment]
Now, with the exact same configuration, it works. No idea why.

**Comment by zhouzhiwen2000** [comment]
> Now, with the exact same configuration, it works. No idea why.

Well, as it turns out, it works with ui-password off.
When I turn on ui-password, it results in a blank page after logging in on chromium-based browsers.
You can try it out yourself:
My browser version: Microsoft Edge Version 88.0.705.56 (Official build) (64-bit)(chromium-based)
Other chromium-based browsers are also tested, including chrome on Android.
Nginx configuration:

```
server {

    server_name yourhost.name;

    location / {
        proxy_pass http://127.0.0.1:43110;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_read_timeout 1h;  # for long live websocket connetion
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 80;
}

```

zeronet.conf:
```
[global]
fileserver_port = 15368
ui_host =  yourhost.name
ui_password = password
```
Now the config is identical to https://zeronet.io/docs/faq/#how-to-configure-nginx-reverse-proxy-for-zeronet
Only the domain name is different.
