### ISSUE TITLE
How do I have to modify a page so it loads stand-alone?

### ISSUE THREAD

**Issue by rubo77** [HelloZeroNet/ZeroNet#2713]
I would like to use the SQL functionality that uses data.json outside of ZeroNet.

If I just copy the ZeroNet site to my webserver it doesn't load any data.

How do I have to modify the code, so it loads outside of ZeroNet? Which extra scripts would I have to include, that are not in the ZeroNet folder of my page?

**Comment by HelloZeroNet** [comment]
The SQLite server is provided by the ZeroNet client, so it's not possible. Some browsers mayprovide [WebSQL](https://en.wikipedia.org/wiki/Web_SQL_Database) access, but it's outdated and not recommended to use.
