### ISSUE TITLE
ModuleNotFoundError: No module named 'base58'

### ISSUE THREAD

**Issue by slondr** [HelloZeroNet/ZeroNet#2715]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1.r4493.g14cbaf47-1
  * Operating system: Årch Linux
  * Web browser: N/A
  * Tor status: disabled
  * Special configuration: None

### Step 2: Describe the problem:
ZeroNet doesn't launch; producing an error instead
#### Steps to reproduce:

  1. `systemctl start zeronet`

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.
https://i.postimg.cc/XvR15NpZ/image.png
#### Expected Results:
ZeroNet starts

**Comment by Oshgnacknak** [comment]
Same error here. 
Installing https://aur.archlinux.org/packages/python-base58/ fixed it.
Seems to be an error in the aur package.
Edit: Has been reported on the package's page.

**Comment by slondr** [comment]
Excellent :+1:
