### ISSUE TITLE
Bigfiles don't download to Mac.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroNet#2719]
Rev4555 on all platforms (Linux, Mac, Android). I've also tried both Chrome and Firefox.

**Comment by ghost** [comment]
You all the time opening issues with a single line, you think that GitHub is a chat or something? 

Those big files should be optional files and you should turn on auto download optional files. Nothing is instant so be patient while those files are downloading. You can also look for different trackers if you know what they are.

**Comment by styromaniac** [comment]
> You all the time opening issues with a single line, you think that GitHub is a chat or something?
> 
> Those big files should be optional files and you should turn on auto download optional files. Nothing is instant so be patient while those files are downloading. You can also look for different trackers if you know what they are.

I've done everything in my power to resolve the issue and I'm the owner of Syncronite...

**Comment by styromaniac** [comment]
It seems to have been a firewall issue. Issue Closed.
