### ISSUE TITLE
Issues while creating a site.

### ISSUE THREAD

**Issue by Stackoverload** [HelloZeroNet/ZeroNet#272]
Hello, I've been recently working on a site and I've been running into issues.
Whenever I edit the HTML everything shows up fine on refresh, but if I am to add any JS files to js/lib it causes the all.js to throw the error of Uncaught TypeError: App.init(...) is not a function. After deleting all.js, and signing/refreshing (I think you have to sign after non HTML changes) I still manage to get the error (yet all.js doesn't even exist in the directory anymore... After deleting the site and redoing this multiple times (where I don't include any library files like jquery, chartjs, etc.) I've still managed to run into the same problem in the end. "x file update failed" in the main 'home' under my website name on the "connected sites" list.
Things I've tried: Deleting all.js (and all.js in the content.json file) Removing the library's I use from js/lib and moving to lib Manually importing every JS file
ALSO: I tried using all.css (which it generated the file) but none of the css properties where showing up so I ended up importing each css file within the HTML manually (instead of just importing all.css)

**Comment by Stackoverload** [comment]
Is there a special way I must connect to see changes locally on refresh? Or is using http://127.0.0.1:43110/{Public_site_key} proper?

**Comment by TheNain38** [comment]
@Stackoverload Maybe your browser cached the files? Try using ctrl+F5 to force redownload without using the cache.

**Comment by Stackoverload** [comment]
I did it, and something new happens. It generated an all.js file but none of my new code is in it.

**Comment by TheNain38** [comment]
Are you running ZeroNet in debug mode? Using the --debug switch?

**Comment by Stackoverload** [comment]
Also, now it says "Updating..." but why should it update if I'm trying to see changes locally?

And yes, I am.

**Comment by Stackoverload** [comment]
Oh and on top of that, it edited my coffeescript back to the previous version.

**Comment by TheNain38** [comment]
Do you have the "own" property set? When on your site if you open the sidebar at the bottom you should see "This is my site" checked

**Comment by Stackoverload** [comment]
My changes aren't showing up after signing (as expected). And yes, but I've been signing via the commandline

**Comment by TheNain38** [comment]
Ok, did your coffeescript file gone back to the previous version?

**Comment by Stackoverload** [comment]
Yes it did. I then changed it and signed, but my changes aren't showing (I didn't edit or delete all.js)

**Comment by Stackoverload** [comment]
Now my changes show up (5 minutes later)

**Comment by Stackoverload** [comment]
Seems like every time I edit a coffeescript file and click 'update' on the site, it says "x File update failed" where x is a number (which makes me think I'm not going to the proper place to see it locally since it shouldn't need to 'update').

**Comment by Stackoverload** [comment]
And then a few minutes later it successfully updates (and I can see changes)

**Comment by Stackoverload** [comment]
This is weird, I went back to check my code and it's the old code (but I see the new changes)

**Comment by TheNain38** [comment]
So, is your problem fixed or not?

**Comment by Stackoverload** [comment]
Kind of, but not really. Any changes I make (and sign) say update failed for 5-15 minutes, and then finally show up which is really bad for development.

**Comment by TheNain38** [comment]
Update failed just means it wasn't able to download the files from other peers (This is normal since YOU have the files, and not them), normally it should show up even if it says that...

**Comment by Stackoverload** [comment]
Do I need to delete all.js everytime?

**Comment by TheNain38** [comment]
No

**Comment by Stackoverload** [comment]
Odd then, because I sign it and look at all.js and my changes aren't in the file. If I delete all.js and hard refresh the page it acts like all.js still exists.

**Comment by TheNain38** [comment]
Try refreshing using ctrl+F5

**Comment by TheNain38** [comment]
Or set your cache size to 0

**Comment by Stackoverload** [comment]
I've cleared my cache and did a hard reload, still acts like all.js exists even though it doesn't for in my folder.

**Comment by Stackoverload** [comment]
Now it just generated it... Odd

**Comment by TheNain38** [comment]
When you delete "all.js" and you go to a page that needs it, it regenerates it, and it take a little bit of time, like 2 seconds or something like that

**Comment by Stackoverload** [comment]
Wow.. I found out how to fix it now. If I delete all.js, and clear the cache and then refresh it works perfectly. Thanks :)

**Comment by TheNain38** [comment]
You're welcome :D, don't forget that you can always set your cache size to 0, so you won't have to clear it everytime :)

**Comment by Stackoverload** [comment]
Where would I do that?

**Comment by TheNain38** [comment]
In your browser settings

**Comment by Stackoverload** [comment]
Oh.. Yeah duh.. haha
Thanks.

**Comment by TheNain38** [comment]
@Stackoverload Btw I'm called `thekill38` on ZeroNet, if you want to send me a ZeroMail ;)

**Comment by Stackoverload** [comment]
Awesome :) I'll make sure to

**Comment by HelloZeroNet** [comment]
Better way to disable caching:
 - Open browser dev tools: F12
 - Network > Disable cache (Chrome), Gear > Disable cache (Firefox)
 - This will disable content caching until you keep the dev tools opened
