### ISSUE TITLE
发布新站点时，一直说没有节点，发布不成功

### ISSUE THREAD

**Issue by loongdy** [HelloZeroNet/ZeroNet#2720]
我想自己发布一个站点，设置完后，在本地输入 http://127.0.0.1:43110/1NVrpiMLBmSXdXPQQqi3K2QkR2tPX44LSL/ 都能访问，但是点击 签名发布时，一直报
“内容发布失败，
找不到节点，但是您的内容已经准备好被访问。
”

是什么原因呢，请教请教

**Comment by scsmash3r** [comment]
必须有人来加载您的网站。 如果只有您发布了该网站，您将收到此消息。 只需将链接发布给其他人，以便zite可以同步并拥有多个合作伙伴。

您必须在线才能将您的网站播种到第一个客户。 如果您不在线，则单击链接的任何人都会收到消息“找不到对等方”。

P.S. I can see your website as "I'm yuyu" and some child photo on the page cover.
