### ISSUE TITLE
Zeronet not working with macOS Big Sur

### ISSUE THREAD

**Issue by Chwiss** [HelloZeroNet/ZeroNet#2722]
### Step 1: Please describe your environment

  * ZeroNet version: irrelevant
  * Operating system: macOS Big Sur
  * Web browser: irrelevant
  * Tor status: not available
  * Opened port: yes/no
  * Special configuration: ____

#### Steps to reproduce:

  1. upgrade to new mac OS

**Comment by Microwave22** [comment]
Are you running on a M1 mac by chance?

**Comment by Chwiss** [comment]
the update from zeronet or an update from apple for big sur must have resolved the issue.
Everything is back to working just fine :)
