### ISSUE TITLE
Recovering my old user.json (ZeroID)

### ISSUE THREAD

**Issue by Jzarecta** [HelloZeroNet/ZeroNet#2724]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Arch Linux
  * Web browser: Firefox
  * Tor status: available
  * Opened port: no
  * Special configuration: ____

#### Steps to reproduce:

  1. Go to ZeroID
  2. Claim old user
  3. Insert old cert

#### Observed Results:

  * What happened? 
  * I used to ran ZeroNet in my old machine, I backup everything but want to run it now
  * I want to keep my old sites, and credentials
  * ZeroNet has changed and I currently don't know the filesystem

#### Expected Results:

  * The easy way would be to just drop the user.json file on the right directory, unfotunately I cant find the old directories anymore. 
  * Used to have them under `ZeroBundle/ZeroNet/data/users.json` as well as other files like sites.json
  * I installed the yay package zeronet-git and need to find the 'data' directory.

**Comment by lez** [comment]
Have you checked `/var/lib/zeronet/users.json`?

**Comment by ghost** [comment]
This happens when someone don't know how to make a backup! Incredible that someone can lose something in 2021. You need decades to learn to make backup of important files? Don't blame it on ZeroNet that your user.json magically disappeared. You are done. Period. Learn from your mistakes.
