### ISSUE TITLE
Window opener bug

### ISSUE THREAD

**Issue by Mujaja** [HelloZeroNet/ZeroNet#275]
How to replicate:

- Trigger a window opener security check by changing the page in a site like [this](http://127.0.0.1:43110/17Kom2G5qNDc6NaQwv445h1gFzxkY3ZtZe/).

- Click the button.

- A new tab shows up but the parent tab doesn't close.

- Clicking the button in the new tab works as it should.

Happens on Firefox for Linux.

**Comment by HelloZeroNet** [comment]
Sorry, I can't reproduce window opener security check using the docs site

**Comment by ZarkBit** [comment]
this?
https://dl.dropboxusercontent.com/s/s2gbofwo77h2sky/2016-02-21_03-51-02.mp4

**Comment by HelloZeroNet** [comment]
Yeah thanks, it's looks like-firefox only (no idea why), possible solutions:
 - (recomended) The site owner add target=_top to every link. The easiest way to do this is creating a `docs.js` file with this content (docs.js referenced in the html source code, but it's not exists):
```
var base = document.createElement('base');
base.target = '_top';
base.href = document.location.href.replace("/media", "").replace("index.html", "").replace(/[&?]wrapper=False/, "").replace(/[&?]wrapper_nonce=[A-Za-z0-9]+/, "")
document.getElementsByTagName('head')[0].appendChild(base);
````
(please also upload [docs.css](https://github.com/HelloZeroNet/Documentation/blob/master/docs/docs.css))
- The site owner add  `"postmessage_nonce_security": true` to [content.json](https://github.com/HelloZeroNet/ZeroBlog/blob/master/content.json#L148), which is disable the popup message

**Comment by Mujaja** [comment]
Works better after the last commit, thanks. I also uploaded the files and added `"postmessage_nonce_security": true` to the content.json file and it's flawless so far.
