### ISSUE TITLE
Is there a way to stop the ZeroNet daemon from another terminal (Linux)?

### ISSUE THREAD

**Issue by Mujaja** [HelloZeroNet/ZeroNet#277]
I don't think `pkill python` is the most efficient, is there another way?

**Comment by HelloZeroNet** [comment]
There is no other way to stop it yet.

**Comment by Mujaja** [comment]
That's ok, I'll look for another way, thank you. :smile:

**Comment by Mujaja** [comment]
In case someone finds this in the future, I've found a way.

- Create a script that starts zeronet (`zero.sh`)
- Create another one that stops it, like so:

`stop.sh`
```
#!/bin/bash

cd /folder/of/the/start/script
zeroPID=$( pgrep zero.sh )
kill -INT -$zeroPID
```

For some reason `pgrep` doesn't work with absolute paths, hence the `cd`.
