### ISSUE TITLE
Can't Download ZeroNet from Github 404 Error.

### ISSUE THREAD

**Issue by CookieCr2nk** [HelloZeroNet/ZeroNet#2786]
### Step 2: Describe the problem:

I can't download Zeronet for Windows from Github. I'm using the link, that is linked on zeronet.(https://codeload.github.com/HelloZeroNet/ZeroNet-win/zip/dist-win64/ZeroNet-py3-win64), I receive a "404: Not Found" error.

**Comment by purplesyringa** [comment]
You're probably looking for https://github.com/HelloZeroNet/ZeroNet-win/archive/refs/heads/dist-win64.zip

**Comment by CookieCr2nk** [comment]
Thx, it's solved now. On Zeronet the new link is at the download button as you mentioned. Before it was the link from "codeload.github.com" there.
