### ISSUE TITLE
request: unique zero id

### ISSUE THREAD

**Issue by dtjl** [HelloZeroNet/ZeroNet#279]
Hi, just looked at zeronet and recognized that it seems not to be possible to have just one zero id on different devices. Since most people have more than one device it's rather an essential feature to be able to have on zero id with which devices can be synced and behave as one.

**Comment by HelloZeroNet** [comment]
Just copy the users.json file and you will have the same identity

**Comment by dtjl** [comment]
thanks, copied it and it works. When using the unique id to sent a mail to myself the mail appears on both devices (but tells by sending the mail that the "content published to 5 peers"?). Deleting this mail on one of the devices doesn't remove it at the other.

**Comment by HelloZeroNet** [comment]
The problem is you can't really delete an incoming message, just hide it, because it's owned by the sender and only he/she able to modify it.

**Comment by dtjl** [comment]
What does this mean? With the same zero id I'm not the sender on both devices? And, clicking on the trash of a message isn't deleting, but hiding it?

**Comment by HelloZeroNet** [comment]
In ZeroMail every user has a data file where he/she stores the messages he/she sent. You inbox lists messages from other users data file that is sent to you (encrypted to your public key).
This data files are only modifiable by it's owner, it means you can't delete from your inbox just hide it. The hidden messages identifier currently stored in browser's local storage, so it's not synced between devices.

**Comment by dtjl** [comment]
Thanks for the explanation. Just for clarification, mails (+ then I assume other message types as well) are stored locally in the browser's storage. But it's not quite clear what this means. Up to now, I tested with IE and assuming to delete my own test mails actually just hide them. Thus, in the IE view the mails do not appear anymore, but e.g. Chrome shows them all again. This behavior is unexpected (because it's different from client-server systems) and thus confusing. 
If I understand 'owner' now as the sender of a mail/message, does this mean, only the sender can delete a mail/message, but the receiver/s on which devices a message is stored can't?
Thanks in advance.

**Comment by HelloZeroNet** [comment]
Mails are stored in your hdd, when you delete a mail from your inbox it adds the mail's id to browser's local storage. Next time you visit the page the js checks reads the deleted ids from browser's local storage and skips them.

**Comment by trcyprkr** [comment]
so how would copying the users.json file work with android?  Where would you place the json file in the system?

**Comment by imachug** [comment]
@trcyprkr `/Android/data/net.mkg20001.zeronet/files/zero/data/users.json` or something like that.

**Comment by trcyprkr** [comment]
thanks much
