### ISSUE TITLE
SEEDING UPDATE FAILED

### ISSUE THREAD

**Issue by Elmit2015** [HelloZeroNet/ZeroNet#28]
My first try:
I created a test site with and published it, and still get SEEDING UPDATE FAILED.

No real content yet there:
http://127.0.0.1:43110/19u3W1KB8nzzEW3EiQYC1eNfQ6Q53o9Gj7

What kind of files can I use for the site?
Is there a tutorial for that?

What will be ZeroMarket and ZeroBay??? or why is it gray?

**Comment by HelloZeroNet** [comment]
Update failed is normal when seeding own site without other peers.
In the latest commit "Update failed" warning changed to "No peers found" when seeding own site to make it less scary.

ZeroMarket and ZeroBay still under planning, it will be arrive later
