### ISSUE TITLE
Ubuntu 15.10 - AttributeError: 'module' object has no attribute '__import__'

### ISSUE THREAD

**Issue by camponez** [HelloZeroNet/ZeroNet#280]
I'm using ubuntu 15.10.

Trying to run from master:

It was working with an oldversion (don't remember) after an update it start giving me this error.

$ python start.py 
- Starting ZeroNet...
Traceback (most recent call last):
  File "/home/devel/ZeroNet/zeronet.py", line 15, in main
    import main
  File "/home/devel/ZeroNet/src/main.py", line 11, in <module>
    monkey.patch_all(thread=False, subprocess=False)
  File "/usr/lib/python2.7/dist-packages/gevent/monkey.py", line 379, in patch_all
    patch_builtins()
  File "/usr/lib/python2.7/dist-packages/gevent/monkey.py", line 350, in patch_builtins
    patch_module('builtins')
  File "/usr/lib/python2.7/dist-packages/gevent/monkey.py", line 94, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 17, in <module>
    _import = builtins.__import__

**Comment by HelloZeroNet** [comment]
Hm i have not met this one yet, can you please execute
`python -V` and `python -c "import gevent; print gevent.version_info"` commands?

**Comment by camponez** [comment]
$ python -V and python -c "import gevent; print gevent.version_info"
Python 2.7.10

**Comment by HelloZeroNet** [comment]
Hm, I have just setup a new Ubuntu 15.10 VPS, 
```
# apt-get install python python-pip python-msgpack
# python -V 
Python 2.7.10
# python -c "import gevent; print gevent.version_info"
version_info(major=1, minor=1, micro=0, releaselevel='beta', serial='1')
# python zeronet.py
- Starting ZeroNet...
[22:29:36] - OpenSSL loaded, version: 01000204F
[22:29:36] - Version: 0.3.6 r909, Python 2.7.10 (default, Oct 14 2015, 16:09:02)
[GCC 5.2.1 20151010], Gevent: 1.1b1
...
```
So everything works fine here, still investigating...

**Comment by HelloZeroNet** [comment]
New installation method released, please try this:

- wget https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-linux64-v0.1.1.tar.gz
- tar xvpfz ZeroBundle-linux64-v0.1.1.tar.gz
- cd ZeroBundle
- Start with ./ZeroNet.sh

**Comment by camponez** [comment]
It works that way. Is there a way to run it from git  repo?

**Comment by HelloZeroNet** [comment]
Yes, the ZeroNet directory = git repo

But you can also update it from the WebUI using ⋮ > Version: ... on ZeroHello (It's basically download the latest version from github and overwrites the existing files)
