### ISSUE TITLE
ZeroNet Landing Page not starting :'(((

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#2804]
I'm on Linux Mint, downloaded the latest ZeroBundle, installed the requirements, and ran ./ZeroNet.sh
But I'm still facing this:

CONNECTING...
TRACKERS ANNOUNCING: 0, ERROR: 7, DONE: 1
NO PEERS FOUND
TRACKER CONNECTION ERROR DETECTED.
[Use Tor meek bridges for tracker connections](http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D#Enable+Tor+bridges)
NO MEEK BRIDGE SUPPORT IN YOUR CLIENT, PLEASE [DOWNLOAD THE LATEST BUNDLE](https://github.com/HelloZeroNet/ZeroNet#how-to-join).

I searched for its solutions, tried the ones which I could, but this screen text, above, still appears

Please tell me what do I do to successfully connect to the ZeroNet Landing Page

**Comment by canewsin** [comment]
@aeroaech Use ZeroNetX https://github.com/ZeroNetX/ZeroNet instead it is actively maintained.

**Comment by caryoscelus** [comment]
see https://www.reddit.com/r/zeronet/comments/s27d34/0net_forks/ or https://en.wikipedia.org/wiki/ZeroNet for less biased description of available forks

**Comment by ghost** [comment]
> @aeroaech Use ZeroNetX https://github.com/ZeroNetX/ZeroNet instead it is actively maintained.

Okay, thanks :)
