### ISSUE TITLE
ERROR    TorManager Tor controller connect error: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TheOncomingStorm** [HelloZeroNet/ZeroNet#281]
The UI is suggesting that there is a problem with Tor connecting. 

debug.log reports:
[2016-03-01 20:17:31,602] ERROR    TorManager Tor controller connect error: 'NoneType' object has no attribute 'group'
[2016-03-01 20:17:31,602] DEBUG    TorManager Tor proxy port 127.0.0.1:9050 check error: No connection

Tor is definitely running as I'm using it for other activities, and I configured it as suggested in the FAQ. Is there anything else I'm missing?

**Comment by TheOncomingStorm** [comment]
I checked the permissions of /var/lib/tor/data/control_auth_cookie (that's apparently the location for mine. I should mention I'm using Gentoo) and it's 

-rw------- 1 tor tor 32 Mar  1 20:40 /var/lib/tor/data/control_auth_cookie

which doesn't give me rights to use it. Any attempt to change its permissions results in nothing happening(which is probably something with Tor resetting them).

**Comment by HelloZeroNet** [comment]
You have to add your user to tor's group: http://zeronet.readthedocs.org/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by TheOncomingStorm** [comment]
As I said, I configured Tor as suggested in the FAQ. I'm a member of the group, etc.

**Comment by HelloZeroNet** [comment]
yeah, sorry probably you have to add: `CookieAuthFileGroupReadable 1`

**Comment by TheOncomingStorm** [comment]
I have that too. When I try:
 
echo 'PROTOCOLINFO' | nc 127.0.0.1 9051

I get 

250-PROTOCOLINFO 1
250-AUTH METHODS=COOKIE,SAFECOOKIE COOKIEFILE="/var/lib/tor/data/control_auth_cookie"
250-VERSION Tor="0.2.8.1-alpha"
250 OK

If that helps.

**Comment by TheOncomingStorm** [comment]
Another observation: 
while the cookie file itself is readable, /var/lib/tor/data is not. I wondered why I kept needing to use sudo just to use "ls". I changed it but when you restart Tor, it resets the permissions. Surely there's a way around that but I've not yet discovered it. 

Also, I tried to connect to the control port with TorCtl for python and it worked fine as long as the "data" directory was at the proper permissions BUT zeronet still spits out that same error. 

Any other ideas?

**Comment by HelloZeroNet** [comment]
You can try changing the cookie path using `CookieAuthFile Path`

**Comment by HelloZeroNet** [comment]
Here is the fix: https://github.com/HelloZeroNet/ZeroNet/commit/779075c4a56ef921f4095220725a16b156eba52e

**Comment by TheOncomingStorm** [comment]
The CookieAuthFile setting worked like a charm. I had to create a directory that was owned by tor so it could create the file but otherwise was fine. 

The rest of the fix worked as well so I'm closing this. Thanks
