### ISSUE TITLE
-

### ISSUE THREAD

**Issue by krzysztof113** [HelloZeroNet/ZeroNet#2815]

**Comment by caryoscelus** [comment]
> PHP powered.

sorry , but it's not going to work . years of research and trends in programming language show where we're all heading and it's not imperative-first dynamic weakly typed languages

**Comment by krzysztof113** [comment]
It's not the kind of feedback I'm looking for. Rather about architectural decisions. Technological stack is decided and working nicely.

**Comment by caryoscelus** [comment]
i know it's not . i have no doubts you can make things work nicely . just a friendly warning that this approach is not future-proof

**Comment by krzysztof113** [comment]
![znwiki](https://user-images.githubusercontent.com/11329331/204833623-d3e13a1e-d9b4-4426-8b7a-3d5dd08e05a6.png)
