### ISSUE TITLE
Ubuntu 15.10 - Access on server IP:PORT

### ISSUE THREAD

**Issue by scriptzteam** [HelloZeroNet/ZeroNet#282]
Hello on start i see 
[08:27:32] Ui.UiServer Web interface: http://127.0.0.1:43110/

But i want to listen it on server ip like 299.145.36.0:43110 how to do it?

**Comment by HelloZeroNet** [comment]
You have to start it using zeronet.py --ui_ip "*"

More info:
http://zeronet.readthedocs.org/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine

**Comment by scriptzteam** [comment]
thx :)

**Comment by bradvo** [comment]
I have a similar question. Would it be possible to bind to a specific ip(s) than just all?

**Comment by HelloZeroNet** [comment]
same syntax: zeronet.py --ui_ip 1.2.3.4
