### ISSUE TITLE
Translation in several languages

### ISSUE THREAD

**Issue by TheSirC** [HelloZeroNet/ZeroNet#285]
Hello,
I'm currently talking to the owner or any person with the knowledge to point a direction :
I would like to participate to the development and the growth of this project. However, I do not have the required knowledge and coding skills to do so. So I would like to translate the content written in the Wiki, the Docs and the README to enlarge the public of this project : I speak three languages so I think that could be helpful. Hear me right : I don't want to edit the content, I want to translate it. Unfortunately, I didn't find how to do it on my own.

Could you show me a procedure to do so ?

Thankfully,

**Comment by Erkan-Yilmaz** [comment]
might also be of interest: #322

**Comment by grez911** [comment]
@HelloZeroNet Can the issue be closed?
