### ISSUE TITLE
error when trying to create a user

### ISSUE THREAD

**Issue by aquila0101** [HelloZeroNet/ZeroNet#2851]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.1
  * Operating system: Windows 10
  * Web browser: LibreWolf
  * Tor status:  available
  * Opened port: yes
  * Special configuration: no

### Step 2: Describe the problem:

Error while during request: error undefined

#### Observed Results:

  * What happened? This could be a screenshot, a description, log output (you can send log/debug.log file to hello@zeronet.io if necessary), etc.

#### Expected Results:

  * What did you expect to happen?
![Capturar](https://github.com/user-attachments/assets/87619039-c0da-4297-9d02-40abffc4f488)
![Capturar2](https://github.com/user-attachments/assets/fb0a92ac-3516-4b6b-9dc4-ef110450acf0)

**Comment by aquila0101** [comment]
the settings are all default

**Comment by aquila0101** [comment]
![3](https://github.com/user-attachments/assets/678cb9b0-6e89-42d7-be2f-3c2cbb561222)

**Comment by mx5kevin** [comment]
The ZeroMail service is no longer supported and no one will fix it. Services what required ZeroID the service is down, the support has ended and it will not be possible to register new users in the future. The ZeroNet  software development also ceased, the project are abonded.
