### ISSUE TITLE
OSX El Capitan: zeronet.py fails on import gevent

### ISSUE THREAD

**Issue by jarlarntzen** [HelloZeroNet/ZeroNet#286]
Hi, I followed the instructions for mac but it fails when attempting to run gevent. Anyone got a suggestion?

```
MacBook-Pro:ZeroNet-master jarla$ python zeronet.py
- Starting ZeroNet...
Traceback (most recent call last):
  File "zeronet.py", line 15, in main
    import main
  File "src/main.py", line 8, in <module>
    import gevent
ImportError: No module named gevent
Traceback (most recent call last):
  File "zeronet.py", line 60, in <module>
    main()
  File "zeronet.py", line 46, in main
    traceback.print_exc(file=open("log/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'
```

**Comment by ASBaumgarten** [comment]
Were you at least able to  get gevent installed through pip? Also do you have System Integrity Protection disabled?

**Comment by jarlarntzen** [comment]
Thanks for your prompt response!
Gevent seems to have installed nicely. Thanks. Not sure what the System Integrity Protection is but I'll look it up. (There wasn't any information about SIP at the download page.)

```
$ pip install gevent msgpack-python
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): msgpack-python in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /usr/local/lib/python2.7/site-packages (from gevent)
```

**Comment by jarlarntzen** [comment]
My SIP isn't disabled and [from the description here](http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11
) it seems I need to switch if off completely. Which is a little much just to run ZeroNet. 
Think I'm going to try this on my Ubuntu 14.04 home machine instead.

**Comment by HelloZeroNet** [comment]
please try `python -m pip install gevent msgpack-python`, maybe the pip command uses different python installation

**Comment by xtazz** [comment]
@HelloZeroNet it works, thank you

**Comment by ASBaumgarten** [comment]
Apple implemented SIP in OSX 10.11 to help lock down a lot of stuff in the system folders like `/usr` 
http://totalfinder.binaryage.com/system-integrity-protection

**Comment by ASBaumgarten** [comment]
@HelloZeroNet If cross platform testing is an issue, one potential solution could be to just release ZeroNet in Docker containers, similar to what [**nofish**](https://hub.docker.com/r/nofish/zeronet/) has made. It would eliminate the strenuous need to test each build on Windows, OSX, and Linux. The only real drawback would be that individuals would need to learn and setup Docker, but that complication is almost perfectly remedied with [**Kitematic**](https://kitematic.com/).

**Comment by victorBaro** [comment]
Same problem here. @HelloZeroNet suggestion didn't work. Any other suggestion? Thanks

**Comment by jarlarntzen** [comment]
Thanks, @HelloZeroNet . It didn't like the command, though:
```
$ python -m pip install gevent msgpack-python
/usr/bin/python: No module named pip
```

**Comment by ASBaumgarten** [comment]
@jarlarntzen Unless you installed Python using Homebrew, you will have install `pip` manually from here https://pip.pypa.io/en/stable/installing/. Once you have `pip` downloaded and installed you will be able to run `python -m pip install gevent msgpack-python`.

**Comment by JayBrown** [comment]
OS X 10.11.3, SIP disabled, additional installation of python in /usr/local, installed gevent & msgpack-python, updated all pip-installed formulas, added zeronet, no problems. Works great.

**Comment by HelloZeroNet** [comment]
I think i was able to create a bundle for mac, please help me verify it's working: https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

 - (Close ZeroNet if already running for you)
 - Download, unpack, run ZeroNet(.app)

It should download the latest version from github, start it and open ZeroHello in the browser.

Please also check http://127.0.0.1:43110/Benchmark if everything is ok. (no errors, openssl verify is working, the python version should be 2.7.11)

Thanks!

**Comment by jarlarntzen** [comment]
Wow! This worked fantastically well!

Thanks @HelloZeroNet 

```
Benchmarking ZeroNet 0.3.6 (rev949) Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec 6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)] on: darwin...

CryptBitcoin:
- hdPrivatekey x 10..........0.127s [x5.52: Insane!!]
- sign x 10..........0.066s [x5.34: Insane!!]
- openssl verify x 100..........0.136s [x2.72: WOW]
- pure-python verify x 10..........0.328s [x4.88: Insane!!]

CryptHash:
- sha256 5M x 10..........0.152s [x3.95: Insane!!]
- sha512 5M x 10..........0.110s [x5.44: Insane!!]
- os.urandom(256) x 100 000..........2.067s [x0.31: Ehh]

Msgpack:
- pack 5K x 10 000..........0.258s [x3.02: WOW]
- unpack 5K x 10 000..........0.473s [x2.54: WOW]
- streaming unpack 5K x 10 000..........0.495s [x2.83: WOW]

Db:
- Open x 10..........0.019s [x6.91: Insane!!]
- Insert x 10 x 1000..........0.394s [x2.54: WOW]
- Buffered insert x 100 x 100..........0.770s [x1.69: Fine]
- Total rows in db: 20000
- Indexed query x 1000..........0.116s [x2.16: Fast]
- Not indexed query x 100..........0.409s [x1.47: Fine]
- Like query x 100..........0.796s [x2.26: Fast]

Done. Total: 8.65s
```

**Comment by jarlarntzen** [comment]
@HelloZeroNet I'd like to argue that this should be the default download for OSX. :+1: Thanks!

**Comment by HelloZeroNet** [comment]
https://zeronet.io/ should offer this method by default now.

**Comment by jarlarntzen** [comment]
Fantastic! Thanks! :smile:

**Comment by preswang** [comment]
https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

(Close ZeroNet if already running for you)
Download, unpack, run ZeroNet(.app)

run successful ,but how to exit ZeroNet ?

**Comment by JayBrown** [comment]
From ZeroNet's web GUI, right?

**Comment by HelloZeroNet** [comment]
use the ... menu on ZeroHello

**Comment by althwn** [comment]
@HelloZeroNet  Use  [ZeroBundle-mac-v0.1.1.zip](https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip)  , It works!  thanks~
