### ISSUE TITLE
TorManager Issue

### ISSUE THREAD

**Issue by ASBaumgarten** [HelloZeroNet/ZeroNet#289]
client-104-39-6-244:ZeroNet-master Alexander$ python zeronet.py --tor always
-Starting ZeroNet...
[13:05:55] - OpenSSL loaded, version: 0009081DF
[13:05:55] - Patching sockets to tor socks proxy: 127.0.0.1:9050
[13:05:55] - Version: 0.3.6 r915, Python 2.7.11 (default, Jan  7 2016, 18:32:26)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)], Gevent: 1.0.2
[13:05:55] - Creating FileServer....
[13:05:55] **TorManager** Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 151 > socket.py line 344
[13:05:55] - Creating UiServer....
[13:05:55] - Removing old SSL certs...
[13:05:55] - Starting servers....
[13:05:55] Ui.UiServer --------------------------------------
[13:05:55] Ui.UiServer Web interface: http://127.0.0.1:43110/
[13:05:55] Ui.UiServer --------------------------------------

**Comment by HelloZeroNet** [comment]
http://zeronet.readthedocs.org/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by metulburr** [comment]
I ran into this problem. However i am running Ubuntu 14.04. When i go to that link, i have no where else to go but to debian link, whihc in turns says go to ubuntu wiki, which has nothing to do with tor, and is a rundown of what ubuntu is. If i try to carry out those execution i run into errors

```
metulburr@ubuntu ~/ZeroNet-master  $ echo 'deb http://deb.torproject.org/torproject.org jessie main'>> /etc/apt/sources.list.d/tor.list
bash: /etc/apt/sources.list.d/tor.list: Permission denied
metulburr@ubuntu ~/ZeroNet-master  $ sudo !!
sudo echo 'deb http://deb.torproject.org/torproject.org jessie main'>> /etc/apt/sources.list.d/tor.list
bash: /etc/apt/sources.list.d/tor.list: Permission denied

```

**Comment by scottbontrager** [comment]
Same problem on OS X (El Capitan).  Any ideas for fixing it on a Mac?

- Starting ZeroNet...
[22:11:09] - OpenSSL loaded, version: 0009081DF
[22:11:09] - Version: 0.3.6 r915, Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)], Gevent: 1.0.2
[22:11:09] - Creating FileServer....
[22:11:09] TorManager Tor controller connect error: error: [Errno 61] Connection refused in TorManager.py line 151 > socket.py line 344
[22:11:09] - Creating UiServer....
[22:11:11] - Removing old SSL certs...
[22:11:11] - Starting servers....
[22:11:11] Ui.UiServer --------------------------------------
[22:11:11] Ui.UiServer Web interface: http://127.0.0.1:43110/
[22:11:11] Ui.UiServer --------------------------------------
[22:11:12] FileServer Checking port 15441 using portchecker.co...
[22:11:13] FileServer [OK :)] Port open: Port 15441 is open.

**Comment by ASBaumgarten** [comment]
@metulburr Following the ZeroNet instructions on how to get Tor running I have had no success. I'm on OSX 10.11 and I've just resorted to running Tor on its own along side it. This won't get it to register through the ZeroNet homepage, but it will still mask your real IP if you did it right. You can check if you did it right here: https://check.torproject.org/

@scottbontrager I don't know how to get it working through the ZeroNet files, but you can always run Tor separately by installing it through [Homebrew](http://brew.sh/) `brew install tor` and then run `tor`. It will give you the the the IP and Port which you can then set as a system wide proxy. As with @metulburr go to https://check.torproject.org/ so you know if you did it correctly.

**Comment by scottbontrager** [comment]
@ASBaumgarten Thanks!  Just got it installed and ran it along side.  Unfortunately I got the Big Red X with "Sorry. You are not using Tor.", but I'm new to all this so I'll keep poking around.  Might you be able to point me in the direction of a correctly configured .torrc file?

**Comment by ASBaumgarten** [comment]
@scottbontrager If you have Tor running in Terminal as expected it will be giving you the IP:Port that Tor will work out of. The default is `127.0.0.1:9050`. If you want Tor to run globally go to `System Preferences > Network > Advanced > Proxies > SOCKS Proxy` then enter the IP:Port info in the corresponding boxes. When SOCKS Proxy box has a check-mark your system will try to route all internet traffic through that proxy. When Tor is running this will route all your network traffic through Tor. Just make sure you have the SOCKS Proxy box unchecked when you are done using Tor, otherwise you will only be given errors when trying connect through a browser.

**Comment by metulburr** [comment]
It says i am not using tor

**Comment by scottbontrager** [comment]
@ASBaumgarten **Touchdown!**  Thank you for your help.  Below is my current state and the steps I performed to get here (in case anyone else is interested).

On OS X 10.11.3 I can...
- Visit [](https://check.torproject.org/) in Safari (v9.0.3) and get the Congratulations message
- [ZeroHello](http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D) says "Tor: OK" in the top-right corner of the window
- [YourIP](http://127.0.0.1:43110/1Ey8WR7e3quTdPTMZZKDdqw2U6JG3zvkHe) reports an IP address that is no longer my IP address

By running...
- Tor in one terminal window
- ZeroNet in another terminal window

The steps I followed to get here were...
- Used homebrew to install Tor (`brew install tor`), which installed v0.2.7.6
- Copied the sample torrc file to my home directory (`cp /usr/local/etc/tor/torrc.sample ~/.torrc`)
- Edited my new `.torrc` file and uncommented lines 57 & 61 (`ControlPort 9051` and `CookieAuthentication 1`)
- Started Tor in a terminal window
- Followed @ASBaumgarten's instructions above for configuring my SOCKS Proxy to route through `127.0.0.1:9050`
- Started ZeroNet in another terminal window

**Comment by jdoig** [comment]
I can run zero net fine when both it and tor are run on my host machine (raspberrypi) but when I use the docker container for zeronet (modifying the "FROM" to something suitable) with a tor docker container I also get this error even if I --link tor_instance:tor_instance and pass --proxy tor_instance:9051and export the port in my tor docker... Any ideas?

**Comment by gyulaweber** [comment]
I've managed to make it work (tor + ZeroNet + docker); just see my fork:

- git clone https://github.com/gyulaweber/ZeroNet
- check / update up.sh as necessary (especially the data directory)
- ./up.sh (don't do this if you don't have docker installed)
and it's up & running & tor is working.
even faster: docker pull gyulaweber/zeronet_tor

I'm planning to clean up things a bit and create a pull request from it, so feedbacks are warmly welcomed :)

btw, every command to install & setup tor for ZeroNet is in the Dockerfile.

**Comment by wfjsw** [comment]
@HelloZeroNet 
In a Debian tor installation, ZeroNet has no permission to read /var/run/tor/control.authcookie ,
therefore I have to run ZeroNet under root which is really a bad practice
Is there any workaround of this?
(Disable control auth would be fine since they are on the same machine.)

**Comment by HelloZeroNet** [comment]
@wfjsw yes, please read http://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by wfjsw** [comment]
Got it, thx!

**Comment by border0464111** [comment]
Seem like everyone have solved his problem here. Closing ?
