### ISSUE TITLE
Add terminal use only ?

### ISSUE THREAD

**Issue by MyTheValentinus** [HelloZeroNet/ZeroNet#295]
Add option to disable ui interface and add options to add zeroSite

**Comment by Erkan-Yilmaz** [comment]
via command line one can do already:
siteCreate, siteSign, sitePublish 

see the docs for more info

**Comment by MyTheValentinus** [comment]
Yes but, add website, curl website etc??

**Comment by HelloZeroNet** [comment]
Well, use curl :)
`curl http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/content.json`

**Comment by MyTheValentinus** [comment]
Yes, this work but to addSite into your list ?

**Comment by HelloZeroNet** [comment]
`curl http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D` should work as adding site

**Comment by MyTheValentinus** [comment]
HUmmmm yes i'm so idiot ! Thank man

**Comment by border0464111** [comment]
Seem like it been solved, Closing ?

**Comment by grez911** [comment]
@HelloZeroNet
Please, close the issue.
