### ISSUE TITLE
OS X 10.9 log/error.log not found

### ISSUE THREAD

**Issue by Wolden** [HelloZeroNet/ZeroNet#301]
$ python zeronet.py
- Starting ZeroNet...
.........
File "zeronet.py", line 46, in main
    traceback.print_exc(file=open("log/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'

no such dir or file in Zero-master. Where am I supposed to find it?

**Comment by Wolden** [comment]
OK the log dir is now created. Next prob: 
  File "/Zeronet/src/main.py", line 8, in <module>
    import gevent
ImportError: No module named gevent

where's gevent?

**Comment by HelloZeroNet** [comment]
gevent is a library that needs to be installed to run zeronet. Please try: `python -m pip install gevent msgpack-python`

**Comment by Wolden** [comment]
/usr/bin/python: No module named pip  oups.

**Comment by HelloZeroNet** [comment]
please try sudo easy_install pip

**Comment by ASBaumgarten** [comment]
@Wolden 

1. Install `pip` https://pip.pypa.io/en/stable/installing/
2. Install `gevent` `python -m pip install gevent msgpack-python`
3. Make sure you are in the proper working directory when you run `python zeronet.py'

For instance I have my ZeroNet files on my Desktop `/Users/Alexander/Desktop/ZeroNet/ZeroNet-master`. If you are new to navigating through `bash` I would highly recommend Codecademy's [Learn the Command Line](https://www.codecademy.com/learn/learn-the-command-line) tutorial.

**Comment by HelloZeroNet** [comment]
I think i was able to create a bundle for mac, please help me verify it's working: https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

 - (Close ZeroNet if already running for you)
 - Download, unpack, run ZeroNet(.app)

It should download the latest version from github, start it and open ZeroHello in the browser.

Please also check http://127.0.0.1:43110/Benchmark if everything is ok. (no errors, openssl verify is working, the python version should be 2.7.11)

Thanks!

**Comment by Wolden** [comment]
Sorry for being so long ... Everything seems to work perfectly :-) 

Benchmarking ZeroNet 0.3.6 (rev1069) Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec 6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)] on: darwin...

Thx so much for all :-)

**Comment by davidgarvey** [comment]
I am new to zeronet and am getting the same error using docker.
docker logs 4fc2d61er8e
Traceback (most recent call last):
  File "zeronet.py", line 13, in main
    os.chdir(os.path.dirname(__file__))  # Change working dir to zeronet.py dir
OSError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "zeronet.py", line 67, in <module>
    main()
  File "zeronet.py", line 51, in main
- Starting ZeroNet...
    traceback.print_exc(file=open("log/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'

**Comment by HelloZeroNet** [comment]
Probably relevant: https://github.com/HelloZeroNet/ZeroNet/pull/687

Please update and try again!

**Comment by davidgarvey** [comment]
sweet, it up and working... thanks
