### ISSUE TITLE
Supposet this to be like that? If not then hurry to update the code

### ISSUE THREAD

**Issue by scriptzteam** [HelloZeroNet/ZeroNet#302]
So i have enabled multiuser as kind of zeronet "proxy", but now anyone can edit seeded sites title (those they do not own) and sites description, is there a way to disable it?

**Comment by scriptzteam** [comment]
Oh and now over zeronet forums - https://screencast-o-matic.com/watch/cDeeqi1lyh

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed now: https://github.com/HelloZeroNet/ZeroNet/commit/3f6f273fb1e01b3185793b1f3b4a95a83e6a4608
