### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by Flux3PO** [HelloZeroNet/ZeroNet#303]
I would like to change the Port to whatever I like

**Comment by OliverCole** [comment]
You can run `zeronet.py --ui_port  12345`.

You can see all the config options by running `zeronet.py -h`

**Comment by aplocher** [comment]
How is this done in Windows with ZeroNet.exe?  Do I need to install Python?  It looks like ZeroNet.exe is a wrapper for python27.dll - so AFAIK - no direct way to call the python script without installing python.  Running "ZeroNet.exe -h" (and --help and /?) doesn't work.

**Comment by aplocher** [comment]
N/m, -h doesn't work but --ui_port does with ZeroNet.exe

**Comment by HelloZeroNet** [comment]
To do that create a file named `zeronet.conf` where your zeronet.exe with the content:
```
[global]
ui_port = 12345
```

There is also a `zeronet.cmd` for command line usage.
