### ISSUE TITLE
Delete contact from ZeroMail

### ISSUE THREAD

**Issue by Angristan** [HelloZeroNet/ZeroNet#304]
Hello, it is possible at the moment to delete a contact from the ZeroMail sidebar ? 

Thanks

**Comment by HelloZeroNet** [comment]
Hi, it's not possible yet, but planned later.

**Comment by Angristan** [comment]
Thanks

**Comment by border0464111** [comment]
I recreated the issue in zeromail repository 

https://github.com/HelloZeroNet/ZeroMail/issues/21

**Comment by border0464111** [comment]
Closing ?

**Comment by grez911** [comment]
@HelloZeroNet Please close.
