### ISSUE TITLE
Error Message: "Message wrapper_nonce error, please report!"

### ISSUE THREAD

**Issue by meriken** [HelloZeroNet/ZeroNet#306]
I cannot use ZeroNetwork at all now. What should I do?
![untitled](https://cloud.githubusercontent.com/assets/5530653/13514458/cd9192b0-e15d-11e5-96af-0d4d62335861.png)

**Comment by HelloZeroNet** [comment]
Can you please specify your os/browser version?

**Comment by war59312** [comment]
I get this all the time in both IE 11 and Chrome 50 dev. on Win 8.1 x64.

Refresh via F5 and it normally goes way. Though some times it takes a few tries.

**Comment by HelloZeroNet** [comment]
Do you have antivirus software installed? sometimes it can make strange things

**Comment by war59312** [comment]
I do not.

AntiVirus / AntiMalware / AntiStupid! = My Fingers ;)

I'll do further testing this weekend and see if something else could be causing issues.

**Comment by barrabinfc** [comment]
I'm getting the same error, but only with my site.

It's address is [1P9jGD6MBCieqFCHU1777CgyzoZZcnoba2](http://127.0.0.1:43110/1P9jGD6MBCieqFCHU1777CgyzoZZcnoba2)

I think it has to do with dbschema or data/.*/json being mal-formed or 
sql database not in good shape , since i'm still learning how to code dynamic sites in zeronet.

I would love to dig deeper into this problem, but don't know where to look.
Any recommendation ?

**Comment by meriken** [comment]
F5 did not help. I got the same error after I restarted ZeroNetwork. I also deleted browser cache, but that had no effect either.

Windows 7 Professional 64bit
Google Chrome Version 48.0.2564.116 m

> Z:\ZeroBundle>Python\python.exe -m zerobundle.run https://github.com/HelloZeroNe
> t/ZeroNet start.py
> Starting ZeroNet/start.py...
> Starting ZeroNet...
> [09:46:09] - OpenSSL loaded, version: 01000201F
> [09:46:11] - Version: 0.3.6 r908, Python 2.7.9 (default, Dec 10 2014, 12:24:55)
> [MSC v.1500 32 bit (Intel)], Gevent: 1.0.1
> [09:46:15] - Creating FileServer....
> [09:46:16] TorManager Tor controller connect error: [Errno 10061] No connection
> could be made because the target machine actively refused it.
> [09:46:16] TorManager Starting Tor client tools/tor/tor.exe...
> [09:46:18] TorManager Tor controller connect error: [Errno 10061] No connection
> could be made because the target machine actively refused it.
> Mar 04 09:46:18.797 [notice] Tor v0.2.7.6 (git-7a489a6389110120) running on Wind
> ows 7 with Libevent 2.0.22-stable, OpenSSL 1.0.1q and Zlib 1.2.8.
> Mar 04 09:46:18.798 [notice] Tor can't help you if you use it wrong! Learn how t
> o be safe at https://www.torproject.org/download/download#warning
> Mar 04 09:46:18.808 [notice] Read configuration file "Z:\ZeroBundle\ZeroNet\tool
> s\tor\torrc".
> Mar 04 09:46:18.811 [warn] Path for GeoIPFile (geoip\geoip) is relative and will
>  resolve to Z:\ZeroBundle\ZeroNet\tools\tor\geoip\geoip. Is this what you wanted
> ?
> Mar 04 09:46:18.811 [warn] Path for GeoIPv6File (geoip\geoip6) is relative and w
> ill resolve to Z:\ZeroBundle\ZeroNet\tools\tor\geoip\geoip6. Is this what you wa
> nted?
> Mar 04 09:46:18.811 [warn] Path for DataDirectory (data) is relative and will re
> solve to Z:\ZeroBundle\ZeroNet\tools\tor\data. Is this what you wanted?
> Mar 04 09:46:18.812 [notice] Opening Socks listener on 127.0.0.1:49050
> Mar 04 09:46:18.812 [notice] Opening Control listener on 127.0.0.1:49051
> Mar 04 09:46:18.000 [notice] Bootstrapped 0%: Starting
> Mar 04 09:46:20.000 [notice] Bootstrapped 80%: Connecting to the Tor network
> Mar 04 09:46:20.000 [notice] New control connection opened from 127.0.0.1.
> [09:46:20] - Creating UiServer....
> Mar 04 09:46:21.000 [notice] Bootstrapped 85%: Finishing handshake with first ho
> p
> Mar 04 09:46:22.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
> Mar 04 09:46:22.000 [notice] Tor has successfully opened a circuit. Looks like c
> lient functionality is working.
> Mar 04 09:46:22.000 [notice] Bootstrapped 100%: Done
> [09:48:08] - Removing old SSL certs...
> [09:48:08] - Starting servers....
> [09:48:08] Ui.UiServer --------------------------------------
> [09:48:08] Ui.UiServer Web interface: http://127.0.0.1:43110/
> [09:48:08] Ui.UiServer --------------------------------------
> [09:48:08] - Opening browser: default_browser...

**Comment by meriken** [comment]
The error disappeared when I switched to a different user account on Chrome. How strange...

**Comment by war59312** [comment]
Sounds indeed like a cache of some kind then.

Perhaps Click & Clean:

> https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod

Would fix it if it happens again.

**Comment by vlad20012** [comment]
1. In latest Google Chrome I get this error on every site, can't use at all
2. In  I get this error ONLY on sites created by me

Can someone explain any *normal* reasons of this error? Incorrect JS?

**Comment by vlad20012** [comment]
I receive it always in google chrome, ZeroNet totally not useable, I placed brakepoint at onMessageInner and found that first message looks like
![image](https://cloud.githubusercontent.com/assets/3221931/13591258/f9d70d26-e4f7-11e5-82cb-e0dd8cdfb432.png)
Note: data field is not ZeroNet object at all. WTF is it?

**Comment by HelloZeroNet** [comment]
Nice find, please try to report it to the plugin owner to allow to setup whitelist or allow it on 127.0.0.1.

**Comment by vlad20012** [comment]
I talked with friGate developer. He sayed that it's common practice to use message bus in chrome extensions, and application must filter messages. I have also heard complaints and other extensions, not only friGate, so it seems to be true.

**Comment by HelloZeroNet** [comment]
Ok, so it's not filtering just sending extra messages, this can be solved and will add it in the next version

**Comment by HelloZeroNet** [comment]
I think it's fixed in latest revision https://github.com/HelloZeroNet/ZeroNet/commit/e891a10e54c31468849ed65892ed97bbb548a534#diff-25ec8dd4ba66e508e805a317bc38fa5fR82
Please update & check

**Comment by vlad20012** [comment]
Yep, it's fixed now.

**Comment by HelloZeroNet** [comment]
Thanks
