### ISSUE TITLE
Config Options > Disable Portcheck, Upnp, And Browser 

### ISSUE THREAD

**Issue by war59312** [HelloZeroNet/ZeroNet#308]
Hi,

Please add config options to disable the portcheck, Upnp, and browser opening.

I see there is "--open_browser", but no "--dont_open_browser".

Protcheck is useless in my case since behind VPN and will never forward port.

Same goes for UPnP, no way is that ever getting enabled.

I don't need to see this on every start:

> FileServer Checking port 15441 using portchecker.co...
> FileServer [BAD :(] Port closed: Port 15441 is closed.
> FileServer Trying to open port using UpnpPunch...
> FileServer Checking port 15441 using portchecker.co...
> FileServer [BAD :(] Port closed: Port 15441 is closed.
> FileServer Checking port 15441 using canyouseeme.org...
> FileServer [BAD :(] Port closed: Error: I could not see your service on myIP on port (15441) Reason: Connection refused
> FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress

Thanks,

Will

**Comment by unsystemizer** [comment]
> I see there is "--open_browser", but no "--dont_open_browser".

`--open-browser=no|yes`?

**Comment by HelloZeroNet** [comment]
if you start it with zeronet.py and the `--open_browser` is not present, then it's not opening the browser.

**Comment by war59312** [comment]
Got ya. I see that now. Yea I was just running the cmd that comes with it.

Was hoping I could just put an option in the config file.

I'll just change how I run it.

All good, thanks.

**Comment by HelloZeroNet** [comment]
If you are using zerobundle the open zeronet.sh/cmd/app and change start.py to zeronet.py, then the browser window will not open.

**Comment by war59312** [comment]
Done. Thanks. :)

**Comment by JS-NET** [comment]
Hey i have the same problem, I have a VPN and can not get ZeroNet to run. I am using Raspberry pi 3 (Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
). What can I do to avoid the port error? I am not sure what needs to get edited.

**Comment by HelloZeroNet** [comment]
You are safe to ignore the port error

**Comment by JS-NET** [comment]
Well i do ignore it however, ZeroNet opens up and nothing else happens. On my PC ZeroNet shows the menu and etc updating and what not. On the Raspberry Pi it just opens the ZeroNet homepage with no menu, nothing happens no matter how long I wait.

**Comment by HelloZeroNet** [comment]
You can try to check browser's javascript console (F12) maybe something is blocking the javascript

**Comment by JS-NET** [comment]
seems that running zeronet on epiphany browser lead to a dead end. so i switched browsers and boom, not it works! Thanks!

**Comment by border0464111** [comment]
cool, probably something blocking Javascript indeed, it seem like the issue have been solved for both OP and js-net. Closing ?
