### ISSUE TITLE
Namecoin integration

### ISSUE THREAD

**Issue by thesoftwarejedi** [HelloZeroNet/ZeroNet#31]
Namecoin should be used for publishing sites, which would allow namecoin lookups to the the public key address of a zeronet site.  This completely decentralizes the technology that handles name lookups.
I propose zeronet public addresses should go in a value field "zn" or "0net" within a domain name registered with namecoin.  More info here: https://wiki.namecoin.info/index.php?title=Domain_Name_Specification#Value_field

**Comment by mchelen** [comment]
:+1:

**Comment by HelloZeroNet** [comment]
We need a cross-platform, pure-python dns query lib, so we can use http://www.opennicproject.org/ servers.

**Comment by sull** [comment]
Worth looking at:

https://openname.org/about

https://github.com/openname/openname-resolver

**Comment by HelloZeroNet** [comment]
I have chosen this format, to allow subdomains (@ means zeronetwork.bit without subdomain)
```
    "zeronet": {
        "blog": "1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8", 
        "@": "1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr", 
        "talk": "1TaLk3zM7ZRskJvrh3ZNCDVGXvkJusPKQ"
    }, 
```

But I haven't found any reliable way to resolve this information without installing namecoind.

Using NS TXT record and http://www.opennicproject.org/ could be a workaround:
```
r = DNS.DnsRequest("zeronet.zeronetwork.bit", qtype="TXT", server=['192.71.247.247', '75.127.14.107'], timeout=300)
res = r.req()
res.show() 
```

```
[...]
zeronet.zeronetwork.bit    1109    TXT     ['@:1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr,blog:1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8,talk:1TaLk3zM7ZRskJvrh3ZNCDVGXvkJusPKQ']
[...]
```

**Comment by HelloZeroNet** [comment]
Found this one, it could work (but single point of failure): https://dnschain.info/bit/d/zeronetwork

**Comment by HelloZeroNet** [comment]
a new dnschain server:
https://api.dnschain.net/v1/namecoin/key/zeronetwork.bit

There is an another option to resolve bit domain:

Create a special, dns resolver site that holds all registered zeronet domains in a json file, so everyone has the dns database on localhost.

Pros:
 - Its allows fast and secure dns resolving
 - Does not depends on any central server
 - Nobody can see what domains are you resolving
 - Later it could work well with anonymity networks (tor, i2p)

Cons:
 - It needs a bot that update the database from namecoin transactions
 - If the private key of the site is compromised then its possible to modify dns records

**Comment by HelloZeroNet** [comment]
another alternative:
http://namecha.in/name/d/zeronetwork

**Comment by HelloZeroNet** [comment]
I have done a plugin using 2 dnschain servers, but i'm not satisfied by the result: 

- It takes 1-5 sec to resolve the domain using the 2 servers, by increasing the dns caching time its possible to workaround the problem, but not a real solution for offline/slow connections
- Trusting in 2 servers result not secure enough and I could not find other servers that allows to resolve namecoin json informations

So I decided to take the alternative, [dns resolver site](#issuecomment-78250713) approach. Its developing well, need some more days to finish it.

**Comment by HelloZeroNet** [comment]
Status report: i think everything is working now, if no other bugs found i will publish it tomorrow

**Comment by HelloZeroNet** [comment]
Added Zeroname plugin: b122f471003e3c293513671d7d53f63c7c6d5753
The experimental dnschain plugin also supplied (disabled by default)
Later, if lightweight namecoin client is released it will be also supported.

**Comment by thesoftwarejedi** [comment]
Has this been documented anywhere? 

    "zeronet": {
        "blog": "1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8", 
        "@": "1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr", 
        "talk": "1TaLk3zM7ZRskJvrh3ZNCDVGXvkJusPKQ"
    }

**Comment by HelloZeroNet** [comment]
The "" key means the primary domain, any other than that is a subdomain.

Also added this information to http://127.0.0.1:43110/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F "HOW TO ADD A DOMAIN?" section

**Comment by thesoftwarejedi** [comment]
The "d/" prefix is intended to be .bit domains on the clearnet within the current DNS architecture - something that we shouldn't be concerned about at all.  I'm thinking that using the "d/" prefix is not the optimal solution, and perhaps a new "z/" prefix should be used instead.

Perhaps "z/zeronet" would contain:
    { "addr": 
        { "": "1EU1tbG9oC1A8jz2ouVwGZyQ5asrNsE4Vr", 
          "blog": "1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8"
        }
    "name": "ZeroNet Home",
    .....
    }

Then the url via browser extension or such, would be: 
"zero://zeronet" or "zero://blog.zeronet"
or
"http://zeronet.zero" or "http://blog.zeronet.zero"

Perhaps this is total pie-in-the-sky given that tools for treating namecoin as clearnet DNS are already available so we just hijack the "d/" prefix.  That said, shouldn't we at the least swap out the ".bit" for ".zero"?

Where is a good place to have this discussion?  I also intend on running namecoind local, and would like to plug it into that directly.

**Comment by HelloZeroNet** [comment]
yeah you probably right a custom prefix could be better solution, but i think we can have both: z/ prefix for .zero d/ prefix for .bit.
This allows to use your exitsing domains in zeronet and if someone wants to access your site without zeronet installed (and he able to resolve .bit domains) you can redirect him to a description about zeronet.

Update: I have asked about it in #namecoin and they said there was similar request from i2p and tor, but they rejected it and advised to use d/.

but changing .bit to .zero still sound like a good idea

**Comment by phelix** [comment]
Hi! It would probably be better to stick to .bit: https://forum.namecoin.info/viewtopic.php?f=5&t=1069

**Comment by MAKA02** [comment]
how to possibly add pgp to your website

**Comment by purplesyringa** [comment]
What do you expect 'add[ing] pgp to your website' to do?

**Comment by MAKA02** [comment]
Adding pgp so that people can be able to encrypt and decrypt messages..
within the website



> <https://github.com/HelloZeroNet/ZeroNet/issues/31#issuecomment-925121056>
>

**Comment by purplesyringa** [comment]
You can use encryption already using the CryptMessage plugin. You don't need PGP for that. Check [ZeroMail](https://github.com/HelloZeroNet/ZeroMail) for example.

**Comment by MAKA02** [comment]
Sending me to GitHub makes no sense😏


I said I need something to put on my website so users of this particular
website can use it 😏😏

And I need to activate a password mnemonic
For lost passwords as well

**Comment by purplesyringa** [comment]
> Sending me to GitHub makes no sense I said I need something to put on my website so users of this particular website can use it

That GitHub repository contains sample code for the feature you were asking about, you dumbass.

> And I need to activate a password mnemonic For lost passwords as well

Then you need to implement the password-to-private-key conversion yourself or use a library that provides such a feature.
