### ISSUE TITLE
(Feature Request) Windows Service for ZNet client

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroNet#312]
I'd like ZNet to auto-start whenever I boot my Windows up.

The way to implement this is wrapping the 'executable' (python code) in a Windows service. I'm sure it's quite easy to implement (I've wrapped exes as services before, but not python scripts).

**Comment by HelloZeroNet** [comment]
You can right click to the systray icon and check starts zeronet when windows starts

**Comment by ripper234** [comment]
Is there a systray icon? The version I downloaded two days ago had only a
command line you run manually.
