### ISSUE TITLE
ZeroID user

### ISSUE THREAD

**Issue by Wogker** [HelloZeroNet/ZeroNet#313]
I can not retrieve the user previously created since I closed the session ZeroNet. Is this correct? Now he appears always as "taken".

Regards, Wogker.
http://127.0.0.1:43110/17wdh8t8wV7iVuYeEUgYPHUhkiZfptzVzx

**Comment by HelloZeroNet** [comment]
If you registered it using a zeroproxy and have not saved the private key displayed on first visited, then it's lost.
If you using local client and have not reinstalled zeronet, then it should be recovered when you visit the zeroid site.
