### ISSUE TITLE
TorClient integration

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroNet#314]
https://github.com/torproject/tor/issues/5

It would be cool if you could just launch TorClient and do http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/?Home

**Comment by HelloZeroNet** [comment]
This is two separate project, if you have zeronet running then you can browse zeronet sites in the tor browser using http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/
