### ISSUE TITLE
Create Self Contained .app Bundle for OSX

### ISSUE THREAD

**Issue by balupton** [HelloZeroNet/ZeroNet#316]
This is meant to be used by non-technical people eventually right? I'm not sure many non-technical people, even myself as a technical people, are that enthused about installing homebrew, python, dev deps, running arbitrary commands, and then getting the app.

**Comment by HelloZeroNet** [comment]
It would be nice, but I don't have access to OSX machine

**Comment by iShift** [comment]
What app you use for windows? py2app?

**Comment by HelloZeroNet** [comment]
No, it's just a packed version of installed python.

**Comment by balupton** [comment]
I could probably set up a virtual machine and give you remote access into it - although it would probably be extremely slow

**Comment by HelloZeroNet** [comment]
I think i was able to create a bundle for mac, please help me verify it's working: https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

Download, unpack, run ZeroNet(.app)

It should download the latest version from github, start it and open ZeroHello in the browser.

Please also check http://127.0.0.1:43110/Benchmark if everything is ok. (no errors, openssl verify is working, the python version should be 2.7.11)

Thanks!

**Comment by iShift** [comment]
@HelloZeroNet it works, but you should move Folders (lib,ssl,Python...) inside of .app

**Comment by HelloZeroNet** [comment]
@iShift Thanks! What's version of OSX are you using?

**Comment by iShift** [comment]
Last 10.11.3 (El Capitan) but for proper test we need clean system without home-brew and python install, on next week i try to install fresh system to virtual machine and try this again

**Comment by jackassdead** [comment]
it does work fine...thank you man!
can you even fix the tor thing.

**Comment by cyranodb** [comment]
On my Mac with Mavericks, the ZeroNet app (v 0.1.1) shows up as a Classic app (eg OS9 days, ca. 1998). Of course, this doesn't run as Classic went the way of the Dodo many years ago.

Any idea how to solve this and why?

**Comment by HelloZeroNet** [comment]
You have to open a terminal and drop the zeronet.app to it

**Comment by cyranodb** [comment]
Thanks, I already found that out when I noticed the "app" was only 123 bytes. So I figured it was probably a shell script, but I was puzzled why I couldn't open it for inspection in an editor.

It will throw off newbies, who will all expect to run it as an app tho.

But thanks again for a *very speedy* reply!

**Comment by HelloZeroNet** [comment]
It works with double-click on latest osx, the Terminal dropping is only requred for older versions

I have created a proper .app that works on all osx, but it needs to be signed that i unable to do. (needs apple osx dev certificate)

more info: https://github.com/HelloZeroNet/ZeroNet/issues/363
