### ISSUE TITLE
(Multi-User Plugin) Media referrer error

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroNet#317]
I'm using the multi-user plugin.
Steps to reproduce:

1. Run the bundle
2. An account is created for you. Save the private key.
3. Kill python process (I don't know how to gracefully terminate the bundle)
4. Run the bundle again
5. A new account is created.
6. Choose to login.
7. Paste the private key created in 2.

Bam:

> Forbidden
> 
> Media referrer error
> 
> Please report it if you think this an error.
> 
> Details:
> 
> {
>     "GATEWAY_INTERFACE": "CGI/1.1", 
>     "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
>     "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch", 
>     "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8,he-IL;q=0.6,he;q=0.4", 
>     "HTTP_HOST": "zero", 
>     "HTTP_PROXY_CONNECTION": "keep-alive", 
>     "HTTP_REFERER": "http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D?login=done", 
>     "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
>     "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36", 
>     "PATH_INFO": "http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/", 
>     "QUERY_STRING": "login=done&wrapper_nonce=71a58fbc7fe0b4a14b46f51fa7401f4a85602bf804982dc5ea91bbbecba249e3", 
>     "REMOTE_ADDR": "127.0.0.1", 
>     "REMOTE_PORT": "51025", 
>     "REQUEST_METHOD": "GET", 
>     "SCRIPT_NAME": "", 
>     "SERVER_NAME": "Lenovo-PC", 
>     "SERVER_PORT": "43110", 
>     "SERVER_PROTOCOL": "HTTP/1.1", 
>     "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
>     "arguments": {
>         "action": "main", 
>         "batch": false, 
>         "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
>         "config_file": "zeronet.conf", 
>         "data_dir": "data", 
>         "debug": false, 
>         "debug_socket": false, 
>         "disable_encryption": false, 
>         "disable_sslcompression": true, 
>         "disable_udp": false, 
>         "fileserver_ip": "*", 
>         "fileserver_port": 15441, 
>         "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
>         "ip_external": null, 
>         "keep_ssl_cert": false, 
>         "log_dir": "log", 
>         "msgpack_purepython": true, 
>         "open_browser": "default_browser", 
>         "proxy": null, 
>         "size_limit": 10, 
>         "stream_downloads": false, 
>         "tor": "enable", 
>         "tor_controller": "127.0.0.1:9051", 
>         "tor_proxy": "127.0.0.1:9050", 
>         "trackers": [
>             "zero://boot3rdez4rzn36x.onion:15441", 
>             "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
>             "udp://tracker.coppersurfer.tk:6969", 
>             "udp://tracker.leechers-paradise.org:6969", 
>             "udp://9.rarbg.com:2710", 
>             "http://tracker.aletorrenty.pl:2710/announce", 
>             "http://explodie.org:6969/announce", 
>             "http://torrent.gresille.org/announce"
>         ], 
>         "trackers_file": false, 
>         "ui_ip": "127.0.0.1", 
>         "ui_port": 43110, 
>         "ui_restrict": false, 
>         "use_openssl": true, 
>         "use_tempfiles": false
>     }, 
>     "plugins": [
>         "AnnounceZero", 
>         "CryptMessage", 
>         "Multiuser", 
>         "Newsfeed", 
>         "Sidebar", 
>         "Stats", 
>         "Trayicon", 
>         "Zeroname"
>     ], 
>     "version_gevent": "1.0.1", 
>     "version_python": "2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]", 
>     "version_zeronet": "0.3.6 r915", 
>     "wsgi.url_scheme": "http"
> }

**Comment by HelloZeroNet** [comment]
The multi-user plugni is not compatible with the chrome plugin, so you need to use it via http://127.0.0.1:43110

**Comment by grez911** [comment]
> Kill python process (I don't know how to gracefully terminate the bundle)

![screenshot from 2016-05-09 17 10 22](https://cloud.githubusercontent.com/assets/12672853/15115861/a4fab364-1609-11e6-9870-6d13cbc52f3b.png)
