### ISSUE TITLE
Incompatible key from non-Multiuser and Multiuser

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroNet#318]
I just enabled Multiuser plugin, and I'm trying to login with my previous ID from before.

I looked up "auth_privatekey" in users.json (no multiuser).
"auth_privatekey" there has various numbers & uppercase letters.

The private keys for IDs I created while using multiuser look different: different length + all lowercase hex.

It seems like the two private keys use different formats. I am not able to login to my old ID while using multiuser.

**Comment by HelloZeroNet** [comment]
You need to enter the master_seed from users.json.

**Comment by dluciv** [comment]
> You need to enter the master_seed from users.json

ZeroID does not handle it though. The only way to pass it to ZeroID is to add it to `users.json` and launch ZeroNet with `--multiuser_local` option.
