### ISSUE TITLE
Unicode characters aren't supported at content.json

### ISSUE THREAD

**Issue by quasiyoke** [HelloZeroNet/ZeroNet#32]
My site uses cyrillic characters at title and description http://127.0.0.1:43110/18C5HmyTt5Ua4WdyESp3mgmrCwVMPc4yw2 Cyrillic characters tend to Python's UnicodeEncodeError.
After I've published it once, ZeroNet allows me to publish latin version of this fields, but downloads old version of site from some peer immediately.

**Comment by quasiyoke** [comment]
Sorry, for publishing I need to "sign" the site. But encoding problem is still actual.

**Comment by HelloZeroNet** [comment]
thanks, fixed by your push
