### ISSUE TITLE
Site clone occasionally fails in UI

### ISSUE THREAD

**Issue by unsystemizer** [HelloZeroNet/ZeroNet#321]
On blog clone from the Web UI using 0.3.5, I got this error:

```
Internal error: IOError: [Errno 2] No such file or directory: u'data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/data-default/data.json'
UiWebsocket.py line 96 > UiWebsocket.py line 172 > UiWebsocket.py line 582 > Site.py line 442 > shutil.py line 119 > shutil.py line 82
```

The 2nd try worked.
Maybe because I didn't visit the original blog prior to that. In that case a fix would be to download the site if the directory doesn't exist.

**Comment by grez911** [comment]
@unsystemizer How can you clone site via WebUI without visiting it previously? Is it still an issue?

**Comment by unsystemizer** [comment]
I don't remember now, but I think I saw a link to a site, then right-clicked to clone it. If it's now not possible to clone a site that hasn't been visited, this can be closed

**Comment by grez911** [comment]
I didn't find a way to do this. Maybe @HelloZeroNet can help?

**Comment by blurHY** [comment]
Oh,this is a very old issue.
@shortcutme Consider to use a bot to close outdated issues

**Comment by HelloZeroNet** [comment]
I think this can be still an issue if someone wants to clone the site before it was fully downloaded

**Comment by DaniellMesquita** [comment]
How it works now after the fix?

**Comment by DaniellMesquita** [comment]
Now it remembers the request and clones after fully downloaded?

**Comment by HelloZeroNet** [comment]
No, you have to wait until the download finishes

**Comment by DaniellMesquita** [comment]
ZN could receive a Queue feature, which could include clonning
