### ISSUE TITLE
$ python zeronet.py

### ISSUE THREAD

**Issue by lamotte** [HelloZeroNet/ZeroNet#325]
- Starting ZeroNet...
Traceback (most recent call last):
  File "/Users/yoannlamotte/ZeroNet-master/zeronet.py", line 15, in main
    import main
  File "/Users/yoannlamotte/ZeroNet-master/src/main.py", line 79, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/Users/yoannlamotte/ZeroNet-master/src/Plugin/PluginManager.py", line 27, in loadPlugins
    for dir_name in os.listdir(self.plugin_path):
OSError: [Errno 2] No such file or directory: 'plugins'

Where am I supposed to find it? please

**Comment by HelloZeroNet** [comment]
probably you have not unpacked it right, please make sure you have the same files/dirs as in: https://github.com/HelloZeroNet/ZeroNet

**Comment by lamotte** [comment]
I have the same files/dirs as in : https://github.com/HelloZeroNet/ZeroNet

**Comment by lamotte** [comment]
and this problem it not resolve.

**Comment by HelloZeroNet** [comment]
are you sure you are in the right directory and you running it using `python zeronet.py` ?

**Comment by lamotte** [comment]
yes, I'm sure.

**Comment by HelloZeroNet** [comment]
please try this one: https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

just download, unpack and run ZeroNet(.app)

**Comment by lamotte** [comment]
thank you.

**Comment by HelloZeroNet** [comment]
Is it working for you?

**Comment by lamotte** [comment]
yes :)

**Comment by HelloZeroNet** [comment]
nice :)
