### ISSUE TITLE
Inconsistent newsfeed on homepage

### ISSUE THREAD

**Issue by ripper234** [HelloZeroNet/ZeroNet#326]
When I open the main zeronet website (using the same account/masterseed, two different computers):

One shows "Welcome to ZeroNet - Let's build a decentralized internet together".
The other instance shows my newsfeed.

(Same URL for both sites: http://zero/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D)

Why does it sometimes work, and sometimes not?

**Comment by ripper234** [comment]
I think this may be related to MultiUser plugin. I switched from disabled-MultiUser to MultiUser, and I think that switched killed my newsletter / follow list.

**Comment by HelloZeroNet** [comment]
Added local multiuser mode to latest revision that is fixes this issue.

To enable it you have to start it using `--multiuser_local` parameter or create a zeronet.conf where your zeronet.py file is with this content:
```
[global]
multiuser_local
```

**Comment by crazysoldier** [comment]
Damn that gives me zeronet.py: error: unrecognized arguments: --multiuser_local on ubuntu ... :/

**Comment by HelloZeroNet** [comment]
You need to enable the plugin first by renaming `plugins/disabled-Multiuser` to `plugins/Multiuser`
