### ISSUE TITLE
[BUG] illegal hardware issue (OS X 10.11.3)

### ISSUE THREAD

**Issue by JayBrown** [HelloZeroNet/ZeroNet#330]
ZeroNet used to work great on OS X 10.11.3 with Safari 9.0.3. But since upgrading pip and gevent to the latest versions a couple of minutes ago, I'm getting the python error message "illegal hardware instruction". What's up with that?

**Comment by HelloZeroNet** [comment]
never seen that error, please try https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip it has everything packed in.

**Comment by JayBrown** [comment]
I'd first like to see what the problem is before chickening out. Here's the error report after running it manually in the shell:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   corecext.so                   	0x000000010179ec85 initcorecext + 19669

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000001017a26d0  rbx: 0x000000010174e390  rcx: 0x000000010173fea8  rdx: 0x000000010173b000
  rdi: 0x0000000000000088  rsi: 0x0000000000000f98  rbp: 0x0000000000000079  rsp: 0x00007fff5ea851f0
   r8: 0x00000001017317e8   r9: 0x00000000ffffff80  r10: 0x0000000000000600  r11: 0x0000000000000000
  r12: 0x00000001017317e8  r13: 0x56004951db03fdb1  r14: 0x0000000101670560  r15: 0x0000000101752b50
  rip: 0x000000010179ec85  rfl: 0x0000000000010202  cr2: 0x000000010179e217
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

**Comment by HelloZeroNet** [comment]
Maybe somehow you have installed 32bit module for 64bit python or vica-versa.

via http://stackoverflow.com/questions/16386707/python-django-on-a-mac-illegal-hardware-instruction

**Comment by JayBrown** [comment]
Probably. Python (in /usr/local/bin) is 64bit, as the default one installed with OS X. Couldn't find the error. Maybe the gevent update messed it up. 

The OS X bundle doesn't work either. Doesn't connect to ZeroNet when launching the .app directly in Finder, and launching it from the Terminal (zsh) with the open command I get the following error:

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/ZeroNet/ZeroNet.app.

**Comment by HelloZeroNet** [comment]
/Applications are special folder:
```
If you have your binary stored in your Applications folder you can do this and it should fix it:

# sudo chmod + x /Applications/Twine.app/Contents/MacOS/Twine
```
via https://groups.google.com/forum/#!topic/tweecode/3X7oJxxYHpg

**Comment by JayBrown** [comment]
Ah, found the error… the .app and the included python binary weren't codesigned. I removed them from quarantine, and now it works.
