### ISSUE TITLE
Security: Any site may call certAdd for any domain

### ISSUE THREAD

**Issue by vlad20012** [HelloZeroNet/ZeroNet#331]
For example
```coffeescript
@cmd "certAdd", ["zeroid.bit", "atype1", "username", "sign"]
```

Then the user will not be able to register at zeroid.bit.

it is easy to fix: just compare domain name with current in UiWebsocket.actionCertAdd

**Comment by vlad20012** [comment]
Live example: http://127.0.0.1:43110/1G9sW6n1wqhUnoHLKEkycKM8sVgazFvFc

**Comment by HelloZeroNet** [comment]
Probably a confirmation dialog of "You already have certificate for zeroid.bit, do you want to change it?" would be better if cert is already exists

**Comment by vlad20012** [comment]
It is good solution too, but what the problem to add one if statement with comparition domain to site.settings[domain]?

**Comment by HelloZeroNet** [comment]
The domain plugin is optional and not restricting it by site domain would allow to recover your ID even if ZeroID site is disappear for some reasons.

**Comment by vlad20012** [comment]
What about confirmation dialog if domains not equal (even if cert not exists)?

**Comment by vlad20012** [comment]
I think it's reasonable to add the ability to redefine or even delete certificates. Otherwise, services are advised to remove them manually. For example http://127.0.0.1:43110/16KzwuSAjFnivNimSHuRdPrYd1pNPhuHqN

**Comment by alxbob** [comment]
How did you give authorization to users to your site? I dont understand http://127.0.0.1:43110/16KzwuSAjFnivNimSHuRdPrYd1pNPhuHqN . Is this your private key L21fbJbceebx6B3bwMK2U46W1Un7peLqBtPjfyARZpxsME9rxWFz?

**Comment by vlad20012** [comment]
@alxbob It is a question for me? It's not my site. I just learned how it (and zeroID) works. Any authorization service (including zeroID) is only associating username with public key. On "Nanasi text board" you sign the certificate yourself, so anybody can choose any username (one username may be associated with two or more public keys). It is quite useless service because you can work directly with public keys without usernames.

**Comment by alxbob** [comment]
I think users can sign their certificates and username / public key pair could be written/added in a users.json inside the site

**Comment by alxbob** [comment]
Can something like that apply to zeronet id?

**Comment by HelloZeroNet** [comment]
Added confirmation if cert with the same domain already exists: https://github.com/HelloZeroNet/ZeroNet/commit/9bb0a0d91b38c15bcda81676ca41b85abe187079
