### ISSUE TITLE
edited site with problems

### ISSUE THREAD

**Issue by mama21mama** [HelloZeroNet/ZeroNet#332]
edited site with problems

http://127.0.0.1:43110/18nQPR4TCM4tQ8L7fm6dX6SGXLsj7wa8sv

people began to enter and leave the chat lines, files started doing his thing and larger data base.

I created the site. by a bug in the code chat site I delete it completely.

I upload the site again.

that's where things appear in the first place. data first version of the site.

I thought that must be respected a full erase. and peer obey the order of that completely erased and not mix old data with the new site.

[![imagebin](http://upimage.mamalibre.com.ar/up/e40ab3aa9d388f63330e15a388011d79.png)](http://upimage.mamalibre.com.ar/#e40ab3aa9d388f63330e15a388011d79.png)

**Comment by border0464111** [comment]
Did you sign and publish at every step ?

**Comment by grez911** [comment]
> Did you sign and publish at every step ?
I think he is talking about user content. There is need for some means to forbid uploading users content which is older than site deletion date. In the current state it is not possible.

**Comment by purplesyringa** [comment]
@HelloZeroNet Not sure if we can close this issue because of inactivity? Also, deleting the whole site is not a good idea and I guess we can't fix the problem because site owner shouldn't delete users' content.
