### ISSUE TITLE
sites.Json is case-sensitive

### ISSUE THREAD

**Issue by MoreJ** [HelloZeroNet/ZeroNet#333]
As the title states, the sites.json file is case-sensitive which results in sites being listed multiple times with different capitalization. In turn, this makes the ZeroNet front page list the same site multiple times in the sidebar.

**Comment by HelloZeroNet** [comment]
I dont understad, the sites.json contains the site's bitcoin address (eg. 1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT), which is case-sensitive

**Comment by MoreJ** [comment]
I have these three entries for the exact same site:
"1Mr5rX9TauvaGReB4RjCaE6D37FJQaY5Ba": {
    [stuff]
  }, 
"1mr5rx9tauvagreb4rjcae6d37fjqay5bA": {
    [stuff]
  }, 
  "1mr5rx9tauvagreb4rjcae6d37fjqay5ba": {
    [stuff]
  }, 

As you can see, the address is identical. And, indeed, when navigating to the site, all three point to the same site. All the same folder. This results in having the site listed 3 times in the sidebar. See the attached image. 

![screen shot 2016-03-07 at 1 08 50 am](https://cloud.githubusercontent.com/assets/4239836/13564814/355091b2-e401-11e5-98b3-202f5355115d.png)

The only difference between them is the case-sensitivity, which is entirely irrelevant it seems when navigating to the site, and managing the site folder. Further, the system doesn't allow me to delete the 'real' one (the one with proper case sensitivity that was generated automatically) due to owning it, however, the other two are freely able to be deleted.

From what I can tell, this happens when you navigate to a site using improper case. I can't imagine this is the intended functionality.

**Comment by HelloZeroNet** [comment]
Fixed: https://github.com/HelloZeroNet/ZeroNet/commit/48db062b49bded23db2a6cfd35a836d5c2d0e77b#diff-9af49b2fc8a9d6fa47722290019d9104R57

(you have to delete the entries from sites.json manually)
