### ISSUE TITLE
TOR: AddOnion error (510 Unrecognized command "ADD_ONION" )

### ISSUE THREAD

**Issue by scriptzteam** [HelloZeroNet/ZeroNet#335]
Can you add option for tor to use ControlPassword not CookieAuth, maybe thats works better

**Comment by HelloZeroNet** [comment]
The auth work, but you need Tor 0.2.7.5+: http://zeronet.readthedocs.org/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by scriptzteam** [comment]
Ah, Ubuntu 15.10 latest is Tor 0.2.6.10 (recommended) :D Too lazy togo and build ... thx anyway
