### ISSUE TITLE
content.json download failed

### ISSUE THREAD

**Issue by dx486** [HelloZeroNet/ZeroNet#338]
I use debian 8.3 and I installed Zeronet using the guide written [here](https://github.com/HelloZeroNet/ZeroNet).

I see following error when I start Zeronet:

http://pastebin.com/XWtyvgA4

I see following error on webpage (http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D):

> Connecting...
> Peers found: 32
> content.json download failed

**Comment by HelloZeroNet** [comment]
please check if http://127.0.0.1:43110/Benchmark runs without any error and maybe log/debug.log have more detailed information. (you can also send it to me: hello@zeronet.io)

Can you please also try the ZeroBundle package?
- wget https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-linux64-v0.1.1.tar.gz
- tar xvpfz ZeroBundle-linux64-v0.1.1.tar.gz
- cd ZeroBundle
- ./ZeroNet.sh

**Comment by dx486** [comment]
Benchmark:
http://pastebin.com/RxwGr2Ck

With Bundle:
http://pastebin.com/tB6fRD69

By the way, I am connected to internet via an OpenVPN server. Sorry I forgot mentioning earlier.

**Comment by dx486** [comment]
> and maybe log/debug.log have more detailed information. (you can also send it to me: hello@zeronet.io)

I looked at /var/log but I am not sure which file you need.

**Comment by HelloZeroNet** [comment]
there should be a log and a data directory where you started ./ZeroNet.sh

**Comment by dx486** [comment]
I have sent an email to you with debug.log attached.

**Comment by HelloZeroNet** [comment]
Thanks, got it. It's looks like a network error, the connections are timeouting.

**Comment by dx486** [comment]
It looks like this error happens when I am connected to VPN. Without VPN I can connect.

**Comment by border0464111** [comment]
The Errors also looks like a network problem to me, Having it working without the VPN is telling us that the problem is more on the VPN side then Zeronet.
