### ISSUE TITLE
Zeronet barely functional in Safari for Mac

### ISSUE THREAD

**Issue by TheMacMini09** [HelloZeroNet/ZeroNet#34]
I've mostly been using Zeronet in Firefox/Chrome for Mac, and they've been working fine. However, when trying to connect in Safari, there are a few problems. One, the flipping red square is white with a 1px red border (after it drops; as it's dropping it's red), two, dynamic content doesn't work (ZeroBlog is blank). It seems to be a problem with Ghostery (maybe?) but it worked fine with Ghostery in Chrome. Web Console messages: 
`[Error] Sandbox access violation: Blocked a frame at "http://themacmini09.agrius.feralhosting.com:43110" from accessing a frame at "http://themacmini09.agrius.feralhosting.com:43110".  The frame requesting access is sandboxed and lacks the "allow-same-origin" flag.
	global code (ghostery-min.js, line 8)`

`[Error] Error: Syntax error, unrecognized expression: .messages .message:not(.template
	error (all.js, line 7)
	tokenize (all.js, line 7)
	select (all.js, line 7)
	gb (all.js, line 7)
	find (all.js, line 7)
	init (all.js, line 7)
	n (all.js, line 7)
	(anonymous function) (all.js, line 654)
	j (all.js, line 7)
	fireWith (all.js, line 7)
	x (all.js, line 9)
	(anonymous function) (all.js, line 9)`

I have tried whitelisting the site in Ghostery, and even disabling it (which only removed the first error).

**Comment by shakna-israel** [comment]
How did you set up the change of domain?

(From 127.0.0.1)

How does the VPS expose public access?

**Comment by TheMacMini09** [comment]
I am running ZeroNetProxy (in this example) on the VPS - however, it works perfectly fine in other browsers, and running off of the local machine doesn't fix the issue - errors are identical (except for the domain, of course).

**Comment by shakna-israel** [comment]
From what I can find, Safari is simply a pain in the butt when it comes to CORS, something used inside ZeroNet.

It might be necessary to add:

```
Access-Control-Allow-Origin: http:127.0.0.1:43110 | *
```

To the header on the server, to make it work.

This is something that ZeroNet needs, I'll look into it and make a pull request if I can find a way to do it nicely. (Without breaking everything in sight).

As a by note, you probably want to update [ZeroNetProxy](https://github.com/zeronetproxy/ZeroNetProxy), so that you can find updating in future a hell of a lot less painful.

**Comment by HelloZeroNet** [comment]
Unfortunately I don't have access to any OSX machine, so I cant test or fix it.

**Comment by iShift** [comment]
Now all is good on os x safari 
![2015-02-28 14 40 45](https://cloud.githubusercontent.com/assets/426427/6426056/e88fde6a-bf57-11e4-949f-26dc4aa6cc96.png)

Only one warning and no errors

**Comment by TheMacMini09** [comment]
Great, thanks! I'll test it out later today.
