### ISSUE TITLE
site too large; problems come

### ISSUE THREAD

**Issue by mama21mama** [HelloZeroNet/ZeroNet#342]
[![imagebin](http://upimage.mamalibre.com.ar/up/ffa3b067138e8b8f41cbdc844096fa57.png)](http://upimage.mamalibre.com.ar/#ffa3b067138e8b8f41cbdc844096fa57.png)

example site: http://127.0.0.1:43110/191C1ggdcP31gFfTtwxH1CBSycXF7tR8uC (probably all **NSFW**)

2GB size
191C1ggdcP31gFfTtwxH1CBSycXF7tR8uC/data/webm/*.webm

not open the index. that politics is first download everything.

there is when you stop sharing and distribution and is no longer hosting collaborative.

**Comment by HelloZeroNet** [comment]
This is a bad idea, please define it as optional files
