### ISSUE TITLE
ERROR] Only ascii encodes filenames

### ISSUE THREAD

**Issue by mama21mama** [HelloZeroNet/ZeroNet#343]
Site:17JcQZ..yi7F - [ERROR] Only ascii encodes filenames allowed: img/sitio_gran_tamaño.png

**Comment by HelloZeroNet** [comment]
Thanks, fixed!

**Comment by bAndie91** [comment]
> Thanks, fixed!

could you point to the corresponding commit?

**Comment by imachug** [comment]
After 3 years? I don't think so.
