### ISSUE TITLE
CSS/JS Merging

### ISSUE THREAD

**Issue by bim9262** [HelloZeroNet/ZeroNet#344]
The merging is described as doing the following: 

> Order in which files are merged into all.css/all.js: Files inside subdirectories of the css/js folder comes first; Files in the css/js folder will be merged according to file name ordering (01_a.css, 02_a.css, etc)

The blog, for example would compile in this order:
generated with
`for file_path in findfiles(merge_dir, find_ext):`
&nbsp;&nbsp;&nbsp;&nbsp;`print file_path():` 
and 
`print root, dirs, files` added to `findfiles`

data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils [] ['Time.coffee', 'Follow.coffee', 'RateLimit.coffee', 'Text.coffee', 'ZeroFrame.coffee', 'Menu.coffee', 'Class.coffee', 'InlineEditor.coffee']
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/Class.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/Follow.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/InlineEditor.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/Menu.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/RateLimit.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/Text.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/Time.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/utils/ZeroFrame.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib [] ['highlight.pack.js', 'jquery.cssanim.coffee', 'identicon.js', 'all.js', 'marked.min.js', 'pnglib.js', 'jquery.csslater.coffee', '00-jquery.min.js']
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/00-jquery.min.js
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/highlight.pack.js
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/identicon.js
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/jquery.cssanim.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/jquery.csslater.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/marked.min.js
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/lib/pnglib.js
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js ['utils', 'lib'] ['all.js.old', 'all.js', 'Comments.coffee', 'ZeroBlog.coffee']
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/Comments.coffee
data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/js/ZeroBlog.coffee

This puts the the js/utills file before js/lib before js and also break the fact that some of the files in js/utils is dependent on 00-jquery.min.js. Is the intended effect to sort the files regardless of which directory they are from or to sort them as follows?

js
├── lib
│   ├── 00-jquery.min.js
│   ├── highlight.pack.js
│   ├── identicon.js
│   ├── jquery.cssanim.coffee
│   ├── jquery.csslater.coffee
│   ├── marked.min.js
│   └── pnglib.js
├── utils
│   ├── Class.coffee
│   ├── Follow.coffee
│   ├── InlineEditor.coffee
│   ├── Menu.coffee
│   ├── RateLimit.coffee
│   ├── Text.coffee
│   ├── Time.coffee
│   └── ZeroFrame.coffee
├── Comments.coffee
└── ZeroBlog.coffee

**Comment by tomasbond** [comment]
How can i add video.js in this? Is it possible?

**Comment by bim9262** [comment]
After some consideration it seems that it would make more sense to have files go in recursive decent order (sorted on folder names), with the files being listed before the decent which would give an order like this:

```
js
├── 00-lib
│       ├── 00-jquery.min.js
│       ├── highlight.pack.js
│       ├── identicon.js
│       ├── jquery.cssanim.coffee
│       ├── jquery.csslater.coffee
│       ├── marked.min.js
│       └── pnglib.js
└── ClassAnimal
            ├── Animal.js
            ├── ClassMammal
            │        ├── Mammal.js
            │        ├── ClassCat
            │         |        ├── Cat.js
            │        └── ClassDog
            │                   └── Dog.js
            └── ClassReptile
                       ├── ClassSnake
                        |         ├── Snake.js
                       └── ClassTurtle
                                  └── Turtle.js
```

This would allow better management of code with a high level of dependencies.

BTW, I don't mind doing the coding, if there is buy in. 
I am not able to currently compile the js for the ZeroBlog with the code on github, with the current implementation because the order of the dependencies is broken.

**Comment by HelloZeroNet** [comment]
can you please specify your platform?

**Comment by bim9262** [comment]
Linux (Arch) Python 2.7.11

**Comment by HelloZeroNet** [comment]
Probably fixed in latest version, please verify: https://github.com/HelloZeroNet/ZeroNet/commit/ff681adfe9e92f8f139347499c35783ed47160a4

**Comment by bim9262** [comment]
It works on the ZeroBlog sample. I haven't tested to see how it holds up on nested sub-directories, although I didn't see any official mention on how that would be handled anyways. What is the intended behaviour?

**Comment by HelloZeroNet** [comment]
- Files in sub-directories first ordered by directory and filenames
 - Then files in parent directories ordered by name

for zeroblog:
```
js/lib/00-jquery.min.js
js/lib/highlight.pack.js
js/lib/identicon.js
js/lib/jquery.cssanim.coffee
js/lib/jquery.csslater.coffee
js/lib/marked.min.js
js/lib/pnglib.js
js/utils/Class.coffee
js/utils/Follow.coffee
js/utils/InlineEditor.coffee
js/utils/Menu.coffee
js/utils/RateLimit.coffee
js/utils/Text.coffee
js/utils/Time.coffee
js/utils/ZeroFrame.coffee
js/Comments.coffee
js/ZeroBlog.coffee
```

**Comment by bim9262** [comment]
What if I also have some plugins in js/lib for example?
`js/lib/plugins/jquery.colorbox-min.js`

Is this the correct order?
```
js/lib/00-jquery.min.js
js/lib/highlight.pack.js
js/lib/identicon.js
js/lib/jquery.cssanim.coffee
js/lib/jquery.csslater.coffee
js/lib/marked.min.js
js/lib/pnglib.js
js/lib/plugins/jquery.colorbox-min.js
js/utils/Class.coffee
js/utils/Follow.coffee
js/utils/InlineEditor.coffee
js/utils/Menu.coffee
js/utils/RateLimit.coffee
js/utils/Text.coffee
js/utils/Time.coffee
js/utils/ZeroFrame.coffee
js/Comments.coffee
js/ZeroBlog.coffee
```

**Comment by HelloZeroNet** [comment]
Looks right for me (jquery colorbox depends on jquery)

**Comment by bim9262** [comment]
True, but it seems weird that the outermost directory is treated differently than any of the sub-directories.

It seems that `js/Comments.coffee` and `js/ZeroBlog.coffee` would come before any of the files just as all of the `js/lib` files come before the `js/lib/plugins` files. Of course this would break `class ZeroBlog extends ZeroFrame`.
