### ISSUE TITLE
how you retake ownership of a zeroblog ?

### ISSUE THREAD

**Issue by dontspamm** [HelloZeroNet/ZeroNet#345]
so lets say i want to retake ownership of a zeroblog if i lose my local copy and i still have the secretkey

**Comment by HelloZeroNet** [comment]
Just copy data/users.json to new installation.

**Comment by dontspamm** [comment]
so i copy the 
ZeroNet-master/data/user.json 

to

/ZeroNet-master/data/123456789xxxxxxxxx/data/users.json

???

**Comment by HelloZeroNet** [comment]
no, copy ZeroNet-master/data/users.json to NewInstalledZeroNet-master/data/users.json. (if you copy it to your site's directory then you will publish it to everyone your privatekey, so anyone would able to modify your blog)

**Comment by dontspamm** [comment]
thats is not relevant to my question then 

i asked how to retake owner ship to a blog if i lose the local copy

**Comment by HelloZeroNet** [comment]
Just open the blog, the files will be downloaded from other peers.
