### ISSUE TITLE
tor running but /Stats show mixed peers

### ISSUE THREAD

**Issue by dontspamm** [HelloZeroNet/ZeroNet#346]
for some season when i look on /Stats there are some peers that are not TOR, why ?

**Comment by bim9262** [comment]
are you using the flag: `--tor always`?

**Comment by dontspamm** [comment]
nope, so i need to force tor settings ?

**Comment by bim9262** [comment]
The default is `enable`, not `always`. I haven't set it up to work tor, so I can't confirm, but it seems like the logical flag to enable the desired behaviour.

**Comment by HelloZeroNet** [comment]
even if you are on --tor always you will see mixed peers. the non-onion peers are connected using exit nodes.
