### ISSUE TITLE
no update blog

### ISSUE THREAD

**Issue by mama21mama** [HelloZeroNet/ZeroNet#348]
my blog http://127.0.0.1:43110/17JcQZkstLE9LH5dn49mCQhC6tamZDyi7F/

I see it updated, but my colleagues do not. That will be happening?

$ python zeronet.py siteSign 17JcQZkstLE9LH5dn49mCQhC6tamZDyi7F --publish

Use is command to update

**Comment by mama21mama** [comment]
**Private key invalid! Valid signers: **

I get that

**Comment by dontspamm** [comment]
offtopic you need to port some of the services to ZN

**Comment by HelloZeroNet** [comment]
if you are sure about you have to correct private key and your site does not exceed 10MB try `python zeronet.py --debug siteSign 17JcQZkstLE9LH5dn49mCQhC6tamZDyi7F --publish`

**Comment by mama21mama** [comment]
solved http://127.0.0.1:43110/165eqHdoQfyf7CVGqtVCGNDvMBZhwVSJBL/?Topic:15_1HcK5Hw1rPZeYdgTmqJGrVG2tSyR9Ke2Gt
