### ISSUE TITLE
video.js

### ISSUE THREAD

**Issue by tomasbond** [HelloZeroNet/ZeroNet#350]
is it possible to add video.js to my blog? how can i divide the all.js to install the video.js? thanks

**Comment by HelloZeroNet** [comment]
Big files not supported yet, so you can't embed videos.

**Comment by tomasbond** [comment]
But im not trying to host big files, the video source is host outside zeronet but i want to host inside my zeronet page the video player. Isnt it possible?

**Comment by HelloZeroNet** [comment]
It is, the example @ http://videojs.com/getting-started/ works for me. If you don't want to merge the video.js resources with your blog js, you can create a js directory in the data dir and put it there.

**Comment by tomasbond** [comment]
so to add video.js to my blog i should create a new js directory? lets asume that will be called video.js (with all the downloaded files). So know, how should i make my blog recognize the video settings and load it?

data/[your site address]
├─ js/
│  └─ all.js
├─ video.js/
│  └─ all files and subdirectories
├── index.html
└── content.json

**Comment by HelloZeroNet** [comment]
You need to add
`<link href="video.js/video-js.css" rel="stylesheet">` and `<script src="video.js/video.js"></script>` to your index.html's <head> section or you can also paste this lines directly to your blogpost

**Comment by tomasbond** [comment]
Very helpfull! Thank you!

**Comment by tomasbond** [comment]
I have a little problem, when i run the page with the new script outside zeronet it work perfect! but when i run it with zeronet the option to full-screen doesnt work (it show up but when on-click nothing happens).

**Comment by HelloZeroNet** [comment]
zeronet sites runs in sandboxed iframe for security reasons, in this enviroment not every javascript functions are available.

**Comment by tomasbond** [comment]
is there any option to bypass the sandboxed iframe? think of a video page where you cant full-screen -.- Can i sacrfice security to enable the full-screen option?

**Comment by HelloZeroNet** [comment]
no, its not possible

**Comment by tomasbond** [comment]
if you could lunch this feature in future update it would be awesome. thanks for your help!

**Comment by HelloZeroNet** [comment]
The sandbox is protecting user's data, so it will not removed. Pressing F11 for fullscreen should work in every browser.

**Comment by tomasbond** [comment]
Hi, why is the fullscreen option dont working in firefox, but yes in microsoft edge? And subtitles works in firefox but not in M Edge?

**Comment by HelloZeroNet** [comment]
Different browsers, different limitations.
