### ISSUE TITLE
Allow to open not sandboxed windows

### ISSUE THREAD

**Issue by vlad20012** [HelloZeroNet/ZeroNet#352]
Currently iframe property `sandbox="..., allow-popups"` allows only to open sandboxed windows (tabs), if they opens in any way from script (`<a target="_blank">`, `window.open()`). "sandboxed" means same-origin restriction to parent domain (for AJAX requests and more). It may totally break some sites (external to ZeroNet). Normal links (without `target="_blank"`) is working good for now.

Fast solution: add `allow-popups-to-escape-sandbox` to iframe sandbox attribute. At least it will work in Chrome. Read more [here](https://googlechrome.github.io/samples/allow-popups-to-escape-sandbox/).

Normal solution: Catch windows opening from parent scripts or add API functions to open windows normally

**Comment by HelloZeroNet** [comment]
At the first look it looks safe for me, but need more research about it.

**Comment by TheNain38** [comment]
Can be closed, it was added in: 4d7ce1dc1671256c9700029c83485dfab99a9574

**Comment by vlad20012** [comment]
It's just fast solution using non-standard attribute for Chrome only. This issue awaiting full cross-browser solution

**Comment by HelloZeroNet** [comment]
@vlad20012  Unfortunetly it's not possible: 
```
document.body.getElementsByTagName("iframe")[0].contentWindow.open
VM3924:1 Uncaught DOMException: Blocked a frame with origin "http://zero" from accessing a cross-origin frame.
```
The outer document also sandboxed from inner frame, so not allowed to access any property of it.

The possible cross-platform solution is adding a zeroframe api command for it

**Comment by vlad20012** [comment]
@HelloZeroNet Yes, in this case, a zeroframe api command is also perfectly acceptable.

**Comment by TheNain38** [comment]
@vlad20012 It adds complexity, and reduces maintability of ZeroNet to add "uneeded" features, a lot of users know about middle click to open in new tab these days

**Comment by vlad20012** [comment]
@TheNain38 I am developing service for authorization via social networks and need normal window.open or any alias (it's not a problem to write `@cmd "openWindow"` instead of window.open)

**Comment by TheNain38** [comment]
@vlad20012 But it is one to add complexity to a piece of software. If there are other way around, I don't see why there should be added complexity.

**Comment by HelloZeroNet** [comment]
@vlad20012 I'm not familiar with google account registration, does it also requires communication between the window and the opener?

**Comment by vlad20012** [comment]
@HelloZeroNet No. I'm speaking about ZeroNet user certificate reception. If ZeroNet 

I can also redirect user from external site back to ZeroNet in same tab. Now I am doing so. It looks not very convenient.

**Comment by vlad20012** [comment]
You can add API function and replace window.open into the default ZeroFrame.coffee. It will be transparent for users. If you feel that this is unreasonable, you can close the issue. But I think that soon it will be duplicated again.

**Comment by HelloZeroNet** [comment]
Related: https://mathiasbynens.github.io/rel-noopener/

**Comment by HelloZeroNet** [comment]
Added a wrapperOpenWindow command: https://github.com/HelloZeroNet/ZeroNet/commit/99f0407ba23707774884cd2ad103914044414587
Tested and works on youtube for me.
Example: `Page.cmd("wrapperOpenWindow", "https://github.com")`

**Comment by vlad20012** [comment]
[:161](https://github.com/HelloZeroNet/ZeroNet/commit/99f0407ba23707774884cd2ad103914044414587#diff-25ec8dd4ba66e508e805a317bc38fa5fR161)
```
w = window.open(null, params[1])
```
3rd param missing.
```
window.open(strUrl, winName [, winParams])
```

**Comment by HelloZeroNet** [comment]
Added: https://github.com/HelloZeroNet/ZeroNet/commit/6496a6125f65ed770778992858b3b152467b40ef

**Comment by vlad20012** [comment]
Now it's working very good. Thank you very much.

**Comment by HelloZeroNet** [comment]
Nice, I think we can close this then
