### ISSUE TITLE
Pls commit each feature separately

### ISSUE THREAD

**Issue by vlad20012** [HelloZeroNet/ZeroNet#353]
I oftem read a GIT history, and it is very comfortable common practice when each commit represents one feature or fix, not multiple.

When I reading your commits I should do extra working to determine what particular feature any line of code relative to.

Pls just commit each feature separately

**Comment by HelloZeroNet** [comment]
I will try, but I usually tests my modifications for longer time and do not want to push it out early, so I need a tool that display the diff and allows me easily to create separate commits based on that.
Any suggestions?

**Comment by vlad20012** [comment]
Commit changes localy and push them together. If bug found in some local commit (mb after testing), just use `git rebase -i` to make this commit the last and then amend it. I do not understand your problems.

**Comment by vlad20012** [comment]
You can also commit to other branch ("development"?) and merge to master only when version assigned

**Comment by HelloZeroNet** [comment]
If you want stable version then download the source code from releases. Master = development version

**Comment by HelloZeroNet** [comment]
Switched to another git client that allows per-line selection for commits, yeah feels better: https://github.com/HelloZeroNet/ZeroNet/commits/master
