### ISSUE TITLE
gevent version needs updating to work on rapberrypi

### ISSUE THREAD

**Issue by jdoig** [HelloZeroNet/ZeroNet#355]
With the version of gevent in the requirements.txt I get: 
```
Traceback (most recent call last):
  File "zeronet.py", line 15, in main
    import main
  File "src/main.py", line 12, in <module>
    monkey.patch_all(thread=False, subprocess=False)
  File "/home/pi/ZeroNet/env/local/lib/python2.7/site-packages/gevent/monkey.py", line 185, in patch_all
    patch_socket(dns=dns, aggressive=aggressive)
  File "/home/pi/ZeroNet/env/local/lib/python2.7/site-packages/gevent/monkey.py", line 124, in patch_socket
    from gevent import socket
  File "/home/pi/ZeroNet/env/local/lib/python2.7/site-packages/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/home/pi/ZeroNet/env/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined
Traceback (most recent call last):
  File "zeronet.py", line 60, in <module>
    main()
  File "zeronet.py", line 46, in main
    traceback.print_exc(file=open("log/error.log", "a"))
IOError: [Errno 2] No such file or directory: 'log/error.log'
```

Updating to version 1.1.0 fixes this (would put in a PR but I'm not sure if this will effect other platforms?)

**Comment by Erkan-Yilmaz** [comment]
>would put in a PR but I'm not sure if this will effect other platforms?
Did you try the ZeroBundle version yet? It should have all dependecies inside the bundle

**Comment by HelloZeroNet** [comment]
Rpi has different binaries so zerobundle probably will not work there.

@jdoig Can you please specify the gevent version and the python version you used?
`python -V`
`python -c "import gevent; print gevent.version_info"`

**Comment by jdoig** [comment]
@HelloZeroNet 
```
$ python -V
Python 2.7.9
$pip freeze
gevent==1.0.1
greenlet==0.4.9
msgpack-python==0.4.7
```
I guess the difference here is I'm using pip and virtualenv... But that shouldn't make a difference

**Comment by HelloZeroNet** [comment]
Can you test this one please?
```
$ python -c "from gevent import monkey; print 'patch_subprocess' in dir(monkey)"
True
```

**Comment by jdoig** [comment]
@HelloZeroNet 
```
python -c "from gevent import monkey; print 'patch_subprocess' in dir(monkey)"
True
```

**Comment by jdoig** [comment]
(as I mentioned above updating to 1.1.0 does fix this)

**Comment by HelloZeroNet** [comment]
I'm a bit afraid to touching it. (Gevent + SSL is a long, sad story, needed many hacks to make it work on most environment)

So I will change the requirements.txt.

**Comment by HelloZeroNet** [comment]
It's done, https://github.com/HelloZeroNet/ZeroNet/commit/25752c927ca694ba912683037829a69432796ad9
Thanks for reporting btw.

**Comment by HelloZeroNet** [comment]
@jdoig Btw it would be interesting for me if you would be able to post http://127.0.0.1:43110/Benchmark results from rpi here.

**Comment by jdoig** [comment]
@HelloZeroNet 
These are from an Rpi v3 model B running raspbian jessie lite heedlessly on a wired connection.  I'm running the benchmark by navigating to http://raspberrypi.local:43110/Benchmark in Chrome on my laptop
```
Benchmarking ZeroNet 0.3.6 (rev989) Python 2.7.9 (default, Mar 8 2015, 00:52:26) [GCC 4.9.2] on: linux2...

CryptBitcoin:
- hdPrivatekey x 10..........0.883s [x0.79: Goodish]
- sign x 10..........0.434s [x0.81: OK]
- openssl verify x 100..........0.647s [x0.57: Goodish]
- pure-python verify x 10..........2.446s [x0.65: Goodish]

CryptHash:
- sha256 5M x 10..........0.815s [x0.74: Goodish]
- sha512 5M x 10..........1.661s [x0.36: Ehh]
- os.urandom(256) x 100 000..........5.640s [x0.12: Sloooow]

Msgpack:
- pack 5K x 10 000..........1.562s [x0.50: Ehh]
- unpack 5K x 10 000..........2.555s [x0.47: Ehh]
- streaming unpack 5K x 10 000..........2.790s [x0.50: Goodish]

Db:
- Open x 10..........1.656s [x0.08: Sloooow]
- Insert x 10 x 1000..........2.506s [x0.40: Ehh]
- Buffered insert x 100 x 100..........3.526s [x0.37: Ehh]
- Total rows in db: 20000
- Indexed query x 1000..........0.429s [x0.58: Goodish]
- Not indexed query x 100..........1.373s [x0.44: Ehh]
- Like query x 100..........3.278s [x0.55: Goodish]

Done. Total: 32.52s
```

**Comment by HelloZeroNet** [comment]
Thanks, pretty good, the multipler is compared to my desktop machine (c2d 2.6ghz). So for the most important operations (sql, openssl verify) are around 2 times slower. 

The sha512 unexpectedly slower than sha256. I have choosen sha512 over sha256 because its around 2x faster on modern 64bit cpus. Probably this will improve in rPi3.
