### ISSUE TITLE
Does the use of tor's control cookie mean we can't use tor running in another docker container?

### ISSUE THREAD

**Issue by jdoig** [HelloZeroNet/ZeroNet#357]
This looks like the manager needs to read the control cookie from the file system:
https://github.com/HelloZeroNet/ZeroNet/blob/e891a10e54c31468849ed65892ed97bbb548a534/src/Tor/TorManager.py#L162

Is there a recommended way to get ZeroNet running, with tor, in a container? e.g: both services in a single container or mounting shared filesystems ?

**Comment by HelloZeroNet** [comment]
Yes, include tor if you want to use it. Docker philosophy: one service = one container
