### ISSUE TITLE
Max connected peer per site parameter doesn't work

### ISSUE THREAD

**Issue by kostaNew** [HelloZeroNet/ZeroNet#361]
I run ZeroNet as `python zeronet.py`. Default max connected peer per site in Config.py is 15.

But in /Stats I can see more 15 connection per site. For example:
1K28kQFMquNzto2iQf4GGjr6oFUbC1NddE	[341, 321, 534, 501, 207, 339, 117, 706, 106, 108, 123, 340, 11, 214, 33, 120, 118, 547, 176]	**19**/24/78	116	932kB	4713kB

**Comment by HelloZeroNet** [comment]
It's a soft limit, the limit checked every 20 minutes and if the site has more than it then close some connections.

**Comment by mama21mama** [comment]
Meanwhile the 1000 connections that ate the bandwidth.

**Comment by HelloZeroNet** [comment]
If you are on limited bw it's recommended to disable popular pages for now (ZeroBoard, ZeroID, ZeroMail)
