### ISSUE TITLE
ZeroBundle does not work on OSX 10.8

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#363]
The error: can't open the application ZeroNet because the classic environment is no longer supported.

I have no access to 10.8 Mac, so need suggestions how to make better .app. (currently its a bash script: https://github.com/HelloZeroNet/ZeroBundle/blob/master/ZeroNet.app)

An icon also would be nice.

**Comment by gsmiro** [comment]
I run a macosx and will try to debug it. Any ideas on the "make better app" part?

**Comment by HelloZeroNet** [comment]
the zerobundle package has the required python with the dependencies, so we don't use the system python, but the packed one: https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-mac-v0.1.1.zip

Can you try to open a terminal and run it with `bash ZeroNet.app`?

**Comment by gsmiro** [comment]
Done. Got 

`Python/python: No such file or directory`

**Comment by gsmiro** [comment]
Both `bash ZeroNet.app` and `open ZeroNet.app` worked.
Double clicking the app does nothing though.

**Comment by gsmiro** [comment]
Wouldn't it be better to package the app as a proper Application bundle, with Info.plist and the folder structure as pointed [here](https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW13)?

**Comment by HelloZeroNet** [comment]
thanks for testing, yeah a proper Application bundle would help, I will try ti when I have Mac access, or if you could try to create one and test it that would be great.

**Comment by gsmiro** [comment]
Ok. I'll look into it as soon as I can

**Comment by HelloZeroNet** [comment]
The ZeroBundle package contains the Python binaries with every dependency when you first time start zeronet it downloads the latest version from github and unpacks it to ZeroNet directory. There is a semi-auto update method in ZeroNet which is - when requested - it is re-downloads the latest source code, overwrite the files in ZeroNet dir and and restarts itself.

So I think to keep the built-in update method working the best would be to convert ZeroNet.app bash script to proper application bundle end leave the rest as it is.

**Comment by liquid** [comment]
FYI: I just ran into the same "classic environment no longer supported" issue on 10.9.5 (using the download through the site)

**Comment by drjmedulla** [comment]
Downloaded Zeronet per https://zeronet.io/ started up and worked great.
Tried to start the Zeronet Desktop App after my laptop went to sleep.
This is what I get:

**Server error

Err: Exception: File not allowed: data/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/index.html in UiServer.py line 81 > UiRequest.py line 82 > UiRequest.py line 209 > UiRequest.py line 282 > SiteStorage.py line 230 > SiteStorage.py line 251

Please report it if you think this an error.

Details:**

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch", 
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "61010", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "1.0.0.127.in-addr.arpa", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 15, 
        "data_dir": "data", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "keep_ssl_cert": false, 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": "default_browser", 
        "proxy": null, 
        "size_limit": 10, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.aletorrenty.pl:2710/announce", 
            "http://explodie.org:6969/announce", 
            "http://torrent.gresille.org/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false
    }, 
    "plugins": [
        "AnnounceZero", 
        "CryptMessage", 
        "Newsfeed", 
        "Sidebar", 
        "Stats", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.0.2", 
    "version_python": "2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58) \n[GCC 4.2.1 (Apple Inc. build 5577)]", 
    "version_zeronet": "0.3.6 r1038", 
    "wsgi.url_scheme": "http"
}

**Comment by HelloZeroNet** [comment]
Do you have any special (non-english) character in the directory where you unpacked it?
Please open ZeroNet/log/debug.log file, search for `not in allowed dir` and paste the line here.

**Comment by drjmedulla** [comment]
1st Question: No, I do not have any special (non-english) characters in the directory.

I search `not in allowed dir` and did not find any associated code.

Here is the closest I found: `[2016-03-18 20:59:33,542] ERROR    Site:1Name2..hM9F Content.json not exist: data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/content.json`

**Comment by HelloZeroNet** [comment]
@drjmedulla Can you check if ZeroNet is not running twice? (eg via taskmanager, search for python.exe)
If not helps please send your log files (debug.log and debug-last.log) to hello@zeronet.io

**Comment by drjmedulla** [comment]
Python 2.7 is only running once.
I attached a screenshot of Python running as well as the log files Zipped.

![screen shot 2016-03-19 at 8 30 07 am](https://cloud.githubusercontent.com/assets/16785963/13898606/f3882172-edac-11e5-933e-59ee0a531dd1.png)

[Archive.zip](https://github.com/HelloZeroNet/ZeroNet/files/180806/Archive.zip)

**Comment by HelloZeroNet** [comment]
Can you please try to move it to your home directory and run it from there? (if not helps please send the log files on mail)

**Comment by stman** [comment]
Hello.
If you need some help to investigate the case, do not hesitate to ask me.
I am an experienced Mac OS X "Objective-C" and "C" experienced developer.

**Comment by HelloZeroNet** [comment]
We need a proper way to pack a bash script into an .app
@drjmedulla's problem is probably not related to this

**Comment by stman** [comment]
You are experiencing the exact same problem as most P2P developpers porting their code to Mac OS X : YaCy had it, Twister has it, you have it.

What I recommand is to build a little native Mac OS X app to launch all necessary processes your application needs, but also that could be used, with a GUI (Menu, Icon in task bar) to configure the daemon and the options so that users don't have to edit text files and so on.

Regarding the libraries, I recommand to include all dependant libraries in an already compiled format (*.a) in a true Mac OS X Application bundle, with the little native app.

The "Linux" way of doing things (Recompiling the source code of each library) is not recommanded to create easy to install Mac OS X Application bundles : Application Bundle where created / engineered to have all the libraries already compiled.

I am going to do this work for Twister, but I would be really glad to do it for ZeroNet too :-)

You can count on my active cooperation to solving this little issue, it will be an honor for me.

Kind regards,

Stman.

**Comment by HelloZeroNet** [comment]
I was able to make it work on 10.8, but now it's not working on 10.11 :( (Unidentified developer error)

**Comment by HelloZeroNet** [comment]
I'm not familiar with OS X app ecosystem, but if we manage to sign the ZeroNet.app, then it would work without any errors (Unidentified developer error) on every platform or do we need to submit it to appstore?

**Comment by stman** [comment]
If you are a registered Developper, one can publish either on the MacAppStore, but in that case the application must meet Apple requirements, and the rules for the MacAppStore are more open than those applying to iOS Apps, 

OR

One can make the binary, signed with his Dev account, on any "custom server" .

Both solutions would end this issue "Un-identifyed" developer.

**Comment by HelloZeroNet** [comment]
So can anyone sign the https://github.com/HelloZeroNet/ZeroBundle/tree/master/ZeroNet.app/Contents application please?

**Comment by stman** [comment]
With pleasure....

**Comment by rippley5150** [comment]
Hello
I've just discovered Zeronet. I was able to install on my Windows 7 laptop but am unable to get it to run on my Macbook running 10.11.4. The app icon bounces then crashes and won't open again. 

Thanks for your time.

**Comment by border0464111** [comment]
So, there a mac app signed now ? Problem solved ?

**Comment by HelloZeroNet** [comment]
Yep, it should work now
