### ISSUE TITLE
[ERROR] Only ascii encoded filenames allowed

### ISSUE THREAD

**Issue by Dhole** [HelloZeroNet/ZeroNet#364]
The current regex at src/Content/ContentManager.py lines 298 and 312:
https://github.com/HelloZeroNet/ZeroNet/blob/e891a10e54c31468849ed65892ed97bbb548a534/src/Content/ContentManager.py#L298
https://github.com/HelloZeroNet/ZeroNet/blob/e891a10e54c31468849ed65892ed97bbb548a534/src/Content/ContentManager.py#L312
are not matching all the ASCII characters but a very limited subset:
`^[a-zA-Z0-9_\.\+\-/]*$`

I think more characters could be allowed. I was able to add '@' and '=' without issues (as I had some filenames containing those characters). 
I believe this should match any printable ASCII character:
`^[\\x20-\\x7e]*$`

If not all ASCII characters can be used, the error message should be changed.

**Comment by HelloZeroNet** [comment]
Added @ and = to allowed file list

**Comment by icf20** [comment]
are spaces and ( ) supported ?
