### ISSUE TITLE
ZeroHello not working through nginx

### ISSUE THREAD

**Issue by zebMcCorkle** [HelloZeroNet/ZeroNet#365]
I tried some light debugging, but I have no idea what's wrong. You can check out New ZeroHello at https://zeronet.classcoder.com/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D, but it doesn't render due to:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    Text.toColor @ all.js:1564
    Dashboard.render @ all.js:2079
    (anonymous function) @ all.js:1942
    doRender @ all.js:983
```

at around line 4 in js/utils/Text.coffee. Nothing is logged to the server console when ZeroHello is loaded. I'm not sure if this should be in HelloZeroNet/ZeroHello or here, but it seems like an issue with the wrapper to me.

**Comment by HelloZeroNet** [comment]
Probably relevant: https://github.com/HelloZeroNet/ZeroNet/issues/288#issuecomment-194722911

**Comment by zebMcCorkle** [comment]
@HelloZeroNet Nope, everything else works, and I figured that nginx config out when I was setting up the proxy a few months ago.

**Comment by HelloZeroNet** [comment]
Looks like for some reasons the new zerohello site does not have admin rights for you, shut down zeronet, open data/sites.json, search for 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D and add "ADMIN" to "permissions":
```
    "permissions": ["ADMIN"], 
```

**Comment by zebMcCorkle** [comment]
Worked, thanks!
