### ISSUE TITLE
Uploading Html 

### ISSUE THREAD

**Issue by Dgotlieb** [HelloZeroNet/ZeroNet#366]
Hi, I didn't quite understand,  where do I locate my htm file, in order for the website to upload?

**Comment by Erkan-Yilmaz** [comment]
Did you follow the FAQ (1) ?
If you create a new site, this site is located in your data dir under a certain address.
A new created site has a content.json and index.html

I think from there you should know what to do.

(1) http://zeronet.readthedocs.org/en/latest/using_zeronet/create_new_site/

**Comment by border0464111** [comment]
solved ?
