### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by RogueHat** [HelloZeroNet/ZeroNet#367]
even when using --ui_ip "*" option, I am getting a connection refused. My setup involves having my laptop ssh tunnel to a host machine with a vm that runs ZeroNet on it, but lately I've been recieving a connection refused error.

![connectionrefused](https://cloud.githubusercontent.com/assets/2320007/13840414/6ae3307c-ebf0-11e5-91c3-93e8e188b2da.PNG)

**Comment by RogueHat** [comment]
I found the cause of the error. It seems that something is causing the connection to be refused when Opera Turbo is enabled. I won't close the issue yet since there might be a solution to this, but for now, the quick fix is to disable Opera Turbo.

**Comment by HelloZeroNet** [comment]
If the browser does not allow to connect to the ui server, then we can't do anything about it. You can try access it using your LAN/WAN ip.

**Comment by border0464111** [comment]
Opera turbo is a opera's specific feature that pipe your traphic throu a compressing proxy somewhere on the internet. As Zeronet is local, you must see on the opera side if there is a way to create exeption rules for the traphic redirection. 

Unfortunately, Nothing Zeronet specific here. 

Closing ?
