### ISSUE TITLE
error on update

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#368]
After update from UI i get that in console:

`OpenSSL dlclosed, handle: 140396059753056
Downloading. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Downloaded.
Plugins enabled: ['AnnounceZero', 'CryptMessage', 'Newsfeed', 'Sidebar', 'Stats', 'Trayicon', 'Zeroname'] disabled: ['Bootstrapper', 'Dnschain', 'DonationMessage', 'Multiuser', 'UiPassword', 'Zeroname-local']
Extracting... . . . . . . . . . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . P . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Done.
Restarting...
ERROR:-:Unhandled exception
None
Traceback (most recent call last):
  File "start.py", line 16, in <module>
    main()
  File "start.py", line 13, in main
    zeronet.main()
  File "/Users/Shift/ZeroNet/zeronet.py", line 52, in main
    import time
NameError: global name 'time' is not defined`

but after python start.py all work normally

**Comment by HelloZeroNet** [comment]
Yeah, it was fixed yesterday: https://github.com/HelloZeroNet/ZeroNet/commit/eea55f8f16fa4737d7d08686c12e0c443e48e760
So updating from rev980-1038 will require manual start after the update, but the next update should be fine.
