### ISSUE TITLE
[Multiuser] After a restart of ZeroNet, all users are logged out

### ISSUE THREAD

**Issue by zebMcCorkle** [HelloZeroNet/ZeroNet#373]
After a restart of ZeroNet, all users are logged out and need to reinput their masterseeds as well as go to [zeroid.bit](https://www.zeropro.xyz/zeroid.bit) to reactivate their ID.

**Comment by HelloZeroNet** [comment]
Yes, in multiuser mode for security reasons nothing is written to disk
