### ISSUE TITLE
Simple site plugins

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#374]
Have ability to modify the site layout/add new features without modifying the original source code to keep it updateable.

Eg if you create a `plugins/DarkSkin/all.css` file on all.css request it would also append this file's content to the end. (same for js)

Maybe combining something similar like hotpatching in #322, so it would be possible to easily attach new functions to events.

**Comment by obv-mikhail** [comment]
How would this be different from adding new features in like this `css/plugins/DarkSkin/all.css` ?

Would the above compile (append to css/all.css) currently?

**Comment by obv-mikhail** [comment]
@HelloZeroNet Maybe add support for multiple databases per site? This way a plugin can store its data independently from the rest of the site. Would make adding some features much easier.

**Comment by grez911** [comment]
@HelloZeroNet Have this implemented in 0.5.5 and can be closed?
