### ISSUE TITLE
fail to startup on Win7 after use&quit ZeroNet once

### ISSUE THREAD

**Issue by WhiteCat6142** [HelloZeroNet/ZeroNet#378]
It seems to forget to close log files

`- Starting ZeroNet...
Traceback (most recent call last):
  File "zeronet.py", line 15, in main
    import main
  File "src\main.py", line 51, in <module>
    os.rename("%s/debug.log" % config.log_dir, "%s/debug-last.log" % config.log_dir)
WindowsError: [Error 32] プロセスはファイルにアクセスできません。別のプロセスが使用中です。(Can't access because other process locks the file)
`

**Comment by HelloZeroNet** [comment]
Probably the old process is still running. Please check process list / log files. Are you sure it's not in your systray icon list?

**Comment by WhiteCat6142** [comment]
python.exe was dead. "WerFault" has the handle. 
And I couldn't find what makes this condition.I'll report as soon as I know.

**Comment by WhiteCat6142** [comment]
I realize that only "debug.log" is locked.
In my conclusion,when zaronet couldn't access "debug-last.log" by some reason,it happens.
