### ISSUE TITLE
Error Message: "Message wrapper_nonce error, please report!"

### ISSUE THREAD

**Issue by OliverCole** [HelloZeroNet/ZeroNet#383]
I'm following the [site tutorial](http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:43:ZeroNet+site+development+tutorial+1), and I'm getting the above error at the last stage (before publishing).

Win 10, latest FF. I've tried in a fresh profile without any extensions. Seeing #306, I have tried disabling antivirus/antimalware - no effect.

Firefox console:
````
The connection to ws://127.0.0.1:43110/Websocket?wrapper_key=f034d74605321b02f027fadcc152eec7afe8804c2e62c215d6afda80797ff2c8 was interrupted while the page was loading. all.js:40:16
[ZeroWebsocket] Closed close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1458488860822000 } all.js:106:14
GET 
http://127.0.0.1:43110/1H1Ee3oP5tVZqz5kmQVqqfXjFUDx8kAinN/ [HTTP/1.1 200 OK 1ms]
GET 
http://127.0.0.1:43110/uimedia/all.css [HTTP/1.1 200 OK 2ms]
GET 
http://127.0.0.1:43110/uimedia/all.js [HTTP/1.1 200 OK 4ms]
[Wrapper] Created! all.js:1292:14
GET 
http://127.0.0.1:43110/1H1Ee3oP5tVZqz5kmQVqqfXjFUDx8kAinN/ [HTTP/1.1 200 OK 0ms]
GET 
http://127.0.0.1:43110/1H1Ee3oP5tVZqz5kmQVqqfXjFUDx8kAinN/js/all.js [HTTP/1.1 200 OK 0ms]
[Wrapper] Message nonce error: undefined != 8ffea5dfc1054366343dda68a7de96679efb05f9fdcc7cd5e864651d89e32628
````

Site: [1H1Ee3oP5tVZqz5kmQVqqfXjFUDx8kAinN.zip](https://github.com/HelloZeroNet/ZeroNet/files/181356/1H1Ee3oP5tVZqz5kmQVqqfXjFUDx8kAinN.zip)

**Comment by OliverCole** [comment]
Packet capture: [wrapper_nonce.zip](https://github.com/HelloZeroNet/ZeroNet/files/181368/wrapper_nonce.zip)

**Comment by HelloZeroNet** [comment]
Are you sure you have used the correct ZeroFrame.coffee ? http://127.0.0.1:43110/blog.zeronetwork.bit/data/files/ZeroFrame.coffee

**Comment by OliverCole** [comment]
OK, my bad. I had a different error earlier, saw the comments on that blog entry and grabbed one from a different site. Thanks!
