### ISSUE TITLE
User "muting"

### ISSUE THREAD

**Issue by wpstudio** [HelloZeroNet/ZeroNet#388]
I'm wondering if there would be a method in which Zeronet would allow users to set up a self-moderating "user muting" list.

This would prevent any type of censorship but individuals could HIDE posts/content made by specific ZeroID individuals. And since the user muting list would remain on individual's localhost it would only mute for that specific user.

**Comment by Erkan-Yilmaz** [comment]
could be part of the "universal admin interface" https://github.com/HelloZeroNet/ZeroNet/issues/354

**Comment by HelloZeroNet** [comment]
@Erkan-Yilmaz The unviersal admin is for managing site database, the muting feature is only for you and it would not modify the site.

**Comment by HelloZeroNet** [comment]
It can be done two ways: 
 - Does not insert hidden user's data to database at all: Probably easier, no site modification needed, but you will not notice if you miss all content created by the user (topics, comments, mails, etc.)
 - Let the sites handle it: Needs modification on every site, but you can see if anyone commented on a topic created by the user you hidden.

It's not that hard, but could be dangerous and narrow your view of the world

**Comment by TheNain38** [comment]
@HelloZeroNet I find the first idea better than the second, because it allows users to hide all the content that comes from a certain cert

**Comment by alxbob** [comment]
its better to let users decide what their want to see and don't want to see. It could be even better if they have the option not to seed what the don't want from a user but i think merger issue should solve this kind of stuff

**Comment by HelloZeroNet** [comment]
Started worknig on this:

 - [ ] muteAdd command: Adding new user to mute list, params: auth_address, cert_user_id, source, reason. Confirmation requred if not an admin site. Check all sites and removes the json files of the user from databases.
 - [ ] muteRemove command: Remove user from mute list, params: auth_address. Confirmation requred if not an admin site. Check all sites and re-add the json files of the user from databases.
 - [ ] muteList command. List all current mutes. Requres admin permission.
 - [ ] UI in ZeroHello to add/list/modify current muted users
 - [ ] Implement to ZeroHello

**Comment by Jookia** [comment]
Will this include optional files, such as images? Would be nice to mute people who show illegal content and have it wipe anything I'm sharing extra too. For instance, to view an option on ZeroMe you have to download it which I think also distributes it.

**Comment by HelloZeroNet** [comment]
No, it's only hides the content, but you will still download and distribute it to other people, because the protocol expects that everyone has every non-optional file.

No mute lists yet, maybe in the future.

**Comment by HelloZeroNet** [comment]
added in 2cea157eccb2f0b3e19158590d2d3e65ba4022a5

**Comment by fiskr** [comment]
@HelloZeroNet I don't understand how to use the Mute plugin, as a user. It seems almost like you implemented it for admin of zites? I am not sure I understand, but essentially: how do I mute users now that 2cea157 is done?

**Comment by slrslr** [comment]
@HelloZeroNet It happen to me that user is posting bad content on some site and on other site he post useful content.
For example on ZeroMe i would mute user who is posting nudity or pedo content publicly, but i want to see his content on ZeroTalk and ZeroMail because i do not believe in blocking valuable user zeronet-wide, just because on one or two sites he post bad images..

Please make the site-wide muting by default and zeronet-wide as a last resort option.

**Comment by Thunder33345** [comment]
actually agreed on begin able to mute with fine tuned addresses, for the public list and mute list
