### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by Elmit2015** [HelloZeroNet/ZeroNet#39]
In the past I had no content by myself, so it was easy to upgrade => replace

Now I have my own blog, my own sites, ... ZeroBlog changed, do I need to upgrade that also ? Do I need to upgrade MY blog? what's with my data?

BTW, one thing needs improvement: As more sites are coming online as more annoying it is WHERE the sites will get the place in the main screen, since it changes with each restart. Maybe we can add numbers to it, or "bookmark" them to a certain spot. What will be if we get hundreds of sites? Will we get a search button/sort button?

**Comment by HelloZeroNet** [comment]
- Upgrading ZeroNet: keep your data dir, all your data is stored there
 - Upgrading ZeroBlog: backup content.json and data.json from your site, overwrite all other files

Yes, the sites ordering is problematic on ZeroHello, currently sorted by peer number, bookmark feature is a good idea
