### ISSUE TITLE
Idea: Using normal domain names via addresses in TXT records

### ISSUE THREAD

**Issue by OliverCole** [HelloZeroNet/ZeroNet#391]
I'm not sure what discussions have already happened about using names other than .bit, but if you put the site address in the TXT record that would allow public internet domain owners to point to a ZeroNet site.

Any thoughts?

**Comment by HelloZeroNet** [comment]
it goes against "uncensorable" goal, so not a good idea

**Comment by OliverCole** [comment]
Hmm - so yes, the entry point/discovery is censorable, but the actual content is not.

If I had a domain, and some ZeroNet content, and my domain was seized or whatever, the ZeroNet content would remain, and still be distributed and updatable.

If users could now reference it via its ZeroNet address then I can continue to maintain and use the ZeroNet content, right? In a sense, it's almost counter-censorship, because it can't be taken down by seizing the domain. Isn't that worth having?

**Comment by HelloZeroNet** [comment]
But what about domain name updates? I think it's not worth it, if we want to create more decentralized internet, then we need to use more decentralized domain system.

**Comment by OliverCole** [comment]
What do you mean by updates? 

Do you mean, what if the seized domain gained a new ZeroNet address pointing at something else? That would be bad yeah, and hard to handle too.

**Comment by TheNain38** [comment]
Another problem is that it does a request to a DNS server, and it isn't secure, so someone could temper it and redirect your users to another address

**Comment by OliverCole** [comment]
That's true, but you could limit it to DNSSEC roots to eliminate that.

Doesn't deal with the earlier issues though - I can see it has problems.

**Comment by border0464111** [comment]
Closing ?

**Comment by ValdikSS** [comment]
@HelloZeroNet, I think it's a useful feature even if it may contradict with your main ZeroNet conception.

For example, I'd like to have a blog in ZeroNet which could be accessible from the internet. The easiest and most sane method to implement this is to allow ZeroNet to handle HTTP `Host` header and perform DNS query for a TXT records which points to zite public key hash (zite address). This feature allows domain owner to point DNS records to different public ZeroNet gateways or to setup own gateway for a limited number of websites without a hassle.

Take a look how it's implemented in IPFS. IPFS handles HTTP `Host` header, performs DNS TXT record lookup to `_dnslink.domain.com` which contains TXT record `dnslink=/ipfs/SoMeRanDoMFilEHasH` and opens resolved address from the TXT record.
This feature brings hosting-less websites with Cloudflare's service https://cloudflare-ipfs.com/ or any other public gateway.

As DNS hijacking brings more and more attention and major public DNS providers has implemented DNS over TLS/over HTTPS, I believe ZeroNet would benefit from this feature.

**Comment by DaniellMesquita** [comment]
@HelloZeroNet @shortcutme
