### ISSUE TITLE
random --fileserver_port

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#392]
is it necessary to random the --fileserver_port every time when ZeroNet start-up?
I worried about the GFW of China may block port 15441 to stop people from using ZeroNet...

**Comment by border0464111** [comment]
Would ` --fileserver_port $( shuf -i 2000-65000 -n 1 )` be a sufficient workaround. 

It seen like a edgy usecase as I presume most people don't keep  65K ports open just in case. But I might be wrong on this one.

**Comment by grez911** [comment]
> GFW of China may block port 15441

@XL2014 Then you can start zeronet with any other port: `./zeronet.py --fileserver_port 12345`
