### ISSUE TITLE
Installation tutorial in Github

### ISSUE THREAD

**Issue by ShalokShalom** [HelloZeroNet/ZeroNet#400]
**Linux terminal

wget https://github.com/HelloZeroNet/ZeroBundle/releases/download/0.1.1/ZeroBundle-linux64-v0.1.1.tar.gz

It downloads the latest version of ZeroNet then starts it automatically.**

Is this surely the latest version ?

**Comment by ShalokShalom** [comment]
why not use the same version numbers, to make it easy to detect that, please? :)

**Comment by HelloZeroNet** [comment]
Fixed: https://github.com/HelloZeroNet/ZeroNet/commit/e3a4dbaab566255c44543a22cb0adb982c3b66bb
