### ISSUE TITLE
Changes to coffeescript files not displayed in browser

### ISSUE THREAD

**Issue by mirrorwish** [HelloZeroNet/ZeroNet#409]
I've followed the instructions here http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:43:ZeroNet+site+development+tutorial+1

When changing the ZeroChat.coffee file (after completing all the steps in the first part), the changes are often not displayed in the browser, even after refreshing. I'm not sure if it is never compiled into all.js or the new version is not loaded.

 I'm already running with the --debug flag and I have the console open (even though I don't think this should matter). This happens in Iceweasel (Firefox) on Debian.

**Comment by OliverCole** [comment]
On my vanilla Firefox I had to open the console and tick a box in the console settings to force disabling the cache.

**Comment by mirrorwish** [comment]
That solved it! Thanks.

**Comment by imachug** [comment]
Heads up: you can now use `--merge_media` option instead of `--debug`.
