### ISSUE TITLE
ZeroHello favorite sites in sites.json

### ISSUE THREAD

**Issue by sermont** [HelloZeroNet/ZeroNet#410]
I believe that ZeroHello "favorited" sites are stored in cookies. (I haven't checked, but I noticed they disappear after cookies get cleared).
How about having a specific flag (or taxonomy / tags) in the sites.json entries?
That would add resilience to cookie removal and consistency between different browsers as a minimum.

**Comment by HelloZeroNet** [comment]
sqlite database would be better (more scalable, multiuser)

**Comment by sermont** [comment]
agreed

**Comment by border0464111** [comment]
I moved the issue to zerohello repository. Closing ?
