### ISSUE TITLE
Unauthenticated Encryption

### ISSUE THREAD

**Issue by mirrorwish** [HelloZeroNet/ZeroNet#412]
It appears that the 'aesEncrypt' and 'aesDecrypt' commands do unauthenticated encryption. This is very bad for security. See the code below that clearly demonstrates the problem.

These commands are used by ZeroMail in an insecure fashion, that could in theory make it possible for an attacker to decrypt messages. But I think this would be very hard to accomplish in practice. Nevertheless, this should definitely be fixed.

The actual problem is [here](https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/CryptMessage/CryptMessagePlugin.py#L105), where the unauthenticated ciphertext is decrypted.

The easiest way to fix this is to add a MAC. I would recommend HMAC-SHA256 as that is already used in ZeroNet. The key for the mac could either be provided separately, or both the aes key and the mac key could be derived from a single key using HKDF or another secure algorithm.

```
msg = 'abcdefghijklmno'
console.log(msg)
@cmd 'aesEncrypt', [msg], (res) =>               # Encrypt message
    key = res[0]
    iv = res[1]
    enc = res[2]
    console.log(key, iv, enc)
    iv = 'a'+iv.substr(1)                        # Modify the IV
    console.log(key, iv, enc)
    @cmd 'aesDecrypt', [iv, enc, key], (res2) => # This should not decrypt
        console.log (res2)                       # But it does about 50% of the time
```

**Comment by HelloZeroNet** [comment]
Thanks for reporting, but i'm not sure if its necessary to authenticate every message, because the whole file is already authenticated by the sha512 hash

**Comment by mirrorwish** [comment]
It think ZeroMail tries to decrypt messages with all its AES keys (not just the one associated with the sender). So I can't see how this would help.

**Comment by TheNain38** [comment]
@HelloZeroNet I was able to successfully forge a ZeroMail:
- Alice: mail_data_from_Alice -> Bob
- Eve: mail_data_from_Alice -> Bob
- "Bob" successfuly decrypted a mail from "Eve" with the same content as the mail from "Alice"

**Comment by HelloZeroNet** [comment]
@TheNain38 it's not related to this problem

**Comment by TheNain38** [comment]
@HelloZeroNet Then, what does this attack uses? http://blog.cryptographyengineering.com/2016/03/attack-of-week-apple-imessage.html
The fact that there isn't any HMAC, and it's bad for security to not have any HMAC

**Comment by HelloZeroNet** [comment]
the hmac is authenticate the message itself and not the sender user.

**Comment by HelloZeroNet** [comment]
it could be possible modify zeromail to decrypt the messages using only the aes key associated to the user, so it would greatly improve performance and would not require per-message hmac, or is there any other attack vector on that?

**Comment by mirrorwish** [comment]
@HelloZeroNet I looked more into the code of ZeroMail, and doing that is not sufficient. The attacker can just send the same AES key as the real sender.

And even if ZeroMail is made secure, other people may still assume that they can safely pass untrusted data into 'aesDecrypt'. So the real solution is to create new secure commands, and then removing the old 'aesEncrypt/Decrypt'.

@TheNain38 It is definitely a problem that you were able to do that, and I wasn't aware that was possible. Adding an HMAC will in itself not be sufficient, to fix that. Some more changes will be required.

**Comment by TheNain38** [comment]
@mirrorwish If you use a nonce and an HMAC, it should be good to prevent replay attacks, right?

**Comment by mirrorwish** [comment]
@TheNain38 Assuming that the nonce is placed under the HMAC, and that the recipient check that this nonce was not previously received, then I believe it should be.

But this is still not sufficient to prevent your attack. If Eve manages to get her message to Bob before Alice's message arrives. Then bob will think that the message from Eve is the real one and will reject the one from Alice.

**Comment by TheNain38** [comment]
@mirrorwish Could we talk using another communication platform? Like Tox, or something else? I have an idea to make this work without requiring a nonce

**Comment by mirrorwish** [comment]
@TheNain38  You can contact me at
Bitmessage: BM-87ZQse4Ta4MLM9EKmfVUFA4jJUms1Fwnxws
ZeroMail: ichigo (I haven't really used this so I'm not sure if it works)

**Comment by TheNain38** [comment]
@mirrorwish
This, is my address, so you can verify it's really me: BM-2cSj4rVtxERWT75V1svyYV3Ju63KNQZPvz
ZeroMail: thekill38

**Comment by HelloZeroNet** [comment]
Modifying the secret exchange by also adding the sender's address to it would prevent the aeskey stole attack + adding the per-user associated decryption modification i think would solve the problems

**Comment by mirrorwish** [comment]
Probably, but I'm not completely sure. And why make it so complicated when you can solve it by simply adding an HMAC?

**Comment by HelloZeroNet** [comment]
HMAC would not solve the message or secret transfer problem, so we need to add this regardless of HMAC-ing messages or not

**Comment by mirrorwish** [comment]
Oh I think I misunderstood.

Yes, adding the sender and only decrypting with the right keys should solve the problems with copying messages.

You seem a bit cautios about adding a MAC, and I don't really understand why, as I see no downsides.

**Comment by HelloZeroNet** [comment]
im not against addig MAC, but i think the real problem (message duplication) is not related to it.

**Comment by TheNain38** [comment]
@HelloZeroNet It's a replay attack

**Comment by TheNain38** [comment]
To encrypt a mail:
- Alice computes a shared secret using her cert's SK, and the PK from Bob's cert and she uses this secret to AES encrypt the message as you already do

To decrypt a mail:
- Bob computes the shared secret using his cert's SK and the PK from Alice's cert, and try to AES decrypt all the messages Alice sent, and when decryption works, it was a mail for him

It can't be a replay attack as it uses the sender's address to compute the shared secret, and then uses it to encrypt and decrypt mails

This method also prevents someone to know when you started mailing to someone new

__I would like to know if doing this is secure__

**Comment by HelloZeroNet** [comment]
Alice's SK = Alice's private key? If so, then if you encrypt anything using it then noone will able to decrypt it.

**Comment by TheNain38** [comment]
@HelloZeroNet It's a __shared secret__, look at this image: https://upload.wikimedia.org/wikipedia/commons/4/4c/Public_key_shared_secret.svg

**Comment by HelloZeroNet** [comment]
I think ECIES works like this, but there would be many drawbacks to use it as message encryption:
 - Much larger messages
 - Around 100x slower than AES
 - You would have to try to decrypt every message (currently don't decrypt unknown user's messages)
 - If we want to have sent folder, then we have store the messages twice (once encrypted for our self, once for other user)

https://github.com/HelloZeroNet/ZeroNet/issues/216#issuecomment-157479518

**Comment by TheNain38** [comment]
@HelloZeroNet You won't need the `secrets_sent` and the `secret` part in your `data.json` anymore

**Comment by HelloZeroNet** [comment]
I know, this is a more complex solution, but it was chosen because of the reasons i written in my prev comment.

**Comment by mirrorwish** [comment]
> Much larger messages

Probably about 60-70 bytes more. Not really that much.

> Around 100x slower than AES

This is true if you blindly use ECIES, but the solution proposed by TheNain38 can do a lot of precomputations, and should be of comparable performance to the current implementation.

> You would have to try to decrypt every message (currently don't decrypt unknown user's messages)

That is true.

> If we want to have sent folder, then we have store the messages twice

Or just store the ephemeral key (32 bytes). This would actually be an improvement as you can make messages unreadable for yourself but still readable for the recipient. But note that this is not even required with the proposed solution.

But I'm not totally convinced the proposed solution is secure, as the same private key is used with ECIES for encryption to multiple recipients. Normally you would use a new key for each message. Do you happen to know what it's called?

**Comment by basxto** [comment]
This does not seem like being a general problem with 'aesEncrypt' and 'aesDecrypt'. Authentification would be overkill when you use permalinks and disposable keys, since others can’t modify the data.json.

Because removal of those functions was proposed…

**Comment by mirrorwish** [comment]
@basxto I assume you are mainly referring to PastePr.

The reason I'm proposing to remove it, is that many people don't understand the security implications of using unauthenticated AES. Normally AES is very fast (with or without authentication) so it should not be a bottleneck, in nearly all cases. But if it really is a bottleneck in PastePr or some other application, it think it's fine to keep it but just add a warning.

I don't know yet if your usage of 'aesEncrypt/Decrypt' in PastePr is secure, but I will look into it, and give my judgment.

**Comment by mirrorwish** [comment]
@basxto PastePr is likely vulnerable to the same vulnerability I reported here, and I think it would be easier to attack PastePr than ZeroMail. So I really think you should use authenticated encryption.

But there is a much more serious problem, that makes the encryption totally broken: PastePr uses the same IV twice. [See here](https://github.com/basxto/PastePr/blob/master/js/paste.coffee#L90-L95). This makes it possible for an attacker to easily decrypt the title and some of the body without knowing the key.

If you want help to solve either of these problems, feel free to contact me.

**Comment by imachug** [comment]
Is this still a problem? @mirrorwish @HelloZeroNet

**Comment by purplesyringa** [comment]
@HelloZeroNet Has this issue been solved yet?

**Comment by HelloZeroNet** [comment]
I might be wrong, but think it's authenticated by the signature in user's content.json
