### ISSUE TITLE
ZeroTalk activation enhancement 

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#420]
lets be honest nobody see the more option, ZeroTalk first time activation should show several "huge" country flags so users can pick what forums they want.

1. spain flag https://en.wikipedia.org/wiki/File:Flag_of_Spain.svg
1. chinese https://en.wikipedia.org/wiki/Flag_of_China#/media/File:Flag_of_the_People%27s_Republic_of_China.svg
1. poland https://en.wikipedia.org/wiki/Flag_of_Poland#/media/File:Flag_of_Poland.svg
1. france https://en.wikipedia.org/wiki/Flag_of_France#/media/File:Flag_of_France.svg
1. russian https://en.wikipedia.org/wiki/Flag_of_Russia#/media/File:Flag_of_Russia.svg
1. portugal https://en.wikipedia.org/wiki/Flag_of_Portugal#/media/File:Flag_of_Portugal.svg

**Comment by HelloZeroNet** [comment]
it does not meet the design principles
