### ISSUE TITLE
Hope to have the mobile version.

### ISSUE THREAD

**Issue by ShenXuGongZi** [HelloZeroNet/ZeroNet#422]
hello:
 my i Hope to have the mobile version

**Comment by HelloZeroNet** [comment]
you can run it on android using GNUROOT, but it's better solution if you put it on remote machine that has persistent internet connection: http://zeronet.readthedocs.org/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine

**Comment by zszszsz** [comment]
the seceond solution seems unsafe, or you need to set a passwd for the server i guess

**Comment by HelloZeroNet** [comment]
Yes, please read the link:

Is it possible to install ZeroNet to a remote machine?

Yes, you have to enable the UiPassword plugin by renaming the plugins/disabled-UiPassword directory to plugins/UiPassword, then start ZeroNet on the remote machine using 
zeronet.py --ui_ip "*" --ui_password anypassword. This will bind the ZeroNet UI webserver to all interfaces, but to keep it secure you can only access it by entering the given password.

**Comment by icf20** [comment]
in my opinion this is a huge privacy risk because GPS

**Comment by OliverCole** [comment]
Can you explain what you mean by GPS being a privacy risk?

**Comment by icf20** [comment]
> Can you explain what you mean by GPS being a privacy risk?

if i remember correctly chrome browser track your location

**Comment by TheNain38** [comment]
Simple solution, don't use chrome, if what @icf20 said is right, ever way, Google is tracking you all the time, it wouldn't surprise me that they track you

**Comment by icf20** [comment]
on that topic is a bit more complex, for example google play services ask for gps, cell data(tower cell), wifi data, general location every 40-60 seconds
the normal default browser ask for general location, contacts, call log, and  calendar  only when is open
by default the google activates (settings -> google) tracking for web and apps, device etc if you block the access to all that using privacy guardian(CM 12) then google does not know what webs you view and your location
so if google can read all that data can read what you do on zeronet and on what places you open/view zeronet

**Comment by grez911** [comment]
@icf20 You can use firefox.

**Comment by mkg20001** [comment]
@ShenXuGongZi There is an android version available https://github.com/HelloZeroNet/ZeroNet-kivy/releases
Google Play: https://play.google.com/store/apps/details?id=net.mkg20001.zeronet
F-Droid comming soon

**Comment by imachug** [comment]
@HelloZeroNet Can we close this?
