### ISSUE TITLE
can it work behind proxy?

### ISSUE THREAD

**Issue by zszszsz** [HelloZeroNet/ZeroNet#423]
I need proxy to access the ipv4 part of the Internet, but cannot find configuration file of zeronet to set front proxy

or can it work with pure ipv6?

**Comment by HelloZeroNet** [comment]
you can use socks5 proxy using --proxy 1.2.3.4:4321

ipv6 not supported yet

**Comment by 0polar** [comment]
and `--tor disable` for better performance
