### ISSUE TITLE
Internal error: IOError: [Errno 13] Permission denied: '/etc/zeronet.conf'

### ISSUE THREAD

**Issue by BruceZhang1993** [HelloZeroNet/ZeroNet#425]
When i try to enable Tor for every connection, i got this error

how can i manally edit and enable this option

**Comment by HelloZeroNet** [comment]
i'm assume you are not using the standard installation, because by default the config file is located at zeronet's directory and not in /etc.

you have to add `tor = always` to `[global]` section

**Comment by BruceZhang1993** [comment]
@HelloZeroNet I install zeronet from AUR on archlinux.. so have to manually edit this file  and   succeed.. thx
