### ISSUE TITLE
zero/blog/mail/talk wont work 

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#426]
zero/blog/mail/talk does not work by itself it require a dns service, this is clearly a design flaw .bit should be optional not enforced

**Comment by Erkan-Yilmaz** [comment]
you can open each ZeroNet site with its address, no need for .bit

(more about .bit mapping: done onto this very ZN address, by ZeroName)

**Comment by HelloZeroNet** [comment]
the dns is optional, every site works without it.

**Comment by icf20** [comment]
did you test ?

**Comment by HelloZeroNet** [comment]
yes http://127.0.0.1:43110/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 works without any problem

**Comment by icf20** [comment]
i said clicking from 1HeLLo

**Comment by HelloZeroNet** [comment]
you have to modify the zerohello to link to non-domain url

**Comment by icf20** [comment]
why ? the rest of the sites are saved correctly but on zeromail the address is changed, why is the zeromail address overwritten ? i the user never requested to be overwritten

**Comment by HelloZeroNet** [comment]
no idea, its just works that way

**Comment by icf20** [comment]
is a obvious flaw / bug then

**Comment by TheNain38** [comment]
@icf20 In ZeroMail he sets the `"domain": "Mail.ZeroNetwork.bit"` which is what is causing ZeroHello to point to the .bit domain, and not to the address directly

**Comment by icf20** [comment]
@TheNain38 
if i seed and favourite http://127.0.0.1:43110/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 i want http://127.0.0.1:43110/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 to be saved on the 1Hello not to be overwritten to Mail.ZeroNetwork.bit because i never went to Mail.ZeroNetwork.bit and never decided to favourite that address

**Comment by TheNain38** [comment]
Then you can't with the current design, because the site owner added `"domain": "Mail.ZeroNetwork.bit"` in his `content.json` file

**Comment by icf20** [comment]
zeronet cant overwrite user decision, by RMS definitions only crapware/spyware does that

**Comment by HelloZeroNet** [comment]
a zeronet site can overwrite any of your decision, if you want to change it you are free to clone/modify it.

**Comment by icf20** [comment]
{
 "address": "1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27",
 "background-color": "#FFF",
 "cloneable": true,
 "description": "End-to-end encrypted messaging",
 "domain": "",
 "files": {

still not respected on 1Hello, 1hello still points to .bit domain

**Comment by HelloZeroNet** [comment]
you have to own the site's private key to modify it

**Comment by icf20** [comment]
so why is not http://127.0.0.1:43110/1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27 saved in 1Hello correctly ?

**Comment by HelloZeroNet** [comment]
the files cached in the memory, you have to restart your client make it work

**Comment by TheNain38** [comment]
@HelloZeroNet You could add an option on ZeroHello to not link using the .bit domain, but to link directly to sites, and if the .bit now resolve to something new, you could add something like: "... is now at ... do you want to update the address?"

**Comment by icf20** [comment]
why u dint say that in the first place ? :D

**Comment by HelloZeroNet** [comment]
the modifications will be reverted on the next modification on the site, so it's not a good idea to modify file you dont own.

**Comment by TheNain38** [comment]
@icf20 Btw, if you want to contact me, you can send me a ZeroMail at `thekill38`
