### ISSUE TITLE
1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F cannot be permantly removed 

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#427]
even if the folder get removed it shows up again if zeronet is restarted

**Comment by HelloZeroNet** [comment]
you have to disable the zeroname plugin

**Comment by icf20** [comment]
that should be done when i pick the delete option from the 3 dots menu

**Comment by HelloZeroNet** [comment]
no, it's simple: if you want to use the plugin you need the site, if you don't want to use the plugin disable it
