### ISSUE TITLE
Update zeronet from zeronet

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#428]
I think Zeronet should update itself from zeronet site because:
1. Some country ban github
2. Zeronet can download file faster then GET request to github (zeronet like good CDN)
3. if github ban zeronet zero users can get updates

**Comment by HelloZeroNet** [comment]
we will think about it when its become problem, https is more reliable, than zeronet protocol

**Comment by iShift** [comment]
according to p2p from Chine it is problem http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Profile/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/13Z7XxTa7JuFat3KzzMWu3onwM6biLuurJ/p2p@zeroid.bit

Why not to make new site with zero distr or add zeronet to zero hello ?

**Comment by HelloZeroNet** [comment]
If it's common problem, then it can be possible.

**Comment by iShift** [comment]
but zero site with optional files (zeronet dist) is solution

**Comment by MuxZeroNet** [comment]
I have problems updating via ZeroUpdate. The ZeroUpdate site did not get updated, so I did not got the latest version. Showing the `rev` number and asking for confirmation can be helpful.

**Comment by border0464111** [comment]
This issue is reported to be solved in :  https://github.com/HelloZeroNet/ZeroNet/issues/416
