### ISSUE TITLE
Bundle sites

### ISSUE THREAD

**Issue by Codes4Fun** [HelloZeroNet/ZeroNet#429]
_This is just to formalize what was said on reddit._

The idea is that users can create a site that is a bundle of other sites, with the intention of distributed those sites and reducing the number of connections. I don't think the concept is the same as [Merger sites](https://github.com/HelloZeroNet/ZeroNet/issues/232), but it takes the hub concept presented there and tries to generalize it for all sites instead of just merger sites. In that way also it provides a solution to the con of having _one user per site_ possibly resulting in lots of connections.

So an example would be to look at the six default/sample sites: ZeroBoard, ZeroBlog, ZeroTalk, ZeroMail, ZeroChat, Reaction GIFs. Those sites end up needing 30 connections (5 \* 6). So in this case someone can create the first bundle site that has those sites and let other users know its available. When users connect they will only need 5 connections to the bundle site, and if they are helping sync they would maybe have 5 extra connections for each site they are helping sync. Additionally if a user doesn't want to seed all those sites they can delete the bundle site and simply seed the sites they want instead (an advantage over hubs).

A bundle site can also provide an interface like ZeroPoll that allows users to request and vote on sites to be added or removed, the site owner can then add new sites to the bundle or remove sites.

Syncing could possibly be helped by having it that when a user connects and seeds a bundle, zeronet will automatically connect and seed to a random site in the bundle, that node will then help keep the bundle and site in sync with each other. If a user is already seeding many sites in a bundle those sites can then be deleted except maybe one which will be used to sync.

**Comment by HelloZeroNet** [comment]
It could work, but it needs much deeper modifications of zeronet, and if the bundle owner decides to include 100+ sites over night it automatically downloads 100*10MB content on your hdd. This also means there is no motivation (size limit) to create new bundle sites.
And if the bundle owner decides to remove your site it will also make it unaccessible for the users, because they seeding the bundle site.
And also not sure how do you add your site to the bundle without knowing anything.

So i think there is not much benefit from it.

**Comment by Codes4Fun** [comment]
It could have a cap of 20 sites or something like that, at least in that way it could potentially reduce connections by 10 times or more. The cap would force people to create bundles and pick bundles that make sense for them.

Bundles would also help seed sites, those who seed a bundle would technically also be seeding the sites in the bundle. So someone who wants to go to a site can either connect to those directly seeding the site or those seeding a bundle that has the site, and they wouldn't (I would think) need to seed the bundle itself.

This might be something particularly useful for proxies as well, since they end up seeding lots of sites, they could reduce their connections by a lot.

> And if the bundle owner decides to remove your site it will also make it unaccessible for the users, because they seeding the bundle site.

It could be too that a user could specify which sites they like in the bundle and if the owner removes the site, ZeroNet will automatically seed the site separately from the bundle. But this will also create another problem where a bundle could remove all sites, and then user ends up now with 10 times more connections. But it could also be that If a bundle only contains one of their sites the bundle is no longer seeded and the last site is seeded independent of it.

Of course another possibility (which maybe harder) is if bundling were automatically handled in zeronet and there is no owner of a bundle, rather zeronet looks for common sites between nodes and creates and matches bundles. When a user adds or removes sites, zeronet will see if there are better matching bundles available.

Actually the whole concept of a bundle may be unnecessary (and maybe zeronet already works this way and I just don't know) but a node could just find another node who seeds a lot of the same sites they seed and that could replace having to have a lot of connections (two or more nodes could split the load of connections).

**Comment by HelloZeroNet** [comment]
Connection sharing is supported, but its not really works in sites with many peers, because query peers from the tracker you only get 20 peers and probably it will not include the ones you already connected. And for privacy reasons the connection sharing is totally disabled on Tor. (new .onion generated for every site you seed)

So think this would require many changes and I think the normal (multiuser), hub sites could work equally well. If one of the profile you follow got removed by the hub owner there can be a notification of it and you can follow the same profile on an another hub.

**Comment by Codes4Fun** [comment]
> And for privacy reasons the connection sharing is totally disabled on Tor. (new .onion generated for every site you seed)

That would be a benefit to user controlled bundle site over connection sharing, they could get some privacy, much in the same way hubs kind of hide who you are following.

> So think this would require many changes and I think the normal (multiuser), hub sites could work equally well.

Hubs probably allow for a more controlled experiment as well, see how things work.

This issue can probably be closed, unless you want to keep it open for some reason.

**Comment by purplesyringa** [comment]
> This issue can probably be closed, unless you want to keep it open for some reason.

@HelloZeroNet Not sure if this can be closed?
