### ISSUE TITLE
more document about dbschema

### ISSUE THREAD

**Issue by zeronetscript** [HelloZeroNet/ZeroNet#431]
Hello, I want to implement more functions ,but I don't known this is possible with dbschema:

for example ZeroBlog, can I add taglist (json array) property to 'post'  object, and map this to another table? or can I recursive map json array to another table inside data.json? can I add sqlite triggers to dbschema.json "indexes" to let zeronet create these custom statement? sqlite currently support json extension and Common Table Expressions(for recursive), did zeronet support this ?  thank you.

**Comment by HelloZeroNet** [comment]
if its not in zerotalk/blog/mail, then it's not supported officially

https://zeronet.readthedocs.org/en/latest/site_development/dbschema_json/ include all supported features

i think custom trigger should work if you put it as index

sqlite version depends on platform
for me on Win/Python 2.7.9 
>>> sqlite3.sqlite_version
'3.6.21'
Linux/Python 2.7.9
>>> sqlite3.sqlite_version
'3.8.7.1'
SQLite Release 3.6.21 On 2009-12-07 so it's not advised to use any new sqlite features
