### ISSUE TITLE
checking select query didn't trim leading spaces leads unnecessary error

### ISSUE THREAD

**Issue by zeronetscript** [HelloZeroNet/ZeroNet#432]
UiWebsocket.py:440   
assert query.upper().startswith("SELECT"), "Only SELECT query supported"

didn't consider leading spaces. this leads some unnecessary dbQuery error

**Comment by HelloZeroNet** [comment]
Fixed https://github.com/HelloZeroNet/ZeroNet/commit/34ead0aec233293148602d2ab4a63096aa61af47, but still recommended to start without whitespace, since most of the clients will not execute it
