### ISSUE TITLE
access to net by some routers, 15441 port is not sure opend all

### ISSUE THREAD

**Issue by xuanyuan1hao** [HelloZeroNet/ZeroNet#434]
i can access to net ，but i can not control top router and open it 15441 port, so i can not share my zeronet to web.how to slove it?

**Comment by xuanyuan1hao** [comment]
zeronet error like this:
Your network connection is restricted. Please, open 15441 port 
on your router to make your site accessible for everyone.

**Comment by Erkan-Yilmaz** [comment]
1. you don't need to open that port for Zeronet to work. Zeronet will laos work ok without it
2. did you do what is said in the FAQ already ? http://zeronet.readthedocs.org/en/latest/faq/#do-i-need-to-have-a-port-opened

**Comment by xuanyuan1hao** [comment]
my ip is 192.168.11.41.
so i has config it like this:
UPnP设备
协议	应用名称	客户端IP	内部端口	外部端口
TCP	ZeroNet	192.168.11.41	15441	15441
UDP	ZeroNet	192.168.11.41	15441	15441

but it can not work.
the error is following:
Your network connection is restricted. Please, open 15441 port 
on your router to make your site accessible for everyone.

**Comment by HelloZeroNet** [comment]
probably your internet provider/router does not allow opened port
you can check it manually on page http://portchecker.co/ by entering 15441 to port it should display "Port 15441 is open."

**Comment by ToJen** [comment]
Mine said the port is closed. What do I do about that?

**Comment by border0464111** [comment]
There is 2 possible issues, It might your network config that refuse to open the port or it might be your ISP.

You can try to fix the problem of your network if you can, otherwise Tor is your main option to circumvent the imposed limitations.

**Comment by xialvjun** [comment]
Can I use ssh reverse proxy ?

**Comment by purplesyringa** [comment]
@xialvjun Yes you can, just proxify the port ZeroNet uses.

@HelloZeroNet Can the issue be closed? I think the FAQ is straightforward enough.
