### ISSUE TITLE
Wikipedia on the 0N

### ISSUE THREAD

**Issue by FraYoshi** [HelloZeroNet/ZeroNet#435]
What about inserting wikipedia on the 0Network?

We could be able to access it offline and preserve the encyclopedia even if it goes down (I hope It will never happen!!)

**Comment by HelloZeroNet** [comment]
on zeronet the current default site size is 10MB, wikipedia contains 10TB+ data (100000x larger), so it's not really possible yet

**Comment by pataquets** [comment]
I was looking for exactly the same to help hosting the WP.
@HelloZeroNet : Does this limitation still stand? Would make sense to reopen the issue?

**Comment by pataquets** [comment]
I was looking for exactly the same to help hosting the WP.
I've read #598 and https://www.reddit.com/r/zeronet/comments/4lm813/zeronet_website_size_limit/
@HelloZeroNet : Does this limitation still stand? Would make sense to reopen the issue?
Also, is it possible to configure ZeroNet to carry just only one single zite?
