### ISSUE TITLE
About build a privilege browser make easy to nav website.

### ISSUE THREAD

**Issue by Feeding** [HelloZeroNet/ZeroNet#436]
For now,ZeroNet Site URL is too long.Not good for share.

I think is any possible we create a ZeroNet privilege browser.Embed a type of Namecoin Network.

User->Browser->P2P Domain Name Network->Point to Website True URL->Load Content->Display.

Example:
User->demo.bit->Get http://127.0.0.1:43110/{zeronet_site_address}->Display

**Comment by OliverCole** [comment]
There was/is a Chrome extension: https://chrome.google.com/webstore/detail/zeronet-protocol/cpkpdcdljfbnepgfejplkhdnopniieop?hl=en

Is that what you mean?

**Comment by Feeding** [comment]
@OliverCole not that simple. that extension can't use Namecoin DNS network.

if i want  input  demo.bit  and browser,it can't work.

**Comment by HelloZeroNet** [comment]
@Feeding It works by using ZeroName site's database. If you enable the ZeroName-local plugin it will use your local namecoin database

**Comment by Feeding** [comment]
@HelloZeroNet @OliverCole Thanks!
