### ISSUE TITLE
Prompt user to download sites

### ISSUE THREAD

**Issue by ymski** [HelloZeroNet/ZeroNet#44]
Creating an issue about an enhancement discussed in irc that I'm working on.

Currently there are some security issues in regards to downloading sites. A good implementation would be to prompt a user prior to downloading a site in which would output metadata such as the site description and directory size, along with an accept or decline. Among the initial download, there is also no prompt to accept or decline the update of a site being published that grows in size. 

Suggestions or enhancements to such an idea are of course welcome.

**Comment by HelloZeroNet** [comment]
I think it could work this way:
 - By default every site has 10MB size limit
 - If the site used 80% of its limit zeronet displays a notification when you visit the site: `This site want to store more data than current limit: 10MB. [Incrase limit to 20MB]`
 - The limit steps: 10MB, 20MB, 50MB, 100MB, 500MB, 1GB, 5GB, 10GB, Unlimited
 - If a new update to content.json comes in and the total size of site exceed the limit then the update will be rejected.
 - If you visit a new site and its size larger than 200MB then the notification will be displayed on the loading screen and the download wont be started until you give the permission

**Comment by shakna-israel** [comment]
As a side not, prompting for downloading may need to include other warnings.

E.g. A user should be able to cancel the download of a site that contains materials illegal in their country.

Something like a NSFW warning before downloading. It would have to rely on site creators, but it's a nice workaround.

**Comment by HelloZeroNet** [comment]
Added in version 0.2.1:
![sizelimit](https://cloud.githubusercontent.com/assets/10350359/6200295/73dc987e-b471-11e4-9438-4d23e5adb5d4.png)

NSFW warning can be added later if necessary
