### ISSUE TITLE
Can't open the sidebar when browsing on Chrome for Android

### ISSUE THREAD

**Issue by PeterCxy** [HelloZeroNet/ZeroNet#442]
Tried long-pressing the up-right button and sliding on it, but nothing made the sidebar show up.

**Comment by HelloZeroNet** [comment]
Sidebar is not supported on mobile

**Comment by HelloZeroNet** [comment]
(reopened as mybe someone else has mobile phone access/able to add support)

**Comment by OliverCole** [comment]
Perhaps an emulator? https://developer.chrome.com/devtools/docs/device-mode

**Comment by HelloZeroNet** [comment]
It's works in emulator

**Comment by HelloZeroNet** [comment]
Fixed in latest revision eedce00d575d6edba83ec03f6c309f95883d0936 (at least it works in the emulator)
