### ISSUE TITLE
Database server for a website

### ISSUE THREAD

**Issue by hayzamjs** [HelloZeroNet/ZeroNet#443]
Hey peeps, 

I was planning on using ZeroNet to make a website, but I came across a huge issue, databases. I read about something sql related with ZeroNet, but don't know much, so I am planning on a website which will have a lot of database needs, there will be a good amount of data, what do you guys think? If someone could lead me to the right direction then it would awesome! :)

**Comment by HelloZeroNet** [comment]
You can find a sql based chat tutorial at zeroblog

**Comment by OliverCole** [comment]
You should read the developer documentation and slideshow which is linked from the readme.

What you need to bear in mind is that the database is really just formed of data in JSON files published by individual users, and then mapped into the database. There's no backend process to run the database for you, unless you run something periodically on your own machine (which isn't great).

ZeroNet isn't great at hosting large amounts of data - how much were you thinking of?

**Comment by OliverCole** [comment]
It won't take long to run through the build a site tutorial - it's on the sidebar in ZeroBlog.

**Comment by Fazelesswhite** [comment]
Thanks a lot guys, It's gonna be around 2-3 megabytes of data per day at max

**Comment by border0464111** [comment]
im glad the problem have been solved, would it be time to close the issue ?

**Comment by grez911** [comment]
@HelloZeroNet Please, close the issue.
