### ISSUE TITLE
WerFault.exe bug

### ISSUE THREAD

**Issue by leoxxx** [HelloZeroNet/ZeroNet#445]
If WerFault.exe in  process list, zeronet is failed to run.
WerFault.exe is appeared by right click the 0 icon to quit.

**Comment by HelloZeroNet** [comment]
http://windows-exe-errors.com/how-to-disable-werfault-exe-in-windows/

**Comment by leoxxx** [comment]
I has set it.But WerFault.exe is still appeared.

**Comment by purplesyringa** [comment]
@HelloZeroNet Given the inactivity and the almost zero relationship with ZeroNet, can we close the issue?

**Comment by leoxxx** [comment]
Close please. I give it up.

**Comment by purplesyringa** [comment]
I guess you can close the issue yourself? Also, we've changed quite a lot in ZeroNet code so it might be useful to try again.
