### ISSUE TITLE
Incorrect update prompt

### ISSUE THREAD

**Issue by unsystemizer** [HelloZeroNet/ZeroNet#446]
- Running a newer version than the "latest" release, but still getting prompted to update

![image](https://cloud.githubusercontent.com/assets/13134193/14941261/c7eabfec-0fc7-11e6-81a9-370ac0889227.png)

**Comment by HelloZeroNet** [comment]
The old ZeroHello is no longer actively supported, please switch to 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D

**Comment by unsystemizer** [comment]
Okay, closing this then
