### ISSUE TITLE
Should add ZeroID register portal

### ISSUE THREAD

**Issue by LinkEscapist** [HelloZeroNet/ZeroNet#450]
No obvious register portal in the home page,only to click these official apps to be noticed to register.that isnt friendly to the new users

**Comment by HelloZeroNet** [comment]
you don't need registration to visit any site. if you try to use any feature that is requires zeroid the site will redirect you to the id providers it accepts. i think it's pretty simple and hard to miss it

**Comment by Jzarecta** [comment]
I think it should be important to have an ID wallet built on ZeroNet utilities. Given the issues with ZeroID from the point of view of privacy.

**Comment by unsystemizer** [comment]
@Jzarecta why are you making off-topic topic comments in unrelated issues?

**Comment by Jzarecta** [comment]
I didnt think this was off-topic, actually I was going to open a new thread when I saw this hits to a similar sissue.

**Comment by border0464111** [comment]
It seem to work as designed to me. Closing ?
