### ISSUE TITLE
AdvOR support

### ISSUE THREAD

**Issue by gema-arta** [HelloZeroNet/ZeroNet#451]
`TorManager Tor controller connect error: AttributeError: 'NoneType' object has no attribute 'group' in TorManager.py line 157`

**Comment by Erkan-Yilmaz** [comment]
can you provide more info please ?
at least your used tor, ZeroNet verison, what you did at that moment the error hapepend ?

**Comment by border0464111** [comment]
OP did not provide enough information to have a proper reproducible or solvable issue. Closing ?

**Comment by grez911** [comment]
Non-reprodicible issue.
@HelloZeroNet Please, close.
