### ISSUE TITLE
Zeroname_updater.py imports unresolvable?

### ISSUE THREAD

**Issue by xtraeme-xt** [HelloZeroNet/ZeroNet#454]
https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/Zeroname/updater/zeroname_updater.py#L9

I was investigating why one of my .bit domains wasn't popping up on 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F even though the name_first_update for the d/record had 122 confs over a 24 hour time-frame. After a little investigating into how the zeroname_updater.py worked I discovered the `bitcoinrpc.authproxy` module doesn't exist. Quickly grabbing [Garzik's bitcoinrpc module](https://github.com/jgarzik/python-bitcoinrpc) confirmed that there's only a `proxy` module not an `.authproxy` module. 

```
import bitcoinrpc
help(bitcoinrpc)
```
Returns:
```
PACKAGE CONTENTS
    config
    connection
    data
    exceptions
    proxy
    util
```
and:

```
pkgpath = os.path.dirname(bitcoinrpc.__file__)
print [name for _, name, _ in pkgutil.iter_modules([pkgpath])]
```

Returns:

`['config', 'connection', 'data', 'exceptions', 'proxy', 'util']`

Simply changing the line from:
`from bitcoinrpc.authproxy import AuthServiceProxy`
to:
`from bitcoinrpc.proxy import AuthServiceProxy`

Seems to work, but I want to make sure I'm not overlooking anything. 

To be thorough I went looking through the ZeroNet bundled Python lib\site-packages to check for a copy of bitcoinrpc, but didn't find anything. Also grepping through the folder structure didn't return much to go off of. Most of the time I just work with `jsonrpc import ServiceProxy` directly so I'm not as familiar with bitcoinrpc. Is there an older version of bitcoinrpc ZeroNet depends on or any modifications not included in the github repo?

**Comment by HelloZeroNet** [comment]
whats your domain name? the problem probably is different

**Comment by xtraeme-xt** [comment]
Looks like it might have been something silly. The original JSON was: `{ "zeronet" : { " " : "some-address" } }`. When I removed the space between the double quotes `{ "zeronet" : { "" : "some-address" } }` the namecoin/zeronet pairing was picked up almost instantly by 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F.
