### ISSUE TITLE
rss plugin not work when incorrect feed used

### ISSUE THREAD

**Issue by zeronetscript** [HelloZeroNet/ZeroNet#455]
if one site provides incorrect feed (such as lacking column), all feeds  disappears. only 

notification:
Internal error: xxxxxx
UiWebsocket.py line 98 > UiWebsocket.py line 176 > NewsfeedPlugin.py line 42

 it should skip incorrect ones and notify user the bad sites.

**Comment by HelloZeroNet** [comment]
Fixed: d2d2967f11f0009547959b57e0f25d1e590da852
