### ISSUE TITLE
Bookmark function

### ISSUE THREAD

**Issue by homersimpsons** [HelloZeroNet/ZeroNet#456]
Can you add something to ZeroHello to ge the ability to create site categories (for example: utilities, social, games, torrent etc...)

**Comment by HelloZeroNet** [comment]
You browser's bookmark function probably more suited for this

**Comment by homersimpsons** [comment]
Yes but to find with zite to delete, or tu update all our social website, or to pause utilities it could be more useful

**Comment by HelloZeroNet** [comment]
you can also use the sidebar to delete/update/pause the site (drag the topright zero button to left)

**Comment by homersimpsons** [comment]
When you have a look to Torrent Manager, there are differents categories to help the user manage his contents. So, in my mind, it should be the same for ZeroNet

**Comment by border0464111** [comment]
I also think you should use your browser for this. Nerverless, I tansfered the issue on the proper repository.
 Could you add a link or image to this `Torrent Manager` you are mentioning.

https://github.com/HelloZeroNet/ZeroHello/issues/56

**Comment by homersimpsons** [comment]
Deluge and µTorrent (at least) have categorization options.
