### ISSUE TITLE
Possibility to not force Perl 2.7 version?

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroNet#459]
I see that signing and probably also publishing perl script wants 2.7 perl version, i assume it is not intended to support also older versions like 2.6.x? I have older OS (CentOS 6.x) and i always listen it should work with 2.6 and i should not replace it by 2.7, and i was unsuccessfull installing 2.7 in paralel.
 /usr/bin/env: python: No such file or directory

**Comment by HelloZeroNet** [comment]
sorry, its not possible, but you can download the zerobundle version that is contains everything you need to run zeronet: https://github.com/HelloZeroNet/ZeroNet#how-to-join
