### ISSUE TITLE
Certificate currently selected bug

### ISSUE THREAD

**Issue by grez911** [HelloZeroNet/ZeroNet#462]
After you have created new certificate with command "certAdd" it will shown as currently selected (see screenshot). But in reality you can't use it for posting until you click on it. So it is not actually selected. Only when you click on this cert, certificate register name will be added to users.json in section with sites (as "cert" property).

---

![screenshot from 2016-05-22 15 29 12](https://cloud.githubusercontent.com/assets/12672853/15453998/cd950f84-2033-11e6-8fef-3f41db04e044.png)

---

You can trace this bug on [nanasi board](http://127.0.0.1:43110/16KzwuSAjFnivNimSHuRdPrYd1pNPhuHqN), for example.
I think that label "currently selected" must be displayed only when name of certificate issuer added to sites section in users.json.

**Comment by Plasmmer** [comment]
@HelloZeroNet is this yet a issue?

**Comment by HelloZeroNet** [comment]
Thanks it was fixed some months ago: https://github.com/HelloZeroNet/ZeroNet/commit/dafe9981a241e5ff170bd989abcd77e85acaf3aa
