### ISSUE TITLE
Customized addresses or brute force?

### ISSUE THREAD

**Issue by EtherTyper** [HelloZeroNet/ZeroNet#465]
Do you customize the addresses of our official ZeroNet websites, or do you just keep making sites until it gives you the prefix you want? If so, have you released scripts to automate this?

Some examples:
```
1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D
1TaLkFrMwvbNsooF4ioKAY9EuxTBTjipT
1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8
1Gif7PqWTzVWDQ42Mo7np3zXmGAo3DXc7h
1MaiL5gfBM1cyb4a8e3iiL8L5gXmoAJu27
1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F
1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz
1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp
```

Thanks,
Eli

**Comment by HelloZeroNet** [comment]
ZeroNet site addresses are 100% compatible with bitcoin, so you can use:
https://bitcointalk.org/index.php?topic=25804.msg321135#msg321135

**Comment by EtherTyper** [comment]
@HelloZeroNet Awesome, thanks! Is there any command-line flag to use this private key in the creation of a new site, or do I have to construct a `content.json` from scratch?

**Comment by HelloZeroNet** [comment]
Easiest way:
 - Generate an address/privatekey with vanitygen
 - zeronet.py siteCreate
 - Rename data/createdsiteaddress to data/vanityaddress
 - zeronet.py siteSign vanityaddress vanityprivatekey
 - visit 127.0.0.1:43110/vanityaddress
