### ISSUE TITLE
Add Possibility to download ZeroNet from within ZeroNet :)

### ISSUE THREAD

**Issue by Richard87** [HelloZeroNet/ZeroNet#468]
The title sais it all actually, I think the dashboard should contain a link, so everyone hosting a proxy would keep zeronet source also distributed :)

Richard

**Comment by EtherTyper** [comment]
See #416. This is a hot subject, and the reason the implemented the gogs.io and GitLab mirrors.

**Comment by border0464111** [comment]
Duplicate of the closed https://github.com/HelloZeroNet/ZeroNet/issues/416 issue.   
Closing?
