### ISSUE TITLE
Uncaught SecurityError:

### ISSUE THREAD

**Issue by calebebrim** [HelloZeroNet/ZeroNet#469]
I'm using google chrome.
I'm also using two machines; these one is only to sync and visualize.
When I open my page on the same computer that I use to seed my page everything is allright; Open the same page on the second computer my page doesn't load propertly. 

I copy the error that i cought on the google chrome console: 

`jquery.mobile-1.4.5.min.js:1 Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://127.0.0.1:43110/1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E/?wrapper_nonce=a1344e8476979d76d7b7121fab4cc68f9ec61d422f653abc3d9cc9e1526dcdf9' cannot be created in a document with origin 'null' and URL 'http://127.0.0.1:43110/1ErAxF8656uGB4rcmWZzkdvDGvP2nvg77E/?wrapper_nonce=a1344e8476979d76d7b7121fab4cc68f9ec61d422f653abc3d9cc9e1526dcdf9'.
`

Some help please??

**Comment by HelloZeroNet** [comment]
History/Cookie and some other manipulations are restricted by browser iframe sandbox

**Comment by calebebrim** [comment]
You mean that jquery mobile are not supported?

**Comment by HelloZeroNet** [comment]
You can't use replaceState (url modification) functions directly, maybe it's possible to disable in jquery mobile

**Comment by calebebrim** [comment]
But why it works on the computer that I developed?
It is not supposed to work right?

**Comment by HelloZeroNet** [comment]
Yes, if it's works on one machine, then it's different problem, are you sure every file is well synced?

**Comment by calebebrim** [comment]
Yes... Sign and publish more than one time.

Note. 
machine1: OSX. (I develop here)
machine2: Windows.

**Comment by HelloZeroNet** [comment]
I mean are the files has the same content?

**Comment by calebebrim** [comment]
Yes,I do thing so. 
How do I check it out?

**Comment by calebebrim** [comment]
I mean there is a simple way to compare? ... like checksum?

**Comment by HelloZeroNet** [comment]
check the directory sizes should be enought

**Comment by border0464111** [comment]
I googled a bit, Many webdevs are reporting inconsistent behaviour across browsers concerning the use of replaceState inside iframe. 

EX: https://stackoverflow.com/questions/25386811/history-replacestate-issue-with-iframes

I doubt this issue is zeronet specific.

**Comment by HelloZeroNet** [comment]
It does not affect us, since the replace/push state command is executed outsite of the iframe by zeroframe api commands
