### ISSUE TITLE
Gevent Broken Pipe

### ISSUE THREAD

**Issue by shakna-israel** [HelloZeroNet/ZeroNet#47]
When running in debug mode, accessing the console raises [Gevent #445](https://github.com/gevent/gevent/issues/445), in UiServer and UiRequest.

![Console Window](https://imgur.com/VWYSQLN.jpg)

![Debug Window](https://imgur.com/grbh0dN.jpg)

**Comment by HelloZeroNet** [comment]
It's normal: 
 - /Console raises a custom exception "Here is your console" to spawn the werkzeug console in UiRequest namespace. (You can access the console by hover over `raise Exception("Here is your console")` line the clicking the second icon from right.) Its a little bit hackish, but works :)
 - /Debug always display the last error's namespace (in next version I will exclude notifications from it)

**Comment by shakna-israel** [comment]
```
'HTTP_HOST': '104.131.8.131',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'HTTP_X_FORWARDED_FOR': '66.249.73.184',
 'HTTP_X_REAL_IP': '66.249.73.184',
 'PATH_INFO': '/Console',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '54914',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'tester',
 'SERVER_PORT': '43110',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f53f74101e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7f53eaac0910>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with Exception
```

In the console seems a bit odd, in that case.

**Comment by HelloZeroNet** [comment]
Ah looks like the google bot found the console url somehow. I'm going to restrict the /Console and /Debug access to debug mode only.
