### ISSUE TITLE
ZeroNet for docker port forward

### ISSUE THREAD

**Issue by droid-Q** [HelloZeroNet/ZeroNet#473]
I am using ZeroNet for docker in my docker for mac . I set the port  forward  15441>0.0.0.0:15441.
Like this :
 
<img width="342" alt="screen shot 2016-05-30 at 9 51 55 am" src="https://cloud.githubusercontent.com/assets/708277/15637862/306f4e08-264c-11e6-86f7-e31c59d8ffac.png">
But ZeroNet shows the 15441 port is not opened.
And I am using ZeroNet in my parallels desktop  windows 10  too,it's ok.
i do not know it is docker for mac 's issue or zeronet 's issue.

**Comment by HelloZeroNet** [comment]
it's probably router/os firewall configuration issue. you can use http://portchecker.co/ to check if the port opened or not

**Comment by droid-Q** [comment]
@HelloZeroNet 
 It is opened.
<img width="560" alt="screen shot 2016-05-30 at 4 41 54 pm" src="https://cloud.githubusercontent.com/assets/708277/15644409/76dd4a82-2685-11e6-9743-63ecfff7086f.png">
I saw the zeronet docker container log,the system is checking port 15441 using portchecker.co.But it is fail.
