### ISSUE TITLE
--debug option causes ZeroNet to not work properly

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#476]
When I add --debug, 'all.js' file doesn't load into the client any more (it becomes a pending query). And the main page 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D also doesn't work.

**Comment by HelloZeroNet** [comment]
probably something with the coffeescript compiler, please check console/logs (use --verbose if necessary)

**Comment by yurivict** [comment]
I am only seeing this error: https://github.com/HelloZeroNet/ZeroNet/issues/477

This may or may not be a related - not sure.

**Comment by yurivict** [comment]
#477 is the real reason.
