### ISSUE TITLE
coffee compiler isn't invoked when the site is accessed locally (all.css isn't regenerated either)

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#478]
After I change the .coffee files, siteSign doesn't run the coffee compiler so that all.js remains the same (--debug option is set). all.js is only updated when I access the site after siteSign.

coffee script should be run during the siteSign operation.

**Comment by HelloZeroNet** [comment]
I'm not sure about this. If you make any changes to your site's source you should try it if it's works or not (using the web interface) and it will be compiled on the file request.

**Comment by yurivict** [comment]
This doesn't happen either, all.css and all.js aren't regenerated either when I run the site.

**Comment by yurivict** [comment]
For me it is only regenerated when I access the site after signing it, and also not every time. Something is wrong with this.

**Comment by HelloZeroNet** [comment]
It's probably caused by your browser's caching. You should open the dev tools (F12) and check disable caching when developing

**Comment by yurivict** [comment]
I see. Thank you. I was under impression that "Reload" invalidates cache but it turns out that it doesn't for css and js.

**Comment by anoadragon453** [comment]
I also found an issue with automatic compiling of coffeescript with the `--debug` flag on. My local site would 404 on a request to all.js every time, even when signing/publishing, manually refreshing with Ctrl-Shift-R and/or having the dev tools open (and yes the option for not caching with the tools open is checked). I'm running the latest version of FF Developer Edition and Zeronet v1422 under Arch Linux x64.

I was following the tutorial [here](http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:43:ZeroNet+site+development+tutorial+1) for creating a site but was stuck for hours until I realized it wasn't compiling the coffee-script automatically. My code and directory structure matches what was given in the tutorial. I was about ready to give up until I compiled manually.

The command I used to start Zeronet:
`sudo -u zeronet /usr/bin/env python2 zeronet.py --config_file /etc/zeronet.conf --debug`

Contents of config file:
```
[global]
data_dir = /opt/zeronet/data
log_dir = /var/log/zeronet
```

Output of above Zeronet command when unable to find all.js: [here](https://gist.github.com/anoadragon453/28af08e61410afd7040ac845c56de598). The site's address is 1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq.

I appreciate any help.

**Comment by HelloZeroNet** [comment]
you can use `python -c "import distutils.spawn; print distutils.spawn.find_executable('coffee')"` to check if coffee binary is visible by python or not. Or you can use `--coffeescript_compiler "/usr/local/bin/coffee --no-header -p"` to define the path of it

**Comment by anoadragon453** [comment]
It seems to be able to find it.

```
➜  js git:(master) ✗ python2 -c "import distutils.spawn; print distutils.spawn.find_executable('coffee')"
/usr/bin/coffee
```

After running:
`sudo -u zeronet /usr/bin/env python2 zeronet.py --config_file /etc/zeronet.conf --debug --coffeescript_compiler "/usr/bin/coffee --no-header -p"`

I still have the same issue, all.js not generated and returning a 404.

Permissions on /usr/bin/coffee are default rwxrwxrwx.

**Comment by anoadragon453** [comment]
Funnily enough an `all.js?rev=1422` file that contains coffee-script is generated under `/uimedia/all.js?rev=1422`, however I am unsure if this is generated by my site or not.

**Comment by HelloZeroNet** [comment]
are you sure you have enabled the  "this is my site" option on the sidebar?

**Comment by anoadragon453** [comment]
...I have not enabled that. Might want to add that to the tutorial :)

Give me one moment while I do that. In the meantime, another quick concern I have is that I often get the message that "This function is disabled on this proxy", for instance when toggling on the `This is my site` option just now. I believe this is the Multiuser plugin causing this, but is there a way to keep Multiuser on and avoid these errors?

**Comment by HelloZeroNet** [comment]
start it using `--multiuser_local` to remove that limitations

**Comment by anoadragon453** [comment]
Thank you. Also after enabling the "This is my site" option I am presented with a javascript alert() that states:
```
/opt/zeronet/data/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/lib/ZeroFrame.coffee compile error: File not found: /opt/zeronet/opt/zeronet/data/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/lib/ZeroFrame.coffee
```

This is the contents of my data/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq folder:
```
➜  1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq git:(master) ✗ tree
.
├── content.json
├── index.html
└── js
    ├── all.js
    ├── lib
    │   └── ZeroFrame.coffee
    └── ZeroChat.coffee
```

As you can see the all.js file is generated however only with the contents of the alert:

```


/* ---- /1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/lib/ZeroFrame.coffee ---- */


alert('/opt/zeronet/data/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/lib/ZeroFrame.coffee compile error: File\ not\ found\:\ \/opt\/zeronet\/opt\/zeronet\/data\/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq\/js\/lib\/ZeroFrame\.coffee\n');


/* ---- /1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/ZeroChat.coffee ---- */


alert('/opt/zeronet/data/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq/js/ZeroChat.coffee compile error: File\ not\ found\:\ \/opt\/zeronet\/opt\/zeronet\/data\/1A6J3fhJvUc7eTfonTU24a4n8GTM46YBxq\/js\/ZeroChat\.coffee\n');
```

Permissions of js/lib/ZeroFrame.coffee are `rwxrwxr-x`.

**Comment by anoadragon453** [comment]
Oh hey! I managed to fix it!

The issue was putting `data_dir = /opt/zeronet/data` in zeronet.conf. Seems that was appended a second time to the dir that coffee-script was looking in. Seems like a bug.
