### ISSUE TITLE
Change Base58 key 

### ISSUE THREAD

**Issue by Tyronethedev** [HelloZeroNet/ZeroNet#48]
Hi, i believe address should begin with Z 
https://en.bitcoin.it/wiki/Base58Check_encoding
chart says 32 is the Z character

**Comment by HelloZeroNet** [comment]
I have been thinking about it earlier, but it would have some problems:
 - The currently used bitcoin crypto libs doesn't support it, so its need to be modified
 - Vanity address generator would not work

So I don't think it worth the mess up.
