### ISSUE TITLE
Error: TypeError: 'bool' object has no attribute '__getitem__' UiWebsocket.py

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#480]
I installed ZeroBlog, tried to edit my own comment as some logged in user, and got these errors:

```
Internal error: TypeError: 'NoneType' object does not support item assignment
UiWebsocket.py line 98 > UiWebsocket.py line 178 > UiWebsocket.py line 476
```

```
Internal error: TypeError: 'bool' object has no attribute '__getitem__'
UiWebsocket.py line 98 > UiWebsocket.py line 174 > UiWebsocket.py line 318 > UiWebsocket.py line 278
```

**Comment by HelloZeroNet** [comment]
probably you have changed data/users/content.json and have not signed it

**Comment by yurivict** [comment]
No, I signed and published the site, jq validates contents.json fine.

The error messages appear when I clieck on "2 comments" under the blog post. It also doesn't show the comments.

Something isn't working, but I can't tell what.

**Comment by HelloZeroNet** [comment]
try edit your comment on zeroblog, if it does not drop error then the problem is in your site. try delete/readd it and check if every file is synced

**Comment by yurivict** [comment]
Sorry, it was a missing data/users/content.json file.
