### ISSUE TITLE
[feature suggestion] Need to prioritize peer downloads, assign the highest priority to the files that browser requested

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#481]
I intentionally lowered the bandwidth of the tor relay such that only the smaller files can get through fast enough (see RelayBandwidthRate and RelayBandwidthBurst in torrc). ZN keeps downloading the larger files and fails smaller important files all.css and all.js with 404. The browser usually asks for more important files first.

ZN should move the files that browser requests to the top of the download queue so that the client will more likely see some version of the site instead of just waiting for something that he maybe doesn't even need at the time.

**Comment by HelloZeroNet** [comment]
its already done: 
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiRequest.py#L352
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Worker/WorkerManager.py#L317
