### ISSUE TITLE
portchecker.co port test error

### ISSUE THREAD

**Issue by droid-Q** [HelloZeroNet/ZeroNet#483]
this is my docker container log:
   [08:04:04] FileServer Checking port 15441 using portchecker.co...
   [08:05:03] FileServer Internet offline,
But i have used the curl to test the portchecker.co in the container.It is working.
    curl -X "POST" "http://portchecker.co/check" \
	-H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
	--data-urlencode "port=15441"
It can return right result that shows the port is opened.

**Comment by droid-Q** [comment]
Now i am not using zeronet in the docker. I am running zeronet in my mac.

**Comment by HelloZeroNet** [comment]
Is this problem gone? What was the problem?

**Comment by droid-Q** [comment]
@HelloZeroNet  it's not gone,maybe it is docker for mac 's problem.
