### ISSUE TITLE
Parsing of markdown URLs with parentheses fails

### ISSUE THREAD

**Issue by unsystemizer** [HelloZeroNet/ZeroNet#486]
`[this](http://127.0.0.1:43110:/123/doesn't (work))`

I don't know if it should, maybe the internal brackets should be escaped.

**Comment by border0464111** [comment]
Maybe you should report the problem to the site owner. This repository is for the zeronet core.

**Comment by HelloZeroNet** [comment]
more specifically the problem(?) is in https://github.com/chjj/marked js lib
