### ISSUE TITLE
Hello Zeronet site shows wildly different peer counts on different hosts

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#490]
I have several ZN instances running on different hosts/OSes, all with tor=always.

For some reason Hello Zeronet shows very different peer counts:

```
This site currently served by 385 peers, without any central server.
This site currently served by 585 peers, without any central server.
This site currently served by 481 peers, without any central server.
This site currently served by 688 peers, without any central server.
```

The separate counts of onion peers are also all very different.

This is confusing, shouldn't they be all the same or very close?

**Comment by HelloZeroNet** [comment]
it not an issue, it's depends on how long have you been running the client (it requests around 50peer/5min) and what other users have you been exchanged peers.
There is no real benefits between having 30 vs 600 peers on a site.

**Comment by yurivict** [comment]
Maybe it makes more sense to show seeders count instead? Because it seems that the tracker returns seeders/leachers counts.

**Comment by HelloZeroNet** [comment]
well there is no leechers in zeronet, so peers = seeders

**Comment by border0464111** [comment]
Question answered. Closing ?

**Comment by yurivict** [comment]
Thanks!
