### ISSUE TITLE
Favorites reset 

### ISSUE THREAD

**Issue by unsystemizer** [HelloZeroNet/ZeroNet#491]
I haven't restarted ZeroNet but all my Zeronet Favorites were un-favorited.

**Comment by HelloZeroNet** [comment]
its currently stored in browsers local storage, later something more persistent are planned

**Comment by unsystemizer** [comment]
Yes, I cleared my browser cache (I also notice this before when I accessed using a different browser). You can close this unless you want to leave it open for later enhancement. Also feel free to change issue title.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?

**Comment by HelloZeroNet** [comment]
Favorites are stored in users.json now.
