### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by liaoran** [HelloZeroNet/ZeroNet#493]
How to use registered zeronet id？

**Comment by unsystemizer** [comment]
this is not a discussion forum, please use ZeroTalk or other venue

**Comment by MuxZeroNet** [comment]
@liaoran [ZeroTalk](http://127.0.0.1:43110/Talk.ZeroNetwork.bit) [ZeroMe](http://127.0.0.1:43110/Me.ZeroNetwork.bit) [Comment on ZeroBlog](http://127.0.0.1:43110/Blog.ZeroNetwork.bit)
Your certificate should work, when you clicked on **sign in.** Please close this issue if you don't have further questions.
