### ISSUE TITLE
ZeroNet, Tor and Arch Linux

### ISSUE THREAD

**Issue by Bobses** [HelloZeroNet/ZeroNet#494]
I cannot start Zeronet with Tor on Arch Linux.
I edited /etc/tor/torrc and removed the # character from lines ControlPort 9051 and CookieAuthentication 1, then I restarted tor service.
How can I add permission for my user to read the auth cookie? The following command doesn't work:

ls -al /var/run/tor/control.authcookie

I receive the following error when I start zeronet:

TorManager Tor controller connect error: IOError: [Errno 13] Permission denied: u'/var/lib/tor/control_auth_cookie' in TorManager.py line 165

Any idea? Thanks

**Comment by HelloZeroNet** [comment]
use ls -al /var/lib/tor/control_auth_cookie instead then follow: https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by Bobses** [comment]
The answer is:

-rw------- 1 tor tor 32 Jun 12 12:11 /var/lib/tor/control_auth_cookie

I don't find the file's user group so that I add permission to my user.

**Comment by HelloZeroNet** [comment]
You need to add `ExtORPortCookieAuthFileGroupReadable 1` to tor config, `usermod -a -G tor [yourlinuxuser]`, re-login, and restart, then it should work

**Comment by Bobses** [comment]
Thanks, HelloZeroNet.
 I tried, but doesn't work: I added ExtORPortCookieAuthFileGroupReadable 1 to /etc/tor/torrc but nothing changed.

**Comment by HelloZeroNet** [comment]
there is an another option, please try this one: CookieAuthFileGroupReadable 0|1

**Comment by Bobses** [comment]
I set CookieAuthFileGroupReadable to 1 in /etc/tor/torrc but nothing changed: when I start zeronet with "python2 zeronet.py --tor always" or "python2 zeronet.py" I receive the same error:

"TorManager Tor controller connect error: IOError: [Errno 13] Permission denied: u'/var/lib/tor/control_auth_cookie' in TorManager.py line 165"

**Comment by HelloZeroNet** [comment]
The permission error come from the operating system, it not really a zeronet issue, please re-check every permission/tor logfile/tor documentation/etc.

**Comment by Bobses** [comment]
Ok, thanks. I'll do that.

**Comment by Split7fire** [comment]
Bobses, you just need to read comments carefully. https://aur.archlinux.org/packages/zeronet-git

**Comment by border0464111** [comment]
@Bobses solved ?

**Comment by grez911** [comment]
https://github.com/HelloZeroNet/ZeroNet#arch-linux

@HelloZeroNet Please, close.
