### ISSUE TITLE
With "tor=always" ZN says that the port is closed when it is in fact open from the previous run

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#501]
Due to https://github.com/HelloZeroNet/ZeroNet/issues/466 the port 15441 stays open between runs, but ZeroNet still says "PORT: CLOSED" which is wrong and misleading. Additionally, port could just be open on the router.

Since the port might be open outside of ZN control, ZN should correctly detect if it is open and say "PORT: UNUSED BUT OPEN" or something to that effect.

Port being open vs. closed is a security matter, and ZN should handle the situation carefully and accurately.

**Comment by HelloZeroNet** [comment]
zeronet does not knows/tests your public ip address when running in tor mode, so it's not possible
