### ISSUE TITLE
No peers found, sitePublish command only works if you already have visitors serving your site

### ISSUE THREAD

**Issue by molykim** [HelloZeroNet/ZeroNet#502]
./ZeroNet.sh sitePublish xxxxxxxxxxxxxxxxxxxxxxxxxxx // my site address
- Starting ZeroNet...
- OpenSSL loaded, version: 01000207F
- Loading site...
- Creating FileServer....
TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 344
FileServer Checking port 15441 using portchecker.co...
FileServer [BAD :(] Port closed: Port 15441 is closed.
FileServer Trying to open port using UpnpPunch...
FileServer Checking port 15441 using portchecker.co...
FileServer [BAD :(] Port closed: Error: URLError: <urlopen error timed out> in FileServer.py line 97 > urllib2.py line 154 > urllib2.py line 431 > urllib2.py line 449 > urllib2.py line 409 > urllib2.py line 1227 > urllib2.py line 1197
FileServer Checking port 15441 using canyouseeme.org...
FileServer [BAD :(] Port closed: Error: I could not see your service on 116.216.30.51 on port (15441) Reason: Connection timed out
FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
- Gathering peers from tracker
Site:1MGiNz..xxxx Publishing content.json to 5/0 peers (connected: 0) diffs: [] (0.00k)...
- No peers found, sitePublish command only works if you already have visitors serving your site

**Comment by molykim** [comment]
i just create the site and publish, so someone can visit.
any thing wrong? please help me, thank you very much.

**Comment by HelloZeroNet** [comment]
you only need to publish it if you already have visitors, who downloaded your site before

**Comment by molykim** [comment]
you mean after I create the site, it's available for other people?
but when I access the site from another computer in the same local net, it's always says:
==================================
CONNECTING...
NO PEERS FOUND
CONTENT.JSON DOWNLOAD FAILED
CONTENT.JSON DOWNLOAD FAILED
==================================

**Comment by HelloZeroNet** [comment]
zeronet does not support local peer discovery yet

**Comment by molykim** [comment]
ok, thank you very much.

**Comment by tansiret** [comment]
@HelloZeroNet no, it doesn't still work. My friend tried to connect to my site from his home (not in the same net ofc) and he got the same error. @molykim can you reopen the issue because it is still a problem?

**Comment by purplesyringa** [comment]
This means that you both don't have open ports, or your trackers are not working. Upload your site to some proxy like z.hex3.cf or 0net.io. I have an open port right now too so if you want me to seed a site, I can do that.

**Comment by tansiret** [comment]
@imachug thanks but how to do that?
