### ISSUE TITLE
index.html download failed

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#505]
i have this site - http://127.0.0.1:43110/159kokXBtcD1zcyB5bo6257kDToq9vcPei/
i can see it on my localhost but when peers try to download it they recieve an "index.html download failed" error. what am i doing wrong?

**Comment by wigy-opensource-developer** [comment]
I can just confirm that `index.html` was not downloaded. I see you are using the 0.3.6 version of the client. Could you try updating that to 0.3.7 to see if that helps? Also, newer versions have an `inner_path` key in all `content.json` files. This is missing in your root `content.json`

**Comment by wigy-opensource-developer** [comment]
I get the following in my node. How did you sign your site after the changes you made to it?

> [17:10:06] Site:159kok..cPei index.html file size does not match 16334 <> 14979, Hash: False
> [17:10:08] Site:159kok..cPei assets/css/style.css file size does not match 9305 <> 9241, Hash: False
> [17:10:10] Site:159kok..cPei app/modules/comments/directives/comment-list.directive.js file size does not match 1062 <> 603, Hash: False
> [17:10:11] Site:159kok..cPei app/modules/posts/directives/post-list.directive.js file size does not match 638 <> 454, Hash: False
> [17:10:13] Site:159kok..cPei data/comment.json file size does not match 1150 <> 850, Hash: False
> [17:10:14] Site:159kok..cPei data/users/1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp/post_vote.json file size does not match 147 <> 133, Hash: False
> [17:10:17] Site:159kok..cPei assets/less/style.less file size does not match 9719 <> 8649, Hash: False

If you are in doubt how to do it, [AceLewis](https://youtu.be/D-x9Ob7kktE?list=PLgFqcJDOq2q5orC1U4IvDBMpjezKt-X4E) created nice tutorial videos about ZeroNet

**Comment by wigy-opensource-developer** [comment]
Today I am still seeing signature problems on the zite you made:

> [14:43:52] Site:159kok..cPei index.html file size does not match 16334 <> 14979, Hash: False

Did you loose interest or do you need more time or help?

**Comment by dnelband** [comment]
hi, im sorry for the lack of reply, i moved my project to a new address, and now it works without a problem

**Comment by SiamakShams** [comment]
I have the same problem but still get "Not Found Index.html" - It's been painful journey so far so any help will be apprenticed.
