### ISSUE TITLE
Can China's GFW block the zeronet ?

### ISSUE THREAD

**Issue by zeronet0** [HelloZeroNet/ZeroNet#506]
sometimes my zeronet UI is baffling lost.

**Comment by FezVrasta** [comment]
I guess if you use both Tor and ZeroNet you should be safe?

**Comment by HelloZeroNet** [comment]
Hard to tell, but you can use Tor's OBFS proxy project to avoid it.
https://www.torproject.org/docs/pluggable-transports.html.en

Easiest way to to this is install Tor browser bundle, start it then start zeronet using `zeronet.py --tor_proxy 9150 --tor_controller 9151 --tor always`

**Comment by kskarthik** [comment]
What are the possibilities now? I heard that China blocked the zeronet website ...
