### ISSUE TITLE
Idea] AlternativeTo Concept

### ISSUE THREAD

**Issue by mcl1234** [HelloZeroNet/ZeroNet#508]
Hi,

Is it possible to add to the ZeroNet network, the concept of AlternativeTo ?
Every application has alternatives and it is listed in it.
People add the application and other check if it is the same theme / a proper alternative
And everyone can vote for their favorite applications.

http://alternativeto.net/software/alternativeto/
Currently this concept is not open-source and not distributed.

**Comment by Adrianzo** [comment]
I don't think this idea is tight-related to zeronet. IMHO this is doable in the current state of the project by any web designer.

**Comment by wigy-opensource-developer** [comment]
I agree that this zite idea does not need support from the ZeroNet client itself. It is still a good idea for a zite. Maybe there should be a label for zite ideas on this project?

**Comment by sbeeee** [comment]
This is an idea of application on this network ;)

**Comment by obv-mikhail** [comment]
Well what is the problem with the original site?

**Comment by mcl1234** [comment]
Some can delete softwares , like owncloud
7th april 2016 : https://ipfs.pics/QmcRwEMDZVwNJZ4wjrnHRYuWP6trLYAyVqCGLHqPHT8GeR
now there is no owncloud listed in the application server

**Comment by border0464111** [comment]
Someone will have to start an initiative in his own Github (or other)   in order to make this append. 
This can be as a site, no need to have the core involved in this. 
Closing ?
