### ISSUE TITLE
ZeroTalk modifications not propagating correctly

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#51]
Not every new message reaches all of the peers.

It's related to https://github.com/HelloZeroNet/ZeroNet/issues/43

Already working on new network code without ZeroMQ. It will be released in 1-2 weeks.

**Comment by apoorvasingh157** [comment]
I am unable to post a message in ZeroBoard. Even after waiting for 15 minutes it is not posting my text.

**Comment by HelloZeroNet** [comment]
It had some bug in publish method, fixed in 0.2.4
