### ISSUE TITLE
zeronet.py missing on 64bit bundle 

### ISSUE THREAD

**Issue by omgbox** [HelloZeroNet/ZeroNet#511]
this shit, is missing the zeronet.py . noway to get it running on a VPS.  
why always on local host start. ????

Linux terminal

    wget https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-linux64.tar.gz
    tar xvpfz ZeroBundle-linux64.tar.gz
    cd ZeroBundle
    Start with ./ZeroNet.sh

> how to change 127.0.01 to domain or IP ???????

**Comment by HelloZeroNet** [comment]
it will download the source when you start it using zeronet.sh
