### ISSUE TITLE
ZERONET INSTALLATION ON MAC OS X 10.10.3.

### ISSUE THREAD

**Issue by tonyassassin** [HelloZeroNet/ZeroNet#514]
Followed simple installation instructions for zero net and nothing happened. I downloaded bundle for mac opened ZeroNet app in bundle and got zero activity. I know nothing about code or open source projects so I need a little advice on getting this prog to run, thanks!

**Comment by FezVrasta** [comment]
Same problem.. I double click it and nothing happens and the sites don't work

**Comment by Adrianzo** [comment]
1. Install Homebrew and then use it in a terminal to install python:
$ brew install python
2. Install python libraries:
$ pip install gevent msgpack-python
3. Download, Unpack & run (in newly created directory):
$ python zeronet.py

I recommend you to use tor-browser and encrypt the folder where all these apps are installed.

**Comment by FezVrasta** [comment]
Can't I install zeronet directly from brew then?

**Comment by tonyassassin** [comment]
Homebrew? Now I am confused, what is Homebrew? It looks like Alice is falling down the rabbit hole. I am looking for an idiot proof method of installation as I am not as knowledgeable as many techs. Thanks for the replies!!!

**Comment by Adrianzo** [comment]
Can't help idiots, sorry.
Try [READING](http://letmegooglethat.com/?q=mac+homebrew) about it ?

PS. sincerely, I can't solve your problem. I don't even have that closed-source operative system of yours. The whole point of trying to access the zeronet from there looks ridiculous to me.

**Comment by tonyassassin** [comment]
OK, point taken! Unfortunately I only use computers for music production
and writing and don't understand a lot of the deeper intricacies of the
systems, but thanks for replying, yours Tony!

**Comment by FezVrasta** [comment]
Homebrew is a package system for OS X used to install CLI dependencies.

**Comment by FezVrasta** [comment]
I found that to run it you have to drop the .app inside the termina, in this way it starts

**Comment by pedox** [comment]
it work's guys, try drag .app file and hit enter.
![screen shot 2016-07-22 at 6 43 27 pm](https://cloud.githubusercontent.com/assets/309709/17056239/495de626-503c-11e6-920c-9308361b6d7a.png)

**Comment by HelloZeroNet** [comment]
I don't have OSX access, but double clicking was worked for me when I tried it. (probably depends on settings)

I have tried to create a proper .app package (https://github.com/HelloZeroNet/ZeroBundle/tree/master/ZeroNet.app/Contents), but it required Apple Dev Account to sign it. 

If anyone would able to sign it, then i think it should always work as double clicking on it.

**Comment by robinvandernoord** [comment]
Here is a simple launcher: [ZeroNet Launcher](https://github.com/robinvandernoord/ZeroNetLauncher) for macOS

**Comment by HelloZeroNet** [comment]
@robinvandernoord Looks good, i will test it the next time when i get a mac access. Any other suggestions to make it easier to install/start on mac?

**Comment by FezVrasta** [comment]
I just use the docker image, it's the easiest way imho (if you already use Docker)

**Comment by HelloZeroNet** [comment]
Probably 90%+ mac users does not have docker installed

**Comment by tonyassassin** [comment]
Thanks, this has worked and thanks all who responded to my question!

**Comment by robinvandernoord** [comment]
@HelloZeroNet since I'm a developer I already had all the tools that ZeroNet requires installed, but I don't know if the mass of mac users has this too. Installing these dependancies can be a bit of a hassle for non-tech-savvy people maybe. But maybe it's preinstalled on all mac and there is no problem
