### ISSUE TITLE
Private data?

### ISSUE THREAD

**Issue by FezVrasta** [HelloZeroNet/ZeroNet#515]
I see in the README that you mention lack of "private websites" but what about private data?

Example, a website which needs to store some personal information, must those info be available for all? So do I need to encrypt them via JS and decrypt them manually?

**Comment by FedoraTipper** [comment]
Only way to make it private is by encrypting them, all data is shared with everyone. And everyone has access to that data. Take a look at zeromail's method.

If you dont want to encrypt, then your only other method is to use a normal website to host the data.

**Comment by border0464111** [comment]
Does this answer your question @FezVrasta  ?
