### ISSUE TITLE
Support for WebTorrent protocol?

### ISSUE THREAD

**Issue by FezVrasta** [HelloZeroNet/ZeroNet#516]
Does ZeroNet supports WebTorrent?

If not, I think it would be a great feature, it would allow to create powerful websites that can stream data directly from within the page (whithout having to host all the files on the ZeroNet website)

**Comment by obv-mikhail** [comment]
Anything in browser supports WebTorrent, so the answer is yes.

**Comment by rllola** [comment]
I have tested webtorrent in zeronet and it works. Here an example : 
https://github.com/rllola/zeroTube
