### ISSUE TITLE
PHP Support

### ISSUE THREAD

**Issue by NullFlex** [HelloZeroNet/ZeroNet#519]
Can you add PHP to ZeroNet sites?

Thanks.

(Functioning PHP.)

Or does that have to be added on my side?

**Comment by OliverCole** [comment]
ZeroNet is intended to serve static sites and Javascript, there's no server to run the PHP on.

But you can achieve almost anything using Javascript these days!

**Comment by HelloZeroNet** [comment]
Unfortunately its not possible, because the p2p websites are completely different from traditional client<>server ones
