### ISSUE TITLE
Taking a lot of time to load other website's

### ISSUE THREAD

**Issue by apoorvasingh157** [HelloZeroNet/ZeroNet#52]
Zeronet is taking a lot of time to load other website's like the one's present in the Zeroboards messages. I recommend that you should include a website load progress bar with some data in it so that user's can know how much percent the website has been loaded. It is very annoying to look at the connecting page without any estimate of how much data is left to be downloaded. Along with that the ZeroSearch (The search engine for zeronet) is not working. The page says internal server error. And one last thing is that please give some more documentation so that the developers could help you build it better.

**Comment by HelloZeroNet** [comment]
Progress bar is planned, but zerosearch is working here. Can you give urls to sites that loads slowly for you?

**Comment by apoorvasingh157** [comment]
The website named ZeroBoard and along with another website of a person named Blue coder. It's really annoying to wait for so long and still get no result. I recommend you to display the contents as soon as they arrive along with a progress bar like that of in Youtube (The red colored seek that runs at the top). Another thing is that the ZeroSearch is still not working and could you make any platform that will allow the user's to make dynamic websites without using an external server. For starter's you should provide support for a web framework in python (web.py or webapp2) along with an optional way to make the website  server dependent(for dynamic websites) or server independent(for static website's).

**Comment by HelloZeroNet** [comment]
Progress bar is a good idea, added to latest (0.2.5) version
