### ISSUE TITLE
Server error (zero net is not opening)

### ISSUE THREAD

**Issue by yamenarhim** [HelloZeroNet/ZeroNet#523]
Err: UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 219990: invalid start byte in UiServer.py line 81 > UiRequest.py line 82 > UiRequest.py line 209 > UiRequest.py line 285 > UiRequest.py line 167 > utf_8.py line 16

**Comment by yamenarhim** [comment]
i have reunpacked the zerobundle to another location and it worked fine but all the data i have downloaded is gone ,obviously ,my internet is slow so downloading the site again is annoying for me.
i use windows 7 32 btw

**Comment by HelloZeroNet** [comment]
Please try to shut down zeronet, copy the old ZeroBundle/ZeroNet/data in place of your new installation and start again. Is the problem still exists?

**Comment by MuxZeroNet** [comment]
ZeroNet is no handling non-ASCII folder names correctly. Check if your path to ZeroNet contains non-English characters. #735
