### ISSUE TITLE
最新版的0.4.0在哪下载？

### ISSUE THREAD

**Issue by wpyok500** [HelloZeroNet/ZeroNet#527]
最新版的0.4.0在哪下载？

**Comment by HelloZeroNet** [comment]
Please in english

**Comment by wfjsw** [comment]
You may wait till officially released.

Download the bundle here: https://github.com/HelloZeroNet/ZeroBundle/tree/master/dist

**Comment by weakish** [comment]
@wpyok500 Released several days ago. Please close this issue.
