### ISSUE TITLE
The latest version 0.4.0 where to download ?

### ISSUE THREAD

**Issue by wpyok500** [HelloZeroNet/ZeroNet#528]
The latest version 0.4.0 where to download ?

**Comment by HelloZeroNet** [comment]
https://github.com/HelloZeroNet/ZeroNet clone or download button

But if you download zerobundle it will download the latest version for you and it also have a built-in updater if you have earlier version.

**Comment by yurivict** [comment]
@HelloZeroNet Why didn't you make a tagged github release? Many OSes normally take only tagged releases.
