### ISSUE TITLE
 zeronet not have a mobile phone version ( Android version ) ?

### ISSUE THREAD

**Issue by wpyok500** [HelloZeroNet/ZeroNet#529]
zeronet not have a mobile phone version ( Android version ) ?

**Comment by q155128** [comment]
？very good

**Comment by HelloZeroNet** [comment]
no official yet, but you can use GNURoot (https://play.google.com/store/apps/details?id=com.gnuroot.debian) and install it using: https://github.com/HelloZeroNet/ZeroNet#manual-install-for-debian-linux

**Comment by rebroad** [comment]
@HelloZeroNet thanks,  has the manual install section gone?

**Comment by HelloZeroNet** [comment]
It's still there:


Manual install for Debian Linux
sudo apt-get update
sudo apt-get install msgpack-python python-gevent
wget https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz
tar xvpfz master.tar.gz
cd ZeroNet-master
Start with python zeronet.py
Open http://127.0.0.1:43110/ in your browser

There is also an experimental .apk: https://github.com/HelloZeroNet/ZeroNet-kivy

**Comment by l5h5t7** [comment]
So we have an Android version, close this issue?
