### ISSUE TITLE
sitePublish fails with a KeyError

### ISSUE THREAD

**Issue by johnhamelink** [HelloZeroNet/ZeroNet#533]
Hi there,

Using ZeroNet from git's master branch, when I try to publish my zeronet site, I get the following error:

```
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    main.start()
  File "src/main.py", line 418, in start
    actions.call(config.action, action_kwargs)
  File "src/main.py", line 118, in call
    func(**kwargs)
  File "src/main.py", line 301, in sitePublish
    site = SiteManager.site_manager.list()[address]
KeyError: '<zeronet site address is here>'
```

Any advice would be greatly appreciated!

**Comment by HelloZeroNet** [comment]
please try using siteSign eg.: zeronet.py siteSign 1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D --publish

**Comment by johnhamelink** [comment]
Hi :smile: 

The issue was that I hadn't published for the first time. A good fix for this would be to check to see if the user has run the zeronet.py server since creating the site.

**Comment by TheMediaGiant** [comment]
Hi johnhamelink,

I'm having the same issue. I was able to create and sign my site but when I come to run the sitePublish command then the same error occurs. Could you expand on how you fixed this?

Thank you.

**Comment by johnhamelink** [comment]
@TheMediaGiant you have to just run `python zeronet.py` - the `sitePublish` command is only for updating. The docs don't make it all that clear 😄

**Comment by TheMediaGiant** [comment]
Ah okay, we have to go to http://127.0.0.1:43110/<zeronet site address is here> at least once before we run the sitePublish command. That worked fine. Thanks for the great help!

**Comment by DaniellMesquito** [comment]
I had that problems: #544.
