### ISSUE TITLE
NameError: name 'PROTOCOL_SSLv3' is not defined

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#534]
Hi, after update to last ubuntu LTS i get this 

> NameError: name 'PROTOCOL_SSLv3' is not defined

**Comment by HelloZeroNet** [comment]
Try python -m pip install -U gevent

**Comment by iShift** [comment]
Thanks, it works for me

**Comment by jesuslemus** [comment]
Same, it worked for me using Debian stretch. Thanks!
