### ISSUE TITLE
Sidebar does not load

### ISSUE THREAD

**Issue by casept** [HelloZeroNet/ZeroNet#536]
Whenever I try to pull out the sidebar an error message appears.
The message is as follows:

`Internal error: TypeError: unsupported operand type(s) for /: 'float' and 'str'
UiWebsocket.py line 98 > UiWebsocket.py line 175 > SidebarPlugin.py line 432 > SidebarPlugin.py line 211`

This happens on several zerosites, both on an alpine linux (edge distribution) and a debian linux (testing distribution) based docker container, and happens both on amd64 and armv7 devices.

**Comment by OliverCole** [comment]
Which sites?

**Comment by casept** [comment]
ZeroHello (the site which opens automatically) for example.

**Comment by casept** [comment]
Seems to be fixed now, closing.
