### ISSUE TITLE
upnp python has some errors (NameError: global name 'SocketError' first)

### ISSUE THREAD

**Issue by arthurlutz** [HelloZeroNet/ZeroNet#54]
```
 src.File.FileServer UpnpPunch run error: NameError: global name 'SocketError' is not defined in FileServer.py line 50 > UpnpPunch.py line 176 > UpnpPunch.py line 40
```

replacing SocketError by socket.error gets us to another error : 

```
src.File.FileServer UpnpPunch run error: UnboundLocalError: local variable 'data' referenced before assignment in FileServer.py line 50 > UpnpPunch.py line 176 > UpnpPunch.py line 44
```

adding return to the except block gets us another error : 

```
src.File.FileServer UpnpPunch run error: TypeError: expected string or buffer in FileServer.py line 50 > UpnpPunch.py line 176 > UpnpPunch.py line 52 > re.py line 177
```

I gave up there...

**Comment by HelloZeroNet** [comment]
Thanks for reporting!
cc: @sirMackk

**Comment by sirMackk** [comment]
Hey @arthurlutz , thanks for reporting this. I'll get on fixing this today evening. Could you please share what OS you're using as well as Python version?

**Comment by sirMackk** [comment]
I think I have the fix for this on my fork's master. I'll get to give it a test on two routers tomorrow and hopefully report back a success.

**Comment by HelloZeroNet** [comment]
For unknown reason it stopped working for me. (nothing changed, same router same computer)

The ssdp discovery UDP packets not even visible using packet analyzer (smartsniff)

If i put `sock.bind(("192.168.1.10",999))` to _m_search_ssdp it wokring fine tried `sock.bind(("",999))`, but no luck. Any idea?

**Comment by HelloZeroNet** [comment]
Made it work by detecting local ips (+added some logging, fixed the successful run check and it also can be run by standalone using `python UpnpPunch.py`):
https://gist.github.com/HelloZeroNet/5133c7f03030620c278f

Please test :)

**Comment by sirMackk** [comment]
Whoa, thanks! I'll test it out soon as I'm home today. Got a windows box
and two routers to test it.

**Comment by sirMackk** [comment]
I checked out the code and it works on both a linux machine and a windows machine on two different routers and it forwards the port without a hitch. Nice job on update 2 - that was the trickiest part. Should we leave it on my fork for more testing or should I submit a PR?

**Comment by HelloZeroNet** [comment]
I think its clearly fixes some problems, so the PR is welcomed
