### ISSUE TITLE
Please sign releases

### ISSUE THREAD

**Issue by kseistrup** [HelloZeroNet/ZeroNet#540]
It would be highly desirable if the `.zip` and `.tar.gz` files found on  the [Releases page](https://github.com/HelloZeroNet/ZeroNet/releases) were signed using GPG/PGP so that people can verify that the blobs haven't been tampered with.

Even  [signed commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) could be useful.

As a minimum, please sha256sum the release files.

Cheers.

**Comment by Nutomic** [comment]
The signatures should also be checked by the integrated updater.

**Comment by DaniellMesquito** [comment]
+1
This will prevent the use corrupt downloads from man-in-middle attacks.

**Comment by g4jc** [comment]
This is an important issue for security and file integrity.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by HelloZeroNet** [comment]
Since last week it possible to download the source code via the ZeroNet network, which verifies the data integrity by checking the signiture, but I will look at pgp signing releases

**Comment by HelloZeroNet** [comment]
Added signing to git commits: https://github.com/HelloZeroNet/ZeroNet/commit/901478475fb15a910d3c99ccb161730b4e84ca25

**Comment by MuxZeroNet** [comment]
FIRST SIGNED COMMIT!

**Comment by border0464111** [comment]
Commits are now signed, :D 

Closing this issue ?
