### ISSUE TITLE
How to start zeronet without windows popup?

### ISSUE THREAD

**Issue by hamiltino** [HelloZeroNet/ZeroNet#541]
How can i start zeronet without the window browser from popping up everything time when i start the zeronet program?

**Comment by HelloZeroNet** [comment]
Change the start.py to zeronet.py in the end of the third line in zeronet.cmd

**Comment by hamiltino** [comment]
Hey can you please give me instructions for linux thanks

**Comment by HelloZeroNet** [comment]
it's similar: replace start.py with zeronet.py in ZeroNet.sh

https://github.com/HelloZeroNet/ZeroBundle/blob/master/ZeroNet.sh#L5
