### ISSUE TITLE
My ZeroNet shows that tor is always waiting~

### ISSUE THREAD

**Issue by q54528** [HelloZeroNet/ZeroNet#542]
I started Tor Browser with ShadowsocksR(127.0.0.1:1080) ;and add "Socks5Proxy 127.0.0.1:1080" in torrc file.
![image](https://cloud.githubusercontent.com/assets/14799855/17960226/562c23b2-6ad7-11e6-8b45-1ae320a68fc5.png)
But in ZeroNet , tor is always waiting . What should I do ?
In the log , there are words I think can help :
### TorManager Error starting Tor client: error: [Errno 10060] [Error 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 in TorManager.py line 74 > TorManager.py line 101 > helper.py line 130 > socket.py line 86

**Comment by zeronet0** [comment]
Because you are in China,The GFW has blocked tor's links.

**Comment by q54528** [comment]
so I used valida and shadowsocksR , it works

2016-09-10 19:12 GMT+08:00 zeronet0 <notifications@github.com>:

**Comment by q54528** [comment]
vidalia,sorry

2016-09-12 9:18 GMT+08:00 William Qian <q54528@gmail.com>:
