### ISSUE TITLE
SiteManager Save error: No sites found & KeyError

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#544]
When I try create a new site, this error is shown:
```
SiteManager Save error: No sites found
- Site created!
```

When I try publish my site:

 ```
sitePublish 1AxCBPaTtvuCEq3GpYg26eAY5Z4KmdeF1H
- Starting ZeroNet...
- OpenSSL loaded, version: 01000201F
- Loading site...
Traceback (most recent call last):
  File "zeronet.py", line 16, in main
    main.start()
  File "src\main.py", line 418, in start
    actions.call(config.action, action_kwargs)
  File "src\main.py", line 118, in call
    func(**kwargs)
  File "src\main.py", line 301, in sitePublish
    site = SiteManager.site_manager.list()[address]
KeyError: '1AxCBPaTtvuCEq3GpYg26eAY5Z4KmdeF1H'
```

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed in latest version

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, whats the new version after this error solved?

**Comment by HelloZeroNet** [comment]
The latest: Rev1429

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, how can I update it?

**Comment by DaniellMesquito** [comment]
I suggest release a fix patch for it.

**Comment by HelloZeroNet** [comment]
you can use the 3dot menu in zerohello > Version 0.4.0 menu item. Or simply download it from github and overwrite the files

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, thanks but I tried it and gets this:
<img src="http://image.prntscr.com/image/718a8cbf7a504c04906f69a8ead3e7a9.png"/>
I'll try manually dowload it.

**Comment by border0464111** [comment]
Hi @Plasmmer
have it been fixed since ? Can we close the issue ?

**Comment by Plasmmer** [comment]
Y.
