### ISSUE TITLE
Can create sites from HelloZeroNet pannel

### ISSUE THREAD

**Issue by DaniellPlasmmer** [HelloZeroNet/ZeroNet#546]
Its my suggestion.

**Comment by obv-mikhail** [comment]
You can sort of already do this by cloning an existing site.

**Comment by DaniellMesquito** [comment]
I'm not talking about clone an existing site, but create a new! You have no plausible arguments for contrary this issue, like you does in my others.

**Comment by obv-mikhail** [comment]
I only provided an existing solution, and never said anything against your suggestion.

**Comment by DaniellMesquito** [comment]
Clone is different from create a new site from scratch.

**Comment by alugarius** [comment]
not if you clone an empty site ^^

**Comment by DaniellMesquito** [comment]
This clonned empty site will need be created via CLI!

**Comment by MuxZeroNet** [comment]
Now you can create a new site by clicking on the `...` button on the top of ZeroHello. @DaniellPlasmmer 
In this way, private key is saved in users.json and you don't have to type it in.
