### ISSUE TITLE
Altcoin addresses

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#550]
My idea is user can use the address of a altcoin ZeroNet can support instead of only Bitcoin.

The ideas:
- [ ] User can change the Bitcoin address for a supported altcoin address;
- [ ] The visitor can see the type of criptocurrency is used in address and can donate;

The initial altcoins:
- [ ] Dash
- [ ] Ethereum
- [ ] Monero

**Comment by obv-mikhail** [comment]
If you are talking about site addresses, I think this would add unneeded complexity with no real benefits.

**Comment by DaniellMesquito** [comment]
@obv-mikhail
> If you are talking about site addresses, I think this would add unneeded complexity and bring no real benefits.

Thanks for your edited comment. This isn't bring complexity, but diversity and more options. Site owners will gain more options for donations and reach users of different altcoins. For example, can create an faucet about Dash, and users can donate directly for the site address using his wallet. I have other issues here that you can consider, or you only comment with contrary?!

**Comment by obv-mikhail** [comment]
Having more options does not equate to any real benefits, considering that bitcoin is more popular than all other cryptocurrencies combined.

**Comment by HelloZeroNet** [comment]
Other addresses are not planned.
