### ISSUE TITLE
GIT webhooks/API new update system

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#552]
- [ ] Access the remote git reppo tracking new updates
- [ ] Assuming a update is ready, sync for download only the changed bytes using GIT system

**Comment by HelloZeroNet** [comment]
You can use git if you want, but i dont see why is it necessary

**Comment by DaniellMesquito** [comment]
> You can use git if you want, but i dont see why is it necessary

Assuming you have a high speed Internet connection, download unecessary bytes is necessary.

**Comment by HelloZeroNet** [comment]
Probably ZeroNet will not work on connections where downloading 2.5MB is a problem.

**Comment by DaniellMesquito** [comment]
@HelloZeroNet
> Probably ZeroNet will not work on connections where downloading 2.5MB is a problem.

It a preconception commet, like the machism. My brazillian Internet connection have 10MB diary limit, after it my connection works at 3KB per second. And ZeroNet works very well in this extremely-poor connection! I don't think what you say is a point to disconsider saving the data plans of your users. I don't see the point of download unecessary bytes if it can download only what user needs. This uses BitTorrent-like, Tor, Bitcoin, Namecoin and a bunch of things, why not use GIT too?

**Comment by HelloZeroNet** [comment]
Most of systems does not have git installed, so it would require to pack/maintain git for every system which is for example 31MB for windows. (https://git-scm.com/download/win)

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, users can simply install Git for work with it. ZeroNet updater with two options: download from master ZIP or using GIT system. User can download the 31MB in a lan-house or another connection, but will save his data plans. Believe on poor mans with 1KBps connections, these uses ZeroNet and it works.

**Comment by HelloZeroNet** [comment]
It's already possible: if you have git installed, then you can update it from github.

**Comment by DaniellMesquito** [comment]
Automate it for final user giving the two options is better. but thanks for the suggestion, I'll use.
