### ISSUE TITLE
Connection lost when try update

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#553]
When I try update my software, I gets this error:
<img src="http://image.prntscr.com/image/718a8cbf7a504c04906f69a8ead3e7a9.png"/>
My connection actually is in the diary 10MB and my speed is 1MBps, then the problem isn't in my side, I think.

**Comment by HelloZeroNet** [comment]
This is normal: zeronet shuts down , download the latest version, then starts up (could take couple of minutes depending on your net/cpu/hdd speed)

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, you can introduce a updater UI/CLI for user see the update progress.
