### ISSUE TITLE
Interface updater

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#554]
A GUI/CLI that starts when updating and user can see the progress of update.

**Comment by HelloZeroNet** [comment]
ZeroNet has to shut down for updating, so unfortunetly since it's not running it's not possible to give any feedback to the user.

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, its quite simple. Before call the program to close, call the updater program to open a new browser tab with a localhost page with the update progress.

**Comment by HelloZeroNet** [comment]
Creating / closing new ports/sevices could have some delay and the update process should not take more than some seconds, so i dont think it's worth developing a separate webserver / popping up a window for that. The zeronet startup speed could be slow on hdd based systems, but it will be improved in the future.
