### ISSUE TITLE
Failing download content.json

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#555]
I've properly created and signed my site, succesfully. Too, I've published. Says in CLI that is published for 0 peers, in UI pannel says that are 3 peers. The content.json says downloading, but it fails.
<img src="http://image.prntscr.com/image/0b087442d2e140db88b824d38275453a.png"/>

**Comment by HelloZeroNet** [comment]
probably the peers are not connectable or offline, so you can't publish it to anyone

**Comment by DaniellMesquito** [comment]
@HelloZeroNet why my content.json fails downloading? Can U [access to see](http://127.0.0.1:43110/1AxCBPaTtvuCEq3GpYg26eAY5Z4KmdeF1H/) it works?
I suggest fix this error showings in a next update.

**Comment by DaniellMesquito** [comment]
Why this shows 3 peers if have only me? This is the conflict.

**Comment by DaniellMesquito** [comment]
You closed this issue with a "probably" doubt "response" while the problem is: inconsistente/conflicting/contraditory showing peers, and inconsistent error messages. I'm still waiting for a response.

**Comment by HelloZeroNet** [comment]
The peer number is shows the possible peers (who have visited the page recently). They can be offline/not connectable or maybe they already removed the page. You can see the connected peer number in the sidebar and the publishing result is in file log/debug.log

**Comment by DaniellMesquito** [comment]
@HelloZeroNet, previously I would sync the content.json succesfully, but actually its with this error. My connection is ok with 1 megabyte per second.
