### ISSUE TITLE
Connection with UiServer Websocket was lost. with docker image nofish/zeronet

### ISSUE THREAD

**Issue by hweidz** [HelloZeroNet/ZeroNet#557]
[16:39:44] Ui.UiServer --------------------------------------
[16:39:44] Ui.UiServer Web interface: http://0.0.0.0:43110/
[16:39:44] Ui.UiServer --------------------------------------
<socket fileno=7 sock=172.17.0.2:43110 peer=myip:52944>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb0\xcax\x17\xd3\'[e<\x9b*\xb2\xedq\xe0\xf6\xf8\xacC\x95\xe7x\xb2)w\xc8!\xcf\x91\x9fc\xe6 Tm\xc2\xb2&\xae\x90j\x0c\x8a\xef\x81\xe1\xc2\xbf=\x1c\x99\xe6^j\xf9l%\xbd\xbe\x81\'\xa2\x0b\xf5[\x00"\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xcc\x14\xcc\x13\xc0\t\xc0\x13\xc0\n'
<socket fileno=7 sock=172.17.0.2:43110 peer=myip:52945>: Expected GET method: '\x16\x03\x01\x00\x80\x01\x00\x00|\x03\x02\x8b\x89\\\x13>\x9704\xf6nW\xd5\x13\xb8\'"\xec\xb7\xe4X\xde=\xed7\xbcm\xcb\xee\xbdr\xf3"\x00\x00\x10\xc0\t\xc0\x13\xc0\n'
[16:39:45] FileServer Checking port 15441 using portchecker.co...
[16:39:46] FileServer [OK :)] Port open: Port 15441 is open.

**Comment by HelloZeroNet** [comment]
probably you try to access it using https or similar

**Comment by hweidz** [comment]
yes... I using https..now I switch to http, the error log is gone, but still "Connection with UiServer Websocket was lost. "

**Comment by hweidz** [comment]
I found if I mount my own data "-v /data/zeronet/data:/root/data" and use my old user.json will cause this problem, why?

**Comment by hweidz** [comment]
I just backup file users.json, should I backup anything else?

**Comment by hweidz** [comment]
I got it, I should pasue the hash from users.json manually.
