### ISSUE TITLE
How access .bit domains of ZeroNet without localhost?

### ISSUE THREAD

**Issue by DaniellMesquito** [HelloZeroNet/ZeroNet#559]
I saw in the prints ZeroNet sites with only .bit domains, without any localhost address/port. How this occurs? A propen plugin? A propen browser?

**Comment by HelloZeroNet** [comment]
Yes: https://chrome.google.com/webstore/detail/zeronet-protocol/cpkpdcdljfbnepgfejplkhdnopniieop

**Comment by DaniellMesquito** [comment]
Its not clearly in the documentation. I'll think what I can do. Thanks.
