### ISSUE TITLE
Update documents

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#56]
http://zeronet.readthedocs.org/
- [x] Make ZeroFrame API reference uptodate
- [x] Add Disqus to allow comments/questions
- [x] Put the [example site](http://zeronet.readthedocs.org/en/latest/site_development/using_zeroframe_api/) to github
- [x] FAQ
- [x] Description of content.json format
- [ ] Create ZeroNet site for the documents
- [x] Network protocol
- [x] New donation page
- [ ] Done / Future features
- [x] More screenshots
- [ ] Dbschema version 2
- [ ] Handshake
- [ ] Trusted authorization providers
- [x] New command: actionSiteSign
- [x] New command: actionSiteClone
- [x] New command: actionFileRules
- [x] New command: actionCertAdd
- [x] New command: actionCertSelect
- [x] New command: actionCertSet (admin)

**Comment by HelloZeroNet** [comment]
add goal specific donation addresses: `$.get("https://mainnet.helloblock.io/v1/addresses?addresses=1QDhxQ6PraUZa21ET5fYUCPgdrwBomnFgX", function(res) { console.log(res) })`

**Comment by HelloZeroNet** [comment]
Faq:
 - How to use it with Tor?
 - Is it possible to install it on remote machine?
 - Do I need open port to create new site?

**Comment by makdisse** [comment]
- How to fix the '1 file upload failed' issue?

**Comment by Idealcoder** [comment]
Can I suggest to create a document page explaining how to create a namecoin .bit address?

**Comment by shakna-israel** [comment]
The [single IP setup](https://github.com/HelloZeroNet/ZeroNet/issues/103) is something that'd probably be worth having in there.

**Comment by HelloZeroNet** [comment]
FAQ WIP: http://zeronet.readthedocs.org/en/latest/faq/

**Comment by TheNain38** [comment]
It should also be said for site developpers the differences between creating a ZeroNet site to a non ZeroNet site. For exemple: links should contain attribute `target="_top"` or `target="_blank"` to works as expected

**Comment by MuxZeroNet** [comment]
> Handshake

Needs more documentation on Handshake and GetHashfield. #987

**Comment by purplesyringa** [comment]
@HelloZeroNet Wondering if this can be closed.
