### ISSUE TITLE
Option to sort 0list by upvotes

### ISSUE THREAD

**Issue by forteller** [HelloZeroNet/ZeroNet#563]
Would be very handy. The list is getting long and it's hard to find good pages.

**Comment by obv-mikhail** [comment]
This probably belongs in the zerotalk repository https://github.com/HelloZeroNet/ZeroTalk .

**Comment by border0464111** [comment]
Unfortunately this issue don't belong here,  0list is an independant project, You should seek for the admins of it. 

Closing ?

**Comment by mkg20001** [comment]
> This probably belongs in the zerotalk repository https://github.com/HelloZeroNet/ZeroTalk .

I think that it rather belongs to the 0List repository (if there is one).

**Comment by imachug** [comment]
@HelloZeroNet 0list is now outdated, can we close this?
