### ISSUE TITLE
Content addressed shared site storage?

### ISSUE THREAD

**Issue by obv-mikhail** [HelloZeroNet/ZeroNet#564]
Right now all sites store their files in separate folders, some of them contain identical files.

With an IPFS-like storage system there would be no data duplication.

Would zeronet benefit from this?

**Comment by HelloZeroNet** [comment]
I think the benefit would be minimal: js/css files recommended to be merged (so the hash does not match), data files are dynamic

**Comment by wigy-opensource-developer** [comment]
Initial page-load might be somewhat longer for a zite, but there is always a time-space trade-off. And since zites are single-page-applications, the initial page-load might not be the most relevant performance metric. Anyways, I see and accept your argument.

**Comment by matthiasbeyer** [comment]
I would love a backend using IPFS. This would also easily enable always-online caching nodes (think of a server running an IPFS node and pinning content for you).

**Comment by purplesyringa** [comment]
@HelloZeroNet I guess this can now be closed in favor of #2192.
