### ISSUE TITLE
RSA operations are not performed in constant time

### ISSUE THREAD

**Issue by rot256** [HelloZeroNet/ZeroNet#566]
The RSA implementation in ZeroNet/src/lib/rsa is not constant time since it uses pythons "pow" function.

[The offending library](https://github.com/sybrenstuvel/python-rsa)

In general this RSA implementation appears a little naive, for instance the encrypt_bigfile simply chunks a larger input into chunks fitting under N.

I suggests using the implementation in openssl (or pycrypto) instead.

**Comment by HelloZeroNet** [comment]
RSA is only used to generate proof-of-tor-address (to avoid some attacks) and not used for encryption at all,so i think it should be fine.

**Comment by border0464111** [comment]
Closing ?

**Comment by imachug** [comment]
@HelloZeroNet Can we close this?
