### ISSUE TITLE
Please keep github release version in sync with the latest version ZN says is available

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#573]
GH shows that 0.4.0 was released a day ago, but when I run 0.4.0 it says "NEW ZERONET VERSION: 0.4.1".

This is confusing to have different versions shown in different places. Please keep them in sync.

**Comment by HelloZeroNet** [comment]
I usually tag new version in github later, because there could (and usually there are) be bugs in new version: so if you want something safe then use the releases tab, if you want to be on edge, then download the latest commit.

**Comment by yurivict** [comment]
You should consider labeling them separately as "rc"="release candidate". ZN client should also show such versions differently.

I maintain ZN FreeBSD port, and I need a stable release. But the way how it is now users always see the green "NEW VERSION AVAILABLE" label, when this is only essentially a release candidate.

**Comment by HelloZeroNet** [comment]
Ok, good idea, I have tagged the latest revision with 0.4.1-rc: https://github.com/HelloZeroNet/ZeroNet/releases
