### ISSUE TITLE
content.json download failed

### ISSUE THREAD

**Issue by HurtLocker936** [HelloZeroNet/ZeroNet#574]
![screenshot 34](https://cloud.githubusercontent.com/assets/10778557/18287707/0935bc4e-742d-11e6-9d69-33d5342387fa.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/10778557/18287656/e1c22cd8-742c-11e6-916f-601ed41f7360.png)

**Comment by HelloZeroNet** [comment]
Please try to check log/debug.log for errors.

**Comment by grez911** [comment]
Non-reproducible issue.
@HelloZeroNet Please, close.
