### ISSUE TITLE
Request for Subtitle Notification

### ISSUE THREAD

**Issue by Vandam** [HelloZeroNet/ZeroNet#576]
When you open a Video, i can download it in SD HD Etc, but I would like to know if it has "Hard Coded Subs" "Subs come with it (Like a txt file)" Or No Subs" So i can instead of downloading the movie and it comes with Hard Coded Subs.

**Comment by obv-mikhail** [comment]
Wrong repo maybe?

**Comment by Vandam** [comment]
Used latest Repo fresh copy. i see the CC Search, but the torrents dont state "Hard Coded" or not

**Comment by obv-mikhail** [comment]
I am not aware of there being any video torrents on ZeroNet.

**Comment by HelloZeroNet** [comment]
Sorry, we can't help, since this issue is not related to zeronet itself, but to a site that's on the network.
