### ISSUE TITLE
UI not adapted for mobile

### ISSUE THREAD

**Issue by espectalll** [HelloZeroNet/ZeroNet#580]
ZeroHello, as well as pages such as ZeroBlog, lack of CSS rules to adapt the interface for small screens and touch devices, hence the network cannot be correctly used from devices such as smartphones. 

This could be considered as a currently irrelevant error, since there is no ZeroNet port for iOS or Android - however, web proxies already allow to load ZeroNet from such devices.

**Comment by imachug** [comment]
@HelloZeroNet Looks like you've solved it already?
