### ISSUE TITLE
Provide another way to detect physical location and IP address

### ISSUE THREAD

**Issue by t123yh** [HelloZeroNet/ZeroNet#581]
I'm here in China. You know the so-called "Internet" in China: Almost everything is blocked.

So I use my router to do proxy. When I'm surfing the Internet, All traffic to IP address in China will be passed through directly, whereas traffic to outside China is passed through my proxy in Los Angeles. I'd like ZeroNet to see me as my real Chinese IP address, but it detects my server IP in Los Angeles, thus I cannot open my port to let others use, and I'm not able to use my local peers.

Will it be possible to provide an alternative way to detect IP address (e.g. use IP detector page in China like http://www.pubyun.com/dyndns/getip) or some other measurements?

**Comment by iShift** [comment]
add rule to proxy with ignoring URL of zeronet ip checker

**Comment by t123yh** [comment]
@iShift Rules are based on IP addresses, not URL.

**Comment by HelloZeroNet** [comment]
you can use --ip_external any.ip.you.want, but the trackers will add the originating ip

**Comment by t123yh** [comment]
@HelloZeroNet Not very clear what 'but the trackers will add the originating ip' means, could you please explain it a little bit more detailed?

**Comment by HelloZeroNet** [comment]
trackers works like this: you send a request to a computer, this computer stores the request's originating ip address as potentional source of the website

**Comment by t123yh** [comment]
Then if I specify the ip_external parameter, will that be like this: I will be able to access ZeroNet using both China and World sources, but only users in China will be able to connect to me because the World see me as my Los Angeles IP?

**Comment by t123yh** [comment]
It seems that those checkers cannot see my actual IP address even I provided my real IP.
```
[14:06:38] FileServer Checking port 15441 using portchecker.co...
[14:06:39] FileServer [BAD :(] Port closed: Port 15441 is closed.
[14:06:39] FileServer Trying to open port using UpnpPunch...
[14:06:54] FileServer Checking port 15441 using portchecker.co...
[14:06:55] FileServer [BAD :(] Port closed: Port 15441 is closed.
[14:06:55] FileServer Checking port 15441 using canyouseeme.org...
[14:06:56] FileServer [BAD :(] Port closed: Error: I could not see your service on 107.151.188.*** on port (15441) Reason: Connection refused
[14:06:56] FileServer Upnp mapping failed :( Please forward port 15441 on your router to your ipaddress
```

where `107.151.188.***` is my proxy server IP.

**Comment by HelloZeroNet** [comment]
It's probably because your proxy does have opened port that is directed back to your computer.

**Comment by t123yh** [comment]
I don't want to expose my proxy server IP. I just want to make myself expose to the Internet with my actual IP specified with the ip_external  parameter.

**Comment by HelloZeroNet** [comment]
It's not possible, the trackers will always store your proxy ip

**Comment by t123yh** [comment]
But now my page shows that my 15441 is opened. Does that mean it's OK now?

**Comment by HelloZeroNet** [comment]
If you specify --ip_external, then it will skip the port open check, but the end result will be the same: nobody will able to connect to you, only you able to connect other computers

**Comment by t123yh** [comment]
No, I mapped my router_actual_public_ip:15440 to my_computer:15440. --ip_external is router_actual_public_ip.
