### ISSUE TITLE
Internal error: TypeError: string indices must be integers, not tuple

### ISSUE THREAD

**Issue by mcl1234** [HelloZeroNet/ZeroNet#582]
When I trying to publish my update of my blog via the HTML interface :  
UiWebsocket.py line 99 > UiWebsocket.py line 178 > MergerSitePlugin.py line 127 > MergerSitePlugin.py line 121 > UiWebsocket.py line 402

**Comment by HelloZeroNet** [comment]
If you upgrade to latest version it will gone
