### ISSUE TITLE
Can't login and import users.json!

### ISSUE THREAD

**Issue by phr34k0** [HelloZeroNet/ZeroNet#583]
So i have deleted my old data folder but backed up and replace the new users.json with old one. How do you even login or use your cert_sign and auth_privatekey? All i'm receiving is just "User Taken"

Also i have Multiuser Plugin on for my group of friends

![0c8f2baa-7bad-11e6-96d9-c314171f2df8](https://cloud.githubusercontent.com/assets/13272249/18560251/58dc7d96-7bad-11e6-91c7-13eea5cdaa4c.png)

![screenshot from 2016-09-16 01-32-45](https://cloud.githubusercontent.com/assets/13272249/18560622/feebf828-7bae-11e6-8b4c-56eeab80d1c8.png)

**Comment by HelloZeroNet** [comment]
you need to use the master_seed value to login
