### ISSUE TITLE
Optional files improvements

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#584]
It will allow more advanced optional files handling and 
## Help distribute specific directories
- New API command: optionalDownloadList
- New API command: optionalDownloadSet [patterns]
## Global size limit optional files

Specific size or % of HDD free space
- Keep track downloaded optional files size
- Cleanup by peer number and last access time
## WebUI to manage optional files
- Display total optional files / limit
- Modify limit
- Display downloaded optional files
- Order by Size/Peers/Uploaded/Added/Used
- Manage signed up directories
- Group by site
## Add image upload to ZeroMe
- Image upload with resize
- Checkbox to help distribute user's files
## Plan
- [x] Create optional file manager mockup
- [x] Fill optional files to a database
- [x] Update optional file database on loadContent / removeContent
- [x] Update optional file database on download complete
- [x] Update access_time
- [x] Update downloaded number stats
- [x] ZeroFrame API command to query current peer number for files
- [x] Always allow fileDelete on optional files
- [x] Update optional file database on fileDelete
- [x] Update peer number in database for optional files
- [x] Delete optional files based on peer number
- [x] Auto download optional files based on optionalDownloadList
- [x] Make OptionalFileDelete merger site compatible
- [x] Save/Restore peers to/from database
- [x] Auto pinning my files
- [x] Try guess and pin my files on first startup after upgrade
- [x] Set optional files limit based on current size of files on first startup after upgrade
- [x] FF/IE Edge test

Manager UI
- [x] Static html version
- [x] Site listing
- [x] File listing
- [x] Select files
- [x] Limit bar
- [x] Limit modification
- [x] Files paging
- [x] Manage/remove followings
- [x] Table sorting
- [x] Display pinned files
- [x] Pinning
- [x] Deleting
- [x] Faster total limit usage calculation
- [x] Empty state
- [x] Message for older versions

ZeroMe
- [x] Image upload UI
- [x] Generate preview
- [x] Resize image
- [x] Save image to data.json
- [x] Lazy display image preview
- [x] Load big file on click
- [x] Show peers for files
- [x] Help distribute images checkbox for the user
- [x] Image uploading
- [x] Downloaded image delete
- [x] Delete image when post deleted
- [x] Message for older versions

**Comment by obv-mikhail** [comment]
Is this connected to torrent plugin at all?

**Comment by HelloZeroNet** [comment]
No, this is for ZeroNet files. Originally I was tried to add torrent support, but after some experiments I dropped it for now, because it would be hard to make it work with Tor and I want to avoid confusions, so maybe after i2p support.

**Comment by HelloZeroNet** [comment]
Added to 0.5.0
