### ISSUE TITLE
Internal error: KeyError: u'data/users/content.json'

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#586]
http://127.0.0.1:43110/17GijTrkMfxhTKWFnM2atrGVaZcp5zNBEW

dragging of the zero icon to reveal the sidebar generates the following error:

Internal error: KeyError: u'data/users/content.json'
UiWebsocket.py line 99 > UiWebsocket.py line 176 > SidebarPlugin.py line 448 > SidebarPlugin.py line 130 > ContentManager.py line 273 > ContentManager.py line 271 > ContentDbDict.py line 54

console:
Site:17GijT..NBEW WebSocket handleRequest error: KeyError: u'data/users/content.json' in UiWebsocket.py line 99 > UiWebsocket.py line 176 > SidebarPlugin.py line 448 > SidebarPlugin.py line 130 > ContentManager.py line 265 > ContentManager.py line 263 > ContentDbDict.py line 54

debug-last.log:
ERROR    - UiWSGIHandler error: error: [Errno 32] Broken pipe in UiServer.py line 39 > pywsgi.py line 495 > pywsgi.py line 486 > pywsgi.py line 376 > pywsgi.py line 369 > pywsgi.py line 355 > socket.py line 458 > socket.py line 443

![ded6071e-7df6-11e6-8f3e-1516659d6f36](https://cloud.githubusercontent.com/assets/5212537/18619276/718d58ea-7df8-11e6-958c-19aa7290896b.png)

**Comment by HelloZeroNet** [comment]
the file data/users/content.json is referenced in root content.json, but it's not signed/found.

**Comment by ysc3839** [comment]
Should check if it exist before using it.

**Comment by dnelband** [comment]
yes that worked

**Comment by CPCer** [comment]
@ysc3839 @HelloZeroNet when i'm deleting sites this appeared again
`Internal error: KeyError: u'data/users/1EZTWytasXcKdiUFnN4KHqAfvg1nwkTkKv/content.json'
UiWebsocket.py line 105 > UiWebsocket.py line 200 > UiWebsocket.py line 726 > Site.py line 1006 > SiteStorage.py line 392 > ContentDbDict.py line 55 > ContentDbDict.py line 28`
and i cannnot find folders related with "1EZTWytas....." or sites in sites.json....

**Comment by intelligentguy** [comment]
Same problem as CPCer. After sending a message in folder data/users/{user_adress}/ zero receives data.json and no content.json Why does this happen?
