### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#591]
http://127.0.0.1:43110/157xGMqaufjjnts9qRd4K953g8dBm6YzXr/
sometimes when this site loads im getting this error from all.js:
uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state

why does this happen & how could this be prevented?

**Comment by HelloZeroNet** [comment]
You have to execute commands after the "onOpenWebsocket" called in ZeroFrame (see the chat tutorial on ZeroBlog for example)
