### ISSUE TITLE
Install fails silently on Windows if Python already exists in Environment Path

### ISSUE THREAD

**Issue by jaredlt** [HelloZeroNet/ZeroNet#594]
Hi,

I was trying to install ZeroNet on Windows (10) by following the default instructions (running ZeroNet.cmd).

It was opening the command prompt and then instantly closing it with no feedback. 

I opened cmd and ran ZeroNet.cmd from inside it and got an error pointing to C:\python... (apparently I already had Python installed and I _think_ it was trying to use this version which lead to the error).

I removed the PATH entry for Python from my Environment Variables, ran ZeroNet.cmd again and it worked fine.

**Comment by HelloZeroNet** [comment]
I have just tested it on same enviroment and works for me, zeronet.cmd contains relative path to included python.exe, so it should not affect it. If possible please provide full error message.

**Comment by jaredlt** [comment]
When I ran zeronet.cmd from within a cmd prompt it provided the following error (I didn't screenshot it at the time, but I did copy and paste it into Google, so this is from my search history):

```
File "C:\python\lib\site.py", line 176 file=sys.stderr) 
                                   ^ SyntaxError: invalid syntax
```

For reference, I had Python 3.4.1 installed at C:\python

I *think* it was actually PYTHONPATH that I deleted

C:\python and C:\python\scripts are still in my PATH

Struggling to reproduce it now as uninstalling and reinstalling Python 3 doesn't have any impact.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?
