### ISSUE TITLE
minor fix for readme.md

### ISSUE THREAD

**Issue by tidux** [HelloZeroNet/ZeroNet#596]
The instructions for a manual install on Debian should note that you need to install Tor from backports if you're running on Jessie, as the stock version is too old.  The complete command for that is `apt-get install -t jessie-backports tor` assuming you've got the backports repo in sources.list.

**Comment by HelloZeroNet** [comment]
The document using tor project's debian repo, so you will always get the latest version: http://zeronet.readthedocs.io/en/latest/faq/#how-to-make-zeronet-work-with-tor-under-linux

**Comment by grez911** [comment]
@HelloZeroNet Please, close.
