### ISSUE TITLE
No coffeescript compiler defined, skipping compiling

### ISSUE THREAD

**Issue by makdisse** [HelloZeroNet/ZeroNet#597]
I keep having this problem: 
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Debug/DebugMedia.py#L84

I'm running ZeroNet  0.4.1 rev1529 on ubuntu with the flags --debug and --ui_ip.
Doesn't help to restart zeronet.

What can cause this problem and how to fix it?

**Comment by ysc3839** [comment]
Run `coffeescript` in shell and see if it works.

**Comment by makdisse** [comment]
You're right. I had to install `coffee` to make it work. I probably got it wrong because the windows bundle comes with the compiler but on linux I have just the repo clone.
thanks!
