### ISSUE TITLE
MacOS Sierre 10.12 - ZeroNet.app won't open - command-line online

### ISSUE THREAD

**Issue by jackquack** [HelloZeroNet/ZeroNet#599]
Nothing happens. I get the dialogue asking if I will allow something downloaded from the internet to run, I click 'open' and then nothing ever happens. I was finally able to run it from the command-line

**Comment by HelloZeroNet** [comment]
Can you please check what happens if you shut down zeronet (using zerohello 3dot menu), rename ZeroNet.app to ZeroNet.command and start executing it?

**Comment by jackquack** [comment]
Yeah, that actually works. It opens a terminal window which does then cause the ZeroNet page to be loaded in the default browser.
