### ISSUE TITLE
Full Tor support

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#60]
- It would be nice to have a per-site `Allow clearnet connections` setting: If disabled then standard ipv4 peers is connected using Tor exit-nodes. If its enabled then only Tor peers are connected through the Tor proxy.
- Display warning to user: You are in Tor-only mode, you should also configure your browser to use Tor network. (maybe restrict external resources using Content Security Policy)

Problem:
 - The torrent trackers does not allow to store tor/i2p addresses.

Possible solutions:
 - DHT: Its not easy to write a good DHT implementation and Tor doesnt support UDP, so we need custom DHT (it requires reliable servers for bootstrapping and not sure if its going to work fine with current small number of nodes) or proxies that converts DHT traffic to tcp.
 - IRC: Not really decentralized solution, so i would not be happy to use it. (some altcoins using it, eg. Namecoin so it could work)
 - Bittorrent http trackers could still work, but without tor address support, so you could browse zeronet sites, but could not host zeronet sites on tor. Maybe its possible with peer-exchange combination.

Any help/idea/suggestion greatly welcomed. Thanks! :)

**Comment by aaannndddyyy** [comment]
There are working DHT implementations for I2P (cf. Vuze's i2phelper plugin or i2p's i2psnark, i2p-bote also uses a dht)

**Comment by alxbob** [comment]
https://github.com/Ayms/node-Tor

**Comment by alxbob** [comment]
https://github.com/blockstack/blockstore

**Comment by alxbob** [comment]
Full tor support and hidden services can work inside zeronet by creating a dht (that would be a tor hidden service it self) that holds the .onion addresses and load balances them. In clearnet it could work as a common dht. So its users connecting to zeronet through tor will have a hidden service created for its site he/she visits. And let tor hdirs take care the rest!

https://pypi.python.org/pypi/OnionBalance

https://stem.torproject.org/tutorials/over_the_river.html

**Comment by str4d** [comment]
See #45 for some comments regarding I2P's torrent support, which may be helpful.

**Comment by HelloZeroNet** [comment]
Done in 0.3.5
