### ISSUE TITLE
ZeroMail not working correctly. 

### ISSUE THREAD

**Issue by Snarkly** [HelloZeroNet/ZeroNet#600]
I just updated to Rev1533 and my mail quit working. I hit encrypt and send but is doesn't do anything. Also I noticed if I update my mail from the ZeroNet home page, at first I do get the green bar next to it that says updated but right after that bar disappears another bar pops up and that one says 1 file update failed. It's done this about five times now.

**Comment by HelloZeroNet** [comment]
Can you please paste your js console content? (F12)

**Comment by Snarkly** [comment]
I hit F12 and it brings up Developer Tools but I don't know what I'm looking for, I've never used that because I'm not a developer or coder.
![zeromail](https://cloud.githubusercontent.com/assets/8492776/19044583/f1c41380-8962-11e6-8991-8c42f853e40a.png) Can you please tell me where to look for the JS content.

**Comment by Snarkly** [comment]
Is this what you want?
[Wrapper] Created!all.js:1357:14
[ZeroMail] Route Object { url: "" }all.js:1578:7
MessageShow renderall.js:3697:7
[ZeroWebsocket] Openall.js:106:14
[Wrapper] Setting title to ZeroMail - ZeroNetall.js:1357:14
[User] Loading user file data/users/1ED3Ho3kmzaKiECtyuqSjDpoE47rKuXeP/data.jsonall.js:1578:7
MessageShow renderall.js:3697:7
[Leftbar] Reloading contactsall.js:1578:7
[MessageListInbox] Loading keys 2all.js:1578:7
[User] Loaded trueall.js:1578:7
MessageShow renderall.js:3697:7
[Leftbar] Unknown contacts found, reloaded.all.js:1578:7
[MessageListInbox] Loaded known AES keysall.js:1578:7
[MessageListInbox] Last parsed secret: Mon Oct 03 2016 11:57:43 GMT-0400 (EDT)all.js:1578:7
MessageShow renderall.js:3697:7
[MessageListInbox] New secrets foundall.js:1578:7
[MessageListInbox] New messages found 0all.js:1578:7
[MessageListInbox] getMessages Loaded messages in mode normal 2 (Done in 163ms)all.js:1578:7
MessageShow renderall.js:3697:7
Render: 7all.js:1025:11
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7
hideProgressall.js:547:7
MessageShow renderall.js:3697:7

**Comment by Snarkly** [comment]
Also here's a screenshot 
![zeromail1a](https://cloud.githubusercontent.com/assets/8492776/19045525/4ecedc78-8967-11e6-9444-9aaa7117f7a1.png)

**Comment by Snarkly** [comment]
I assume I posted the right stuff since you haven't replied back. I hope you can figure out what's wrong with the email.

**Comment by HelloZeroNet** [comment]
Yes, thanks for reporting i'm going to fix it soon

**Comment by Snarkly** [comment]
Thanks.

**Comment by HelloZeroNet** [comment]
I was unable to reproduce the problem, but made some modifications and added new log messages. Please try now, if it's still not work pelase post the js console lines that appears when you press the button.

**Comment by nikhiljha** [comment]
`at first I do get the green bar next to it that says updated but right after that bar disappears another bar pops up and that one says 1 file update failed`

Having same issue, latest version from the commit < 1 minute ago.

**Comment by HelloZeroNet** [comment]
You can ignore that error, probably just one of the users file is not distributed corrently. (you can check the missing file on sidebar when the site is opened)

**Comment by nikhiljha** [comment]
Ah ok. Good to know.

**Comment by Snarkly** [comment]
I just sent nofish a test email to see if it was working now.

**Comment by HelloZeroNet** [comment]
Got it & replied!

**Comment by Snarkly** [comment]
OK thanks.
