### ISSUE TITLE
ZeroNet Failed To Run On Raspberry Pi

### ISSUE THREAD

**Issue by thebitbrine** [HelloZeroNet/ZeroNet#604]
I'm trying to run ZeroNet on raspberry pi for seeding purposes but it fails to run, this is what happens when i try to run it:
![untitled-2](https://cloud.githubusercontent.com/assets/10282676/19183114/d75ca64c-8c87-11e6-8a5c-dca87412ae4e.jpg)

**Comment by HelloZeroNet** [comment]
Try delete data/content.db and try again
