### ISSUE TITLE
add the Multi-Zeroid function PLZ!!!

### ISSUE THREAD

**Issue by fujita-nozomi** [HelloZeroNet/ZeroNet#613]
Because I want to separate the political speech ID and personal use ID

**Comment by HelloZeroNet** [comment]
there is a multiuser plugin, but it's better if you run two different installation (with tor enabled if you care about your privacy)

**Comment by fujita-nozomi** [comment]
You mean "disabled-Multiuser" i try to rename but will be Crash(ERROR)

**Comment by HelloZeroNet** [comment]
It works for me, but its created for proxies, it's very easy to connect your accounts if you posting on both using the same connections.

**Comment by fujita-nozomi** [comment]
theres another question when i use the new user its tell me i using proxymode can't clone any "apps" like ZeroBlog

**Comment by HelloZeroNet** [comment]
you can use `--multiuser_local` to disable that restriction

**Comment by aemxdp** [comment]
@HelloZeroNet 
> it's very easy to connect your accounts if you posting on both using the same connections.
Could you explain a little bit more details how your accounts could be matched?
Do you mean your peers may listen to traffic and notice posting from same peer with different id?
Can they really be sure that this is you posting and you not just send update from someone else?

**Comment by HelloZeroNet** [comment]
Someone can connect to many peers, then log first source of the update by that finding the poster's ip/onion address. If you using the same client to post to multiple account, then you will use the same ip/onion address/connection to send the update, so it's possible to find out, that the two account owned by the same person.

**Comment by aemxdp** [comment]
@HelloZeroNet 

Thanks! As I understand, the number of peers one may connect is not infinite and with growth of ZN the likelihood that first source of update in your neighbourhood is the first source of update globally will decline, is this correct (1)? Also, if we have triangle like A-B, B-C, A-C, is this impossible that A starts to publish its updates to all peers but in some cases B will receive it first and publish it to C quicker than A (2)?

**Comment by HelloZeroNet** [comment]
Yeah, more peer means more privacy.
If B is close to C and A is far, then it can be possible to receive the update faster that way, than directly from A.

**Comment by grez911** [comment]
@HelloZeroNet Can the issue be closed?

**Comment by purplesyringa** [comment]
@HelloZeroNet Can the issue be closed?

**Comment by HelloZeroNet** [comment]
User selection from a list in multiuser local mode is also added:

https://github.com/HelloZeroNet/ZeroNet/commit/15fca6bd12a1304a7053270b758cfed94dd78296
