### ISSUE TITLE
Serve Site-Specific Favicon

### ISSUE THREAD

**Issue by mishfit** [HelloZeroNet/ZeroNet#620]
Was hoping to get dynamic favicon files served by the UiServer. I've created a tentative [commit](https://github.com/mishfit/ZeroNet/commit/84ea1687ab76b27688f44d61abdf99d92c985a5e) but am not sure I'm using the right approach.

I've removed the lines where UiRequest blindly serves the standard ZeroNet favicon and added an attempt to retrieve the favicon from content.json.

I've also changed the wrapper template to take a favicon variable and add the appropriate header link tag.

I would appreciate it if you could look it over, critique it, and (if acceptable) I'll create the PR for it.

**Comment by HelloZeroNet** [comment]
It's looking good for me

**Comment by mishfit** [comment]
Cool, I've made a [PR](https://github.com/HelloZeroNet/ZeroNet/pull/621). I just need to update the docs and make a PR for that too
