### ISSUE TITLE
anonying open site popups. pls help

### ISSUE THREAD

**Issue by siyuandong** [HelloZeroNet/ZeroNet#622]
I got this "You have opened this page by clicking on a link. Please, confirm if you want to load this site." even when I refresh my site. and with click link too..

After search in code I found it there in https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee line 76.

It seems that only I have this problem after asking around.. is it a local mozilla setting thing ? and how can I shut it down.  it is annoying cos when I click "open site" then all the http paremeters are missing. 

Thx in advance!

**Comment by HelloZeroNet** [comment]
Can you please describe when do you see this error? Are you using the ZeroNet's api?

**Comment by siyuandong** [comment]
here is my site.
1HrBmidiq34bcHaDAdQWC37ne6Scu8euQN
when I click the link inside the page I see the popups. 

I use ZeroFrame.js ZeroChat.js

**Comment by HelloZeroNet** [comment]
You need to add  `"postmessage_nonce_security": true,` to content.json, then sign/publish it.

**Comment by siyuandong** [comment]
got error.

13:57:38.245 The connection to ws://127.0.0.1:43110/Websocket?wrapper_key=7e14d9be96e9beaacaed17d1c0b40ef0fcaab9adc4847ff83ed4ce8cbb518e52 was interrupted while the page was loading.1 all.js:40:16


[Wrapper] Message nonce error: undefined != 73b55c44553e90763eec746a73a31b1bf5692e0006aba5f39ac94628af5517e9 all.js:1357:14

**Comment by HelloZeroNet** [comment]
please update your zeroframe.coffee to this version: https://github.com/HelloZeroNet/ZeroMe/blob/master/js/utils/ZeroFrame.coffee

**Comment by siyuandong** [comment]
updated.

**Comment by HelloZeroNet** [comment]
you need to compile it to zeroframe.js. (if you dont have coffeescript compiler installed, then you can paste this: https://github.com/HelloZeroNet/ZeroMe/blob/master/js/all.js#L2363-L2514)

**Comment by siyuandong** [comment]
o...sorry. now compiled. got Class not found error.

**Comment by HelloZeroNet** [comment]
https://github.com/HelloZeroNet/ZeroMe/blob/master/js/lib/Class.coffee

**Comment by siyuandong** [comment]
@HelloZeroNet 

Thank you very much! it is working !!!

**Comment by siyuandong** [comment]
only curious,  I tested on my mac machine and it has no popups even without adding "postmessage_nonce_security": true.  and my friend has Ubuntu dont have this popup either. why this only happen to my computer (linux mint + firefox) ?

**Comment by HelloZeroNet** [comment]
Well, it's hard to tell: the message is displayed if the window.opener object is present. Normally it should not be present if you does not opened the page using javascript's `window.open` command. 

It's a security issue, because it means there is a opener page that able to fake the page API commands by using postMessage that we use to comminicate between the inner iframe page and the wrapper html. With the nonce security added it's not longer possible becase you need a random generated "password" to make the messages executed by the frame.
