### ISSUE TITLE
cloud anyone help me with this ? i use ubuntu+apache2

### ISSUE THREAD

**Issue by tianrking** [HelloZeroNet/ZeroNet#624]
Forbidden
Media referrer error
Please report it if you think this an error.

Details:

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip", 
    "HTTP_ACCEPT_LANGUAGE": "en-SG,en-US;q=0.8,en;q=0.6", 
    "HTTP_CF_CONNECTING_IP": "204.44.93.202", 
    "HTTP_CF_IPCOUNTRY": "US", 
    "HTTP_CF_RAY": "2f9f97a5a24507e5-LAX", 
    "HTTP_CF_VISITOR": "{\"scheme\":\"http\"}", 
    "HTTP_CONNECTION": "Keep-Alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_MAX_FORWARDS": "100", 
    "HTTP_REFERER": "http://zeronet.0o0o0.ml/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "HTTP_SAVE_DATA": "on", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Linux; Android 6.0.1; SM-G9008V Build/MOB31E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.28 Mobile Safari/537.36", 
    "HTTP_X_FORWARDED_FOR": "204.44.93.202, 173.245.48.71", 
    "HTTP_X_FORWARDED_HOST": "zeronet.0o0o0.ml", 
    "HTTP_X_FORWARDED_PROTO": "http", 
    "HTTP_X_FORWARDED_SERVER": "zeronet.0o0o0.ml", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/", 
    "QUERY_STRING": "wrapper_nonce=4f109fba2ddb543806336e71392e1046c264bcbf74cdc10a0b059ec32d06aa6e", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "37001", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost.localdomain", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 10, 
        "data_dir": "data", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "keep_ssl_cert": false, 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": null, 
        "proxy": null, 
        "size_limit": 10, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.aletorrenty.pl:2710/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false
    }, 
    "plugins": [
        "Zeroname", 
        "MergerSite", 
        "Newsfeed", 
        "Trayicon", 
        "AnnounceZero", 
        "CryptMessage", 
        "Sidebar", 
        "Stats"
    ], 
    "version_gevent": "1.0.2", 
    "version_python": "2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]", 
    "version_zeronet": "0.4.1 r1536", 
    "wsgi.url_scheme": "http"
}

**Comment by HelloZeroNet** [comment]
You need `ProxyPreserveHost on`, example:
```
<VirtualHost *:443>

        ServerName zeronet.example.com

        ProxyRequests off
        ProxyPreserveHost on
        ProxyPass / http://127.0.0.1:43110/
        ProxyPassReverse / http://127.0.0.1:43110/

        <Location /Websocket>

                ProxyPass ws://127.0.0.1:43110/Websocket
                ProxyPassReverse ws://127.0.0.1:43110/Websocket
        </Location>


        SSLEngine on
        SSLProxyEngine on
        SSLCertificateFile /etc/certs/cert.pem
        SSLCertificateKeyFile /etc/certs/privkey.pem
        SSLCertificateChainFile /etc/certs/chain.pem
</VirtualHost>
```

**Comment by tianrking** [comment]
哦耶 @@  thank you very much. i get it .:))
