### ISSUE TITLE
Seed websites on Demand

### ISSUE THREAD

**Issue by Nutomic** [HelloZeroNet/ZeroNet#625]
At the moment, Zeronet will start to seed a site as soon as you visit it. This is problematic, because users might accidently seed content that's illegal in their country. Additionally, it means you get a lot of connected sites really fast.

Instead, it should be possible to browse sites without connecting to them. Zeronet should show a button "Connect to Site", which starts seeding it.

[Discussion on this topic on Reddit](https://www.reddit.com/r/zeronet/comments/5a41ss/i_love_the_idea_and_the_technology_its_truly/)

**Comment by HelloZeroNet** [comment]
It would be against the network relability. If you don't like the content of the site, then you can delete or pause it.
