### ISSUE TITLE
Is it possible to develope a zeronet website without Wrapper.coffee?

### ISSUE THREAD

**Issue by suzumiyasmith** [HelloZeroNet/ZeroNet#626]
Actually, I am confused about front-end of zeronet website, since every website suffers an "O" in the up-right corner.
I have no ideas about how to get a clear & clean website.
Every page I have seen in the zeronet all uses Wrapper.coffee as a part of js code which adds a big "o" in its coner.

**Comment by fl0wjacky** [comment]
Cause it's ZeroNet.so there is a zero(O),I guess.

2016年11月4日星期五，suzumiyasmith <notifications@github.com> 写道：

**Comment by HelloZeroNet** [comment]
Nope, it's not possible, the frame is required for security reasons, since every site is using the same domain (127.0.0.1)
