### ISSUE TITLE
Per-user settings

### ISSUE THREAD

**Issue by Binero** [HelloZeroNet/ZeroNet#630]
When changing settings like always having Tor on, Zeronet tries to edit a file in /etc/ which is global to all users. Every user should have their own zeronet configuration in their home directory.

**Comment by HelloZeroNet** [comment]
By default zeronet is using (and writing) the zeronet.conf from the working directory (where the zeronet.py file is), so it does not writes to /etc.

You can specify the path of the config file by `--config_file anyfile`
