### ISSUE TITLE
report 

### ISSUE THREAD

**Issue by juansantiago** [HelloZeroNet/ZeroNet#632]
generated link: http://127.0.0.1:43110/15F9LYs6c17NUXv3MxpJSGbpWxyHTEbzMk/stream/audio.html?wrapper_nonce=83838116cdd6148da634b34d78e2862cfc17ab809d63a6010f51511b95c39604?ID=038adceb2b5f4bf9451df7a8b6cf9393ea693918

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate", 
    "HTTP_ACCEPT_LANGUAGE": "es,en-US;q=0.7,en;q=0.3", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1", 
    "PATH_INFO": "/15F9LYs6c17NUXv3MxpJSGbpWxyHTEbzMk/stream/audio.html", 
    "QUERY_STRING": "wrapper_nonce=83838116cdd6148da634b34d78e2862cfc17ab809d63a6010f51511b95c39604?ID=038adceb2b5f4bf9451df7a8b6cf9393ea693918", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "46201", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 10, 
        "data_dir": "data", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "keep_ssl_cert": false, 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": null, 
        "proxy": null, 
        "size_limit": 10, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.aletorrenty.pl:2710/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false
    }, 
    "plugins": [
        "AnnounceZero", 
        "Trayicon", 
        "Zeroname", 
        "Sidebar", 
        "Newsfeed", 
        "MergerSite", 
        "CryptMessage", 
        "Stats"
    ], 
    "version_gevent": "1.0.1", 
    "version_python": "2.7.9 (default, Jun 29 2016, 13:08:31) \n[GCC 4.9.2]", 
    "version_zeronet": "0.4.1 r1536", 
    "wsgi.url_scheme": "http"
}

**Comment by HelloZeroNet** [comment]
You have to use target=_top on links to make it work
