### ISSUE TITLE
Trayicon disappear after restart "explorer.exe"

### ISSUE THREAD

**Issue by ysc3839** [HelloZeroNet/ZeroNet#633]

**Comment by HelloZeroNet** [comment]
Can't reproduce on windows 10, earlier windows probably works, but not fully supported.

Alternatively you can install the come extension that adds a button next to the address bar to easy access:
https://chrome.google.com/webstore/detail/zeronet-protocol/cpkpdcdljfbnepgfejplkhdnopniieop

**Comment by ysc3839** [comment]
I know what's the problem. Because after explorer.exe started all tray icon were cleared, apps need to re create them again. I'll try to fix it on weekends if I have time.
