### ISSUE TITLE
Err: IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by yzou** [HelloZeroNet/ZeroNet#634]
Server error

Err: IOError: [Errno 24] Too many open files: u'data/1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F/data/names.json' in UiServer.py line 81 > UiRequest.py line 82 > MultiuserPlugin.py line 40 > UiRequest.py line 194 > SiteManagerPlugin.py line 59 > SiteManagerPlugin.py line 39 > SiteStorage.py line 230 > SiteStorage.py line 151

Please report it if you think this an error.

Details:
```

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch, br", 
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4", 
    "HTTP_CONNECTION": "upgrade", 
    "HTTP_HOST": "bit.no.com", 
    "HTTP_REFERER": "https://www.google.com.hk/", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36", 
    "HTTP_X_FORWARDED_FOR": "47.89.43.124", 
    "HTTP_X_REAL_IP": "47.89.43.124", 
    "PATH_INFO": "/shadowsocksr.bit/", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "38191", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43111", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.1 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 10, 
        "data_dir": "data", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "keep_ssl_cert": false, 
        "log_dir": "log", 
        "max_files_opened": 102400, 
        "msgpack_purepython": true, 
        "multiuser_local": false, 
        "open_browser": null, 
        "proxy": null, 
        "size_limit": 10, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.aletorrenty.pl:2710/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43111, 
        "ui_restrict": false, 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false
    }, 
    "plugins": [
        "Newsfeed", 
        "Zeroname", 
        "AnnounceZero", 
        "Stats", 
        "Multiuser", 
        "Trayicon", 
        "MergerSite", 
        "CryptMessage", 
        "Sidebar"
    ], 
    "version_gevent": "1.1.0", 
    "version_python": "2.7.12 (default, Jul  1 2016, 15:12:24) \n[GCC 5.4.0 20160609]", 
    "version_zeronet": "0.4.1 r1536", 
    "wsgi.url_scheme": "http"
}
```

**Comment by HelloZeroNet** [comment]
The proxy owner has to increase the opened file limit:
http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by yzou** [comment]
Thanks.

**Comment by HelloZeroNet** [comment]
python and the gc should take care of closing not used files

**Comment by WalnutATiie** [comment]
for my client, fd open is 3 as well. but what i use is keep-alive connection and still get problem. That's the console reports:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-i686.egg/gevent/greenlet.py", line 327, in run
  File "plugins/AnnounceZero/AnnounceZeroPlugin.py", line 43, in announceTracker
  File "/home/test/ZeroNet-master/src/Site/Site.py", line 725, in announceTracker
  File "/home/test/ZeroNet-master/src/lib/subtl/subtl.py", line 42, in __init__
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.2-py2.7-linux-i686.egg/gevent/socket.py", line 229, in __init__
    self._sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files`

**Comment by HelloZeroNet** [comment]
@WalnutATiie Can you please check these commands?
```
$ ls -l /proc/13302/fd | wc -l
211
$ ulimit -a
Maximum size of core files created                           (kB, -c) 0
Maximum size of a process’s data segment                     (kB, -d) unlimited
Maximum size of files created by the shell                   (kB, -f) unlimited
Maximum size that may be locked into memory                  (kB, -l) 64
Maximum resident set size                                    (kB, -m) unlimited
Maximum number of open file descriptors                          (-n) 1024
Maximum stack size                                           (kB, -s) 8192
Maximum amount of cpu time in seconds                   (seconds, -t) unlimited
Maximum number of processes available to a single user           (-u) 5897
Maximum amount of virtual memory available to the shell      (kB, -v) unlimited
```

**Comment by HelloZeroNet** [comment]
At startup ZeroNet tries to modify the it's limit to 2048, I just found a bug in that code, so please update and try again: https://github.com/HelloZeroNet/ZeroNet/commit/6f2445c417e59c3bf948ff5c3fd0a722c710f9d3

**Comment by WalnutATiie** [comment]
I think to deal with the problem is not just changing system max FD settings. All opened FD should be closed after use.

What I want to do is use a local zeronet client as a web proxy to crawl webpages in zeronet. I use `python gevent` to request webpages asynchronously but once the number of my requests reach about 1000, the problem occured. Netstat is all normal, juse take about 20 port as I set, so I don't think it's all of tcp collections. 

Or you can tell me what should I do if I want to use the client as a web proxy.:) thank you very much.

**Comment by HelloZeroNet** [comment]
My instance running since 3 month and it has 223 opened files, so I don't think if there is any any FD closing problem. 
ZeroNet very rarely closes sockets, since it required to receive and distribute new updates. You can try to disable ssl via `--disable_encryption` and `--connected_limit`, but I think it's safe to increase the limit, for example Debian 8 has 65536 as default.

**Comment by slrslr** [comment]
Hello, i just got this error when i downloaded new 64bit Linux ZeroBundle today and copied into its data folder my users.json, sites.json and started Zeronet.sh

My sites.json contains several hundred of sites and apparently Zeronet is made the way it is reaching my Linux OS limits.


$ python [test_max.py](https://github.com/HelloZeroNet/ZeroNet/issues/320#issuecomment-192617608)

> Max open files without changing settings: 1021
> Current RLIMIT_NOFILE limit: 1024 4096 Changing to 3000...
> Max open files after changing settings: 2997

[This Zeronet article](http://127.0.0.1:43110/1LfvE91ZF18jdG3wW62Dw7NtfTZh737KPL/?Topic:1749819733_1NyeZB982bDoQY7uu5EAM88RJDnDCYzdpR/ZeroNet+Conservancy+FIX+Err+OSError+Errno+24+Too+many+open+files) may help to raise the limits.
