### ISSUE TITLE
Recommended Optional Files

### ISSUE THREAD

**Issue by ZerataX** [HelloZeroNet/ZeroNet#635]
I think ZeroNet sites could improve a lot if they were allowed to recommend what parts of a website to save to a client.

For example a website for sharing comics, music or whatever.
Here you could implement one button for individual comics to save them to local storage so that they wouldn't just be seeded but also would be available offline with the same features, that a site like this could offer, like a search and tagging system.
Instead of just saving what was recently visited users could seed the content they really wanted and also get something out of it for themselves.

Of course this would require some kind of permission system to make sure a website only adds optional files the user willingly opted in for and allowed.

Or is this what is possible with the new list/delete/pin/manage files?

**Comment by unsystemizer** [comment]
I think that's available (or large subset of it) in the new version.

**Comment by HelloZeroNet** [comment]
If you include the recommended content to your page (eg using simple <img> tag), then it will be downloaded for offline viewing.

**Comment by ZerataX** [comment]
Okay cool thank you for your support!
