### ISSUE TITLE
logo for file update failed missing

### ISSUE THREAD

**Issue by numidark** [HelloZeroNet/ZeroNet#643]
After formating my computer and reinstall Zeronet, the logo for "file update failed" missing.
![capture du 2016-11-15 11-49-18](https://cloud.githubusercontent.com/assets/14799472/20302990/99550efa-ab29-11e6-88f7-746a392dd4ad.png)

I am no idea for reason of this problem.
I am on linux mint 18

Cordialy

**Comment by HelloZeroNet** [comment]
it's using bell utf8 character: 🔔 http://graphemica.com/%F0%9F%94%94
probably you are missing some fonts on your machine

**Comment by numidark** [comment]
what is the font used on ZeroNet for bell utf8 ?

**Comment by HelloZeroNet** [comment]
It's defined as Arial, Helvetica, 'Segoe UI Symbol', but if these are not present on your system, then it should fall back to systemdefault

**Comment by numidark** [comment]
Strange it's present on my system :o but the bell is not correctly formated
I have no idea to solve that :D

**Comment by HelloZeroNet** [comment]
https://jsfiddle.net/kha51nn0/
is any of these works for you?

**Comment by numidark** [comment]
Nothing work :(
