### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by robinvd** [HelloZeroNet/ZeroNet#645]
After the lastest update i get this error starting zeronet. 
using arch linux arm on raspberry pi.
python version: 2.7.12

```
- Starting ZeroNet...
Traceback (most recent call last):
  File "./zeronet.py", line 15, in main
    import main
  File "./src/main.py", line 25, in <module>
    from Config import config
  File "/usr/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "./src/Config.py", line 343, in <module>
    config = Config(sys.argv)
  File "./src/Config.py", line 17, in __init__
    self.createArguments()
  File "./src/Config.py", line 51, in createArguments
    language = language.split("_")[0]
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by HelloZeroNet** [comment]
Can you please run: `python -c "import locale; print locale.getdefaultlocale()"` ?

**Comment by robinvd** [comment]
$ python2 -c "import locale; print locale.getdefaultlocale()"
(None, None)

$ locale -a
C
POSIX
en_US.utf8

**Comment by HelloZeroNet** [comment]
It's fixed in latest version

**Comment by MarwaDF** [comment]
Any help about this please ? I am using python 3.5 anaconda

filter_sizes=list(map(int, FLAGS.filter_sizes.split(","))),

AttributeError: 'NoneType' object has no attribute 'split'

**Comment by imachug** [comment]
@MarwaDF You have to use Python 2, not Python 3.

**Comment by MarwaDF** [comment]
But python 2 is not supported with tensorflow on windows

**Comment by imachug** [comment]
@MarwaDF I'm sorry, but I don't understand what you mean. Do you want to add tensorflow to ZeroNet or just use ZeroNet and TensorFlow simultaneously? In the latter case, you might want to check out `py launcher` for Windows.

**Comment by MarwaDF** [comment]
I am using python 3.5 and tensorflow for deeplearning on windows,
tensorflow is not supporeted with python 2 ,  so i should turn To python 3
but i get this error

**Comment by imachug** [comment]
@MarwaDF You should install both Python 2 and python 3 then. You can use [py launcher](https://docs.python.org/3/using/windows.html), which will install both Python 2 (for ZeroNet) and Python 3 (for TensorFlow). Then you will be able to run ZeroNet via `py -2 zeronet.py` and some script using TensorFlow via `py -3 tensorflow.py`.

**Comment by MarwaDF** [comment]
I am sorry,but I forgot to mention that I use anaconda and I already installed both versions of python (2 and 3)

**Comment by imachug** [comment]
@MarwaDF How are you running ZeroNet? Via command line? What command or script are you using?

**Comment by MarwaDF** [comment]
Sorry,don't understand you, but I am using spyder

2018-04-02 20:16 GMT+02:00 Ivanq <notifications@github.com>:

**Comment by imachug** [comment]
@MarwaDF Oh, I see. You are using IDE.

Could you please open Command Line (via WindowsKey+R, then `cmd` <kbd>Enter</kbd>), and try to execute some of the following commands;

```
python
python2
py -2
```

If you receive a Python prompt after running one of them (the prompt is `>>>`), type `exit()`; if you don't, try the next one. One of the commands should say `...Python 2...`.

Now, if e.g. `py -2` worked, you should create a script in `ZeroNet/start.bat` and type the following:

```batch
py -2 start.py
```

So you won't have to run ZeroNet via IDE (it won't help you at all, because ZeroNet is a server, and it is infinite, and ...well, will you ever need to debug it?..).

**Comment by MarwaDF** [comment]
have you an idea how to convert code written on tensorflow to keras ?

2018-04-03 6:51 GMT+02:00 Ivanq <notifications@github.com>:

**Comment by imachug** [comment]
@MarwaDF Oh man, in fact I don't use TensorFlow, I've just heard something about it, and I've never heard anything about Keras... I'm sorry I can't help.

**Comment by MarwaDF** [comment]
okay .Thanks

2018-04-07 11:42 GMT+02:00 Ivanq <notifications@github.com>:
