### ISSUE TITLE
Tor cant connect

### ISSUE THREAD

**Issue by triceratops1** [HelloZeroNet/ZeroNet#648]
0
≡
! Internal error: IOError: [Errno 13] Permission denied: '/etc/zeronet.conf'
UiWebsocket.py line 99 > UiWebsocket.py line 184 > UiWebsocket.py line 721 > Config.py line 336
×
  

host: archlinux
version: 0.50

**Comment by HelloZeroNet** [comment]
ZeroNet by default does not writes to /etc, please use the zerobundle package or report it to the package maintainer.
