### ISSUE TITLE
Distributed minimum spanning tree

### ISSUE THREAD

**Issue by Bachstelze** [HelloZeroNet/ZeroNet#649]
Is the Broadcast with UDP SSDP M-SEARCH comparable with the minimum spanning tree?
watch out: https://en.wikipedia.org/wiki/Distributed_minimum_spanning_tree

**Comment by HelloZeroNet** [comment]
It's only used for UPNP port opening: https://en.wikipedia.org/wiki/Universal_Plug_and_Play
