### ISSUE TITLE
how we can help with translations ?

### ISSUE THREAD

**Issue by icf20** [HelloZeroNet/ZeroNet#650]
:)

**Comment by HelloZeroNet** [comment]
If someone want to help add new languages, the files needs to be translated:

https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Translate/languages/hu.json
https://github.com/HelloZeroNet/ZeroNet/blob/master/plugins/Sidebar/languages/hu.json
https://github.com/HelloZeroNet/ZeroHello/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroMe/blob/master/languages/hu.json
https://github.com/HelloZeroNet/ZeroTalk/blob/master/languages/hu.json

Simply make a copy of them to the same dir where they are with the language short code you are going to translate to and replace the Hungarian translation.

To test them before submitting to github:
 - By default ZeroNet uses the operating system language, but you can also specify it in zeronet.conf (where zeronet.py is)
 - Open sidebar, check "This is my site"
 - Open javascript console (F12) check "Disable cache" on Network tab to avoid caching, keep window open
 - To reload Core language files (src/Translate/languages/hu.json and plugins/Sidebar/languages/hu.json) without restart you have to click on you language again on ZeroHello's 3dot menu

**Comment by icf20** [comment]
for now 
https://github.com/icf20/ZeroNet/blob/master/src/Translate/languages/ro.json

**Comment by brato-mo** [comment]
So i just translted all those files into Bosnian. Renamed hu to ba. i hope thats it
