### ISSUE TITLE
How to get started in implementing ZeroNet to other languages?

### ISSUE THREAD

**Issue by ghost** [HelloZeroNet/ZeroNet#658]
As the title suggests, can someone help me understand how to get started in developing ZeroNet into other languages like Java or C++?
Can you put together a list of all the dependencies too perhaps?

**Comment by ysc3839** [comment]
You need to learn about [ZeroNet network protocol](https://zeronet.readthedocs.io/en/latest/help_zeronet/network_protocol/).

**Comment by shanmukhateja** [comment]
@ysc3839  Thank you. Have there been any other implementations so far? It would help as reference code.

**Comment by ysc3839** [comment]
I think no.

**Comment by suzumiyasmith** [comment]
Currently, there is no need to make a new implement.
1. Zeronet codes are improving and making progress.
2. Python is fast enough for networking now.

No doubt there will be another implementation of Zeronet boosting efficiency without conflicting the existing one.

**Comment by MuxZeroNet** [comment]
[ZeroGo](https://github.com/G1itchZero/ZeroGo) is a minimalist Golang implementation of ZeroNet.

**Comment by grez911** [comment]
There is also appeared [ZeroNetJS](https://github.com/ZeroNetJS/zeronet-js).

**Comment by IronBug** [comment]
Are there any C/assembler forks? I don't use python, but I like the overall idea and could write the same engine in C. But maybe somebody has already started such a project?

**Comment by MuxZeroNet** [comment]
zerolib (Python 3)
https://github.com/MuxZeroNet/zerolib

ZeroGo (Go)
https://github.com/G1itchZero/ZeroGo

**Comment by purplesyringa** [comment]
@HelloZeroNet Not sure if this is resolved?
