### ISSUE TITLE
Some questions about translate

### ISSUE THREAD

**Issue by ysc3839** [HelloZeroNet/ZeroNet#661]
Is there any tools like `xgettext` to extract translatable strings?
Also I think we should use _("text") to translate in js files so that we can extract translatable strings.
And it's also necessary to add format function (like Python) in js.

**Comment by HelloZeroNet** [comment]
It's not possible to list, because you can translate any string.

There is tons of javascript localization frameworks, you can use any of them if you want.

**Comment by ysc3839** [comment]
I mean list strings in .py files.

**Comment by HelloZeroNet** [comment]
I'm not familiar with it, but I have added every string to the hu.json file

**Comment by ysc3839** [comment]
I will try to edit the pygettext.py and see if it works.
