### ISSUE TITLE
Responsive design for mobile device?

### ISSUE THREAD

**Issue by ysc3839** [HelloZeroNet/ZeroNet#666]

**Comment by HelloZeroNet** [comment]
You can specify the viewport in content.json, example from ZeroTalk: https://github.com/HelloZeroNet/ZeroTalk/blob/master/content.json#L81

**Comment by ysc3839** [comment]
You misunderstood me, I mean will the ZeroHello have responsive design for mobile devices? I want to help but I really lack of HTML...

**Comment by HelloZeroNet** [comment]
I have no smartphone, but in the emulator it's seems pretty comfortable to use: double tap right selection if you want to read the newsfeed, double tap left selection if you want to browse sites you seed

**Comment by ysc3839** [comment]
You can use browser's developer tools to test responsive design. Double tap is not convenient. And other sites (ZeroMe, ZeroMail etc.).

**Comment by ysc3839** [comment]
Off topic: Which mobile phone do you use?

**Comment by HelloZeroNet** [comment]
Yeah I meant the chrome's responive tester by the emulator. I have an old nokia phone. (1110 or similar)
