### ISSUE TITLE
Internal error: error: nothing to repeat

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#672]
im getting this error on every attempted user-originated site publish (comments, votes)

Internal error: error: nothing to repeat
UiWebsocket.py line 99 > UiWebsocket.py line 184 > MergerSitePlugin.py line 180 > MergerSitePlugin.py line 174 > UiWebsocket.py line 333 > MergerSitePlugin.py line 177 > MergerSitePlugin.py line 174 > UiWebsocket.py line 314 > ContentManager.py line 594 > ContentManager.py line 714 > re.py line 137 > re.py line 244

example function:

// get user's view.json
var inner_path = "data/users/"+Page.site_info.auth_address+"/view.json";			
Page.cmd("fileGet", { "inner_path": inner_path, "required": false },function(data) {
        (------------)				
	// write to file
	var json_raw = unescape(encodeURIComponent(JSON.stringify(data, void 0, '\t')));					
	Page.cmd("fileWrite", [inner_path, btoa(json_raw)], function(res) {
		console.log(res);
		// sign & publish site
		Page.cmd("sitePublish",["stored",inner_path], function(res) {
                    (------)
		});
	});
});

this is the site:
http://127.0.0.1:43110/1HPbR1zp6hsvrqgTSVdsEC5VWw7MEMGPTR

**Comment by HelloZeroNet** [comment]
The line 714 in ContentManager.py:
`                if not re.match("^%s$" % rules["files_allowed"], file_inner_path):`

Your files_allowed pattern in data/users/content.json is invalid: `"files_allowed": "*.json"` it should be: `"files_allowed": ".*json"`
