### ISSUE TITLE
Can't translate 1 field

### ISSUE THREAD

**Issue by iShift** [HelloZeroNet/ZeroNet#674]
![image](https://cloud.githubusercontent.com/assets/426427/20619412/7bc1ed52-b305-11e6-923f-a7534f21dc69.png)

**Comment by ysc3839** [comment]
Try adding "Site control" in Jason file.

**Comment by HelloZeroNet** [comment]
Yeah, missed that one. Addig "Site control" will work: e2d73637f62eb13548c2a3bdb7bb9191ade92874
