### ISSUE TITLE
Angularjs error while hosting app in ZeroNet

### ISSUE THREAD

**Issue by amiyatulu** [HelloZeroNet/ZeroNet#675]
Tried to serve an angularjs app: it gives an error due to iframe. `angular.js:9475Error: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.`
How do i fix it?

**Comment by ysc3839** [comment]
Do you use cookies?

**Comment by amiyatulu** [comment]
No.

**Comment by ysc3839** [comment]
Use localstorage instead of cookies.
