### ISSUE TITLE
Making an api, for making post, get, delete,  request in json that works with $http service of angularjs

### ISSUE THREAD

**Issue by amiyatulu** [HelloZeroNet/ZeroNet#676]
Zero net has  ZeroFrame API, but can user build an API over it to make POST and GET request in JSON that can be used with $http service of angularjs. We can write the logic on the page (a local host link) that gives GET data in JSON and takes POST data in JSON. But what if some client changes the logic.  I think the owner site should be always online. POST request can only be done through owner site, where the owner can authenticate the JSON file before feeding it to the database. Even owner can host multiple (authentic) sites on different servers where post request can be done in all these sites by different clients. All authentic sites should be synced with each other. Another question is how does a client recognize the different authentic owner sites and downloaded sites from the owner? Authentic sites can have a unique public key, than that of downloaded sites, and downloaded sites can't use the authentic site public key. A registrar of username and the authentic public key and its downloaded site public key should be kept.

**Comment by HelloZeroNet** [comment]
ZeroNet only support websocket api, no alternative API planned yet

**Comment by amiyatulu** [comment]
Just a suggestion, what is the feasibility of including [IPFS](https://ipfs.io/) in ZeroNet?

**Comment by HelloZeroNet** [comment]
IPFS written in GO, so it would require different toolset to run it. But there is many alternative to IPFS: BitTorrent, StorJ, Maidsafe, Sia, etc., every site owner able to choose the best one that fits to his/her needs.

**Comment by amiyatulu** [comment]
IPFS has a python [api](https://github.com/ipfs/py-ipfs-api), which can work with zeronet. Large file sharing can be done with it.

**Comment by HelloZeroNet** [comment]
It's just an API, but you still need to compile to run it. With the optional files support it's also possible to share big files using ZeroNet, but the problem is most of the users are using ZeroNet using Tor, which is not suitable to transfer big files.

**Comment by amiyatulu** [comment]
It already comes precompiled. The good thing about it is, it's very [structured](https://github.com/ipfs/papers/raw/master/ipfs-cap2pfs/ipfs-p2p-file-system.pdf), and is made to be usable by different apps like ZeroNet.

**Comment by sonatagreen** [comment]
There's [a JS implementation](https://github.com/ipfs/js-ipfs) of IPFS.
