### ISSUE TITLE
Multiuser systems

### ISSUE THREAD

**Issue by SergeyDjam** [HelloZeroNet/ZeroNet#682]
Hello! 
How i can one installation in multiuser system?

**Comment by ysc3839** [comment]
What's the meaning of "one installation"?

**Comment by SergeyDjam** [comment]
Installation in systempaths /usr/share/zeronet or /opt/zeronet or /usr/lib/python2.7/site-package/zeronet and run oher users in system

**Comment by ysc3839** [comment]
Try download the tar archiver and extract to /opt.

**Comment by SergeyDjam** [comment]
/opt/zeronet/start.py 
- Starting ZeroNet...
Traceback (most recent call last):
  File "/opt/zeronet/zeronet.py", line 15, in main
    import main
  File "/opt/zeronet/src/main.py", line 95, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/opt/zeronet/src/Plugin/PluginManager.py", line 29, in loadPlugins
    for dir_name in sorted(os.listdir(self.plugin_path)):
OSError: [Errno 2] No such file or directory: 'plugins'

and this non fix problem

**Comment by SergeyDjam** [comment]
ls -la /opt/zeronet/
итого 96
drwxr-xr-x  5 root root  4096 ноя 28 19:08 ./
drwxr-xr-x 19 root root  4096 ноя 28 19:09 ../
-rw-r--r--  1 root root  4581 ноя 28 00:03 CHANGELOG.md
-rw-r--r--  1 root root     0 ноя 27 23:40 debugfiles.list
-rw-r--r--  1 root root     0 ноя 27 23:40 debuglinks.list
-rw-r--r--  1 root root     0 ноя 27 23:40 debugsources.list
-rw-r--r--  1 root root   755 ноя 28 00:03 Dockerfile
-rw-r--r--  1 root root   355 ноя 28 00:03 .gitignore
-rw-r--r--  1 root root 18027 ноя 28 00:03 LICENSE
drwxr-xr-x 19 root root  4096 ноя 28 19:08 plugins/
-rw-r--r--  1 root root  7459 ноя 28 00:03 README.md
-rw-r--r--  1 root root  7407 ноя 28 00:03 README-zh-cn.md
-rw-r--r--  1 root root    36 ноя 28 00:03 requirements.txt
drwxr-xr-x 19 root root  4096 ноя 28 19:08 src/
-rwxr-xr-x  1 root root   243 ноя 28 00:03 start.py*
drwxr-xr-x  4 root root  4096 ноя 28 19:08 tools/
-rw-r--r--  1 root root   495 ноя 28 00:03 .travis.yml
-rwxr-xr-x  1 root root  3373 ноя 28 00:03 update.py*
-rw-r--r--  1 root root  1196 ноя 28 00:03 Vagrantfile
-rwxr-xr-x  1 root root  2008 ноя 28 00:03 zeronet.py*

**Comment by SergeyDjam** [comment]
If the program different users of the one computer launch that data of a profile there will be the general which are stored in the data folder

**Comment by casept** [comment]
cd into the install directory, then do this: `python2 /path/to/directory/containing/zeronet/zeronet.py --data_dir ~/data --log_dir ~/logs`. For some reason the code is picky about in which directory you are when you run it.

**Comment by SergeyDjam** [comment]
python2 /opt/zeronet/zeronet.py --data_dir ~/.zeronet/data --log_dir ~/.zeronet/logs
- Starting ZeroNet...
Traceback (most recent call last):
  File "/opt/zeronet/zeronet.py", line 15, in main
    import main
  File "/opt/zeronet/src/main.py", line 95, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/opt/zeronet/src/Plugin/PluginManager.py", line 29, in loadPlugins
    for dir_name in sorted(os.listdir(self.plugin_path)):
OSError: [Errno 2] No such file or directory: 'plugins'

d'nt fix problem

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it should work now: c1fd2be8cfadf3e93ae70e3d9763875460bb81a3
