### ISSUE TITLE
Favorited sites last item menu not shown

### ISSUE THREAD

**Issue by siyuandong** [HelloZeroNet/ZeroNet#683]
Very strange... 

I run Firefox and Chrome. zeronet rev1755. both of them has this problem.

the last item from favorited sites menu not shown.  so can not clone or do any else action.

**Comment by siyuandong** [comment]
I deleted browsers local storage, the favorited sites goes back to the list,  menu appear again.. seems only happen to Favorited Sites ' s Last menu .

**Comment by siyuandong** [comment]
dont know why.. seems working now.

**Comment by siyuandong** [comment]
seems only happens to favorite this site: 1LK6eAVVsRscLCTQqEHhrvLXACaDcWUrU1

**Comment by HelloZeroNet** [comment]
Thanks, fixed (btw the site is broken, being a merger and a merged site will never work properly)
