### ISSUE TITLE
Changed proxy port 

### ISSUE THREAD

**Issue by SEVENID** [HelloZeroNet/ZeroNet#684]
Tried to start
`python zeronet.py --proxy 127.0.0.1:9050`
result: big traceback and
`Error connecting to SOCKS5 proxy 127.0.0.1:49050: [Errno 111] Connection refused
^C^CShutting down...
[04:49:23] - Unhandled exception
None`
Port 9050 in args, port 49050 in traceback. Of course, it doesn't connect.

**Comment by HelloZeroNet** [comment]
add --tor disable to the parameters

**Comment by border0464111** [comment]
cool , solved ?

**Comment by SEVENID** [comment]
I still think it's problem, defaults must be changed. But solution works.
