### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jingshiwenlibi** [HelloZeroNet/ZeroNet#685]
I have following requrements：BT protocol can  do？or changed can do？
（1）data  is distributed fullly  or incrementally which mode peer can choose？
（2)data  distribution support priority？
thank you！

**Comment by HelloZeroNet** [comment]
- A new update is distributed as a "diff", so while your computer is online you will receive only the changed lines, but if you re-connect to the network you re-download the who changed files
- The files that requested by your client (via http) will be prioritized
