### ISSUE TITLE
MacOS client requires administrator account to use.

### ISSUE THREAD

**Issue by Forbo** [HelloZeroNet/ZeroNet#694]
```
forbo$ ./ZeroNet.app 
- Starting ZeroNet...
Can't open lock file, your ZeroNet client is probably already running, exiting... ([Errno 13] Permission denied: 'data/lock.pid')
Opening browser: %s... default_browser
```

For security purposes, it would be great to be able to run this within the context of a standard user account. If that's not possible at this point, then it would be nice to at least have some indicator in the documentation listing an administrative account as a requirement.

**Comment by HelloZeroNet** [comment]
It should work, are you sure your user has the permission to write in the data directory?

**Comment by HelloZeroNet** [comment]
I have just tried and it's works with "Standard user"

**Comment by Forbo** [comment]
Strange. I created a fresh standard account to test it out and it worked great. I then went back to the account I was having trouble with, deleted the bundle, re-downloaded and it worked perfectly. Not sure what the issue there would have been. Sorry to have wasted cycles, thanks for the swift response! Keep up the amazing work. I truly believe this project to be the future of the Internet.
