### ISSUE TITLE
CryptMessage - decrypt error handling

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#696]
I am sometimes getting error notification when decrypting cryptMessage messages :
<pre>
Internal error: AttributeError: 'NoneType' object has no attribute 'decode'
UiWebsocket.py line 99 > UiWebsocket.py line 184 > CryptMessagePlugin.py line 103
</pre>

The problem is mismatch between message and private key after switching cert and reading old messages sent to the old cert. 

Is there any way to catch error in javascript instead of getting error notification in the UI?

**Comment by HelloZeroNet** [comment]
This error happens if the key parameter is not supplied at all (or null passed), so eg.: Page.cmd("aesDecrypt", ["iv", "enryptedtext", null])
Please check the Dev console's network tab websocket entry to see if correct number of paramters sent.

**Comment by jaros1** [comment]
You are right. First step in decryption, eciesDecrypt, returns null when mismatch between encryption in incoming message and private key. No problem. Closing the issue
