### ISSUE TITLE
site publish problem...

### ISSUE THREAD

**Issue by siyuandong** [HelloZeroNet/ZeroNet#704]
after site publish, seems html/js are published.. but db not... 

Help please.
```
- Loading site...
- Creating FileServer....
TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 154 > socket.py line 342
FileServer StreamServer bind error, must be running already: [Errno 98] Address already in use: ('', 15441)
- Sending siteReload
- {'to': 1, 'cmd': 'response', 'ok': 'Reloaded'}
- Sending sitePublish
- {'to': 2, 'cmd': 'response', 'ok': 'Successfuly published to 3 peers'}
- Done.
```

**Comment by HelloZeroNet** [comment]
The db file never gets published, it's locally generated from the .json files

**Comment by siyuandong** [comment]
thx for replying.... 
the problem is that I have 4 registerd merge pages.  I can see them on /data/user/xxxxxxxxx...... now sth went wrong.. I delete 2 of them.  and  dbRebuild. and restart zeronet and publish the site...

On my own local site they disappeard.. but on some peers not. bit.no either.... 

what can I do to make the changes published. 


THX A LOT!!!!

**Comment by siyuandong** [comment]
https://bit.no.com:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/

this is my site.. the content are deleted locally..  but now syn... how can I get them syn...

**Comment by HelloZeroNet** [comment]
To delete user content you have to remove the unwanted content from user's data.json file, then sign and publish it.

**Comment by siyuandong** [comment]
yes. that is what I did. I even delete the user's whole directory which include .json files... but the peers could not get update.... I edit the index.html too and it could get updated...

**Comment by siyuandong** [comment]
could be somthing to do with my router... fileserver checking port 15441... and 15441 is not open..

fileServer Internet offline.

**Comment by HelloZeroNet** [comment]
Deleting the files will not work, you need to edit the data.json file, then sign and publish data/users/useraddress/content.json

or alternatively:
add the user's address and the when timestamp you deleted it to data/users/content.json, example for that:
http://127.0.0.1:43110/talk.zeronetwork.bit/data/users/content.json
In that way the clients will delete the user's directory that is defined here

**Comment by siyuandong** [comment]
yeah... I did the first suggestion  sign and publish data/users/useraddress/content.json.... it works.

Thank you so much. very helpful!
