### ISSUE TITLE
how to deal `window.URL.createObjectURL(new window.MediaSource())` host = null？

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#707]
hi， I'm  [cinema online](http://127.0.0.1:43110/1FdEWyVHmhbwRZ3u3LmkVGQ9ei7HTcdzU7/) owner, I want to add gtihub.com/bilibili/flv.js to my site to play Flv video , but when flv.js execute `window.URL.createObjectURL(new window.MediaSource())`, it get URL is` "blob:null/3fa58623-5096-40fe-859d-1147135b2305"` , it can't be load, how to deal it? thanks~

**Comment by HelloZeroNet** [comment]
It's the sandboxed iframe's limitation and I don't know any workaround for it.

**Comment by cxgreat2014** [comment]
is it a bug with chrome?

**Comment by HelloZeroNet** [comment]
I'm not sure if it's bug or a feature, there is lots of result if you search for "blob:null sandboxed iframe" on google

**Comment by cxgreat2014** [comment]
I tried to add allow-same-origin to zeronet iframe, and `window.URL.createObjectURL(new window.MediaSource())` work. But..it seems like it will let zeronet to be unsafe😂

**Comment by cxgreat2014** [comment]
could zeronet add some video support? if not we are too hard to build a P2P video site in zeronet

**Comment by HelloZeroNet** [comment]
You mean big file support by "video support"?

**Comment by cxgreat2014** [comment]
no, video in iframe can't change to full screen, now we only can change the video screen size to window size. I think maybe we can add a video support API for media file

**Comment by HelloZeroNet** [comment]
I can't change the sandbox limitations, but adding a new "wrapperRequestFullscreen" could be possible.

**Comment by cxgreat2014** [comment]
Thanks a lot

**Comment by HelloZeroNet** [comment]
`Page.cmd("wrapperRequestFullscreen")` added in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/5103879471176fced494dc70d35e8384275f787e

**Comment by cxgreat2014** [comment]
thank you very much :smile:
