### ISSUE TITLE
I have use up my 3rd id zerome hub space just now..

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#709]
my 3rd zeroid join green hub, and 48k user space only supports my 3days...
I'm creating my 4th zeroid now, but..how to deal this problem

**Comment by HelloZeroNet** [comment]
The possible solutions are:
 - If you run out of limit delete the oldest comment you made (automatize this)
 - Create your own hub and increase the limit for yourself

**Comment by cxgreat2014** [comment]
okay. I'm join kha's 500MB hub
