### ISSUE TITLE
Faster page load times

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#71]
At the moment at every click: Load wrapper -> Wrapper creates iframe and loads page html -> Init websocket connection -> Load page details using websocket api

It could be much faster by sharing the wrapper and the websocket connection between and only change the inner frame html.

Need a wrapper api command that allows change the url of the page.

**Comment by EdenSG** [comment]
`window.history.pushState` can do what you're looking to do (I think) — maybe look it up. Here's a little [demo](https://jsfiddle.net/fJ9wq/) of how it could work.

**Comment by shakna-israel** [comment]
Probably worth noting that ```window.history.pushState``` is a HTML5 spec, so you don't need the heaviness of the jQuery library for it to work. However, it is only supported in fairly modern browsers.

[History.js](https://github.com/browserstate/history.js) is a shim that'll let you use it, with a fallback to a HTML4 hash API.

**Comment by HelloZeroNet** [comment]
The overhead is much smaller since the http caching enabled on js and css files. Pushstate support can be a solution, but then its needs application level support for this feature.

Probably related problem that needs to be fixed:
If you scroll down on a page (for example zerotalk topic listing) then click on a link and then go back to previous page then chrome and ie scrolls to page top. (it worked on chrome some months ago, but they broken it :( )

Possible workaround for the problem: Store (cookie or localstorage) the scroll position before the page onload then load it back on next page load.

**Comment by Plasmmer** [comment]
@HelloZeroNet, is it updated?

**Comment by HelloZeroNet** [comment]
Probably we don't need it.

**Comment by grez911** [comment]
> Probably we don't need it.

@HelloZeroNet, why? If zites will work without page refreshes it will be nice.

**Comment by HelloZeroNet** [comment]
It would require changes in site's source code (call API instead of simple `<a href="...`) and they can archive the same with wrapperPop/Pushstate API calls.
Also with js/css caching enabled the wrapper loading speed dramatically increased.
