### ISSUE TITLE
I think zeronet should add a ballon tips when receive new message from zeromail

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#710]
like bitmessage
![image](https://cloud.githubusercontent.com/assets/15062548/21302026/00170196-c5ee-11e6-8597-8fc1d77fcc09.png)

**Comment by iShift** [comment]
Browser notification (HTML5 notification API) is better

**Comment by cxgreat2014** [comment]
@iShift but Browser notification (HTML5 notification API)  need user keep a page run in background

**Comment by HelloZeroNet** [comment]
ZeroNet itself does not execute anything downloaded from the network, so it's not possible to display notifications if the site is not running in the browser.

**Comment by cxgreat2014** [comment]
okay...thanks~
