### ISSUE TITLE
[3566:3600:1222/102821:ERROR:socket_stream.cc(208)] Closing stream with result -100

### ISSUE THREAD

**Issue by photonxp** [HelloZeroNet/ZeroNet#715]
Every time I start my ZeroNet 0.5.1 on my Unbuntu 12.04, I can see this error message repeated in the console after running ZeroNet for a few minutes.

**Comment by HelloZeroNet** [comment]
This error comes from chrome browser.
https://wyldeplayground.net/terminal-errors-concerning-netflix-in-google-chrome/

If you want you can disable the browser window opening by replacing start.py with zeronet.py in zeronet.sh
