### ISSUE TITLE
When Tor is blocked by goverment it doesnt work (Solved)

### ISSUE THREAD

**Issue by neosinan** [HelloZeroNet/ZeroNet#717]
When Tor is blocked by goverment it doesnt work, It cant connect to any other user even If tor's settings is changed to go around goverment block.

**Comment by unsystemizer** [comment]
Maybe you should contact your government about this issue. Or the Tor Project.
How is ZeroNet supposed to make Tor work differently?

**Comment by photonxp** [comment]
Try to append "--tor disable" to the start command as long as Zeronet is not blocked

**Comment by HelloZeroNet** [comment]
ZeroNet does not include [Tor pluggable transports yet](https://www.torproject.org/docs/pluggable-transports.html.en). The easiest way to do that is starting the Tor browser, configuring the pluggable transports, then modifing ZeroNet's config to use the browser's tor client by starting it with `--tor_controller 127.0.0.1:9151 --tor_proxy 127.0.0.1:9150` or adding it to zeronet.conf
```
[global]
tor_controller = 127.0.0.1:9151
tor_proxy = 127.0.0.1:9150
```

**Comment by neosinan** [comment]
thanks to both of you. Both suggestion fixed my problem.
