### ISSUE TITLE
Why 127.0.0.1:43110 ?

### ISSUE THREAD

**Issue by khao** [HelloZeroNet/ZeroNet#719]
Why 127.0.0.1:43110 , when there is whole /8 network available? Why use IP address at all, while /etc/hosts is available too? Something like: http://zeronet/ will look much better, and it's far more user-friendly.

**Comment by HelloZeroNet** [comment]
- You can bind to 127.0.0.2 if you want by `--ui_ip 127.0.0.2`
- Editing host file require root/admin permissions.
