### ISSUE TITLE
Reject contents in distant future

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#722]
If a user publishes the content that the `modified` value is in distant future (Wrong system time or Intentionally modifying), this content will be at the top of the list for a long time such as ZeroTalk or ZeroMe.
The worse thing is, if the user try to fix the error, they will find that is difficult because the `modified` value will be synchronized back to the wrong time.

**Comment by HelloZeroNet** [comment]
It's already there (allows +1 day from local time): https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Content/ContentManager.py#L758

**Comment by l5h5t7** [comment]
But users can still use this way to stick posts to the post for a day.
![stick](https://cloud.githubusercontent.com/assets/18724949/21522018/d6e141d2-cd3c-11e6-9c60-be94d6c84bac.png)
I have been seeing this post for hours. consider reducing to a shorter time?

**Comment by HelloZeroNet** [comment]
This does not protect from post timestamp modifications.
The future post filtering have to be implemented in every site's js code independently.
