### ISSUE TITLE
FileServer Trying to open port using UpnpPunch... - Unhandled exception

### ISSUE THREAD

**Issue by kasv** [HelloZeroNet/ZeroNet#725]
$ pwd
~/downloads/ZeroBundle/ZeroNet/src/util

$ ~/downloads/ZeroBundle/Python/python ./UpnpPunch.py
Opening port...
DEBUG:root:Trying to open port 15443.
DEBUG:root:Found local ips: ['192.168.0.8']
DEBUG:root:Trying using local ip: 192.168.0.8
Traceback (most recent call last):
  File "./UpnpPunch.py", line 342, in <module>
    print ask_to_open_port(15443, "ZeroNet", retries=3, protos=["TCP"])
  File "./UpnpPunch.py", line 320, in ask_to_open_port
    protos=protos)
  File "./UpnpPunch.py", line 299, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "./UpnpPunch.py", line 274, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "./UpnpPunch.py", line 258, in _collect_idg_data
    _retrieve_igd_profile(idg_data['location']))
  File "./UpnpPunch.py", line 104, in _parse_igd_profile
    dom = parseString(profile_xml)
  File "/home/kasv/downloads/ZeroBundle/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/home/kasv/downloads/ZeroBundle/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/home/kasv/downloads/ZeroBundle/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 442

See attachment
[answer.xml.txt](https://github.com/HelloZeroNet/ZeroNet/files/677114/answer.xml.txt)

**Comment by HelloZeroNet** [comment]
cc @sirMackk

**Comment by sirMackk** [comment]
Super big thanks for attaching the SOAP response @kasv . I'll look into this in the next few days.

**Comment by sirMackk** [comment]
Hi @kasv , I think I was able to fix the issue. Before I create a pull request, could you test the fix out? You can either clone my [patched branch](https://github.com/sirMackk/ZeroNet/tree/unicode_fix) and run Zeronet as you normally would _or_ you can download the [python script from here](https://github.com/sirMackk/ZeroNet/blob/unicode_fix/src/util/UpnpPunch.py) and run it with `python UpnpPunch.py` (all it does is opens port 15443 port and then closes it). 

In case you still get an error, the script will create a file called `upnp_error.txt`, which will help further troubleshooting. If there's no error, I'll submit a PR and we can close this one out :).

**Comment by MuxZeroNet** [comment]
@kasv More information needed.

**Comment by kasv** [comment]
Hi @sirMackk, Your version utf8 python script result:
$ ../Python/python ./UpnpPunch_utf8.py 
Opening port...
DEBUG:root:Trying to open port 15443.
DEBUG:root:Found local ips: ['192.168.0.8']
DEBUG:root:Trying using local ip: 192.168.0.8
Traceback (most recent call last):
  File "./UpnpPunch_utf8.py", line 346, in <module>
    print ask_to_open_port(15443, "ZeroNet", retries=3, protos=["TCP"])
  File "./UpnpPunch_utf8.py", line 324, in ask_to_open_port
    protos=protos)
  File "./UpnpPunch_utf8.py", line 303, in _communicate_with_igd
    _orchestrate_soap_request(local_ip, port, fn, desc, protos)
  File "./UpnpPunch_utf8.py", line 278, in _orchestrate_soap_request
    idg_data = _collect_idg_data(ip)
  File "./UpnpPunch_utf8.py", line 262, in _collect_idg_data
    _retrieve_igd_profile(idg_data['location']))
  File "./UpnpPunch_utf8.py", line 86, in _retrieve_igd_profile
    return urllib2.urlopen(url.geturl(), timeout=5).read().decode('utf-8')
  File "/home/kasv/Загрузки/ZeroBundle/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcd in position 465: invalid continuation byte

My version (patched, [UpnpPunch.py.txt](https://github.com/HelloZeroNet/ZeroNet/files/701766/UpnpPunch.py.txt)) result:
$ ../Python/python ./UpnpPunch.py 
Opening port...
DEBUG:root:Trying to open port 15443.
DEBUG:root:Found local ips: ['192.168.0.8']
DEBUG:root:Trying using local ip: 192.168.0.8
DEBUG:root:Sending UPnP request to 192.168.0.1:1024...
DEBUG:root:500
DEBUG:root:<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>718</errorCode><errorDescription>ConflictInMappingEntry</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
DEBUG:root:Upnp request using "192.168.0.8" failed: SOAP request error: 718 - ConflictInMappingEntry
DEBUG:root:Trying using local ip: 192.168.0.8
DEBUG:root:Sending UPnP request to 192.168.0.1:1024...
DEBUG:root:500
DEBUG:root:<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>718</errorCode><errorDescription>ConflictInMappingEntry</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
DEBUG:root:Upnp request using "192.168.0.8" failed: SOAP request error: 718 - ConflictInMappingEntry
DEBUG:root:Trying using local ip: 192.168.0.8
DEBUG:root:Sending UPnP request to 192.168.0.1:1024...
DEBUG:root:500
DEBUG:root:<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>718</errorCode><errorDescription>ConflictInMappingEntry</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
DEBUG:root:Upnp request using "192.168.0.8" failed: SOAP request error: 718 - ConflictInMappingEntry
Traceback (most recent call last):
  File "./UpnpPunch.py", line 351, in <module>
    print ask_to_open_port(port, desc, retries=3, protos=["TCP"])
  File "./UpnpPunch.py", line 328, in ask_to_open_port
    protos=protos)
  File "./UpnpPunch.py", line 319, in _communicate_with_igd
    port, retries))
__main__.UpnpError: Failed to communicate with igd using port 15443 on local machine after 3 tries.

**Comment by sirMackk** [comment]
Thanks @kasv , this is a big help in pinpointing the issue. I'll look into how to best make the code handle multiple encodings.

In the second case, it appears that your router is telling you that port 15433 is already open. This shouldnt be an error (500), which can be confusing. I'll see how this can be handled in a friendlier fashion.

**Comment by kasv** [comment]
I tried different ports and always get this error.

2017-01-12 16:37 GMT+03:00 sirMackk <notifications@github.com>:

**Comment by sirMackk** [comment]
Does it even open/close the ports at all?

I know that UPnP is horribly implemented and some routers will ignore commands even if they have UPnP enabled or some will even send a "200 OK" reply ("yes, I opened the port!") without actually opening the port :/.

You can confirm this if you use `miniupnpc` to perform the same operation (`apt-get install miniupnpc` if you're on ubuntu).

**Comment by kasv** [comment]
Does not work(
The test script (taken from [http://nullege.com/codes/show/src@p@y@pyethereum-HEAD@pyethereum@tcpserver.py/33/miniupnpc](http://nullege.com/codes/show/src@p@y@pyethereum-HEAD@pyethereum@tcpserver.py/33/miniupnpc)) result:
INFO:root:TCP server started 192.168.0.8:15554
DEBUG:root:Setting UPNP
DEBUG:root:1 UPNP device(s) detected
DEBUG:root:external ip: 10.0.50.131
DEBUG:root:status: ('Connected', 866834, 'ERROR_NONE'), connection type: IP_Routed
DEBUG:root:trying to redirect 10.0.50.131 port 15554 TCP => 192.168.0.8 port 15554 TCP
DEBUG:root:upnp failed: ConflictInMappingEntry
INFO:root:my public address is b'178.155.5.26':15554
[tcpserver.py.txt](https://github.com/HelloZeroNet/ZeroNet/files/701979/tcpserver.py.txt)

**Comment by sirMackk** [comment]
Hey @kasv , I've been looking into this and it appears that short of switching out the router's firmware to something like openwrt/dd-wrt, there's not much someone can do to get their router to talk upnp :/.

@HelloZeroNet Quick update here - I'm still trying to figure out how to handle this charset issue without introducing more dependencies - basically, how to detect the charset from a bunch of bytes and use that to decode it into a string fit for an xml parser. The updates from #757 makes things better, but I wouldn't consider it a long-term solution.

**Comment by USER0308** [comment]
I suffer from the same problem on my Ubuntu 16.04. I check your source code of the 'UpnpPunch.py',and I run your debug version of the 'UpnpPunch.py' above. According to the results and some informations I get from the Internet, I want to know whether it is necessary for my router to start the upnp mapping service,transporting the data got from Port 15443 to the Port 43110? Is it possible that I face this problem because of the lack of of the control over the router? If I got the control and start the upnp service manually and set the proper parameters, will I successfully install my zeronet? I am waiting for your answer,any words would be appreciated.

**Comment by HelloZeroNet** [comment]
You need to forward port 15441 to your local ip, but zeronet should also work fine without any opened port.

**Comment by USER0308** [comment]
OK, it actually works today, though continuously telling me that 
"[12:47:16] Ui.UiServer Web interface: http://127.0.0.1:43110/
[12:47:16] Ui.UiServer --------------------------------------
[12:47:17] FileServer Checking port 15441 using portchecker.co...
[12:47:23] FileServer [BAD :(] Port closed: Port 15441 is closed.
[12:47:23] FileServer Trying to open port using UpnpPunch...
[12:47:38] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 74 > UpnpPunch.py line 324 > UpnpPunch.py line 315
".
Thanks a lot. I love this project:).
