### ISSUE TITLE
if enable UiPassword, it seems that will blocked some source

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#727]
http://127.0.0.1:43110/1CiDoBP8RiWziqiBGEd8tQMy66A6fmnw2V/big/docs/about/demos/
disable:
![image](https://cloud.githubusercontent.com/assets/15062548/21575744/1b8f6b80-cf52-11e6-8e3a-707fc707ca76.png)
enable:
![image](https://cloud.githubusercontent.com/assets/15062548/21575746/401c6228-cf52-11e6-9dd3-463a1545b6be.png)
![image](https://cloud.githubusercontent.com/assets/15062548/21575747/4e508c34-cf52-11e6-838a-a78680c49234.png)
seems like uipassword bug..

**Comment by ysc3839** [comment]
Off topic: Please improve your English grammar.

**Comment by HelloZeroNet** [comment]
this limitation is not in zeronet, but in the browser, so i cant modify it, but if you use the same way to load the resources as other zeronet sites, then it should be fine
