### ISSUE TITLE
[feature] Would it be useful to have a "Demanded Difficulty" as what bitmessage does?

### ISSUE THREAD

**Issue by photonxp** [HelloZeroNet/ZeroNet#729]
For bitmessage, It's used for reducing the impact of spams or excessive contents
[Pic of Demanded Difficulty on Bitmessage](http://www.image-share.com/ijpg-3409-191.html)

And it would be convenient if users, web admins, developers or third parties could adjust this parameter easily. So, would ZeroNet need this kind of function sooner or later?

**Comment by HelloZeroNet** [comment]
I don't thing proof of work is a good solution to protect against spam: For example if we require 1 minute CPU time POW before to submitting new comment a spammer (really annoying) with a decent GPU would still able to send 100 message / minute.
