### ISSUE TITLE
Lazy sql updates

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#73]
Currently the sqlite database is updated as the new file is written to the hdd.

Maybe it would be better to read the files when its required by the sql query:
- data/user/data.json updated
- The storage layer marks the data/user/data.json as updated
- File written to disk, no sql connection made

When user tries to list the topics:
- Storage layer loads the files to sql that marked as updated
- Reset the files updated status
- Run the query on updated database

Pros:
- Lot faster data process by batching updates using BEGIN / COMMIT
- Less CPU usage If you only "seed" the site
- If the file updated more than once then only have to load 1 times

Cons:
- Displaying the data could be slower if you have many pending updated files because it has to parse the updated files before display any result
- Has to store somewhere the pending database updates

**Comment by Plasmmer** [comment]
@HelloZeroNet, was this already been implemented?

**Comment by HelloZeroNet** [comment]
nope, probably we don't need it.

**Comment by Plasmmer** [comment]
Moved to: https://github.com/ZeroNetJS/zeronet-js/issues/49.
