### ISSUE TITLE
[question] Is it normal to have repeated "Wrapper key not found" after starting the zeronet server

### ISSUE THREAD

**Issue by photonxp** [HelloZeroNet/ZeroNet#730]
In the console, something like:
[17:35:11] Ui.UiServer Wrapper key not found: xxxxxx
[17:35:11] Ui.UiServer Wrapper key not found: aaaaaa
... ...

**Comment by HelloZeroNet** [comment]
It usually happens if you someone has a site in the browser that in no longer in the client
