### ISSUE TITLE
Suggestion:Why don't you keep some native javascript libraries?

### ISSUE THREAD

**Issue by jakop345** [HelloZeroNet/ZeroNet#732]

**Comment by l5h5t7** [comment]
You can use [ZeroCDN](http://127.0.0.1:43110/1AMh6MG4K59ki1dPXX1PrgzeeqkMmZ1YKm/).

**Comment by HelloZeroNet** [comment]
Please explain your question

**Comment by jakop345** [comment]
I mean instead of loading common javascript libraries from site we visit wouldn't it be faster if we use local stored once instead .

**Comment by HelloZeroNet** [comment]
The storage and the bw used by js libs are negligible and different sites requires different version libs, so it would be a mess.
