### ISSUE TITLE
Zeronet fails to start when site content.json is empty

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#736]
This can happen after ungraceful system shutdown or disk full.
```
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Failures in individual zerosites shouldn't affect zeronet as a whole. Exceptions should be caught on per-site level.

Also, zeronet should regularly create backups of content.json. For example, every 10 minutes in a separate thread to prevent them being affected by similar conditions.

If content.json is missing and there is no backup, zeronet should reload this site, because it knows the site name and can do this any time.

**Comment by HelloZeroNet** [comment]
Fixed in Rev1797: It will skip broken sites on startup and use crash-safe writing for root content.json file.
