### ISSUE TITLE
signed git tags

### ISSUE THREAD

**Issue by adrelanos** [HelloZeroNet/ZeroNet#738]
Can you please OpenPGP sign your following git tags? It's also useful in case github [gets hacked](http://www.extremetech.com/computing/120981-github-hacked-millions-of-projects-at-risk-of-being-modified-or-deleted) again in case [SSL CA's](https://en.wikipedia.org/wiki/DigiNotar) get [hacked](http://www.scmagazine.com/two-more-comodo-resellers-owned-in-ssl-hack/article/199620/) again.

With git it requires minimal effort.

In my ~/.gitconfig I use.

```
[user]
         name = adrelanos
         email = adrelanos at riseup dot net
         signingkey = 713AAEEF
```

After setting that up you can just use.

```
git tag -s 1.9
```

Users who wish can verify it with.

```
git tag -v 1.9
```

I am using it all the time. If there are any questions about this git feature / feature request, I am happy to answer.

**Comment by MuxZeroNet** [comment]
Related: #540 "Please sign releases"

`--updatesite` argument https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Config.py#L149

**Comment by HelloZeroNet** [comment]
Added signing to git commits: https://github.com/HelloZeroNet/ZeroNet/commit/901478475fb15a910d3c99ccb161730b4e84ca25

**Comment by adrelanos** [comment]
It's not on keyservers.

Where can I find the gpg public key?

```
gpg --recv-keys 9557210F5E536D3D
```
```
gpg: requesting key 5E536D3D from hkp server keys.gnupg.net
gpgkeys: key 9557210F5E536D3D not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by HelloZeroNet** [comment]
Just, sent it, please check again

**Comment by adrelanos** [comment]
The signing key mentioned here is no longer up to date. See:
`GPG signing 4096 bit keys`
https://github.com/HelloZeroNet/ZeroNet/issues/759
