### ISSUE TITLE
ZeroNet throws an error notification when get auth cert

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#747]
![1481559181](https://cloud.githubusercontent.com/assets/18724949/21735486/2c3cc178-d4a5-11e6-8405-2ce5fc1b45e9.jpg)
KaffieID has the same problem. But it seems that both ZeroID and KaffieID can get an auth cert normally.
See the post: http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/12h51ug6CcntU2aiBjhP8Ns2e5VypbWWtv/1MpUdwe28gwynzoKg9ziFCRWcQK2FqNunb/1481559181

**Comment by HelloZeroNet** [comment]
Thanks, fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/bea212a8d1fbf314b5a40e8828d17ab9d0bec27a
