### ISSUE TITLE
port TorManager.py to python-stem

### ISSUE THREAD

**Issue by adrelanos** [HelloZeroNet/ZeroNet#758]
Please consider porting [src/Tor/TorManager.py](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Tor/TorManager.py) to [python-stem](https://stem.torproject.org/). Stem is also available packages.debian.org package repository.

For example [onionshare](https://github.com/micahflee/onionshare) is based on python-stem. It is an torproject officially supported python implementation and actively maintained. It's upstream author is super responsive. stem can do stuff like authentication and there is also no need to parse Tor version. With stem it's as simple as `controller.get_version()`.

**Comment by MuxZeroNet** [comment]
Let's merge #834 to close this issue. @shortcutme What do you think?

**Comment by MuxZeroNet** [comment]
The pull request has been merged!
