### ISSUE TITLE
GPG signing 4096 bit keys

### ISSUE THREAD

**Issue by HulaHoopWhonix** [HelloZeroNet/ZeroNet#759]
Please upgrade your GPG signing key to 4096 bits which is considered standard. 2048 is no longer sufficient.

**Comment by MuxZeroNet** [comment]
4096 is the recommendation of GitHub.

**Comment by HelloZeroNet** [comment]
Thanks, changed, new key:
(1)     Tamas Kocsis (4096) <tamas@zeronet.io>
          4096 bit RSA key CB9613AE, created: 2017-01-15, expires: 2022-01-14

**Comment by adrelanos** [comment]
Posting the full key fingerprint here for verification purposes.

> `960F FF2D 6C14 5AA6 13E8  491B 5B63 BAE6 CB96 13AE`

```
gpg --keyid-format long --fingerprint tamas@zeronet.io
```

```
pub   rsa4096/5B63BAE6CB9613AE 2017-01-15 [SC] [expires: 2022-01-14]
      Key fingerprint = 960F FF2D 6C14 5AA6 13E8  491B 5B63 BAE6 CB96 13AE
uid                 [ unknown] Tamas Kocsis (4096) <tamas@zeronet.io>
sub   rsa4096/A77A8F3444323B73 2017-01-15 [E] [expires: 2022-01-14]
```

That's how I have seen it. Perhaps someone else can confirm it.

**Comment by HulaHoopWhonix** [comment]
@adrelanos

Confirmed

user@host:~$ gpg --keyid-format long --fingerprint tamas@zeronet.io
pub   4096R/5B63BAE6CB9613AE 2017-01-15 [expires: 2022-01-14]
      Key fingerprint = 960F FF2D 6C14 5AA6 13E8  491B 5B63 BAE6 CB96 13AE
uid               [ unknown] Tamas Kocsis (4096) <tamas@zeronet.io>
sub   4096R/A77A8F3444323B73 2017-01-15 [expires: 2022-01-14]

**Comment by MuxZeroNet** [comment]
Confirmed. Fingerprint = `960F FF2D 6C14 5AA6 13E8  491B 5B63 BAE6 CB96 13AE`

```bash
$ gpg2 --export "960F FF2D 6C14 5AA6 13E8  491B 5B63 BAE6 CB96 13AE" | sha256sum
1e46c22a0ab4e766637b1676b9394ac3465eb094b8deb4daeb09deb06cfa04be  -
```
