### ISSUE TITLE
Video Streaming Capability

### ISSUE THREAD

**Issue by HulaHoopWhonix** [HelloZeroNet/ZeroNet#760]
An interesting application ZeroNet could be designed to do is enabling of video streaming as a YouTube replacement. Similar to torrent clients - such a feature would be possible if you add the ability to download files in sequential order including its first and last parts so it can be played while its fetched.

**Comment by MuxZeroNet** [comment]
Torrent and big file support relevant issues: #7 #145 
At ZeroNet application layer: [ZeroMux](https://github.com/MuxZeroNet/ZeroMux) (WIP)

**Comment by chptx** [comment]
is it possible to add live video streaming support to ZeroNet?  https://github.com/gitsummore/nile.js

**Comment by DaniellMesquita** [comment]
@chptx
Nile.js requires HTTPS. Could it be achieved by ZeroNet?

**Comment by DaniellMesquita** [comment]
@MuxZeroNet
Thanks, now big file support is implemented.

**Comment by purplesyringa** [comment]
I think the possibility has been proved by StreamZ. Can this be closed? @HelloZeroNet

**Comment by HelloZeroNet** [comment]
Streaming video files with big file support is possible.

Still no real-time streaming (eg. webcam), but it's requires different kind of p2p protocol, so it's out of the scope.

**Comment by purplesyringa** [comment]
> but it's requires different kind of p2p protocol, so it's out of the scope.

PeerMessage does support livestreaming though.
