### ISSUE TITLE
@cmd 'optionalLimitStats',[],(Stats)->console.log Stats log：Forbidden

### ISSUE THREAD

**Issue by cxgreat2014** [HelloZeroNet/ZeroNet#766]
I 'm trying to get optionalLimitStats to auto set seed file list, but..
```
  onOpenWebsocket: (e) =>
    @cmd 'optionalLimitStats',[],(Stats)->
      console.log Stats
```
log: Forbidden
???should I requires ADMIN permission？

**Comment by HelloZeroNet** [comment]
To list optional files: 
`Page.cmd("optionalFileList", "1BLueGvui1GdbtsjcKqCf4F67uKfritG49")`

To list current auto-seet.
`Page.cmd("optionalHelpList", "1BLueGvui1GdbtsjcKqCf4F67uKfritG49")`

Add new:
`Page.cmd("optionalHelpList", "data/1H3aufYewimybeycENBJaLKt41uyRE9iEn", "Anyuser's files', "1BLueGvui1GdbtsjcKqCf4F67uKfritG49")`

via https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#plugin-optionalmanager

**Comment by cxgreat2014** [comment]
um。。I want to make a class to auto seed option files，If user's disk space not enough, it will seed recently hot file, else will seed files with the times of the site has been visited by users * 0.3,.....um...My English not well..show you the code
```
    if Math.random() < 0.3
        @seedFiles()

    seedFiles: ()->
        if user.freeDiskSpace < '1000M'
            //TODO: SEED HOT FILE
        @cmd 'optionalFileList',['','',999],(row)->
            for x in row
                if x.peer > 5 || x.is_downloaded
                    continue
                else
                    @cmd 'optionalFilePin',[x.inner_path],()->
                        return
                     return
```

**Comment by HelloZeroNet** [comment]
it should be individual applications to serve optional files, so it's not recommended to add it by random number. 
If sites going to abouse this feature then probably it will turned into admin-site only or require personal confirmation.
