### ISSUE TITLE
Strange free space in sidebar

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#769]
![fs](https://cloud.githubusercontent.com/assets/18724949/21950295/5d68d0d6-da34-11e6-88be-1845816b913c.png)
Open any one site (e.g.: [ZeroHello](http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/)), we can see the value of free space is most more than site_limit - total_used. This is a bug?

**Comment by l5h5t7** [comment]
Another user report their sidebar on Android displays "-1MB": http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1KNmG5rJUGhgUJGFbLkv2B5isaqu9PrZqi/19qBszkhiRjHLP4Z1eeZXS6HztiCD7yiBx/1484354950

**Comment by HelloZeroNet** [comment]
it displays free space on your hdd, it's possible that function is not implemented in android python

**Comment by pahakalle** [comment]
i thinks its the *comma* that confuses people of the actual size (and showing it in megabytes), making it seem smaller that it actually is, like in the upper picture it would seem like you have 32 megabytes of free space, not 32 000
