### ISSUE TITLE
lose optional files when copy cert to other devices

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#771]
When a user upload a optional file, the file is pinned. So if the user publish new contents, old optional files won't lose. But if a user copy their cert to a new device, their old optional files won't download and pin automatically, then if the user submit new posts, `content.json` will be resigned and the new `content.json` doesn't include the old optional files, the old optional files will be lost.
Many users' old images have been lost.

**Comment by l5h5t7** [comment]
Probably solution: 
- Don't remove existing optional files' record automatically in `content.json` while signing but display a notification.
- Always download own user content.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, Optional files no longer got removed on signing: https://github.com/HelloZeroNet/ZeroNet/commit/697e177e135eb7b9acfff53570df9119ec18c3bc
