### ISSUE TITLE
User defined content rules

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#776]
Site owners can define what user content to seed, and what not to seed. We hope we can define our own rules without having to contact the site owner.
```json
    "permissions": {
      "bad@zeroid.bit": false,
      "nofish@zeroid.bit": { "max_size": 100000 }
    }
```

**Comment by l5h5t7** [comment]
Allow user publish and follow public blacklists is batter.

**Comment by purplesyringa** [comment]
@HelloZeroNet We've now implemented blocklists, do you think this issue can be closed?
