### ISSUE TITLE
Grumpy

### ISSUE THREAD

**Issue by ShalokShalom** [HelloZeroNet/ZeroNet#778]
https://github.com/google/grumpy

https://opensource.googleblog.com/2017/01/grumpy-go-running-python.html

In order to improve the performance?

**Comment by HelloZeroNet** [comment]
Probably no: ZeroNet is single threaded and requires external modules (gevent, msgpack). Probably it could be possible to exchange gevent with go workers, but I don't think it's worth to do.

And 90% of the CPU power used by the database and the cryptography, but these parts already written in C.

**Comment by ShalokShalom** [comment]
Ah i see

**Comment by ShalokShalom** [comment]
And instead of a change to Python3?

**Comment by HelloZeroNet** [comment]
Python3 change is planned to this year, but I'm not sure if it improve the performance or not.

**Comment by ShalokShalom** [comment]
I dont talk about performance. It might be more easy to transition to Go with Grumpy?

**Comment by ShalokShalom** [comment]
I mean Go instead of Python3, since its more future proof?

**Comment by skwerlman** [comment]
how is go more future-proof than python3? i don't expect either will be obsoleted any time soon....

**Comment by HelloZeroNet** [comment]
I'm also not familiar with go, but I think it's safe to say, that it would be much harder to change it to go, than to python3.

Btw actually python is growing faster (in percentage), than go

![](https://zgab33vy595fw5zq-zippykid.netdna-ssl.com/wp-content/uploads/2017/09/growth_smaller_tags-1-1024x878.png)
via https://stackoverflow.blog/2017/05/09/introducing-stack-overflow-trends/

**Comment by ShalokShalom** [comment]
On Stackoverflow, yes. On TIOBE, not a single language in history ever raised up so quickly into the Top10.
To measure a language based on how many people have troubles with it, seems questionable to me. 
Since you both seem to prefer Python, is it probably the saver choice.

**Comment by HelloZeroNet** [comment]
A quick rise also not a good measure of "future proofness" as the new languages tend to became fashionable and they could drop quickly as the hype disappears (see: ruby/ruby-on-rails)

btw from: https://www.tiobe.com/tiobe-index/

Jan 2018 | Jan 2017 | Change | Programming Language | Ratings | Change
-- | -- | -- | -- | -- | --
4 | 5 |   | Python | 4.678% | +1.21%
19 | 13 |   | Go | 1.569% | -0.76%

**Comment by ShalokShalom** [comment]
Well, that might be, while Ruby was/is very similar to Python and performs less speedy.
Go has no competitor. Much fun

**Comment by HelloZeroNet** [comment]
Swift, C#, Kotlin, Rust are all competitors for Go in many levels.

**Comment by ShalokShalom** [comment]
They all are more verbose, less newbie friendly and/or offer not such a nice and convenient way to (cross-)deploy with one single command and without any makefile. 

As said, if it works for you, is fine. 

And I simply hint you about the benefits of a particular language, I do not even use Go on my own. 
I simply keep my eyes open, since such decisions grow on us and with that on our projects. 

Much success, this is really a great project, which is why I am commenting here. :)

**Comment by ShalokShalom** [comment]
They all are more complex, less newbie friendly and/or offer not such a nice and convenient way to (cross-)deploy with one single command and without any makefile. 

As said, if it works for you, is fine. 

And I simply hint you about the benefits of a particular language, I do not even use Go on my own. 
I simply keep my eyes open, since such decisions grow on us and with that on our projects. 

Much success, this is really a great project, which is why I am commenting here. :)
