### ISSUE TITLE
Youtube video about ZeroNet

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#78]
Create a demonstartion youtube video about ZeroNet.

**Comment by EdenSG** [comment]
I might be able to do some graphics for a video, I'd just need content. Ideas?

**Comment by HelloZeroNet** [comment]
I think a video that demonstrates ZeroNet working would be a good start:
- Starting from clean install
- Doubleclick on zeronet.cmd
- Browser starts, loads ZeroHello
- Load ZeroBoard, submit a message
- Load ZeroBlog, Register username using ZeroID, submit a message
- Load ZeroTalk, click on some topic (the registration process will be changed to ZeroID based, so registration can be skipped here)

**Comment by HelloZeroNet** [comment]
A video about how zeronet work also would be nice, but it needs more work.

For graphics you can use https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/edit

**Comment by EdenSG** [comment]
I likely won't be able to do much until a week or so from now, but I'll play around with some ideas. Do you want tutorials for installation, or is it more of just a demonstration (look at this new cool thing)?

I can certainly use the presentation for graphics/theme, thanks!

**Comment by HelloZeroNet** [comment]
It could also include the downloading ZeroBundle.zip from zeronet.io > rigtclick extract here > start zeronet.cmd process. Probably needs some editing/speedup at extracting because it has 3500+ files files and its boring to watch the progress bar. (Later it can be improved by creating a more compact python runtime using [py2exe](http://www.py2exe.org/) or removing unnecessary files, eg. testing or tcl/tk)

**Comment by EdenSG** [comment]
The problem is that I don't actually have Windows — I'm a mac/linux user. I was thinking I'd just use mockups so that I'm not limited by resolution (I can zoom in on single button or whatever) to show the general process, but there could also be walkthrough videos for specific OSes later on. I was thinking it would be more of an introduction to *what* ZeroNet is than instructions on how to use it.

**Comment by EdenSG** [comment]
Alright, I've got some time on my hands now, sorry for the long wait.

You're looking for a video demonstrating ZeroNet being installed and working — is a screencast fine, or would something a little nicer-looking (UI kits and AE) be preferable?

**Comment by HelloZeroNet** [comment]
I think both would be nice, probably it would be easier to start with a simple screencast

**Comment by EdenSG** [comment]
Alright. I'm on OS X at the moment and don't have access to a windows machine — do you want me to go ahead with the more complex installation, or should I wait on #133?

**Comment by HelloZeroNet** [comment]
I think you can skip the platform-specific installation method for now and start from executing start.py

**Comment by EdenSG** [comment]
Alright, here's a [first take](https://youtu.be/q7HJ0jDe8-E). I included `git clone`ing the repo, `cd`ing into the folder, and starting zeronet, and then browsing a little. This is rough and in no way complete — I'll want to add music, a voiceover, etc. Thoughts?

**Comment by HelloZeroNet** [comment]
It looks nice, probably it would be beter with a bit larger browser window and starting with clean install (also showing the download process)

**Comment by EdenSG** [comment]
> download process

From zeronet.io, or just from the gh page?

**Comment by HelloZeroNet** [comment]
I meant the ZeroHello (and other zeronet pages) downloading process (rotating square).

**Comment by EdenSG** [comment]
Oh, ok.

**Comment by EdenSG** [comment]
[Another attempt](https://youtu.be/Ke--PTR105M).

**Comment by HelloZeroNet** [comment]
Yeah, its better, but the layout looks broken :( I really need to find a mac to fix/reproduce the problems.

**Comment by EdenSG** [comment]
What are the issues? Perhaps I could help test... Is it an issue of browser width, or is it a mac/windows inconsistency?

**Comment by HelloZeroNet** [comment]
The two main problems is with the zero button on top-right (has to find a fond that similar to Consolas on windows) and for some reasons the site names on zerohello are misaligned and not visible.

I try to find a way to access a mac machine this week.

**Comment by EdenSG** [comment]
Instead of using a single font, use a font stack: `font-family: Consolas, Monaco, monospace` — this should fix the first issue.

In ZeroHello.css, the `margin-bottom` of `h4` can be changed from 19px to 1.45rem, and the `bottom` of `.site .action` can be changed from 21px to 1.64rem. This seems to fixe the second issue, at least on my machine. The issue here was that I was zoomed out, and since most of the values were set in pixels, it didn't scale very well.

Also, would it be possible to add a 32x32px favicon image as well as the 16x16px one for HiDPI displays?

**Comment by HelloZeroNet** [comment]
Thanks for the tips, I will check them! 
I have contacted browserstack.org, maybe they can sponsor us with a osx safari live browser testing solution.

**Comment by HelloZeroNet** [comment]
hooray! browserstack.org going to sponsor us with an account, so it will allow to test zeronet on more platforms (eg osx safari) and makes also possible to write automated tests

**Comment by EdenSG** [comment]
Congrats! Let me know when think it's ready to be screencast again! 

One little tip: the misaligned site names only appeared when I zoomed out, so make sure to test different zoom levels as well.
