### ISSUE TITLE
content.json

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#785]
cant update content.json resulting in zero peers served, even though bit name resolution is correct. the left side link points to the undirected hash.

I keep getting this error.
ubu16 native(w apache in background and dnscrypt-proxy for name resolution)

**Comment by MuxZeroNet** [comment]
Let's go through this step by step:

`1. `Can you load any site?
`2. `Can you go to your Stats page `http://127.0.0.1:43110/Stats` and check if it shows any peer IP?

**Comment by JazzMaster** [comment]
I fixed it. thx. wasnt signing correctly somehow.
