### ISSUE TITLE
assets not allowed

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#786]
coming from jekyll tis is confusing.

Im not shure if this means /assets/xyz
or request for an asset of media type, as in images...which seems to work.

I keep getting throw this silently in background(no UI error in the browser) 

Ui.UiServer Media referrer error: 
assets not allowed from http://127.0.0.1:43110/chomping-at-the.bit/?wrapper_nonce=dcea03242c2de26ed8f2f05ce7eabaf2e627b0816007964fcd82444f780438b3

since its a nonce, I have no idea what this is. It could be js file, font file, image...or links. Ive heard that without _top, links dont work....so tell me how thats suppose to work in jekyll.. anyways the navcode seems to handle things ok and the images are loading.

thx to someone else, one can stream or fetch nearly instantly. As far as large files, we would have to chisel out that part of code from zeroTube or similar, which dices up large files(or just torrent).

**Comment by HelloZeroNet** [comment]
the site not signed properly, so cant download but this is normal: your site is avalible from  http://127.0.0.1:43110/chomping-at-the.bit/, so loading  http://127.0.0.1:43110/assets/anything won't work.

this should help: http://ricostacruz.com/til/relative-paths-in-jekyll
