### ISSUE TITLE
Question: ZeroFrame API callbacks

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#788]
Any information/rules about ZeroFrame API callbacks that is nice to know?

I expect callbacks to be executed asyn, independently and as quickly as possible.
A1 => cb1 (long call), A2 => cb2 (short call), A3 => cb3 (short call).
I would expect cb2 and cb3 to be executed before cb1 but it is not always so.
Sometimes A1 call will block A2 and A3 calls until A1 is done. 
For example can a fileGet (optional file) block many other ZeroFrame API calls for a long time.

So what is the rules for ZeroFrame API callbacks?
Is UI server a blocking resource? Max one running UI server call at any time?

**Comment by HelloZeroNet** [comment]
ZeroNet is single threaded, event-based, it means IO-related tasks (file/socket read/write) will execute concurrently, CPU-bound things (eg. signing a file, crypto-functions, database query) will block the application. 

I have tried to move this CPU-heavy functions to separate thread, but without any success. I have not given up on it, I will try it again later.

Currently one websocket connection can only execute one command at a time. So yes, the fileget will block it. It would be a good idea execute that async, I will check it later today.

**Comment by jaros1** [comment]
Thanks for the info. Will try to be smarter in my API calls. 

Regarding fileGet. Sometimes fileGet fails with a timeout (empty response in callback) and the requested file will arrive later and is detected in file_done event. Sometimes very long time after the failed fileGet request. I have used that in my message processing. 
Maybe add a timeout parameter to fileGet? Would be nice with shorter timeout period.

**Comment by HelloZeroNet** [comment]
fileGet should be async now: https://github.com/HelloZeroNet/ZeroNet/commit/bf34d95bc121005fd82f07308dedf71c9be21773
+ base64 encoding and timeout also added: https://github.com/HelloZeroNet/ZeroNet/commit/54c553d13bbc2c01d1d69ab020592c29d180fa08
