### ISSUE TITLE
problem hacker?

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#789]
[00:56:03] FileServer Unknown target onion address: lzxufmo7heqhrbeh
appears repeatedly (all proper sites end in onion) and I noticed some files when pushing a late update. The file browser showed them as images. SocketIO,re ...etc. And they were snapshots of me launching zeronet sitting there in its folder. Which makes no sence.

Either previous zeronet took them or somehow ubuntu, despite being locked down is attempting to send console snapshots over the onion network. NEITHER is good. If it involves us, we need to put the kabash and ban this mf-er. Comcast ans spectrum aka Twc aka ATT MAY be to fall as well. This is one of the only hdd not exclusively scanned to the T- because it doesnt get infected. 100% always on scans are ludicris machine stoppers.Going to scan for rootkits but I want to ensure the site gets updated since Im picking up traffic. Nothing else seems affected by this. No other files seem out of place.

**Comment by MuxZeroNet** [comment]
Sorry, but we need more clarification.

**Comment by JazzMaster** [comment]
looked like someone was snapshotting me while running zero and saving the files as random text. caja knew better. also: random ass onions showing up without the .onion domain. I have another.

**Comment by jmfgdev** [comment]
Any news on this @MuxZeroNet @HelloZeroNet @JazzMaster ? So you are suggesting someone was remote connecting to you and snapshotting you but only your ZeroNet usage?

**Comment by MuxZeroNet** [comment]
I wasn't aware of any hackers. The only problem I have since I have been running ZeroNet for a year, is the minor problem of file size mismatch, simply because not all peers in the network have the latest version of a file.

Regarding the snapshots, a [volunteer](https://github.com/weakish/0me-hubs-snapshots) is running a script that backs up ZeroMe Hubs. Don't worry about that.

**Comment by jmfgdev** [comment]
@jazzmaster your personal website is giving off a ssl error, some kind of misconfiguration. Everything alright over @ https://southernhedgehogs.org/ ?

**Comment by imachug** [comment]
@HelloZeroNet We've closed a "couple" (huh) vulnerabilities recently, and this issue is from 2 years ago, and we're switching to py3... I think this isn't related anymore.
