### ISSUE TITLE
On getFile Speed Improvement

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#792]
This is an interesting but hard-to-implement idea: asking more than one peer for a big file, so file loading will not get stuck even when many peers have slow Internet.

![zeronet_protocol](https://cloud.githubusercontent.com/assets/24784041/22236524/10ead87c-e1fe-11e6-8bfc-fa85328e18ab.png)

When browser requested for a _big enough_ file, ZeroNet loads small parts of the same file form multiple peers concurrently.

## Problems:
Some computers in the network may have an old version of the file. We need to check for this inconsistency before marking the response as valid. (Heuristic Check)
- Check if file size matches.
- Add this to ~~response~~ header (Correction: should be **request** header) -  sha512sum of this file. We assume an up-to-date ZeroNet will send back an error message when checksum does not match.
- Add this to ~~response~~ header (Correction: should be **request** header) - sha512sum of `content.json` that contains this file.

The hash checksum of reassembled file may still be different from what your `content.json` said. In this case, fallback to single-peer download.

To further improve this design, write your comments below.

**Comment by HelloZeroNet** [comment]
I see the problem, but whats the point adding it to the response? I think all we need to do is add it to request.

**Comment by purplesyringa** [comment]
@HelloZeroNet Not sure if this is already implemented?

**Comment by HelloZeroNet** [comment]
Yeah, similar implemented with the big file support.
