### ISSUE TITLE
ZeroNet no longer works with gevent > 1.1.x

### ISSUE THREAD

**Issue by benmoran56** [HelloZeroNet/ZeroNet#793]
It seems like the 1.2.x version of gevent does not work with Zeronet. One of the modules was renamed, causing a crash on startup.

**Comment by HelloZeroNet** [comment]
I'm running it with gevent 1.2:
>>> gevent.version_info
gevent.version_info((1, 2, 0, 'final', 1))

Please make sure you have the latest version
