### ISSUE TITLE
option to have ZeroNet listen on IP other than 127.0.0.1:15441

### ISSUE THREAD

**Issue by adrelanos** [HelloZeroNet/ZeroNet#795]
* Talking about `127.0.0.1:15441` here.
* Not talking about the web interface here which can be configured with `--ui_ip`.

Could you add a command line switch to make the listener IP configurable please?

That would be useful to make ZeroNet fully work inside Whonix.

Related and further information:
#794

**Comment by HelloZeroNet** [comment]
You can configure it using:   `--fileserver_ip ip    FileServer bind address (default: *)`

**Comment by adrelanos** [comment]
When using...

    ./zeronet.py --tor always --fileserver_ip 10.137.11.80

That does not work for me.

```
sudo netstat -tulpen | grep python
tcp        0      0 127.0.0.1:43110         0.0.0.0:*               LISTEN      1000       30399      2988/python2.7      
tcp        0      0 127.0.0.1:15441         0.0.0.0:*               LISTEN      1000       30402      2988/python2.7
```

Looks like `--tor always` prevents using any `--fileserver_ip` other than `127.0.0.1`.

Could you fix that please?

**Comment by HelloZeroNet** [comment]
It should be fixed by https://github.com/HelloZeroNet/ZeroNet/commit/d57d82f4398995389c390f344ee093027ff08d6b (also added other modifications to allow local addresses other than 127.0.0.1)

**Comment by adrelanos** [comment]
Works for me! Thanks!
