### ISSUE TITLE
P2P port open checking

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#80]
Does not relies on canyouseeme.org, also possible to use to check i2p/tor hidden service.

**Comment by MuxZeroNet** [comment]
Hi there. Any progress on this? This can be used in public gateways.

**Comment by HelloZeroNet** [comment]
No progress on it, but i'm not sure what you mean.

In my theory it would work like this:
 - Collect some IPs via Trackers/Peer database/etc.
 - Ask them to connect back to the given port and return the result

Based on this information the client would be possible to find out if their public ip/hidden service is works well or not.

**Comment by grez911** [comment]
@HelloZeroNet I made a pull request to close this issue, please, review it.

**Comment by grez911** [comment]
@HelloZeroNet All checks have passed.

**Comment by grez911** [comment]
Not closing because there is need to add tor hidden service check also.

**Comment by HelloZeroNet** [comment]
I think Tor hidden service checking is not necessary. If the hidden service has registered successfully, then it should work regardless your network settings. 
It also has 1-5 minute cooldown time, so you can't do it on startup.

**Comment by grez911** [comment]
@HelloZeroNet Then closing, I think.
