### ISSUE TITLE
SiteCreate doesn't create directory on filesystem

### ISSUE THREAD

**Issue by agharbeia** [HelloZeroNet/ZeroNet#801]
On Ubuntu 14.04

upon issuing `~/.local/bin/ZeroNet/zeronet.py siteCreate`
I get the following:

> - Starting ZeroNet...
> - OpenSSL loaded, version: 01000106F
> - Version: 0.5.1 r1848, Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
> [GCC 4.8.4], Gevent: 1.0
> - Generating new privatekey...
> - ----------------------------------------------------------------------
> - Site private key: [redacted]
> -                   !!! ^ Save it now, required to modify the site ^ !!!
> - Site address:     19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF
> - ----------------------------------------------------------------------
> ? Have you secured your private key? (yes, no) > yes
> - Creating directory structure...
> - Creating content.json...
> Site:19CjDc..akeF Content.json not exist: data/19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF/content.json
> Average Speed: 43678.8 w/s. Current Word: 'IroXCb'
> Site:19CjDc..akeF File content.json not exist yet, loading default values...
> Site:19CjDc..akeF Opening site data directory: data/19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF/...
> Site:19CjDc..akeF - index.html (SHA512: 4319ecaec2b7c0569900f73fee07b8d887adcf254c827a217706d3423e79a8e1)
> Site:19CjDc..akeF Adding timestamp and sha512sums to new content.json...
> Site:19CjDc..akeF Verifying private key...
> Site:19CjDc..akeF Correct 19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF in valid signers: ['19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF']
> Site:19CjDc..akeF Signing content.json...
> Site:19CjDc..akeF Saving to content.json...
> Site:19CjDc..akeF File content.json signed!
> - Site created!
> 
However no data is written to disk inteh current directory, and no "data" directory created.
Searching the whole file system, I found the data directory, site directory, json and html files under `/proc/5988/cwd/data/19CjDcEs4C5i1pyNvaMTcxuKgaGhpHakeF`

**Comment by HelloZeroNet** [comment]
`ls -al /proc/5988/cwd`  probably points to ~/.local/bin/ZeroNet and your site is created in ~/.local/bin/ZeroNet/data directory
