### ISSUE TITLE
Mount ZeroNet on nginx path e.g. /zeronet instead of domain_root

### ISSUE THREAD

**Issue by cibacoox** [HelloZeroNet/ZeroNet#802]
Hi,

I would like to integrate ZeroNet in an application where it would be "mounted" to a path instead of the root domain, for example instead of **https://mydomain.org** on **https://mydomain.org/zeronet**

After some research about Nginx's reverse proxy [1] I have learned that for this to work we would have to update the ZeroNet app code so all relative paths take the new "root domain path" into account [2]. To make an example, in the UI wrapper the line  ( https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/template/wrapper.html#L9 )

`<link rel="stylesheet" href="/uimedia/all.css?rev={rev}" /> `

would become something like 

`<link rel="stylesheet" href="{domain_root}/uimedia/all.css?rev={rev}" /> `

where domain_root would have the value "/zeronet", an optional parameter that could be passed when starting the app.

I have started to work on a fork with some first success [3].

However, since I'm quite new to ZeroNet I thought I would ask the developers here first. 

@HelloZeroNet How feasible do you think it is to complete this feature?

Thank you very much for your feedback!
Thank you even more for this awesome project!

cibacoox

PS: I forgot to mention that for my app it is unfortunately not an option yet to use a subdomain e.g. zeronet.mydomain.org, the alternative way the Nginx folks have recommended.

[1] https://github.com/HelloZeroNet/ZeroNet/issues/288
[2] https://serverfault.com/questions/667947/nginx-rewrites-and-absolute-resource-paths
[3] https://github.com/cibacoox/ZeroNet/commit/8fe3b0d564d200bd86deb4ad92c1af8642175c28

**Comment by JazzMaster** [comment]
and like jekyll --you have the . when undefined- or the site goes south fast.

**Comment by cibacoox** [comment]
@JazzMaster I'm not acquainted with Jekyll and I'm afraid I don't understand your comment. Could you elaborate a bit more?

**Comment by q158073378252010** [comment]
Are you successful?
