### ISSUE TITLE
content.json refuses to update

### ISSUE THREAD

**Issue by JazzMaster** [HelloZeroNet/ZeroNet#803]
Im having a split issue. The site updates but content.json does not and yields an update failed(to sync) error. As a side result, Im getting failure to share my zite.<br />

ex:
[FAILED] mfqipozsmdbgdnmq.onion:15441: {'to': 1, 'cmd': 'response', 'error': 'File invalid'}
...
Site: **** [FAILED] fcwt5bzv2w5it3lv.onion:15441: None
...

and then FAILURE to sync messages. 55+ nodes. either someone not staying online long enough, or zero isnt sending updates. Im also getting timeouts(I might could fix these, my upstream bandwidth is limited) on a number of attempted nodes when pushing updates. Im looking for the timeout variable---mebbe I can adjust it-- but cant find anything documented, like the zeronet.conf file. pascal has two engine for this, C has a few. I hope py is good at documenting itself...

**Comment by MuxZeroNet** [comment]
ZeroNet will not seed an unknown site without user interaction. When you are pushing your new site to peers, make sure they want to seed your site.

For example, simply open your site on [one](https://bit.no.com:43110/138R53t3ZW7KDfSfxVpWUsMXgwUnsDNXLP/?Page:proxies) [of](https://zeronet.korso.win) [these](https://zeronet.iikb.org) [public](https://proxy1.zn.kindlyfire.me/) [gateways](https://zero.btnova.org/), and push your site update again.

**Comment by HelloZeroNet** [comment]
Probably your site is too large, you should keep it under 10MB to make it to every client.
