### ISSUE TITLE
Pass location.hash to inner iframe?

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#806]
Hello!

There is no easy way to get the `#hash` of the `top` of a page. I can set it by with `window.open` API,
```js
window.open("#hash", "_top");
```
but I am not able to get the hash. [This page](https://bit.no.com:43110/1CiDoBP8RiWziqiBGEd8tQMy66A6fmnw2V/big/docs/usage/mp4-file-format/#moov-box) doesn't work well.

**Comment by HelloZeroNet** [comment]
If you call the "wrapperInnerLoaded" command, then it will got applied to your page:

https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee#L104

(looks like I forgot to add it to docs, I will do)

**Comment by HelloZeroNet** [comment]
Added to docs
