### ISSUE TITLE
Custom favicon.ico can't display when use browser proxy to access zeronet

### ISSUE THREAD

**Issue by liyafe1997** [HelloZeroNet/ZeroNet#809]
When use http://zero/xxxx in address bar to access zeronet with setting a proxy in browser (like http proxy 127.0.0.1:43110), all zerosites with a custom favicon.ico would not show on the title bar,  it only display the zeronet default favicon.
like this:
![1](https://cloud.githubusercontent.com/assets/18359157/22623754/4f275dee-eba0-11e6-9255-457e20312479.jpg)
![22](https://cloud.githubusercontent.com/assets/18359157/22623771/23e1d0b4-eba1-11e6-8809-25a98691f7e3.jpg)

Use full url (http://127.0.0.1:43110/me.zeronetwork.bit) is work well:
![2](https://cloud.githubusercontent.com/assets/18359157/22623756/683f17ae-eba0-11e6-9875-d7d71c75dc0a.jpg)

Use bit domain directly (with setting proxy) also work well:
![3](https://cloud.githubusercontent.com/assets/18359157/22623772/34cb599a-eba1-11e6-88db-ff5b3dbe79c5.jpg)

**Comment by MuxZeroNet** [comment]
Add `view-source:` to the beginning of URL and show us the page source code.

**Comment by HelloZeroNet** [comment]
I was able to reproduce it and working on fix

**Comment by HelloZeroNet** [comment]
Fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/f74e9397db20336835a72220321480328f4de477
