### ISSUE TITLE
`ignore` patterns fail (on windows at least)

### ISSUE THREAD

**Issue by vprimachenko** [HelloZeroNet/ZeroNet#81]
i tried simple dotfile hiding with `\..*` (escaped as `"ignore": "\\..*)"` yet my `.test` file still got served

also the sample from the docs fails for me: `http://localhost:43110/…/css/test.css` was served

OS: win7
Method of installation: ZeroBundle package

**Comment by HelloZeroNet** [comment]
The ignore patter in only exclude file from content.json signing method.
You can still access the file locally, but it won't be transfered to other peers.

**Comment by vprimachenko** [comment]
thanks, the part that those files can be accessed locally should be noted in the docs
