### ISSUE TITLE
Manage public proxy without interruption

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#823]
I use this way to manage a public proxy:
1. Kill ZeroNet's process.
2. Rename Multiuser plugins and add `disabled-` prefix.
3. Start ZeroNet.sh again.
4. Do some operation (e.g.: delete some inactive sites and open help distribution for some sites)
5. Stop ZeroNet.
6. Rename Multiuser plugins and remove `disabled-` prefix.
7. Start ZeroNet.sh again.

But there is some problems:
1. Service interruption.
2. Kill process directly is unsafe for data.
3. If I don't turn off reverse proxy or add an authorization temporarily, users can do some unsafe operation.

Any advice for that?

**Comment by ysc3839** [comment]
IIRC, the `killall` command will signal the target process, which is safe. `killall -9` will kill the process without signal.

**Comment by l5h5t7** [comment]
But I think that the signal sends Python's process only, for ZeroNet, it's still unsafe.

**Comment by HelloZeroNet** [comment]
I just made it easy: From Rev1892 if you login on ZeroHello with any user's master_seed from data/users.json, then you will have no restriction. So you can delete sites, update zeronet, etc.

Other modification is you enable --multiuser_no_new_sites, then normal users will not able to add new sites (users in data/users.json still can)
