### ISSUE TITLE
zeronet proxy update

### ISSUE THREAD

**Issue by nqzhang** [HelloZeroNet/ZeroNet#824]
how to update a zeronet proxy
the update function was disabled in the ui

**Comment by HelloZeroNet** [comment]
the easiest way currently is: 
stop it, run `python update.py`, start again

**Comment by nqzhang** [comment]
python update.py
usage: update.py [-h] [--verbose] [--debug] [--debug_socket] [--debug_gevent]
                 [--batch] [--config_file path] [--data_dir path]
                 [--log_dir path] [--language language] [--ui_ip ip]
                 [--ui_port port] [--ui_restrict [ip [ip ...]]]
                 [--open_browser [browser_name]] [--homepage address]
                 [--updatesite address] [--size_limit size]
                 [--connected_limit connected_limit] [--fileserver_ip ip]
                 [--fileserver_port port] [--disable_udp] [--proxy ip:port]
                 [--ip_external ip]
                 [--trackers [protocol://address [protocol://address ...]]]
                 [--trackers_file path] [--use_openssl {True,False}]
                 [--disable_db] [--disable_encryption]
                 [--disable_sslcompression {True,False}] [--keep_ssl_cert]
                 [--max_files_opened limit] [--use_tempfiles {True,False}]
                 [--stream_downloads {True,False}]
                 [--msgpack_purepython {True,False}]
                 [--fix_float_decimals {True,False}]
                 [--coffeescript_compiler executable_path]
                 [--tor {disable,enable,always}] [--tor_controller ip:port]
                 [--tor_proxy ip:port] [--tor_password password] [--version]
                 
                 {main,siteCreate,siteNeedFile,siteDownload,siteSign,sitePublish,siteVerify,dbRebuild,dbQuery,peerPing,peerGetFile,peerCmd,cryptSign}
                 ...
update.py: error: unrecognized arguments: --optional_limit 10%

**Comment by HelloZeroNet** [comment]
Then you have: 
 - disable the Multiuser plugin
 - start it
 - update using the menu 
 - stop
 - enable Multiuser plugin again
 - start again

I will fix standalone update.py running and add a simpler method to update the proxy

**Comment by nqzhang** [comment]
ok ,thanks for your respons
I'll try this now

**Comment by nqzhang** [comment]
it works

**Comment by HelloZeroNet** [comment]
I just made it easy: From Rev1892 if you login with any user's master_seed from data/users.json, then you will have no restriction. So you can delete sites, update zeronet, etc.

It also have security enhancements, so the update is recommended.

Other modification is if you enable --multiuser_no_new_sites, then normal users will not able to add new sites (users in data/users.json still can)

**Comment by nqzhang** [comment]
Thanks for your hard work
