### ISSUE TITLE
Question: information about download processing

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#833]
I am trying to test a chat site in a multi user environment and sometimes the files are not replicated and it is very hard to find out which files that hangs and why (I think my problem is with optional files). 
Very often the download problem can be seen in top of screen as a hanging download and you must already have all the necessary information for updating the green download indicator.

Is it possible to see/find the information behind the download indicator?

Just an idea. Very nice experience to drag the 0 icon left and see all the site info and the extra controllers for the site. Could it be possible to drag the 0 icon down and see download process information?

**Comment by HelloZeroNet** [comment]
If you drag the zero button to left it shows what files missing from current site

**Comment by jaros1** [comment]
OK. On one of my VM machines there are 271 missing files (required files) from user areas. A lot of "data/users/xxxx/content.json invalid cert!" errors in UI log. And no green download indicator in top of screen. 
I think that the download indicator in top of screen is showing pending download for current page (fileGets) and not all missing files. I am interested in the pending fileGets behind the hanging green indicator in top of page. Requests with pending response. Not all missing files.

**Comment by jaros1** [comment]
Closing this issue. Tried a number of different things to get a better file replication for my site. The major problems in my site were:
1) a very big main content.json file with many optional files (fixed). Now moved to smaller content.json files. 
2) a big all.js file about 1 Mb (todo).  
3) many invalid content.json files (invalid cert) (fixed). I think the mayor problem was that the UI server were busy trying to replicate the invalid content.json files again and again and did not replicate the other site content (optional files and js-files).
4) disabled TOR also helper.

But it was a very frustrating debug process and it could be nice with more build-in ZeroNet help. 
I cannot be the only one wondering why some files are not replicated as expected

**Comment by HelloZeroNet** [comment]
I have just added .tar.gz, .tar.bz2, .zip support in latest rev: 2854e20
example site: http://127.0.0.1:43110/1AsRLpuRxr3pb9p3TKoMXPSWHzh6i7fMGi/en.tar.bz2/index.html (please update your client before visit)

I think this could help you in many cases:
- Javascript files compression rate is pretty good (3-5x)
- It also help to reduce content.json size, because the packed file is only takes up one entry
