### ISSUE TITLE
Add mutil thread support for downloading

### ISSUE THREAD

**Issue by liyafe1997** [HelloZeroNet/ZeroNet#835]
Now Zeronet is single thread for downloading. So the speed of files loading is slow and unstable, espcially ZeroMux.
So if it can download a files from mutil peers at the same time, it will be more stable and faster.

**Comment by HelloZeroNet** [comment]
ZeroNet download is multi threaded: 
 - Spawns 6 worker if you add new tasks
 - Try to assign 6 different task for these workers
 - If there is no 6 tasks, then it steals another worker's tasks, wait 1 sec to allow the current worker to finish it, if it's still not finished after 1 sec, then tries to download.
