### ISSUE TITLE
Question: tar/zip support and this is my site

### ISSUE THREAD

**Issue by jaros1** [HelloZeroNet/ZeroNet#838]
I am very happy with the new zip support in ZeroNet and has added an all.js.tar.bz2 file to my site.
To support "old" clients I load both all.js and all.js.tar.bz2 in my index page. I expect all.js (big 1 Mb file) to be replicated slow on ZeroNet and all.js.tar.bz2 to be replicated fast (small file).
Before page reload I delete both all.js and all.js.tar.bz2 files.

all.js is generated from my js-files (OK) and all.js.tar.bx2 is downloaded from ZeroNet (not OK).

I would have expected that "this is my site" would prevent files to be downloaded from ZeroNet?

**Comment by MuxZeroNet** [comment]
Yes, you should definitely check that option.
