### ISSUE TITLE
Auto-update with zeronet.cmd

### ISSUE THREAD

**Issue by HostFat** [HelloZeroNet/ZeroNet#84]
Can you change zeronet.cmd so than it will update ZeroNet if it finds a new version on github?

**Comment by HelloZeroNet** [comment]
If new, safe to update version out it will displayed on homepage like this:
https://camo.githubusercontent.com/8eca76beec11d1b903ea233cee169b2c84ff1330/687474703a2f2f7a65726f6e65742e72656164746865646f63732e6f72672f656e2f6c61746573742f696d672f7a65726f68656c6c6f2e706e67

**Comment by HostFat** [comment]
oh, thank you :)
