### ISSUE TITLE
Port forwarding question

### ISSUE THREAD

**Issue by ShadowRZ** [HelloZeroNet/ZeroNet#840]
On some routers(Like my TL-WR886N), Port forwarding needs two ports: One for access, The other for hosting port.
I need to forward port 15441, should I use 43110(ZeroNet's port) for internal port?

**Comment by ShadowRZ** [comment]
In a nutshell:
I want map port 43110 to port 15441.
Am I correct?

**Comment by HelloZeroNet** [comment]
both port should be 15441.

**Comment by ShadowRZ** [comment]
My ISP:
China Unicom(?)（中国联通）

**Comment by ShadowRZ** [comment]
Should the server use DHCP?

**Comment by ShadowRZ** [comment]
@HelloZeroNet Looks like I have a IP mismatch.

**Comment by ShadowRZ** [comment]
@HelloZeroNet My router's IP address is 10.93.30.105, I can use this IP to access my internal server.
But IP checkers gives me a different IP: 175.19.44.91
I think that's the problem.

**Comment by HelloZeroNet** [comment]
This is normal: Your internal and external IP is different.
- [find your computer's internal ip address](https://www.groovypost.com/howto/microsoft/windows-7/find-your-local-ip-address-windows-7-cmd/)
- Add new portforward: external/internal port both 15441, ip address your computer's internal ip
- Restart ZeroNet
- You should see Port: Opened

**Comment by ShadowRZ** [comment]
http://service.tp-link.com.cn/detail_article_2578.html

**Comment by ShadowRZ** [comment]
I think you misunderstand my network layout.
(Can we speak in Chinese?)

**Comment by ShadowRZ** [comment]
I set my forward rules but still not working.
@HelloZeroNet @clarkzjw

**Comment by HelloZeroNet** [comment]
It's hard to tell what's the problem, please try to enable uPnP on your router. On my TP-Link (TL-WR841N),
it's looks like this:
![image](https://cloud.githubusercontent.com/assets/10350359/23578367/676d1836-00d5-11e7-97ff-ad397a834ba3.png)
After you enabled it all you have to do is restart your ZeroNet client and it will open port for itself.

If it's not working,then please add a screenshot of the port forwarding page of your router's web interface.

**Comment by ShadowRZ** [comment]
But TL-WR886N is a cloud router, It's upnp is on, But I can't check the status.
See http://service.tp-link.com.cn/detail_article_2936.html

**Comment by ysc3839** [comment]
You shouldn't use router's port map. Because your ISP give you a ethernet IP.

**Comment by ShadowRZ** [comment]
@ysc3839 Ethernet IP?

**Comment by ShadowRZ** [comment]
@ysc3839 What should I use? Modem's port map?

**Comment by ysc3839** [comment]
I mean you don't have a internet IP, so the port map is useless.

**Comment by ShadowRZ** [comment]
I don't have a internet IP?
PS: I'm connected to Internet with a router and a modem.

**Comment by ysc3839** [comment]
The IP that ISP gives you is a private IP, which is not accessible from internet. You connect to ISP's router and that router connect to the internet. 
See more: https://en.wikipedia.org/wiki/Network_address_translation

**Comment by ShadowRZ** [comment]
I know.
So should I tweak my modem?

**Comment by ysc3839** [comment]
There's no use.

**Comment by ShadowRZ** [comment]
I'll try to figure it myself, close this for now.
@clarkzjw @ysc3839

**Comment by ShadowRZ** [comment]
But first, check if it really works:
http://127.0.0.1:43110/16k5CXBJTk79BPhe6yhtEa9hXVzFKcTGox/
@HelloZeroNet @ysc3839 @clarkzjw

**Comment by ysc3839** [comment]
You can upload your zite without open a port. Just Open it on a public proxy (such as bit.surf:43110) and then publish it.

**Comment by ShadowRZ** [comment]
I did and it works.
@ysc3839 ~

**Comment by ShadowRZ** [comment]
Similar to #873 , but it's so bad that we can't have a public IP.
