### ISSUE TITLE
Is it possible to specify a different inbound port #?

### ISSUE THREAD

**Issue by aplocher** [HelloZeroNet/ZeroNet#845]
My VPN provider gives me a random inbound TCP/UDP port and unfortunately I have no control over what port it's going to be.  Is it possible for me to specify a different port instead of 15441?

**Comment by l5h5t7** [comment]
Edit `zeronet.conf` and add these contents below:
```
[global]
fileserver_port = your inbound port
```
Then restart ZeroNet, it should be works.

**Comment by aplocher** [comment]
Thank you, that worked
