### ISSUE TITLE
[Feature Request] Directory Listing

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#846]
Like this: http://ftp.debian.org/debian/
Sometimes we need't a gorgeous page and only to share/browse a structured file system. In this situation, directory listing allow us not create a catalog and browse files easily.

**Comment by HelloZeroNet** [comment]
I think it would be better to not build this into ZeroNet client, but provide a cloneable site that take cares of the listing, so it would be possible to customize and enhance the listing.

**Comment by mishfit** [comment]
@l5h5t7 as of #842 there's a feature in the API to list directories and files (`dirList`) non-recursively. Or you can call `fileList` which will recursively get all the files given a specific path, excluding the directories as it traverses.

**Comment by grez911** [comment]
@l5h5t7 @HelloZeroNet Closing?

**Comment by clownfeces** [comment]
So, if someone wants to activate directory listing for the directory /files/, what does he need to do?
