### ISSUE TITLE
p2p marketplace?  

### ISSUE THREAD

**Issue by nyancat18** [HelloZeroNet/ZeroNet#849]
would be extremely cool make a p2p makretplace with zeronet.

censorship-resistant
full protected

**Comment by border0464111** [comment]
It would totally be cool indeed ! 

But zeronet is only the platform/protocol. Site developement don't append here. Im affraid you are at the wrong place. 

Maybe this issue should be closed as it's not related to zeronet core.

**Comment by grez911** [comment]
@nyancat18 @HelloZeroNet Not related to the project core. Please, consider closing this issue.
