### ISSUE TITLE
Merger site?

### ISSUE THREAD

**Issue by undo2000** [HelloZeroNet/ZeroNet#855]
I don't know if Merger sites is what i need, do they allow to query database of another site from my site? If my site needs to display something from ZeroMail (for example number of messages in inbox). How can i do it?

**Comment by HelloZeroNet** [comment]
Unfortunetly there is no way to do that. In the future it's planned to be able to request permission to another site, but ZeroMail messages are stored in encrypted form, so it's even more compliated.

**Comment by imachug** [comment]
@HelloZeroNet We have `as` ZeroFrame command now, can this be marked as resolved and closed?
