### ISSUE TITLE
Can't load ZeroNet.

### ISSUE THREAD

**Issue by Snarkly** [HelloZeroNet/ZeroNet#858]
I recently install the new Linux cinnamon 18.1 and I downloaded your ZeroNet bundle but I seem to be having problems with it. After I downloaded the bundle I clicked on ZeroNet.sh to set up ZeroNet and it loaded the ZeroNet site for the first time like it was supposed to. Well the next day I clicked on zeronet.py to get it running like I did when I had the old version of Linux but for some reason it wont load ZeroNet site. I only get a screen that says unable to connect. I noticed the only way I can get ZeroNet to load now is to always click on ZeronNet.sh every time instead of the zeronet.py like I used to do. I also have my port open.

**Comment by HelloZeroNet** [comment]
Probably you missing one of the required packages. Try run zeronet.py in terminal and see the error message.

**Comment by Snarkly** [comment]
I typed in run zeronet.py in the command terminal and got this
No command 'run' found, did you mean:
 Command 'grun' from package 'grun' (universe)
 Command 'qrun' from package 'torque-client-x11' (universe)
 Command 'qrun' from package 'torque-client' (universe)
 Command 'srun' from package 'slurm-client' (universe)
 Command 'zrun' from package 'moreutils' (universe)
 Command 'runq' from package 'sendmail-bin' (universe)
 Command 'runq' from package 'exim4-daemon-light' (main)
 Command 'runq' from package 'exim4-daemon-heavy' (main)
 Command 'rn' from package 'trn4' (multiverse)
 Command 'rn' from package 'trn' (multiverse)
 Command 'runc' from package 'runc' (universe)
 Command 'rup' from package 'rstat-client' (universe)
run: command not found
I'm still learning about all this Linux so I really don't understand all that stuff. Should I have typed sudo run zernet.py?

**Comment by HelloZeroNet** [comment]
You have to enter `python zeronet.py`

**Comment by Snarkly** [comment]
I typed in python zeronet.py and I got this. python: can't open file 'zeronet.py': [Errno 2] No such file or directory

**Comment by mishfit** [comment]
You have to enter `python zeronet.py` from the same directory in which zeronet.py is located.

**Comment by Snarkly** [comment]
I already tried that as well and it didn't work.

**Comment by Snarkly** [comment]
Here's where I put ZeroNet ![zeronet1](https://cloud.githubusercontent.com/assets/8492776/23911711/fca23900-08b3-11e7-87a4-e2f0a1123a9e.png) and here's the zeronet.py I'm clicking on.
![zeronet2](https://cloud.githubusercontent.com/assets/8492776/23911800/434987be-08b4-11e7-9ccc-857ca9563aa5.png)

**Comment by mishfit** [comment]
When I say "the same directory" I mean in the terminal app

**Comment by Snarkly** [comment]
Is this what your talking about? ![zeronet3](https://cloud.githubusercontent.com/assets/8492776/23914141/728e1c86-08bb-11e7-9519-c5fb1fd4f90e.png)

**Comment by Snarkly** [comment]
Is there a log file located somewhere that might tell whats wrong?

**Comment by Snarkly** [comment]
I just disabled four Firefox add-ons and this time the page loaded like it was supposed to. I disabled uBlock Origin, Random Agent Spoofer, Decentraleyes and Privacy Badger.
