### ISSUE TITLE
Errors when running with --verbose flag

### ISSUE THREAD

**Issue by undiagnosed** [HelloZeroNet/ZeroNet#860]
Get the following error:

WebSocket handleRequest error: UnboundLocalError: local variable 's' referenced before assignment in UiWebsocket.py line 105 > UiWebsocket.py line 212 > UiWebsocket.py line 549

In the actionDbQuery function in UiWebsocket.py, the variable s which is keeping track of execution time is only defined when the debug flag is specified but is used with the verbose flag and thus has not been initialized.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroNet/commit/afcd6dfa14c2759ac12151a324e7051cea4fb38d
