### ISSUE TITLE
ZeroNet not working with Eduroam

### ISSUE THREAD

**Issue by pmfcdb** [HelloZeroNet/ZeroNet#861]
Hi, first of all I would like to thank you/team for this excellent initiative.  This software could empower people and technology to choose their own path  instead of being pushed by other interests. 

So Eduroam is academic wifi network for students,researchers and academic staff  https://www.eduroam.org/ but I can't connect with zeronet. The network uses NAT and block a lot of external ports. 

So, is there an option/workaround to connect to zeronet from this network? Also Opera browser with private window and vpn ON cannot bypass external port block. I'm using windows 10 x64 pro.

Thks,

**Comment by MuxZeroNet** [comment]
## Do I need to have a port opened?
It is not required, but highly recommended.

## Can I get around the NAT?
Tor relays serve as super nodes, so enable Tor Always mode and enjoy.
```
zeronet.py --tor always --tor_controller 127.0.0.1:9151 --tor_proxy 127.0.0.1:9150
```

Alternatively, you can route ZeroNet through any working SOCKS proxy, but then you don't have open ports.
```
zeronet.py --tor disable --proxy 127.0.0.1:9150 --disable_udp
```

**Comment by pmfcdb** [comment]
Ok, thks it worked! In ZeroNet 0.5.3 the only thing that I had to change was this (cmd from the directory of  ZeroNet-win-dist):

zeronet.exe --tor always --tor_controller 127.0.0.1:9151 --tor_proxy 127.0.0.1:9150
