### ISSUE TITLE
german website translation

### ISSUE THREAD

**Issue by petrk94** [HelloZeroNet/ZeroNet#862]
Hey guys,

please check your grammar on the website, I have found 2 wrong words
"Seiten Antworzeit ist nicht begrentzt durch *deien* Verbindungs-Geschwindigkeit."
"Es ist *niergendwo*, weil es überall ist!"

How someone can take that serious, if there such big spelling mistakes, about grammar I dont will discuss.

**Comment by HelloZeroNet** [comment]
I don't speak german, but feel free to open a pullrequest.

**Comment by petrk94** [comment]
@HelloZeroNet its not hard at all, but someone has made the german translation, and its really bother me, because Im speaking german ;) 
here are the corrected senctences 
"Die Seiten Antwortzeit ist nicht begrenzt durch deine Internetverbindung."
"Es ist nirgendwo, weil es überall ist!"

Nice greets

**Comment by HelloZeroNet** [comment]
Thanks, fixed: https://github.com/HelloZeroNet/zeronet.io/commit/752d05210764a86dea98c380c664e8020c2de4fe
