### ISSUE TITLE
Cloned site upgrade

### ISSUE THREAD

**Issue by Emeraude** [HelloZeroNet/ZeroNet#865]
There is currently no way to update a zite you cloned.  
Most of the users that want to have a zeroblog will just go to the ZeroHello zites list and click "clone". But when ZeroBlog will be updated with a new feature, the cloned zite will not be. It can be by looking at te files and replacing them by the new ones, but a very few part of the users will be able to do that.

Here is a proposition to fix it:
Add the following entry in the `content.json` file of the cloneable zite:
```json
"repository": "https://github.com/HelloZeroNet/ZeroBlog"
```
Regularly (let's say once a day), zeronet will check for all the updates, and the cloned zite admin will have a notification on its ZeroHello page, asking him if he want to update its zite. It can also set it to be updated automatically without asking for anything.

Yes, there are a few drawbacks with this method:
- Git will be mandantory for running the project
- It relies on external http content

**Comment by Emeraude** [comment]
We can also juste reference the parent repository with this kind of entry:
```json
"cloned_from": "1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8"
```
Using that, we can only copy the updated `all.js` and `all.css` files (and other resources like images) to the cloned zite. It fix the two drawbacks I described above, but it create new ones. For example, the parent zite have to be updated first, and if a zite is of a clone of a clone (and so on) of a zite, it may takes a lot of time to update.

**Comment by HelloZeroNet** [comment]
it was planned when I implemented the clone feature (that's why the "cloned_from" data present in content.json), but I havent added this for the webui yet.

**Comment by Emeraude** [comment]
Oh I didn't noticed those two fields. Is it planned to be implemented soon or is it abandoned ?

**Comment by HelloZeroNet** [comment]
It's definetly planned

**Comment by grez911** [comment]
@Emeraude @HelloZeroNet Is this the same issue as https://github.com/HelloZeroNet/ZeroNet/issues/374 and can be closed?

**Comment by HelloZeroNet** [comment]
It's added in 0.5.5
