### ISSUE TITLE
Error after login - Err: AttributeError: 'NoneType' object has no attribute 'group' in UiServer.py line 62

### ISSUE THREAD

**Issue by thesoftwarejedi** [HelloZeroNet/ZeroNet#87]
After latest release, the following error is presented after logging in

Server error

Err: AttributeError: 'NoneType' object has no attribute 'group' in UiServer.py line 62 > UiRequest.py line 42 > UiRequestPlugin.py line 20 > UiRequest.py line 200 > UiRequestPlugin.py line 26

![image](https://cloud.githubusercontent.com/assets/6439434/7219440/084c1d08-e66e-11e4-95a8-490318c9feb5.png)

**Comment by HelloZeroNet** [comment]
Thanks for reporting, it got fixed in latest commit (rev106):
https://github.com/HelloZeroNet/ZeroNet/commit/c8fe73f5c0c3916c3244e446c7fbf03109567834#diff-67726306a3ab3bef30655f8f7f7465baR26
