### ISSUE TITLE
hello,i cannot open 15441 port on the ISP router so i cannot publish my site.

### ISSUE THREAD

**Issue by clamever** [HelloZeroNet/ZeroNet#873]
the 15441 port is blocked.so how can i publish my site to the zeronet?

**Comment by pmgouveia** [comment]
did you tried it? Which problems you ran into? which "tutorial" or instructions are you using?

**Comment by albjeremias** [comment]
which tutorial did you follow? Or what is failing? 

i found this, but i didn't try: 
http://zeronet.readthedocs.io/en/latest/using_zeronet/create_new_site/

**Comment by MuxZeroNet** [comment]
1. You don't need to have an open port. NAT Firewalls will not block outbound traffic.
2. You should turn on Tor Always mode. See #861 or #875 or ["How to use Pluggable Transport with ZeroNet."](https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-tor-work-if-my-isp-or-goverment-blocks-it) in the FAQs.
3. You didn't sign and publish your content, as what happened [here](https://www.reddit.com/r/zeronet/comments/61l7ku/i_create_zite_in_the_linuxthen_i_visite_the_zite/).
4. In [this thread](https://bit.surf:43110/Talk.ZeroNetwork.bit/?Topic:1_16UbJDyboDaAjW5fiZouKWpPJztpt43kEj/help+me+i+can+not+publish+my+site+becuase+i+cannot+open+port+15441), Rythyrix and Kaffie already have the answer for you:
> Kaffie: You should be okay. Just check your site on something like **https://bit.surf/** before you link it. If you can see it there, then you're good to go.

> Rythyrix: Firewalls tend only to stop incoming traffic, not outgoing. Initial peers for your content may be hard to get, but that's what **[New ZeroNet Sites](http://127.0.0.1:43110/1LtvsjbtQ2tY7SCtCZzC4KhErqEK3bXD4n/)** is for :D Plus you can always **go to a proxy and add your zite to their node**, but try not to flood the proxy's HDD. **Be sure to advertise your site too**, otherwise no one will know it exists.

5. I believe your [Chinese FAQ](https://bit.surf:43110/NewGFWTalk.bit) is much longer than the [original English FAQ](https://bit.surf:43110/Talk.ZeroNetwork.bit/?Topic:8_1J3rJ8ecnwH2EPYa6MrgZttBNc61ACFiCj/ZeroNet+help+FAQ).

**Comment by clamever** [comment]
very thanks!i had sovled my problems!

**Comment by border0464111** [comment]
@clamever  can you close this issue if it's solved?
