### ISSUE TITLE
The Profiles are Bitcoin addresses?

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#874]

**Comment by HelloZeroNet** [comment]
Yes, every user is also identified by valid bitcoin address (you can find your in data/users.json)

**Comment by Plasmmer** [comment]
@HelloZeroNet 
How the system protects to a user not use the same username as the existing other?

**Comment by HelloZeroNet** [comment]
For usernames you need to get a certificate from id provider. It's the provider resposibility to keep the usernames unique.

**Comment by Plasmmer** [comment]
This provider is served by all users? Its not much huge to download?

**Comment by HelloZeroNet** [comment]
The id provider only gives a signature to the user. (certs entry in your data/users.json) 
Actually after that you can even delete the id provider site.
