### ISSUE TITLE
zeronet

### ISSUE THREAD

**Issue by zohdi11** [HelloZeroNet/ZeroNet#875]
I am having an issue with turning tor while using tor browser. While I am in zeronet the status for tor it say it waiting but I can't do anything

**Comment by MuxZeroNet** [comment]
How to use ZeroNet with Tor Browser: https://zeronet.readthedocs.io/en/latest/faq/#how-to-make-tor-work-if-my-isp-or-goverment-blocks-it

```
zeronet.py --tor always --tor_proxy 127.0.0.1:9150 --tor_controller 127.0.0.1:9151
```

or 
```
zeronet.py --tor disable --proxy 127.0.0.1:9050 --disable_udp
```

**Comment by HelloZeroNet** [comment]
What operating system you using?

**Comment by zohdi11** [comment]
i am using macos

**Comment by MuxZeroNet** [comment]
@zohdi11 Have you tried starting ZeroNet with the parameters I mentioned above?

**Comment by zohdi11** [comment]
I am very sorry but I haven't done that yet. I will try to fix it then I will tell you what happened 

again i am very sorry

**Comment by zohdi11** [comment]
i Have tried everything you told me to do but it not working what can i do
