### ISSUE TITLE
Using --trackers return "too few arguments"

### ISSUE THREAD

**Issue by border0464111** [HelloZeroNet/ZeroNet#878]
all the following commands return: 

```
- Starting ZeroNet...
- OpenSSL loaded, version: 01000207F

[ it show all the usage ]

start.py: error: too few arguments

```

`./ZeroNet.sh  --trackers ["zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441"]`

`./ZeroNet.sh  --trackers "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441"`

`./ZeroNet.sh  --trackers zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441`

`./ZeroNet.sh  --trackers {["zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441"]}`

it seem to be specific to  `--trackers` as `--proxy` return no error.

**Comment by HelloZeroNet** [comment]
it works this way: `zeronet.py --trackers http://anything http://other --batch` (it should end with non-multivalue argument)

**Comment by border0464111** [comment]
isn't it a bug ? 

Posix standard make no mention of either it should sucess or fail, but It never append to me on linux before. 
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

Im not python dev but `optparse` seem depricated tho, Maybe the new lib could fix it ?  
https://docs.python.org/2/library/argparse.html#nargs
