### ISSUE TITLE
Trusted third-party authorization services

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#88]
Currently to make an user able to publish his own content, he/she has to contact the site owner to put his/her auth_address to the [users/data/content.json](http://zeronet.readthedocs.org/en/latest/site_development/content_json/#includes) file.

This required to has some kind of control over the users. (eg. be able to ban spamming users)

This makes the multi-user sites much harder because the user has to able reach the site owner and zeronet does provide any messaging service (yet), so it has to be done using other protocol (http, bitmessage, etc.).

To make it easier the site owner could able to provide trusted site addresses who is processes the new user requests. 
So the site owner could say: Any user who registered at Talk.Zeronetwork.bit is able to post on myblog.bit.

To make it possible we have 2 options:
#### Auth from other site's content.json
Every user who is seeding myblog.bit also has to seed the talk.zeronetwork.bit site. If a new user content comes in the peer checks if the auth_address is in talk.zeronetwork.bit user database.

Pros:
 - The auth site able to delete users if reported as spammer

Cons:
 - Users has to seed the authorization site

#### Validate other site's certificate
If a user registered successfuly at talk.zeronetwork.bit the site owner would sign the user's auth_address like a proof of a registration. If the user wants to post on myblog.bit he adds the cert to his content.json, and the peers will accept his/her new content. 
Pros: 
  - Does not requres peers to seed the auth site
  - Works even if the auth site deleted

Cons:
  - No way to revoke cert

To make any of it possible the user has to use the same auth_address for talk.zeronetwork.bit and myblog.bit. (unique auth_address generated for currently every user using the same BIP32 xprv, but its easily possible to copy the identity)

## _Update:_
I think i will go for the second solution.

Required modifications:
- [x] File for specify rules where the third-party signed can be stored Contains: trusted authorization services, allowed files/size limit using regexp, directory where it will be stored, banned users.
- [x] Modifications on web interface that allows to use the same auth_address on multiple sites
- [x] A sample trusted authorization service page
- [x] Protocol command to get all current commented users data file (changedSince)

**Comment by HelloZeroNet** [comment]
example cert address: `16YsjZK9nweXyy3vNQQPKT8tfjCNjEX9JM#web/nofish@id.zeronetwork.bit`
 - 16YsjZK9nweXyy3vNQQPKT8tfjCNjEX9JM: user's auth address
 - web/: auth type used for registration (namecoin/, bm/, email/ etc.), this allows site users to ban some registration types or give them more trust (more space)
 - nofish: username, has to be unique per site
 - id.zeronetwork.bit: the auth provider address

On successful registration the site owner signs this string and sends the sign to the user.

The user saves it and if he want to post on a site he adds the signature to his content.json in `auth_cert_sign` field and the cert address to `auth_cert_address`

example for users.json
```json
{
"directory": "data/users",
"trusted": {
  "id.zeronetwork.bit": ["1IDzero2NXVi1RDPDgf5617UoW7xA6YrhM9F"]
},
"deny": ["/nofish@id.zeronetwork.bit"],
"rules": [
  ["/nofish@id.zeronetwork.bit", { "max_size": 40000 }],
  ["*", { "max_size": 20000, "files_allowed": "data.json"}],
]
}
```

**Comment by HelloZeroNet** [comment]
Added in 7e4f6bd38ecadb871a537c27a70a161d0a36816e

**Comment by gerardo-junior** [comment]
I am building a site @wikificha and would like to publish in zeronet too and I am using continuous integration but realized that there is no way to delegate a deploy token and then remove, the only thing I can do is give the master key and this is very insecure if you work with multiple developers or use continuous delivery services

any updates on this?
