### ISSUE TITLE
get list of user's certificates

### ISSUE THREAD

**Issue by dnelband** [HelloZeroNet/ZeroNet#883]
how can i get a list of all user certificates? i want to create a certificate for users for this site (IFS - http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/) but in order to check if a user has already created an ifs.anonymous certificate i need to get a list of the user's certificates.
is it possible in zeronet? if not is there a hack or a way to go around it?

**Comment by HelloZeroNet** [comment]
Currently due privacy reasons there is no way to list certificates, so I would recommend separate buttons for "create new identity" and "select identity"

**Comment by mishfit** [comment]
If the cert already exists and there's only one valid cert signer for the site then 

siteInfo.cert_user_id will not be null when you call the ["siteInfo"](http://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#siteinfo) API command.

**Comment by purplesyringa** [comment]
@HelloZeroNet Can this be closed?
