### ISSUE TITLE
Feature request for zeroupdate zite

### ISSUE THREAD

**Issue by kavamaken** [HelloZeroNet/ZeroNet#886]
It would be nice if zeroupdate zite has a zeronet version on it so it could be easier to see witch version it has now.
Many thanks and sorry if my request is wrong addresed.

**Comment by HelloZeroNet** [comment]
You added a simple page for it:
![image](https://cloud.githubusercontent.com/assets/10350359/24811183/38f30122-1bc5-11e7-8c16-03a6bd4d13ed.png)

**Comment by kavamaken** [comment]
Thanks a lot!!!
