### ISSUE TITLE
Selenium was not installed in Travis testing environment

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#889]
Some Travis tests require `selenium` so that they can see what's going on inside the HTML page. These tests are skipped because you forget to pre-install `selenium` in the Travis testing box.

https://travis-ci.org/HelloZeroNet/ZeroNet/builds/219820681
```
SKIP [1] /home/travis/build/HelloZeroNet/ZeroNet/src/Test/conftest.py:172:
Test requires selenium + phantomjs: No module named selenium
```

**Comment by AwesomeTurtle** [comment]
#890

**Comment by HelloZeroNet** [comment]
Adding selenium does not fixes it, because it also requires phantomjs and zeronet client running

**Comment by MuxZeroNet** [comment]
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS

Thanks for the timely PR. Travis says PhantomJS is actually pre-installed. The error disappeared. There is another issue here:
```
SKIP [2] /home/travis/build/HelloZeroNet/ZeroNet/src/Test/conftest.py:181: Test requires zeronet client running: [Errno socket error] [Errno 111] Connection refused
```

The UI server wasn't running.

**Comment by AwesomeTurtle** [comment]
#890 (updated)

**Comment by HelloZeroNet** [comment]
Thanks!

**Comment by HelloZeroNet** [comment]
Unfortunetly `docker run -d -v $PWD:/root/data -p 15441:15441 -p 127.0.0.1:43110:43110 nofish/zeronet` does not reflect the latest version, so it makes the testing pointless. So we need other way to run the client.

**Comment by mkg20001** [comment]
You can just use `docker build -t zeronet .` to build the image in the container

**Comment by AwesomeTurtle** [comment]
When docker does not find an image with `docker run` command, it will automatically build it with `Dockerfile`.
But in the `Dockerfile`, we said: 

```
ADD . /root/data
```

So we can not currently fetch data from a pull request or specific branch. :confused:

**Comment by mkg20001** [comment]
See #894

**Comment by mkg20001** [comment]
@AwesomeTurtle This does not matter if building locally

**Comment by grez911** [comment]
@HelloZeroNet Pull request has been successfully merged. Can the issue be closed?
