### ISSUE TITLE
[API request] Open post's links in a new tab

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#897]
Isn't a good practice open external links in the same tab.
Nofish said:

> Actually this is because technical limitation. ZeroNet running sites sandboxed iframe where the links with target="_blank" does not work properly in every browser.
> Probably related to https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

iframes can communicate with the main frame with JavaScript. ZeroNet can create a API for it.
When user clicks a link (that is modified for the code work), then the main receives this message with the link metadata, and then does the work.

**Comment by mishfit** [comment]
The wrapper already contains this [feature](https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/media/Wrapper.coffee#L167-L175): https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/#wrapperopenwindow-_url-target-specs

**Comment by Plasmmer** [comment]
How site owner can achieve it in HTML?

**Comment by mishfit** [comment]
I think the changes would be [here](https://github.com/HelloZeroNet/ZeroMe/blob/master/js/utils/Text.coffee#L40-L50).

Essentially, strip out `target="_blank"` in any URLs and replace it with an "onclick" event call to a new function which uses the API.

The new function would look similar to `handleLinkClicked` (see [here](https://github.com/HelloZeroNet/ZeroMe/blob/8136f5b24f231fd2f57f8aa07a96c7aa29af068f/js/ZeroMe.coffee#L117)) but would call the API.

**Comment by mishfit** [comment]
Also, I'm not sure if you noticed that you pushed your linked issue to a repo that isn't the original [ZeroMe](https://github.com/HelloZeroNet/ZeroMe)

**Comment by border0464111** [comment]
So, for `target="_blank"` it work as designed.
 
Good practice on zeronet is to use `wrapperOpenWindow _url` from zeroframe. 

closing ?
