### ISSUE TITLE
[API request] Donate to seeders

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#898]
When a custom blockchain comes to ZeroNet, will be nice a system where a site owner automatically donates tokens to users that are seeding. Also other seeders can donate to other seeders.

**Comment by HelloZeroNet** [comment]
Well i'm not sure if its a good idea, because it would encourages people to run many clients on the same machine an by that flood the network.

**Comment by Plasmmer** [comment]
Moved to: https://github.com/ZeroNetJS/zeronet-js/issues/47.
