### ISSUE TITLE
[API request] Sites with optional seeding

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#899]
Site owners will can activate this option, then users will can get his site from peers but after close the tab, the site will be removed. It will open a horizont to a lot of possibilities:

- External images (image from site B on site A);
- Social gadgets (ZeroMe's like button, embedded post, etc);
- External APIs;
- Search engine scrapping website's pages;
- Search engine getting Wiki's pages;
- etc.

**Comment by border0464111** [comment]
do you mean: 
1 loading the site,
2 loading all the optional 
3 delete all optionals on tab close
? 

if so, it seem like a huge waste on bandwith to me.

**Comment by mishfit** [comment]
@Plasmmer have you seen the example of optionally seeding a user's images in ZeroMe?

It seems like you're talking about something that already exists...all except for the automatic deletion of images, which as @border0464111 pointed out seems like a waste of cycles (from a network/CPU standpoint).

**Comment by Plasmmer** [comment]
Thanks all for showing your GORGEOUS knowledge, but please show the intuitivity and the capacity of understand.
Please read again what I'm propusing, count till 20, then return to the comments.

**Comment by border0464111** [comment]
Well, Your english is not top quality. I did a reformulation and asked if it's what you meant. Im only trying to understand here. 

No need to get salty about that, it will help either you and me. Best is to be excellent to each others.

**Comment by mishfit** [comment]
You are asking for features which exist (and some that shouldn't exist). It might take some work on your part to implement them in your own site...we're here to help.

To that end, I'm going to break down your original comment:

> Site owners will can activate this option, then users will can get his site from peers but after close the tab, the site will be removed. It will open a horizont to a lot of possibilities:
- A site owner already has the option to include "merger" sites.
- Having the optional site removed on the closing of the browser (or tab/window) is unnecessary. However, you can implement that on your own (the browser can let you know when it is closing and you can intercept that event).

> External images (image from site B on site A);
- That's how ZeroMe works...the images are on a merger site (called a "hub" for some reason).
> Social gadgets (ZeroMe's like button, embedded post, etc);
- There's nothing preventing you from cloning ZeroMe, making it a merger site of a site you already own and inserting content from ZeroMe into your site (including a "like button")
>External APIs;
> Search engine scrapping website's pages;
> Search engine getting Wiki's pages;
>etc.
- Take a look at ZeroHello. It has an example implementation of pulling data from various sites and aggregating that data. Once aggregated, one could implement a search on that data

**Comment by mkg20001** [comment]
I think the feature he was talking about was to only temporary download a zite on a proxy and then remove it, but this is (like already pointed out) a waste of resources
