### ISSUE TITLE
No way to monitor or limit bandwidth usage.

### ISSUE THREAD

**Issue by Oxilic** [HelloZeroNet/ZeroNet#9]

**Comment by HelloZeroNet** [comment]
Unfortunately the library currently used for networking (ZeroMQ) don't offer bw limitation or network usage information. It could be fixed by removing ZeroMQ and rewriting the communication without it.

At current stage ZeroNet is not suitable to distribute large files/sites, so its not priority.

**Comment by shakna-israel** [comment]
Something like [Celery](http://www.celeryproject.org/) should be able to monitor the usage, and perhaps limit it, in the long run, with gevent compatibility. That being said, it might be a bit of a hack to use.

**Comment by HelloZeroNet** [comment]
I think the a simple gevent StreamServer will do the work. Not really take advantage of these messaging libraries.
Something with built-in rate limiting and maybe client priority will be nice, but I don't know anything like this for python :(

**Comment by iShift** [comment]
Now we have http://127.0.0.1:43110/Stats

**Comment by border0464111** [comment]
http://127.0.0.1:43110/Stats solve this issue indeed. closing ?
