### ISSUE TITLE
Private key validation method for UIWebSocket

### ISSUE THREAD

**Issue by Rask** [HelloZeroNet/ZeroNet#90]
I tried skimming through documentation and source code, but didn't find anything of use.

It would be great to have a simple private key validation method available for the ZeroFrame API, e.g.

```
Site.cmd('wrapperPrompt', ['Please give private key:', 'password'], function(private_key) {
     var privateKeyValid = Site.cmd('validatePrivateKey', private_key, callback);
});
```

There is `siteSign` available, but to my understanding it isn't that usable for "password protected" content and such.

**Comment by HelloZeroNet** [comment]
If you want to just validate it then its probably better to do on client-side. Eg. you can use this library: http://bitcore.io/playground/#/address

**Comment by Rask** [comment]
That works wonders. Thanks for sharing!
