### ISSUE TITLE
[Feature] Protect sites with GIT versioning

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#900]

**Comment by Adrianzo** [comment]
you should have a repo somwhere and use a script and a hook to deploy (signing, updating, etc).

**Comment by Plasmmer** [comment]
I'm talking about support a versioning system by default.

**Comment by border0464111** [comment]
Is this a duplicate of https://github.com/HelloZeroNet/ZeroNet/issues/859 
or we are talking about something else ?

**Comment by Plasmmer** [comment]
Moved to: https://github.com/ZeroNetJS/zeronet-js/issues/8.
