### ISSUE TITLE
User data content.json missing "cert_user_id"

### ISSUE THREAD

**Issue by mishfit** [HelloZeroNet/ZeroNet#901]
`ContentManager.py` checks user content.json for "cert_user_id"...however, when I sign a file the cert_user_id is not included in the user content.json. Everything else looks okay:
```json
{
 "address": "1Gyhw9AfTojuc42h6nHmV9QCgroTXG9WRt",
 "files": {
  "user.json": {
   "sha512": "67a27e6e9a1154adc93e24bcdef2a7430983a8b6bb000f14f1860597a0b94977",
   "size": 5082
  }
 },
 "inner_path": "data/users/128WNjzSyM9kEFCCHQJVSEp2y81ojrcKs1/content.json",
 "modified": 1491897904,
 "signs": {
  "128WNjzSyM9kEFCCHQJVSEp2y81ojrcKs1": "HKSwACHjMksJgDwhPP7mOjcHnjJ2oeSzu/kMq+lgCJXZd+HYZRz44ei9BaoIpqhCnqwSgO1hVVfmGwat6wBtlN0="
 }
}
```
^ It's just missing "cert_user_id"

**Comment by HelloZeroNet** [comment]
I tried to reproduce it: 
 - created a new zeroblog clone
 - published an user file
 - modified contentmanager to remove cert signatures by adding:
```
        del new_content["cert_auth_type"]
        del new_content["cert_sign"]
        del new_content["cert_user_id"]
```
 - tried to sign & publish this file to remote machine, but it got rejected: `[2017-04-11 06:10:24,423] WARNING  Site:1NLjoF..qPa7 Verify sign error: KeyError: 'cert_user_id' in ContentManager.py line
797 > ContentManager.py line 640`

Running `zeronet.py siteVerify 1NLjo...` locally also drops error.

do you have other details how to reproduce it?

**Comment by mishfit** [comment]
You can get to it by loading my development site: http://127.0.0.1:43110/1Gyhw9AfTojuc42h6nHmV9QCgroTXG9WRt

![contrechess-signup-signing-001](https://cloud.githubusercontent.com/assets/817064/24917569/d6e0935e-1e9a-11e7-9752-10859c746c0e.gif)

The section of code that writes the file is located [here](https://github.com/ContreChess/ContreChess/blob/master/src/js/signup/signup.js#L126-L147) but I've pulled out an excerpt:
```javascript
// 2. sign user address, plus cert type, plus user address (again) in base64
    //    using site's user content address private key
    var textToSign = _self.model.get('btcAddress') + '#web/' + _self.model.get('userName'),
        cert = currency
          .btcSignMessage(_self.contentAddress, textToSign)
          .toDER()
          .toString('base64');

    return zeronet.addCertificate(cert, _self.model.get('userName'))
      .then(function () {
        return zeronet.selectCertificate('contrechess.io');
      })
      .then(function (response) {
        // 3. write the model to the file system
        var fileContent = btoa(unescape(encodeURIComponent(JSON.stringify(_self.model.toJSON(), null, '  '))));
        return zeronet.writeFile(filePath, fileContent);
      })
      .then(function (response) {
        return zeronet.publish(filePath);
      })
      .then(function (response) {
        console.log(response);
        // 4. handle errors or process notifications
      });
```
The file it is trying to save is "user.json"...it creates content.json (it's just missing "cert_user_id"). I've looked at "nanasi" (http://127.0.0.1:43110/16KzwuSAjFnivNimSHuRdPrYd1pNPhuHqN) and it appears to create the cert_user_id for that site.

**Comment by HelloZeroNet** [comment]
There was an error that did not set the added certificate correctly. Fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/1a7a22eb913865505db152037f579d18addf7b65

Now the cert selection is working for me, but the generated certificate drops "Wrong encoding" error.  (the signature should be 65 char long, but it generates 71 char long one)

**Comment by mishfit** [comment]
Awesome, thanks, I'll play around with that.
