### ISSUE TITLE
[Feature - Proxies] .txt login

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#902]
After user receives his privatekey, a download button will appear. Also user will can login by simply uploading this file.

**Comment by mishfit** [comment]
I am trying to understand this issue.

Is the intent to have multiuser-enabled ZeroNet instances push the user's private key down to the browser by downloading a text file with the key in it?

**Comment by Plasmmer** [comment]
Yes, a text file containing the privatekey will be generated and a button with download link will appear. User will can also upload this privatekey in the login form.

**Comment by border0464111** [comment]
Cleartext files with private keys is a bad security approach IMO, Let users manage keys the way they want.

**Comment by Plasmmer** [comment]
> Let users manage keys the way they want

It can be heartbreaking and sad to read this, but this commotion ends when we remember that we are in a network where the IDs manager is CENTRALIZED and communications with Clearnet are constant and without intutive options for the casual user to change/know that.
I know a lot of open-source services that allow you to download privatekeys / seeds in plain text. In fact the user will not lose their options, but only have one more.
ZeroNet in the future will need casual users, those who have difficulty simply opening a context menu. Believe me, they are many and we will need them if we want a popular ZeroNet. Of course, firstly accessing ZeroNet on a proxy is the first step that will entice them to download fully, and secondly copy a privatekey, paste somewhere and then save is not very comfortable for casual users.
Regarding the security, the privatekey can be saved into a encryted file (then user can choose a password), or also be saved into a pendrive that when inserted will do the login (more like Google does).

**Comment by Plasmmer** [comment]
Unfortunately people want to come up with problems for everything. Steve Jobs himself suffered this with the Safari project.

**Comment by border0464111** [comment]
oh I taught you where talking about site private key, 

It can make sense for a local install, but one should ever upload his private key into a remote proxy he don't own.

**Comment by mishfit** [comment]
@Plasmmer dude, chill out.

I agree with @border0464111 that passing around private keys in plain text is a bad idea. Most people that are even remotely familiar with cryptography would think that is a bad idea.

ZeroNet adoption would increase via a mobile client or even simpler desktop bundles.

Proxies are not trustworthy (implicitly...not an insult towards proxy operators). So why would one want to pass in a private key to an entity one doesn't trust?
