### ISSUE TITLE
High memory usage in a short time and be killed

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#903]
Yesterday I updated https://fuckcf.cf/ public proxy, then I found ZeroNet would be killed in short time.
I viewed the usage statistics and found the memory usage was increase in a short time, then ZeroNet was killed. But before that, ZeroNet is rarely be killed(for reduce memory usage, I replaced Apache with Caddy, later fewer times be killed).
So how to limit ZeroNet's memory usage?

**Comment by HelloZeroNet** [comment]
Well it's not easy to tell, you can try remove big sites like zeromail

**Comment by l5h5t7** [comment]
I don't think that, I have seed ZeroMail for a long time without any problem. I think there are single big files cause this problem.
Are there any ways to limit single big files?
BTW: There is no option to limit user add non-optional big sites, isn't it? Any users can change size limit for site without master's permission.

**Comment by HelloZeroNet** [comment]
I have created an issue to restrict adding big sites: https://github.com/HelloZeroNet/ZeroNet/issues/907

**Comment by l5h5t7** [comment]
ZeroNet is still killed recently on https://fuckcf.cf/ public proxy.
If anyone request a file which is bigger than free memory from public proxy, ZeroNet will try to download this file then ZeroNet will be killed due to out of memory.
So I think we need a new limit: file size limit.

**Comment by HelloZeroNet** [comment]
I have added max file limit defaults to 10MB: https://github.com/HelloZeroNet/ZeroNet/commit/aacde3361401f37f895ba2782e9d91ef464111fe
I hope it helps...
