### ISSUE TITLE
hello,could you tell me how to build windows exe from source code in github.

### ISSUE THREAD

**Issue by clamever** [HelloZeroNet/ZeroNet#905]
i install the .exe windows from the link in the README.MD.now i want to build windows .exe from source code.but i cannot found  how to do that.

**Comment by HelloZeroNet** [comment]
here is the script I use: https://github.com/HelloZeroNet/ZeroBundle/blob/master/compile/compile_win.cmd

**Comment by clamever** [comment]
very thanks!!
