### ISSUE TITLE
How to start in debug mode on Windows (gevent not found)

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroNet#908]

**Comment by Plasmmer** [comment]
@HelloZeroNet

**Comment by mishfit** [comment]
This may be a silly/unnecessary question...but do you have python27 installed? If so, can you run
```cmd
pip install gevent
```
(you might need to do this for `msgpack-python` if you don't have that either)

**Comment by Plasmmer** [comment]
@mishfit

Yes, I have python27 and I'd installed gevent successfully. Then I started zeronet.py, but:

Windows icon was closed an I received a message that msgpack was not found. Then I tried to install via pip, but received this message:

>   Could not find a version that satisfies the requirement msgpack (from versions
> : )
> No matching distribution found for msgpack
