### ISSUE TITLE
Plugin for password based auth for the web interface

### ISSUE THREAD

**Issue by HelloZeroNet** [HelloZeroNet/ZeroNet#91]
Would be handy to allow access ZeroNet from anywhere (eg. mobile) using a box that running the client.
Cookie or Http auth based (logout?).

**Comment by Rask** [comment]
Do you mean that a server runs ZeroNet and allows mobile/similar clients to access ZeroNet through it using auth? Password protected proxy in essence?

**Comment by HelloZeroNet** [comment]
Yes, now it has ip based restriction: `--ui_restrict 123.456.678.982`, but it not works when you are in ip changing environment (eg. mobile)

**Comment by HelloZeroNet** [comment]
Currently working on this, probably it will be cookie based, i try to find a solution to make it more secure (does not send password as cleartext) on non-https connection. (similar to this: http://www.lightcubesolutions.com/blog/?p=47)

**Comment by HelloZeroNet** [comment]
Unfortunately sandboxed iframe ajax requests does not send the cookies, so the sites that using ajax to load data will not work.

As result i will mark ajax as unsupported method of loading data, instead use zeroframe api [fileGet](http://zeronet.readthedocs.org/en/latest/site_development/zeroframe_api_reference/#fileget-inner_path) method which is the same and probably faster.

**Comment by HelloZeroNet** [comment]
added in: https://github.com/HelloZeroNet/ZeroNet/commit/a93ca2c3b4e1d2fa95ad96fb04804e397c4dcb88

**Comment by keith24** [comment]
I am getting

    zeronet.py: error: unrecognized arguments: --ui_password mypassword

with v0.5.4.  Should I start a new issue or am I doing it wrong?

**Comment by ysc3839** [comment]
You should enable the UiPassword plugin. See plugins folder.
