### ISSUE TITLE
PyElliptic is officially deprecated. Consider using another crypto library.

### ISSUE THREAD

**Issue by MuxZeroNet** [HelloZeroNet/ZeroNet#917]
Yann [announced](https://github.com/yann2192/pyelliptic/issues/50#issuecomment-297018932) that PyElliptic is officially **deprecated**.

Please consider using another wrapper or crypto library, such as [pyOpenSSL](https://pypi.python.org/pypi/pyOpenSSL), [cryptography](https://cryptography.io/en/latest/), [PyNaCl](https://pynacl.readthedocs.io/) or [pySodium](https://github.com/stef/pysodium). Here is a crypto library choice discussion among Ethereum devlopers: ethereum/pydevp2p#58

[pyOpenSSL](https://pypi.python.org/pypi/pyOpenSSL) - a OpenSSL wrapper library

[cryptography](https://cryptography.io/en/latest/) - the famous, actively maintained Python cryptography library. If used, it needs to be included in `requirements.txt`

[PyNaCl](https://pynacl.readthedocs.io/) and [pySodium](https://github.com/stef/pysodium) are both wrappers for libsodium. PyNaCl is mentioned and recommended in cryptography's documentation. The libsodium provides Curve25519 for public key encryption, Salsa20 + Poly1305 for secret key encryption, and Ed25519 for digital signatures.

**Comment by HelloZeroNet** [comment]
Unfortunately Nacl is not compatible with the crypto we use, pyopenssl does not have functions we need (eg aes encryption). Cryptography probably could work, but has binary dependencies and requires compilation to every platform/openssl version, which could reduce the portability.
Pyelliptic still has some support by the bitmessage project

**Comment by ofek** [comment]
[https://github.com/pyca/cryptography](https://github.com/pyca/cryptography)'s `pip install cryptography` only requires compilation on linux. Binary distributions are available for Windows and macOS.

**Comment by MuxZeroNet** [comment]
On the Privacy mailing list, Peter Surda wrote:

> Hello and thank you for the info.
> 
> The PyElliptic code that's in PyBitmessage is a modified version of PyElliptic (i.e. a fork). I'm not aware of any issues with it, those that existed were fixed (e.g. OpenSSL 1.1 support, library locator, using a different hash algorithm). I tested it on a broad range of operating systems.
> 
> I'll keep it for the time being as it is.
> 
> Peter Surda  
> Bitmessage core developer

Bitmessage developer did fork PyElliptic and fix a few bugs, but for the long term it is worth making ZeroNet work with pyca/cryptography.

**Comment by radfish** [comment]
I extracted the pyelliptic fork from Bitmessage source and called it  pyelliptic v2.0:
https://github.com/radfish/pyelliptic
See section Version for details. In brief, bitmessage forked from v1.3, I extracted the commits ffrom Bitmessage repo and re-applied them, so history is preserved.

Tested ZeroMail with this pyelliptic 2.0.1: sending message works (I sent to myself and message appeared in Sent, but I did not receive it; not sure if self-sending is supposed to work or not).

No change to zeronet is necessary. Except updating requirements.txt to pyelliptic>=2.0.1. I asked Yann of pyelliptic to upload this v2.0.1 fork to PyPi. Once it's on PyPI, we can update requirements.txt. If this doesn't work then I will create a pyelliptic2 package on PyPI.

**Comment by HelloZeroNet** [comment]
Great work! I can confirm the ECIES functions works with https://github.com/radfish/pyelliptic on both openssl 1.0.2q and 1.1.1b using windows.

**Comment by radfish** [comment]
@HelloZeroNet PyBitmessage folks are themselves moving away from pyelliptic apparently:

Dmitri Bogomolov g1itch
> I'm going to port pybitmessage to coincurve

They are saying that ECIES might be doable with eciespy package plus coincurve package -- are those sufficient for ZeroNet?


Peter Šurda
> I know that in the past, libsecp256k1 didn't contain encryption, but now it does. Are you sure you still can't do ECIES with it?

Dmitri Bogomolov g1itch
> https://gist.github.com/dahlia/795b4bd95ddfe6329a723cd2869220ae
> https://kigawas.me/eciespy/
 
Discusson here: https://gitter.im/Bitmessage/PyBitmessage?at=5ca11e447ecbdc29cad9f65a
