### ISSUE TITLE
small spelling error in dropdown

### ISSUE THREAD

**Issue by haschimoto** [HelloZeroNet/ZeroNet#921]
"avalible"= should read "New version available":
![snap 2017-04-30 at 15 49 28](https://cloud.githubusercontent.com/assets/20817185/25564876/bb2ae91c-2dbc-11e7-8be7-b451c21752dc.png)

**Comment by ysc3839** [comment]
https://github.com/HelloZeroNet/ZeroHello/blob/901abf0ec4b9254752a03fe97a1e80619f820a93/js/Head.coffee#L7

**Comment by HelloZeroNet** [comment]
Thanks, fixed!
