### ISSUE TITLE
Minimum site size override

### ISSUE THREAD

**Issue by kzshantonu** [HelloZeroNet/ZeroNet#922]
Any way to do that? Thanks

**Comment by MuxZeroNet** [comment]
> If anyone could tell me how to increase the global site size limit from 10mb, would be helpful. Thanks.

**Comment by kzshantonu** [comment]
I'm hosting a proxy and was wondering if there's a way to increase the global limit for sites from the default 10MB to say 50MB

**Comment by HelloZeroNet** [comment]
You can do by starting it using `zeronet.py --size_limit 50`
