### ISSUE TITLE
Idea: .bit domain redirection.

### ISSUE THREAD

**Issue by ysc3839** [HelloZeroNet/ZeroNet#926]
When accessing `one.bit` it redirects to `two.bit`.

**Comment by MuxZeroNet** [comment]
:confused: This seems creepy. Please explain.

**Comment by ysc3839** [comment]
@MuxZeroNet Sorry for my bad English. It means when I goto `http://127.0.0.1:43110/one.bit`, it can redirect to `http://127.0.0.1:43110/two.bit`.

**Comment by April93** [comment]
Just point `one.bit` to the same site that `two.bit` points to. I do this for kaffiene. `search.kaffie.bit`, `kaffiene.bit`, `zerosearch.bit` and `0search.bit` all work and point to the same address.

**Comment by MuxZeroNet** [comment]
Regarding .bit domain features, I suggest adhering to the spec of NameCoin blockchain, instead of implementing separate features in ZeroNet.

**Comment by grez911** [comment]
@ysc3839 @HelloZeroNet Close?
