### ISSUE TITLE
Bug: coffeescript wrong compilation paths with custom data_dir

### ISSUE THREAD

**Issue by grez911** [HelloZeroNet/ZeroNet#936]
I have the following conditions:
OS: Arch Linux
Zeronet is installed in `/opt/zeronet/`
Directory with zites is `/var/lib/zeronet/`
My newly created site is in
`/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/`

Config /etc/zeronet.conf:
```
[global]
data_dir = /var/lib/zeronet
log_dir = /var/log/zeronet
```

When I run zeronet with the following command:
`python2 /opt/zeronet/zeronet.py --config_file /etc/zeronet.conf --debug`

and go to my zite in browser, these alerts are popping:
```
/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/Class.coffee compile error: File not found: /opt/zeronet/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/Class.coffee
/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/ZeroFrame.coffee compile error: File not found: /opt/zeronet/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/ZeroFrame.coffee
```

in logs I have:

```
[20:48:37] - Running: "/usr/bin/coffee" --no-header -p "var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/ZeroFrame.coffee" (Done in 0.09s)
[20:48:37] - /var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/ZeroFrame.coffee Compile error: File not found: /opt/zeronet/var/lib/zeronet/13KHcN8FvmY9UgZ2DWAc2323f28qE5LZic/js/utils/ZeroFrame.coffee
```

**Comment by grez911** [comment]
Changing this string: https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Debug/DebugMedia.py#L88
from
`file_path_escaped = helper.shellquote(os.path.join(*file_path.split("/")))`
to
`file_path_escaped = helper.shellquote("/" + os.path.join(*file_path.split("/")))`
helped me. I hope someone will fix this in a more proper way.

**Comment by grez911** [comment]
Created pull request: https://github.com/HelloZeroNet/ZeroNet/pull/942

**Comment by grez911** [comment]
Created pull request: https://github.com/HelloZeroNet/ZeroNet/pull/942

**Comment by HelloZeroNet** [comment]
Thanks
