### ISSUE TITLE
Cannot encode Base64 value: 0\n

### ISSUE THREAD

**Issue by kavamaken** [HelloZeroNet/ZeroNet#941]
![zeronet1](https://cloud.githubusercontent.com/assets/5235877/26319013/85731b54-3f47-11e7-9ef3-26aae43e7185.png)
![zeronet2](https://cloud.githubusercontent.com/assets/5235877/26319011/856df142-3f47-11e7-8acd-43889d24733b.png)
![zeronet3](https://cloud.githubusercontent.com/assets/5235877/26319012/856f1e6e-3f47-11e7-9106-2e8acc53188d.png)
Any page wont startup.
version is 0.5.5-2081 at windows.

**Comment by HelloZeroNet** [comment]
Are you running ZeroNet in debug mode?
Have you modified any default running parameters? (eg. using zeronet.conf)

**Comment by kavamaken** [comment]
Yes, I use zeronet.conf to turn off tor.
The message appears regardless of debug mode is on or off.

**Comment by imachug** [comment]
@shortcutme, Could you test #974 which fixes this issue?

**Comment by HelloZeroNet** [comment]
Fixed in latest rev: https://github.com/HelloZeroNet/ZeroNet/commit/1f83b6691b7864a35c1466ee23a14628f28ec974
