### ISSUE TITLE
portchecker.co has been supported HTTPS

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#945]
portchecker.co has been supported HTTPS recently, and all page are redirected to HTTPS version.
This causes some users report their port is closed, but ZeroNet detected that the port is open.
So src/File/FileServer.py should replace the old HTTP address to the new HTTPS address.
https://portchecker.co/check

**Comment by HelloZeroNet** [comment]
Thanks, nice finding, fixed!
https://github.com/HelloZeroNet/ZeroNet/commit/ed11ae283fc28f98d870602af7b0a6aba5bde277
https://github.com/HelloZeroNet/ZeroNet/commit/89bb12de71b0aadfb4f02aee73747dc1c38dd69a
