### ISSUE TITLE
Assign a random fileserver_port rather than stationary 15441 at first start

### ISSUE THREAD

**Issue by jerry-wolf** [HelloZeroNet/ZeroNet#955]
Network administrator can block ZeroNet by blocking TCP 15441 port's inboard and outboard. Single user can set another inboard port, but it's impossible to change others inboard port, then the user whois TCP 15441 port is blocked can only connect to the peers whois FileServer port is changed.
If ZeroNet assign a fileserver_port at every start, it will cause trouble to the users who need forward port manually, but assigning a random file_server at first start then use this port in future won't bring extra trouble.
And perhaps we can recommend users using port 80 and 443, it helps some user whois network have a whitelist firewall connect to ZeroNet.
Another user create a issue 1 year ago. (#392)

**Comment by mkg20001** [comment]
I think it should be optional.

**Comment by MuxZeroNet** [comment]
Whonix developers plan to put ZeroNet into their privacy-respecting operating system. They are working on a set of Tor control port firewall rules. The current rule for ZeroNet is to allow a listening port 15441. If FileServer port is to be randomized, we should discuss this issue with @adrelanos

Nevertheless, this is not how Internet censorship works. Changing the FileServer port will not in any sense disguise the fact that you are using ZeroNet. I believe even the worst firewall software you currently know of examines packet payload, looking for static strings. More advanced Deep Packet Inspection techniques look for statistical features such as packet length, timing patterns and netflow directions. You should read @blanu's [Dust paper](http://www.blanu.net/Dust.pdf) to learn more about these packet inspection techniques already deployed.

ZeroNet network protocol is not a Pluggable Transport protocol. The protocol itself is not yet "blocking resistant," as Wiley puts. Without Tor, ZeroNet does not make you anonymous, either. There are a lot of research and programming to be done. I believe Tamas does not have the funding or resources to implement Pluggable Transports or to make ZeroNet protocol indistinguishable. The community do not ignore this issue, but for the time being, the community always recommend you use Tor Always mode.

**Comment by adrelanos** [comment]
We can also cope up with a random port, but it's not pretty.

Specifically if there is an option to set this port on command line / by
config, ZeroNet can still work in Whonix.

Why use a random port, if it provides no benefit?

**Comment by imachug** [comment]
@HelloZeroNet I think this is currently implemented. Can we close this issue?
