### ISSUE TITLE
Content signing failed

### ISSUE THREAD

**Issue by tetsaicn** [HelloZeroNet/ZeroNet#956]
Content signing failed，
the tree：
├───about
├───archives
│   ├───2016
│   │   ├───11
│   │   └───12
│   ├───2017
│   │   ├───01
│   │   ├───03
│   │   └───05
│   └───page
│       └───2
├───categories
│   ├───????
│   ├───???
│   ├───???
│   └───???
├───css
├───data
│   └───users
├───donate
├───fonts
├───img
│   ├───footer
│   ├───gallery
│   └───random
├───js
│   └───gallery
├───liuyan
├───page
│   └───2
├───read
│   ├───2017-happy-new-year
│   ├───blog-enable-https-protoco
│   ├───boom-html5
│   ├───google-chrome-will-label-
│   ├───hello-newblog
│   ├───pptp-vpnserver
│   ├───red-bag-time
│   ├───video-player
│   ├───wifi-key
│   ├───wordpress-for-the-https
│   ├───WordPress-to-hexo
│   └───??????
└───tags
    ├───2017
    ├───360
    ├───api
    ├───CDN
    ├───chrome
    ├───google
    ├───googlechrome
    ├───hexo
    ├───html5
    ├───http
    ├───https
    ├───JS
    ├───key
    ├───pptp
    ├───wifi
    ├───wifikey
    ├───wifi????
    ├───wifi??
    ├───WordPress
    ├───???
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───?
    ├───???
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───???
    ├───??
    ├───????
    ├───????
    ├───???
    ├───???
    ├───???
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    ├───??
    └───??

content.json is ok

**Comment by tetsaicn** [comment]
content.json: Site too large 10838660 > 10485760, aborting task..

**Comment by mkg20001** [comment]
You may want to set the property `optional` in the content.json to mark all images/videos/big files/etc as optional files
