### ISSUE TITLE
zeronet.conf documentation

### ISSUE THREAD

**Issue by tiferrei** [HelloZeroNet/ZeroNet#958]
Hi there,
I would like to customise a bit the startup of ZeroNet, mainly by passing Tor to the Browser ports and setting it to open on Tor, etc.
I can do this easily on the CLI from source with the parameters, this doesn't seem to be so easy with the GUI though. I was wondering if the `zeronet.conf` file on the data dir could take this kind of parameters and options? Would be cool to have the same level of customisation.

Thanks,
tiferrei

**Comment by MuxZeroNet** [comment]
Yes, it can.
```ini
[global]
tor_controller = 127.0.0.1:9151
tor_proxy = 127.0.0.1:9150
```

**Comment by tiferrei** [comment]
Does it support pretty much all the script arguments then? Are there any extra ones, any documentation?

**Comment by HelloZeroNet** [comment]
you can use the same ones as arguments. To list it and get help use `zeronet.py --help`
