### ISSUE TITLE
OptionalManager not working with files containing space

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#961]
**Steps to Reproduce:**
1. Create new zite
2. Change `optional` entry to `^abc def$`
3. Create file `abc def` (say, `Hello World!`)
4. Sign

**Actual Results:**
`optional_files` entry in `content.json` is empty.

**Expected Results:**
`optional_files` entry in `content.json` contains `abc def` file.

**Comment by HelloZeroNet** [comment]
right now only files matching `^[a-zA-Z0-9_@=\.\+-/]*$` hashed by zeronet.

**Comment by JazzMaster** [comment]
i have a similar bug. I can limit file extensions. ok. fine. but I want to limit zite size by keeping larger content (jpegs. gifs) which otherwise load and exclude by filename or folder. This doesnt seem to be working. also, we need to deal with spaces in filenames. Its a utf issue but---lfn has been around for awhile now.

**Comment by MuxZeroNet** [comment]
> exclude by filename or folder

It's just a [Regular Expression](https://en.wikipedia.org/wiki/Regular_Expression). To exclude files by extension `.mp4`:
```json
{
    "optional": "(.*\\.mp4)"
}
```
To exclude files in a folder `updater/`:
```json
{
    "optional": "(updater/.*)"
}
```
To exclude files by a filename pattern `optional_`:
```json
{
    "optional": "(optional_.*)"
}
```

**Comment by imachug** [comment]
@MuxZeroNet, [I know Regular Expressions](https://xkcd.com/208/). But even with regex `optional/.*` `optional_files` is empty.

**Comment by HelloZeroNet** [comment]
It should work, can you please check the `log/debug.log` after the signing? (btw the files should match `"^[a-zA-Z0-9_@=\.\+\-/]+$"`, so white space is not allowed yet)

**Comment by imachug** [comment]
@HelloZeroNet, That's the problem itself. I meant that:
> even with regex optional/.* optional_files is empty
...when the only file name in `optional/` contains whitespace.

This issue is connected to file-containing-whitespace caching, not file caching in general.

**Comment by HelloZeroNet** [comment]
Since 0.6.0 space character allowed in filename.
