### ISSUE TITLE
VPS?   

### ISSUE THREAD

**Issue by nyancat18** [HelloZeroNet/ZeroNet#964]
How could i run a Zeronet node at a VPS

**Comment by HelloZeroNet** [comment]
Is it possible to install ZeroNet to a remote machine?

Yes, you have to enable the UiPassword plugin by renaming the plugins/disabled-UiPassword directory to plugins/UiPassword, then start ZeroNet on the remote machine using 
zeronet.py --ui_ip "*" --ui_password anypassword. This will bind the ZeroNet UI webserver to all interfaces, but to keep it secure you can only access it by entering the given password.

Tip: You can also restrict the interface based on ip address by using --ui_restrict ip1 ip2.
Tip: You can specify the password in config file by creating a zeronet.conf file and add [global],  ui_password = anypassword lines to it.

via https://zeronet.readthedocs.io/en/latest/faq/#is-it-possible-to-install-zeronet-to-a-remote-machine
