### ISSUE TITLE
IP False

### ISSUE THREAD

**Issue by jeddah-liu** [HelloZeroNet/ZeroNet#967]
I enconter IP False (active) every time. Even there are some connections, ie 5 or 10, but I can't download any page.

**Comment by l5h5t7** [comment]
I reported that sometimes can't access portcheck.co recently (#966). seems portcheck.co get unstable in other countries?

**Comment by Plasmmer** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/1016

**Comment by imachug** [comment]
@HelloZeroNet This issue is unrelated anymore: we query the ip via several clearnet sites and via ZeroNet protocol itself too. Can this be closed?
