### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by lym7851824** [HelloZeroNet/ZeroNet#969]
在win版本里，添加删除下载内容的功能以及导出用户数据功能

**Comment by l5h5t7** [comment]
可选文件可以删除。方法：打开 ZeroHello 的“文件”标签，选中你要删除的文件，点“删除”。
非可选文件只能随着整个站点的删除而删除。
导出用户数据的功能是不必要的。因为一些软件的常有的“导出”功能实际上是一个格式转换的功能，使得其他软件能导入数据。而目前并没有其他软件接受 ZeroNet 的数据，但是你可以轻易地使用文本编辑器打开 .json 文件，或者使用 SQLite 查看器来查看缓存的 .db 数据。如果你需要将所有数据带着走，直接复制整个目录到其他设备即可；如果只需要带着 ID 和站点数据，那就带着 data\users.json 和 data\sites.json 走即可。
另外，这个标题含义不清。希望以后提 issue 时直接在标题粗略地表达你想说的内容，如果可能的话，使用英语（主要开发者是匈牙利人，不理解中文）。

**Comment by paradise-x** [comment]
……在这下面用中文求助一下QAQ

请问我安装完zeronet确实也自动跳出浏览器页面了，但页面无论打开哪个127.0.0.1:43110/ 开头的地址都是显示

Forbidden
Invalid Accept header to load wrapper
Please report it if you think this an error.
Details:
{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "*/*", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate", 
    "HTTP_ACCEPT_LANGUAGE": "zh-cn", 
    "HTTP_CONNECTION": "Keep-Alive", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_USER_AGENT": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)", 
    "PATH_INFO": "/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
    "QUERY_STRING": "", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "53095", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "para-PC", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.2 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": "type %s | tools\\coffee\\coffee.cmd", 
        "config_file": "D:/Program Files/ZeroNet-win-dist/zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "D:/Program Files/ZeroNet-win-dist/data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": false, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "zh", 
        "log_dir": "D:/Program Files/ZeroNet-win-dist/log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": "default_browser", 
        "optional_limit": "10%", 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_host": null, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.2.1", 
    "version_python": "2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]", 
    "version_zeronet": "0.5.6 r2127", 
    "wsgi.url_scheme": "http"
}

**Comment by l5h5t7** [comment]
IE 7 太老了，微软官方已经停止维护，请更新到 IE 11 。
等等！装 IE 7 的是 XP 用户？请尽量更新操作系统，如果不能，请使用 Firefox 52 ESR 。

**Comment by paradise-x** [comment]
……不，是国内360极速浏览器（chrome内核），不过测过IE（不知道版本）也确实分版本，有的能用有的不能……谢谢解答！！我换浏览器去了

**Comment by tangdou1** [comment]
It has been solved and can be closed.
