### ISSUE TITLE
No module nammed gevent

### ISSUE THREAD

**Issue by bussiere** [HelloZeroNet/ZeroNet#97]
bussiere@kusanagi:~/WorkspaceSafe/ZeroNet-master$ ./start.py - Starting ZeroNet...
Traceback (most recent call last):
  File "/home/bussiere/WorkspaceSafe/ZeroNet-master/zeronet.py", line 9, in main
    import main
  File "/home/bussiere/WorkspaceSafe/ZeroNet-master/src/main.py", line 35, in <module>
    from Debug import DebugHook
  File "/home/bussiere/WorkspaceSafe/ZeroNet-master/src/Debug/DebugHook.py", line 1, in <module>
    import gevent, sys, logging
ImportError: No module named gevent
-- Error happened, press enter to close -

And i'am sure that i have gevent installed ...

**Comment by HelloZeroNet** [comment]
Can you run this commands please?
```
$ python -V
Python 2.7.3
$ python -c "import gevent; print gevent.__version__"
1.0.1
```

**Comment by bussiere** [comment]
My python install must be a mess :+1: 
bussiere@kusanagi:~$ python -V
Python 2.7.6
bussiere@kusanagi:~$ python -c "import gevent; print gevent.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gevent
bussiere@kusanagi:~$ sudo pip install gevent
[sudo] password for bussiere: 
The directory '/home/bussiere/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bussiere/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bussiere/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet in /usr/local/lib/python2.7/dist-packages (from gevent)
bussiere@kusanagi:~$ python -c "import gevent; print gevent.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gevent

It worked when i made a venv.

So sorry

**Comment by HelloZeroNet** [comment]
Maybe its version incompatibles, you can try to fix it using any of it: 
 - Remove the gevent package and install it again using pip 
 - Install using pip's `--user` parameter (no root needed, it installing it to user's home dir)
 - Use `apt-get python-gevent`

**Comment by bussiere** [comment]
Ok done it works thanks :)


On Thu, May 7, 2015 at 3:00 PM, ZeroNet <notifications@github.com> wrote:

> apt-get python-gevent




- Были бы кости, а мясо нарастет
