### ISSUE TITLE
¿How can i support Zeronet to have more compatibility with spanish lenguage?

### ISSUE THREAD

**Issue by Pupiloho** [HelloZeroNet/ZeroNet#971]
Hi, just how the tittle says, i see there are a few things already that are in english, id like to translate everything of the base system that is translatable.

**Comment by HelloZeroNet** [comment]
You can improve the tranlation by editing es.json files located in site's translate directory and in the client's src/Translate/languages/
plugins/MergerSite/languages
plugins/Mute/languages
plugins/OptionalManager/languages
plugins/Sidebar/languages
plugins/Trayicon/languages
directories

Thanks!
