### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by Pupiloho** [HelloZeroNet/ZeroNet#972]
When i open the default Blog i only see this, when i clone it i get the same result, i can't also access Zeroid, it gets stuck in the main logo.

![a](https://user-images.githubusercontent.com/8495728/27008288-77c256e8-4e3b-11e7-9eac-ae0af93e7348.png)

**Comment by Pupiloho** [comment]
All the other pages like Zerotalk get stuck at Initial sync progess... i see the posts in ZeroHello but this shows empty, only comment dialog without content.

**Comment by funny110** [comment]
@Pupiloho Just waiting all files downloaded.

**Comment by HelloZeroNet** [comment]
Can you check the javasript console for errors (F12)?
And please try in incognito mode (plugins disabled there)

**Comment by Pupiloho** [comment]
I see this error in network. the same happens in Edge, the files are updated, the same happens with every other page, y unpacked the app in another folder and the only thing that changed is that the Zeroid page works and the authentication service, also can publish pages, the pages were even unable to publish before that.

![sin titulo](https://user-images.githubusercontent.com/8495728/27015244-90109db2-4ed7-11e7-8525-4f4d33136ecc.jpg)
![sin titulo2](https://user-images.githubusercontent.com/8495728/27015245-9017c380-4ed7-11e7-9cdf-2f92427c8fc6.jpg)

**Comment by HelloZeroNet** [comment]
It looks weird, something with the directories, please try to open sidebar (drag topright button to left) and press Rebuild.
I will try to reproduce this error.

**Comment by Pupiloho** [comment]
I also tried it before with the blog, didn't worked, i tried now with Talk, Blog, Me, and did not work, There is no temporal file that Zeronet.exe or Tor.exe creates?.

**Comment by HelloZeroNet** [comment]
Everything is stored in data folder, so you can do this:
 - Stop ZeroNet client
 - Rename data to data-old
 - Start ZeroNet client again and try to visit sites that you had problems before

If it's got fixed, then you can try to rename back your data directory and move data/content.db to data/content.db-old to re-generate that cache file.

**Comment by Pupiloho** [comment]
Doesn't work, I had a firewall enabled, i disabled it but still persist, also reset the pc, still, cleaned files with C
Cclenaer, same... I don't know what is happening, the error still persist on all pages.
![sin titulo](https://user-images.githubusercontent.com/8495728/27018439-99146322-4efe-11e7-817e-42526af48c24.png)

**Comment by HelloZeroNet** [comment]
Can you please send me (tamas@zeronet.io) or attach your data/1BLogC9LN4oPDcruNz3qo1ysa133E9AGg8/data/zeroblog.db file?

**Comment by Pupiloho** [comment]
Here is it

[zeroblog.zip](https://github.com/HelloZeroNet/ZeroNet/files/1073054/zeroblog.zip)

**Comment by HelloZeroNet** [comment]
Thanks, but unfortunetly it's empty, can you please also send the .db from 1Talk... directory?

**Comment by Pupiloho** [comment]
Again, i send you the one from Gif forum to see if there is data 
[zerotalk.zip](https://github.com/HelloZeroNet/ZeroNet/files/1076299/zerotalk.zip)
[zeroblog.zip](https://github.com/HelloZeroNet/ZeroNet/files/1076307/zeroblog.zip)

**Comment by HelloZeroNet** [comment]
Thanks, I was able to reproduce and fix it latest rev. Please update and press "Rebuild" button on sidebar. https://github.com/HelloZeroNet/ZeroNet/commit/97b3563e6b4e88eba6ac338a52981806297823fc

**Comment by Pupiloho** [comment]
¡Excellent!, the issue is fixed, thank you, you are awesome, love this project, keep on.
