### ISSUE TITLE
Err: ValueError: Invalid control character at: line 4886 column 20

### ISSUE THREAD

**Issue by MercuryhgJiang** [HelloZeroNet/ZeroNet#973]
Server error

Err: ValueError: Invalid control character at: line 4886 column 20 (char 352129) in UiServer.py line 83 > UiRequest.py line 83 > MutePlugin.py line 153 > UiRequest.py line 223 > SiteManagerPlugin.py line 64 > SiteManager.py line 132 > Site.py line 56 > Site.py line 80 > __init__.py line 291 > __init__.py line 339 > decoder.py line 364 > decoder.py line 380

Please report it if you think this an error.

Details:

{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate, sdch", 
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_HOST": "10.102.4.1:43110", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36", 
    "PATH_INFO": "/yangleitj.bit/", 
    "QUERY_STRING": "Post:18:yourname.com%E7%BB%91%E5%AE%9Ayourname.bit", 
    "REMOTE_ADDR": "10.102.4.240", 
    "REMOTE_PORT": "51844", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "ZBT-WE1326", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.2 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": true, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "en", 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": null, 
        "optional_limit": "10%", 
        "proxy": null, 
        "size_limit": 10, 
        "stack_size": 32768, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_ip": "10.102.4.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.2.1", 
    "version_python": "2.7.13 (default, May 30 2017, 21:05:50) \n[GCC 5.4.0]", 
    "version_zeronet": "0.5.5 r2099", 
    "wsgi.url_scheme": "http"
}

**Comment by HelloZeroNet** [comment]
Looks like your data/sites.json file is broken at line 4886 (character 20)

If you have data/sites.json-tmpold or data/sites.json-tmpnew file, then after you shut down your ZeroNet client you can try to overwrite with it
