### ISSUE TITLE
cert_auth_id is not tested during first sign

### ISSUE THREAD

**Issue by imachug** [HelloZeroNet/ZeroNet#983]
```python
# ContentManager.py
try:
    if not content:
        content = self.site.storage.loadJson(inner_path)  # Read the file if no content specified
    user_urn = "%s/%s" % (content["cert_auth_type"], content["cert_user_id"])  # web/nofish@zeroid.bit
    cert_user_id = content["cert_user_id"]
except Exception:  # Content.json not exist
    user_urn = "n-a/n-a"
    cert_user_id = "n-a"
```

If default file size is `0` , and file size for `nofish@zeroid.bit` is `100000`, then nobody can sign. That's because if there is no `content.json`, user id is tested against `n-a/n-a@n-a`.

Probably we can change `except` block to get current ZeroID (or other cert provider).

**Comment by HelloZeroNet** [comment]
Can you please add more details on reproducing it?
I just tried and this works for me (cloned zerosites, modified data/users/content.json to this, then added a new site):
```
...
 "user_contents": {
  "cert_signers": {
   "zeroid.bit": ["1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz"]
  },
  "permission_rules": {
   ".*": {
    "files_allowed": "data.json",
    "max_size": 0,
    "signers": []
   },
   "bitid/.*@zeroid.bit": {"max_size": 20000}
  },
  "permissions": {
   "nofish@zeroid.bit": {"max_size": 200000}
  }
 }
...
```

**Comment by imachug** [comment]
1. Press `Create new, empty site` in ZeroHello
2. Create `data/users/content.json` with the following content:
```javascript
{
  "files": {},
  "ignore": ".*",
  "modified": 0.0,
  "signs": {},
  "user_contents": {
    "cert_signers": {
      "zeroid.bit": [ "1iD5ZQJMNXu43w1qLB8sfdHVKppVMduGz" ]
    },
    "permission_rules": {
      ".*": {
        "files_allowed": "data.json",
        "max_size": 0
      }
    },
    "permissions": {
      "nofish@zeroid.bit": { "max_size": 100000 }
    }
  }
}
```
3. Add `include` and `ignore` to root `content.json`:
```javascript
...
    "ignore": "data/.*",
    "includes": {
        "data/users/content.json": {
            "signers": [],
            "signers_required": 1
        }
    },
...
```
4. Sign `content.json` and then `data/users/content.json`
5. Login to ZeroID using sidebar (`Unique address` -> `Change` -> `nofish@zeroid.bit`)
6. Try to sign `data/users/1J3rJ8ecnwH2EPYa6MrgZttBNc61ACFiCj/content.json` using sidebar

Signing fails because there is no `content.json`, and `n-a/n-a@n-a` is used as `cert_user_id` instead

**Comment by HelloZeroNet** [comment]
Thanks I was able to reproduce the problem.
It's happening because when you using the sidebar to sign the content it executes:
`wrapper.ws.cmd("siteSign", {"privatekey":"stored","inner_path":"data/users/1J3rJ8ecnwH2EPYa6MrgZttBNc61ACFiCj/content.json"})`
So it's using the site's private key and not the user's. In that case it does not adds user details to the content.json. Executing `wrapper.ws.cmd("siteSign", {"inner_path":"data/users/1J3rJ8ecnwH2EPYa6MrgZttBNc61ACFiCj/content.json"})` command does works.

**Comment by imachug** [comment]
Thanks!
