### ISSUE TITLE
Won't learn allowed host at public proxy

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroNet#986]
ZeroNet add a ui_host restriction in a recent update, if `ui_ip` is not `127.0.0.1`, ZeroNet will also add the first http request's host to the allowed host list.
In actual use, set `ui_ip = * ` to allow users access on internet is not suitable, we need a reverse proxy to set HTTPS and gzip compression and don't allow access ZeroNet directly. It causes ZeroNet won't learn allowed host.
We can set `ui_host` by command line and edit `zeronet.conf`, but it seems can't set multi value in `zeronet.conf`.

**Comment by HelloZeroNet** [comment]
What's the error message when you try to access the ui interface and what host it added by the first request? (please search for "as allowed host" in log/debug.log)


This format should work in zeronet.conf
```
ui_host =
 host1
 host2
```

**Comment by l5h5t7** [comment]
When I access UI interface, `INFO     Ui.UiServer Added 127.0.0.1:43110 as allowed host` is in log/debug.log. So I think that "learn allowed host" should ignore "127.0.0.1:43110". And if Multiuser plugins enabled or ui_ip is not `127.0.0.1`, learn allowed host.
OS: Windows Server 2012 R2 Standard
Browser: Firefox 52.2.0 ESR
When I open ZeroNet, a ZeroHello page opens.
This format in `zeronet.conf` works well.

**Comment by tangdou1** [comment]
It can be closed.
