### ISSUE TITLE
Undocumented command "handshake"

### ISSUE THREAD

**Issue by mkg20001** [HelloZeroNet/ZeroNet#987]
The network command handshake is completely missing from the docs at https://zeronet.readthedocs.io/en/latest/help_zeronet/network_protocol/
Could there be some more documentation?

```
{ cmd: 'handshake',
  params: 
   { target_ip: '217.234.60.22',
     version: '0.5.6',
     protocol: 'v2',
     crypt: null,
     fileserver_port: 15441,
     port_opened: false,
     peer_id: '-ZN0056-Ap3jwnKJHrCy',
     rev: 2109,
     crypt_supported: [ 'tls-rsa' ] },
  req_id: 0 }
}
```

**Comment by mkg20001** [comment]
Also getHashfield, setHashfield and listModified are undocumented

**Comment by HelloZeroNet** [comment]
Nice to hear! :)
I have added the handshake and the missing network commands to documentation: https://zeronet.readthedocs.io/en/latest/help_zeronet/network_protocol/

**Comment by mkg20001** [comment]
The handshake command doc is missing the details about the "crypto" variable.
Usually the response includes the crypto both clients support (as seen in live traffic).
Also the onion variable seems optional.
At least afaik. But I have seen that behavior in live traffic too.

**Comment by mkg20001** [comment]
...and it completely leaves out the fact about wrapping the socket afterwards and that the handshake is optional (afaik the client responds to requests even if no handshake was sent, if that is a feature)

Could you please document that behavior too?

**Comment by mkg20001** [comment]
I have created a pr (#58) but I'm unsure if everything is correct.
