### ISSUE TITLE
Why ZeroNet zites don't surport Chinese file name ?

### ISSUE THREAD

**Issue by funny110** [HelloZeroNet/ZeroNet#990]
Put a Chinese  named file to blog, click it, show error.

**Comment by HelloZeroNet** [comment]
Various file systems/applications could have problems with utf8 file names in url/fs. If you really need special characters I recommend using the archive feature that support utf8 filenames:
http://127.0.0.1:43110/blog.zeronetwork.bit/?Post:105:New+version+0.5.3
