### ISSUE TITLE
Don't update to Rev2124, on ZeroUpdate.bit ! ! !

### ISSUE THREAD

**Issue by funny110** [HelloZeroNet/ZeroNet#991]
![default](https://user-images.githubusercontent.com/28748344/27466283-0ea3304e-580c-11e7-8022-a79c1bb09ad5.PNG)

Can't open ZeroNet Client.
win10 x64

**Comment by HelloZeroNet** [comment]
Thanks for reporting, just fixed it, it contained an invalid zeronet.py file.
To fix it manually please overwrite the `core/zeronet.py` file with this: https://raw.githubusercontent.com/HelloZeroNet/ZeroNet/master/zeronet.py
