### ISSUE TITLE
Content.json Download Failed

### ISSUE THREAD

**Issue by WonderingDane** [HelloZeroNet/ZeroNet#992]
I've been using ZeroNet for some time now, but after a reinstall of Windows, ZeroNet suddenly won't work. I just get the error "CONTENT.JSON DOWNLOAD FAILED" and then nothing happens.

Nothing have really changed on my system. Even my ISP and router is the same.

Using Windows 10, but the same issue is present on my Linux machine. Thinking it must have something to do with my internet?

**Log**
[https://hastebin.com/kegosomepi.rb](https://hastebin.com/kegosomepi.rb)

**Benchmark**
[https://hastebin.com/voyukevomi.css](https://hastebin.com/voyukevomi.css)

**Comment by skwerlman** [comment]
what address is failing? usually that message indicates a lack of peers, but if it's happening for well-seeded zites, it might be an internet issue.
