### ISSUE TITLE
The state of Zeronet security

### ISSUE THREAD

**Issue by HulaHoopWhonix** [HelloZeroNet/ZeroNet#993]
I was very excited about Zeronet until I read this: https://news.ycombinator.com/item?id=14041077 

As a security/privacy distro integrator I really care about the safety of the underlying cryptolibs. We recommend tools for people in potentially life-threatening situations. Using outdated code (by a couple of years) that has known vulnerablities just doesn't cut it. I was sad to see these problems brushed off and shut down by the core devs. If you want to avoid breakage while maintaining security than I advise you to develop on Debian stable where security fixes are backported while avoiding unstable code churn. Its also good for code reproducibility which will be a requirement in Debian stable-next.

***

The second point is not really your fault but its smart to avoid. Namecoin hashing power has sunk to a level where a single miner is dominating it. Domain squatting is becoming a serious problem. I recommend moving to a Tor related solution for human memorable and secure addresses still under development.

https://github.com/Jesse-V/OnioNS-client

cc/ @adrelanos

**Comment by MuxZeroNet** [comment]
As far as I know, ZeroNet is using these inactive cryptolibs.

- [BitcoinECC](https://github.com/HurlSly/BitcoinECCPython), removal is _in progress_ as it is only used by the outdated ZeroBoard site.
- [PyElliptic](https://github.com/yann2192/pyelliptic/issues/50#issuecomment-297018932), deprecated, a fork by @PeterSurda is used in ZeroNet.

These libraries are OpenSSL bindings:
- PyElliptic fork
- [opensslVerify](https://github.com/Bitmessage/PyBitmessage/blob/master/src/pyelliptic/openssl.py), borrowed from Bitmessage

These features use OpenSSL:
- Bitcoin signature verifying (correct me if I am wrong)
- ECIES encryption of ZeroMail (from PyElliptic)
- AES encryption API ([unauthenticated](https://github.com/HelloZeroNet/ZeroNet/issues/412)!!)

These features should be done in OpenSSL for better performance and better security.
- Python-RSA, [not in constant time](https://github.com/HelloZeroNet/ZeroNet/issues/566), currently only used for verification purposes, proving the ownership of .onion addresses.


\#UseProper[Cryptography](https://cryptography.io)
\#MakeZeroNetUpToDateAgain

**Comment by PeterSurda** [comment]
@MuxZeroNet PyEliptic is merely a middle layer, it uses ctypes to load OpenSSL, which does all the crypto.

**Comment by abueide** [comment]
Ethereum Name Service might also be a viable alternative for decentralized DNS

**Comment by Plasmmer** [comment]
A good security idea for the sites is using a three like Git, like IPFS does.

**Comment by Plasmmer** [comment]
https://github.com/HelloZeroNet/ZeroNet/issues/1016
