### ISSUE TITLE
Wrapper nonce error. Please reload the page.

### ISSUE THREAD

**Issue by Lucas-Developer** [HelloZeroNet/ZeroNet#994]
**What is it?**

`{
    "GATEWAY_INTERFACE": "CGI/1.1", 
    "HTTP_ACCEPT": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
    "HTTP_ACCEPT_ENCODING": "gzip, deflate", 
    "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.5", 
    "HTTP_CONNECTION": "keep-alive", 
    "HTTP_DNT": "1", 
    "HTTP_HOST": "127.0.0.1:43110", 
    "HTTP_REFERER": "http://127.0.0.1:43110/16HCPUcNXDSthnLgvmnhWUVGKweWoKLDWh/", 
    "HTTP_UPGRADE_INSECURE_REQUESTS": "1", 
    "HTTP_USER_AGENT": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0", 
    "PATH_INFO": "/16HCPUcNXDSthnLgvmnhWUVGKweWoKLDWh/", 
    "QUERY_STRING": "wrapper_nonce=75dc825a674d26b517b471a99e4dedb1e913a14e7543ee0365038e3540e30538", 
    "REMOTE_ADDR": "127.0.0.1", 
    "REMOTE_PORT": "49496", 
    "REQUEST_METHOD": "GET", 
    "SCRIPT_NAME": "", 
    "SERVER_NAME": "localhost", 
    "SERVER_PORT": "43110", 
    "SERVER_PROTOCOL": "HTTP/1.1", 
    "SERVER_SOFTWARE": "gevent/1.0 Python/2.7", 
    "arguments": {
        "action": "main", 
        "batch": false, 
        "bind": null, 
        "bit_resolver": "1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F", 
        "coffeescript_compiler": null, 
        "config_file": "zeronet.conf", 
        "connected_limit": 8, 
        "data_dir": "data", 
        "db_mode": "speed", 
        "debug": false, 
        "debug_gevent": false, 
        "debug_socket": false, 
        "disable_db": false, 
        "disable_encryption": false, 
        "disable_sslcompression": true, 
        "disable_udp": false, 
        "end": true, 
        "file_size_limit": 10, 
        "fileserver_ip": "*", 
        "fileserver_port": 15441, 
        "fix_float_decimals": false, 
        "homepage": "1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D", 
        "ip_external": null, 
        "ip_local": [
            "127.0.0.1"
        ], 
        "keep_ssl_cert": false, 
        "language": "pt", 
        "log_dir": "log", 
        "max_files_opened": 2048, 
        "msgpack_purepython": true, 
        "open_browser": "default_browser", 
        "optional_limit": "10%", 
        "proxy": null, 
        "silent": false, 
        "size_limit": 10, 
        "stack_size": null, 
        "stream_downloads": false, 
        "tor": "enable", 
        "tor_controller": "127.0.0.1:9051", 
        "tor_hs_limit": 10, 
        "tor_proxy": "127.0.0.1:9050", 
        "trackers": [
            "zero://boot3rdez4rzn36x.onion:15441", 
            "zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441", 
            "udp://tracker.coppersurfer.tk:6969", 
            "udp://tracker.leechers-paradise.org:6969", 
            "udp://9.rarbg.com:2710", 
            "http://tracker.opentrackr.org:1337/announce", 
            "http://explodie.org:6969/announce", 
            "http://tracker1.wasabii.com.tw:6969/announce"
        ], 
        "trackers_file": false, 
        "ui_host": null, 
        "ui_ip": "127.0.0.1", 
        "ui_port": 43110, 
        "ui_restrict": false, 
        "updatesite": "1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp", 
        "use_openssl": true, 
        "use_tempfiles": false, 
        "verbose": false, 
        "workers": 5
    }, 
    "plugins": [
        "AnnounceZero", 
        "CryptMessage", 
        "FilePack", 
        "MergerSite", 
        "Mute", 
        "Newsfeed", 
        "OptionalManager", 
        "PeerDb", 
        "Sidebar", 
        "Stats", 
        "TranslateSite", 
        "Trayicon", 
        "Zeroname"
    ], 
    "version_gevent": "1.0.2", 
    "version_python": "2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]", 
    "version_zeronet": "0.5.6 r2125", 
    "wsgi.url_scheme": "http"
}`

**Comment by MuxZeroNet** [comment]
To make the sandbox hard to escape, there will always be a nonce in the query string of the inner `<iframe>`. The nonce will appear invalid if you try to reload the inner `<iframe>`. If you see this, hit the reload button on the browser address bar.

**Comment by Lucas-Developer** [comment]
thank you
