### ISSUE TITLE
Ability to return 'raw' index.html files

### ISSUE THREAD

**Issue by ohboyiloveyou** [HelloZeroNet/ZeroNet#997]
Hello there, currently writing an application that parses websites hosted on ZeroNet.

When one requests a website on ZeroNet, such as:

http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D

it grabs the index.html content and wraps it in an iframe.

At this point any application trying to resolve `http://127.0.0.1:43110/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/index.html` runs into the following issues:

* Receives a 403 forbidden error due to missing nonce - this is only required for the index.html site, not other files on the site
* Even with the correct nonce, included source code is just the ZeroNet wrapper code, no actual site HTML.

Is it possible to add a feature to ZeroNet to download raw index.html's, for easier inter-operability with other services? Something like:

http://127.0.0.1:43110/raw/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D

that could just return the raw index.html file would be great.

Thanks!

**Comment by mkg20001** [comment]
I think that would be a security issue.
That's why there is a wrapper.
But a workaround would be to only allow loading the /raw from an ajax request.

**Comment by ohboyiloveyou** [comment]
@mkg20001 I don't believe so, as other files as served quite happily as downloads directly to the browser.

I'm not sure if we can differentiate between a `wget` GET request to that URL and a browser request, but then again it shouldn't be a problem.

All we would need to do is present the content in a similar manner to have GitHub does so with it's raw feature: https://raw.githubusercontent.com/HelloZeroNet/zeronet.io/master/index.html

This way no javascript on the page is executed, and there's no other stuff on the page that can confuse application parsers.

**Comment by ohboyiloveyou** [comment]
I took a look at the code for the Stats plugin since it already has the functionality of returning data upon a request to `127.0.0.1:43110/xxxx`.

While it wasn't immediately where the code that defined this entry point lived... @HelloZeroNet would writing a plugin for this functionality be overkill compared to just including it in the client? Are there any other `127.0.0.1:43110/xxx` addresses that are available already or is the `/Stats` page just a special feature?

**Comment by ohboyiloveyou** [comment]
I took a look at the code for the Stats plugin since it already has the functionality of returning data upon a request to `127.0.0.1:43110/xxxx`.

It wasn't immediately clear where the code that defined this entry point lived... @HelloZeroNet would writing a plugin for this functionality be overkill compared to just including it in the client? Are there any other `127.0.0.1:43110/xxx` addresses that are available already or is the `/Stats` page just a special feature?

**Comment by HelloZeroNet** [comment]
The wrapper is required because all sites served from same domain (127.0.0.1 normally) and without it would would allow cross site scripting.
If you want to read the raw files I recommend directly open it from file system. If you want to render the site I recommend using PhantomJS (http://phantomjs.org/) than can also render javascript based ZeroNet sites.

**Comment by MuxZeroNet** [comment]
`<a href="http://127.0.0.1:43110/raw/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D/evil.html" target="_top">Stupid mankind</a>`

**Comment by ohboyiloveyou** [comment]
@HelloZeroNet @MuxZeroNet Good points, I can see how it could be a security issue now.

And @HelloZeroNet wow, that definitely does work! I guess I still need to adjust to the p2p mindset :)
