### ISSUE TITLE
Can't download android APK

### ISSUE THREAD

**Issue by funny110** [HelloZeroNet/ZeroNet#998]
Android mobile open https://zeronet.io  can't download zeronet APK. click download no response.

**Comment by ohboyiloveyou** [comment]
Same here, this seems to be due to the following GitHub URL resolving to a 404:

https://api.github.com/repos/HelloZeroNet/ZeroNet-kivy/releases/latest

ZeroNet-kivy obviously still has releases available, so this may be a temporary GitHub issue, rather than ZeroNet's.

**Comment by HelloZeroNet** [comment]
Yes, looks like it's github issue. It returns not found also for the example in the official document:
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
https://api.github.com/repos/octocat/Hello-World/releases/1

**Comment by HelloZeroNet** [comment]
Update: https://api.github.com/repos/HelloZeroNet/ZeroNet-kivy/releases still works, changed!
